### ISSUE TITLE
Support for ingress annotation for "x-envoy-retry-grpc-on"

### ISSUE THREAD

**Issue by swapnil1988** [projectcontour/contour#1041]
**Describe the solution you'd like**
Currently there is support for "contour.heptio.com/retry-on" Ingress annotation that maps to Envoy's [x-envoy-retry-on ](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/router_filter.html#x-envoy-retry-on) , This request is to make a provision in contour to support new ingress annotations for [x-envoy-retry-grpc-on](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/router_filter.html#x-envoy-retry-grpc-on)

**Environment:**

- Contour version: v0.10.0
- Kubernetes version: (use `kubectl version`): 1.11
- Kubernetes installer & version: Kubeadm 1.11
- Cloud provider or hardware configuration: BareMetal

**Comment by davecheney** [comment]
Thank you for raising this issue. Before we jump to the implementation can I ask you to step back and describe the problem you are having. What is so magically about grpc that it needs its on retry logic, can we just roll that into the general retry support we're adding in 0.12? #815

**Comment by swapnil1988** [comment]
We have a special case where each gRPC upstream pod of the service supports only one concurrent rpc call. Here what we are trying to achieve is add retry logic if the upstream gRPC pod returns a "resource-exhausted" status code. Ideally we would have liked to couple it with max-request = 1 per upstream pod but that is not supported by Envoy.

**Comment by davecheney** [comment]
Thank you for your response. It sounds like you have two issues.

1. You need to limit upstream concurrency to one.
2. You would like to retry a request, but only on certain conditions

Is that correct?

**Comment by swapnil1988** [comment]
Yes you are correct

**Comment by michmike** [comment]
is this issue still relevant?
OP, would header re-write, a feature in contour 1.2 enable you to solve this scenario?
we encourage you to attend the community meeting for contour to discuss your scenario.

**Comment by michmike** [comment]
i am closing this issue. please reopen if it can't be solved using the header re-write or if this issue is still occuring for you

**Comment by jpeach** [comment]
@swapnil1988 You can set these headers on the the request using the `requestHeadersPolicy` o the route. Let us know how it goes.
