### ISSUE TITLE
Route Name feature

### ISSUE THREAD

**Issue by drao9** [projectcontour/contour#1121]
Recently, I worked on a feature to add route name in envoy's http route.Route structure. Here is the link for this issue: https://github.com/envoyproxy/envoy/issues/6364
I was wondering if the community would be interested in having route name field in ingressroute as a part of the route struct to support the feature in envoy. I can make the necessary changes for this.

**Comment by davecheney** [comment]
Thank you for raising this issue. If I understand the linked feature request correctly this is for reporting stats. If Envoy grows this feature I think we could enable it in contour in the same way we name clusters currently; a predictable, but not configurable, value.

**Comment by drao9** [comment]
Yes, the envoy community is considering having stats per-route with the help of route name. Thanks!

**Comment by davecheney** [comment]
Moving to the unplanned release as it is not clean when this feature will be delivered upstream.
