### ISSUE TITLE
Envoy should output CLF access logs by default

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1124]
Currently we configure Envoy to http access logs to `/dev/stdout`. Because we do not specify any logging format,[Envoy's default format](https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log#config-access-log-default-format) is chosen for us.

This is not ideal for two reasons

1. The format is not from [CLF](https://en.wikipedia.org/wiki/Common_Log_Format) which is emitted by competitors like nginx and apache. CLF is a well understood format that is handled natively by most log aggregation platforms.
2. Because the default format is not CLF, the requirement for end users to write their own parser for Envoy's default format drives them towards other solutions like JSON logging. See #624 and #1080 for discussion on JSON logging as an option, or default.

Putting aside #624 we _should_ change to emitting CLF. There is no reason to use Envoy's format and hopefully by offering CLF as a default we can lessen the calls for changing the logging to something else that is easier (than Envoy's default format) for log aggregation platforms to ingest.

**Comment by asenchi** [comment]
@davecheney TBH, it makes little to no difference that I can see. Both Envoy's log format and CLF require me to configure a parser to slurp and forward structured logs, neither provide any particular benefit for me as an operator.

The reason why JSON is so desirable (reading through #624 and #0180) is that they are more flexible from the parsing standpoint. I don't have to know what all the fields are, or even limit what is shipped with each message. In fact I can add onto that message without breaking my parser down the road from where the log message is managed. This is the primary reason JSON logging structure has risen in popularity.

I'm down with the idea of making this pretty straight forward and not allowing a billion ways to configure logs, that is definitely a valuable goal and provides a much better experience when managing Contour. However, when it comes down to logging, I see very little benefit in putting time into CLF compared to Envoy's format given the fact that both require my time to parse via a regex in Fluentbit ([example of a parser.conf](https://github.com/fluent/fluent-bit/blob/master/conf/parsers.conf).)

**Comment by stevesloka** [comment]
I agree with @asenchi  that a json format would be easier to manage and like the idea of that format changing over time and not breaking consumers of the logs.

**Comment by davecheney** [comment]
@asenchi thanks for your reply. The discussion has moved back to #624 but the TL;DR is, we're not going to do JSON today, but that doesn't mean we won't do it in the future. See https://github.com/heptio/contour/issues/624#issuecomment-497202378 for details.

However, CLF is something I should have done a long time ago, the unique Envoy format helps nobody and it is, somewhat worryingly, only now after a dozen releases that people are complaining about it that makes me think the output from envoy is so useless people are ignoring it entirely. Perhaps things aren't as bad as I fear, but I don't think there is any reasonable justification for not switching to CLF irrespective of #624

**Comment by asenchi** [comment]
@davecheney Sounds good, thanks for your work!

**Comment by davecheney** [comment]
So I put some time into this yesterday and discovered that explicitly passing an access log format for the _same_ value as the default that Envoy applies if we do not give any configuration -- a noop change -- caused no logs to be printed.
```diff
+++ b/internal/envoy/accesslog.go
@@ -21,12 +21,21 @@ import (
 
 // FileAccessLog returns a new file based access log filter.
 func FileAccessLog(path string) []*accesslog.AccessLog {
+
+       // Envoy's default log format. See https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log#default-format-string
+       const ENVOY_DEFAULT_FORMAT = `[%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" ` +
+               `%RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% ` +
+               `%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" ` +
+               `"%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"\n`
+
        return []*accesslog.AccessLog{{
                Name: util.FileAccessLog,
                ConfigType: &accesslog.AccessLog_TypedConfig{
                        TypedConfig: any(&accesslogv2.FileAccessLog{
                                Path: path,
-                               // TODO(dfc) FileAccessLog_Format elided.
+                               AccessLogFormat: &accesslogv2.FileAccessLog_Format{
+                                       Format: ENVOY_DEFAULT_FORMAT,
+                               },
                        }),
                },
        }}
```
This puts this change outside the trivial and into the "great, now I have to figure out why envoy goes mum when I supply a custom log formatter". I'm going to push this to 0.14.

**Comment by davecheney** [comment]
I'm sorry this didn't make it for 0.14. The plumbing for this will land in #1130, we'll add logging configuration to the config.json file in 0.15

**Comment by youngnick** [comment]
I've spent some time investigating this, here's what I've found:

- @davecheney is correct - if you pass a format (any format, from what I can see) to Envoy, you get no logs. There are no other issues about this in Envoy's issue tracker, so I suspect we've got something wrong.
- Looking into CLF logs, however, it seems that Envoy can't output them correctly anyway - the timestamp format doesn't match the CLF one, and three of the CLF fields are not output by Envoy (well, at least not easily).
- Lastly, Envoy's default format includes a fair bit of probably useful information (request IDs, etc), that CLF elides.

I'm going to call this one a no-go and update documentation and options etc so that our two options for `accesslog-format` are `envoy` or `json`. That will close out this issue.

**Comment by davecheney** [comment]
@youngnick sounds good to me.

**Comment by youngnick** [comment]
The issue with logs not appearing is due to the escaping of the newline at the end of the format string; this means that the output log buffer is never flushed. https://github.com/envoyproxy/envoy/issues/5193 has more details about the efforts to fix this problem, looks like it's reasonably common.

**Comment by youngnick** [comment]
We're leaving this one here, in case we want to come back to CLF later.

**Comment by michmike** [comment]
we do have json logging now and this mitigates the need for this ticket. closing due to lack of priority
