### ISSUE TITLE
Add docs on how to use CertManager with HTTPProxy

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1140]
**Describe the solution you'd like**
Docs exist today on how to setup CertManager to create Let's Encrypt certificates with Kubernetes Ingress resources. It would be great to also demonstrate how to accomplish this with IngressRoute objects. 

We cannot use annotations with this style, however, we can create Cert Manager "Certificate" CRD's to also let CertManager help with the certificate request flow.

**Comment by vongohren** [comment]
Is this coming :D ?

**Comment by SDBrett** [comment]
Is this still relevant with v1.0 and moving away from IngressRoute?

**Comment by davecheney** [comment]
@youngnick could you please provide an update. Thank you

**Comment by youngnick** [comment]
Sorry, this is on my list for today. I've also updated the title to make it clear it will be about HTTPProxy, although you could generalise to IngressRoute.

**Comment by davecheney** [comment]
@shabx this issue was closed 22 days ago. Please open a new issue to hold ZD4657

**Comment by davecheney** [comment]
@shabx it looks like ZD4657 is resolved. No action required.
