### ISSUE TITLE
design: e2e/integration test rig

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1155]
**Describe the solution you'd like**
Contour currently has standard unit tests as well as some e2e tests that test the configuration that gets passed to Envoy, however, there aren't any full integration tests which spin up an instance of Contour & Envoy. 

The purpose of this issue is to gather a list of use-cases / tests to decide if the effort to build/maintain a full e2e test suite shows us value.

**Comment by davecheney** [comment]
Thank you for raising this issue. 

The driving reason I have wanted to be able to test a contour and envoy stack from end to end; that is configure envoy via contour and then send a request through envoy to verify it is correctly configured. Said another way, our `internal/e2e` tests give me good confidence that we can translate a k8s object to a syntactically valid set of messages to Envoy. What the`internal/e2e` tests do not let me do at the moment is know with confidence that a particular pattern we've expressed to Envoy works how we think, and also if the configuration we generated yesterday still operates as we expect when Envoy is upgraded.

An example of this this might be validating that session affinity correctly routes requests as configured.

**Comment by davecheney** [comment]
Ping @youngnick . Please roll this into your issue when you write up your plan for an e2e test cluster.

**Comment by youngnick** [comment]
I've taken this issue for now to cover writing up a design for an e2e/integration test rig for Contour.

**Comment by skriss** [comment]
Closing this one out as we've got E2E tests in place.
