### ISSUE TITLE
Contour/Envoy should preserve the remote ip address whenever possible

### ISSUE THREAD

**Issue by rjbez17** [projectcontour/contour#1182]
**Describe the solution you'd like**
Contour/envoy should inject the X-Forwarded-For header whenever possible. Right now it currently only injects this header when configured with a cloud provider proxy. 

My use case is that some third party services I deploy expect the remote IP exposed via the X-Forwarded-For header when behind an LB. It would also be helpful to have the remote IP exposed to backend services in general. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Deploying httpbin behind contour, I get the following headers:

```
"headers": {
    "Accept": "*/*", 
    "Content-Length": "0", 
    "Host": "httpbin.srv.home", 
    "User-Agent": "curl/7.54.0", 
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000", 
    "X-Envoy-Internal": "true"
  }
```

**Environment:**

- Contour version: v0.13.0-beta.1
- Kubernetes version: (use `kubectl version`): v1.14.3
- Kubernetes installer & version: kubeadm v1.14.3
- Cloud provider or hardware configuration: baremetal (Intel NUCs)
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04.6 LTS
- Load Balancer: Metal LB v0.7.3

**Comment by davecheney** [comment]
Thanks for raising this issue, it is very clear what needs to happen.

I am tentatively marking this as p2 for the 0.14 cycle. At the moment I don't know if anyone has bandwidth to work on this so it may slip to 0.15.

There is some good documentation here, https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers#x-forwarded-for and we may already be setting the correct header, https://github.com/heptio/contour/blob/master/internal/envoy/listener.go#L122. Some investigation on why this setting is not correct may be needed.

**Comment by rjbez17** [comment]
@davecheney I did some digging and noticed that no listeners are actually being set in the envoy configs, I'll do some more looking around the bootstrap process that generates it:

```
{
  "static_resources": {
    "clusters": [
      {
        "name": "contour",
        "alt_stat_name": "heptio-contour_contour_8001",
        "type": "STRICT_DNS",
        "connect_timeout": "5s",
        "load_assignment": {
          "cluster_name": "contour",
          "endpoints": [
            {
              "lb_endpoints": [
                {
                  "endpoint": {
                    "address": {
                      "socket_address": {
                        "address": "127.0.0.1",
                        "port_value": 8001
                      }
                    }
                  }
                }
              ]
            }
          ]
        },
        "circuit_breakers": {
          "thresholds": [
            {
              "priority": "HIGH",
              "max_connections": 100000,
              "max_pending_requests": 100000,
              "max_requests": 60000000,
              "max_retries": 50
            },
            {
              "max_connections": 100000,
              "max_pending_requests": 100000,
              "max_requests": 60000000,
              "max_retries": 50
            }
          ]
        },
        "http2_protocol_options": {}
      },
      {
        "name": "service-stats",
        "alt_stat_name": "heptio-contour_service-stats_9001",
        "type": "LOGICAL_DNS",
        "connect_timeout": "0.250s",
        "load_assignment": {
          "cluster_name": "service-stats",
          "endpoints": [
            {
              "lb_endpoints": [
                {
                  "endpoint": {
                    "address": {
                      "socket_address": {
                        "address": "127.0.0.1",
                        "port_value": 9001
                      }
                    }
                  }
                }
              ]
            }
          ]
        }
      }
    ]
  },
  "dynamic_resources": {
    "lds_config": {
      "api_config_source": {
        "api_type": "GRPC",
        "grpc_services": [
          {
            "envoy_grpc": {
              "cluster_name": "contour"
            }
          }
        ]
      }
    },
    "cds_config": {
      "api_config_source": {
        "api_type": "GRPC",
        "grpc_services": [
          {
            "envoy_grpc": {
              "cluster_name": "contour"
            }
          }
        ]
      }
    }
  },
  "admin": {
    "access_log_path": "/dev/null",
    "address": {
      "socket_address": {
        "address": "127.0.0.1",
        "port_value": 9001
      }
    }
  }
}
```

**Comment by davecheney** [comment]
@rjbez17 thanks for your investigation. Listeners are only generated when the is an ingress or ingressroute record that references them. #389

**Comment by davecheney** [comment]
I'm sorry to report that no work has been done on this issue in 0.14. Bumping to 0.15

**Comment by stevesloka** [comment]
Hey @rjbez17, I double-checked and like @davecheney mentioned, we're setting the flag in Envoy to have it automatically add the XFF header. 

I'm curious, since you're not seeing the header, how your environment is deployed? You mentioned some nuc's with kubeadm, but how are you driving traffic to Contour (i.e. Envoy?). Are you just hitting a node port on a static node or using something else to configure load balancing internal to your network?

**Comment by rjbez17** [comment]
@stevesloka I'm using a LoadBalancer service in from of contour to get an external IP (from metallb):

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8000"
    prometheus.io/scrape: "true"
  name: contour
  namespace: heptio-contour
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.1.53
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: contour
  sessionAffinity: None
  type: LoadBalancer
```

Then I use an IngressRoute to route my clusterip service (httpbin in this example):

```
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: httpbin
spec:
  routes:
  - match: /
    services:
    - name: httpbin
      port: 80
  virtualhost:
    fqdn: httpbin.srv.home
```

I think the issue is, contour is never actually creating an listener in the envoy config. You see in my envoy config above (https://github.com/heptio/contour/issues/1182#issuecomment-504016390), there is no listener section. So I guess the question is, why isn't the listener section being generated/used? Did I miss something in the docs?

**Comment by stevesloka** [comment]
@rjbez17 That IngressRoute looks ok to me. Are there any errors in Contour's log? Like it can watch errors for Ingress resources or something?

**Comment by rjbez17** [comment]
@stevesloka  I didn't see any errors pop out in either contour and envoy containers. I'm going to try and reproduce on a single node tonight with only essential services. See if I can see any logs. I did however, see logs indicating that it was creating an http listener but didn't seen any created in the envoy config.

**Comment by rjbez17** [comment]
@stevesloka  I've been unable to find any errors in the logs, and the routing actually works, I just don't have the listner in the config. Here is a dump of all logs with debug mode on via:

`k logs deployment/contour -n heptio-contour --all-containers > contour.log `

[contour.log](https://github.com/heptio/contour/files/3556062/contour.log)

**Comment by davecheney** [comment]
@rjbez17 could you please update me on the status of this issue. Would you be able to summarise the current state of play for me? Thank you.

**Comment by rjbez17** [comment]
@davecheney I've been able to reproduce this consistently across new installs on bare metal. I provided full logs above that don't seem to indicate and issues. I'm happy to provide any more data needed, I'm just at a loss on where to debug this.

**Comment by davecheney** [comment]
@rjbez17 can you please update this issue with your current status. Thank you.

**Comment by rjbez17** [comment]
@davecheney i waiting for direction from you on how to proceed here.

**Comment by davecheney** [comment]
I’m sorry, this was my mistake. In https://github.com/projectcontour/contour/issues/1182#issuecomment-531936036 you suggested that you had additional information to provide. From contours POV all the options we can enable to preserve remove ip’s have been enabled in 1.0.

**Comment by davecheney** [comment]
@rjbez17 what would be the resolution you would like to see on this ticket? As far as I am aware Contour turns on all the flags that we have access too to request the remote IP is preserved.

**Comment by rjbez17** [comment]
@davecheney  I'm just getting back into the swing of things from KubeCon. I'll try to repro with the latest version over the next few days and get back to you.

**Comment by rjbez17** [comment]
@davecheney closing this to get it off your plate. I'll reopen if I can reproduce this on bare metal.
