### ISSUE TITLE
xDS stale nonce is ignored

### ISSUE THREAD

**Issue by phylake** [projectcontour/contour#1187]
From the [Envoy docs](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#resource-updates)

> The management server should not send a DiscoveryResponse for any DiscoveryRequest that has a stale nonce.

I don't see that in the current implementation which would be another source of unneeded updates sent to Envoy

**Comment by stevesloka** [comment]
Hey @phylake thanks for reporting this, I'm still digging into some of this specific to xDS. I know there are additional xDS things  (https://github.com/heptio/contour/issues/1176) we should handle more properly. Let me poke around and see what's needed from a Contour perspective.

**Comment by davecheney** [comment]
eecdb7e999af43e9e4d45723df057e41c0b7449e added error level logging of NACKs from envoy. Moving to the backlog as there is no work scheduled before 1.0

**Comment by youngnick** [comment]
This is most likely related to #1176, which we are getting prioritized soon.
