### ISSUE TITLE
pkg/contour: Disable Ingress & IngressRoute resources via flag or config item

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1241]
**Describe the solution you'd like**
If users are utilizing `HTTPProxies`, we should have a way to disable `Ingress`  as well as `IngressRoute` resources as they don't follow the same delegation mechanism and could possibly allow users to introduce unpredicted configurations within their Ingress infrastructure. 

// #1234

**Comment by bgagnon** [comment]
As a workaround, can this be achieved by removing Contour’s RBAC permission to read/list/watch Ingress objects?

**Comment by davecheney** [comment]
Thanks for raising this issue. I think for the moment the answer is to prevent Ingress via RBAC. I'm going to move this to the unplanned milestone and we'll re-evaluate post Contour 1.0

**Comment by bgagnon** [comment]
We've neutralized the `Ingress` object in our clusters in two ways:
* blocking Contour from seeing any `Ingress` objects, via RBAC
* enforcing a `ResourceQuota` of `max: 0` objects of type `Ingress` in namespaces

For us, the quota was necessary to avoid having confused users wondering why their `Ingress` objecs are ignored. We felt the resource quota approach gave a better user and developer experience:
- the error message is clearer than an RBAC problem
- it's not possible to write RBAC roles that target _everything except Ingress_, which is annoying to maintain as we need to list _everything else_ explicitly
- should a particular namespace require a different ingress controller, we can deploy it there and lift the quota restriction on that namespace

We intend to use the same strategy to support only `HTTPProxy` and forbid `IngressRoute`.

**Comment by davecheney** [comment]
Thank you for your reply. At the moment the way we expect admins to restrict which k8s objects are used inside their cluster is RBAC. The resource quote method is really nice. I’d like to document that in the , as yet to start, learning and solutions section of the website. 

FWIW: if —root-namespaces is used to restrict root ingressroute and HTTPProxy objects untraceable objects will have their status set to orphaned. We could probably do better than that to notify end users that their object is unreachable by policy, not just typo.

**Comment by bgagnon** [comment]
This issue should be revised to disable Ingress and/or IngressRoute objects. This lets an operator support _only_ HTTPProxy objects.

**Comment by davecheney** [comment]
For the record my suggestion on the k8s slack was to address this with RBAC in the cluster rather than introduce logic into contour.

Rbac would let the user know immediately that objects are disallowed by policy. Communicating this after the fact if Contour was programmed to ignore certain objects would be less effective.

On 11 Feb 2020, at 08:04, Benoit Gagnon <notifications@github.com> wrote:

﻿

This issue should be revised to disable Ingress and/or IngressRoute objects. This lets an operator support only HTTPProxy objects.
