### ISSUE TITLE
Leader election should be multi-read, single write style

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour#1385]
The current implementation of leader election in Contour is as follows:
- Contour pods elect a leader using a Configmap as the distributed lock. (Hard-coded to `contour` in `heptio-contour`).
- All pods block before opening the gRPC port until one becomes leader.
- In order to ensure that only the leader actually serves traffic, the Pod's readinessProbe is configured to look for the gRPC  port.

Importantly, this means that non-leader Pods are not Ready (as far as Kubernetes is concerned), which ensures that their Endpoint is not present in the Endpoints that the Contour Service uses, and so no traffic from the Envoy Daemonset arrives at non-leader xDS ports. If this was not the case, and we used the metrics port for readinessProbes (as we do for livenessProbes), then Envoy would fail at connecting to Contour n-1 out of n times. (where n is the number of Contour pods in the Deployment).

The problems with this current method are:
- The Contour Deployment can't use the RollingUpdate strategy (as that requires that Pods become Ready for the Deployment to complete its rolling update).
- Kubernetes tooling assumes that most Pods will be Ready most of the time, and that unReady pods are an exceptional condition that should be looked at.

This ticket covers moving the leader election pattern to the same pattern used by the core Kubernetes components like the apiserver:
- n Pods run, and serve information from their serving endpoints
- only the leader writes back changes to controlled objects.

In the case of Contour these changes will mainly be status updates and events.

The downside of moving to this model is that the current single-reader, single-writer model ensures that all Envoys will receive the same messages in the same order, preventing partial configuration states at the Envoy end. I anticipate that #1280 will help to mitigate this in the future.

Blocked

- [ ] #1425

**Comment by youngnick** [comment]
This work is currently in two parts:
- Changing the Status to be more compatible with this idea (#1425 )
- Setting up leader election to no longer block the gRPC server from opening its port.

I'm covering the latter in this issue.

**Comment by youngnick** [comment]
This is blocked at the moment by the StatusWriter work in #1425 - I'm unassigning myself and leaving this one to @davecheney once he's finished there.

**Comment by davecheney** [comment]
There are too many other higher priority issues ahead of this one. Bumping to rc.1

**Comment by davecheney** [comment]
@youngnick I don't want to block this issue on #1425. If leader election is working -- a leader is elected amongst running contours -- and we've reverted the deployment changes that caused use to move away from `RollingUpdate`, then I'm fine to close this issue. 

Can you please action this soon. Thanks

**Comment by youngnick** [comment]
Sorry, @davecheney, I missed your comment on here. The deployment has been changed back to rollingupdate for some time, so I'll leave this to be closed by #1745.
