### ISSUE TITLE
Move leader election to use the new Lease object

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour#1393]
As of Kubernetes 1.15, the new Lease object is in beta, and can be used as the lock for leader election.

Once the Lease object is in beta in all our supported versions of Kubernetes (ie in the 1.17 or 1.18 timeframe), we should move the leader election code to use it.

This will mean that Contour won't need Update permissions on the leader election configmap (which is currently the `config` ConfigMap in `heptio-contour`).

**Comment by sunjayBhatia** [comment]
we've started doing this as part of moving to using more controller-runtime managed runnables/leader election

release 1.21.0 can remove use of the configmap for leader election

**Comment by skriss** [comment]
Bumping this to 1.21 for the remaining work.
