### ISSUE TITLE
Lowering Envoy's cluster per-connection buffer to 32kb

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1408]
Envoy allocates 1mb per connection to a backend pod.

https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto#cluster

It is not clear if it allocates it all in one go, or it is an upper limit. In either case 1Mb is a lot. I think it should be lowered to something like 64kb.

**Comment by youngnick** [comment]
I've updated the title to reflect the recommendations from #1375.

**Comment by youngnick** [comment]
From the Envoy documentation, this is a soft limit, not a hard limit, so we should be fine to set this to 32KiB.

**Comment by davecheney** [comment]
@youngnick agreed.

**Comment by davecheney** [comment]
Based on https://github.com/projectcontour/contour/pull/1797#pullrequestreview-306974148 I think this setting doesn't do what I thought it did. Moving to the backlog for further investigation.
