### ISSUE TITLE
Add openAPIV3Schema validation for HTTPProxy

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1414]
**Describe the solution you'd like**
The initial build of the HTTPProxy CRD left out defining the openAPIV3Schema definitions. This was on purpose while the spec is in development.

**Comment by youngnick** [comment]
Turns out, there is a generator (https://github.com/kubernetes-sigs/controller-tools/blob/master/cmd/controller-gen/) that can help with this by doing it automatically. I'll get it working, then add it to the make check in the same way we have the check that the manifests have been updated.

**Comment by davecheney** [comment]
> help with this by doing it automatically.
![](https://media.giphy.com/media/Zk9mW5OmXTz9e/source.gif)
