### ISSUE TITLE
internal/e2e tests need some love

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1436]
Our `internal/e2e` directory needs some love. This package was initially created to test scenarios that required sequences of operations flowing through Contour. It's also a useful way to reproduce failures reported in the field. Once fixed, they act as regression tests.

However, over time the e2e package has grown rather unruly. Most of this is my fault. Casual investigations will discover half finished attempts to apply test helpers and refactor assertions.

A more serious issue is the duplicate between tests in different files. Initially the e2e tests were structured around the various xDS endpoints, however over time we're finding that a test of a _feature_ presents itself across multiple endpoints, eg. secrets interact with LDS and SDS, routes, tcproxying and https upgrade interact with LDS, CDS, and EDS. This was highlighted recently adding e2e tests for #865, the same test was written in two files to test the output in RDS and LDS.

I propose the following

1. Rename `internal/e2e` to `internal/featuretests`. This is probably a symbolic action, but it does more accurately reflect the role of the tests in the current `e2e` directory. This would also free up `e2e` for _real_ end to end tests including a full contour and envoy process standup.
3. Complete the refactor of test and assertion helpers. Also drop the _nonce_ checks that continually need updating whenever the order of events changes. If needed they can be tested specifically but at the moment they're just noise.
2. Refactor the current tests along the lines of the features they test, specifically if a feature manifests in LDS and SDS, do both assertions in the same test rather than repeating it across files.

**Comment by jpeach** [comment]
The `e2e` -> `featuretests` migration is complete.
