### ISSUE TITLE
Add filtering capabilities to the DAG debug endpoint

### ISSUE THREAD

**Issue by alexbrand** [projectcontour/contour#1446]
**Describe the solution you'd like**
As a cluster operator using Contour, I would like to be able to filter the DAG debugging output that can be obtained via the debug endpoint. In a cluster with hundreds or thousands of IngressRoutes, the DAG is impossible to understand as it currently stands.

It would be great if I could produce a DAG for a specific IngressRoute by passing filtering parameters to the /debug/dag endpoint. E.g. `/debug/dag?namespace=foo,ingressroute=bar`

**Comment by davecheney** [comment]
@alexbrand if you'd like to drive this work i'd be happy to pair with you on it.

**Comment by alexbrand** [comment]
Yeah, I'd love to! I think the biggest open question here is the UX. 

Another use case came up this week around capturing all the secrets that Contour is holding in its DAG. We got around it by using grep, cut, etc to filter the DAG down.

Maybe a good starting point is adding the ability to get the DAG for a specific namespace? Delegation might throw a wrench into this though.
