### ISSUE TITLE
internal/dag: Enable additional fields in Condition

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1457]
**Describe the solution you'd like**
An httplb can contain `[conditions](https://github.com/heptio/contour/blob/master/apis/projectcontour/v1alpha1/httploadbalancer.go#L44)`, as an `Include` or as part of a `Route` definition. Currently, we've implemented `pathPrefix`, but there are additional items to implement:

- [x] HeadersMatch
- [x] HeadersContain
- [x] ExactMatch: https://github.com/heptio/contour/blob/master/design/routing-design.md#exact-path-routing
- [ ] Wildcard Path (i.e. Glob routing): https://github.com/projectcontour/contour/blob/master/design/routing-design.md#path-wildcard

**Comment by davecheney** [comment]
Sadly we won't be delivering `prefix:` wildcard condition for Contour 1.0. The design is close from a user facing perspective, but there are some subtle implementation details that remain unanswered and we want to proceed carefully there in case we paint outselves into a corner.

I'm moving this ticket to the backlog as a placeholder for a epic ticket which will capture the business requirements for wildcard routing.

**Comment by sunjayBhatia** [comment]
removing important-soon as this is an httplb issue, not httpproxy
