### ISSUE TITLE
cmd/contour: Flag to enable routing config objects

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1461]
**Describe the solution you'd like**
Contour now has the ability to process `Ingress`, `IngressRoute` and now `HTTPProxy`. 

We should have a flag which enables types that a user would want Contour to process. If users create a mix of two or more types at the same time, unexpected results could arise.

**Comment by jpeach** [comment]
You can approximate this with the `ingress.class` annotation to force Contour to ignore certain objects, but that's hacky and burdensome for operators.

**Comment by jpeach** [comment]
Duplicate of #1241
