### ISSUE TITLE
Preserve incoming X-Request-Id headers

### ISSUE THREAD

**Issue by jessedearing** [projectcontour/contour#1487]
**Describe the solution you'd like**
For my use-case, I have Contour running as an ingress to my cluster but I have a service that routes HTTP requests to the Contour endpoint. The routing service generates a `X-Request-Id` header, but Envoy in it's default configuration will sanitize it and create a new request ID making log correlation difficult. I'd like to have some way I can set Envoy via Contour to not sanitize that header.

Envoy seems to permit setting this with the [`preserve_external_request_id`](https://www.envoyproxy.io/docs/envoy/v1.11.1/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto.html#envoy-api-field-config-filter-network-http-connection-manager-v2-httpconnectionmanager-preserve-external-request-id) setting in HttpConnectionManager.

This is configured when the listener is created so my initial thought was to add a flag to Contour, but I'd love to hear more suggestions and feedback.

**Anything else you would like to add:**
Not that I can think of.

**Environment:**

- Contour version: 0.14.2
- Kubernetes version: (use `kubectl version`): 1.14.6
- Kubernetes installer & version: Kubeadm 1.14
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.3 LTS

**Comment by davecheney** [comment]
@jessedearing thanks for the issue report. I can't see any reason to remove the `x-request-id` field so I can tell envoy to always permit it through. 

When do you need this by and does it need to be in a non beta release? At the moment 0.15 is our stable release and will be until November. We'll have a beta.1 release this month and several release candidates next month.

**Comment by jessedearing** [comment]
Awesome! That makes this an even easier story.

I think we can target getting it in a beta.1 release this month and that will be fine.
