### ISSUE TITLE
Renaming heptio-contour namespace

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1505]
The current namespace contour is deployed into contains the name of a defunct company. What should we rename the namespace?

- [ ] `contour`
- [x] `projectcontour`
- [ ] `vmware-contour`
- [ ] D. none of the above.

---
Blocked
- [ ] #1418

**Comment by stevesloka** [comment]
`projectcontour` to be consistent?

**Comment by davecheney** [comment]
+1 to that
