### ISSUE TITLE
Deprecate contour.heptio.com annotations

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1506]
Contour offers these annotations
```go
        annotationRequestTimeout     = "contour.heptio.com/request-timeout"
        annotationWebsocketRoutes    = "contour.heptio.com/websocket-routes"
        annotationUpstreamProtocol   = "contour.heptio.com/upstream-protocol"
        annotationMaxConnections     = "contour.heptio.com/max-connections"
        annotationMaxPendingRequests = "contour.heptio.com/max-pending-requests"
        annotationMaxRequests        = "contour.heptio.com/max-requests"
        annotationMaxRetries         = "contour.heptio.com/max-retries"
        annotationRetryOn            = "contour.heptio.com/retry-on"
        annotationNumRetries         = "contour.heptio.com/num-retries"
        annotationPerTryTimeout      = "contour.heptio.com/per-try-timeout"

        contour.heptio.com/upstream-protocol.{protocol}
        "contour.heptio.com/ingress.class"
```

We need to duplicate those to the `projectcontour.io` space and deprecate the `contour.heptio.com` variants.

- Duplicate `contour.heptio.com` annotations to `projectcontour.io`
- Deprecate `contour.heptio.com` annotations
- Update `docs/annotations.md`

Still TODO

- [x] `contour.heptio.com/upstream-protocol.{protocol}`
- [x] `contour.heptio.com/ingress.class`
- [x] `contour.heptio.com/request-timeout`
- [x] `contour.heptio.com/websocket-routes`
- [x] `contour.heptio.com/max-connections`
- [x] `contour.heptio.com/max-pending-requests`
- [x] `contour.heptio.com/max-requests`
- [x] `contour.heptio.com/max-retries`
- [x] `contour.heptio.com/retry-on`
- [x] `contour.heptio.com/num-retries`
- [x] `contour.heptio.com/per-try-timeout`
- [x] `contour.heptio.com/tls-minimum-protocol-version`

**Comment by jpeach** [comment]
I'm working on `contour.heptio.com/max-connections`.

**Comment by jpeach** [comment]
I'm taking `contour.heptio.com/max-pending-requests`

**Comment by davecheney** [comment]
Imma taking `contour.heptio.com/tls-minimum-protocol-version`

**Comment by jpeach** [comment]
Working on `contour.heptio.com/max-requests`.

**Comment by jpeach** [comment]
Working on `contour.heptio.com/max-retries`

**Comment by stevesloka** [comment]
I'll take `retry-on`

**Comment by stevesloka** [comment]
All tasks complete! 🎉

**Comment by davecheney** [comment]
Huzzah for teamwork!
