### ISSUE TITLE
internal/envoy: Switch to Safe_Regex

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1513]
**Describe the solution you'd like**
The regex  field has been deprecated in favor of safe_regex as it is not safe for use with untrusted input in all cases.

Need to update to use [safe_regex](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto) used here: https://github.com/projectcontour/contour/blob/master/internal/envoy/route.go#L175

**Comment by stevesloka** [comment]
Safe_Regex is new in Envoy 1.12, so this needs to wait until Contour upgrades to that new version.

**Comment by jpeach** [comment]
See #1351
