### ISSUE TITLE
Contour config file example breaks deployment

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1527]
**What steps did you take and what happened:**
If I deploy the sample Contour deployment (i.e. `kubectl apply -f examples/contour`), Contour fails to start and throws this error:

```
kubectl logs -f contour-754f4dd657-2rmk4 -n projectcontour                                              [14:35:17]
contour: error: EOF, try --help
```

Taking out the reference to the configfile allows Contour to run.

**Comment by davecheney** [comment]
@youngnick this could be related to your json logging docs change.

**Comment by youngnick** [comment]
Yep, this is because at least one line needs to be uncommented, it seems. Just testing now to find the exact requirement.

**Comment by davecheney** [comment]
Oops. I remember looking at the `tls:` lines that were previously uncommented and thinking -- hmm I wonder how the yaml parser deals with a map with no values.

This is a case of just getting lucky last time. My suggestion would be to revert the change to the `tls: ` section.

If only there was a way to write unit tests for yaml.
