### ISSUE TITLE
make yamllint target needs to pass

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1543]
YAML is a mess. As Rob Pike put it "semantic whitespace is a profound mistake". But it's what we have.

I recently added a `make yamllint` target. It would be great if we could make it part of CI for the 1.0 release.

TODO:
- [ ] tweak `.yamllint` configuration, choose reasonable settings that aline with the generally accepted style of Kubernetes YAML.
- [ ] make the `make yamllint` target pass cleanly either by addressing its errors or adjusting `.yamllint`. Blindly following yamllint's complaints is not the goal.
- [ ] add `yamllint` target to `make check`
- [ ] ensure `yamllint` target can fail the build.

**Comment by ffahri** [comment]
Hey i make some editing on yamls and changed some rules if its okey i can create pr for it
https://github.com/ffahri/contour/commit/95f9328cedfc0ea09e40891a3dc0c0de5154fa29

Few things:
Line length can be a problem for configmaps (making them multiline can be easy or not allowed) especially for prometheus configs. i changed that length to 280 but can be removed.

**Comment by davecheney** [comment]
@ffahri thank you for working on this. I'm fine with removing a fixed line length or setting it to a more realistic number like 9999
