### ISSUE TITLE
Contour should configure a stream_idle_timeout

### ISSUE THREAD

**Issue by xstevens** [projectcontour/contour#1547]
**Describe the solution you'd like**
Allow the configuration of Envoy's [stream_idle_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#envoy-api-field-config-filter-network-http-connection-manager-v2-httpconnectionmanager-stream-idle-timeout). According to the Envoy documentation this can be set globally as well as per-route. Envoy defaults this to 5 minutes, but it is overridden by per-route idle timeout.

We use gRPC streaming for some APIs and we would like to keep the connection open as long as possible in many cases. We have currently enabled gRPC keep-alive, but recently realized that Envoy doesn't proxy these through to keep upstream connections alive (see [envoy/2086](https://github.com/envoyproxy/envoy/issues/2086) and [envoy/5142](https://github.com/envoyproxy/envoy/issues/5142)).

What happens currently is if we don't send data in under 60 seconds ([Contour's default idle timeout](https://github.com/projectcontour/contour/pull/1070)) then we get a gRPC error back of ["stream timeout"](https://github.com/envoyproxy/envoy/blob/c5738e1f852acd2a63da799973c9f78e35c4c798/source/common/http/conn_manager_impl.cc#L553). 

**Anything else you would like to add:**

We also need to consider how to do this in a way where we can avoid security issues such as trusting timeouts specified by clients.

Related Issues:

- https://github.com/projectcontour/contour/issues/944
- https://github.com/projectcontour/contour/issues/1073#issuecomment-501527196

**Environment:**

- Contour version: v0.15
- Kubernetes version: v1.15.3

**Comment by davecheney** [comment]
@xstevens in 1.0.0-beta.1 we added support for a `route.timeoutPolicy.idle` per route idle timeout. Is this useful for you?

**Comment by xstevens** [comment]
Yes, per route idle timeout is useful for us. Thanks!

**Comment by ewoutp** [comment]
We have same problem. Even after setting idle timeout to infinity, we still get stream timeout errors.

**Comment by skriss** [comment]
Stream idle timeout is now globally configurable for Contour -- see https://projectcontour.io/docs/v1.9.0/configuration/#timeout-configuration. Closing this out, but feel free to reach out again if needed.
