### ISSUE TITLE
Promote HTTPProxy to v1beta1

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1552]
Promote HTTPProxy to v1beta1 for rc.1

However it look like this will be traumatic for the codebase and equally traumatic for the users of v1alpha1.

We should probably

- [ ] promote v1alpha1 to v1 final immediately to avoid creating a longer trail of deprecated versions.
- [ ] register v1 as v1alpha1 (if such a thing is possible) to support the v1alpha1 users from contour 1.0.0-beta.1 until 1.0.
- [ ] publish a deprecation advisory for v1alpha1 and remove it in rc.2

**Comment by davecheney** [comment]
@stevesloka @youngnick 

I looked into this briefly this morning and I think we have three options

1. Duplicate `apis/projectcontour/v1alpha1` to `apis/projectcontour/v1`. This will duplicate all the current projectcontour types, with a comesurate duplication throughout the `internal/dag` and `internal/contour` packages. 
2. Move `apis/projectcontour/v1alpha1` to `apis/projectcontour/v1` and alter the schema registration to register these types as both v1 and v1alpha1. This should allow people who have written v1alpha1 types to continue to use them until we delete them -- in 1.0 final?
3.  Move `apis/projectcontour/v1alpha1` to `apis/projectcontour/v1` period. This will break anyone using alpha1 types in rc2, giving them two weeks less grace period -- but also not letting them continue to use a deprecated type for two weeks longer than necessary.

Option 2 originally looked like a nice hack but I'm pretty sure that because status can't tell the difference between `v1alpha1.HTTPProxy` and `v1.HTTPProxy` status updates will either fail, or silently upgrade/downgrade objects in bizarre ways. 

My suggestion is we pursue option 3. The population of people using v1alpha1 types should be small, and will be smaller than option 2. The sooner we move to the v1 type the better IMO.


n.b. in all cases we'll also need to adjust examples/contour/01-common and RBAC to account for these changes.

**Comment by stevesloka** [comment]
I think given the short time window, I think that option 3 is fine to break existing users. There are some fields that I'm looking to add, but those aren't breaking changes for any version. 

I think (and haven't tested), but all that would happen if someone had the `v1beta1` version, is that any object of that type will just not get watched by our controller. It would break short names I think though, but again totally acceptable.
