### ISSUE TITLE
HTTPProxy: Update printer columns

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1567]
**Describe the solution you'd like**
Need to fix up the printer columns used to show `HTTPProxy` CRDs when using kubectl. 

Currently breaking issues:
- [x] Fix "first route" column

New Features:
- [ ] Show root vs child Proxy
- [ ] Separate HTTP vs TCP Proxy implementations

**Comment by youngnick** [comment]
All of these features are not deliverable without adding extra information into the `status:` area.

For 1.0.0-rc.2, I'll remove the 'first route' column, since it does nothing on HTTPProxy anyway, then this will go back on the backlog, blocked behind figuring out what to do about status.
