### ISSUE TITLE
internal/dag: Fix SetValid() status writing

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1569]
**Describe the solution you'd like**
In #1562, the dag/status tests were re-enabled, however, there were some issues discovered on how `setValid` or `setInvalid` is getting set.

The call here https://github.com/projectcontour/contour/blob/master/internal/dag/builder.go#L481 might be in the wrong place. Ideally, there should be only one path per object that can lead to SetValid/SetInvalid.

In the case of the SetValid that should be logically at the end of processing the object -- when nothing else can set its status to Invalid. This is straight forward for roots but complex for http proxies which are included, possibly multiple times. Its possible this has no answer at the moment or the final status which is set is unstable.

In the case of SetInvalid the inverse is true, this should occur as close to the condition which caused the object to be invalid. After that no further processing should be performed on the object -- set invalid is a final state. The code should return as quickly as possible to the point where the object's status writer's commit function should run.

**Comment by davecheney** [comment]
I think this is fixed in 44102ef5e99
