### ISSUE TITLE
Getting Readiness probe failed: HTTP probe failed with statuscode: 403

### ISSUE THREAD

**Issue by Siddharthk** [projectcontour/contour#1580]
**What steps did you take and what happened:**
I am using 1.12.7 AWS EKS version and deployed contour as replicaset. The pods are not coming up and giving readiness probe error. Currently using contour-v0.12.1 and envoy-v1.10.0 versions.

```
NAMESPACE        NAME                                                  READY     STATUS    RESTARTS   AGE
heptio-contour   contour-845b4c59f4-k8jlt                              1/2       Running   0          5m8s
heptio-contour   contour-845b4c59f4-tq99r                              1/2       Running   0          5m8s
```

Error:
```
 Normal   Created    1m                 kubelet, ip-10-167-82-217.ap-southeast-1.compute.internal  Created container
  Normal   Started    1m                 kubelet, ip-10-167-82-217.ap-southeast-1.compute.internal  Started container
  Warning  Unhealthy  28s (x13 over 1m)  kubelet, ip-10-167-82-217.ap-southeast-1.compute.internal  Readiness probe failed: HTTP probe failed with statuscode: 403

```

**What did you expect to happen:**
The pods should be coming up.

Kubectl version:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-12-06T01:33:57Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**Comment by davecheney** [comment]
Hello,

I’m sorry to hear you are having issues. 

The first thing you should do is upgrade to contour 0.15 as there are some important security issues with the version of Envoy that previous versions of Contour use. 

Once you’ve upgraded, please let me know if the issue persists.

**Comment by davecheney** [comment]
@Siddharthk ping

**Comment by Siddharthk** [comment]
@davecheney  The issue was with the proxy that I was using due to which the kubelet was not able to do readiness probe.  Is it still recommended to use latest version of Contour? Also I am currently running contour and envoy in same deployment. Should I break them out?

**Comment by davecheney** [comment]
Yes. As a small team our support resources are very limited. If you need some help the first thing we’re going to ask you to do is upgrade to the latest stable version. I think it would be a good idea to get onto the latest stable version so you’re up to date and also using the latest envoy which always comes with some juicy security fixes.

**Comment by davecheney** [comment]
> Also I am currently running contour and envoy in same deployment. Should I break them out?

Let's get to the bottom of why your readiness probes fail first before changing anything else.

**Comment by Siddharthk** [comment]
@davecheney The issue is resolved as it was related to proxy issue on my side.

**Comment by davecheney** [comment]
Thank you for confirming.
