### ISSUE TITLE
All prefix: conditions must start with a /

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1628]
Breaking out from https://github.com/projectcontour/contour/issues/1597#issuecomment-537754073

I propose that all `prefix: ` conditions, if present, must start with a `/`. Specifically

- At most one `prefix: ` condition may be present in each `include.conditions` or `route.conditions` block.
- If present the `prefix: ` condition must start with a `/`.

**Comment by youngnick** [comment]
I'll implement this, including checking that we test for:
- [ ] included with `prefix: /prefix`, and no prefix on the included HTTPRoute
- [ ] included with `prefix: /prefix`, and `prefix: /` on the included HTTPRoute
- [ ] included with `prefix: /prefix`, and `prefix: /other` on the included HTTPRoute
- [ ] included with `prefix: /foo` and `prefix: bar` should fail.
