### ISSUE TITLE
Envoy memory optimization: do better filter_chain_match organization

### ISSUE THREAD

**Issue by phylake** [projectcontour/contour#1636]
Contour creates a `filter_chain_match` with a single FQDN in `server_names` for every FQDN. It also provides TLS delegation which we use heavily. The problem is that the same `tls_context` and `filters` are copied in each `filter_chain`.

We reorganized `filter_chain_match` creation to aggregate `server_names` that reference the same secret name and saw a memory reduction of 40+ GiB to ~250 MiB in Envoy

This non-optimal construction of `filter_chain_match` plus #1635 plus https://github.com/envoyproxy/envoy/issues/7923 came together to cause our months-long issue of Envoy being oom-killed

**Comment by phylake** [comment]
Forgot to mention: you might think it's better to aggregate FQDNs by cert _content_ (i.e. a digest), or inspect the cert and aggregate by Common Name. The latter was our first approach but it was confounded by https://github.com/envoyproxy/envoy/issues/6767

**Comment by dharmab** [comment]
>aggregate by Common Name

What about Subject Alternative Names? That aggregation could get tricky.

**Comment by dharmab** [comment]
There's also a corner case for different certs issued for the same names by different PKIs (think internal/enterprise CAs).

**Comment by davecheney** [comment]
Thank you for your issue.

> We reorganized filter_chain_match creation to aggregate server_names that
reference the same secret and saw a memory reduction of 40+ GiB to ~250 MiB
in Envoy

Would you be willing to contribute that change to the project?

**Comment by jpeach** [comment]
FYI, we organized the filter chains differently in 1.4 to enforce SNI binding semantics. This strongly binds a SNI server name to the corresponding routes, but I expect that this has some negative effect on Envoy resources, since there are now more HttpConnectionManagers.
