### ISSUE TITLE
Allow TCPProxy to work with Includes in HTTPProxy

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1655]
**Describe the solution you'd like**
#1654 added support for `TCPProxy` at the root httpproxy level, this issue is to describe allowing this to happen from an include outside the root.

**Comment by davecheney** [comment]
@stevesloka I think this has to slip to rc.2

**Comment by davecheney** [comment]
Assigning to myself as I have some suggestions for a design.

**Comment by davecheney** [comment]
My proposal is to implement TCPProxy inclusion following the same mechanism as IngressRoute TCPProxy delegation. Specifically;

- There can be at most one TCPProxy defined per _root_ HTTPProxy.
- `spec.tcpproxy` can include an array of `services` or a `include` key, but not both.
- `spec.tcpproxy.include` is a simplified version of `spec.includes`, it does have a conditions key.
- Processing of the TCPProxy include chain continues until the first TCPProxy with non empty `services` key is found. Those services become the backing services for the TCPProxy for that _root_ HTTPProxy.

**Comment by youngnick** [comment]
So, it has a conditions key, but setting it doesn't really do anything? Why have it at all?

**Comment by davecheney** [comment]
> spec.tcpproxy.include is a simplified version of spec.includes, it does have a conditions key.

I've changed the tcp of spec.tcpproxy.include to be a new type which does not have any conditions. I think we can get away with this because the key, `include`, hasn't changed since rc.1 and the validations we added in #1731.
