### ISSUE TITLE
Envoy init container inits starting

### ISSUE THREAD

**Issue by lostllama** [projectcontour/contour#1666]
**What steps did you take and what happened:**

I'm currently running Contour 15.0, installed using [this config](https://github.com/projectcontour/contour/blob/v0.15.0/examples/render/deployment-rbac.yaml). This was the situation in two of my clusters as of yesterday, when I upgraded from 0.9.1.

With the release of 15.1 today, I decided to upgrade to the now-latest version.  This time I opted to go down the DaemonSet route using [this config](https://github.com/projectcontour/contour/blob/v0.15.1/examples/render/daemonset-rbac.yaml). As of this morning, I was running 15.0 in two clusters.

Due to the LoadBalancer getting recreated, I modified the LoadBalancer service config to declare a LoadBalancerIp in order to ensure I get the same static IP when the new one comes up.

My deployments are done via helm, and I simply did an upgrade from the old version to the new version by replacing the scripts, and doing my usual automated deployment (a Helm upgrade). This worked fine on one cluster, but not on another.

**What did you expect to happen:**

After my success with one cluster, I expected the second cluster would spring to life immediately. Instead, the Envoy daemonset pods entered a crash loop backoff state.

**Anything else you would like to add:**

I've done some basic diagnostics to pull information out.
[commandOutputs.txt](https://github.com/projectcontour/contour/files/3706258/commandOutputs.txt)

Looking at logging on Google, I can see this for the Envoy pod - these are the only log entries:

> write /config/envoy.json: file already closed

**Environment:**

- Contour version: 15.1
- Kubernetes version: (use `kubectl version`): v1.13.10-gke.0
- Kubernetes installer & version: ?
- Cloud provider or hardware configuration: Google
- OS (e.g. from `/etc/os-release`): ?

**Comment by stevesloka** [comment]
There a couple issues with your upgrade from what I see in your logs. 

1. Contour <> Envoy now (by default) communicate over TLS. We include a sample [k8s Job ](https://github.com/projectcontour/contour/blob/master/examples/contour/02-job-certgen.yaml)to automate this if you don't want to build your own. Alternatively, you can pass `--insecure` to the bootstrap command to bypass.

```
MountVolume.SetUp failed for volume "envoycert" : secrets "envoycert" not found
MountVolume.SetUp failed for volume "cacert" : secrets "cacert" not found
```

2. Looks like you didn't target v0.15.1 properly, the log is pulling a `master` tag of Contour. Right now master is broken from a PR last night that I have a fix for shortly.

```
pulling image "docker.io/projectcontour/contour:master"
```

I'd look to add the proper certs to Envoy so it starts, also change the Contour image to `v0.15.1` and you should be good to go. =)

**Comment by lostllama** [comment]
I've repeated my upgrade today, this time manually instructing Helm to delete the old deployment, and then deploying the new one on top. All solved. Thank you very much.
