### ISSUE TITLE
Envoy IP tagging support

### ISSUE THREAD

**Issue by bgagnon** [projectcontour/contour#1690]
We have a need for geo-location of incoming client requests for application routing decisions. Contour supports source IP preservation in various ways, including the `PROXY` protocol.

We think we can leverage Envoy's [IP tagging](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ip_tagging/v2/ip_tagging.proto) filter for this, but it is not currently available from Contour.

I understand this is really a niche request, but I figured I'd file an issue anyway, as suggested by @youngnick.

**Comment by bgagnon** [comment]
We have an extra requirement that makes this every more niche: the CIDRs for the tags are changing often enough in our network that we need to automatically refresh this information.

But this feature could be generalized to support public geo IP databases (like [Maxmind](https://dev.maxmind.com/geoip/geoip2/geolite2/)) that would also benefit from periodic automated updates.

**Comment by Nefelim4ag** [comment]
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/geoip_filter
there is native support from the envoy
