### ISSUE TITLE
Enforce the use of `kubernetes.io/tls` secret types.

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#1697]
Currently, Contour can allow the use of secrets that are not of type `kubernetes.io/tls` if they are not service account tokens and contain the expected data keys.

We should consider enforcing a requirement that the secret be of type `kubernetes.io/tls`. This makes the requirement clearer for users and improves separation of secrets in the cluster. It would also make it a bit easier to implement a certificate validation controller.

**Comment by jpeach** [comment]
I'm working on this next.

**Comment by jpeach** [comment]
Related to #1702

**Comment by jpeach** [comment]
Proposed rules:
* TLS certificate/key pairs must be secrets of type "kubernetes.io/tls"
* Certificate bundles may be "kubernetes.io/tls" or "Opaque" (aka generic) secrets
* Secrets type must be specified

**Comment by jpeach** [comment]
Document this per #1415

**Comment by sunjayBhatia** [comment]
having a small issue due to this, see: https://github.com/projectcontour/contour/issues/2138#issuecomment-777942264
