### ISSUE TITLE
HTTPProxy header conditions, value is case sensitive

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1701]
**Describe the solution you'd like**
Currently, when specifying condition values of type `header`, they are case-sensitive. We should make this field case insensitive.

**Comment by davecheney** [comment]
@stevesloka would you be able to expand on this. Based on previous readings of RFC2616 headers keys should be compared case insensitive but the value should be case sensitive.

**Comment by stevesloka** [comment]
Ahh ok I misread that then, it's working properly as-is with the case sensitive values.

**Comment by davecheney** [comment]
That is a good question thou. Envoy had a flag on the header marcher that says “case insensitive” (from memory)

I think for the moment we should say that heavier values are case sensitive but we might look at exposing the “case insensitive” flag
