### ISSUE TITLE
Enable PrefixRewrite (RewritePolicy) by default and rewrite to /

### ISSUE THREAD

**Issue by embano1** [projectcontour/contour#1719]
**Describe the solution you'd like**

One of the strengths of Contour is route/condition matching, where I can expose multiple (potentially unrelated) backends transparently via sub-routes. Backends such as nginx or services build with the Go std library usually serve their entrypoint, e.g.`index.html`, under `"/"`.

The current behavior (as of RC1 with deprecated `IngressRoute` and likely a similar implementation in `HTTPProxy`) with conditions/matches is that those paths are forwarded to the respective backend. As a user I would expect a default behavior of stripping the path matched and default to a `prefixRewrite` (or policy) of `"/"`. This would enable out of the box integrations of backends without modification to prevent 404's and seems to be a common deployment scenario when using a reverse proxy with pattern matching.

In case of a rewrite policy, hierarchies could be implemented. E.g. default to `"/"` for any condition (route), which can be overwritten per route though.

**Environment:**

- Contour version: RC1 with `IngressRoute`
- Kubernetes version: (use `kubectl version`): n/a
- Kubernetes installer & version: n/a
- Cloud provider or hardware configuration: n/a
- OS (e.g. from `/etc/os-release`): n/a

**Comment by davecheney** [comment]
@embano1 thank you for this issue. Is this a duplicate of #899 ?

**Comment by davecheney** [comment]
@embano1 ping

**Comment by embano1** [comment]
Thx @davecheney and sorry for the delay. After reading #899 I don't think it's dup. My feature request was about changing the default behavior of route matching to automatically rewrite the /<:match> and defaulting to `"/"`. So I don't have to make modifications on the backend services, which usually accept traffic on `"/"`.

**Comment by davecheney** [comment]
@embano1 thank you for clarifying. I don't think we will be able to make prefix rewriting the default. The workaround is you will have to use the `prefixRewrite` stanza, or whatever replaces it in HTTPProxy on each route.

**Comment by embano1** [comment]
Thank you @davecheney for responding to this. I think it was good to discuss this publicly in case there are similar requests.

**Comment by davecheney** [comment]
To be clear, I’m not saying we won’t add back prefix  rewrite, but what I am saying is we won’t make it opt out as that would require us to also add a mechanism to make prefix rewrite opt out _as well as_ add a replacement for prefix rewrite.
