### ISSUE TITLE
CRD Shortname for "tlscertificatedelegation"? 

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1739]
When working with the `tlscertificatedelegation` crd we haven't defined a short name for it. This issue is to discuss if we'd like to add one so users don't have to type out: `t-l-s-c-e-r-t-i-f-i-c-a-t-e-d-e-l-e-g-a-t-i-o-n` each time.

Possible names:
- certs
- tlscerts
- certdel

**Comment by davecheney** [comment]
Yeah, it sure is a mouthful, `tlscerts` sounds like a decent abbreviation.
