### ISSUE TITLE
Move some resources content into guides.

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#1750]
There are a number of pages located in the "resources" section that could arguably be better kept in the "guides" section. My thought is that resources is mainly for conference videos and the like, whereas "guides" is for showing users how to achieve some useful aim. With that in mind, I think we could relocate

- [x] "IngressRoute to HTTPProxy"
- [x] "Prometheus"
- [ ] "Troubleshooting"
- [ ] "Upgrading Contour"

**Comment by davecheney** [comment]
@jpeach what's left to do on this ticket?

**Comment by jpeach** [comment]
I updated the description to a checklist, and I'll keep it updated as I knock off the guides.

**Comment by davecheney** [comment]
@jpeach thank you!

**Comment by davecheney** [comment]
@jpeach moving this to the 1.0.0 milestone so I can close rc.2 today. Please keep doing what you're doing, there's not need to get this into the rc.2 tag as the website is released from the `master` branch,

**Comment by jpeach** [comment]
Removed the milestone since this is not needed for the 1.0 release.

**Comment by jpeach** [comment]
I don't think we need to do any more here.
