### ISSUE TITLE
Travis CI should run `make check` on each PR

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1780]
For some reason, the Travis CI runs for each PR don't fail on `make check`. 

// Example #1778

**Comment by davecheney** [comment]
Did #1778 fail locally for you or in CI? The master branch looks like its building, https://travis-ci.org/projectcontour/contour/builds/601641154

**Comment by stevesloka** [comment]
1778 failed for me locally, but CI passed.

**Comment by davecheney** [comment]
I’ve seen the same thing locally and I thought it was related to running master not a released version of Go. I haven’t looked into why these, I’m assuming, false positives happen locally yet

**Comment by SDBrett** [comment]
Did PR #1824 fix this issue?

**Comment by davecheney** [comment]
I believe this issue is solved. No action is required.

**Comment by stevesloka** [comment]
#1824 fixed the result of this issue, but I'm not convinced that it's "fixed". Let me run a test, just spelling something wrong should kick the build out, but I don't think it will fail in Travis.

**Comment by davecheney** [comment]
@stevesloka can you please confirm if this is still an issue. Thank you.

**Comment by stevesloka** [comment]
I just did a quick test and make check found the spelling error, so it must have been fixed with other updates. Closing! =)
