### ISSUE TITLE
site: Contour 1.0 release blog post

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1790]
We need a blog post for the Contour 1.0 release. It should highlight

- Major new implementations 
- User impact of those changes 
- Why do we consider this release to be 1.0 and stable? Something like “We’ve been working on this, it’s battle tested, we consider it stabled because of X, Y, and Z.” 
- What will happen after 1.0? Detail the relaxed release schedule. 
- Contributor shoutouts.

**Comment by stevesloka** [comment]
It would be neat to throw stats in there, like the release cadence, the rate of stars, commits, etc. Those are always interesting when looking back over the last two years of work.

**Comment by davecheney** [comment]
Thanks to @youngnick for starting the document, I'll take it over for a spell

**Comment by davecheney** [comment]
I'm done. @stevesloka @jonasrosland over to you.

**Comment by davecheney** [comment]
Draft finalised, closing.
