### ISSUE TITLE
Contour needs a contour-announce mailing list

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1796]
Contour needs a low traffic mailing list for people to subscribe to release notifications.

**Comment by jonasrosland** [comment]
It's been created: https://groups.google.com/forum/#!forum/projectcontour-announce

**Comment by davecheney** [comment]
Thank you. Closing.

**Comment by davecheney** [comment]
reopening, this needs to be added to the website somewhere.

**Comment by jonasrosland** [comment]
I'll add it under /community for you :)

**Comment by davecheney** [comment]
Superb, thank you.
