### ISSUE TITLE
Dual newline character after TLS cert is considered invalid

### ISSUE THREAD

**Issue by lrouquette** [projectcontour/contour#1809]
**What steps did you take and what happened:**
Upgrading Contour from `0.15.0` to `0.15.3` and see the following errors in the log:
```
ERRO[0001] failed to parse PEM block  context=KubernetesCache kind= name=<redacted> namespace=<redacted> version=
```

The `ingress_https` listener is never configured in Envoy.

**What did you expect to happen:**
I expected the secret to be valid (as it was in `0.15.0`) and the https listener to be configured.

**Anything else you would like to add:**
The issue stems from the fact that some of our secrets have a double newline characters as such (`$` representing the newline that would not normally be there):
```
-----BEGIN CERTIFICATE-----
<some cert>
-----END CERTIFICATE-----$
$
```

At some point in the [loop](https://github.com/projectcontour/contour/blob/v0.15.3/internal/dag/secret.go#L56), I see  that `data` is  `"Cg=="`, which is the base64 encoded value of newline. At this point, `len(data) == 1` and `block == nil`, failing the validation.

Apparently, Envoy ignores these characters (and so does openssl btw). My current fix is to change the [test](https://github.com/projectcontour/contour/blob/v0.15.3/internal/dag/secret.go#L54) to `len(data) > 1` (not sure how good/bad that is...).

Below is a full go source that reproduces the issue. The cert is the one from your [tests](https://github.com/projectcontour/contour/blob/v0.15.3/internal/dag/secret_test.go#L20-L52), with the newlines appended:

```go
package main

import (
	"crypto/x509"
	"encoding/pem"
	"errors"
	"fmt"
)

const (
	CERTIFICATE = `-----BEGIN CERTIFICATE-----
MIIFtTCCA52gAwIBAgIJAO0cq2lJPZZJMA0GCSqGSIb3DQEBBQUAMEUxCzAJBgNV
BAYTAkFVMRMwEQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBX
aWRnaXRzIFB0eSBMdGQwHhcNMTQwMzEyMTc0NzU5WhcNMTkwMzEyMTc0NzU5WjBF
MQswCQYDVQQGEwJBVTETMBEGA1UECBMKU29tZS1TdGF0ZTEhMB8GA1UEChMYSW50
ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
CgKCAgEAsgzs6vN2sveHVraXV0zdoVyhWUHWNQ0xnhHTPhjt5ggHmSvrUxvUpXfK
WCP9gZo59Q7dx0ydjqBsdooXComVP4kGDjulvOHWgvcVmwTsL0bAMqmsCyyJKM6J
Wqi8E+CPTOpMBWdapUxvwaSmop8geiTtnX0aV4zGXwsz2mwdogbounQjMB/Ew7vv
8XtqwXSpnR7kM5HPfM7wb9F8MjlRuna6Nt2V7i0oUr+EEt6fIYEVZFiHTSUzDLaz
2eClJeCNdvyqaeGCCqs+LunMq3kZjO9ahtS2+1qZxfBzac/0KXRYnLa0kGQHZbw0
ecgdZC9YpqqMeTeSnJPPX4/TQt54qVLQXM3+h8xvwt3lItcJPZR0v+0yQe5QEwPL
4c5UF81jfGrYfEzmGth6KRImRMdFLF9+F7ozAgGqCLQt3eV2YMXIBYfZS9L/lO/Q
3m4MGARZXUE3jlkcfFlcbnA0uwMBSjdNUsw4zHjVwk6aG5CwYFYVHG9n5v4qCxKV
ENRinzgGRnwkNyADecvbcQ30/UOuhU5YBnfFSYrrhq/fyCbpneuxk2EouL3pk/GA
7mGzqhjPYzaaNGVZ8n+Yys0kxuP9XDOUEDkjXpa/SzeZEk9FXMlLc7Wydj/7ES4r
6SYCs4KMr+p7CjFg/a7IdepLQ3txrZecrBxoG5mBDYgCJCfLBu0CAwEAAaOBpzCB
pDAdBgNVHQ4EFgQUWQI/JOoU+RrUPUED63dMfd2JMFkwdQYDVR0jBG4wbIAUWQI/
JOoU+RrUPUED63dMfd2JMFmhSaRHMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIEwpT
b21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGSCCQDt
HKtpST2WSTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4ICAQBwGbAmiLHE
jubdLeMygwrV8VjlOVxV41wvRi6y1B5Bdvh71HPoOZdvuiZOogzxB22Tzon6Uv5q
8uuAy37rHLlQTOqLwdLJOu/ijMirAkh13gQWt4oZGUDikyiI4PMNo/hr6XoZWUfU
fwmcAzoEMln8HyISluTau1mtQIDgvGprU472GqC4AC7bYeED+ChCevc7Ytjl4zte
/tw8u3nqrkESYBIA2yEgyFAr1pRwJPM/T1U6Ehalp1ZTeQcAXEa7IC6ht2NlN1FC
fk2KQmrk4Z3jaSVv8GxshA354W+UEpti0o6Fv+2ozkAaQ1/xjiNwBTHtgJ1/AG1j
bDYcCFfmYmND0RFjvVu7ma+UNdKQ+t1o7ip4tHQUTEFvdqoaCLN09PcTVgvm71Lr
s8IOldiMgiCjQK3e0jwXx78tXs/msMzVI+9AR9aNzo0Y42C97ctlGu3+v07Zp+x4
6w1rg3eklJM02davNWK2EUSetn9EWsIJXU34Bj7mnI/2DFo292GVNw1kT5Bf4IvA
T74gsJLB6wacN4Ue6zPtIvrK93DABAfRUmrAWmH8+7MJolSC/rabJF3E2CeBTYqZ
R5M5azDV1CIhIeOTiPA/mq5fL1UrgVbB+IATIsUAQfuWivDyoeu96LB/QswyHAWG
8k2fPbA2QVWJpcnryesCy3qtzwbHSYbshQ==
-----END CERTIFICATE-----

`
)

func main() {
	err := validateCertificate([]byte(CERTIFICATE))
	if err != nil {
		fmt.Println("error:", err)
	}
}

func validateCertificate(data []byte) error {
	var exists bool
	for len(data) > 0 {
		var block *pem.Block
		block, data = pem.Decode(data)
		if block == nil {
			return errors.New("failed to parse PEM block")
		}
		if block.Type != "CERTIFICATE" {
			return errors.New("unexpected block type in certificate: " + block.Type)
		}
		if _, err := x509.ParseCertificate(block.Bytes); err != nil {
			return err
		}
		exists = true
	}
	if !exists {
		return errors.New("failed to locate certificate")
	}
	return nil
}
```

**Environment:**

- Contour version: v0.15.3
- Kubernetes version: (use `kubectl version`): n/a
- Kubernetes installer & version: n/a
- Cloud provider or hardware configuration: n/a
- OS (e.g. from `/etc/os-release`): n/a

**Comment by jpeach** [comment]
I will work on this today.

**Comment by jpeach** [comment]
envoy uses `PEM_X509_INFO_read_bio`, which calls [`PEM_read_bio`](https://www.openssl.org/docs/man1.1.0/man3/PEM_read_bio.html) in a loop. At the end of file, if there's no more PEM blocks, `PEM_read_bio` returns and error (with code PEM_R_NO_START_LINE), and [`pem.Decode`](https://godoc.org/encoding/pem#Decode) returns a  nil `Block` that is indistinguishable from an invalid PEM block.
