### ISSUE TITLE
Emphasize which objects annotations apply to

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#1826]
The annotations documentation tells you which object the annotation should be applied to in the section headings. However, when I was reading these docs, my eyes slid over that part and focused on the content.

We could emphasize the objects by adding an initial sentence to each section, like `the following annotations may be specified on "FooType" objects` ...

**Comment by davecheney** [comment]
Thanks for raising this. This has been a perennial problem and while I personally think these are annotations that belong on the service, the usability of this mechanism is sub optimal.

Rather than further wordsmithing the document I think finding a way to replicate this information on the httpproxy document is the better solution, I know @stevesloka has strong opinions on this.

**Comment by jpeach** [comment]
> On 30 Oct 2019, at 9:50 am, Dave Cheney <notifications@github.com> wrote:
> 
> Thanks for raising this. This has been a perennial problem and while I personally think these are annotations that belong on the service, the usability of this mechanism is sub optimal.
> 
> Rather than further wordsmithing the document I think finding a way to replicate this information on the httpproxy document is the better solution, I know @stevesloka has strong opinions on this.

The annotations will still be with us for along time, so I think it's worth taking a few minutes to improve them.

**Comment by SDBrett** [comment]
I could try to make this clearer while working on the annotations page to move depreciated annotations further towards the bottom of the page.

**Comment by stevesloka** [comment]
I think this is also another place for status to come in. We could somehow label that we're sending "http" traffic to some service vs sending "h2c" traffic or something. Just talking off the top of my head, but some feedback to the user as to how Contour configured that route.

**Comment by stevesloka** [comment]
Seems lame, but could also have Contour look for these annotations on the Proxy document and throw a warning up saying they are invalid.

**Comment by jpeach** [comment]
On Oct 30, 2019, at 1:53 PM, Steve Sloka <notifications@github.com> wrote:

﻿

Seems lame, but could also have Contour look for these annotations on the Proxy document and throw a warning up saying they are invalid.

Yup I filed a separate issue to cross check annotations. It should be straightforward, but helps users get a correct config.
