### ISSUE TITLE
Migration of projectcontour.io from Jekyll3 to Jekyll4

### ISSUE THREAD

**Issue by SDBrett** [projectcontour/contour#1827]
# Upgrade to Jekyll 4 investigation

## Motivation
    
The projectcontour.io site is currently built using Jekyll 3.8.5 which is close to 12 months old and 2 releases behind current. Jekyll 4 improves build times and provides many bug fixes and new features.

## Testing
    
Testing has been performed on a local computer using the `site-devel` make target from contours makefile. The makefile was updated to use the docker container `jekyll/jekyll:4`. The file /site/gemfile has been updated to allow control over plugin versions.

Sucessful builds were manually compared the live projectcontour.io site.

## Findings

**Markdown Processor:** Jekyll 4 no longer supports redcarpet as a markdown processor, this was changed to kramdown. This did not appear to break anything on the site, links and layout matched the live site. The only difference found was on the getting-started.md page where the `--` used on the line `- Depending on your configuration, new cloud resources -- for example, ELBs in AWS`. When using redcarpet, this was processed as two hyphen characters `--`, however, when using kramdown this was processed as a single hyphen `-`. This behaviour difference was not present with inline or multiline code blocks.

**Plugin usage inconsistency:** There is an inconsistency between [Jekyll documentation](https://jekyllrb.com/docs/plugins/installation/) on using plugins and results experienced. Jekyll should allow for the choice between using a gemfile or configuring the plugins property in _config.yaml, testing results displayed that this was not always true.
The specific inconsistency found was when using the plugin `jekyll-seo-tag`; if this was declared in gemfile but not _config.yaml and unknown tag error would crash the build process during markdown processing. 

To counter this issue the gemfile should be used to control plugin versions while maintaining a plugin list in _config.yaml.

**jekyll-github-metadata:** This plugin does not have a Jekyll 4 compatible release, the gemfile must be configured to use the master branch on GitHub. A an [issue](https://github.com/jekyll/github-metadata/issues/169) has been raised but there has been no confirmation on a new at this stage.

The risk of using a nightly build could be mitigated by forking the plugin repo to provide control.

## Conclusion
    
Advantages provided by the Jekyll 4 release not overly significant based on the site’s simplicity, however, a Jekyll major version change is less complex while the site is small and simple. 

The jekyll-github-metadata plugin can be mitigated without significant impact on site management.

The change in markdown processors appears to have very little impact on the site and no breakages have been detected.

Migration risks are minimal and reasonable.

#### Follow up actions

- Further validate plugins which are required and remove those which are not
- Peer review site build with Jekyll 4 for inconsistencies

**Comment by davecheney** [comment]
Assigning to @jonasrosland as he is the owner of the family of open source sites.

**Comment by stevesloka** [comment]
Fixed in #1828
