### ISSUE TITLE
Discuss site image for building

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1852]
**Please describe the problem you have**
Working on the projectcontour.io site (aka Jekyll), there is a makefile task to automate the site, however, each run of it requires all the Gems to be downloaded. 

The first rev of this from @jpeach had a Dockerfile which stored a cache of this essentially in an image but in a review that was taken out. 

I've been doing a bunch of work with the site and found that having that image is super handy. I'm also proposing (#1851) that we add a check to the site for links. Downloading all the Gems each time will add to our build times. 

This issue is to discuss if we want to use a default image that gets built to save us time? 

For now and my own personal needs, I built this: https://github.com/stevesloka/contour-site

**Comment by jpeach** [comment]
I'm +1 on this.  Remember, building a Docker image doesn't necessarily mean publishing it to an official repository.

**Comment by SDBrett** [comment]
I'm happy to work on using a Docker image and relevant documentation for building a local test site. I think that it's a good idea because managing Ruby gems can be painful to mange and this provides consistency for those working on the site.

**Comment by davecheney** [comment]
`bundle exec jekyll serve --livereload` just works for me. I agree getting the right version of ruby installed is a moderate annoyance (personally I use macports and it just works). If you want to work on a docker builder for the site go for it, but please don't publish this as an image, it is not a deliverable of this project.
