### ISSUE TITLE
site: Update links to use `latest` variable

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1855]
**What steps did you take and what happened:**
There are various places throughout the code that references docs links (e.g. `/docs/v1.0.0/something`). We should update these links to use a variable such that we don't hard code the `v1.0.0` unless desired.

**Comment by SDBrett** [comment]
Unfortunately Jekyll doesn't support the use of variables with links created using `{% link %}. I've made comparisons on link insertion methods in issue #1891

**Comment by jpeach** [comment]
We changed a number of these to use `site.latest` in d4b3c89ebf83b678bfbc94b4cf58bca0fedf9e7a
