### ISSUE TITLE
docs: update deploy-options.md for kind (redux)

### ISSUE THREAD

**Issue by ghchinoy** [projectcontour/contour#1858]
The section in /deploy-options (/site/_guides/deploy-options.md) for kind is a little different now and I'd like to add a few things to make it clearer

* change /site/_guides/deploy-options.md and /examples/kind-expose-port.yaml to reference exposing port 80 (rather than 8080), and adding 443
* add a sentence or two on how to add Contour to kind (via `kubectl apply -f examples/contour`)
* add a new file to /site/examples called kuard-httpproxy.yaml and reference this file from the /site/_guides/deploy-options.md (as https://projectcontour.io/examples/kuard-httpproxy.yaml doesn't exist)

**Comment by ghchinoy** [comment]
This suggestion is to align the various ways of showing the use of Kind + Contour.
There's a great post by Steve here ([Kindly running Contour](https://projectcontour.io/kindly-running-contour/)) shows using a config yaml for Kind which exposes 80/443 (rather than 8080 / 8443). I don't want to ascribe intent, but I think having 80/443 make a quick local usage easier to use. A subsequent (also great) [blogpost on HTTPProxy](https://projectcontour.io/httpproxy-in-action/) is based upon this configuration.

Both the example kind config yaml in the repo https://github.com/projectcontour/contour/tree/master/examples/kind and the site's [Deployment Options](https://projectcontour.io/docs/v1.0.0/deploy-options/) document ( git [deploy_options.md](https://github.com/projectcontour/contour/blob/master/site/docs/v1.0.0/deploy-options.md)) show using 8080 for a Kind config. Unfortunately, the examples/walkthrough in Deployment Options for Kind is somewhat incomplete. 

1.  it's unclear how to install Contour from this page, 
2. in the HTTPProxy section, there's a 404 to https://projectcontour.io/examples/kuard-httpproxy.yaml 

For 1,  I'd suggest reiterating something like `kubectl apply -f examples/contour`
For 2, II'd suggest clarifying this by adding an HTTPProxy kuard example file and also the instructions to `kubectl apply -f site/examples/kuard-httproxy.yaml` (I'm not sure where this file should go, /site/examples looks good, but there's also an /examples)

Lastly, I'm not clear how the url forms of the files (a la https://projectcontour.io/examples/kuard-httpproxy.yaml ) get referenced, so the previous suggestions require cloning the repo to apply. I do think it's easier for users to have a publicly accessible yaml rather than having to clone the whole repo, but that's an aside.

**Comment by davecheney** [comment]
Thanks for the reply. There are many things here so please forgive me if I don't address them all

> Both the example kind config yaml in the repo https://github.com/projectcontour/contour/tree/master/examples/kind and the site's Deployment Options document

I think this is not a deployment manifest, its some kind of configuration file for kind. I have no position on if it should use 80/443 or 8080/8443 other than I would prefer that deploying inside kind was as close to deploying _not_ inside kind.

> it's unclear how to install Contour from this page,

Could this be addressed by referring back to the getting started link instead? My general approach when faced with multiple installation options is to push people to reduce them rather than double down on documenting the differences.

> in the HTTPProxy section, there's a 404 to https://projectcontour.io/examples/kuard-httpproxy.yaml

What is the smallest change that can be made to address this? It should be possible to fix the broken link independently of the rest of this discussion.

> For 1, I'd suggest reiterating something like kubectl apply -f examples/contour

Agreed. Why can't this be simply "follow the getting started guide". What is it about kind that makes it not like a usual k8s cluster, and if there is a difference, can that small difference be called out at the end of the usual getting started page?

> For 2, I'd suggest clarifying this by adding an HTTPProxy kuard example file and also the instructions to kubectl apply -f site/examples/kuard-httproxy.yaml (I'm not sure where this file should go, /site/examples looks good, but there's also an /examples)

This seems independant of the issues using kind, would you please take this to a seperate issue for discussion. In general I think issues that are focused on a specific deliverable, with a straight forward definition of done are easier to complete. This seems to fit that definition well.

> As an aside, I'm not clear how the url forms of the files (a la https://projectcontour.io/examples/kuard-httpproxy.yaml ) get referenced, so the previous suggestions require cloning the repo to apply.

**Comment by ghchinoy** [comment]
Thank you so much for the replies!

> > Both the example kind config yaml in the repo https://github.com/projectcontour/contour/tree/master/examples/kind and the site's Deployment Options document

> I think this is not a deployment manifest, its some kind of configuration file for kind. I have no position on if it should use 80/443 or 8080/8443 other than I would prefer that deploying inside kind was as close to deploying not inside kind.

You're correct here - this is just a setup for the Kind cluster to expose one of the nodes to the host and doesn't have anything to do with Contour, really. ref. https://kind.sigs.k8s.io/docs/user/quick-start#mapping-ports-to-the-host-machine

> > Could this be addressed by referring back to the getting started link instead? My general approach when faced with multiple installation options is to push people to reduce them rather than double down on documenting the differences

Yes, can definitely do this, and I agree with the principle.

>> in the HTTPProxy section, there's a 404 to https://projectcontour.io/examples/kuard-httpproxy.yaml

> What is the smallest change that can be made to address this? It should be possible to fix the broken link independently of the rest of this discussion.

I think you're correct here, too - The smallest change would to be to add (back?) in the kuard-httpproxy.yaml to the `site/examples` as you mentioned. I can create a separate issue and PR for this.

Re-reviewing the deploy-options.md, there's no real need to have the kind-config changed at all.

I'll close this issue and open another for the above mentioned smallest change to rectify the missing file reference for kuard-httpproxy.yaml.
