### ISSUE TITLE
Site discussion: Evaluate value of Jekyll plugins

### ISSUE THREAD

**Issue by SDBrett** [projectcontour/contour#1860]
Jekyll plugins increase site build times and complexity of Ruby gem management and introduce additional dependencies for the site to function.

Do you think that there is value to spending time evaluating the plugins used to build the site and removing those which are unused or not of sufficient value?

**Comment by davecheney** [comment]
Assigning to @jonasrosland as he is the owner of the family of open source sites.

**Comment by SDBrett** [comment]
All plugins specified are performing a purpose, no need for clean up found.
