### ISSUE TITLE
Site Discussion: Pull external JS into repo

### ISSUE THREAD

**Issue by SDBrett** [projectcontour/contour#1861]
The site currently references JS files from external sources as part of the loading process. Locally caching these files into the project and site build will help present site load errors due to the referenced external location being unavailable and governance over the supply chain.

This approach does have the draw back of introducing some overhead as the cached JS scripts will need to manually updated, but does provide an additional security layer.

**Comment by davecheney** [comment]
I'm fine with this caching as part of the netlify site build operation if you can figure out how to integrate that into the process. I don't want to host yet another copy of jquery in our repo.
