### ISSUE TITLE
Dynamic forward proxy support

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#1890]
A colleague had a use case where a service they were running vends signed URLs to a separate service, but they want to proxy that URL internally.

I think that something approximating this could be implemented using the envoy [dynamic forward proxy](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_proxy#arch-overview-http-dynamic-forward-proxy) support. Instead of routing to a in-cluster `Service`, we could use and [ExternalName](https://kubernetes.io/docs/concepts/services-networking/service/#externalname) service and then build a forward proxy configuration that points to the DNs name specified in there.

We would probably need to ensure that we configure TLS to the upstream (with validation), and enable host, header and path rewriting as these features become available.

**Comment by stevesloka** [comment]
@jpeach I think we have this working now with externalName and host rewrite? Please confirm if this solves this issue.

**Comment by jpeach** [comment]
Yep, I think it does.
