### ISSUE TITLE
Add support for Envoy xDS v3.

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#1898]
A year after Envoy ships xDS v3, they plan to remove support for v2. It's not entirely clear to me what that entails, but it seems likely we will need to add and qualify v3 support and maybe support v2 at the same time.

See envoyproxy/envoy#6271

**Comment by jpeach** [comment]
Related to #2132

**Comment by jpeach** [comment]
xref https://github.com/envoyproxy/envoy/issues/10943

**Comment by bgagnon** [comment]
According to https://www.envoyproxy.io/docs/envoy/latest/api/api_supported_versions, the V2 API will stop being supported at the end of _this year_.

**Comment by skriss** [comment]
We should move this into Prioritized -- we're aware of the EOY deprecation deadline and are working towards adding v3 support.

**Comment by stevesloka** [comment]
I'm going to poke around a bit to see how we might address this migration.

**Comment by skriss** [comment]
@stevesloka think we can consider this closed now?

**Comment by stevesloka** [comment]
Yup I think so! 🎉
