### ISSUE TITLE
Ability to configure ConnectTimeout

### ISSUE THREAD

**Issue by awprice** [projectcontour/contour#1902]
**Please describe the problem you have**
We are seeing the occasional, low frequency issue with envoy failing to connect to an upstream service. Envoy reaches the current connect timeout of 250ms and fails to connect to the upstream. 

The `envoy_cluster_upstream_cx_connect_fail` metric is increased when this occurs and the client subsequently receives `upstream connect error or disconnect/reset before headers. reset reason: connection failure`.

We are currently looking at the root cause of the occasional timeouts, but would also like the functionality to configure the hard coded default ConnectTimeout of 250ms: https://github.com/projectcontour/contour/blob/ba76c05a08ac9ecff5c95ff2274425cca5a47870/internal/envoy/cluster.go#L38

**Comment by davecheney** [comment]
@awprice thanks for the issue. If you could configure this value, what would be a sensible value in your environment?

**Comment by awprice** [comment]
@davecheney Yet to be determined, we are still trying to fully understand the problem before we can commit to a sensible value.

cc @youngnick

**Comment by davecheney** [comment]
Thanks for your reply. To be transparent the value of 250ms was chosen arbitrary years ago. If it’s incorrect for your use case it’s likely incorrect for others. I we change that value ideally I’d like to choose a default value which works for a wide variety of users. If we make it configurable there should be at least a sensible default that works for the majority of use cases as foisting the requirement for each contour user to choose a value for connect timeout isn’t something I want to see for the product.

**Comment by awprice** [comment]
👍 @davecheney. @youngnick explained to me in person that ideally this should be a default that would be applicable for most people.

**Comment by davecheney** [comment]
Also this is the tcp connect timeout, not an l7 request/response timeout. The rationale for the 250ms connect timeout was If the backend isn’t ready to accept(1) a connection immediately then it’s probably unhealthy. 

The current value may be incorrect, but not by an order of magnitude. Waiting seconds for a backend to SYN/ACK is a symptom of a more serious problem so making the connect timeout configurable for such values without strong guidance feels like giving free foot gun ammunition.

**Comment by davecheney** [comment]
@awprice ping, what's the next steps for this issue?

**Comment by awprice** [comment]
@davecheney Apologies for the late reply. Going to close this out, more work is needed on my part to further understand the issues we are facing.
