### ISSUE TITLE
Check site for broken links using travis

### ISSUE THREAD

**Issue by SDBrett** [projectcontour/contour#1909]
[html-proofer](https://github.com/gjtorikian/html-proofer) is a widely used Ruby gem for performing various tests against websites.

This gem can help significantly reduce the chance of broken link appearing on the website by testing them during the build process. The `.travis.yml` file will be updated to perform a Jekyll build and test the links to ensure that they are valid.

- [x] Update `.travis.yml` to perform html-proofer
- [x] Add directory change checking to reduce build times.

**Comment by davecheney** [comment]
I would prefer this runs in netlify as a post ci step and blocks publishing of the site.

**Comment by SDBrett** [comment]
It looks like the option to do in Netlify this is still a closed beta.

https://www.netlify.com/blog/2019/10/16/creating-and-using-your-first-netlify-build-plugin/

**Comment by davecheney** [comment]
If the goal is to spot broken links, does this need to run on every commit?
on every site build? If not are there external web services that can spot
this?

In addition to broken links, what about stale links, references to
docs/1.0.0 when we've moved on to later releases, and so forth?

What is the underlying problem to be solved here?

**Comment by SDBrett** [comment]
I don't know external services which offer this level of checking for broken links.

I can add configuration to `.travis.yml` which will only run the check if the commit includes changes to the file within /site/.

This will resolve broken links which are internal or external. If you have a link to a page within docs/v1.0.0 and that page is deleted it will detect a broken link.

The primary problem that this addresses is detection of links which have been incorrectly entered into the `.md` files, most likely because of typos. Jekyll only validates links during build if they are inserted with `{% link %}` or `{% post_url %}`.

Errors are most likely to occur during the release of a new version, particularly documentation links.

**Comment by jpeach** [comment]
@SDBrett was this fully fixed in #1848?

**Comment by SDBrett** [comment]
> @SDBrett was this fully fixed in #1848?

Yeah, closing.
