### ISSUE TITLE
docs: missing kuard-httpproxy.yaml referenced in deploy options

### ISSUE THREAD

**Issue by ghchinoy** [projectcontour/contour#1920]
When going through the instructions for using Contour on Kind, here ([deploy-options](https://projectcontour.io/docs/v1.0.0/deploy-options/)), the referenced file https://projectcontour.io/examples/kuard-httpproxy.yaml does not exist.

I expected that either `curl`'ing or `kubectl apply -f`'ing the url would provide the appropriate yaml example for the kuard HTTPProxy.

Suggestion is to add in the kuard-httpproxy.yaml to the `site/examples` repo tree.

ref #1858

**Comment by stevesloka** [comment]
Fixed in https://github.com/projectcontour/contour/pull/1926
