### ISSUE TITLE
Forward auth support

### ISSUE THREAD

**Issue by jieyu** [projectcontour/contour#1922]
**Please describe the problem you have**

We're looking for some equivalent functionality of forward auth in Traefik
https://docs.traefik.io/middlewares/forwardauth/
https://github.com/thomseddon/traefik-forward-auth

Is there any plan to support something similar to that? This is for the case when the user app does not have built-in support for authentication/authorization, and would like to have a general way to do that in the proxy.

**Comment by stevesloka** [comment]
Hey @jieyu, this is currently an issue on the backlog (https://github.com/projectcontour/contour/issues/432). But it is something that I really would like to get added. We're going to be doing some planning for the next release (after 1.1), so we will have more details after 1.1 ships.

**Comment by jpeach** [comment]
Relating #432, #433 , #986 and #1014 which are all touching on aspects of authentication support.

**Comment by jpeach** [comment]
Related #68

**Comment by MrSaints** [comment]
I've implemented a Contour / Envoy compatible `ext_authz` service to act as a forward authN middleware: https://github.com/MrSaints/forward-ext-authz-service

It is based on the same code, and flow used by Traefik's forward authN middleware. I've currently tested it with Pomerium.

**Comment by youngnick** [comment]
That looks really neat, thanks @MrSaints!
