### ISSUE TITLE
tls upstream validation fails with non-existent CA-secret in IngressRoute

### ISSUE THREAD

**Issue by movikbence** [projectcontour/contour#1924]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I am trying to set up end to end encryption in my environment. If the ca-secret exists in the cluster the validation seems to be working between envoy and the backend, but if I add a nonexistent ca-secret the validation fails, and I am able to run traffic to the backend.

CA-secret creation:
kubectl create secret generic ca-secret --from-file=ca-secret/ca.crt

Configuration files:

apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: e2e-encryption
spec:
  virtualhost:
    fqdn: external-hostname.example.com
    tls:
      secretName: external-tls-secret
  routes:
    - match: /
      services:
        - name: e2e-encryption-service
          port: 443
          validation:
            caSecret: **non-existent**
            subjectName: backend.example.com

Result:
kubectl get ingressroute -A
NAMESPACE   NAME                      FQDN                   TLS SECRET            FIRST ROUTE   STATUS    STATUS DESCRIPTION
default     e2e-encryption   external-hostname.example.com   external-tls-secret   /             invalid   route "/": service "e2e-encryption-service": upstreamValidation requested but secret not found or misconfigured

Although I noticed that it flaps between valid and invalid in the background, it gets generated again and again:
kubectl describe ingressroute -A
Name:         e2e-encryption
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"contour.heptio.com/v1beta1","kind":"IngressRoute","metadata":{"annotations":{},"name":"e2e-encryption","namespace"...
API Version:  contour.heptio.com/v1beta1
Kind:         IngressRoute
Metadata:
  Creation Timestamp:  2019-11-21T07:28:07Z
  Generation:          **1637**
  Resource Version:    23592572
  Self Link:           /apis/contour.heptio.com/v1beta1/namespaces/default/ingressroutes/e2e-encryption
  UID:                 
Spec:
  Routes:
    Match:  /
    Services:
      Name:  e2e-encryption-service
      Port:  443
      Validation:
        Ca Secret:     non-existent
        Subject Name:  backend.example.com
  Virtualhost:
    Fqdn:  external-hostname.example.com
    Tls:
      Secret Name:  external-tls-secret
Status:
  Current Status:  valid
  Description:     valid IngressRoute
Events:            <none>

The backend configuration is good, and the certificates&keys are too.
Anyway, when the CA-secret exists, but not matching with backend crt and key, the validation fails which is correct.

**Environment:**

- Contour version: 0.15
- Kubernetes version: (use `kubectl version`): v1.15.2
- Kubernetes installer & version: v1.14.2
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from `/etc/os-release`): centOS

**Comment by davecheney** [comment]
Thank you for your issue. Contour 1.0.0 is the current supported release. Are you able to upgrade and confirm if the problem is fixed or persists?

**Comment by movikbence** [comment]
Yes, I've tried it, and the problem is still in place.

**Comment by davecheney** [comment]
How many contour pods do you have deployed? Status flapping can be caused when multiple contour pods are deployed with leadership election disabled.

**Comment by movikbence** [comment]
I've used the file you provided on contour page https://projectcontour.io/quickstart/contour.yaml
 to deploy the service, and the deployment for contour contains two replicas.

By the way the flapping is gone in 1.0 (Faulty work hasn't, the ingressroute becomes valid, traffic works)

**Comment by davecheney** [comment]
Thank you for the update 

> By the way the flapping is gone in 1.0 (Faulty work hasn't, the ingressroute becomes valid, traffic works)

I’m sorry I don’t think I understand. Could you say that again a little differently?

**Comment by movikbence** [comment]
So, I assume we are talking about only 1.0, right?
If that is the case, the steps I have done:

Deploy contour, generate certificates, make ingressroute and apply it with a nonexistent CaSecret.
Although the secret not exists in the environment, still the ingressroute becomes valid. So far, with version 0.15 that validation did not succeeded without the existence of the secret, it was flapping between valid and invalid status.

Now as I said it becomes valid, and I am able to get response from the backend without the TLS upstream validation between envoy and the backend server. It seems like that function does not work at all.

**Comment by tsaarni** [comment]
I succeeded reproducing this myself and I think I found the cause of the problem. I opened a PR for this.

**Comment by movikbence** [comment]
Thank you for the help, it was so fast.
Can you tell me, if that change will be only available in the next release, which is 1.?
Thank you!

**Comment by davecheney** [comment]
Yes, this will ship with 1.1. I don't have an ETA for 1.1 at the moment but
please follow the 1.1.0 milestone for updates.
