### ISSUE TITLE
tls upstream validation fails with non-existent CA-secret in IngressRoute contour 1.0

### ISSUE THREAD

**Issue by movikbence** [projectcontour/contour#1925]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Please check the referenced issue below:
https://github.com/projectcontour/contour/issues/1924

The configuration is the same like in the referenced issue, but the result changed a bit.
Now the "flapping" disappeared from the ingressroute generation, but it still got validated even if the ca-secret is nonexistent, and I am still able to run traffic without TLS upstream validation.

**Environment:**

- Contour version: 1.0
- Kubernetes version: (use `kubectl version`):v1.15.2
- Kubernetes installer & version:  v1.14.2
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from `/etc/os-release`):centOS

**Comment by davecheney** [comment]
As with #1924 Contour 1.0.0 is the current supported release. Are you able to upgrade and confirm if the problem is fixed or persists?

**Comment by movikbence** [comment]
I have tried with 1.0 and the problem is still in place.

**Comment by davecheney** [comment]
Thank you for confirming.
