### ISSUE TITLE
Broken Link on https://projectcontour.io/

### ISSUE THREAD

**Issue by brito-rafa** [projectcontour/contour#1927]
**What steps did you take and what happened:**
https://projectcontour.io/getting-started/ FAQ link points to
https://github.com/projectcontour/contour/tree/master/FAQ.md which gives 404

**What did you expect to happen:**
FAQ.md should exist?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version:
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by davecheney** [comment]
Thanks for spotting this, I've sent #1929 to fix it.
