### ISSUE TITLE
Investigate running ingress-controller-conformance in CI

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#1944]
We should investigate running [ingress-controller-conformance](https://github.com/kubernetes-sigs/ingress-controller-conformance) as part of our CI pipeline.

The necessary items here are:

- [ ] Get an upstream release for the conformance tests
- [ ] Add conformance tests flag to specify load balancer address
- [x] Scripting to bring up a kind cluster
- [ ] Scripting to pull the conformance tests and  run them against kind

**Comment by jpeach** [comment]
xref kubernetes-sigs/ingress-controller-conformance#12

**Comment by jpeach** [comment]
xref: kubernetes-sigs/ingress-controller-conformance#11

**Comment by jpeach** [comment]
The ingress conformance suite has made pretty steady progress; this issue can be worked on now.

**Comment by sunjayBhatia** [comment]
remaining upstream work to be done is just `Add conformance tests flag to specify load balancer address`?

**Comment by youngnick** [comment]
That would be so that the conformance tester can find the external address to look for; I'm not sure off the top of my head how we do that for kind at the moment, but I think the integration tests are the place to look.

**Comment by sunjayBhatia** [comment]
i'm able to get things working using `--ingress-status-address=envoy.projectcontour` in `kind` which is needed b/c the Envoy service load balancer address never gets set (`kind` doesnot support load balancer services all the way)

**Comment by sunjayBhatia** [comment]
Here's a draft PR to start running conformance in CI: https://github.com/projectcontour/contour/pull/3195

**Comment by sunjayBhatia** [comment]
I think this can be closed? The investigation is done and we have a commented out make target and CI pipeline merged in https://github.com/projectcontour/contour/pull/3195 that will be enabled once we finish Ingress v1 support
