### ISSUE TITLE
Version guides by moving to docs directory

### ISSUE THREAD

**Issue by SDBrett** [projectcontour/contour#1950]
The steps provided by a guide are written with relevance to a specific release version. 

It seems suitable that guides should be moved to the relevant directory under `site/docs`. This allows the users to look up guides specific to a version in the same manner that they will be looking up other documentation. 

The above also extends to classifying `/site/_resources/upgrading` as a versioned guide document.

Doing the above addresses issues: #1870 and #1854

**Comment by davecheney** [comment]
I would prefer not to version guides. I do not think we need to document things that are no longer supported. Rather than versioning the guides they should be updated to reflect the current way the product works if required.

**Comment by stevesloka** [comment]
> I do not think we need to document things that are no longer supported

This just forces folks to read git diffs or always run latest. 

The logs guide probably a good example, if we change how logs work we'll break other versions possibly. It hasn't happened yet so maybe just see how these docs progress over time and leave this decision for later.

**Comment by davecheney** [comment]
> This just forces folks to read git diffs or always run latest.

I know I'm pedantic about this but our support policy _is_ always run latest. If we want to change that policy we should have that discussion, not side step it by changing the documentation to _look_ like we support older versions. That will lead to confusion and hurt feelings.
