### ISSUE TITLE
HTTPProxy CRD should be structural and have pruning enabled

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour#1978]
As noted in https://github.com/projectcontour/contour/issues/1723#issuecomment-544307006, our CRDs are not structural, and can't have pruning enabled at the moment.

My latest investigation into this suggests that pruning requires (for CustomResourceDefinitions v1beta1):
- structural definitions (this should be taken care of by the tooling added in #1723)
- At least Kubernetes v1.15

This is complicated by the fact that we'll need to move to CustomResourceDefinitions v1 at some point, which requires *only* structural schemas, and enforces pruning by default. v1beta1 is now deprecated, as of v1.16. However, changing this will mean that Contour will require v1.16 at a minimum.

So, this issue is to record these details for now, until we are ready to mandate at least either v1.15 or v1.16 of Kubernetes.

**Comment by jpeach** [comment]
Blocked by https://github.com/projectcontour/contour/issues/2678
