### ISSUE TITLE
Ingress Status: Allow users to specify their own IP/FQDN

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1980]
From #1976 need to allow Status for Ingress to be specified by operator and not looked up from Envoy service. 

> Also, I think that it's important that our design here allow for other deployment methods - nginx gets around this by allowing you to either specify the service, or just IPs or FQDNs directly. Being able to cover 'monitor this service' and 'just let me specify the IPs or FQDNs' hits all the deployment scenarios I can think of, in cloud and otherwise.

_Originally posted by @youngnick in https://github.com/projectcontour/contour/pull/1976#issuecomment-560990500_

**Comment by jpeach** [comment]
Related to #403

**Comment by youngnick** [comment]
Fixed by #2421
