### ISSUE TITLE
External Name Host Rewrite

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1982]
# Background 
A use-case came up chatting with someone in the community that involves routing requests to external domains, so using Contour as a proxy to redirect requests to locations other than pods inside a Kubernetes cluster. 

Today Contour has support for `externalName` services. An externalName type service allows for a Kubernetes service to define a fqdn that when a request is made to it, the request is directed to that fqdn (e.g. foo.com). 

The one issue with how externalName is implemented today is that host header on the request sent to the externalName is not swapped, it includes the original host definition. 

## Example: 

- The fqdn & path, foo.com/something, is configured to route to the externalName: `extsvc`.
- `extsvc`: Is configured to route to: `bar.com`
- A request to: `foo.com/something` is then proxied to `bar.com/something`, however the host header field is still `foo.com`. 

# Proposal

Add a new field to the service struct called `rewriteHost`. When set to `true`, then the value of the externalName will be swapped in the Host header for proxied requests. This is a more straightforward approach solving a smaller use-case vs the next alternative proposal.  This allows for a host rewrite on only the services which target externalNames.

An alternative implementation would be to create a `rewriteHostPolicy` that gets attached to the VirtualHost struct allowing for a global host rewrite for that fqdn. This isn't needed for HTTPProxy since we can have multiple roots target the same child Proxy documents.

**Comment by jpeach** [comment]
A few notes:

* You need to both set the right Host header, and also use the right SNI name
* I think that a "header rewrite" policy at the same level as "path rewrite" is a better approach than a specific "rewriteHostPolicy"
* For external names in particular, can we just make sure they work right without extra configuration? We should just install the correct rewrites, etc without the user needing additional config

**Comment by stevesloka** [comment]
> I think that a "header rewrite" policy at the same level as "path rewrite" is a better approach than a specific "rewriteHostPolicy"

I wonder though if something like this should live higher up at the vhost level?

**Comment by jpeach** [comment]
> On 5 Dec 2019, at 1:12 pm, Steve Sloka <notifications@github.com> wrote:
> 
> I think that a "header rewrite" policy at the same level as "path rewrite" is a better approach than a specific "rewriteHostPolicy"
> 
> I wonder though if something like this should live higher up at the vhost level?

I think that rewriting headers is a useful feature, but I'm not sure that we should distinguish the host header.

**Comment by davecheney** [comment]
One of the things I had hoped for the various _*Policy_ types is because they are types, we could extend HTTPProxy in the future to define them at both the VirtualHost, HTTPProxy, Include, as well as Route levels as a way of defining "defaults" or values to be inherited or superseded as evaluation got close to the route stanza. We can start small, define header rewriting at the route level, which solves the problem we have today, and allow the same policy to be defined at a higher level at some later date.

**Comment by stevesloka** [comment]
Ok great! Here's the quick design for the host rewrite:

- This policy will be applied at the `Route` level
- `HostRewrite` allows a user to define what the value of the host header should be
- `ExternalServiceRewrite` allows a service of type external name to automatically become the host header during forwarding and only applies to upstreams with this type. 

**I'm a bit torn on "ExternalServiceRewrite", my initial idea was to reduce the config a user would need to configure both the HTTPProxy as well as the external service. I think we could omit this for the initial config and discuss to add later on if desired.** 

```
// HostRewritePolicy defines the attributes with host rewriting
type HostRewritePolicy struct {
	// HostRewrite defines the value of the host header will be
	// swapped during forwarding
	HostRewrite string
	// ExternalServiceRewrite swaps the value of the host header
	// for the value in the external service  during forwarding
	ExternalServiceRewrite bool
}
```

**Comment by jpeach** [comment]
> On 6 Dec 2019, at 2:57 pm, Steve Sloka <notifications@github.com> wrote:
> 
> Ok great! Here's the quick design for the host rewrite:
> 
> 	• This policy will be applied at the Route level
> 	• HostRewrite allows a user to define what the value of the host header should be

I'm not in favor of special-casing the host header. We should we just to header rewrite?

> 	• ExternalServiceRewrite allows a service of type external name to automatically become the host header during forwarding and only applies to upstreams with this type.
> I'm a bit torn on "ExternalServiceRewrite", my initial idea was to reduce the config a user would need to configure both the HTTPProxy as well as the external service. I think we could omit this for the initial config and discuss to add later on if desired.

I'm not sure why we should not just always reset the host header for an external service. There's very few cases where you can reasonably take a request for host A and just send it to host B expecting it to work.

**Comment by davecheney** [comment]
> I'm not in favor of special-casing the host header. We should we just to header rewrite?

Ironically (depending on your POV about Envoy's way of doing things) even things which are not headers (methods, urls, query params) are treated as headers via a magic syntax.

**Comment by stevesloka** [comment]
> I'm not sure why we should not just always reset the host header for an external service. There's very few cases where you can reasonably take a request for host A and just send it to host B expecting it to work.

What if the service you want to proxy to is off cluster and you still want to handle the request as it came to the k8s cluster originally. In that case you'd want to preserve the original header.

**Comment by jpeach** [comment]
> On 6 Dec 2019, at 3:09 pm, Steve Sloka <notifications@github.com> wrote:
> 
> I'm not sure why we should not just always reset the host header for an external service. There's very few cases where you can reasonably take a request for host A and just send it to host B expecting it to work.
> 
> What if the service you want to proxy to is off cluster and you still want to handle the request as it came to the k8s cluster originally. In that case you'd want to preserve the original header.

If the request is to example.foo.com and you use an external name to send that to example.bar.com, then the target has to do something magical to accept example.foo.com names. I suppose that you could do some sort of split DNS so that the cluster could resolve a service that was really example.foo.com as some other name. Seems like a stretch though :)

**Comment by stevesloka** [comment]
```
GET "Host: example.foo.com" http://example.foo.com --> (proxies to) --> "Host: example.foo.com" http://example.bar.com
```

Where `example.bar.com` is a service that exists and handles traffic for `example.foo.com` since when the request is received at `example.bar.com` the host is still `example.foo.com`.

That's a use-case that Gimbal could use where your externalName is another Envoy proxy sitting in another cluster.

**Comment by jpeach** [comment]
> On 6 Dec 2019, at 3:21 pm, Steve Sloka <notifications@github.com> wrote:
> 
> GET "Host: example.foo.com" http://example.foo.com --> (proxies to) --> "Host: example.foo.com" http://example.bar.com
> 
> Where example.bar.com is a service that exists and handles traffic for example.foo.com since when the request is received at example.bar.com the host is still example.foo.com.

So this would have to be some kind of split DNS configuration so that the thing serving "example.foo.com" could resolve as "example.bar.com" inside the cluster?

**Comment by davecheney** [comment]
Would something like this fit the bill?
```
spec:
  routes:
  - conditions:
     - prefix: /
     headerRewritePolicy:
     - replaceHeader:
        - key: host
           value: s3.example.com
```

**Comment by stevesloka** [comment]
Ahh your design makes more sense @davecheney (I shouldn't try and design APIs at 11:30 at night). =)

Looking forward, it would be nice to support adding/removing headers (#70), so maybe call it `headerPolicy` or something? Then we could add `addHeader` & `removeHeader` potentially in the future.

**Comment by davecheney** [comment]
> so maybe call it headerPolicy or something? 

on yes! much nicer

**Comment by jpeach** [comment]
Note that "add", "delete" and "replace" are all different cases, though AFAICT envoy doesn't support "replace" :-/

**Comment by davecheney** [comment]
> Note that "add", "delete" and "replace" are all different cases, though AFAICT envoy doesn't support "replace" :-/

Whoa, **record scratch**. But headers are a set, if we do add `Host: foo`, then the result will be `Host: original, foo`

**Comment by jpeach** [comment]
> On 9 Dec 2019, at 12:10 pm, Dave Cheney <notifications@github.com> wrote:
> 
> Note that "add", "delete" and "replace" are all different cases, though AFAICT envoy doesn't support "replace" :-/
> 
> Whoa, record scratch. But headers are a set, if we do add Host: foo, then the result will be Host: original, foo

I should have defined these terms :)

Here are all the cases I can think of:

1. Unconditionally add a header value (could result in multiple values)
2. Remove all existing values of a header and add the specified value
3. Remove any existing values a header  and add the specified value only if the header was already present
4. Delete all values of a header
5. Delete specific values of a header
6. Delete matched values of a header

Envoy has an "append" flag that I think can distinguish (1) and (2). It's not obvious whether you need to append if you want to add multiple values, but that could conflict with the cases above.

IIUC, the only header removal option is (4).

**Comment by stevesloka** [comment]
> AFAICT envoy doesn't support "replace" :-/

Replace is header rewrite? https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-field-route-routeaction-host-rewrite

**Comment by stevesloka** [comment]
So this does require us to set the `Sni` config on the upstream tls section. Right now in my PR I have this set automatically when an externalName service is used. Just wanting to confirm with the team this works or if we should introduce a new field to allow Sni to be specified.

**Comment by jpeach** [comment]
> On 13 Dec 2019, at 8:49 am, Steve Sloka <notifications@github.com> wrote:
> 
> So this does require us to set the Sni config on the upstream tls section. Right now in my PR I have this set automatically when an externalName service is used. Just wanting to confirm with the team this works or if we should introduce a new field to allow Sni to be specified.

At this stage, I agree we should set it automatically.
