### ISSUE TITLE
doc: HTTPProxy must have at least one route or include defined

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#1988]
From #1947, the HTTPProxy routes field is documented as

> HTTPProxy must have at least one route or include defined.

This is probably not correct, since TCPProxy could be valid instead.

**Comment by davecheney** [comment]
@jpeach is this resolved in #1974?

**Comment by jpeach** [comment]
> is this resolved in #1974?

No, I didn't want to bundle it with unrelated changes.

**Comment by jpeach** [comment]
Looks like we don't actually enforce that there must be routes ... investigating ...

**Comment by jpeach** [comment]
Closing. We can address this as part of #2141
