### ISSUE TITLE
Document Header-rewriting capabilities

### ISSUE THREAD

**Issue by mattmoor** [projectcontour/contour#2008]
Update site/docs/master/httpproxy.md to reflect the header-rewriting capabilities being added in https://github.com/projectcontour/contour/pull/2006 (see also #70).

**Comment by stevesloka** [comment]
I think we've got this documented in the section: `Request and Response Header Policies` (https://projectcontour.io/docs/v1.2.0/httpproxy/)

**Comment by jpeach** [comment]
Re-opening.

It turns out that we have a "Request and Response Header Policies" section and a "Header Policy" section, which document the same facility but differently. How about we use this issue to condense that?
