### ISSUE TITLE
site proof job did not run when site/ changed

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#2031]
https://github.com/projectcontour/contour/pull/2025 which changed site/ did not trigger the site proof job.

https://travis-ci.org/projectcontour/contour/jobs/623359710?utm_medium=notification&utm_source=github_status

**Comment by stevesloka** [comment]
Right now the `site-check` task is not part of the `check` task due to #2032

**Comment by skriss** [comment]
xref https://github.com/projectcontour/contour/issues/2624#issuecomment-648959329 and https://github.com/projectcontour/contour/issues/2624#issuecomment-648993471

**Comment by skriss** [comment]
It looks like the current reason for this is that https://github.com/projectcontour/contour/blob/master/hack/travis/travis-check-files-changed.sh checks for changes in the most recent commit only, but with Travis PR builds, the most recent commit is a merge commit where travis takes the PR changes and merges them into master, so there are never changes to `site/` in there.

However, we still need to resolve #2032, and now also https://github.com/projectcontour/contour/issues/2624, before we want to get this running for PRs.
