### ISSUE TITLE
Generate config file documentation

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2045]
To ensure that the Contour configuration file documentation is always up to date, we should generate it from code comments in the Contour source.

**Comment by jpeach** [comment]
Related to #2111

**Comment by jpeach** [comment]
xref #2621 #3023

**Comment by xaleeks** [comment]
Agreed.  Ideally it comes from some config system or CI/CD pipeline so we have full audit capabilities, know who made what changes and can tie this back to the specific release with a little bit of effort.  If user deploys an older version of Contour, they can also grab the older config file that goes with it.  This is not critical for us though, but it’d be a nice bonus
