### ISSUE TITLE
step-by-step TLS HOWTO link broken

### ISSUE THREAD

**Issue by surajssd** [projectcontour/contour#2055]
The link to ` step-by-step TLS HOWTO` is broken in https://github.com/projectcontour/contour/tree/v1.0.0/examples/contour#moving-parts

It links to https://projectcontour.io/guides/grpc-tls-howto which does not exist.

**Comment by jpeach** [comment]
Thanks @surajssd, it looks like this was dropped from the table of contents when we added versioned docs.
