### ISSUE TITLE
Changing envoy listening ports results in xDS error

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2060]
**What steps did you take and what happened:**

1. Start Contour with default arguments.
1. Restart Contour with `--envoy-service-http-port=80 --envoy-service-https-port=443`

Envoy throws an xDS error:
```
ERRO[0011] Error adding/updating listener(s) ingress_http: error updating listener: 'ingress_http' has a different address '0.0.0.0:80' from existing listener  code=13 connection=2 context=grpc node_id=envoy-frqhg response_nonce=1 version_info=2
```

**What did you expect to happen:**

I expected that Contour would restart the listeners in the new configuration.

**Environment:**

- Contour version: 3a23a30
- Kubernetes version: v1.16.3
- Kubernetes installer & version: kind version 0.6.1
- Cloud provider or hardware configuration:

**Comment by stevesloka** [comment]
Maybe docs on this behavior is a good first step? I'm not sure how frequently users might do this but agree it can be hard to track down if you don't know it's how it works today.
