### ISSUE TITLE
Break HTTPProxy document into separate pages.

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2070]
The HTTPProxy document is really long and it is hard to find the section that describe how to achieve specific tasks (especially since we lack good indexing and search). Now that we have generated API reference docs in #2069, let's use that as the primary reference page, and break the existing documentation into a set of task-centric or feature-centric pages. For example, "how to make a virtual host", "how to use the include mechanism", "route conditions", etc.

**Comment by skriss** [comment]
Yeah, and in the TOC it/they should be called something other than "HTTPProxy **Reference**", since there's also an "API Reference" page which is a true reference.

**Comment by jpeach** [comment]
Proposed breakdown of pages for the `Configuration` topic. Numbered items will become a page, items marked by a "#" indicate current headings on the `HTTPProxy.md` page whose content will be migrated.

```
1. HTTPProxy

# HTTPProxy Reference
## Key HTTPProxy Benefits
## Ingress to HTTPProxy
## Interacting with HTTPProxies
## HTTPProxy API Specification
## Status Reporting

2. HTTPProxy virtual hosts 

### Virtual Host Configuration
#### Fully Qualified Domain Name
#### Virtualhost aliases
### Restricted root namespaces

3. HTTPProxy Inclusion and Delegation

## HTTPProxy inclusion
### Conditions and Inclusion
### Configuring inclusion
#### Within the same namespace
#### Across namespaces
### Orphaned HTTPProxy children

4. TLS Termination

#### TLS
##### Fallback Certificate
###### Configuration
#### Permit Insecure
## Client Certificate Validation

## TCP Proxying
### TLS Termination at the edge
### TLS passthrough to the backend service
### TCPProxy delegation

5. Upstream TLS

#### Upstream TLS
##### Envoy Client Certificate
## Upstream Validation
##### Error conditions (for upstream validation)

6. Request Routing

### Conditions
#### Prefix conditions
#### Header conditions
### Routes
#### Multiple Upstreams
#### Upstream Weighting
#### Request and Response Header Policies
#### Traffic mirroring
#### Response Timeout
#### Load Balancing Strategy
#### Session Affinity
##### Limitations (of session affinity)

7. External Service Routing

### ExternalName
#### Proxy to external resource

8. Request rewriting

#### Path Rewriting
### Header Policy

9. CORS

#### CORS policy

10. Websockets

#### WebSocket Support

11. Backend Service Health Checking

#### TCP Proxy health checking
#### Per route health checking

12. Client Request Authorization

13. TLS Delegation

#### TLS Certificate Delegation

14. Annotations Reference

15. Contour API Reference
```

**Comment by youngnick** [comment]
Layout looks great to me.

**Comment by stevesloka** [comment]
Can we make the menu on the left reflect the toc of docs rather than inside each page?

**Comment by jpeach** [comment]
> Can we make the menu on the left reflect the toc of docs rather than inside each page?

AFAIK we can't make the left-most menu dynamic. We could possibly generate a fully expanded menu from parsing each document, but I don't plan to do that in the PR. However with smaller individual pages, the need for an intra-page menu is less, so hopefully most pages won't need it.
