### ISSUE TITLE
site: Quickstart / Getting started guides

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2109]
The quick-start and getting started guides need some updating. I'd like to have separate breakouts as to how to deploy contour to EKS, GKE, and AKS as well as Kind. 

Today there's a smattering of AWS and other docs intermingled and I'd like to make them clear depending on the environment folks are deploying Contour into. 

- [ ] AWS Docs
- [ ] GKE Docs
- [ ] AKS Docs
- [ ] Non-Cloud Docs

**Comment by jpeach** [comment]
We can also address some of these deployment scenarios with kustomize, see #2088
