### ISSUE TITLE
Update host networking deployment docs

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2117]
In the [deployment options](https://projectcontour.io/docs/v1.1.0/deploy-options/) documentation,  we see the following:

>  Envoy will listen directly on port 8080 on each host that it is running. This is best paired with a DaemonSet (perhaps paired with Node affinity) to ensure that a single instance of Contour runs on each Node.

There are 2 issues with this:
- The default deployment YAML has envoy listening on ports 80 and 443
- The default deployment YAML places envoy in a daemonset, not contour (which isn't necessary with split deployment)

**Comment by jpeach** [comment]
@stevesloka I think #2129 fixes this too?

**Comment by stevesloka** [comment]
@jpeach yup I think this is all resolved now.
