### ISSUE TITLE
Mark "kubernetes.io/ingress.class" supported on HTTPProxy

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2119]
If you set the "kubernetes.io/ingress.class" annotation on a HTTPProxy document, Contour will log a warning that it is unsupported. In fact, it is supported and works correctly. We should update the warning.

**Comment by davecheney** [comment]
Opps, this should be a pretty straight forward fix. @mattmoor can you live with the warning until 1.2 or do we need a 1.1.1 ?

**Comment by mattmoor** [comment]
Warning is fine, I hadn't even noticed it :)
