### ISSUE TITLE
DeepCopy unstructured HTTPProxy causes panic

### ISSUE THREAD

**Issue by awprice** [projectcontour/contour#2123]
**What steps did you take and what happened:**
When converting an HTTPProxy object to an unstructured object and then performing a DeepCopy on that unstructured object, a panic is experienced.

The following code can be used to replicate:

```go
package main

import (
	v1 "github.com/projectcontour/contour/apis/projectcontour/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
)

func main() {
	proxy := &v1.HTTPProxy{
		TypeMeta: metav1.TypeMeta{
			Kind:       "HTTPProxy",
			APIVersion: v1.SchemeGroupVersion.String(),
		},
		Spec: v1.HTTPProxySpec{
			Routes: []v1.Route{
				{
					Services: []v1.Service{
						{
							Weight: uint32(100),
						},
					},
				},
			},
		},
	}

	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(proxy.DeepCopyObject())
	if err != nil {
		panic(err)
	}

	unstr := &unstructured.Unstructured{Object:u}
	unstr.DeepCopy()
}
```

When run, results in:
```
panic: cannot deep copy uint64
```

**What did you expect to happen:**

For the above code to run without issue.

**Anything else you would like to add:**

I believe this is occurring due to the use of `uint32` for the `weight` (and other fields) in the HTTPProxy struct. I've manually changed the `weight` field in the `Service` struct from `uint32` to a signed integer and the code above runs fine.

Works:
```go
	// Weight defines percentage of traffic to balance traffic
	// +optional
	Weight int32 `json:"weight,omitempty"`
```

Looking at the Kubernetes external API codebase, no unsigned integers are used in the public structs - https://github.com/kubernetes/api, most likely for this reason.

**Environment:**

- Contour version: v1.1.0
- Kubernetes version: (use `kubectl version`): v1.15.7
- Kubernetes installer & version: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from `/etc/os-release`): N/A

**Comment by davecheney** [comment]
Thanks for raising this issue. I think we can change _some_ of these uints to ints pretty painlessly but there might be some that have a direct correlation with the value that envoy consumes so some care might need to be taken there.

The thing about using unsigned ints in general is the json schema makes harder for people to give negative values for weights.

**Comment by awprice** [comment]
Perfectly understand the reasoning behind the use of the uints. Is it possible to use validation rules in the schema to enforce that negative values aren't used? i.e. `minimum: 0`
