### ISSUE TITLE
Makefile: site-devel task does not allow for site reload

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2125]
The make task `site-devel` which hosts the documentation development site has `--livereload` enabled, however, the livereload port is not exposed from the container which blocks the live reload from happening.

**Comment by jpeach** [comment]
> On 17 Jan 2020, at 8:19 am, Steve Sloka <notifications@github.com> wrote:
> 
> The make task site-devel which hosts the documentation development site has --livereload enabled, however, the livereload port is not exposed from the container which blocks the live reload from happening.

For me, reloading happens automatically when file changes are detected, but I agree that we should expose the reload port too.
