### ISSUE TITLE
Ingress V1: path matching mode

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2135]
Support Ingress V1 path changes:

https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md#path-as-a-prefix

> Paths proposal

> Explicitly state the match mode of the path.
> Support the existing implementation-specific behavior.
> Support a portable prefix match and future expansion of behavior.
> Add a field ingress.spec.rules.http.paths.pathType to indicate the desired interpretation of the meaning of the path

**Comment by jpeach** [comment]
https://github.com/cmluciano/kubernetes/pull/2

**Comment by sunjayBhatia** [comment]
So we already support regex path matching on Ingress resources but the current implementation is such that the path match type is ignored if you put something in the path field that "looks like" a regex.

Seems like this regex path match deal is better suited for just the `ImplementationSpecific` path match type and should be documented as such, however that would be a breaking change.

So moving forward how does this sound:
- If you provide a path that "looks like" a regex, you will get a regex match in practice, no matter what you set on the path type
  - Another option would be to honor the path type set and only do a regex match if you set the type to implementation specific
  - We could also do the "looks like regex" check if you don't specify a path type
- If you do not specify a path match type, you get a prefix match
- If you specify a prefix path match type, you get a prefix match
- If you specify an exact path match type, you get an exact match
- If you specify an implementation specific path match type, you get a regex match

**Comment by youngnick** [comment]
We could also put a changelog note and change it, although that would also not be ideal. I anticipate that the Ingress code is going to be around a *long* time though, so we should make it as tidy as posisble.

If we don't want to do that, @sunjayBhatia's solution above seems like the only way.

**Comment by sunjayBhatia** [comment]
Another weird caveat that the spec wants: https://github.com/kubernetes-sigs/ingress-controller-conformance/blob/79bd068cbb31d77c2a060f61eea795f9791a3d48/features/path_rules.feature#L162

Prefix matches are not string prefix matches, but path label matches

See also https://kubernetes.io/docs/concepts/services-networking/ingress/#examples

```

Kind | Path(s) | Request path(s) | Matches?
...
Prefix | /aaa/bbb | /aaa/bbbxyz | No, does not match string prefix
```

**Comment by youngnick** [comment]
We specifically had to stop doing prefix matches using Go's Path support because of weird interactions with inclusion for HTTPProxy, but if we're going to meet the spec, maybe the Ingress validation code can just treat them as path labels.

**Comment by sunjayBhatia** [comment]
To close the loop what we ended up coming up with in office hours is the following:
- Exact match gives you exact matching
- Prefix match gives you path segment matching
- Implementation specific will give you a regex match if you supply a string that "looks like" a regex and otherwise a string prefix match
  - To ensure people relying on the old behavior have a path match they can use
  - If you don't specify a path match type right now you get "ImplementationSpecific" filled in for you, so this should hopefully seamlessly work for most cases

**Comment by shashankram** [comment]
> To close the loop what we ended up coming up with in office hours is the following:
> 
> * Exact match gives you exact matching
> * Prefix match gives you path segment matching
> * Implementation specific will give you a regex match if you supply a string that "looks like" a regex and otherwise a string prefix match
>   
>   * To ensure people relying on the old behavior have a path match they can use
>   * If you don't specify a path match type right now you get "ImplementationSpecific" filled in for you, so this should hopefully seamlessly work for most cases

I must admit this is a great way to blend additional functionality with simplicity. In the openservicemesh.io project that I work on, I am upgrading our Ingress capability to v1 and was wondering how `ImplementationSpecific` path types can be interpreted in a reasonable way, given that our software must work at present with multiple ingress controllers. Do I have permission to borrow the `looks like a regex` idea for `ImplementationSpecific` path matches? @maintainers (/cc @youngnick, @stevesloka)

**Comment by sunjayBhatia** [comment]
This path matching behavior was done b/c that was all Contour supported before implementing Ingress v1 fully and I want to say was that way b/c it mimiced the nginx Ingress implementation which came first? Someone who has been around longer can check me on that
