### ISSUE TITLE
Ingress V1: support spec.backend field rename

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2136]
Support Ingress V1 backend field rename.

https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md#backend-to-defaultbackend

> v1beta1 field | v1 | rationale
> -- | -- | --
> spec.backend | spec.defaultBackend | Explicitly mentions default

**Comment by skriss** [comment]
Closed by #3266.
