### ISSUE TITLE
Ingress V1: support for service backends

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2137]
Support Ingress V1 IngressBackend changes. The IngressBackend gets a new [ServiceBackend](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md#backend-types-proposal) field to replace the service name and port. It probably doesn't make sense for Contour to support backends other than Services.

https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md#alternative-backend-types

**Comment by sunjayBhatia** [comment]
The links in the issue are broken it seems, and the Ingress API seems to have settled on a more generic `Resource` backend: https://kubernetes.io/docs/concepts/services-networking/ingress/#resource-backend that is a `TypedLocalObjectReference`

**Comment by sunjayBhatia** [comment]
How do we select a port to forward traffic to with a `TypedLocalObjectReference`? Use the first one? Add a cluster/route for each port?

See
- `IngressBackend.Resource`: https://github.com/kubernetes/api/blob/v0.19.7/networking/v1/types.go
- `TypedLocalObjectReference`: https://github.com/kubernetes/api/blob/v0.19.7/core/v1/types.go#L5235-L5245

**Comment by sunjayBhatia** [comment]
Updated KEP link: https://github.com/kubernetes/enhancements/tree/c14615cbf22c760fd0a6cbb4e962c66260c98463/keps/sig-network/758-ingress-api-group#alternative-backend-types

**Comment by sunjayBhatia** [comment]
Ah this is definitely already finished by https://github.com/projectcontour/contour/pull/3266
