### ISSUE TITLE
Documentation: V1.1.0 Release Page Incorrect protocol Example

### ISSUE THREAD

**Issue by ryanelian** [projectcontour/contour#2156]
Continuing discussion from https://github.com/projectcontour/contour/issues/1962#issuecomment-578333524

**What steps did you take and what happened:**

Following the instruction for `protocol: https` feature from the V1.1.0 Release page: 

https://github.com/projectcontour/contour/releases/tag/v1.1.0

![image](https://user-images.githubusercontent.com/8892187/73118506-a899ad80-3f87-11ea-90f3-39481767c28a.png)

Upstream TLS did not work. **Surprisingly, the correct option is `protocol: tls`, NOT `protocol: https`!**

The HTTPProxy documentation did not help too because it was not updated: https://projectcontour.io/docs/v1.1.0/httpproxy

![image](https://user-images.githubusercontent.com/8892187/73118463-04176b80-3f87-11ea-9256-c4e42390924f.png)

**What did you expect to happen:**

The documentation reflects the correct use of the `protocol` option.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Used to use annotations in 1.0.0, migrated to `protocol` in 1.1.0

**Environment:**

- Contour version: 1.1.0
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
```
kubeadm version: &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:20:25Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: UpCloud 2 core 4 GB RAM
- OS (e.g. from `/etc/os-release`):
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by stevesloka** [comment]
Hey @ryanelian thanks for reporting this and sorry for the confusion on the field. I updated the release notes and also opened #2152
