### ISSUE TITLE
Update our Code of Conduct to Contributor Covenant v2.0

### ISSUE THREAD

**Issue by jonasrosland** [projectcontour/contour#2172]
**Please describe the problem you have**
We are currently using Contributor Covenant v1.2. We should update our Code of Conduct to Contributor Covenant v2.0. For enforcement contact information, see current Velero CoC:
https://github.com/vmware-tanzu/velero/blob/master/CODE_OF_CONDUCT.md

For Contributor Covenant v2.0, see https://www.contributor-covenant.org/version/2/0/code_of_conduct

**Comment by jpeach** [comment]
@jonasrosland Is this complete now?

**Comment by jonasrosland** [comment]
> @jonasrosland Is this complete now?

Yup! Closing.
