### ISSUE TITLE
Add Contour Operator Project

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour#2187]
**Please describe the problem you have**
Managing Contour consists of many different [resources](https://github.com/projectcontour/contour/tree/v1.1.0/examples/contour). It's difficult for novice users to understand the intricacies of managing the lifecycle of Contour in a production environment through Kubernetes resources directly.

The [operator pattern](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) has become well adopted for managing applications and components such as Contour. This request is to add a new project (i.e. "operator") to the projectcontour organization for managing Contour using the operator pattern.

/cc @youngnick @ironcladlou @Miciah

**Comment by timothysc** [comment]
If it's just for lifecycle mgmt I always debate if a full blown operator makes sense, I'd love to hear the logic.

**Comment by shyaamsn** [comment]
Below are the use cases that can be handled by an Operator:

1. Deployment 
There are several options when deploying contour. Operator could automate these based on user input

 - Exposing envoy service based on user input as NodePort or LoadBalancer or HostNetwork
 - Deploying envoy on selective hosts based on user provided node labels
-  Certificate generation for GRPC TLS communication between contour and envoy by either integrating with a cert manager like jetstack/cert-manager, or using contour cert-gen or Bring your own certificate by user
- DNS registration: DNS records could be created in cloud-provider's DNS if operator provides some top level domains which will be served by Contour. 


2. Scale up/down
 - Autoscaling envoy based on traffic metrics

3. Upgrade
-   Automation of contour upgrade without data plane downtime

4. Certificate rotation
- Rotate contour - envoy GPRC TLS communication certificates before they expire

5. Troubleshooting
https://projectcontour.io/docs/v1.1.0/troubleshooting/
- Automation of some of these troubleshooting steps to help operator debug ingress controller

Not sure if operator is right tool to achieve the above use cases. But, opening this up for discussion

**Comment by timothysc** [comment]
Couldn't these be a features of contour, what necessitates the need for a separate component?

**Comment by jpeach** [comment]
WRT deployment, we have discussed improving our support for helm #2050 and kustomize #2088. I have a separate [repo](https://github.com/projectcontour/contour/issues/2070) where I have been experimenting with kustomize and it looks quite promising.

The following deployment goals can be accomplished with kustomize:

> Exposing envoy service based on user input as NodePort or LoadBalancer or HostNetwork

https://github.com/jpeach/kustomize/tree/master/contour/configurations/kind

> Deploying envoy on selective hosts based on user provided node labels

https://github.com/jpeach/kustomize/tree/master/knative/configurations/contour/contour-external

**Comment by timothysc** [comment]
@jpeach we do similar things with kubeadm and should loop in @fabriziopandini and @neolit123

**Comment by youngnick** [comment]
With respect to improving the upgrade experience, @stevesloka has #145 with the PR #2177 describing his solution - we would like both Contour and Envoy upgrades to be as close to hitless as possible without any additionaly tooling.

For certificate rotation, we've discussed a few options including #2149 for using cert-manager or vault for managing those certificates, and @tsaarni is looking at improving the support for having the key rotation be more automatic in #2143.

**Comment by neolit123** [comment]
> Couldn't these be a features of contour, what necessitates the need for a separate component?

this is a good question. if a certain feature is not achievable as part of the core component and an operator pattern can solve that, the operator pattern should be considered.

but splitting the feature set between multiple components is not ideal.
the operator will introduce boiler plate that has to be maintained and because of that the list of missing features has to be evaluated carefully.

a Google Doc might be a good start for that.

> WRT deployment, we have discussed improving our support for helm #2050 and kustomize #2088. I have a separate repo where I have been experimenting with kustomize and it looks quite promising.

i'm personally not advocating the kustomize project, but i do like how helm are using templates.
if something can be solved with a templates or patches, then this should be part of the core.

**Comment by youngnick** [comment]
I should also be one hundred percent clear here that the current `contour certgen` command is in no way intended to be a viable long-term solution for managing certificates. It's intended to help people get a sample Contour install up and running, nothing more.

**Comment by danehans** [comment]
A few examples of operators that use kustomize:

https://github.com/coreos/prometheus-operator/issues/2391
https://hub.docker.com/_/microsoft-k8s-azure-databricks-operator
https://github.com/fluxcd/helm-operator/blob/master/docs/tutorials/get-started-kustomize.md

**Comment by danehans** [comment]
__Use Case:__ Have Envoy run without `hostPort`. This change requires several dep changes:

- ds/envoy use a service account 
- create envoy svc account
- envoy listener 80/443 > 8080/8443 in deploy/contour
- envoy containerPort 80/443 > 8080/8443 in ds/envoy
- envoy svc `targetPort` 80/443 > 8080/8443

**Comment by jpeach** [comment]
> Use Case: Have Envoy run without hostPort. This change requires several dep changes:

I think that this use case can be addressed by improved helm and kustomize support. It doesn't seem like a new controller would directly address this.

**Comment by jpeach** [comment]
*Use Case:* automatically inject Linkerd headers.

To integrate with Linkerd, every HTTPProxy needs to set a `l5d-dst-override` header. Since this is a burden for operators, and arguably outside the direct scope for Contour, an operator or admission controller could maintain the relevant header policy in all the proxies.

xref: #2089

**Comment by stevesloka** [comment]
I think for your header example, we should allow operators to define policies at the vhost level which roll down automatically. We had this in the design phases of IngressRoute. Another example is lbPolicy, an operator could define this at the top level and every route would inherit this default automatically.

**Comment by jpeach** [comment]
> I think for your header example, we should allow operators to define policies at the vhost level which roll down automatically. We had this in the design phases of IngressRoute. Another example is lbPolicy, an operator could define this at the top level and every route would inherit this default automatically.

That would definitely help. Note that in this case, the value needs to be different for each proxy, so it would need some sort of templating or variable substitution as well.

**Comment by danehans** [comment]
This [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/addons/0035-20190128-addons-via-operators.md) provides additional background on the benefits of operators.

**Comment by jpeach** [comment]
> This [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/addons/0035-20190128-addons-via-operators.md) provides additional background on the benefits of operators.

Thanks @danehans. I don't know that any current maintainers have bandwidth to take on an operator in the short term, but I'd definitely support you or others exploring this space.

**Comment by danehans** [comment]
> Thanks @danehans. I don't know that any current maintainers have bandwidth to take on an operator in the short term, but I'd definitely support you or others exploring this space.

@jpeach I'll take the lead on creating and maintaining the operator.

**Comment by youngnick** [comment]
There's a couple of things I think will be helpful for a Contour operator:
- figuring out how to break up our YAMLs to allow for optional components - @jpeach and I have discussed this, and there's some chat in the Helm issue #2050 about this, but I don't think it covers everything.
- checking in with the knative folks about what they do when repacking Contour. xref #2254 for this one.

Both of those things are kind of grouped under the "make Contour more installable" banner, I think.

**Comment by danehans** [comment]
@youngnick thanks for the details above. The operator proposed in this issue will abstract the Contour yaml config from a user through an API (CRD). The [cluster-ingress-operator](https://github.com/openshift/cluster-ingress-operator) supports a use case similar to https://github.com/projectcontour/contour/issues/2254 through the [IngressController](https://github.com/openshift/api/blob/master/operator/v1/types_ingress.go) API type. For example, the following `IngressController` will create an internal `type: clusterIP` service and an external `type: loadBalancer` service for the ingress controller (haproxy):

```
kind: IngressController
apiVersion: operator.openshift.io/v1
metadata:
  name: test
  namespace: test
spec:
  endpointPublishingStrategy:
    type: LoadBalancerService
```

The next example is similar to the one above, but provisions an NLB instead of a Classic ELB (default for AWS):
```
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: test
  namespace: test
spec:
  endpointPublishingStrategy:
    type: LoadBalancerService
    loadBalancer:
      scope: External
      providerParameters:
        type: AWS
        aws:
          type: NLB
```

Several endpoint publishing strategies are supported, see [here](https://github.com/openshift/api/blob/master/operator/v1/types_ingress.go#L208-L226) for details. I provide this information to illustrate how operators can provider declarative configuration management of an application such as Contour.

**Comment by jpeach** [comment]
> * checking in with the knative folks about what they do when repacking Contour. xref #2254 for this one.

IIRC, they repackage with some bespoke scripting. I think that kustomize would work OK for that purpose, and I've been able to make it work for a knative install.

**Comment by jpeach** [comment]
@danehans are you proposing an operator that implements the OpenShift IngressController type, or something more general?

**Comment by danehans** [comment]
@jpeach the proposed operator will not implement the OpenShift IngressController type. I was just using that as an example.

**Comment by jpeach** [comment]
I created https://github.com/projectcontour/contour-operator to host exploring the options and utility of building an operator for Contour. I don't think the current Contour maintainers have strong opinions on an operator, but we are happy to support this and let anyone who is interested drive it forward.

**Comment by danehans** [comment]
Thanks for creating the repo @jpeach.
