### ISSUE TITLE
Move off Travis to a different CI system (GitHub Actions or CircleCI)

### ISSUE THREAD

**Issue by timh** [projectcontour/contour#2200]
To simplify our setup, and have more consistency with other OSS projects in the same team, it's desirable to move away from Travis. There have been good results with GitHub Actions, and it's GA now, so that is likely the best option. CircleCI also has more functionality here.

Moving to GitHub actions will bring the maintainers and community a more consolidated "single source of truth" for introspecting build results over time. The Contour maintainers are already using Actions for the release process, so this move would bring these different stages of our build process together.

**Comment by SDBrett** [comment]
Consistency with the other projects is a huge benefit, especially information sharing. 

Distribution of CI's currently used is pretty even currently.

| CI Platform / Project | Travis | CircleCI | Github |
|-----------------------|--------|----------|--------|
| Velero                | X      |          |        |
| Otant                 |        |          | X      |
| Sonobuoy              |        | X        |        |
| Contour               | X      |          |        |

I cannot think of any Travis features used that are not available in CircleCI. I don't know if this is the case for GitHub, but happy to have a look and compare.
