### ISSUE TITLE
Can not perform leader election

### ISSUE THREAD

**Issue by pratimsc** [projectcontour/contour#2207]
**What steps did you take and what happened:**
The contour v 1.1.0 was installed on the system using the provided YAML file. However, the namespace of target installation is not `projectcountour` but an internal namespace.

**What did you expect to happen:**
I would expect contour  to perform normally. The contour is processing IngressRoutes and HttpProxy propery. However, the logs show the following error every second.
`  message: "error retrieving resource lock projectcontour/leader-elect: configmaps "leader-elect" is forbidden: User "system:serviceaccount:my-internal-namespace:contour" cannot get resource "configmaps" in API group "" in the namespace "projectcontour""`

The source of the error is represented as `  source: "leaderelection.go:324" `

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The only change that has been conciously made is to split the file `https://projectcontour.io/quickstart/contour.yaml` into multiple file containing each resource, and change the namespace to `my-internal-namespace`

**Environment:**

- Contour version: `1.1.0`
- Kubernetes version: (use `kubectl version`): 1.15.8-gke.3
- Kubernetes installer & version: `1.15.8-gke.3`
- Cloud provider or hardware configuration: Google Cloud Platform
- OS (e.g. from `/etc/os-release`): Standard GCP build

**Comment by jpeach** [comment]
In the Contour ConfigMap, you also need to change the leader election namespace:

```
# The following config shows the defaults for the leader election.
leaderelection:
  configmap-name: leader-elect
  configmap-namespace: my-internal-namespace
```

Here's an example of deploying Contour into a non-default namespace (uses kustomize):
    https://github.com/jpeach/kustomize/tree/master/knative/configurations/contour/contour-external

**Comment by pratimsc** [comment]
Thanks @jpeach , the issue is resolved. Shame that I missed this in the documentation.
