### ISSUE TITLE
Automatically enable detected GVKs

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour#2219]
This issue is to discuss whether Contour should autodetect supported GVKs, both CRD and core, at startup and watch any supported objects that are installed in a cluster.

The current option is to have specific flags for types we want to enable or disable (#1461, #1241). We will keep doing this for now, but we can consider doing a more dynamic solution.

Pros of autodetecting:
- Less config flags
- Enables cluster admins to switch off CRD functionality by not installing CRDs
- Stops the surprise factor of having a CRD or other object installed that is not watched by Contour

Cons of autodetecting:
- Doesn't allow for clearly flagging things as experimental as easily - probably warning logs would be required.

**Comment by youngnick** [comment]
We would probably need to use https://godoc.org/k8s.io/client-go/discovery or similar, for future reference.

**Comment by jpeach** [comment]
xref: #1241

**Comment by youngnick** [comment]
After some consideration of this, I'm going ahead with it, as it will allow for people to make an ultimate "disable this configuration type" decision by removing a CRD from the cluster. This will  help with IngressRoute -> HTTPProxy migration, version changes, and so on.

**Comment by stevesloka** [comment]
@youngnick I have some work for this started, did you already start? I don't want to duplicate efforts.

**Comment by youngnick** [comment]
I started in that I did some refactoring in preparation - my idea was that we would build the default set of informers using the bits I added already, and then wash that set against what's actually present on the apiserver. Could also do it the other way around, of course.
