### ISSUE TITLE
IPv6 - dual stack support for contour

### ISSUE THREAD

**Issue by prateekjainaa** [projectcontour/contour#2220]
Hi,

 I just wanted to know if there is some timeline from contour to support IPv6/dual stack in kubernetes cluster.

Regards,
Prateek

**Comment by davecheney** [comment]
I believe we implemented dual stack support last year. Could you please try and log issues for things that don’t work. Thank you.

On 11 Feb 2020, at 21:17, Prateek <notifications@github.com> wrote:

﻿

Hi,

I just wanted to know if there is some timeline from contour to support IPv6/dual stack in kubernetes cluster.

Regards,
Prateek

**Comment by prateekjainaa** [comment]
Thanks a lot @davecheney . We will start to log specific issues as we encounter them.
