### ISSUE TITLE
Test minimal Envoy functionality before release

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour#2223]
This issue covers work to test the minimum Envoy functionality in #2048 with a release candidate before the final release is cut.

This step should be performed between creating the release branch and cutting the final release in the release runbook https://projectcontour.io/resources/release-process/.

**Comment by jpeach** [comment]
xref #2048

**Comment by jpeach** [comment]
Probably need to spin off a separate issue for generating the deployment YAML to run envoy with extensions disabled. That might depend on doing something with kustomize, since we want to be able to deploy Contour in a standard way but just slam in some new flags to the envoy container.

xref #2088

**Comment by stevesloka** [comment]
Completed manual testing for Contour release v1.2.0

**Comment by jpeach** [comment]
Test scenarios from @stevesloka 

https://docs.google.com/spreadsheets/d/1Y22qy_9Q6UO1rcM24NrFq8x6sHoEpWTuNEVQq7hb42Y

**Comment by stevesloka** [comment]
@jpeach what's the status on the test infra? Can we merge that and start incorporating even if it's not 100% complete. 

We also need to find a way to track changes as new features are added. For example, the ingress class work that was just added should be tracked somewhere to be added to the functional tests.

**Comment by jpeach** [comment]
> @jpeach what's the status on the test infra?

The test driver works and can run declarative tests. I've got a handful of tests written for Contour.

> Can we merge that and start incorporating even if it's not 100% complete.

Yes, we should start that. I need to publish the repo and add goreleaser so that there is an artifact that we can run. I have a separate repo with the test cases, which I think would end up being merged into Contour repository.

> We also need to find a way to track changes as new features are added. For example, the ingress class work that was just added should be tracked somewhere to be added to the functional tests.

We could add a label, or file an issue for each test as we think of it?

**Comment by youngnick** [comment]
I think that creating issues with a label is the way to go

**Comment by skriss** [comment]
What's the action item on this issue? Should we consider this closed now that we have some integration tests in place?

**Comment by youngnick** [comment]
Yes, I think that we should close this out now that we have integration tests in place. More specific items should generate new issues.
