### ISSUE TITLE
internal/dag: Refactor builder

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2226]
The first step to build the DAG is to convert resources into internal Contour types which are done in [`internal/dag/builder.go`](https://github.com/projectcontour/contour/blob/master/internal/dag/builder.go). 

The builder processes the following types:

- Ingress/v1beta1 
- IngressRoute/v1beta1
- TLSCertificateDelegation/v1beta1
- HTTPProxy/v1
- TLSCertificateDelegation/v1

The builder has grown to be a single file handling all these types and I think could win by being split apart to make it more clear, especially as this list of types grows and the Contour API's progress.

**Comment by jpeach** [comment]
I think that this is closely related to https://github.com/projectcontour/contour/issues/2683.

If we define a builder abstraction, we can have independent builders for all the APIs that we want to support (ingress, httproute, service apis). However that needs the support of a generic Kubernetes resource cache (i.e. #2683). All the builders end up creating objects in the DAG, then you can have a DAG visitor interface like the one in #2753 to generate envoy resources in whatever way you want. This approach would result in a set of loosely coupled components that collaborate via the DAG.

**Comment by skriss** [comment]
Now that #2847 has landed I'm starting to look at having the `Processors` (probably to be renamed builders eventually) operate directly on the DAG, rather than a Builder. Looking at what a good API for that looks like.
