### ISSUE TITLE
404 errors for couple of http fqdns

### ISSUE THREAD

**Issue by michmike** [projectcontour/contour#2230]
We are experiencing 404 errors for couple of http fqdns with contour v 1.1.0 after few hours of contour in service.
We have created ‘httpproxy’ config with one route configured with “permitInsecure”.
The route is exposed on https endpoint properly but the http endpoint is receiving 404 error.
In this situation if we restart contour, http endpoint start to serve traffic properly again.
Presently after the restart of contour is serving well.

**Environment:**
- Contour version: 1.1.0
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by stevesloka** [comment]
Can you share your `HTTPProxy` config? Also, any logs that are relevant in Envoy when this happens? 

The next thing I would look at is the Envoy admin page (localhost:9001 on the envoy pod) and dump the configuration.

**Comment by stevesloka** [comment]
Closing since no discussion since, please reopen if this issue is still a problem providing any items noted in the previous comment.
