### ISSUE TITLE
internal/metrics: contour_dagrebuild_timestamp should not be defined as a GaugeVec

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#2238]
The `contour_dagrebuild_timestamp` is defined as a Guage Vec, it should probably not be.

**Comment by stevesloka** [comment]
What type would you suggest to switch to? The gauge type seems to fit the use of this field, just knowing when the last time the rebuild occurred:

```
A gauge is a metric that represents a single numerical value that can arbitrarily go up and down
```
https://prometheus.io/docs/concepts/metric_types/#gauge

**Comment by youngnick** [comment]
Ideally, a timestamp should monotonically increase, so it would make more sense to be a Counter. 

Hopefully, the rare times when a timestamp might appear to roll back should be handled by whatever displays the Prometheus metrics assuming a rollover.

**Comment by jpeach** [comment]
A timestamp is not a counter because it is a discrete value that cannot be converted to a rate.

**Comment by davecheney** [comment]
For clarity, the current metrics is a GuageVec, a Guage with a label dimension. However we define the current metric as a GuageVec with an empty slice of labels

https://github.com/projectcontour/contour/blob/master/internal/metrics/metrics.go#L167

and update the metrics with a blank label

https://github.com/projectcontour/contour/blob/master/internal/metrics/metrics.go#L223

We should just stop doing this.
