### ISSUE TITLE
update https://projectcontour.io/resources/kubernetes/ for 1.2.0 release

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#2251]
Please update https://projectcontour.io/resources/kubernetes/ to include the versions of k8s supported by Contour 1.2.0

**Comment by stevesloka** [comment]
This up to date with the version of client-go (e.g. v0.17) we are using in Contour v1.2, so that page is up to date.

**Comment by davecheney** [comment]
@stevesloka the page needs to be updated to include Contour 1.2.0 and resolve the question of k8s 1.18 support from the last community meeting.

**Comment by stevesloka** [comment]
Oh ok I'm sorry I misunderstood. I can take this as well.

**Comment by davecheney** [comment]
Thank you!
