### ISSUE TITLE
Producing knative-compatible yamls in a sustainable way

### ISSUE THREAD

**Issue by mattmoor** [projectcontour/contour#2254]
**Please describe the problem you have**

knative.dev/net-contour requires a slightly odd configuration of Contour, where we effectively use two installs:
1. The first is our `ExternalIP` visibility, where the Envoys have a `type: LoadBalancer` service, and a Contour, which programs them with a specified class (e.g. `contour-external`)
2. The second is our `ClusterLocal` visibility, where the Envoys have a `type: ClusterIP` service, and a Contour, which programs them with a specified class (e.g. `contour-internal`)

The "class" and service name are configured for each visibility through our `config-contour` configmap [here](https://github.com/knative/net-contour/blob/ef9d8bdc016203645eab5dc0a4d7465ad239930e/config/config-contour.yaml#L36-L42).

To bootstrap things, I produced artisan hand-crafted yamls to achieve this, and I'll probably do this a few more times before we sort out how to do this sustainably, but I wanted to open this issue to seek guidance on how we might do this most sustainably moving forward.

**Comment by jpeach** [comment]
Exposing a parts of the Contour YAML as a kustomize base can help with this.

xref #2088

**Comment by stevesloka** [comment]
Hey @mattmoor, in a perfect world, what would you want here? Some Kustomize yaml? A helm chart?

**Comment by mattmoor** [comment]
I don't have a strong preference, but what I ultimately did was to produce two yamls with `s/projectcontour/contour-{internal,external/`, and then scripted fixing up everything else I found.

This was much simpler than the crazy stuff I was doing previously, but still harder than it should be to find everything (e.g. `--namespace` on the Job, class flag on contour)

**Comment by johanbrandhorst** [comment]
Sorry if this isn't the best place for this, but what is the reason that Contour can't support knative natively? Why the need for the separate project?

**Comment by mattmoor** [comment]
> what is the reason that Contour can't support knative natively 

This sort of ties into: https://github.com/projectcontour/contour/issues/2809

We use a separate installation of Contour for each "class"-equivalent in the Knative model.

If a single install of Contour could satisfy Knative's needs, then we could maybe discuss it, but I'm still not sure it makes sense given costs/benefits (e.g. vendoring knative?) and the longer term prospects (e.g. ingress v2).
