### ISSUE TITLE
Site: Quickstart still references master tags

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2268]
The quickstart which is in the v1.2 release still references `:master` for images. We should pin those manifests to the release they are included in and not use a rolling image tag.

**Comment by youngnick** [comment]
Looks like we missed adding the "Update the yamls from `:master` to the pinned version" to the release guide, and I missed it. I'll fix this issue and add that in the same PR.

**Comment by youngnick** [comment]
No, it's there, I just missed the step. Dang.
