### ISSUE TITLE
httpproxy: spec.virtualhost.tls.secretName is optional, or is it?

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#2273]
```
type TLS struct {
        // required, the name of a secret in the current namespace.
        SecretName string `json:"secretName,omitempty"`
```
The comment says spec.virtualhost.tls.secretName is required, but its marked as optional by dint of the `omitempty` json tag. 

Decide if secretName is required, and if is, adjust validations, if not adjust the comment.

**Comment by stevesloka** [comment]
I agree this is confusing. `SecretName` is required when `PassThrough` is `false`, otherwise, it shouldn't be defined and I believe the value is ignored.
