### ISSUE TITLE
internal/k8s.Status is not race safe

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#2278]
k8s.Status's methods do not protect against concurrent access or mutation of its internal state.

**Comment by youngnick** [comment]
Looking at the code:
- feels like maybe the current type should be renamed to CRDStatus or something, since it can only store projcontour.Status objects in its cache
- Looks to me like it needs either some `sync.Mutex` around the critical parts, or to be moved so it can't be concurrently accessed

**Comment by jpeach** [comment]
By `k8s.Status` do you mean `k8s.StatusCacher`? Or `dag.Status`?

**Comment by youngnick** [comment]
`k8s.StatusCacher`, good catch.
