### ISSUE TITLE
unable to downgrade TLS version

### ISSUE THREAD

**Issue by prateekjainaa** [projectcontour/contour#2290]
**What steps did you take and what happened:**
 We have an application which is exposed over https. It is working fine in web-browsers. 
 Now, we also have a generic load generating tool (written in python 2.7) which works fine for this application.

Now, we switched to contour and updated our Ingress objects accordingly. everything works fine here too in web-browser. But load generating tool cant connect to new application. While digging into it, we found that this tool is expecting TLSv1.2 cert. So, we added this annotation to our Ingress object:

`projectcontour.io/tls-minimum-protocol-version: TLSv1_2`

This is more evident from a simple curl log:

curl -v https://<app_url>

This one works fine with tool:

```
$ curl -v https://ieatenmc12a008.com/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.42.14.152:443...
* TCP_NODELAY set
* Connected to ieatenmc12a008.com (10.42.14.152) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: C:/Users/foo/AppData/Local/Programs/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [106 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [893 bytes data]
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
} [2 bytes data]
* SSL certificate problem: unable to get local issuer certificate
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0

```

And this one (from contour) doesn't

```
$ curl -v https://ieatenmc13a006.com/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.210.220.59:443...
* TCP_NODELAY set
* Connected to ieatenmc13a006.com (10.210.220.59) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: C:/Users/foo/AppData/Local/Programs/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [15 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [1098 bytes data]
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
} [2 bytes data]
* SSL certificate problem: self signed certificate
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0

```

**What did you expect to happen:**

After applying this annotation:

`projectcontour.io/tls-minimum-protocol-version`

we expected it to send TLSv1.2 certificate.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.1
- Kubernetes version: (use `kubectl version`): 1.16
- Kubernetes installer & version:
- Cloud provider or hardware configuration: k8s cluster
- OS (e.g. from `/etc/os-release`): SLES 15-sp1

**Comment by davecheney** [comment]
You shouldn’t need that annotation, contours default tls level is 1.1.

If the administrator has raised it to 1.3, you will not be able to lower it to 1.2.

On 25 Feb 2020, at 23:02, Prateek <notifications@github.com> wrote:

﻿

What steps did you take and what happened:
We have an application which is exposed over https. It is working fine in web-browsers.
Now, we also have a generic load generating tool (written in python 2.7) which works fine for this application.

Now, we switched to contour and updated our Ingress objects accordingly. everything works fine here too in web-browser. But load generating tool cant connect to new application. While digging into it, we found that this tool is expecting TLSv1.2 cert. So, we added this annotation to our Ingress object:

projectcontour.io/tls-minimum-protocol-version: TLSv1_2

This is more evident from a simple curl log:

curl -v https://<app_url>

This one works fine with tool:

$ curl -v https://ieatenmc12a008.com/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.42.14.152:443...
* TCP_NODELAY set
* Connected to ieatenmc12a008.com (10.42.14.152) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: C:/Users/foo/AppData/Local/Programs/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [106 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [893 bytes data]
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
} [2 bytes data]
* SSL certificate problem: unable to get local issuer certificate
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0



And this one (from contour) doesn't

$ curl -v https://ieatenmc13a006.com/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.210.220.59:443...
* TCP_NODELAY set
* Connected to ieatenmc13a006.com (10.210.220.59) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: C:/Users/foo/AppData/Local/Programs/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [15 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [1098 bytes data]
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
} [2 bytes data]
* SSL certificate problem: self signed certificate
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0



What did you expect to happen:

After applying this annotation:

projectcontour.io/tls-minimum-protocol-version

we expected it to send TLSv1.2 certificate.

Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

Environment:

  *   Contour version: 1.1
  *   Kubernetes version: (use kubectl version): 1.16
  *   Kubernetes installer & version:
  *   Cloud provider or hardware configuration: k8s cluster
  *   OS (e.g. from /etc/os-release): SLES 15-sp1

**Comment by prateekjainaa** [comment]
Hi @davecheney Thanks for the update. Can you explain more on this? There is no administrator coming into play. Earlier it was using k8s ingress controller and things are/were fine. Its the same clsuter, we just swapped nginx with contour. 

FYI, we used openssl to generate certificate. Can that cause issue? 

openssl version: 1.10i-fips
command used: 

`openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout ca-key.key -out ca-cert.crt`

`kubectl create secret tls my-cert --key ca-key.key --cert ca-cert.crt -n foo`

any pointers in this would be helpful.

**Comment by prateekjainaa** [comment]
Tried curl from director node inside cluster and it is able to handle TLSv1.2. Seems like some internal issue with this cluster. Closing this issue.
