### ISSUE TITLE
TLS redirects (HTTP 302) errors with clients who dont follow redirect

### ISSUE THREAD

**Issue by prateekjainaa** [projectcontour/contour#2294]
**What steps did you take and what happened:**
We have an application which is running fine and we swapped nginx ingress with contour. Did corresponding updates in svc and ing objects. Everything appears to work fine from web browser. But issue comes up when we are using tools which dont follow re-directs. for example:

when get 302 error from curl:

```
$ curl -k -X GET https://ieatenmc13a006.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   306  100   306    0     0   4857      0 --:--:-- --:--:-- --:--:--  5016<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://ieatenmc13a006.com:443/login/?goto=https%3A%2F%2Fieatenmc13a006.com%3A443%2F">here</a>.</p>
</body></html>
```
But if we allow re-direct follow:

```
$ curl -k -X GET -L https://ieatenmc13a006.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   306  100   306    0     0   4707      0 --:--:-- --:--:-- --:--:--  4857
100  2852  100  2852    0     0  39068      0 --:--:-- --:--:-- --:--:-- 39068<!DOCTYPE html>
<html>
<head>
    <title>AppLogin</title>
.
.
```
page is displayed successfully.
 

By some searching on internet we found this:

> When TLS is enabled for a virtual host, Contour will redirect the traffic to the secure interface. To verify this, run (with your domain):

at 
https://aws.amazon.com/blogs/containers/securing-eks-ingress-contour-lets-encrypt-gitops/

Now, issue is - we dont understand why is this redirection happening? Ingress is already configured to use tls-termination. This is a big blocker for the testing tools which have got redirects disabled. Is there an option to disable this feature?

**Anything else you would like to add:**

**Environment:**

- Contour version: 1.1
- Kubernetes version: (use `kubectl version`): 1.15
- Kubernetes installer & version:
- Cloud provider or hardware configuration: internal k8s cluster
- OS (e.g. from `/etc/os-release`): SLES 15-SP1

**Comment by jpeach** [comment]
It looks to me like the application is sending a redirect to its login page. Contour doesn't configure this kind of redirect.

**Comment by davecheney** [comment]
I don't believe this redirect is coming from envoy -- envoy does not return 3xx response bodies.

As @jpeach noted above, the 302 is likely coming from the backend pod. I'm going to mark this question as answered, please feel free to reopen it if you disagree or require further assistance. You can also find us on the k8s slack, https://projectcontour.io/community/

**Comment by prateekjainaa** [comment]
Just updating this issue just to help people who encounter anything similar in future. 

In our case, client calling our application was using HTTP 1.0 and contour also responded with HTTP 1.0. Issue is, earlier we used nginx-ingress and that used to respond with HTTP 1.1 even if request was using HTTP 1.0. 

Now, in this very specific case of Header 302, there were improvements in HTTP protocol itself. As per Wikipedia:

> The HTTP response status code 302 Found is a common way of performing URL redirection. The HTTP/1.0 specification (RFC 1945) initially defined this code, and gave it the description phrase "Moved Temporarily" rather than "Found".

For details: [https://en.wikipedia.org/wiki/HTTP_302](https://en.wikipedia.org/wiki/HTTP_302 )

**Comment by davecheney** [comment]
Thanks for your update. I am sceptical of this diagnosis. If your client used HTTP/1.0 it may have issued a request without a Host: header, in which case Envoy will have returned a 404. If your _backend_ application responded with a HTTP/1.1 response, it could be that nginx proxied the message with a HTTP/1.1 response where Envoy is recoding the message to the HTTP/1.0 standard. 

In either case the diagnosis by @jpeach that it is the application running in the pod, not the ingress controller, which issued the 302 redirect, remains correct in my mind.

Please feel free to reopen this issue if you disagree with this diagnosis.
