### ISSUE TITLE
Minimum HTTP version

### ISSUE THREAD

**Issue by prateekjainaa** [projectcontour/contour#2299]
**What steps did you take and what happened:**
We have a legacy application which can handle both HTTP 1.0 and 1.1 but sends requests using HTTP 1.0. Till now we were using k8s ingress controller and it sends response in HTTP 1.1, even if requests are in HTTP 1.0. Now, when we have transitioned to use contour; it has stopped working.
We found a similar issue logged earlier on contour 
[https://github.com/projectcontour/contour/issues/537](https://github.com/projectcontour/contour/issues/537)

but seems like contour has enabled HTTP 1.0 by default.

**What did you expect to happen:**

Is it possible to make this minimum version of HTTP protocol configurable (just like minimum TLS version)? 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.1
- Kubernetes version: (use `kubectl version`): 1.15
- Kubernetes installer & version:
- Cloud provider or hardware configuration: private k8s cluster
- OS (e.g. from `/etc/os-release`): SLES 15 sp1

**Comment by jpeach** [comment]
> but seems like contour has enabled HTTP 1.0 by default.

Did you mean "has *disabled* HTTP 1.0 by default"?

**Comment by davecheney** [comment]
@prateekjainaa would it be possible for you to support the output of a curl (or similar command) showing the complete request and response.

**Comment by prateekjainaa** [comment]
@davecheney  Here it is:

```
curl -k --http1.0 -v https://ieatenmc13a006.com/login/

* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 302 Found
< date: Fri, 28 Feb 2020 16:30:38 GMT
< server: envoy
< content-security-policy: frame-ancestors 'self' https://*/elex*;
< x-frame-options: allow-from https://*/elex*
< location: https://ieatenmc13a006.com/login/?goto=https://ieatenmc13a006.com
< content-length: 287
< content-type: text/html; charset=iso-8859-1
< x-envoy-upstream-service-time: 25
< connection: close
<
{ [287 bytes data]
100   287  100   287    0     0   3337      0 --:--:-- --:--:-- --:--:--  3416<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
.
.
.
```

**Comment by davecheney** [comment]
Thank you for your reply. From the information you have provided I don’t think http/1.0 vs 1.1 is the issue. Can you please explain why it is important that the ingress controller responds with a http/1.1 response when sent a http/1.0 request?

**Comment by prateekjainaa** [comment]
Because we conducted similar experiment where request was sent in http 1.1
and contour responded with http 1.1 and everything worked fine.

**Comment by davecheney** [comment]
Thank you for your reply. I'm still having trouble isolating the issue here. You said you wanted HTTP/1.0 requests to respond with a HTTP/1.1 response. Why is that important, what is it about an unconditional HTTP/1.1 response that is key to solving your problem?

**Comment by davecheney** [comment]
Said another way, what isn't working fine?

**Comment by prateekjainaa** [comment]
because of header 302 difference implementation b/w HTTP versions. From wikipedia,

https://en.wikipedia.org/wiki/HTTP_302

`The HTTP response status code 302 Found is a common way of performing URL redirection. The HTTP/1.0 specification (RFC 1945) initially defined this code, and gave it the description phrase "Moved Temporarily" rather than "Found".`

In failure cases, we can see exactly same code getting logged.

> Moved Temporarily

so, this is our first point to get rid of this error by responding in HTTP 1.1.

**Comment by davecheney** [comment]
Thank you for explaining. To recapitulate your request, you have a system which is looking for the specific word “Moved Temporarily” on a 302 response, and does not work when contour, or your backend pod, responds to a HTTP/1.0 request with a HTTP/1.0 response with a 302 and the HTTP/1.0 response message of “Found”

**Comment by prateekjainaa** [comment]
In this case, we got trapped by response headers being case insensitive from envoy. I am closing this ticket. Our testware has a comparison, which is case sensitive but envoy converted all headers to lower case and this broke condition. I will open a separate ticket on how to preserve the case of headers via contour.
