### ISSUE TITLE
internal/metrics: Contour should track Ingress metrics

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour#2304]
Contour currently makes metrics available for each of HTTPProxy and IngressRoute (although it's deprecated). It should do the same for Ingress.

The current counters are for the CRDs are:
- Total
- Orphaned
- Valid
- Invalid
- Root

I suggest for Ingress:
- Total
- Valid
- Invalid

Although I'm unsure if we collect the validity information for Ingress currently.

**Comment by stevesloka** [comment]
Status for Ingress is blocked currently on: https://github.com/projectcontour/contour/issues/403

Does Contour need to expose this info or it is already available from the k8s api? The understanding of valid vs invalid might be the reason to have it in Contour. Also, I guess you'd be able to understand what Contour is processing (i.e. ingress class, etc).

**Comment by jpeach** [comment]
For ingress, contour can track validity internally and emit metrics based on that.
