### ISSUE TITLE
request response headers case

### ISSUE THREAD

**Issue by prateekjainaa** [projectcontour/contour#2313]
**What steps did you take and what happened:**
We found that response header names coming from envoy gets converted to lower case. From [https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive](https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive) we can see that header names should be case insensitive but there are applications which are setting custom header or making comparisons on header names but looking for exact names like "X-AuthErrorCode" instead of equalsIgnoreCase("x-autherrorcode").

**What did you expect to happen:**
Is there a way via which envoy doesn't perform this case conversion and keep header names as it receives? 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

We saw something similar on envoy

[https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/header_casing](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/header_casing)

and discussion on contour

[https://github.com/projectcontour/contour/issues/1701](https://github.com/projectcontour/contour/issues/1701)

**Environment:**

- Contour version: 1.1
- Kubernetes version: (use `kubectl version`): 1.15
- Kubernetes installer & version:
- Cloud provider or hardware configuration: internal k8s cluster
- OS (e.g. from `/etc/os-release`): SLES 15 sp1

**Comment by davecheney** [comment]
Thank you for raising this issue. It is my goal to give clear feedback when we cannot accept an issue. In this case I am going to close this issue as RC2616 and others defines headers as case insensitive. Envoy takes advantage of this part of the specification and we cannot change that

 In light of this I am going to close this issue and encourage your development team or vendor to use case insensitive comparisons when comparing header keys.

/cc @michmike
