### ISSUE TITLE
Update j.hept.io shortlinks - j.hept.io/contour-deployment-rbac

### ISSUE THREAD

**Issue by seanalexander** [projectcontour/contour#2330]
**What steps did you take and what happened:**
Visited: https://j.hept.io/contour-deployment-rbac
Got redirected to: 
https://raw.githubusercontent.com/heptio/contour/master/examples/render/deployment-rbac.yaml

**What did you expect to happen:**
Redirected to an active link.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Kubernetes Up & Running references this link, and it seems to be dead:

the last instance I can find of this file is:
https://raw.githubusercontent.com/projectcontour/contour/release-0.15/examples/render/deployment-rbac.yaml

which I assume has been updated to:
https://raw.githubusercontent.com/projectcontour/contour/release-1.2/examples/render/contour.yaml

**Environment:**
n/a

**Comment by jpeach** [comment]
Where did you follow the `https://j.hept.io/` link from?

**Comment by seanalexander** [comment]
![20200311_020405](https://user-images.githubusercontent.com/1403107/76387221-c1de9980-633c-11ea-8fb1-3170ff3f0b45.jpg)

![20200311_020444](https://user-images.githubusercontent.com/1403107/76387230-c905a780-633c-11ea-8ffb-8010f6421ea8.jpg)

**Comment by seanalexander** [comment]
I was using this issue as a reference:
https://github.com/projectcontour/contour/issues/1144

**Comment by jbeda** [comment]
Hard to update a hard copy! Bummer that that slipped through in the second edition.

Updated now.
