### ISSUE TITLE
Documents are a bit confusing

### ISSUE THREAD

**Issue by cten** [projectcontour/contour#2345]
**What did you expect to happen:**
That the documents referenced Envoy instead of Contour in this section: https://projectcontour.io/docs/v1.2.1/deploy-options/#host-networking
I would expect to set 'hostNetwork' and 'dnsPolicy' on the Envoy DS instead of the Contour Deployment.

**Environment:**

- Contour version: v1.2.1
- Kubernetes version: (use `kubectl version`): 1.16
- Kubernetes installer & version: kops 1.16
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): debian

**Comment by stevesloka** [comment]
Ahh good catch @cten. I think this is left over from when contour used to be colocated into the same pod.
