### ISSUE TITLE
Write release tooling

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2351]
**Please describe the problem you have**

Releasing involves a lot of manual steps.

https://projectcontour.io/resources/release-process/

We should have a tool or script that takes care of the majority of these tasks.

**Comment by youngnick** [comment]
I used goreleaser for ir2proxy, and it was great.

**Comment by jpeach** [comment]
I'm re-opening this since there is more tooling that we need to make releases

- [ ] Make the release branch (which is not named the same as the release)
- [ ] Update `site/_redirects`
- [ ] Generate release notes outline from the Github issues
- [ ] Create a Github release and add release notes to it
- [ ] Build and push the versioned image to Dockerhub

**Comment by jpeach** [comment]
Should look into K8s release notes generator

https://github.com/kubernetes/release/blob/master/cmd/release-notes/README.md

**Comment by skriss** [comment]
Closing this out as much of this is done and we have #3552 as a more recent placeholder.
