### ISSUE TITLE
Slow Envoy startup due DNS

### ISSUE THREAD

**Issue by Zsolt-LazarZsolt** [projectcontour/contour#2354]
**What steps did you take and what happened:**
Envoy is slow to get ready in my IPv6 cluster.
I install envoy 1.12.2 as part of a contour 1.1.0 quck start rendered manifest. Some of the pods can take up to 140s to get ready.
I suspect some kind of race condition during startup. If I add a new initcontainer to the DaemonSet, Sleeping 5 seconds, the issue is not reproducible for me.
I do also have another cluster with only IPv4 addresses, and installing with the manifest I also do not see the issue.
The only things I changed compared to the original contour example is:
- Remove the internal security, to see it happening in the most basic setup
- changes in the args for envoy to be ready for v6 use

```
kubectl apply -f contour.yaml

kubectl get pods -n projectcontour
NAME READY STATUS RESTARTS AGE
contour-58f47b9d8c-4k664 1/1 Running 0 2m20s
contour-58f47b9d8c-rpkcv 1/1 Running 0 2m20s
envoy-k59m9 0/1 Running 0 2m20s
envoy-n4kw4 1/1 Running 0 2m20s
envoy-vnnq2 1/1 Running 0 2m20s
envoy-xrnr9 0/1 Running 0 2m20s
```

**What did you expect to happen:**
Most of the time envoy gets ready in 10-15 seconds

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.1.0
- Kubernetes version: (use `kubectl version`): v1.15.3
- Kubernetes installer & version:
- Cloud provider or hardware configuration: 
- OS (e.g. from `/etc/os-release`): centos 7

[contour_manifest.txt](https://github.com/projectcontour/contour/files/4349188/contour_manifest.txt)
Envoy debug log from envoy-k59m9
[envoy.pod.log](https://github.com/projectcontour/contour/files/4349210/envoy.pod.log)

**Comment by youngnick** [comment]
Hi @Zsolt-LazarZsolt, is there any chance you could try with the current release? (1.2 as of writing, although 1.3 will be released on Friday the 20th of March.) There have been a bunch of changes to Contour and Envoy's behaviour, although it doesn't sound specifically related to your problem.

We haven't done a lot of testing of IPV6. What makes you think it's DNS? (Aside from it always being DNS...)

**Comment by Zsolt-LazarZsolt** [comment]
Hi @youngnick 
Thanks for the quick answer. 
Yes, unfortunately is was able to reproduce the issue, easily, with a slightly modified version of the rendered quick start guide manifest of Contour 1.2.1.

1. I removed the internal security and certificate stuff
2. Tweaked some parameters and ports to be v6 ready
3. Switched on envoy debug logging

[contour_new.txt](https://github.com/projectcontour/contour/files/4360843/contour_new.txt)


kubectl get pods -n projectcontour
NAME                      READY   STATUS    RESTARTS   AGE
contour-bd85db49c-ddmrr   1/1     Running   0          2m32s
contour-bd85db49c-gzpvn   1/1     Running   0          2m32s
envoy-4kfzl                           1/2     Running   0          2m32s
envoy-7rzt9                           1/2     Running   0          2m32s
envoy-f72tb                           1/2     Running   0          2m32s
envoy-sbvzw                         2/2     Running   0          2m32s
Notice 3 of the envoy pods are not ready at 2 minutes 32 secs

not much later: 
kubectl get pods -n projectcontour
NAME                      READY   STATUS    RESTARTS   AGE
contour-bd85db49c-ddmrr   1/1     Running   0          2m53s
contour-bd85db49c-gzpvn   1/1     Running   0          2m53s
envoy-4kfzl                           2/2     Running   0          2m53s
envoy-7rzt9                          2/2     Running   0          2m53s
envoy-f72tb                          2/2     Running   0          2m53s
envoy-sbvzw                        2/2     Running   0          2m53s

Of course I collected the log from one of the envoy pod, all the "slow" pods have the same happening.


[envoynew.log](https://github.com/projectcontour/contour/files/4360841/envoynew.log)


To answer your question, the only thing making me think of DNS is the recurring DNS request seen in the envoy log. So in the end my title can be misleading.

Best Regards
Zsolt

**Comment by stevesloka** [comment]
Hey @Zsolt-LazarZsolt, to rule out your cluster DNS, could you try chaning the xds server to use the contour service IP instread of the name? 

This change would be in the Envoy Daemonset in the init container:
```
- --xds-address=contour. # <--- change to service IP of contour
```

Did you change anything else in that bootstrap config? Could you share it?

**Comment by Zsolt-LazarZsolt** [comment]
Hey @stevesloka 

I only removed the certificate files from the bootstrap configuration. 
I can provide the /config/envoy.json that it creates:

[envoy.config.txt](https://github.com/projectcontour/contour/files/4369411/envoy.config.txt)

I tried to give the Cluster IP of contour service as xds-address. Is there a special syntax I should be using? Envoy failed to start up with it:

```
[2020-03-23 12:32:58.813][1][debug][init] [source/common/init/watcher_impl.cc:27] init manager Server destroyed
malformed url: tcp://2001:db8:10a:c751::ffff:42ba:8001
```

**Comment by jpeach** [comment]
An IPv6 literal URL like this should be `tcp://[2001:db8:10a:c751::ffff:42ba]:8001`.

https://tools.ietf.org/html/rfc3986#section-3.2.2

**Comment by Zsolt-LazarZsolt** [comment]
Hi, I might be misunderstanding the way, I tried like this:

      bootstrap
      /config/envoy.json
      --xds-address=[2001:db8:10a:c751::ffff:7805]
      --xds-port=8001

Envoy still dies on me:

**Comment by Zsolt-LazarZsolt** [comment]
Ops sorry, missclick.

**Comment by jpeach** [comment]
> On Mar 24, 2020, at 6:51 PM, Zsolt-LazarZsolt <notifications@github.com> wrote:
> 
> Envoy still dies on me

Looks like an envoy bug to me, see the issue I filed upstream. If you can get the cluster DNS to serve an IPv4 address, I think it will make Envoy happier.

**Comment by uablrek** [comment]
> If you can get the cluster DNS to serve an IPv4 address, I think it will make Envoy happier.

Not possible. In an ipv6-only cluster the PODs only have ipv6 addresses.

**Comment by jpeach** [comment]
> Hi, I might be misunderstanding the way, I tried like this:
> 
> ```
>   bootstrap
>   /config/envoy.json
>   --xds-address=[2001:db8:10a:c751::ffff:7805]
>   --xds-port=8001
> ```
> 
> Envoy still dies on me:
> [2020-03-24 07:46:53.427][1][debug][init] [source/common/init/watcher_impl.cc:27] init manager Server destroyed
> malformed url: tcp://[2001:db8:10a:c751::ffff:7805]:8001

I looked into the Envoy code a bit more; pretty sure that Envoy is expecting this to always be a hostname. As per envoy docs, "for LOGICAL or STRICT DNS it is expected to be hostname, and we bootstrap the management cluster as STRICT_DNS.

https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/endpoint/endpoint_components.proto#L36

This explains why envoy isn't prepared to parse the IPv6 address, but puts us back to square 1 with the issue :-/

**Comment by youngnick** [comment]
So, it seems like the real issue here is that, when the Envoy containers start, they very quickly try to connect to the 'contour' name, which does not resolve for a long time. I would think that this is probably something weird going on with the intersection of Envoy's IPv6 support, and its DNS-lookups.

Unfortunately, I don't have easy access to an IPv6 only cluster to test with.

What are the DNS settings for your Pods? What's in the `/etc/resolv.conf` in the pod?

Maybe there are some IPv4 bits in there somewhere, and that's why the resolution for 127.0.0.1 is failing, it should be looking up `::1` instead...

**Comment by Zsolt-LazarZsolt** [comment]
To answer you question:
**cat /etc/resolv.conf** 
nameserver 2001:db8:10a:c751::ffff:a
search contour.svc.cluster.local svc.cluster.local cluster.local
options ndots:5

I also tried to run a custom script instead of the initconfig to see how the dns looks at the very early times:
#! /bin/bash
 while true; do getent hosts eric-tm-ingress-controller-cr-contour; sleep 0.5; done

I was hoping it takes time to actually give back useful information for the DNS. Unfortunately even the very first query gave a valid address back.
Which is strange because if I added a custom secondary initcontainer, with only a 3 or 5 sec sleep, I did not see the error at all. Also when I did not run the initconfig just saved the config as a configmap, the issue was more apparent, happening more times.

**Comment by jpeach** [comment]
@Zsolt-LazarZsolt I was going to ask you for a envoy debug log, then I looked and saw you had already attached one, thanks!

Edited logs:
```
[2020-02-25 08:42:56.868][1][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:909] adding TLS initial cluster contour

[2020-02-25 08:44:11.870][1][debug][upstream] [source/common/network/dns_impl.cc:120] DNS request timed out 4 times

[2020-02-25 08:45:26.873][1][debug][upstream] [source/common/network/dns_impl.cc:120] DNS request timed out 4 times

[2020-02-25 08:45:26.873][1][debug][upstream] [source/common/upstream/upstream_impl.cc:912] initializing secondary cluster contour completed
[2020-02-25 08:45:26.873][1][debug][init] [source/common/init/manager_impl.cc:45] init manager Cluster contour contains no targets
[2020-02-25 08:45:26.873][1][debug][init] [source/common/init/watcher_impl.cc:14] init manager Cluster contour initialized, notifying ClusterImplBase

[2020-02-25 08:45:26.875][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 14, no healthy upstream

[2020-02-25 08:45:26.875][1][debug][upstream] [source/common/upstream/strict_dns_cluster.cc:148] DNS refresh rate reset for contour, (failure) refresh rate 5000 ms

[2020-02-25 08:45:31.874][1][debug][upstream] [source/common/upstream/strict_dns_cluster.cc:125] DNS hosts have changed for contour
[2020-02-25 08:45:31.874][1][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:1069] membership update for TLS cluster contour added 1 removed 0

[2020-02-25 08:45:41.874][1][debug][connection] [source/common/network/connection_impl.cc:711] [C0] connecting to [2001:db8:10a:c751::ffff:6f61]:8001


```

So it took envoy about 3mins to get a DNS response and to make a connection to Contour. I know that it is now especially helpful advice, but the problem is most likely as the network or DNS layers of your cluster.

**Comment by Zsolt-LazarZsolt** [comment]
@jpeach Hi, 
I was thinking the same, but when I introduced a delay of 5 sec, which is definitely less ten the 3 minutes, everything worked. Also as a check I introduced a liveness probe to the container, It looks like this 
        livenessProbe:
          httpGet:
            path: /ready
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 3

This liveness probe triggers a restart on the envoy container rougly around 45 sec in, most importantly the second envoy container gets ready in 2 seconds.
I do still suspect the DNS too, is there any kind of check, or debugging process against to find out what envoy wants from the DNS and what can go wrong in there?

**Comment by stevesloka** [comment]
Hey @Zsolt-LazarZsolt are you still seeing these latency delays when starting up in your cluster? I know it has been some time since your last comment.

**Comment by Zsolt-LazarZsolt** [comment]
Hi @stevesloka 

Sorry for the late answer. 
Yes it is still visible for us, Since we updated the versions using contour 1.11 and envoy 1.16.2.

I will try to get some tcpdumps with the help of a sidecar, if that helps.

BR
Zsolt

**Comment by Zsolt-LazarZsolt** [comment]
Hi 
Back in the day I created a similar ticket for envoy too:
https://github.com/envoyproxy/envoy/issues/10159, I paste my last comment here too.

I poked around the issue, as a novice.
I recorded some tcpdumps that I unfortunately can not share.
To my eye it seemed like the following happening:

1.     Envoy starts up as a part of a contour cluster
2.     when the pod starts in a v6 only cluster, the interface not immediately receives a global address, for a little while the only address on the interface is 1::
3.     as soon as envoy starts it starts dns queries for the contour service. at first using the 1:: as source address?
4.     In the meantime the interface has a working v6 IP address, and other traffic starts working
5.     Envoy for some reason still uses the 1:: as source address for the DNS queries, resulting no answer.
6.     Envoy hangs in this state until some external force (killed by liveness probe)

I'm not sure about the inner working of envoy, can it be that envoy chooses a source address for it's dns queries and not updating that with interface changes?

**Comment by youngnick** [comment]
Hi @Zsolt-LazarZsolt, sorry about the delay on replying here. It seems weird that Envoy can't tell that it's got a non-localhost address, but I think the other person in your Envoy issue is probably correct. It seems like this is something that Envoy will have to fix, as we just send the DNS name there.

**Comment by Zsolt-LazarZsolt** [comment]
Me too sorry for the late reply. It does seem like nothing can be done from contours perspective.
I will close the ticket.

Thank you for the help.
