### ISSUE TITLE
Expose Contour version in metrics

### ISSUE THREAD

**Issue by moderation** [projectcontour/contour#2378]
We have a number of internal dashboards that show information about our clusters. Cluster information includes CPU, memory and pod statistics as well as Kubernetes version. We would like to include the Contour version on this dashboard.

Today there is no easy way to scrape the Contour version without logging into the cluster as admin and query based on image version (dashboard and developers don't have cluster admin rights).

Request - expose the Contour version as part of the Prometheus metrics - https://projectcontour.io/guides/prometheus/#contour-metrics

**Comment by youngnick** [comment]
I agree, we should do this. We'll get this worked on asap. 

For the implementer, I'd suggest doing something like https://www.robustperception.io/exposing-the-software-version-to-prometheus

Adding help-wanted and good-first-issue to this one.

**Comment by pickledrick** [comment]
Happy to take this issue. I will update with a WIP PR later on today.

**Comment by jpeach** [comment]
@pickledrick When you look at this, please check how the metrics documentation is generated to ensure that documentation for the new metric will automatically be published. I'm happy to shepherd your PR.
