### ISSUE TITLE
Set status on HTTPProxy when ingress class is ignored

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2391]
Followup to https://github.com/projectcontour/contour/issues/2199, we should set the status of any `HTTPProxy` which is ignored when the ingress.class does not match. Currently, this is logged to Contour's `STDOUT`, but would be much easier for users to consume if the status was set properly.

**Comment by jpeach** [comment]
Do you mean that Contour using ingress class "A" should set a status on a proxy that specifies ingress class "B"?

**Comment by stevesloka** [comment]
Yeah thinking through, if the class doesn't match the ingress object, it should be ignored completely by that instance of Contour since it has no rights to manage it.
