### ISSUE TITLE
do not use latest as image tag for job contour-certgen

### ISSUE THREAD

**Issue by alanpeng** [projectcontour/contour#2395]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
In file https://github.com/projectcontour/contour/blob/master/examples/render/contour.yaml (Line 1365)
image tag for the job contour-certgen is set as:
image: docker.io/projectcontour/contour:latest

**What did you expect to happen:**
use the release version tag for this image. e.g. :
image: docker.io/projectcontour/contour:v1.3.0

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version:
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by youngnick** [comment]
Thanks for this issue @alanpeng - this has actually been done for a specific reason - namely that job specs are immutable once they are created.

If we set the version via the tag, then rerunning `kubectl apply` with a different version as part of an upgrade will fail. #2150 and #2030 are two examples of this happening before.

I think we need to put a comment in this file explaining this though.

**Comment by alanpeng** [comment]
Ok, I get it now, thanks！
