### ISSUE TITLE
New Weak Ciphers Flagged in Qualys SSL Labs Scan

### ISSUE THREAD

**Issue by ryanelian** [projectcontour/contour#2401]
**What steps did you take and what happened:**

This appears to be a repeat issue of a past issue:
- Issue: https://github.com/projectcontour/contour/issues/823
- PR: https://github.com/projectcontour/contour/pull/1011

In that PR thread, it is written:

![image](https://user-images.githubusercontent.com/8892187/77885577-76f7d800-7291-11ea-9069-e6961609e83b.png)

However when I scanned my site using https://www.ssllabs.com/ssltest/index.html new weak ciphers appear:

![image](https://user-images.githubusercontent.com/8892187/77884963-51b69a00-7290-11ea-8d72-77ca4a035305.png)

This is the YAML I used to produce the result: (A+ score when using cert-manager + letsencrypt)

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: my-proxy
spec:
  virtualhost:
    fqdn: website.com
    tls:
      secretName: my-tls
      minimumProtocolVersion: '1.2'
  routes:
    - conditions:
      - prefix: /
      services:
        - name: my-service
          port: 80
      enableWebsockets: true
```

**What did you expect to happen:**

No weak ciphers displayed in the scan result  page.

**Anything else you would like to add:**

While the grade is capped at A+, Contour might require updated configuration to improve Cipher Strength score:

![image](https://user-images.githubusercontent.com/8892187/77885497-4f087480-7291-11ea-8a70-723f29712742.png)

**Some more information about the weak ciphers:**
- https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA/
- https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA/

>  **Cipher Block Chaining:**

> The CBC mode is vulnerable to plain-text attacks with TLS 1.0, SSL 3.0 and lower. However a real fix is implemented with TLS 1.2 in which the GCM mode was introduced and which is not vulnerable to the BEAST attack. GCM should be preferred over CBC (cf. BEAST).

>  **Secure Hash Algorithm 1 MAC:**

> The Secure Hash Algorithm 1 has been proven to be vulnerable to collision attacks as of 2017 (cf. shattered.io). While this does not affect its usage as a MAC, safer alternatives such as SHA-256, or SHA-3 should be considered.

**Internet Explorer 11 is compatible with TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 and TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 cipher suites which are flagged as secure:**

https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%2010&key=107

**Environment:**

- Contour version: v1.3.0
- Kubernetes version: (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version: kubeadm 

```
kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:01:11Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: UpCloud 2 Core 4 GB RAM

- OS (e.g. from `/etc/os-release`):

```env
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

/cc @yob

**Comment by yob** [comment]
I'm not using contour in my current gig, so don't have particularly strong opinions here.

It looks like qualys might've started [marking all CBC ciphers as weak in May 2019](https://blog.qualys.com/technology/2019/04/22/zombie-poodle-and-goldendoodle-vulnerabilities).

> SSL Labs identifies cipher suites using CBC with orange color and with text WEAK. This change won’t have any effect on the grades, as it only means that SSL Labs discourages the use of CBC-based cipher suites further

There's also some specific attacks on CBC ciphers that they're now checking for.

I'm no expert but it sounds like it's not critical to disable all CBC ciphers yet. I can see a number of clients in the qualys test are choosing one of the `weak` ciphers, including some Windows 7/8 and iOS 6-8. It'd be interesting to know if those clients can still connect when the CBC ciphers are disabled.

**Comment by ryanelian** [comment]
> I can see a number of clients in the qualys test are choosing one of the weak ciphers, including some Windows 7/8 and iOS 6-8. It'd be interesting to know if those clients can still connect when the CBC ciphers are disabled.

https://www.ssllabs.com/ssltest/clients.html

According to their automated client user agent test, yes. (Using the more secure GCM cipher suites)

https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=6.0&key=129

![image](https://user-images.githubusercontent.com/8892187/78022419-1777f600-737f-11ea-8986-746fbef27112.png)

https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%207&key=36

![image](https://user-images.githubusercontent.com/8892187/78022447-2199f480-737f-11ea-953a-95b64507e623.png)

**Comment by tsaarni** [comment]
@ryanelian, @bascht, While ECDHE-RSA-AES128-SHA and ECDHE-RSA-AES256-SHA were disabled in 1.11, ECDHE-ECDSA-AES128-SHA and ECDHE-ECDSA-AES256-SHA were kept.  I wonder why the latter ciphers were keps, while both sets of ciphers would fall into the same category?

Was it possibly because the original SSL Labs report shows only RSA ciphers?  Maybe it was tested with RSA based keys/certificates only, and not with EC keys?

**Comment by bascht** [comment]
@tsaarni Thanks for the heads-up. To be honest, I only verified the changes via [`testssl.sh`](https://testssl.sh/) and which didn't list ECDHE-ECDSA-*

![Screenshot-2021-01-15-131756](https://user-images.githubusercontent.com/51264/104726696-5cb1bc80-5734-11eb-9d92-af69633c0ed1.png)

Nevertheless - it makes sense to disable all of them via #3237 :)
