### ISSUE TITLE
Document the CONTOUR_NAMESPACE environment variable

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2403]
**Please describe the problem you have**

The `CONTOUR_NAMESPACE` environment variable is used by various Contour components, in slightly different ways. Document what this does and how operators can and should use it.

xref #2389

**Comment by jpeach** [comment]
The best place to document this would be in `site/_site/docs/master/configuration.md`, which attempts to document the config file. We can expand this page to fully document the config file, and add command flags and environment variables too.

**Comment by youngnick** [comment]
That sounds good to me.

**Comment by youngnick** [comment]
@jpeach what more do you think needs to be done here?

**Comment by jpeach** [comment]
> @jpeach what more do you think needs to be done here?

CONTOUR_NAMESPACE is also used for:
-  the bootstrap `--namespace` flag
- the certgen `--namespace` flag
- the serve `--envoy-service-namespace` flag

**Comment by youngnick** [comment]
Removed from "In Progress" since noone is currently assigned or working on this.

**Comment by skriss** [comment]
Looks like there are a couple of options here:

1) add an "Environment Variables" section to `site/docs/master/configuration.md` which specifically documents the `CONTOUR_NAMESPACE` env var (i.e. which flags on which commands it serves as a default for)
2) expand `site/docs/master/configuration.md` to additionally document all CLI flags for all `contour` subcommands, including any env var defaults

Option 1's a lot less work, so I'll probably start with that. 

Re: Option 2 - are we interested in maintaining docs on all of the CLI flags for all of the contour commands? I'm envisioning something like the following table that would correlate the config file field names (for `contour serve`, when available), CLI flags, and environment variables for each command:

| Config File Field Name | CLI Flag | Environment Variable | Default | Description |
|----------------------- |---------|----------------------|---------|------------|
| `envoy-service-namespace` | `--envoy-service-namespace` | `CONTOUR_NAMESPACE` | `projectcontour` | Envoy service namespace |
...

But this is more upfront work plus ongoing maintenance burden, so want to see what others think before going down that route. FWIW I do think it'd be useful documentation for users.

**Comment by jpeach** [comment]
@skriss Option 2 is where we need to end up. I thought there was an issue for that, but my memory is faulty. Personally, I'm happy if you want to start with (1) but done in a way that someone could later expand into (2), if that's applicable.

Ideally option 2 would generate documentation from the current source, but when I looked at it, it seemed hard to do that with kingpin

**Comment by youngnick** [comment]
I agree that Option 2 is the end goal, but also that Option 1 is a good place to start.
