### ISSUE TITLE
Upgrade to Go 1.14

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2409]
**Please describe the problem you have**

Go [1.14](https://golang.org/doc/go1.14) is out, so we should upgrade.

**Comment by jpeach** [comment]
I marked this for the 1.4 milestone, but really what I'd like to do here is switch over first thing after we cut the 1.4.0 release. That way we get a full release cycle to experience the upgrade.

**Comment by jpeach** [comment]
@stevesloka @youngnick WDYT?

**Comment by stevesloka** [comment]
Sounds fine to me. So you want to drop this into 1.15? 

What's the hesitation not to just switch now? I'm using go 1.14 locally on my machine without issues.

**Comment by jpeach** [comment]
> Sounds fine to me. So you want to drop this into 1.15?
> 
> What's the hesitation not to just switch now? I'm using go 1.14 locally on my machine without issues.

If we do have any issues (unlikely), they would be subtle, so I was thinking it would be best to have a full release cycle. There's no urgency on this, so that seemed to be the path with the least possible risk :)

**Comment by stevesloka** [comment]
🎉 🤸‍♂ 🤸‍♀ 🎉

**Comment by youngnick** [comment]
That sounds good to me.

**Comment by moderation** [comment]
Go 1.14.2 released today - https://golang.org/doc/devel/release.html#go1.14.minor
