### ISSUE TITLE
HTTPS connection resets since upgrade

### ISSUE THREAD

**Issue by remmeier** [projectcontour/contour#2413]
We updated our old contour 0.6.x setup to the most recent 1.3 version. It mostly works great. We make use of GKE, contour and a few rest services.  

We have a number of services/clients that poll our  services in regular intervals between one and five minutes. Unfortunately, since the update a few of those do not manage to make more than one call. The second  one fails with a HTTPS protocol error / "connection reset". It seems to be related to the keep-alive handling / idle configuration of envoy. When manually forcing clients to have a low keep alive timeout, they will make a new connection on their own and we don't' have the issue.

When looking at 
https://projectcontour.io/docs/master/troubleshooting/
or  
https://projectcontour.io/docs/master/annotations/
have not seen anything about this topic.

Is there something users have to be aware of?

**Comment by jpeach** [comment]
@remmeier I assume that you upgraded your Envoy at the same time as Contour?

**Comment by remmeier** [comment]
yes from https://raw.githubusercontent.com/projectcontour/contour/release-1.3/examples/render/contour.yaml:

docker.io/projectcontour/contour:v1.3.0
docker.io/envoyproxy/envoy:v1.13.1

**Comment by stevesloka** [comment]
Hey @remmeier so your clients are making requests from outside the cluster into the cluster? 

What are you setting to work around this issue? I'm just trying to understand the problem a bit more.

**Comment by remmeier** [comment]
yes, outside the cluster. If we override the client HTTP keep alive strategy, it works:

```builder.setKeepAliveStrategy((response, context) -> 30000```

We make use of a default Java  stack with untertow behind. No custom settings or anything. So I was hoping for it to work out-of-the-box. Not quite sure yet where to look. Whether we can tune setting on our internal servers. But since  contour/envoy is in contract with the clients, i would have hoped for it to work out of the box?

The issue seems limited to HTTPS, not HTTP (90% sure about that, will look further into tohat, some testing succeeds, but then we noticed that only for HTTP). 

Thank you for your help!

**Comment by remmeier** [comment]
is there a possibility to specify a keep-alive strategy in contour? I would have expected something like:

```
Connection: Keep-Alive
Keep-Alive: "timeout=15, max=1000
```

Without setting a timeout, at some point the connection still seems open, but SSL is not able to handling it anymore and causing the issue above.

**Comment by ravilr** [comment]
from your comments, it looks like this could be running into Envoy's downstream idle timeout: https://www.envoyproxy.io/docs/envoy/v1.14.1/faq/configuration/timeouts#connection-timeouts

your client could be attempting to send data on a connection that had been closed by the Envoy due to idle timeout, and Envoy send a TCP RST/ connection reset.

Contour seem to be hardcoding idleTimeout configuration it applies to Envoy, to 60 secs:
https://github.com/projectcontour/contour/blob/d174fcf185cab8c16b497756a962a681e20fcf8e/internal/envoy/listener.go#L141

1. If Contour allows this httpConnMgr idleTimeout to be configurable through https://projectcontour.io/docs/v1.4.0/configuration/, that is something you could have tried tuning for your specific Contour deployment.

2. Or you could try configuring retries in httpClient configuration on your client side.

**Comment by youngnick** [comment]
xref #2225, we're looking into adding configurability of the Contour defaults (that is, the app-wide setting, rather than a HTTPProxy or Ingress-level one).

**Comment by skriss** [comment]
@remmeier FYI, we've merged https://github.com/projectcontour/contour/pull/2632, which allows the envoy `idle_timeout` to be tuned via the Contour config file. I'd be interested to see if changing the value solves your issue. It'll be included in the next release, or you could try `projectcontour/contour:master` if you're comfortable testing the latest development build.

https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts may also be a useful reference.

**Comment by skriss** [comment]
@remmeier we've just released v1.7.0 (https://github.com/projectcontour/contour/releases/tag/v1.7.0) which includes the additional config setting mentioned just above. If you get a chance, please try it out and let us know if adjusting that timeout adddresses your issue or not.

**Comment by skriss** [comment]
closing this out due to inactivity, feel free to reach out again as needed.
