### ISSUE TITLE
question about container images used by contour

### ISSUE THREAD

**Issue by curx** [projectcontour/contour#2423]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I'm playing with Contour right now and I'm figuring out why the image of the certifiacte job is :lastest and not the same version as for the other containers?
Is there a reason for this?

**What did you expect to happen:**
All images of contour should use the same, e.g. version=1.3.0

**Anything else you would like to add:**

Images from: https://projectcontour.io/quickstart/contour.yaml

contour.yaml:        image: docker.io/projectcontour/contour:latest
contour.yaml:        image: docker.io/projectcontour/contour:v1.3.0
contour.yaml:        image: docker.io/projectcontour/contour:v1.3.0
contour.yaml:        image: docker.io/envoyproxy/envoy:v1.13.1
contour.yaml:        image: docker.io/projectcontour/contour:v1.3.0

from github/example/contour:
contour/examples/contour/02-job-certgen.yaml:        image: docker.io/projectcontour/contour:latest
contour/examples/contour/03-contour.yaml:        image: docker.io/projectcontour/contour:master
contour/examples/contour/03-envoy.yaml:        image: docker.io/projectcontour/contour:master
contour/examples/contour/03-envoy.yaml:        image: docker.io/envoyproxy/envoy:v1.13.1
contour/examples/contour/03-envoy.yaml:        image: docker.io/projectcontour/contour:master

Thanks,
Thorsten

**Comment by stevesloka** [comment]
The reason the image tag on the job is `:latest` is because if you pin to a specific version, when you `kubectl apply -f` for an upgrade, it will fail since you can't mutate the job, so this is just a simple workaround. 

The tags in `example/contour` point to master since they aren't a release. The images in each release tag do point to the version that exists for that release.

**Comment by curx** [comment]
@stevesloka thanks for the clarification

**Comment by jpeach** [comment]
xref #2395
