### ISSUE TITLE
Support Service AppProtocol field

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2431]
Kubernetes 1.8 adds an [appProtocol](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#serviceport-v1-core) field to the Service. This is an optional feature that is enabled with the ServiceAppProtocol [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/).

We already support this concept in a Contour-specific way, so we should support this standard field in Contour too. We need to be careful how we resolve this against the equivalent field in labels and HTTPProxy.

**Comment by davinkevin** [comment]
This parameter is now globally available in kubernetes v1.20+, is this planned to be integrated into Contour?

Thank you 👍

**Comment by davinkevin** [comment]
With GatewayAPI, it's now integrated, no?

**Comment by sunjayBhatia** [comment]
Yes, as of 1.28.0+ Contour supports backend protocol selection with Gateway API: https://github.com/projectcontour/contour/blob/main/changelogs/CHANGELOG-v1.28.0.md#gateway-api-backend-protocol-selection

**Comment by lubronzhan** [comment]
Cool I can help on this while waiting for the review for other PR

**Comment by davinkevin** [comment]
up?
