### ISSUE TITLE
Test contour and public cloud ingress comparison

### ISSUE THREAD

**Issue by iyacontrol** [projectcontour/contour#2433]
how to optimize contour？ i use ab to test contour and elb.

result:
contour:

> 

Server Software: | envoy
-- | --
Server Port | 80
Document Path | /
Document Length | 612 bytes
Concurrency Level | 10
Time taken for tests | 12.048 seconds
Complete requests | 100
Failed requests | 0
Total transferred | 87200 bytes
HTML transferred | 61200 bytes
Requests per second | 8.30
Transfer rate | 7.07 kb/s received

cloud ingress :

> 

Server Software: | elb
-- | --
Server Port | 80
Document Path | /
Document Length | 612 bytes
Concurrency Level | 10
Time taken for tests | 1.828 seconds
Complete requests | 100
Failed requests | 0
Total transferred | 83600  bytes
HTML transferred | 61200 bytes
Requests per second | 54.70
Transfer rate | 44.66 kb/s received

**Environment:**
- Contour version: 1.2.1
- Kubernetes version: 1.13:

**Comment by jpeach** [comment]
I spent some time replicating this.

I spun up a 4 node cluster on GKE with [this script](https://github.com/jpeach/kustomize/blob/master/hack/gke-make-cluster.sh). My backend service was [this echo server](https://github.com/kubernetes-sigs/ingress-controller-conformance/blob/master/tools/echoserver.go), which `ab` can drive at 32K RPS locally on my laptop. I did a variety of simple tests. When I run `ab`, I am doing `ab -k -c 4 -t -n 9999999`.

RPS | Description 
-- | -- 
9000 | Running both ab and echo server in the same container. Networking completely over loopback.
3000 | Running ab inside the envoy container, so the first hop is loopback, the second hop is the cluster network.
170 | Running ab from my laptop. This goes over corporate VPN to the GKE load balancer, to envoy, then across the cluster network.
4  | If you force envoy to generate a 404 it seems incredibly slow. | 

Note that this is all pretty quick & dirty and is only interesting for the comparison.
