### ISSUE TITLE
ExternalName proxying uses external service name for SNI

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2437]
If a user wants to proxy to an external resource using Kubernetes service type `externalName`, and "tls" is set on the service, the SNI used during the proxy is the value of the `externalName`. 

If, for example, a user wants to proxy to a resource using externalName, but the `host` header doesn't match, the wrong SNI is used.

What this example needs is to use the value of the `requestsHeadersPolicy` rewrite as the SNI value not the externalName. 

Here's where the change needs to be done: https://github.com/projectcontour/contour/blob/master/internal/envoy/cluster.go#L83

**Comment by stevesloka** [comment]
I think a solution to this could be to set the SNI for the route to use the `requestHeadersPolicy.Host` value if defined, otherwise use the `externalName` as it is today. The thought is that the header that's rewritten should match the SNI set on the request.

**Comment by jpeach** [comment]
xref #1982 

Looks like we originally discussed and intended to set the SNI server name https://github.com/projectcontour/contour/issues/1982#issuecomment-565202633 but that it was removed during code review https://github.com/projectcontour/contour/pull/2046#pullrequestreview-331640300.

I'm very much in favor of Contour getting this right by default, and not requiring users to mess around with arcane SNI config or having to debug why it doesn't work.
