### ISSUE TITLE
support fallback certificate in v1beta1/Ingress

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2453]
#2428 has a design to enable fallback certs in `HTTPProxy`. This issue is to follow up with thoughts around how to apply to Ingress v1beta1.

_Originally posted by @stevesloka in https://github.com/projectcontour/contour/pull/2428_

**Comment by ravilr** [comment]
I guess the logic to support fallback certificate feature in Ingress resource wouldn't be that different from HTTPProxy.
If ingressResource.Spec.TLS is not set and an fallback annotation is set, add the hosts and corresponding route rules from that ingressResource to ingress_fallback route config during dag visit.

**Comment by echupriyanov** [comment]
Any updates on this feature?

**Comment by sunjayBhatia** [comment]
Cc @xaleeks if this is something on your priority list

If we were to support this on Ingress, would have to be via an annotation to enable it, however which vhost to apply a fallback cert to is problematic as an Ingress could have many

**Comment by youngnick** [comment]
Yes, I agree that it would need an annotation, and would also need clear documentation about what would happen in various Ingress cases (like multiple vhosts).

**Comment by sunjayBhatia** [comment]
same boat as https://github.com/projectcontour/contour/issues/4556 moving out of a milestone until we get more info
