### ISSUE TITLE
HTTPProxy Upstream TLS doc - sample YAML doesn't match the scenario explained.

### ISSUE THREAD

**Issue by georgegoh** [projectcontour/contour#2457]
**What steps did you take and what happened:**

Documentation at:
https://github.com/projectcontour/contour/blob/master/site/docs/master/httpproxy.md#upstream-tls

Describes:
"""
In this example, the upstream service is named https and uses port 443
"""

The sample YAML does not reflect this statement, and can be misleading to the reader.

**What did you expect to happen:**

I'd like to see both the samples for HTTPProxy, and also the sample for the upstream service with the appropriate annotations, for an e2e example.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version:
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by jpeach** [comment]
The documentation says

> A HTTPProxy can proxy to an upstream TLS connection by first annotating the upstream Kubernetes service with: projectcontour.io/upstream-protocol.tls: "443,https". This annotation tells Contour which port should be used for the TLS connection. In this example, the upstream service is named https and uses port 443.

In this context "https" refers not to the service, but to the backend protocol used to proxy to the service.
