### ISSUE TITLE
HTTPProxy inclusion with upstream weight capability for different namespaces

### ISSUE THREAD

**Issue by shaktiprasadrath** [projectcontour/contour#2461]
I have a micro service which is deployed in a namespace **tom** and when a new version of micro service will come, I want to deploy that in a different  namespace **jerry**. Then as part of canary deployment model, I want to move the traffic(based on weight) from micro service in namespace **tom** to micro service in namespace **jerry**.
It seems with the current version this arrangement is not possible. I have attached the code.
[microservice.txt](https://github.com/projectcontour/contour/files/4522791/microservice.txt)

If the above the scenario is not exist in current version, then please see if it is possible to add this as an new feature in your upcoming release.

**Comment by stevesloka** [comment]
Thanks for the issue and for chatting on Slack @shaktiprasadrath! The main reason this hasn't been implemented is that it breaks the security boundary when referencing services across namespaces. 

I think there are ways that we could still accomplish this but we'd need to discuss the API and the side effects by implementing this.

**Comment by shaktiprasadrath** [comment]
Thanks Steve. Please do update this thread based on any progress.
Appreciate your help.
