### ISSUE TITLE
Need Envoy http filter in contour

### ISSUE THREAD

**Issue by manvindar** [projectcontour/contour#2475]
Problem: we have an API domain which requires api-key on the header , when a user sends a request to that domain then Lua filter calls another service to check if it's a valid api-key, if true then it creates a JSON object and posts it to another service if false then it sends a response to the user that API key  is not valid

lua HTTP filter is explainer here in envoy's documentation
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter

example
https://github.com/envoyproxy/envoy/tree/0b0213fdc38eb0d0346659cf90bd4c502cadb00c/examples/lua

**Comment by jpeach** [comment]
xref #432

**Comment by jpeach** [comment]
This use case sounds it could be satisfied by en external authentication service that validates the API key. External authentication is tracked in #432 and there is initial scoping in #2459.
