### ISSUE TITLE
[Doc Fix]: AWS annotation for enabling proxy-protocol doesn't work

### ISSUE THREAD

**Issue by savithruml** [projectcontour/contour#2478]
**What steps did you take and what happened:**
AWS EKS service annotation to enable proxy-protocol on NLB doesn't take any action. This has been confirmed with AWS support & here's an additional issue to back it up https://github.com/kubernetes/kubernetes/issues/57250.

**What did you expect to happen:**
The annotation `service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'` should enable proxy-protocol on NLB but it doesn't. Hence the documentation must be fixed on Contour's page which discusses the scenario https://projectcontour.io/guides/proxy-proto/

**Anything else you would like to add:**
Need to remove the content of this section [Enable PROXY protocol on your service in AWS](https://github.com/projectcontour/contour/blob/master/site/_guides/proxy-proto.md#enable-proxy-protocol-on-your-service-in-aws) & instead link it to [AWS documentation to enable proxy-protocol](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#proxy-protocol) to manually enable/disable through AWS console.

**Environment:**

- Cloud provider or hardware configuration: AWS EKS

**Comment by stevesloka** [comment]
Thanks for reporting this @savithruml! Would you like to contribute a PR to update? Happy to help and walk through this if you have questions.

**Comment by savithruml** [comment]
> Thanks for reporting this @savithruml! Would you like to contribute a PR to update? Happy to help and walk through this if you have questions.

Sure @stevesloka, sent out a PR.
