### ISSUE TITLE
Documentation for multi-tenant Contour

### ISSUE THREAD

**Issue by cten** [projectcontour/contour#2484]
Document the use-case of running more than 1 Contour install in a cluster within the same non-default namespace (ie. not "projectcontour").

For clarity we will reference the deployments as internal and external; and everything will be in the "contour" namespace instead of "projectcontour".

Need separate contour-configs for each A and B, each with leader-elect settings set. Also update the Deployments to reference these new ConfigMap names.
ConfigMap = contour-internal
```
leaderelection:
      configmap-name: leader-elect-internal
      configmap-namespace: contour
```
ConfigMap = contour-external
```
leaderelection:
      configmap-name: leader-elect-external
      configmap-namespace: contour
```

Extra args for Deployment of contour-internal:
```
        - --ingress-class-name=contour-internal
        - --envoy-service-name=envoy-internal
        - --envoy-service-namespace=contour
```
Extra args for Deployment of contour-external:
```
        - --stats-port=8003
        - --ingress-class-name=contour-external
        - --envoy-service-name=envoy-external
        - --envoy-service-namespace=contour
        - --envoy-service-http-port=8080
        - --envoy-service-https-port=8443
```

Update the ports used by envoy container in the external Envoy DS from 80 and 443 to 8080 and 8443. Also update the external Envoy Service definition to point at ports 8080 and 8443.

Extra flag added to the external Envoy DaemonSet only: ```--serve-port=8091``` this also requires updating the ports elsewhere in the DS from 8090 to 8091.

Extra flag added to the internal Envoy DaemonSet: ```--base-id 1``` 
Extra flag added to the external Envoy DaemonSet: ```--base-id 2``` 

Update the internal Envoy DaemonSet initContainer flag to be ```--xds-address=contour-internal```
Update the external Envoy DaemonSet initContainer flag to be ```--xds-address=contour-external``` also add this flag ```--admin-port=9002```

**Comment by youngnick** [comment]
Thanks for these great notes @cten!

**Comment by jpeach** [comment]
Duplicate of #855

**Comment by xaleeks** [comment]
@cten  First of all, thanks so much for documenting this.  I assume this is for the knative net contour, unless there’s another extremely similar setup.  Do you mind submitting a PR to add this to our official docs?  We would love to publicize knative and add a ref to the work the knative team did here

**Comment by youngnick** [comment]
I think that we'll need to write this documentation again once the Operator has support for multiple installations as well.
