### ISSUE TITLE
Ability to vendor contour configuration files

### ISSUE THREAD

**Issue by shashwathi** [projectcontour/contour#2486]
## Problem
[Knative](https://github.com/knative/) project is starting to switch individual projects to use Go modules instead of Godep. [`net-contour`](https://github.com/knative/net-contour) project provides configuration yaml files in [examples folder](https://github.com/projectcontour/contour/tree/master/examples/contour) for generating contour configurations.
In Godep world the whole repo is vendored in and [knative scripts](https://github.com/knative/net-contour/blob/master/hack/update-deps.sh#L112) would refer to the vendored example files. Folders with only non Go files are not vendored by Gomod. 

Possible solutions : One option is to add a dummy go file so we can vendor in `examples/contour` folder.

We are open to other ideas or thoughts? Thanks 

cc @andrew-su

**Comment by stevesloka** [comment]
//cc #2254

**Comment by stevesloka** [comment]
I think adding a dummy go file in that directory is fine, the only caution we need to make is how to maintain going forward. There's some work to break apart the current `examples` folder into pieces that would break this (or require more dummy files). 

We just need to decide on what we're going to maintain long-term and how.

**Comment by jpeach** [comment]
xref #2474

**Comment by youngnick** [comment]
Yes, I think that this should wait until we decide what we're doing with #2474 - knative will have a bunch of work to update their installs if we do that as well, so let's talk there.

**Comment by mattmoor** [comment]
Ack that this might not be the forever plan (or even the 1.5+ plan), but I wonder if you would be receptive to landing `dummy.go` on `release-1.4` to unblock our `go mod` migration?  🙏

The idea of trying to land `go mod` while simultaneously pulling in kustomize scares me a little, so I'm mostly looking for ways we can take it in pieces with the least disruption to what you all have planned.

**Comment by stevesloka** [comment]
Closed via #2503

**Comment by mattmoor** [comment]
🤔 I didn't close this with my PR because we still need a story going forward.  If that's tracked elsewhere (#2474?) then 👍

**Comment by youngnick** [comment]
I think part of the story with kustomize is for us to understand how knative is consuming Contour and make sure that whatever we do has a way forward for you too.
