### ISSUE TITLE
config file: refresh automatically when file changes

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2491]
If a value in the configuration file changes, the only way to have contour update this is to kill the Contour pod. It would be neat to have Contour automatically refreshed the values from the config file and processed the changes. 

There's a bunch of startup work that would need to be thought about when doing this.

**Comment by stevesloka** [comment]
An initial start might be to detect the config file changed and exit contour so that it gets restarted.

**Comment by youngnick** [comment]
I can see the use case, but I think that it may create more problems than it solves.

Doing this makes it not possible to stage config file changes; if you change the configmap, then the contour pods will restart as soon as they see it. Some operators want to be able to control how the rollout happens.

In particular, I'm thinking of customers who run a single Contour in a busy cluster; we still haven't managed to completely get rid of ordering problems at startup, which we've seen can cause intermittent problems when Contour restarts.

As a second point, I think that for most things that use a configmap for config, the usual contract is to expect the thing to be kicked.

App startup is one of those things that, often, it's good to have a human in the loop on, to prevent cascading failures. 

Those are the costs I can see, what do you think are the benefits we get out of doing this? Obviously, if we can get enough benefit, the tradeoffs may be worth it.

**Comment by stevesloka** [comment]
I agree with you on all your points. This came up when working on the fallbackCertificate work. I wanted to change which cert was the fallback, so I updated the configmap, then had to manually bounce all the Contour pods in my cluster.

**Comment by jpeach** [comment]
> I agree with you on all your points. This came up when working on the fallbackCertificate work. I wanted to change which cert was the fallback, so I updated the configmap, then had to manually bounce all the Contour pods in my cluster.

Probably a little late, but what if the fallback certificate was a selector?

**Comment by youngnick** [comment]
So, it seems like this particular idea - having config file changes cause Contour to restart - is probably a no go. But I think it's good to talk about the flow when using the fallback cert. Do you want to raise another issue about that @stevesloka ?

**Comment by lubronzhan** [comment]
One way to do it is through github.com/fsnotify/fsnotify, we already implemented in cloud-proivder-vsphere 

https://github.com/kubernetes/cloud-provider-vsphere/blob/master/cmd/vsphere-cloud-controller-manager/main.go#L260-L280

**Comment by lubronzhan** [comment]
Close due to we are moving away from configMap as part of this initiative https://github.com/projectcontour/contour/issues/6159
