### ISSUE TITLE
Misleading status message with TLS passthrough and secret

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2501]
If you create a HTTPProxy document that contains both the `tls.passthrough` and `tls.secretName`fields, you get a really misleading error status:

```
$ k get proxies
NAME   FQDN                     TLS SECRET   STATUS    STATUS DESCRIPTION
echo   echo.projectcontour.io   echo-one     invalid   tcpproxy: missing tls.passthrough or tls.secretName
```

This is because:
```Go
        tlsValid = tls.Passthrough != !isBlank(tls.SecretName)

        if proxy.Spec.TCPProxy != nil {
                if !tlsValid {
                        sw.SetInvalid("tcpproxy: missing tls.passthrough or tls.secretName")
                        return
                }
     
        }
```

**Comment by jpeach** [comment]
To clarify, it's misleading because neither field is missing. The problem is actually that you can't specify both.

**Comment by skriss** [comment]
godoc on `TLS.Passthrough`:

```
// If Passthrough is set to true, the SecretName will be ignored
// and the encrypted handshake will be passed through to the
// backing cluster.
```

Should we do what the godoc says, and ignore `SecretName` if `Passthrough == true`? Or should we mark it invalid with an accurate error (that they can't both be set)?

**Comment by youngnick** [comment]
I think that having an accurate error is better UX, and the godoc should be updated accordingly.
