### ISSUE TITLE
docs: Terminate TLS at AWS NLB

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2509]
Need to update docs to show how to use an AWS NLB and terminate TLS there, then proxy traffic to Contour running behind the NLB.

_Originally posted by @stevesloka in https://github.com/projectcontour/contour/issues/2441#issuecomment-625853628_

**Comment by geoffcline** [comment]
Hi from AWS 👋 I'm taking a look

**Comment by youngnick** [comment]
I'll assign this to you for now @geoffcline, please ping us with any updates!

**Comment by xaleeks** [comment]
Seems this is done, going to close it out
