### ISSUE TITLE
status is not getting set on resources properly

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2522]
Was testing out other features on my cluster and found the expected status hadn't updated on my object. I assumed it was my code with the new status, but upon further investigation, I see various errors around setting status for `HTTPProxy` objects.

The interesting bit is I don't always get an error, meaning, I change my resources and I sometimes get the status updates, other times I do not BUT I do get an error log, and the last case is the status does not change and I do NOT get an error. 

```
time="2020-05-13T20:23:32Z" level=error msg="failed to set status" context=contourEventHandler desc="this HTTPProxy is not part of a delegation chain from a root HTTPProxy" error="Operation cannot be fulfilled on httpproxies.projectcontour.io \"infosite\": the object has been modified; please apply your changes to the latest version and try again" name=infosite namespace=projectcontour-marketing status=orphaned
```

**Comment by stevesloka** [comment]
NOTE: I validated with v1.4.0 and that seems to work fine.

**Comment by youngnick** [comment]
Was this with `master`? This is the exact thing I'm working on solving with my current HTTPProxy status refactor.

**Comment by youngnick** [comment]
To be more clear - this happens when an update is rejected by the apiserver because the object that it's based on has been modified since Contour got it. It usually happens when there is more than one thing attempting to update the object concurrently (like two Informers acting on the same object).

**Comment by stevesloka** [comment]
yup this was on `master`. It worked on a new set of kind clusters, then I spun up a new EKS cluster and it all worked, so no idea what went wrong. 

My suspicion it's got to do with the move to the subresource for status.

**Comment by stevesloka** [comment]
I take that back, it just happened again on a clean cluster. This one is a v1.15. I'm upgrading now to v1.16.

**Comment by stevesloka** [comment]
So this isn't a version issue I don't think, I had to go back to Contour v1.3.0 for this to work properly. 

What I've found is the child proxies do not get updated, only the root. 

Here are my repro steps:

```bash
# Install Contour
$ kubectl apply -f examples/contour/ 

# Deploy example app
$ kubectl apply -f site/examples/proxydemo/ 

# Validate that all status for 3 proxies are "Valid"
$ kubectl get proxy -A

---
NAMESPACE                  NAME       FQDN                      TLS SECRET   STATUS   STATUS DESCRIPTION
projectcontour-marketing   blogsite                                          valid    valid HTTPProxy
projectcontour-marketing   infosite                                          valid    valid HTTPProxy
projectcontour-roots       root       local.projectcontour.io                valid    valid HTTPProxy
---

# Edit root proxy and change the inclusion from `blogsite` to `blogsite99` (anything invalid)
# Validate that the root proxy is "Invalid" and the child proxies are "Orphaned"
$ kubectl get proxy -A

# Actual (Note: The child proxies keep the old status, so in this example is was "Valid")
NAMESPACE                  NAME       FQDN                      TLS SECRET   STATUS    STATUS DESCRIPTION
projectcontour-marketing   blogsite                                          valid     valid HTTPProxy
projectcontour-marketing   infosite                                          valid     valid HTTPProxy
projectcontour-roots       root       local.projectcontour.io                invalid   include projectcontour-marketing/blogsit88e not found

# Expected 
NAMESPACE                  NAME       FQDN                      TLS SECRET   STATUS     STATUS DESCRIPTION
projectcontour-marketing   blogsite                                          orphaned   this HTTPProxy is not part of a delegation chain from a root HTTPProxy
projectcontour-marketing   infosite                                          orphaned   this HTTPProxy is not part of a delegation chain from a root HTTPProxy
projectcontour-roots       root       local.projectcontour.io                invalid    include projectcontour-marketing/blogsit66e not found
```
