### ISSUE TITLE
Not all envoy access log command operators are mapped

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2523]
There's no log field mapping for `%RESPONSE_CODE_DETAILS%`. 

https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#command-operators

Looks like we are missing

- `%REQUEST_DURATION%`
- `%RESPONSE_DURATION%`
- `%RESPONSE_CODE_DETAILS%`
- all the `%DOWNSTREAM` keys
- `%HOSTNAME`

Canonical envoy list of keys looks like it is in `source/common/access_log/access_log_formatter.cc`

**Comment by youngnick** [comment]
When we did the original setup for JSON logging, we used the default JSON logging output of Envoy at the time, with the intent we would add more later. I guess it's later?

**Comment by jpeach** [comment]
> When we did the original setup for JSON logging, we used the default JSON logging output of Envoy at the time, with the intent we would add more later. I guess it's later?

Makes sense. There are some keys that take parameters which makes them hard to express in JSON, but I think we should just add everything else that's missing.

**Comment by Tazminia** [comment]
Hello, I just discovered the project although, I have been working with kubernetes and ingress controllers for a few months now (mainly nginx). I would like to give you a hand if you want, but I will probably need some assistance

**Comment by jpeach** [comment]
> Hello, I just discovered the project although, I have been working with kubernetes and ingress controllers for a few months now (mainly nginx). I would like to give you a hand if you want, but I will probably need some assistance

That sounds great! Take a look at our [contribution guide](https://github.com/projectcontour/contour/blob/master/CONTRIBUTING.md) to get started. Contour people hang out in [slack](https://kubernetes.slack.com/messages/contour) if you have questions.

For this PR, it should be a matter of adding field mappings for all the Envoy log fields that don't require a parameter (there's no way to specify parameters in JSON). I'll be happy to shepherd your changes.

**Comment by Tazminia** [comment]
So if I get it right, the ones we are not willing to map are the following:

- %REQ(X?Y):Z%
- %RESP(X?Y):Z%
- %TRAILER(X?Y):Z%
- %DYNAMIC_METADATA(NAMESPACE:KEY*):Z%
- %FILTER_STATE(KEY:F):Z%

There are the fields that look like they need some paramters.

**Comment by jpeach** [comment]
> So if I get it right, the ones we are not willing to map are the following:
> 
> * %REQ(X?Y):Z%
> * %RESP(X?Y):Z%
> * %TRAILER(X?Y):Z%
> * %DYNAMIC_METADATA(NAMESPACE:KEY*):Z%
> * %FILTER_STATE(KEY:F):Z%
> 
> There are the fields that look like they need some paramters.

Yep, that sounds about right. It would be good to think about how to support these kinds of logging keys, but that's a larger problem and we can leave that to a separate issue :)

**Comment by sunjayBhatia** [comment]
this is out of date, the access log operators listed here are all supported
