### ISSUE TITLE
Certgen can emit certificates with an inconsistent CA

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2531]
**What steps did you take and what happened:**

* Delete the `contourcert` and `envoycert` certificates
* Reapply the certgen job

```
$ k logs -n projectcontour contour-certgen-gwn7r
Outputting certs to Kubernetes in namespace projectcontour/
secret/cacert already exists
secret/contourcert created
secret/envoycert created
```

At this point, the contour and envoy certificates have been generated with a different CA certificate that isn't known to anyone.

**What did you expect to happen:**

🤷

**Comment by youngnick** [comment]
certgen was designed to assume that the CA cert would be rotated when you reran the certgen job, and then thrown away, since it was intended to be for initial trial use.

**Comment by jpeach** [comment]
This would be substantially resolved by including the CA certificate in each secret, since that would mean that at least a secret was self-contained.

xref #2494
xref #2494

**Comment by youngnick** [comment]
Agreed that including the CA cert in each secret is a better option.

**Comment by jpeach** [comment]
Duplicate of #2494
