### ISSUE TITLE
certgen doesn't have enough RBAC permissions to update secrets

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2538]
**What steps did you take and what happened:**

Re-run a patched certgen job that attempts to update secrets

```
secrets "contourcert" is forbidden: User "system:serviceaccount:projectcontour:contour-certgen" cannot update resource "secrets" in API group "" in the namespace "projectcontour"
```

**Comment by youngnick** [comment]
This was a deliberate design decision previously, since it was only *creating* secrets, not updating them.
