### ISSUE TITLE
--ingress-status-address supports only a single address

### ISSUE THREAD

**Issue by al45tair** [projectcontour/contour#2540]
**What steps did you take and what happened:**
See #2539.

I tried using `--ingress-status-address` as a workaround, with a list of comma-separated IP addresses. The result was an error message

    time="2020-05-19T05:54:53Z" level=error msg="unable to update status" context=IngressStatusUpdater error="Ingress.extensions \"nginx-test\" is invalid: status.loadBalancer.ingress[0].hostname: Invalid value: \"192.168.1.17,192.168.1.18,192.168.1.19,192.168.1.20\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')" name=nginx-test namespace=ajh

**What did you expect to happen:**
I expected all of the addresses to appear on my Ingress.

**Anything else you would like to add:**
It's true that I could specify a DNS name that points to all of those IP addresses. It's also true that the result of doing that, if I want to use External DNS (and who doesn't?), is that I'll end up with a CNAME record. I don't want CNAME records. So I'd like to set multiple IP addresses.

Or, actually, for Contour to do what `ingress-nginx` does, give or take, and give the IP addresses of all of the nodes on which the `envoy` Pods are running (see #2539), then I wouldn't need to use this option in the first place.

**Environment:**

- Contour version: e1961860
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/arm64"}
- Kubernetes installer & version: kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:41:38Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/arm64"}
- Cloud provider or hardware configuration: 4 x Raspberry Pi 4 (4GB)
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04 LTS

**Comment by jpeach** [comment]
Accepting comma-separated names seems pretty reasonable to me.
