### ISSUE TITLE
Introduce feature flags machinery

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2543]
**Please describe the problem you have**

As we introduce more features and tuning knobs into Contour, we increase the probability of some behavior being desirable in one cluster but harmful in another. We also increase the probability of needing to ship experimental features that can be disabled in configuration.

So we should think about and discuss a feature flagging mechanism in Contour - how it would work, what kinds of application we think it might have, and how it interacts with our compatibility commitments.

**Comment by xaleeks** [comment]
Are you referring to functionality like feature gate like in k8s, so you can enable or disable them with command line flags and query for supported versions and EOL info.

**Comment by youngnick** [comment]
I think that covers what we're talking about, yes.

**Comment by sunjayBhatia** [comment]
closing, I think we're too far along at this point to start this machinery, but can reopen if it comes up again
