### ISSUE TITLE
HTTPProxy timeoutPolicy.response of "0s" (as mentioned in docs) is NOT infinite

### ISSUE THREAD

**Issue by kevincantu** [projectcontour/contour#2544]
With contour 1.4.0, I've just attempted to set a timeoutPolicy.response, and "0s" doesn't seem to work.

I expected the value "0s" to mean an infinite timeout, as the docs describe:
> `timeoutPolicy.response` This field can be any positive time period or “infinity”. The time period of 0s will also be treated as infinity. This timeout covers the time from the end of the client request to the end of the upstream response. By default, Envoy has a 15 second value for this timeout. More information can be found in Envoy’s documentation.
https://projectcontour.io/docs/v1.4.0/httpproxy/

First with `"infinity"` (as worked in the old Ingress [annotation](https://projectcontour.io/docs/v1.4.0/annotations/)):
```
      timeoutPolicy:
        response: "infinity"
        idle: "355s"
```

That gives a timeout of zero in Envoy's `/config_dump`:
```
          "route": {
           "cluster": "default/myapp-service/5000/da33a3ff5e",
           "timeout": "0s",
           "idle_timeout": "355s"
          }
```

But then with `"0s"` (as described in the `timeoutPolicy` documentation):
```
      timeoutPolicy:
        response: "0s"
        idle: "355s"
```

That gives a default setting (no timeout field) in Envoy's `/config_dump`:
```
          "route": {
           "cluster": "default/myapp-service/5000/da33a3ff5e",
           "idle_timeout": "355s"
          }
```

So I have a workaround (setting timeoutPolicy.response to "infinity"), but either there's a bug or the docs are out of date.  😺

**Comment by jpeach** [comment]
This looks like a documentation error. The latest version of the API reference describes [timeoutPolicy](https://projectcontour.io/docs/master/api/#projectcontour.io/v1.TimeoutPolicy) accurately.
