### ISSUE TITLE
Add promlint analyzer for metrics static analysis.

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2554]
**Please describe the problem you have**

Add [promlint](https://godoc.org/github.com/prometheus/client_golang/prometheus/testutil/promlint) static analysis to make sure we are using Prometheus metrics conventions consistently.

**Comment by jpeach** [comment]
```
diff --git hack/generate-metrics-doc.go hack/generate-metrics-doc.go
index 7194a55..f3f62df 100644
--- hack/generate-metrics-doc.go
+++ hack/generate-metrics-doc.go
@@ -21,6 +21,7 @@ import (

        "github.com/projectcontour/contour/internal/metrics"
        "github.com/prometheus/client_golang/prometheus"
+       "github.com/prometheus/client_golang/prometheus/testutil/promlint"
        dto "github.com/prometheus/client_model/go"
 )

@@ -78,4 +79,16 @@ func main() {

                f.Close()
        }
+
+       linter := promlint.NewWithMetricFamilies(family)
+       problems, err := linter.Lint()
+       if err != nil {
+               log.Fatalf("promlint failed: %s", err)
+       }
+
+       for _, p := range problems {
+               fmt.Printf("%s: %s\n", p.Metric, p.Text)
+       }
+
+       os.Exit(len(problems))
 }
```

**Comment by abhide** [comment]
I would like to work on this GH issue. 

@stevesloka @jpeach if it's fine, could either of you assign this to me?
I can't assign this GH to myself.

**Comment by abhide** [comment]
Also, seems like there are some linting errors
```➜  contour git:(main) ✗ make generate-metrics-docs 
Generating metrics documentation ...
contour_httpproxy_invalid_total: non-counter metrics should not have "_total" suffix
contour_httpproxy_orphaned_total: non-counter metrics should not have "_total" suffix
contour_httpproxy_root_total: non-counter metrics should not have "_total" suffix
contour_httpproxy_total: non-counter metrics should not have "_total" suffix
contour_httpproxy_valid_total: non-counter metrics should not have "_total" suffix
exit status 5
make: *** [Makefile:218: generate-metrics-docs] Error 1
```
I think we can't just remove `_total` as it would be a "backward incompatible" change; as it can potentially break dashboards/ alerts.

**Comment by stevesloka** [comment]
> I think we can't just remove _total as it would be a "backward incompatible" change; as it can potentially break dashboards/ alerts.

Yeah the backwards bit is the harder part. What's the recommended name?

**Comment by abhide** [comment]
@stevesloka For metrics that aren't type: Counter we need to drop `_total` suffix from the name.
All the metrics flagged above by promlint are gauges.

**Comment by sunjayBhatia** [comment]
we'll probably have to duplicate the existing metrics with a conformant name to get a deprecation plan going for the existing metrics

**Comment by abhide** [comment]
Yes. add new metrics and update description for old ones with deprecation message. 
I guess we will have to update release notes as well.

**Comment by sunjayBhatia** [comment]
I would say the process would be:
- add duplicate metrics with conformant names
- investigate if there is a formal method for deprecating prometheus metrics, if not, maybe just add a tag to indicate these metrics are deprecated (or some other solution if we want to do this) and document the process for this project
- release notes for the release with that change would mention the old metric name and what should be used instead
- open a new issue/PR to track the *removal* of the non-conformant metric names
- wait until the deprecated metrics *should* no longer be in use (1 release? a few? major version bump?) and apply change to remove deprecated names

**Comment by youngnick** [comment]
Traditionally we've done removals like that, yes, with one release in between each stage.

**Comment by abhide** [comment]
Remaining work
- Update CONTRIBUTING doc for depredating metrics
- Update release notes

**Comment by abhide** [comment]
Added release note to #3322. 
Filed #3337 to remove deprecated metrics and enable promlint analyzer.

Closing this issue.
