### ISSUE TITLE
docs: caution users to verify their load balancer approach before updating envoy

### ISSUE THREAD

**Issue by niels-s** [projectcontour/contour#2563]
The Contour documentation on [redeploying envoy](https://projectcontour.io/docs/v1.5.0/redeploy-envoy/) could be more specific by warning the end-user. The redeploy can cause downtime depending on which load balancer setup they are using with different combinations of `externalTrafficPolicy`.

For example, on GKE, the GCLB, when using a VPC native cluster, is smart enough to remove the k8s node from the list of the available backends, so `externalTrafficPolicy: local` isn't a problem.
But when using a solution as MetalLB in combination with `externalTrafficPolicy: local, this can and probably will cause issues since MetalLB isn't smart enough like the GCLB.

It's difficult to cover all potential Loadbalancer solutions, but a word of cautions could help users from running into issues before redeploying envoy.

**Comment by jpeach** [comment]
Thanks @niels-s . We don't always have experience with all the deployment possibilities and infrastructure, so there's definitely some gaps here.

I'd be happy to help you contribute docs for anyone using metal-lb. Reach out on [slack](https://kubernetes.slack.com/messages/contour) or post a PR and we can go from there.
