### ISSUE TITLE
Errors in status updates of HTTPProxy starting with 1.5.0

### ISSUE THREAD

**Issue by primeroz** [projectcontour/contour#2570]
**What steps did you take and what happened:**
Starting with 1.5.0 I started to see , in the contour pod logs, errors about updating the Status of the HTTPProxy resource.

I saw a few different ones, all of them about *object has been modified* and most of the time not even about the object that was actually being *Added/Modified*
```
contour-6595d86dd9-s29lh contour time="2020-06-05T10:02:34Z" level=error msg="failed to set status" context=contourEventHandler desc="valid HTTPProxy" error="Operation cannot be fulfilled on httpproxies.projectcontour.io \"grafana-svc\": the object has been modified; please apply your changes to the latest version and try again" name=grafana-svc namespace=monitoring status=valid

contour-6595d86dd9-s29lh contour time="2020-06-05T10:19:45Z" level=error msg="unable to update status" context=StatusUpdateWriter error="Operation cannot be fulfilled on httpproxies.projectcontour.io \"grafana-svc\": the object has been modified; please apply your changes to the latest version and try again" name=grafana-svc namespace=monitoring

contour-6595d86dd9-s29lh contour time="2020-06-05T09:10:02Z" level=error msg="failed to set status" context=contourEventHandler desc="Spec.VirtualHost.TLS Secret \"ingress-controller/star-letsencrypt-cert\" certificate delegation not permitted" error="Operation cannot be fulfilled on httpproxies.projectcontour.io \"grafana-svc\": the object has been modified; please apply your ch
anges to the latest version and try again" name=grafana-svc namespace=monitoring status=invalid 
```

So to exclude anything funky with my cluster i wrote this [gist](https://gist.github.com/primeroz/d6aa3c62ea5819fdecea04ed6b79fa3c) to reproduce the issue using KIND.

* When using 1.5.0 on either k8s 1.14 or 1.16 when the second httpproxy is applied an error about status update on the first httpproxy is printed
* When using 1.4.0 no errors are printed 

**What did you expect to happen:**

* Clean update of status on httpproxies and no errors

**Anything else you would like to add:**
I think envoy is being configured properly even though those errors are emitted , it was correct everytime i checked.

This can create problems though when waiting on the Status of an HTTPProxy with "kubectl wait" 

**Environment:**

- Contour version: 1.5.0
- Kubernetes version: (use `kubectl version`): 1.14.10 and 1.16.9
- Kubernetes installer & version: Kind and GKE

**Comment by youngnick** [comment]
Thanks for this issue @primeroz. We've seen some similar issues before (#2522), and I believe that they should be fixed by #2560. I'll bump my priority on that and get it done as soon as I can.

**Comment by youngnick** [comment]
I should note I'll use your repro script to check my changes as I go, thanks very much for that.

**Comment by youngnick** [comment]
I've opened #2613 to hopefully fix this, but I haven't been able to reproduce the problem with either current Contour or my branch. @primeroz, can you try using `docker.io/youngnick/contour:dag-status-update` as the image for Contour and seeing if you can reproduce?

**Comment by primeroz** [comment]
@youngnick So this morning i tried the script again and ... i could not get any error either! I then realized that in _my version_ of the script i , by mistake, left contour at 1.4 which never had the issue. 
Once i switched mine to 1.5 i was able to reproduce the error 100% of the time 

```
#####################################
## Creating first instance of HTTPROXY
namespace/podinfo1 created
deployment.apps/podinfo created
service/podinfo created
httpproxy.projectcontour.io/podinfo created

#####################################
## Fetching error logs from contour after first httpproxy created


#####################################
## Creating second instance of HTTPROXY
namespace/podinfo2 created
deployment.apps/podinfo created
service/podinfo created
httpproxy.projectcontour.io/podinfo created

#####################################
## Fetching error logs from contour after second httpproxy created
time="2020-06-19T07:47:21Z" level=error msg="failed to set status" context=contourEventHandler desc="valid HTTPProxy" error="Operation cannot be fulfilled on httpproxies.projectcontour.io \"podinfo\": the object has been modified; please apply your changes to the latest version and try again" name=podinfo namespace=podinfo1 status=valid


#####################################
## Creating 2 more instance of HTTPROXY
namespace/podinfo3 created
deployment.apps/podinfo created
service/podinfo created
httpproxy.projectcontour.io/podinfo created
namespace/podinfo4 created
deployment.apps/podinfo created
service/podinfo created
httpproxy.projectcontour.io/podinfo created

#####################################
## Fetching error logs from contour after 2 more httpproxy created
time="2020-06-19T07:47:28Z" level=error msg="failed to set status" context=contourEventHandler desc="valid HTTPProxy" error="Operation cannot be fulfilled on httpproxies.projectcontour.io \"podinfo\": the object has been modified; please apply your changes to the latest version and try again" name=podinfo namespace=podinfo2 status=valid
time="2020-06-19T07:47:29Z" level=error msg="failed to set status" context=contourEventHandler desc="valid HTTPProxy" error="Operation cannot be fulfilled on httpproxies.projectcontour.io \"podinfo\": the object has been modified; please apply your changes to the latest version and try again" name=podinfo namespace=podinfo1 status=valid
time="2020-06-19T07:47:29Z" level=error msg="failed to set status" context=contourEventHandler desc="valid HTTPProxy" error="Operation cannot be fulfilled on httpproxies.projectcontour.io \"podinfo\": the object has been modified; please apply your changes to the latest version and try again" name=podinfo namespace=podinfo2 status=valid
time="2020-06-19T07:47:29Z" level=error msg="failed to set status" context=contourEventHandler desc="valid HTTPProxy" error="Operation cannot be fulfilled on httpproxies.projectcontour.io \"podinfo\": the object has been modified; please apply your changes to the latest version and try again" name=podinfo namespace=podinfo3 status=valid
```

I checked the uploaded script though and that one does not even have the option to run 1.4 and is hardcoded to 1.5 so i am really confused as to why you are not getting the error, maybe the issue is more subtle then i thought.

Anyway, with your updated image `wget https://raw.githubusercontent.com/projectcontour/contour/release-1.5/examples/render/contour.yaml -O- 2>/dev/null | sed 's/docker\.io\/projectcontour\/contour:v1\.5\.1/docker.io\/youngnick\/contour:dag-status-update/' | kubectl apply -f - `
i was able to run _3 clean runs_ of contour both for k8s 1.14 and 1.16 so I'd say it looks good :)

For reference _MY_ version of the script is [here](https://gist.github.com/primeroz/66a140c52d2a024b4c128672fdeb2e31) ... but is not that very different from the one i uploaded in the description, just have a couple of different options of contour , including one with your patch

**Comment by primeroz** [comment]
feel free to close this issue , i will in case reopen / recreate if i still hit the problem once your code is released on contour 

thanks!

**Comment by youngnick** [comment]
Thanks for verifying @primeroz! Closing this one out.
