### ISSUE TITLE
Redirect: add flag to completely disable the HTTP listener and HTTP->HTTPS redirect

### ISSUE THREAD

**Issue by primeroz** [projectcontour/contour#2577]
**Please describe the problem you have**
I don't use the HTTP listener at all , is not even exposed to the internet but for every HTTPProxy resource i create i also get an entry in the http listener to do the redirect to https.

This makes looking at the Contour DAG and Envoy Configuration painful when many HTPProxies exists for no real benefit.

Would be great to be able to disable the http listener and the redirect entirely

**Comment by youngnick** [comment]
Thanks for this issue @primeroz. Just to confirm, you'd like to be able to totally disable all HTTP serving, full stop. No opening of port 80 (or whatever) at all?

**Comment by primeroz** [comment]
yep that's what i meant. 

For setup like mine where no HTTP is needed and is not even exposed to the internet is just a complication when looking at the config or the Generated DAG svg file.

I only expose HTTPS on my cluster and do , for client facing apps, redirect at the CDN level

**Comment by stevesloka** [comment]
@danehans

**Comment by stevesloka** [comment]
If we did this, we'd need to think about how Contour will handle this internally. Given a flag or config option exists, we'd need to make the Cert required on a vhost since Contour won't be able to serve any traffic without one.

**Comment by youngnick** [comment]
Agreed that if we implement this, then any HTTPProxy that attempts to configure a HTTP virtualhost should be placed into an Error state.
