### ISSUE TITLE
Invalid annotation log messages include a hard-coded resource version 

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2589]
In `(*KubernetesCache) Insert()` we see the following:

```Go
				kc.WithField("name", om.GetName()).
					WithField("namespace", om.GetNamespace()).
					WithField("kind", kind).
					WithField("version", "v1"). <<< 
					WithField("annotation", key).
					Error("ignoring invalid or unsupported annotation")
```

I think that the value of the "version" field should the API group/version.

**Comment by ffahri** [comment]
Hey i want to change this, is it okey to use object.GetResourceVersion() ? @jpeach

**Comment by ffahri** [comment]
I was confused with the resourceVersion sorry, we can get apiVersion with using same as 
k8s.kindOf  -> k8s.apiVersionOf func, and retrieving the version from that function ? 
I thought maybe we can use unstructured type for this but it says 
```
WARNING: This object has accessors for the v1 standard metadata. You *MUST NOT* use this type if you are dealing with objects that are not in the server meta v1 schema.
```
https://godoc.org/github.com/kubernetes/apimachinery/pkg/apis/meta/v1/unstructured

So another option can be a jsonpath of the $object.apiVersion what is your thoughts of this ?

**Comment by jpeach** [comment]
> I was confused with the resourceVersion sorry, we can get apiVersion with using same as
> k8s.kindOf -> k8s.apiVersionOf func, and retrieving the version from that function ?

Yeh we will need something like this, since it's difficult to guarantee that the resource meta is populated in all cases.

> I thought maybe we can use unstructured type for this but it says
> 
> ```
> WARNING: This object has accessors for the v1 standard metadata. You *MUST NOT* use this type if you are dealing with objects that are not in the server meta v1 schema.
> ```

This is fine, because every resource we deal with does use the meta v1 schema.

**Comment by ffahri** [comment]
Hey @jpeach i tried out with different thing and succeeded but 
```
	return obj.(runtime.Object).GetObjectKind().GroupVersionKind().GroupVersion().String()

---
//test case objects
{"test.projectcontour.io/v1", &unstructured.Unstructured{
			Object: map[string]interface{}{
				"apiVersion": "test.projectcontour.io/v1",
				"kind":       "Foo",
			}}
},
{"apps/v1", &v1.Pod{
			TypeMeta: metav1.TypeMeta{
				APIVersion: "apps/v1",
			}}
},

```

however you said 
>since it's difficult to guarantee that the resource meta is populated in all cases.

could you give an example for this and I guess that makes the implementation above deficient.

**Comment by jpeach** [comment]
> > since it's difficult to guarantee that the resource meta is populated in all cases.
> 
> could you give an example for this and I guess that makes the implementation above deficient.
> 
> commit from fork
> [fd234fc](https://github.com/projectcontour/contour/commit/fd234fca3b7477dd775813ed2b81eac3819ec6e9)

The problem is that, depending on which client-go APIs are used to convert from unstructured resources to typed resources, the version fields can be dropped. My concern here is that we add an API that works at the time of writing, but then starts to fail in certain call paths because of changes in the way we use other client-go APIs. That's why I'm suggesting a wrapper that tries to extract the version information generically, then falls back to a type switch. Maybe there's a reliable API somewhere in the Kubernetes project that does this.

https://github.com/kubernetes/kubernetes/issues/80609

**Comment by ffahri** [comment]
Hey sorry for late response, 
I couldn't find any API for this purpose, I implemented the same as KindOf

``` 
func VersionOf(obj interface{}) string {
	switch obj := obj.(type) {
	case *v1.Secret, *v1.Service, *v1.Endpoints:
		return v1.SchemeGroupVersion.String()
	case *v1beta1.Ingress:
		return v1beta1.SchemeGroupVersion.String()
	case *projectcontour.HTTPProxy, *projectcontour.TLSCertificateDelegation:
		return projectcontour.GroupVersion.String()
	case *unstructured.Unstructured:
		return obj.GetAPIVersion()
	default:
		return ""  << Also not sure if we decide to implement this ; should we use v1 or "" 
	}
}
``` 

Here is the output in logs. (added wrong annotation in kuard example ingress)

``` 
time="2020-08-16T12:16:48Z" level=error msg="ignoring invalid or unsupported annotation" annotation=projectcontour.io/wololo context=KubernetesCache kind=Ingress name=kuard namespace=default version=networking.k8s.io/v1beta1
``` 

However I'm not sure is this the good solution since 
- If Contour starts to implement and handle Gateways and other ServiceAPI's etc it needs to be add both VersionOf and KindOf functions. 

What do you think for this @jpeach

**Comment by ffahri** [comment]
edit: I asked in #sig-api-machinery and got an answer for the API
scheme.Scheme.ObjectKinds(obj.(runtime.Object))
is the answer. And that function also good for the KindOf method. Im updating the PR 
https://github.com/projectcontour/contour/pull/2796
