### ISSUE TITLE
expand configuration docs to cover all CLI commands, flags and env vars

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#2615]
Spun out from discussion in #2403.

Ideally, `site/docs/master/configuration.md` would cover all CLI flags, config file fields, and environment variables for all `contour` commands.

**Comment by alexbrand** [comment]
+1

**Comment by jpeach** [comment]
xref #2045 

FWIW cobra supports generating markdown docs https://pkg.go.dev/github.com/spf13/cobra@v1.0.0/doc?tab=doc

**Comment by glerchundi** [comment]
We are using ff (flags) & ffcli (commands) for all of our micro and not so micro services. It is working pretty well for us.

Main pros:
- Simple (small footprint -> smaller binaries)
- Very idiomatic and close to how flags are handled in stdlib

Drawbacks
- No nested structures, bad to make the config file more operator friendly
- No markdown generator

Just puttting my 2 cents in

**Comment by jpeach** [comment]
> We are using ff (flags) & ffcli (commands) for all of our micro and not so micro services. It is working pretty well for us.

Thanks for the pointer. However, I think for CLI tooling, we should just use the most widely used package that works. I don't want to be stranded again :)

**Comment by skriss** [comment]
> FWIW cobra supports generating markdown docs https://pkg.go.dev/github.com/spf13/cobra@v1.0.0/doc?tab=doc

Yep we used to do this for Velero, and I've seen many other projects use it. Also agree that cobra is likely the safe choice for CLI, though I'm not aware of the original reasons for not using it.
