### ISSUE TITLE
Question: Is contour only a proxy?

### ISSUE THREAD

**Issue by StarpTech** [projectcontour/contour#2618]
**What steps did you take and what happened:**

Hi, this is a question, not a bug report. I evaluated many ingress controller for Kubernetes and come to the conclusion that contour has the best combination of smooth configuration and proxy features. I'd like to use it as NGINX replacement but I couldn't find solutions for common problems these days: HTTP GZIP compression, Authentication e.g JWT, Basic-Auth, Rate-Limiting etc.. 

Is it necessary to run contour in parallel with an API gateway? I'm interested in how contour will position itself in that area and what's the current approach in that field. Thanks.

**Comment by youngnick** [comment]
Hi @StarpTech, thanks for the question, and for the kind words about Contour.

I saw that you already commented on #310, as @jpeach said there, we always enable GZIP - we decided it was better to default that to on, and add a way to disable it if anyone needed it (noone has yet).

We are planning to implement both authentication and rate-limiting.
- Authentication is being looked at in #432 (the original request), with a more up to date design and thoughts in #2459.
- Rate limiting is covered by #370 and some older PRs, but is scheduled for another look soon.
A rough outline of Contour's current roadmap is available at https://github.com/projectcontour/community/blob/master/ROADMAP.md.

In terms of an API gateway, Contour has and will have some features of an API gateway (currently, the ability to route different parts of a domain to different services via HTTPProxy inclusion, and things like external auth, rate limiting, tracing, and so on to come), but that's not its main focus.

The main focus of Contour is to provide a Kubernetes Ingress controller using Envoy's featureset. Envoy's featureset includes some API gateway-style things, so Contour does as well. But it's not our main focus.

I'm also working on an update to our [philosophy document](https://projectcontour.io/resources/philosophy/) which currently doesn't do a good job of stating our commitment to exposing more of Envoy's feature set. That should be out soon (hopefully in the next couple of weeks).

Does that answer your question? Please feel free to ask more if you need to.

**Comment by StarpTech** [comment]
Hi @youngnick thank you! This explains a lot and I like the direction. I hope Contour will not be split into a commercial product. Many solutions today are OOS but lack in basic features like JWT parsing or OAuth :smile: Keep up the great work!

**Comment by youngnick** [comment]
Okay @StarpTech, I'll close this, feel free to reopen if you have more.
