### ISSUE TITLE
Add support to disable HTTP2.

### ISSUE THREAD

**Issue by primeroz** [projectcontour/contour#2619]
**Please describe the problem you have**

HTTP2 Coalescing , when using a wildcard, can lead to problems in SNI based routing.\
This was addressed in https://github.com/projectcontour/contour/issues/1493 by responding with the **http 421** code pushing on the client the responsability to re-establish a connection using the correct tls name for sni routing.

_unfortunately_ Safari ( or apparently webkit ... or actually the CFNetwork  ) has a [bug](https://bugs.webkit.org/show_bug.cgi?id=192926) and so it just hangs when it receive a 421 back.\
This have been known for years but no fix exists for it yet.

As discussed with @jpeach the only solution , for people in my situation where we can't stop using wildcard certificates, is to to disable HTTP2 and revert to the always great HTTP 1.1. 

This is currently not possible in Contour though

**Comment by maplain** [comment]
setting `default-http-versions` to only `HTTP/1.1` solves the problem in my case: https://projectcontour.io/docs/main/configuration/#configuration-file

**Comment by youngnick** [comment]
Following up on issues, it seems like @maplain's fix may cover your use case, @primeroz. Is there anything else you would like done on this issue?

**Comment by primeroz** [comment]
It sounds good to me, feel free to close this issue and thanks!
