### ISSUE TITLE
Separate the Contour config file code into a new package

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2621]
**Please describe the problem you have**

The Contour config file definition is embedded in `serveContext`, which contains both public definitions for the config file, internal definitions used by command-line flags, and other internals. It's confusing trying to separate out how the various fields are used and likely to become more so as we expand the use of the config file.

Let's break this struct and create an `internal/config` package to formalize the configuration file and bring all the defaults into one place. This should make it easier to understand the config flow and easier to add new configurations.

**Comment by stevesloka** [comment]
//cc https://github.com/projectcontour/contour/issues/2924#issuecomment-695081070

**Comment by jpeach** [comment]
I'm going to move the config-file code to a new package `pkg/config` that can be consumed internally and by the operator. The top-level API will be:

```
package config

type Parameters struct {
        ...
}

func New() *Parameters { ... }

func Parse(in io.Reader) (*Parameters, error) { ... }
```
