### ISSUE TITLE
Enable strict YAML parsing for the configuration file.

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2623]
**What steps did you take and what happened:**

Added the following to the Contour config file:
```yaml
    default-http-vertsions:
     - "HTTP/1.1"
```

Contour started up and I had to debug why the config didn't seem to work.

**What did you expect to happen:**

Any kind of error.

**Anything else you would like to add:**

xref #2621

**Comment by tthebst** [comment]
@jpeach You can enable strict yaml parsing. This would have prevented the error. Your example would have given this error:

```
contour: error: yaml: unmarshal errors:
  line 60: field default-http-versionss not found in type main.serveContext, try --help
```

I think the error message could be improved because it is not obvious that it is an error with the config map.

**Comment by youngnick** [comment]
Seems like this would be a good, quick way to get some feedback over parsing errors in the YAML. It does run a risk of breaking someone who currently has a broken config file, but that's probably okay.

It also does mean that if we remove fields from `serveContext`, then we'll need a slightly different deprecation and removal flow:
1. Mark the field as deprecated, log a warning.
2. Mark the field as removed, log that the setting will have no effect.
3. Actually remove the field.

There will need to be at least a few releases between each of these steps.

@jpeach, @stevesloka, @skriss, WDYT?
