### ISSUE TITLE
Rendered RBAC rules are missing the contour-leaderelection role

### ISSUE THREAD

**Issue by brenix** [projectcontour/contour#2639]
**What steps did you take and what happened:**

While inspecting the latest deployment examples on `master`, I noticed that the `contour-leaderelection` role appears to have been removed. Though, the rolebinding still references this role. 

**What did you expect to happen:**

The rendered examples should include all roles/rolebindings necessary

**Anything else you would like to add:**

This was discussed in a [slack thread](https://kubernetes.slack.com/archives/C8XRH2R4J/p1593454903152600) and determined to be an issue with the automation around RBAC rules.

Seems to come from https://github.com/projectcontour/contour/pull/2634

**Comment by stevesloka** [comment]
Thanks for reporting @brenix, what looks like happened is the rbac permissions were changed so the `contour-leaderelection` binding is no longer needed. I have a PR to remove the duplication coming next.
