### ISSUE TITLE
internal/contour: EndpointsTranslator should only reflect clusters with routes/tcpproxies

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2680]
Currently, the `EndpointsTranslator` manages updates to Kubernetes endpoints in its own handler. This was due to the high volume of updates that typically comes from endpoint changes. 

However, in the work I'm doing for #2604, to implement ADS with `go-control-plane`, there's a consistency check which rejects updates if the CDS clusters do not match the EDS clusters. Given currently, any endpoint creates a `ClusterLoadAssignment` in EDS regardless if it's referenced in a route or tcpproxy, any EDS change us rejected. 

We should match how other types are implemented in Contour (e.g. Secrets, Clusters) where they are only created in Envoy if they are referenced from an ingress resource somehow.

**Comment by jpeach** [comment]
Note that this bears on authorization, rate limiting and logging, since those features will also reference clusters.

Is the check in envoy or in go-control-plane? Do you think that the check itself makes sense?

**Comment by stevesloka** [comment]
> Is the check in envoy or in go-control-plane? 

Yes, when enabling `ADS` there's a check to make sure that all objects in EDS match something in CDS, etc. It's actually a count right now, but we could help improve that futher as a seperate issue upstream. 

> Do you think that the check itself makes sense?

It's a good validation against passing config that should work to Envoy. 

Also, it doesn't make sense to store & keep track all ALL the endpoints in a cluster. There could be thousands of endpoints which aren't related to anything ingress and we'll still be managing them in Contour and passing updates to Envoy.

**Comment by skriss** [comment]
@stevesloka @jpeach has this been fixed by #2805?

**Comment by stevesloka** [comment]
Yup I think this is done now thanks to the changes from @jpeach. =)
