### ISSUE TITLE
tcpproxy: services should be optional to support clean delegation

### ISSUE THREAD

**Issue by glerchundi** [projectcontour/contour#2681]
We tried to upgrade from 1.1 to 1.6 following the upgrading tips on the webpage
with no success. We already know where the problem is but I wanted to double
check if it's something done on purpose or if it's a bug.

One of our `HTTPProxy` definitions, which was working before the upgrade, is
erroring out with the following message:

```
The HTTPProxy "tunnel" is invalid: spec.tcpproxy.services: Required value
```

The problem seems to be introduced in 1076f5a156bbb0a9e804f63296b94faa147bbe7f
(👋 @davecheney as he was the one who made the change) where `services` was made
a required property with a minimum items of 1, even if the idea of that
definition was to be delegated into another namespace.

IMHO, this is somehow inconsistent with how you designed the `routes` because
they can colive with `includes` as both are optional. As the `include` for the
`tcpproxy` belongs to the entity, the `services` should be made optional and add
a validity check programatically to allow one (`services`) or the other
(`include`) (in case there isn't a conditional solution with `kubebuilder`
tags).

WDYT?

**Environment:**

- Contour version: Upgrading 1.1 -> 1.6
- Kubernetes version: (use `kubectl version`): 1.15
- Cloud provider or hardware configuration: GKE

**Comment by skriss** [comment]
@glerchundi this does seem like a bug to me - @stevesloka would you agree?

**Comment by stevesloka** [comment]
Yup, I agree. You should be able to define an include without a service. But you shouldn't be able to define a proxy without at least one service.

**Comment by skriss** [comment]
It does look like we have runtime code to check that exactly one of `Services` or `Include` is specified -- see https://github.com/projectcontour/contour/blob/master/internal/dag/builder.go#L983-L986 and https://github.com/projectcontour/contour/blob/master/internal/dag/builder.go#L1008-L1012. So I think we probably just want to remove the kubebuilder validation.

@glerchundi are you interested in contributing a fix here?

**Comment by glerchundi** [comment]
Sure, happy to send a PR.

**Comment by glerchundi** [comment]
Do you think this is worth backporting to the 1.6 branch? Being a bug
probably means it is but wanted to check with you first.

I’m happy to send another PR to replicate this one into the stable version.
