### ISSUE TITLE
Onboard Contour to get CII badge

### ISSUE THREAD

**Issue by michmike** [projectcontour/contour#2688]
Onboard Contour to https://bestpractices.coreinfrastructure.org/

Achieve at least passing rate

Add the badge to our main github repo

**Comment by jpeach** [comment]
I tried this, and the CII Github login doesn't let me select contour as a repository. Maybe someone else will have better luck.

**Comment by youngnick** [comment]
I think the projectcontour organisation needs to have the CII integration enabled. Maybe @jonasrosland or @skriss can tell us more.

**Comment by youngnick** [comment]
I've assigned Jonas and Steve to this one as the people who know the most about this. Please reassign yourselves if you need someone else to pick it up.

**Comment by skriss** [comment]
https://bestpractices.coreinfrastructure.org/en/projects/4141
