### ISSUE TITLE
"Making cert-manager work with HTTPProxy" docs talk about unknown ingress-shim

### ISSUE THREAD

**Issue by alexbrand** [projectcontour/contour#2692]
The Making cert-manager work with HTTPProxy section of the [cert-manager guide](https://projectcontour.io/guides/cert-manager) mentions an `ingress-shim` but it is not clear what `ingress-shim` is. 

> The dummy Ingress record exists only to hold the annotations ingress-shim requires. Because it does not include the ingress-class: contour annotation, Contour will not see it and so the configuration of the Ingress does not matter, except that it is valid enough for ingress-shim to use.

**Comment by alexbrand** [comment]
I wonder if it is referencing the Ingress resource that needs to be created to make cert-manager work with HTTPProxy. If that is the case, I can open a PR to update the name of that ingress resource from `httpbinproxy` to `ingress-shim`.

**Comment by skriss** [comment]
I found [these cert-manager docs](https://cert-manager.io/docs/usage/ingress/) that cover `ingress-shim` (subcomponent of cert-manager). It'd be great to clarify our docs to include a link or otherwise explain this better.

**Comment by stevesloka** [comment]
I always thought the `Certificate` object was a cleaner approach when not using Ingress objects: https://github.com/projectcontour/contour/issues/2018

**Comment by youngnick** [comment]
The `Certificate` object is absolutely a cleaner approach, but will require quite a bit of product work to figure out the best way to emit it, to control when we emit it, to determine how we check the state and surface that back to the HTTPProxy, and so on.

**Comment by youngnick** [comment]
Also, yes, I think that the `ingress-shim` parts either need to explain that `ingress-shim` is part of cert-manager, or we just shouldn't mention it, and just call the ingress doc a dummy one and say it's "to kick off the cert-manager certificate creation flow".
