### ISSUE TITLE
Envoy per route health checking not working as expected

### ISSUE THREAD

**Issue by Zsolt-LazarZsolt** [projectcontour/contour#2693]
**What steps did you take and what happened:**
I used contour 1.4
Installed a simple one pod backend which beside answering, logs all access.

Set up an httpproxy object with health check policy:
    healthCheckPolicy:
      path: /health
      intervalSeconds: 10
      timeoutSeconds: 2
      unhealthyThresholdCount: 3
      healthyThresholdCount: 5

I was surprised to see, that instead of the set 10s intervals the envoy pods only checked the backend at the time the httpproxy is applied and then in every 60 seconds.
Until I did a wget to reach the service:
Then the envoy pod which handled the one request started actually checking in every 10 seconds.

I could not find any documentation nor in envoy or contour that explains this "laziness". May be connected to opened connections?
 

**What did you expect to happen:**
Setting up the intervalSeconds I was expecting requests from the envoy pods exactly at that interval from the start.

**Environment:**

- Contour version: 1.4
- Kubernetes version: (use `kubectl version`): v1.18.2
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): CentOS Linux release 7.5.1804 (Core)

**Comment by Zsolt-LazarZsolt** [comment]
I got an answer on the envoy forums, there is a parameter in envoy no_traffic_interval which actually defaults to 60 sec.
I have to check but it seems not to be settable in the httpproxy object yet.

**Comment by skriss** [comment]
ref. https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/health_check.proto
@Zsolt-LazarZsolt you are correct, there is not currently a way to tune this setting via Contour/HTTPProxy.

**Comment by youngnick** [comment]
I guess Envoy has made the assumption that if there's no traffic going to a service, you can probably check if it's up less frequently. In a large-scale deployment, I can see this being very important and saving a lot of bandwidth.

This seems like Envoy's desired behavior, @Zsolt-LazarZsolt, would you like anything further done on this issue?

**Comment by Zsolt-LazarZsolt** [comment]
Hi @youngnick 

I think the provided answer is satisfactory, thank you for your time :)
