### ISSUE TITLE
Document valid options for HTTPProxy spec.routes.services[].protocol

### ISSUE THREAD

**Issue by alexbrand** [projectcontour/contour#2703]
**Please describe the problem you have**
Document valid options for HTTPProxy `spec.routes.services[].protocol`

**Comment by skriss** [comment]
@alexbrand these are documented in the [API reference](https://projectcontour.io/docs/v1.6.1/api/#projectcontour.io/v1.Service); are you looking for it to be documented on https://projectcontour.io/docs/v1.6.1/httpproxy/ as well?

**Comment by alexbrand** [comment]
Aaaaah there we go! I was having the hardest time finding the API reference for some reason. I kinda assumed that the HTTPProxy reference was the API reference for the HTTPProxy resource. This is my bad.

**Comment by jpeach** [comment]
> Aaaaah there we go! I was having the hardest time finding the API reference for some reason. I kinda assumed that the HTTPProxy reference was the API reference for the HTTPProxy resource. This is my bad.

Those docs need to be broken down into more digestible chunks https://github.com/projectcontour/contour/issues/2070

**Comment by skriss** [comment]
Sounds like we can close this out and tackle some docs reorg in the linked issue; feel free to reopen this if you disagree.
