### ISSUE TITLE
cmd/shutdown-manager: Use new drain_listeners command

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2705]
The shutdown-manager still begin the listener drain sequence by setting Envoy to fail it's health checks. This should change to use the new `drain_listeners?graceful` command from the Admin UI (https://www.envoyproxy.io/docs/envoy/v1.15.0/operations/admin#post--drain_listeners?graceful)

**Comment by jpeach** [comment]
What's the semantic difference between this and what the shutdown manager is currently doing?

**Comment by skriss** [comment]
Dupe of #4852, closing.
