### ISSUE TITLE
improve validation around user-specified timeout values

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#2728]
Currently, if an unparseable timeout value is specified in either the config file or in a `TimeoutPolicy` field in an `HTTPProxy` route, the parse error is swallowed and the timeout is disabled/set to infinity.

There are a few things we can do to improve this:
- for the HTTPProxy fields, add kubebuilder validations (e.g. `+kubebuilder:validation:Pattern`)
- for HTTPProxy, if there's an unparseable timeout value, set a validation error or warning in the proxy's status/conditions.
- for the config file, if there's an unparseable timeout value, return the error so either `contour serve` can exit, or we can log a warning/error.

Also, consider what to do with unparseable timeout annotations on `Ingress` resources.

ref. #2697

**Comment by stevesloka** [comment]
// cc auth impl: https://github.com/projectcontour/contour/pull/2886#discussion_r486606226
