### ISSUE TITLE
Curl request hangs when SNI is omitted (httpproxy fallback certificate mode)

### ISSUE THREAD

**Issue by moondev** [projectcontour/contour#2733]
@jpeach and I have been actively investigating this. We succeeded in reliably recreating it and James has already developed a fix. This issue is for tracking purposes so we can document when the fix is merged. Thanks James!

**What steps did you take and what happened:**

This is similar, but separate from the previously filed https://github.com/projectcontour/contour/issues/2720

While the correct fallback certificate is presented, the request seems to hang and never succeeds. 

**What did you expect to happen:**
Request to succeed when SNI is omitted. `curl` examples below
```
# succeeds (SNI included) 
curl -v -k https://fallback.instakube.io:8843/healthy

# hangs and eventually times out after presenting fallback cert (SNI omitted)
curl -v -k -H "Host:fallback.instakube.io" https://127.0.0.1:8843/healthy
```

Contour version: master
Kubernetes version: v1.18.6
Kubernetes installer & version: `kind` via https://github.com/projectcontour/contour/blob/master/_integration/testsuite/make-kind-cluster.sh

**Comment by jpeach** [comment]
I have the fix, and will post a PR later today. Just looking at how to write an integration test for this case.

**Comment by jpeach** [comment]
> I have the fix, and will post a PR later today. Just looking at how to write an integration test for this case.

Integration test will need to wait for a separate PR; it still needs some manual steps ATM.
