### ISSUE TITLE
Using more inclusive language in Contour

### ISSUE THREAD

**Issue by michmike** [projectcontour/contour#2744]
we need to be using inclusive language throughout contour

action items
1. replace master -> main
2. run vale tool to identify insensitive language in docs/code

Reference - https://docs.google.com/document/d/1bnPvb6oE07Wg9rb7kBXcpHe6j85bbyltdc0h0_gil88/edit

**Comment by michmike** [comment]
cc: @stevesloka  and @jonasrosland 
Steve mentioned he would pick this up for 1.8

**Comment by youngnick** [comment]
I spent some time looking into renaming master to main a while ago, here's my notes:

# Renaming master to main

Pre-work:

Close out all PRs - they will be auto-closed anyway when the branch is renamed.

Prepare a PR with `s/master/main/g` applied, obviously don't submit it yet.

Then, rename the branch:

```
# rename your local branch
git branch -m master main
# Push the new main branch upstream
git push --set-upstream origin main

```

Then, go to the Github UI and change the `main` branch to be the default one.

I don't know what will happen with open PRs at this point, they will probably stay pointing to `master`.

Then, delete the `master` branch:
```
git push origin :master
```
(This says "push nothing into master, deleting it")

This will close any outstanding PRs against `master`.


That said, it seems that Github is building tooling to help with the rename, I'd suggest waiting for it: https://github.com/github/renaming

**Comment by jpeach** [comment]
The branch change should socialized at the community meeting and on slack.

**Comment by youngnick** [comment]
Agreed. I propose we say "we will almost certainly do this later (when Github has tooling for it), unless someone can raise an extremely good reason."

**Comment by stevesloka** [comment]
Just a note as well to not forget, we'll need to update the docker image tag that gets pushed on each PR.

**Comment by stevesloka** [comment]
@jonasrosland & I worked through the `vale` bits this morning and all is up to date in our docs. The only hits we had were contained in links so the initial pass is good.

**Comment by youngnick** [comment]
Okay, after some discussion with @jonasrosland, I think we should move ahead by creating a *new* `main` branch, setting the it as the mainline branch, leaving master open. This will leave current PRs open, we should not merge any new PRs until we get the other ones either closed or retargeted to `main`.

I'll run through a test of this flow in a test repo, and report back with a proper plan.

**Comment by youngnick** [comment]
Okay, I've run through some tests, this looks pretty straightforward from a purely Git sense.

1. We prepare a PR to `s/master/main/`. This will probably be a bit tricky, there's a lot of site stuff to fix up.
1. Firstly, we close out all the PRs - they can be reopened against `main` afterwards.
2. We branch a new `main` and push it back to Github.
3. We change the default branch for new PRs.
4. We open, review. and merge the `s/master/main/g` PR against `main`.
5. We leave `master` around for a week or two to confirm we haven't missed anything.
6. We delete `master`.
5. This work is finished, we virtually high five.

**Comment by youngnick** [comment]
I'll get started on an `s/master/main` PR.

**Comment by youngnick** [comment]
I've created a new `main` branch, created a rename PR (#2798), and updated Slack with details.

**Comment by youngnick** [comment]
Howto for contributors:

1. Create a `main` branch in your fork locally and push it. I use `origin` for my fork, and `upstream` for the main `projectcontour/contour` repo, so I did the following:
```
git checkout -b main
git push --set-upstream origin main
```
2. Update your workflow to rebase anything you need to from `main` instead of `master` from `upstream`.

**Comment by youngnick** [comment]
Once #2798 is merged, we need to verify:

- [ ] Docker images are pushed to Docker hub with `main`
- [ ] Release tooling works (probably will need to wait for 1.8.0 release).

**Comment by youngnick** [comment]
With the release tooling confirmed working, I'll close out this issue.

For anyone watching, if you see any other non-inclusive language used in Contour, please feel free to do any of the following, whichever you are comfortable with:
- raise an issue here in Contour
- tell us in the #contour channel on k8s slack
- ping me privately on k8s slack (I'm `@youngnick` there.)
