### ISSUE TITLE
Deprecate and then drop support for contour.heptio.com/ annotation prefix

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#2749]
We should eventually drop support for annotations prefixed with `contour.heptio.com/` since they've been replaced with `projectcontour.io/` for quite awhile. This could be a 2.0 thing, or we could put out a deprecation notice and then drop support a few releases later.

**Comment by youngnick** [comment]
We should issue a deprecation notice, then drop support, agreed. Let's do this for 1.8, I've updated the title accordingly.

**Comment by youngnick** [comment]
I'm marking this for removal in 1.10.
