### ISSUE TITLE
Adopt HTTP ConnectionManager `strip_matching_host_port`

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2752]
**Please describe the problem you have**

Currently, we duplicate virtual host entries to allow them to match when a port is specified in the Host header. We can drop this and use `strip_matching_host_port` instead.

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto

**Comment by jpeach** [comment]
Blocked on #1898

**Comment by sunjayBhatia** [comment]
closing, we're already using the `strip_any_host_port` option
