### ISSUE TITLE
Ability to set keepalive timings on downstream connection

### ISSUE THREAD

**Issue by imranismail** [projectcontour/contour#2788]
**Please describe the problem you have**

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html#connection-idle-timeout

> Elastic Load Balancing sets the idle timeout value for TCP flows to 350 seconds. You cannot modify this value. Clients or targets can use TCP keepalive packets to reset the idle timeout.

This can be set through the socket_options in listener config.

https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/listener.proto
envoyproxy/envoy#10301
envoyproxy/envoy#3634

**Comment by youngnick** [comment]
Thanks for logging this issue @imranismail. We already set the keepalive for connections to the Envoy listeners (merged in #2638).

The settings there (idle time of 45 seconds, with 5 sec between keepalives) should work just fine with the ELB settings you list above, from what I can see. Please see `internal/envoy/tcp_keepalive.go` for all the gory detail.

Please feel free to respond if I've missed something here.

**Comment by imranismail** [comment]
I'll close this, but it'd be great if this settings is configurable
