### ISSUE TITLE
Provide debug variants of contour container images

### ISSUE THREAD

**Issue by mkilchhofer** [projectcontour/contour#2789]
**Please describe the problem you have**
As already mentioned (https://github.com/projectcontour/contour/issues/2050#issuecomment-672570646) it would be nice, if you build debug variants of your container images containing debug tools like busybox or another minimal linux distro. This would help people troubleshoot (eg. look at the configs in the empty dir, curl the envoy healthcheck API, etc.)

For inspiration, look at the guys behind fluent-bit:
* Normal image: https://github.com/fluent/fluent-bit/blob/master/Dockerfile
* Debug image: https://github.com/fluent/fluent-bit/blob/master/Dockerfile.debug 

**Update:**
We only need to talk about the contour container images. Envoy images seems to be ubuntu based.

**Comment by jpeach** [comment]
Would [ephemeral debug containers](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-container) address similar use cases?

**Comment by youngnick** [comment]
I think they will, but these will help for those people who don't have an up-to-date cluster, or don't want to use an alpha feature yet.

**Comment by mkilchhofer** [comment]
> I think they will, but these will help for those people who don't have an up-to-date cluster, or don't want to use an alpha feature yet.

Yes, exactly. There is a sentence on this page which says:
> Note: The examples in this section require the EphemeralContainers feature gate enabled in your cluster and kubectl version v1.18 or later.

We can't expect that everyone has up-to-date clusters with alpha features enabled :)

**Comment by mkilchhofer** [comment]
Closing my issue as ephemeral debug container are GA since K8s 1.25.
