### ISSUE TITLE
[site][guides/cert-manager] Incorrect secret name value for `httpbinproxy` resources

### ISSUE THREAD

**Issue by rajat404** [projectcontour/contour#2800]
**What steps did you take and what happened:**
I followed all the steps in [Deploying HTTPS services with Contour and cert-manager](https://projectcontour.io/guides/cert-manager/) as is. While the steps for getting certs for the `httpbin` sub-domain worked as expected, but the steps for the `httpbinproxy` sub-domain didn't get the cert.

**What did you expect to happen:**
Get a TLS cert for my sub-domain related to `httpbinproxy`

**Anything else you would like to add:**
In the steps for `httpbinproxy` with HTTPProxy resource, the secret name is still specified as `httpbin` and not `httpbinproxy`. When I changed the secret name in both `HTTPProxy` & `Ingress` resource manifests, it worked as expected.

Another thing I noticed - The namespace for the dummy Ingress object is set to `default`. It's the only resource in the guide for which the default namespace is specified. While debugging the cert issue, I also changed it. 

I wanted to confirm that this is the right reason, and I'm not doing something wrong. If so, I'd be happy to raise a PR for fixing it. Please let me know if any more information is needed. Thanks 🙂

**Domains where I made it work (still live, so can be checked):**

- https://httpbinproxy.rajat404.com/
- https://httpbin.rajat404.com/

**Environment:**

- Contour version: v1.7.0
- Kubernetes version: (use `kubectl version`): v1.18.6
- Kubernetes installer & version: (not sure what's meant by installer 😓)
- Cloud provider or hardware configuration: DigitalOcean 
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 10 (buster)
- Kernel Version: 4.19.0-0.bpo.6-amd64

**Comment by youngnick** [comment]
Thanks for this issue @rajat404! Totally fine for you to send a docs PR, @jpeach or I will help shepherd it for you.
