### ISSUE TITLE
Replace check with Fatal logs

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2811]
**Please describe the problem you have**

There are quite a few places in Contour that call a local `check` helper that prints to standard error and exits. This approach loses error context and makes it difficult for aggregated log collectors to recognize that this is a fatal error message. We should replace these with fatal level logs.

**Comment by ShaileshSurya** [comment]
@jpeach @youngnick  This issue can not be closed as there is one more PR open to be merged. https://github.com/projectcontour/contour/pull/2827

**Comment by ShaileshSurya** [comment]
Hey, @youngnick @jpeach it was really great working with you guys. I would like to contribute more to this project. Please feel free to mention me in any issue you think I can contribute.

**Comment by youngnick** [comment]
Thanks for all your help @ShaileshSurya! Please feel free to pick up any [`help-wanted`](https://github.com/projectcontour/contour/labels/help%20wanted) or [`good-first-issue`](https://github.com/projectcontour/contour/labels/good%20first%20issue) issues, they're ready for contributions any time you are.

If you do decide to pick something up, please just assign it to yourself, and get started. Feel free to ask any questions you need as well.
