### ISSUE TITLE
DAG Service and Cluster types duplicate the Protocol field

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2833]
In the `dag` package, both the `Cluster` and `Service` types have a "Protocol" field. Unit tests seem to indicate that the duplicate field isn't set consistently (see "insert httpproxy with h2 expecting upstream verification" in `builder_test.go`.

```Go
type Service struct {
	// Protocol is the layer 7 protocol of this service
	// One of "", "h2", "h2c", or "tls".
	Protocol string
...
}

type Cluster struct {
	Upstream *Service

	// The protocol to use to speak to this cluster.
	Protocol string

...}

```

**Comment by youngnick** [comment]
I think the `Service` protocol field can be set either from annotations on the Kubernetes Service, or via a HTTPProxy field under its `Service`, so it may not be set consistently?
