### ISSUE TITLE
release examples: Make certgen job use tagged image

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2834]
The cert-gen job has always used an image tag of `:latest` to get around the issue of applying the same manifest on top of an existing installation, however, tagged releases use a unique name for each certgen job for that release so there's no need to use latest for releases and can cause issues for users in air-gapped environments.  

We should remove the `:latest` tag and use a specific version. 

ref: https://github.com/projectcontour/contour/blob/v1.7.0/examples/render/contour.yaml#L1466

**Comment by youngnick** [comment]
Agreed, for the release examples only.

**Comment by tong101** [comment]
So we will leave it to `:latest` in `main` and pin to specific version whenever we tag a release? Looks like this can updated together with other examples pointing to `latest` under `examples/contour` when we tag a release.

**Comment by stevesloka** [comment]
> So we will leave it to :latest in main and pin to specific version whenever we tag a release? 

I think we might change this to be `:main` for the `main` branch matching all the other images and when a release is tagged then it gets the specific version related to that release.

**Comment by youngnick** [comment]
Yes, I think the todo here is:
- change certgen to `:main` for the main branch
- update release tooling such that the certgen Job image is updated to the release version, the same as we do for other Contour container images.
