### ISSUE TITLE
Support for IP filtering (access lists) for HTTPProxy TCP Proxying

### ISSUE THREAD

**Issue by manast** [projectcontour/contour#2855]
Currently HTTPProxy support TCP proxying which is great for having a cluster with several instances of databases, such as Redis, that can be instantiated dynamically and let envoy handling the routing.

These databases can then be accessed by other clusters or services, but by default these databases become publicly accessible, so it is important to limit the access to only a set of IPs or IP ranges of the clients that are intended to use them.

I am not aware of any workaround that can be built with current version of contour or on top of it, so providing some kind of support for this use case would be greatly appreciated.

**Comment by jpeach** [comment]
It's possible that Kubernetes [network policy](https://kubernetes.io/docs/concepts/services-networking/network-policies/). You would deploy a Contour with a custom ingress class (e.g. "internal") that forwards to the Redis instances. Then network policy could be used to control access to the Envoy pods that the "internal" Contour is programming.

**Comment by manast** [comment]
To clarify why network policies may not work in this case: every database may have a different set of access list, so a global filtering will not do it.

**Comment by stevesloka** [comment]
@manast are the differing access lists determined by which client is accessing? 

Sounds like you might need an "allow" or "deny" list work to determine access, but the trickier part is implementing that per client (if I understand your problem).

**Comment by jpeach** [comment]
The external auth network filter could probably help for this use case.

**Comment by youngnick** [comment]
I should also note that we support TCP proxying, but it's kind of intended to be for tunneling HTTPS sessions through to a backend service that wants to handle its own TLS, not really for any TCP protocol. Great that it works, but I can't say confidently that you may not encounter weird issues.

That said, even in the "forwarding HTTPS" case, I can see that IP filtering is probably a useful feature. I think we'd need to carefully consider where we put it, and how its configured though.

**Comment by manast** [comment]
@stefanprodan not per client but per database. For example, in digital ocean when you request a redis instance you can also choose an access list of IPs that are allowed to access it.

**Comment by manast** [comment]
@youngnick for me it is working great, and the only alternative I could find for kubernetes that worked out of the box. As @jpeach mentioned before, a first step maybe is just to expose the auth network filter and then let the implementation of the access list to the user, but of course the most user friendly would be to support ip lists and ranges. Please let me know if there is something I can do to increase the changes or improve the time for implementing such a feature.

**Comment by manast** [comment]
Basically I think that what we need is this functionality available in istio, I am assuming they support TCP too:
https://istio.io/latest/docs/tasks/security/authorization/authz-ingress/

**Comment by levimm** [comment]
for my case, upstream proxy protocol is used so network policy doesn't work in this case. IP whitelisting feature utilize "envoy.filters.network.rbac" would be very useful.
