### ISSUE TITLE
Provide support for integrating with external auth for TCP connections

### ISSUE THREAD

**Issue by manast** [projectcontour/contour#2888]
Since external authorization is WIP for HTTP https://github.com/projectcontour/contour/issues/432 And since Envoy also supports network auth https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/ext_authz_filter#config-network-filters-ext-authz, we would also like to have support for TCP connections. This will make possible to expose TCP services such as databases outside of the cluster while providing any kind of authentication including access lists for IPs, which is considered a standard security mechanism for public facing databases. This feature request would also make https://github.com/projectcontour/contour/issues/2855 unnecessary since it can be built in user space instead and keep contour simpler.

**Comment by manast** [comment]
To clarify in case this was not clear enough: the feature I am requesting would be on the HTTPProxy CRD, so that we can have different auth functions for every service, not just a global auth.

**Comment by jpeach** [comment]
Doing this per-HTTPProxy resource is different than adding support for the network-level auth filter. Maybe one approach is to figure out some builtins that can add client connection information to the metadata map that the auth service gets. Might need some new Envoy support for that, not too sure.

**Comment by manast** [comment]
ok, in my particular case, if the auth filter also has information such as the hostname then it solves my requirements, so I am more than happy with such an implementation :).
