### ISSUE TITLE
Shutdown manager "error checking for file" log messages shouldn't be at ERROR level

### ISSUE THREAD

**Issue by bgagnon** [projectcontour/contour#2896]
After upgrading to Contour 0.8.1, I was surprised to find these entries in the `shutdown-manager` container logs:

```
envoy-m2trt shutdown-manager time="2020-09-10T02:11:58Z" level=error msg="error checking for file: stat /ok: no such file or directory" context=shutdownReadyHandler
envoy-m2trt shutdown-manager time="2020-09-10T02:11:59Z" level=error msg="error checking for file: stat /ok: no such file or directory" context=shutdownReadyHandler
envoy-m2trt shutdown-manager time="2020-09-10T02:12:00Z" level=error msg="error checking for file: stat /ok: no such file or directory" context=shutdownReadyHandler
envoy-m2trt shutdown-manager time="2020-09-10T02:12:01Z" level=error msg="error checking for file: stat /ok: no such file or directory" context=shutdownReadyHandler
```

My initial thought was that something was not configured correctly. But further investigation leads me to believe this is the normal behavior for the shutdown manager.

It polls a file continuously until it exists. Since it expects **not** to find it, I would argue errors from `os.Stat()` that relate to the file not existing are not to be logged at `level=error`, but rather `level=info`.

A minor detail for sure, but since we cannot see the pre stop hook logs from the Envoy side, it's best if normal things are reported as normal events from the `shutdown-manager` side.

Also, a final logging message with a confirmation that the file now exists would be nice.

**Comment by skriss** [comment]
I'd add that we should differentiate between `os.IsNotExist(err)` (expected errors), and all other errors. The former should be logged at `info`, and the latter should be logged at `error`.

@bgagnon were you planning to work on this? If not, I can pick it up.

**Comment by bgagnon** [comment]
@skriss I can work on this, yes.

BTW, I think commit 2fb8de3e from @jpeach introduced a regression in the error checking condition in this very handler function.

**Comment by skriss** [comment]
Yep, I noticed the same, need to fix that as well :) thanks!
