### ISSUE TITLE
Sometimes the ingress status address is not updated

### ISSUE THREAD

**Issue by laurovenancio** [projectcontour/contour#2904]
**What steps did you take and what happened:**
I created a new ingress and the Ingress Status address was not updated.
There is an error message in the contour log:

time="2020-09-11T20:40:57Z" level=error msg="unable to retrieve object for updating" context=StatusUpdateWriter error="ingresses.networking.k8s.io \"redacted\" not found" name=redacted namespace=redacted resource="networking.k8s.io/v1beta1, Resource=ingresses"

**What did you expect to happen:**
The status address should have been updated.

**Anything else you would like to add:**
This might be related to PR #2864  

**Environment:**

- Contour version: 1.8.1
- Kubernetes version: (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by youngnick** [comment]
Hmm, very interesting, thanks @laurovenancio.

So, can I confirm that your steps were just creating the Ingress, and the status was then never updated?

The code for this is supposed to pull the object from the Lister cache, which _should_ have the object, since there's been an update generated for it.

@mattmoor, any thoughts from you? From what I understand about the Lister cache, if there's been an event fired for the object, it should be present in the Lister cache?

I'll see if I can replicate with my 1.8.1 install as well.

**Comment by mattmoor** [comment]
Yeah, `OnAdd` is called when it enters the cache and `OnUpdate` is called when it changes.

A nice property of this is that the Lister cache is always as up to date as the events that triggered reconciliation.  It can still be behind the actual state of the world, but if it is acting on stale information, then we can be assured that when our cache is made current new events will be fired and reconciliation will happen again.

**Comment by laurovenancio** [comment]
> So, can I confirm that your steps were just creating the Ingress, and the status was then never updated?

Yes. I don't know how frequent is this issue. I updated Contour to 1.8.1 last Friday morning. During the day, three new ingresses were created. Everything worked fine with the first two, but we had this problem with the last one.

To recover from the problem, I had to restart the contour leader pod.

I am not sure if this is relevant, but, when the issue occurred, there was no connection on the leader contour pod from Envoy pods. All Envoy pods were connected to the contour pod that was not the leader.

**Comment by laurovenancio** [comment]
@youngnick I have a theory: I notice that the StatusUpdateHandler and the loadBalancerStatusWriter use different instances of the InformerFactory. These instances may not be in sync all the time.

The InformerFactory for the StatusUpdateHandler is created at https://github.com/projectcontour/contour/blob/main/cmd/contour/serve.go#L146
The InformerFactory for the loadBalancerStatusWriter is created at https://github.com/projectcontour/contour/blob/main/cmd/contour/ingressstatus.go#L100

**Comment by mattmoor** [comment]
That could be a problem, good find.

You want the same (shared) informer factory stamping out (shared) informers.

**Comment by youngnick** [comment]
Ah, great. That does suggest a fix, I'll have a look and see how we can wire the same one to both places.

**Comment by jpeach** [comment]
I started working on this, there are more informer factories than you might expect (especially around updating load balancer status). I'm trying to bring everything back to the controller-runtime informer cache since that will make progress towards #2683 (though not completely solve it).
