### ISSUE TITLE
Guidance on optimal --concurrency level for Envoy in large core environments

### ISSUE THREAD

**Issue by moderation** [projectcontour/contour#2929]
Today the `--concurrency` [CLI flag](https://www.envoyproxy.io/docs/envoy/latest/operations/cli.html?highlight=concurrency#cmdoption-concurrency) is not set in the [example configs](https://github.com/projectcontour/contour/blob/main/examples/contour/03-envoy.yaml#L48-L53).

> If not specified defaults to the number of hardware threads on the machine. 

This means that when running Contour in a Kubernetes cluster that has beefy VMs, Envoy sees the 32 CPUs as 64 cores.

In a relatively early days on Envoy blog, Matt Klein covered the tuning of the `--concurrency` flag - https://blog.envoyproxy.io/envoy-threading-model-a8d44b922310

> One major takeaway however is that from a memory and connection pool efficiency standpoint, it is actually quite important to tune the--concurrency option. Having more workers than is needed will waste memory, create more idle connections, and lead to a lower connection pool hit rate. At Lyft our sidecar Envoys run with very low concurrency so that the performance roughly matches the services they are sitting next to. We only run our edge Envoys at max concurrency.

I suspect that on these large core count VMs / nodes Contour's Envoy is running at too high a concurrency level. Whilst Contour's Envoy is an "edge" it isn't internet facing and serves internal traffic to the organization. Anecdotally we have noticed greater tail latency variation when we moved from NGINX to Contour.

There is little mention of this setting in Contour's issues but https://github.com/projectcontour/contour/issues/2662 mentions being able to remove segfaults by using a lower concurrency setting. I have seen reports in the Envoy Github issues about people needing to tune down their `--concurrency` settings to restore round robin load balancing - https://www.envoyproxy.io/docs/envoy/latest/faq/load_balancing/concurrency_lb.html?highlight=concurrency

It was interesting to see Riot Games need to make a similar adjustment as they tried to tune their servers for high performance / low latency. Their machines are 36 CPU / 72 cores - https://technology.riotgames.com/news/valorants-128-tick-servers
> Erlang has a configurable for how many threads its scheduler is allowed to spawn. The default is one thread per core on the system, hence the 72 processes. Once we set this to a more reasonable default like 4, the problem disappeared overnight. The lesson here is that it’s vitally important to measure performance in a configuration that matches your production environment!

Is it possible to get some guidance on what `--concurrency` should be set on large core machines. This is relevant for people running in cloud environments with 48, 72, 96 vCPU's available and also those running on premise with large core count nodes and VMs.

**Comment by youngnick** [comment]
At the moment, I don't think we (the maintainers) can give much better advice than "you probably want to turn down concurrency on big machines". I would also love to hear some operational experience about this, however.

**Comment by jpeach** [comment]
In the quote above, Matt is talking about a sidecar proxy. It's unlikely that a single sidecar will need to do enough traffic to used all the cores on a machine to it makes sense to tune the concurrency down. OTOH an ingress proxy is serving the entire cluster, so it may well make sense to consume the entire machine if there's enough traffic. If you are deploying as a Daemonset though, you clearly don't want to consume all the CPUs of all the hosts in the cluster.
