### ISSUE TITLE
Supporting gollvm (llvm-goc) builds, for Contour 

### ISSUE THREAD

**Issue by advancedwebdeveloper** [projectcontour/contour#2932]
Wanted to open an issue, to cross-reference bugs, during the build process.

I am dealing with https://go.googlesource.com/gollvm/, these days - and Contour appear to be compiling well, compared to k8s/Docker. Other Kubernetes related CNCF projects have various bugs, related to reflection - mainly cause of [reflect2](https://github.com/modern-go/reflect2) package/dependency.

Ivan

**Comment by youngnick** [comment]
Thanks @advancedwebdeveloper! Is there any action you need from Contour at the moment? I'll add the `blocked` label for now until you have a chance to respond.

**Comment by advancedwebdeveloper** [comment]
@youngnick , as for what I was able to clarify https://github.com/json-iterator/go/issues/501 - there are two separate pipelines:

1. To build all Go packages, using https://golang.org/pkg/reflect/ - you would have to ensure that no other alternatives (reflect2, goccy/go-reflect) are involved, and replace the code where needed
2. Same as (1), but ensure/enforce https://github.com/goccy/go-reflect to be used for reflection

. Consider re-compiling all dependencies - and simply use the resulting binaries/static libraries/shared libraries in your existing tests.

If you are interested to try gollvm - you can start with some business intelligence, written in Golang, and running on VMWare's virtual infrastructure.
I thought about extending https://github.com/advancedwebdeveloper/clang_test_cpu_features/tree/main/.github/workflows ( https://github.com/advancedwebdeveloper/clang_test_cpu_features/actions ), to add installation and benchmarking support.
It was not started for AMD CPUs - but you can consider using specific servers.

**Comment by youngnick** [comment]
Thanks for the investigation @advancedwebdeveloper! I suspect that gollvm support is behind a few other issues in priority, but I'll check in with the other maintainers and see what they think.
