### ISSUE TITLE
Tracking issue: Blog post for 1.9 release

### ISSUE THREAD

**Issue by jonasrosland** [projectcontour/contour#2934]
This is a tracking issue (as discussed in the community meeting) to ensure we have a blog going out together with the 1.9 release, explaining new features and functionality.

- [x] Assigned blog author
- [x] Blog drafted
- [ ] Blog reviewed
- [ ] Blog published

**Comment by youngnick** [comment]
Features that will need documentation:
- external auth (#432)
- status changes (#2495)
- CRD v1 (pr #2916)
- go-control-plane experimental support (#2134 )
