### ISSUE TITLE
internal: Update Contour import alias for Contour API

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2938]
The Contour import alias for the contour api is currently `contourv1`. Since the refactoring the internal/contour package into `contourv2` and it's not clear which version we should use.  

We could use `contourv1api` or similar for the the Contour api. 

_Originally posted by @skriss in https://github.com/projectcontour/contour/pull/2928#discussion_r493837575_

**Comment by stevesloka** [comment]
so we did some work to standardize on <thing><version>  which ended us up with `contourv2` and `envoyv2`. 

Now we're looking to add `contourapiv1` and `contourapiv1alpha1`. 

Maybe we should follow what we did with envoy to match so we'd end up with <thing>_<type>_<version> 

That would give us:

- `contour_v2`
- `envoy_v2`
- `contour_api_v1`
- `contour_api_v1alpha1`

I think this reads much better, but I'd like to get consensus since it's a pain to rename it all. 

@skriss @youngnick

**Comment by skriss** [comment]
Note that if we implement #2939, then `contourv2` would end up being more like `xds_cache_v2`
