### ISSUE TITLE
Using HTTPProxy APIs gives error

### ISSUE THREAD

**Issue by nmathew** [projectcontour/contour#2945]
**What steps did you take and what happened:**
I have written a golang application, which will install HTTPProxy rule to kubernetes cluster.

A more detailed code is here
https://gist.github.com/nmathew/7f5a357b2f387aab317ec04869f8925c

this resulted in an error 
**Got error: no kind is registered for the type v1.HTTPProxy in scheme "pkg/runtime/scheme.go:101"**

Is this correct to use these APIs from an application? If yes why this error is happening.

From api-resources: 
kubectl api-resources | grep http
httpproxies                       proxy,proxies             projectcontour.io                 true         HTTPProxy

**Environment:**

- Kubernetes version: 1.18.8
- OS: SLES 15 SP1

**Comment by skriss** [comment]
Per slack, I believe you need to explicitly add the `projectcontour.io` types to the scheme you're using for your client, using the helpers here: https://github.com/projectcontour/contour/blob/main/apis/projectcontour/v1/register.go#L56-L65

**Comment by nmathew** [comment]
Add projectcontourv1.AddToScheme to client supported schemes in the client code. This will solve the problem. Thanks @skriss.
