### ISSUE TITLE
httpproxy cookie attributes

### ISSUE THREAD

**Issue by lienerieksta** [projectcontour/contour#2965]
It would be very helpful if there was option to set additional attributes for httpproxy session affinity cookie. 

We have a stateful application that requires the cookie to have "SameSite=None" and "Secure" attributes set for them to be returned by the client.

I believe this feature would complement the very welcome addition of CORS support in contour.

**Comment by youngnick** [comment]
Thanks for this issue @lienerieksta, sorry about the delay in getting back to you. We have another request open (#3142) that's similar, and I wanted to ask what you would like for this one.

Would you want `SameSite=None` and `Secure` unconditionally added when using the `loadBalancerPolicy: cookie` setting? Or would you prefer more configurability?

**Comment by lienerieksta** [comment]
Thank you for you reply!

I think it needs to be more configurable. Adding `Secure` unconditionally would break the option to use `loadBalancerPolicy: cookie` without HTTPS. 

Most browsers nowadays seem to gravitate to `SameSite=Lax` as default behaviour and therefore that seems the most reasonable default, if one needs to be set. 

The `Secure` attribute could be added transparently when `SameSite=None` is set, or just as another configuration field independent of SameSite. 

From configuration perspective I imagined it something along the lines of:
```yaml
spec:
  routes:
    loadBalancerPolicy:
      strategy: Cookie
      attributes:
        sameSite: Lax/None/Strict
        secure: True/False
```

**Comment by sunjayBhatia** [comment]
This is something that would require an Envoy change no? Contour currently doesn't have control over the cookie attributes as per: https://www.envoyproxy.io/docs/envoy/v1.17.0/api-v3/config/route/v3/route_components.proto#config-route-v3-routeaction-hashpolicy-cookie

**Comment by youngnick** [comment]
Ah, you're right @sunjayBhatia. If we implement #3044, can you use the hash_policy list to get these attributes?

Regardless, it's probably worth opening an upstream issue to see if we can get these settings configurable.

**Comment by sunjayBhatia** [comment]
> Ah, you're right @sunjayBhatia. If we implement #3044, can you use the hash_policy list to get these attributes?
> 
> Regardless, it's probably worth opening an upstream issue to see if we can get these settings configurable.

Currently Envoy doesn't expose them but if it did and we do #3044 we would get the opportunity to configure them per named cookie

I'll do some experimenting with what Envoy does now, I think it gives a pretty minimal `Set-Cookie` header by default, not sure if it tries to add `Secure` as an attribute if its for a HTTPS service etc.

If we wanted to add more Lua I think we might be able to do something ourselves, but idk, a better solution may be Envoy supports it natively

**Comment by sunjayBhatia** [comment]
heres a related Envoy issue: https://github.com/envoyproxy/envoy/issues/12970

seems people are happy with writing a Lua filter to support this 🤔

**Comment by sunjayBhatia** [comment]
> I think it needs to be more configurable. Adding Secure unconditionally would break the option to use loadBalancerPolicy: cookie without HTTPS.

We could only apply a Lua script (or if we get Envoy to make it configurable) for virtualhosts with TLS enabled (and the cookie load balancer strategy on_

**Comment by sunjayBhatia** [comment]
For nginx it seems people might be using this 3rd party module to set cookie attributes: https://github.com/AirisX/nginx_cookie_flag_module

**Comment by youngnick** [comment]
I think that to get this one moving, applying a Lua filter is acceptable.

**Comment by andrewzah** [comment]
There are a few complications in the envoy lua api, namely:

* while iterating over the headers via `pairs()`, [they are not modifiable](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#pairs).
* [`headers:replace(key, val)`](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#replace) doesn't have a notion of multiple headers with the same key (like `Set-Cookie`...)

---

It seems like there's a viable workaround from this example with [streamInfo](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#stream-info-object-api) and [dynamicMetadata](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#dynamic-metadata-object-api):

```lua
function envoy_on_request(request_handle)
    local cookies = {}
    request_handle:streamInfo():dynamicMetadata():set("envoy.filters.http.lua", "cookies", cookies)
end

function envoy_on_response(response_handle)
    local headers = response_handle:headers()
    local cookies = response_handle:streamInfo():dynamicMetadata():get("envoy.filters.http.lua")["cookies"]

    for _, cookie in pairs(cookies) do
        local modifiedCookie = -- do processing here
        headers():add("set-cookie", modifiedCookie)
    end
end
```
(taken from [this example](https://github.com/envoyproxy/envoy/issues/7986#issuecomment-748673696)), but I haven't been able to test it yet.
