### ISSUE TITLE
Update Gangway readme

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2966]
The Gangway (https://github.com/heptiolabs/gangway/blob/master/docs/README.md) readme is from when Contour was still part of Heptio. It needs updated to remote the references to `heptio-contour` and replace with `projectcontour`.

**Comment by pbisen** [comment]
i would love to work on this. only the references have to be updated right? Could you please assign this to me

**Comment by stevesloka** [comment]
You got it @pbisen! Yup should just be the Heptio references as well as some links possibly. Thanks! 🎉

**Comment by pbisen** [comment]
Added my pr. please reply if you need any other change

**Comment by sunjayBhatia** [comment]
blocked on https://github.com/heptiolabs/gangway/pull/173

**Comment by kushthedude** [comment]
Hi @stevesloka , looks like the previous PR is abandoned, shall I move ahead with this issue?

**Comment by youngnick** [comment]
I'm fine with you moving ahead, @stevesloka?

**Comment by stevesloka** [comment]
Sounds good @kushthedude!

**Comment by kushthedude** [comment]
Hi @stevesloka @youngnick , I have made a pr
