### ISSUE TITLE
Use the Github Action for Go linting

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2972]
**Please describe the problem you have**

Run the linter from the Github action for better PR integration

https://github.com/golangci/golangci-lint-action

bonus points if we can add this to https://github.com/projectcontour/.github/ in such a way that every repo gets it automatically.

**Comment by Glyphack** [comment]
Hi, I'm willing to work on this. I'm not familiar with how https://github.com/projectcontour/.github/ works, will adding a workflow to it copied to all the repositories?

**Comment by stevesloka** [comment]
@jpeach why is this needed? The lint is already run on PRs as a separate task.

![image](https://user-images.githubusercontent.com/1048184/94958531-af38d700-04bd-11eb-9183-ab25293dcb3c.png)

**Comment by jpeach** [comment]
> @jpeach why is this needed? The lint is already run on PRs as a separate task.
> 
> ![image](https://user-images.githubusercontent.com/1048184/94958531-af38d700-04bd-11eb-9183-ab25293dcb3c.png)

IIUC, the action is able to annotate the PR diff with any errors that it finds 

https://github.com/golangci/golangci-lint-action#golangci-lint-action

Using an action also (I think) makes it possible to automatically get it to run on every projectcontour repo my adding it into the .github repository.
