### ISSUE TITLE
Add a lifecycle/needs-triage issue label

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2981]
**Please describe the problem you have**

I recently discovered that Github issue templates can add a default set of labels. This opens the possibility of automatically adding a `lifecycle/needs-triage` label to all new issues. This label would (IMHO) make it easier to keep track of which issues need to be triaged.

**Comment by jpeach** [comment]
@youngnick @stevesloka @skriss @danehans WDYT?

**Comment by skriss** [comment]
So all new issues would get the label, and then as we triage, we remove it?

That sounds reasonable to me, though we'll need to be more regular about triaging things or we'll end up with a lot of issues with this label.

**Comment by jpeach** [comment]
> So all new issues would get the label, and then as we triage, we remove it?
> 
> That sounds reasonable to me, though we'll need to be more regular about triaging things or we'll end up with a lot of issues with this label.

I don't think the label changes the need for triage,  but I do hope that it makes it clearer what needs to be triaged.

**Comment by michmike** [comment]
i support this.
