### ISSUE TITLE
Split KubernetesCache into separate cache and policy objects

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2982]
**Please describe the problem you have**

`KubernetesCache` caches various Kubernetes types, but also contains some controller policy fields and policy-oriented retrieval APIs.

To make it easier to implement #2683, I propose splitting this object up into its separate responsibilities.

* A `Cache` object that implements the controller-runtime [`cache.Cache`](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/cache#Cache) interface
* Move the `RootNamespaces` field to the HTTPProxy build processor
* Replicate the `IngressClass` field to the relevant build processors and add just have the the processor call `annotation.MatchesIngressClass()` as needed
* Move the following members into accessor functions that take a `cache.Cache` parameter
  * LookupSecret
  * LookupUpstreamValidation
  * LookupDownstreamValidation
  * DelegationPermitted
  * LookupService

**Comment by jpeach** [comment]
@stevesloka @skriss @youngnick WDYT?

**Comment by youngnick** [comment]
This one seems like it will be a good idea to me.

**Comment by skriss** [comment]
Yep, sounds reasonable to me.
