### ISSUE TITLE
use nonroot vs. nobody user

### ISSUE THREAD

**Issue by dprotaso** [projectcontour/contour#2984]
related: https://github.com/knative-sandbox/net-contour/pull/292

`nobody` doesn't have a valid `/home` directory - so it is recommended to use `nonroot`

**Comment by jpeach** [comment]
Thanks for reporting @dprotaso. This seems to be a problem introduced in knative by their image building process. I'll check back later for new information, but I think that any fix needs to be made in the knative tooling.

**Comment by dprotaso** [comment]
gonna close this out since contour doesn't use distroless
