### ISSUE TITLE
Reevaluate how comparisons for status are implemented

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2995]
When comparing status structs, the `LastTransitionTime` was causing lots of updates in #2979. #2986 moved to use the `cmp.Equal` package as it is used in other places, however, #2853 moved away from the cmp package since it can panic. 

This issue is to determine the best path forward to fixing this comparison. 

1. Knative defines a `VolatileTime` type, which we exclude from semantic equality, which is used exclusively for `LastTransitionTime`.
2. We can add a custom `equalities` func to ignore the `LastTransitionTime` as we did in the `cmp.Equal` PR. 

_Originally posted by @mattmoor in https://github.com/projectcontour/contour/pull/2986#issuecomment-703935498_

**Comment by skriss** [comment]
Two places where we currently use `cmp.Equal` in non-test code:

1. https://github.com/projectcontour/contour/blob/main/internal/k8s/helpers.go#L42-L49
1. https://github.com/projectcontour/contour/blob/main/internal/contour/handler.go#L179-L184

Both require ignoring certain fields from the comparison.
