### ISSUE TITLE
Add Anti-Affinity to Contour Deployment

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour#2997]
**Please describe the problem you have**
The current contour deployment specifies multiple pod replicas but does not include an anti-affinity policy. This may cause pods from the deployment to get scheduled onto the same node.

/cc @jpeach @stevesloka @Miciah

**Comment by jpeach** [comment]
@danehans it looks like anti-affinity to me https://github.com/projectcontour/contour/blob/main/examples/contour/03-contour.yaml#L28-L36

**Comment by youngnick** [comment]
@danehans, does this meet what you were looking for?
