### ISSUE TITLE
site: Fix the table of contents plugin

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3004]
There's a plugin on the projectcontour.io site that shows a table of contents. For some reason when published through netlify, it doesn't render, but locally it does. 

A good example is on the Auth Page: https://projectcontour.io/guides/external-authorization/

_Originally posted by @stevesloka in https://github.com/projectcontour/contour/pull/2999#issuecomment-704982099_

**Comment by michmike** [comment]
@jonasrosland can you please take a look at this. thanks!

**Comment by sunjayBhatia** [comment]
Same issue: https://github.com/projectcontour/contour/issues/2094

**Comment by sunjayBhatia** [comment]
Possibility, drop current CMS and move to Hugo

**Comment by jonasrosland** [comment]
This will happen very, very soon :)
