### ISSUE TITLE
Upgrade to Envoy v1.16

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3013]
Hot on the tail of Contour v1.9.0, Envoy v1.16.0 just got released. =) 

We should test/upgrade Contour to the new Envoy version.

**Comment by glerchundi** [comment]
Just to let you know that the first Envoys version that fixes a blocking issue with gRPC-Web & Safari 13 is 1.16 🤷‍♂️

So at least for me and my team it's worth bumping...

/cc @yoitsro @aberasarte @lopezator

**Comment by yoitsro** [comment]
Yep, this is the final piece of the CORS/gRPC-Web puzzle for me! Once this is done, it'll mean we can stop running custom versions of both Contour and Envoy 🎉

**Comment by mattmoor** [comment]
This is the first version of Envoy with arm64 support as well.  I've been running Contour on arm64 for a while with unofficial builds of Envoy, so it works (for how we hold Contour).  Would be awesome to see Contour starting to ship multi-arch images 🤩

**Comment by jpeach** [comment]
> Would be awesome to see Contour starting to ship multi-arch images

https://github.com/projectcontour/contour/issues/2868

**Comment by stuartpb** [comment]
I'm going to give it a try - looking at [the release notes](https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.16.0), it doesn't look like anything was changed that would obviously affect Contour.

**Comment by jpeach** [comment]
@stuartpb We'd like to do this for the 1.10 release ... if you could submit a PR for upgrading the Envoy version (should just be updating YAML and running tests), I'd be happy to review 👍

**Comment by yoitsro** [comment]
https://github.com/projectcontour/contour/pull/3029
