### ISSUE TITLE
Ingress path missbehaving when upstream service is not found.

### ISSUE THREAD

**Issue by Zsolt-LazarZsolt** [projectcontour/contour#3039]
**What steps did you take and what happened:**
Installed an ingress resource with:
/ path served by service1
/second served by service2 

[backend1.txt](https://github.com/projectcontour/contour/files/5403230/backend1.txt)
[backend2.txt](https://github.com/projectcontour/contour/files/5403231/backend2.txt)
[ingress.txt](https://github.com/projectcontour/contour/files/5403234/ingress.txt)

Both service1 and service2 is installed.
So far everything is fine
/second prefix is routed to service2, everything else routed to service1.

I remove service2 from the cluster.
Now everything, including /second prefix is served by **service1**

**What did you expect to happen:**
The same setup should result in 503 to everything that is with prefix /second

**Anything else you would like to add:**
I will include ingress, and backend manifests.
Also config dump when service2 is present and when it is not.

[backend_missing.log](https://github.com/projectcontour/contour/files/5403232/backend_missing.log)
[backend_present.log](https://github.com/projectcontour/contour/files/5403233/backend_present.log)

**Environment:**

- Contour version: 1.7.0
- Kubernetes version: (use `kubectl version`): v1.15.3
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): suse

**Comment by skriss** [comment]
It looks like in our ingress processor, if we encounter a path pointing to a service that doesn't exist in the cluster, we silently ignore it: https://github.com/projectcontour/contour/blob/main/internal/dag/ingress_processor.go#L138-L141

The result of this would be that only the `/` route gets configured in Envoy, so every path, including `/second`, ends up matching that route.

At a minimum, we should be logging this; not sure about programming the route in Envoy, though.

**Comment by jpeach** [comment]
> It looks like in our ingress processor, if we encounter a path pointing to a service that doesn't exist in the cluster, we silently ignore it: https://github.com/projectcontour/contour/blob/main/internal/dag/ingress_processor.go#L138-L141

Yeh, basically every error in ingress is silent :(

**Comment by skriss** [comment]
Moving this back to the parking lot for now.

**Comment by sunjayBhatia** [comment]
The missing service is being logged now: https://github.com/projectcontour/contour/pull/3359

**Comment by xaleeks** [comment]
Thanks @sunjayBhatia.  So is the behavior corrected now so that none of the /second requests are routed to service 1?  If so, we can consider this bug fixed.  And I assume it doesn’t exist on HTTPProxy right? Say when you have 2 services matching different prefixes specified under spec.routes and one of the services is removed, the matching request isn’t automatically redirected to the other.

**Comment by sunjayBhatia** [comment]
> So is the behavior corrected now so that none of the /second requests are routed to service 1?

No, we just log the missing service and continue on processing the Ingress resource, so if you have a prefix path that is more general than the route that had a missing service, requests will be routed to it

> And I assume it doesn’t exist on HTTPProxy right? Say when you have 2 services matching different prefixes specified under spec.routes and one of the services is removed, the matching request isn’t automatically redirected to the other.

I believe for HTTPProxy we set status on the resource and say it is invalid/don't program any of it

The original request was to 503 if a service is missing, which matches what Gateway API specifies and seems v reasonable, but the Ingress spec never specified so we haven't done anything to remediate it.

**Comment by youngnick** [comment]
Sadly, this behavior has always been undefined in the Ingress spec, and we copied what nginx did back in the day ( I believe). This is not easily fixable in Ingress as well, because there is nowhere to put information about things not working on the object. We really need something like in the conflict resolution proposal (#3145), and have our stance for Ingress be "If you configure something, and we can't do it, we'll give you a HTTP error code. But you'll have to check the log or try the request to find out which ones are working for Ingress."

**Comment by xaleeks** [comment]
Yeah I think we should surface to the user that his service no longer exists instead of silently failover to whatever existing service on that paths.  And we should at least document that behavior in the meantime.

**Comment by youngnick** [comment]
I agree we should document the behavior, but there's no way to surface to the user that the service no longer exists. If they've asked for ingress using an Ingress object, there's nowhere to put status information except the Contour logs (which probably won't be accessible to application developers anyway).

So, our options are either fail silently, or give an error code. That's it. Even if we supply an error code, the user will need to go hunting around in Contour logs to find out what happened. This is one of Ingress' biggest operational failings, that if anything is broken, you have to solve a mystery to figure out what it was.

**Comment by sunjayBhatia** [comment]
heyo @tsaarni are you still working on this by chance? just changing labels around and noticed you are assigned
