### ISSUE TITLE
Support custom use_remote_address settings in Envoy

### ISSUE THREAD

**Issue by tsing** [projectcontour/contour#3041]
We are using Contour behind the AWS ALB, and having issues on getting the real remote address of the client connection.

The AWS ALB would pass X-Forwarded-* headers to Envoy, but we couldn't get the X-Forwarded-For and X-Forwarded-Proto headers from the downstream. 

We are thinking it could be fixed by allowing custom the *use_remote_address* setting in Envoy.

**Comment by youngnick** [comment]
Yes, it seems that for forwarding X-Forwarded-* info on, `use_remote_address` must be set to `false`.

Both the [v2 api](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#use_remote_address) and the [v3 api](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto) have this setting; and it appears to work the same in both cases.

I think allowing the flipping of this value to `false` is reasonable, and we should make this change.

However, there is a slight concern here - in that if you set `use_remote_address` to `false`, you're trusting the downstream or external proxy to set the details correctly. 

Any change we make needs to keep the current default, and have a name that makes clear that you're trusting someone else to set the XFF headers for you. Maybe `use-external-xff`, `trust-downstream`, or similar?

**Comment by jpeach** [comment]
Yeh, I think the policy question that operators need to specify here is whether the downstream connection is trusted or not; i.e. where the envoy sits in the proxy hierarchy.

extended discussion [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-for)
