### ISSUE TITLE
xDS v2-->v3 Upgrade Plan

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3047]
As Contour moves to the xDS v3 version API we need to think about how users upgrade from v2 to v3 in production systems.

Upgrading to v3 requires a new bootstrap config on the Envoy instances. After Contour is upgraded and only serves v3, there is a period of time where any Envoy that still runs the v2 API won't receive updates. 

## How to solve?
- Have two instances of Contour, one with v2 and one with v3 such that as old Envoy's are recycled into new, then they can still receive updates. 
- Have Contour serve up two instances of xDS version from the same contour pod, but running on different ports? 

// cc #1898

**Comment by jpeach** [comment]
> * Have Contour serve up two instances of xDS version from the same contour pod, but running on different ports?

Pretty sure you can have v2 and v3 running in the same gRPC server

**Comment by moderation** [comment]
Related to the move to Envoy 1.16.0 in https://github.com/projectcontour/contour/pull/3029 will by more v2 warnings as per https://www.envoyproxy.io/docs/envoy/v1.16.0/version_history/current
` config: additional warnings have been added for the use of v2 APIs. These appear as log messages and are also captured in the deprecated_feature_use counter after server initialization.`

**Comment by jpeach** [comment]
Accepted. Holding for feedback.

**Comment by stevesloka** [comment]
https://www.envoyproxy.io/docs/envoy/latest/faq/api/control_plane_version_support

**Comment by stevesloka** [comment]
@moderation thanks for the link to the logs, I do see those now in Envoy v1.16.0. =)

**Comment by stevesloka** [comment]
I played around with this a bit today and think @jpeach's suggestion is good to run both versions of the server at the same time.

I haven't been able to get different transport / resource api versions nor get the `envoy.reloadable_features.enable_type_url_downgrade_and_upgrade` to work. 

**Solution:**
Currently Contour serves a v2 endpoint which Envoy clients connect to since `transport_api_version` & `resource_api_version` aren't currently defined in the contour boostrap config file. We will then add the v3 endpoints to the same v2 server currently running. New Envoy clients can be upgraded with v3 boostrap config files referencing `transport_api_version: V3` & `resource_api_version: V3` and will connect to the v3 endpoints and get their configuration where older Envoy clients whom still reference v2 will still get their configuration. 

The configuration file currently has a config value for `xds-server-version` which can still be used. If nothing is specified, the default is to serve both xDS api endpoint versions (e.g. v2 & v3). If a specific version is specified, then the xDS server will only serve that version configured.

Thoughts @skriss @jpeach @youngnick and anyone else?

**Comment by stevesloka** [comment]
The alternative which might make more sense is to change the `xds-server-version` to a list of versions. We can still keep the same logic outlined previously, but gives a more clear representation of Contour's behavior.

Additionally, changing to a list will allow for new xDS versions to be enabled if specific users desire to do that which using the default strategy would automatically enable them which might not be desirable.

**Comment by youngnick** [comment]
That solution sounds great @stevesloka! That seems like a great way to allow people to move to v3 as they are ready - if it's just a change to `contour bootstrap` for the actual cutover, then we can do it with the usual process - add a new flag that defaults to the current version, add the new version as an option, then flip the default, then later, remove the flag. (Just for the boostrap, I mean).

That will allow people to flip their Envoys when they are ready, and then flip back easily if there is a problem.

**Comment by jpeach** [comment]
> The configuration file currently has a config value for xds-server-version which can still be used. If nothing is specified, the default is to serve both xDS api endpoint versions (e.g. v2 & v3). If a specific version is specified, then the xDS server will only serve that version configured.

Defaulting to both versions sounds reasonable to me.

> The alternative which might make more sense is to change the xds-server-version to a list of versions. We can still keep the same logic outlined previously, but gives a more clear representation of Contour's behavior.

I think it will be tricky to make the config file accept either a string or an array for the `xds-server-version` key. If we hard-switch to an array, that will break compatibility. But you could achieve a similar effect using the value "any" to indicate that Contour should serve all xds versions.

> just a change to contour bootstrap for the actual cutover, then we can do it with the usual process - add a new flag that defaults to the current version, add the new version as an option, then flip the default, then later, remove the flag

This approach is the most consistent with what we have done so far. I can think of some complicated ways to make the rollout a bit more controllable, but probably not worth it :)

Interesting discussion in https://github.com/istio/istio/issues/19885.

**Comment by stevesloka** [comment]
> I think it will be tricky to make the config file accept either a string or an array for the xds-server-version key. If we hard-switch to an array, that will break compatibility. But you could achieve a similar effect using the value "any" to indicate that Contour should serve all xds versions.

We haven't shipped the feature yet, so have time to switch which is why I'd like to determine this path before shipping v1.10.0. 

For the list of supported xDS versions, any version in that list would be served by Contour. This helps with future proofing as well, when v4 is released and if parts of Contour switch over, potentially we'd want to allow users to move to that while others want to stay on v3. Some users may not want to serve a v4 endpoint until they move and there would be no way to disable it. 

If we keep the convention method then when we add v4 support it will just show up automatically. Maybe that's ok and I'm over thinking? 

Config file example: 
```
server:
    xds-server-type: contour
    xds-server-versions:     # <--- change to "versions"
    - v2                               # <--- any in the list will be served
    - v3
```

**Comment by youngnick** [comment]
After a call today, I think the maintainers have decided that we're going to go with serving a combined v2/v3 server in the transition period between v2 and v3, and retire v2 as soon as Envoy removes support for it. The version served will not be configurable by Contour, the v2/v3 switch be solely done by the bootstrap configuring Envoy to request a specific version.

@jpeach @stevesloka @skriss, anything else important here?
