### ISSUE TITLE
site: allow content to horizontally expand beyond 1440px

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#3062]
The content on the site/docs seems to be limited to a max width of 1440px, even if the browser window is expanded beyond this. It'd be really nice to allow it to continue to expand, so wider screens could display more content and less whitespace.

**Comment by stevesloka** [comment]
@jonasrosland is Contour moving away from the current Jekyll site?

**Comment by jonasrosland** [comment]
@stevesloka Yes, but not immediately, and it would require some heavy lifting. The issue here though could be fixed with some CSS changes. I'll dive into it a bit.

**Comment by skriss** [comment]
fixed in the new site, closing!
