### ISSUE TITLE
site: fix broken links

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#3063]
It looks like after merging #3057, we have some broken links that point to the now-deleted `httpproxy.md` page. The site-proof check shows them:

https://github.com/projectcontour/contour/runs/1306396610

**Comment by stevesloka** [comment]
So the PR job didn't pick up this running the proof check?

**Comment by skriss** [comment]
https://github.com/projectcontour/contour/issues/2032 makes it pretty ineffective as a PR check for broken links
