### ISSUE TITLE
Contour "X-Contour-Session-Affinity" cookie is missing "secure" and "SameSite" settings

### ISSUE THREAD

**Issue by ryanelian** [projectcontour/contour#3142]
**What steps did you take and what happened:**

Enable Contour sticky session / affinity for a website:

```yaml
spec:
  routes:
    loadBalancerPolicy:
      strategy: Cookie
```

Then open the said website in Firefox / scan the website using some security audit software.

Firefox will warn you that they will soon **reject** the cookie:

```
Cookie “X-Contour-Session-Affinity” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

A security audit gives us this message:

```
The 'secure' flag is not set on this cookie. There is no Cookie Prefix on this cookie. This is not a SameSite Cookie. 
```

This is a somewhat important problem because it may cause developers using Contour to fail security audit with no way of fixing it other than changing their ingress / reverse proxy.

**What did you expect to happen:**

Cookie is not flagged as insecure: set `SameSite` flag to `Lax` or `Strict`

Set cookie as secure if accessing the site via HTTPS / TLS enabled.

**Anything else you would like to add:**

Firefox version: 84.0b2
Sample security header scanner: https://securityheaders.com

**Environment:**

- Contour version: 1.8.1
- Kubernetes version: (use `kubectl version`): v1.18.9
- Kubernetes installer & version: kubeadm
- Cloud provider or hardware configuration: UpCloud 2core 4GB RAM
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.5 LTS

**Comment by youngnick** [comment]
Thanks for this issue @ryanelian. We've got a number of issues around the Contour cookie generation open, #2965 seems very similar to yours. Thanks for the additional information from Firefox though, that's very helpful. I'll speak to the team and get this prioritised.

**Comment by youngnick** [comment]
Just looking over this again and wanted to ask what you would expect to see, @ryanelian?

It seems like the `Secure` property should be set if accessing the site via HTTPS, but I think one of us will need to spend some time parsing how `SameSite` and `Secure` interact between themselves and with CORS?

**Comment by youngnick** [comment]
We've also got #3044 open as a request to add a more direct ability to configure the Envoy `hash_policy`, which seems like it would allow this to be solved, but it seems to me like it might be overkill.

**Comment by ryanelian** [comment]
> Just looking over this again and wanted to ask what you would expect to see, @ryanelian?

> It seems like the Secure property should be set if accessing the site via HTTPS, but I think one of us will need to spend some time parsing how SameSite and Secure interact between themselves and with CORS?

I think setting `SameSite=Lax` should be enough to drop the warning.

**Comment by sunjayBhatia** [comment]
Similar to https://github.com/projectcontour/contour/issues/2965#issuecomment-763992272

This requires an Envoy change to allow adding attributes to generated cookies

**Comment by xaleeks** [comment]
@youngnick @sunjayBhatia  Does 'Prioritized Backlog' still accurately reflect the status of this request here? It does feel like a bug, or at least a gap.

**Comment by sunjayBhatia** [comment]
Sounds accurate to me? I don't know what the priority is around changing this behavior, seems like a relatively involved Envoy or Lua in Contour change since Envoy does not yet natively support rewriting Cookies

**Comment by youngnick** [comment]
Yeah, this is definitely a problem, because it causes incorrect XSS errors, but as @sunjayBhatia says, the fix requires an Envoy change, so we will probably need to organise that change ourselves.

**Comment by sunjayBhatia** [comment]
Through a separate channel, this issue came up, unrelated to Contour: https://github.com/envoyproxy/envoy/issues/15612

There may be room to add some sort of generic Cookie attribute rewriting utility, im involved with this issue and we can see if it some solution could fit this and Contour's need

**Comment by xaleeks** [comment]
tagging this 1.19 temporarily for us to discuss how to make progress
