### ISSUE TITLE
Operator CI Job

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour#3165]
**Please describe the problem you have**
Create a CI job similar to https://github.com/projectcontour/contour-operator/pull/133 that installs contour using the [operator](https://github.com/projectcontour/contour-operator). This will help avoid any deployment-related regressions to Contour.

xref: https://github.com/projectcontour/contour-operator/issues/71

/cc @Miciah

**Comment by sunjayBhatia** [comment]
closing, we've got the contour gateway provisioner and have slowed work on the operator
