### ISSUE TITLE
HTTPProxy FQDN Validation 

### ISSUE THREAD

**Issue by perithompson** [projectcontour/contour#3166]
**Please describe the problem you have**

During the creation of new HTTPProxy resources, FQDNs are not validated resulting that invalid urls such as `my-domain-${somevariable}.domain.tld` are passed to envoy but the HTTPProxy is not created. Could the CRD definition be edited to include DNS1123 validation similar to [apimachinery](https://github.com/kubernetes/apimachinery/blob/2456ebdaba229616fab2161a615148884b46644b/pkg/util/validation/validation.go#L78)  to check that the FQDN does not container invalid characters?

**Comment by youngnick** [comment]
This seems very reasonable to me, hopefully adding this to the CRD validation would cover most of it, although that wouldn't help for already exsiting resources.

**Comment by stevesloka** [comment]
/assign @abhide 

(Having trouble assigning you "officially" but feel free to work on this Amey!)

**Comment by abhide** [comment]
Thanks @stevesloka 

Looks like i need to add a validation to `internal/dag/httpprocessor.go` ?

**Comment by stevesloka** [comment]
@abhide yup I think that should work as well as adding validation to the CRD spec would also be good, but need to make sure that regex matches a bunch of domains. At one point we did have this type of validation in IngressRoute, but found it was too restrictive for many users who were using internal domains, etc.

**Comment by abhide** [comment]
> @abhide yup I think that should work as well as adding validation to the CRD spec would also be good, but need to make sure that regex matches a bunch of domains. At one point we did have this type of validation in IngressRoute, but found it was too restrictive for many users who were using internal domains, etc.

@stevesloka would the CRD validation be part of a validating webhook or there is a different way to add these validations? Don't see any validating webhooks in the repo.

**Comment by xaleeks** [comment]
@abhide hey Amey, do we

**Comment by abhide** [comment]
> @abhide hey Amey, do we

@xaleeks Seems incomplete; could you please clarify here?

**Comment by xaleeks** [comment]
@abhide  Sorry about that, I meant to ask if there's confidence to have this delivered in 1.14.  And to see if there's any help you need from the contour team.  Cheers

**Comment by youngnick** [comment]
Yes, the domains we need to support are:
- one valid DNS label (by RFC1123)
- two or more valid DNS labels, separated by `.`, that is, what RFC1123 defines as a "subdomain".

The single valid DNS label is important so that people may use a Kubernetes service name - this enables using Contour as a cluster-internal thing (which some people want to do).

**Comment by sunjayBhatia** [comment]
Moving this to 1.15

**Comment by sunjayBhatia** [comment]
Seems like https://github.com/projectcontour/contour/pull/3343 is still in progress, moving to 1.16

**Comment by youngnick** [comment]
Still waiting on #3343, moving to 1.17.

**Comment by youngnick** [comment]
Looks like #3343 has been closed as stale, I'll move this to 1.18 for now, @abhide do you still want to work on this?

**Comment by abhide** [comment]
@youngnick I might not be able to get to this week. To unblock; I have unassigned myself from this ticket.
