### ISSUE TITLE
Setting use-proxy-protocol breaks Contour

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3181]
If you set the flag `--use-proxy-protocol` on Contour, Envoy will stop serving traffic. There aren't really any error logs anywhere which is interesting. Also interesting is only the filter shows up in the Envoy config, not being used anywhere. 

## Contour Config
```
containers:
      - args:
        - serve
        - --incluster
        - --use-proxy-protocol
        - --xds-address=0.0.0.0
        - --xds-port=8001
        - --envoy-service-http-port=80
        - --envoy-service-https-port=443
        - --contour-cafile=/certs/ca.crt
        - --contour-cert-file=/certs/tls.crt
        - --contour-key-file=/certs/tls.key
        - --config-path=/config/contour.yaml
```

## Curl 
```
$ curl -i local.projectcontour.io                                                                                                                              
curl: (52) Empty reply from server
```

**Comment by jpeach** [comment]
Do you need to use `curl --haproxy-protocol`?

**Comment by stevesloka** [comment]
Yeah that works locally, I was in AWS testing through this. Let me poke at the guide and see if something is missing or changed in AWS-land.

**Comment by jpeach** [comment]
> Yeah that works locally, I was in AWS testing through this. Let me poke at the guide and see if something is missing or changed in AWS-land.

Oh, because you used `local.projectcontour.io` I assumed that you were local :)

**Comment by stevesloka** [comment]
So I killed my cluster and redid this and all works, so not sure if it was an `ID10T` error or something else, but seems to work fine as-is.
