### ISSUE TITLE
`main` image builds are failing

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#3205]
The last few PR merges to `main` have had their image builds fail. See e.g. https://github.com/projectcontour/contour/runs/1554462882.

```
failed to solve: rpc error: code = Canceled desc = failed to compute cache key: failed to copy: httpReadSeeker: failed open: failed to do request: context canceled
```

**Comment by sunjayBhatia** [comment]
Seeing some things pointing to `buildkit` being at fault for this potentially

**Comment by skriss** [comment]
Maybe it's fixed itself now: https://github.com/projectcontour/contour/runs/1559663637

**Comment by youngnick** [comment]
This looks like a transient problem to me. Can someone in PDT check in your morning, and resolve this if it's clear still?

**Comment by skriss** [comment]
Yeah, it looks like it's cleared up. Closing this out.
