### ISSUE TITLE
Linter errors not showing

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3227]
Looking at the go reportcard, there are a bunch of linter errors that aren't showing up when the lint task is run, we should fix that and push our score up: https://goreportcard.com/report/github.com/projectcontour/contour#golint

**Comment by seemiller** [comment]
I've been working with Contour on a work-related project and am interested in contributing more to the Kubernetes OSS community. This looks like a good first issue that I am willing to take on. Could this issue be assigned to me?

**Comment by skriss** [comment]
@seemiller that'd be great! Let us know if you need any input.
