### ISSUE TITLE
RouteConfiguration rejected due to duplicate entry

### ISSUE THREAD

**Issue by erwbgy** [projectcontour/contour#3230]
**What steps did you take and what happened:**
Creating two HTTPProxy objects with FQDNs that only differ by case is allowed and causes Envoy to reject all further route configuration.

**What did you expect to happen:**
Duplicate FQDNs should be rejected, regardless of case.

**Anything else you would like to add:**
Example - creating these two HTTPProxy objects:
```
$ cat explorer-httpproxy-routes.yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: explorer
spec:
  virtualhost:
    fqdn: explorer.mydomain.com
    tls:
      secretName: explorer-tls
  routes:
    - services:
      - name: explorer
        port: 8080
 
$ cat explorer-httpproxy-routes-up.yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: explorer-up
spec:
  virtualhost:
    fqdn: EXPLORER.mydomain.com
    tls:
      secretName: explorer-tls
  routes:
    - services:
      - name: explorer
        port: 8080
 ```
Results in Envoy rejecting all further route configuration with an error like:
```
envoy-vdpsb envoy-485m7envoy-wpvz4envoy-t82l7envoy-v4krhenvoy  envoy    [2020-12-21 13:12:00.024][1][warning]
[config] [source /common/config/grpc_subscription_impl.cc:107] gRPC config for 
type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Only unique values for domains are permitted.
Duplicate entry of domain explorer.mydomain.com in route ingress_http
```

**Environment:**

- Contour version: 1.10.1
- Kubernetes version: (use `kubectl version`): 1.18.11
- Kubernetes installer & version: kubeadm 1.18
- Cloud provider or hardware configuration: on-prem
- OS (e.g. from `/etc/os-release`): RHEL 8.2

**Comment by youngnick** [comment]
Thanks for this issue @erwbgy. If you remove the config, does Envoy start accepting updates again? Otherwise, this is also hitting the NACK problem (#1176 ).

I'll take a look at your PR as well, thanks for sending that through.

**Comment by erwbgy** [comment]
Yes, after removing the duplicate it starts working  okay again.
