### ISSUE TITLE
Support a TLS Client Authentication policy: request client certificate but not validate it or request client certificate and proceed even though validation fails 

### ISSUE THREAD

**Issue by yanjunli76** [projectcontour/contour#3253]
Hi @youngnick @jpeach 

**Problem Statement**
We import client certificates into the secret `(HTTPProxy: spec->tls->clientValidation->caSecret)` so that the envoy can validate the client certificate against the caSecret.  But because of the limit of k8s secret, we can only import around limited client certificates (around 500-1000 certificates) into the caSecret. Currently, we have more than 5k hosts with self-signed certificates that need to connect to the ingress entrypoint. Because of some reasons, we can't use a CA and issue a ca-signed certificate for each host. We can only use a self-signed certificate for each host.

**Solution**
We could use external auth for client certificate validation. The external auth server gets the client certificate from envoy and could check it against as many secrets as it needs to.

**Feature Request**
for contour v1.11.0, if we don’t specify the `clientValidation` part in HTTPProxy spec, the envoy will not request the clients certificate. If we give the `clientValidation` part in HTTPProxy spec, then the envoy will request the client certificate and validate it against the caSecret.

To implement the above solution, we need that envoy can request the client certificate but not validate it or request the client certificate and proceed even though validation fails so that the envoy can pass the client certificate to external auth server.

Thanks!

**Comment by sunjayBhatia** [comment]
Sounds like requesting a combination of https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#extensions-filters-http-ext-authz-v3-extauthz (`include_peer_certificate` field) and https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#enum-extensions-transport-sockets-tls-v3-certificatevalidationcontext-trustchainverification (peer verification mode set to `ACCEPT_UNTRUSTED`)

**Comment by sunjayBhatia** [comment]
Side note: This might be in the bucket of things where some pretty specific Envoy config is requested? Maybe we need a tag for that?

**Comment by yanjunli76** [comment]
> Sounds like requesting a combination of https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#extensions-filters-http-ext-authz-v3-extauthz (`include_peer_certificate` field) and https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#enum-extensions-transport-sockets-tls-v3-certificatevalidationcontext-trustchainverification (peer verification mode set to `ACCEPT_UNTRUSTED`)

yes, I did a quick test by modifying the `internal/envoy/v3/auth.go`:
```diff
--- a/internal/envoy/v3/auth.go
+++ b/internal/envoy/v3/auth.go
@@ -102,9 +102,17 @@ func DownstreamTLSContext(serverSecret *dag.Secret, tlsMinProtoVersion envoy_v3_
                vc := validationContext(peerValidationContext.GetCACertificate(), "")
                if vc != nil {
                        context.CommonTlsContext.ValidationContextType = vc
-                       context.RequireClientCertificate = protobuf.Bool(true)
                }
+       } else {
+               vc := &envoy_v3_tls.CommonTlsContext_ValidationContext{
+                       ValidationContext: &envoy_v3_tls.CertificateValidationContext{
+                               TrustChainVerification: envoy_v3_tls.CertificateValidationContext_ACCEPT_UNTRUSTED,
+                       },
+               }
+               context.CommonTlsContext.ValidationContextType = vc
        }
+       context.RequireClientCertificate = protobuf.Bool(true)
```

which can work as I expect.

**Comment by sunjayBhatia** [comment]
Also required: Gatekeeper templating to let Contour administrators prevent users from overriding this
