### ISSUE TITLE
CI should use the latest integration-tester

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#3257]
CI is currently skipping integration tests b/c it is not using the latest integration-tester code that fixes a bug where `skip` directives are leaked

Some options to fix:
- Just tag the latest integration-tester and cut a release, use that in CI
  - Pros: will be fixed for a while, integration-tester doesn't change much; stable integration-tester release
  - Cons: more convoluted process to get latest changes if there is another bug, have to cut a release etc.
- Install the latest integration-tester code on each PR and commit (use `go install etc.`)
  - Pros: always have the latest code
  - Cons: Each PR/CI run will take longer, changes to integration-tester are infrequent so this may be a bit of a waste

**Comment by sunjayBhatia** [comment]
Slack conversation about this topic: https://kubernetes.slack.com/archives/C8XRH2R4J/p1610569123306600

**Comment by sunjayBhatia** [comment]
An option extrapolated from slack:
- Do continue to use integration-tester releases
- However, name artifacts in the release generically so we can use the `latest` release URL to download things (is this possible?)
- Doesn't require a new PR each time integration-tester changes

**Comment by skriss** [comment]
> An option extrapolated from slack:
> 
> * Do continue to use integration-tester releases
> * However, name artifacts in the release generically so we can use the `latest` release URL to download things
>   
>   * `curl -s -L https://github.com/projectcontour/integration-tester/releases/latest | grep ...` to find the URL
> * Doesn't require a new PR each time integration-tester changes

Seems like the best of both worlds; do we just need to remove the version # from the release artifact? Should be easy to do with the `name_template` in goreleaser: https://goreleaser.com/customization/archive/

**Comment by sunjayBhatia** [comment]
It doesn't seem like https://github.com/projectcontour/integration-tester/releases/download/latest/integration-tester_6.0.0_Linux_x86_64.tar.gz works so maybe removing the version won't help 🤔
