### ISSUE TITLE
Remove `-mod=vendor`, `go mod vendor` from scripts

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#3276]
Contour has a number of places where it runs `go mod vendor` or `export GOFLAGS=-mod=vendor`. I *think* these are obsolete at this point and we can just remove them. 

My specific issue is that I'd like to avoid having to run `go mod vendor` before running `make generate` locally.

The specific instances are shown here:
https://github.com/projectcontour/contour/search?l=Shell&q=vendor&type=code
https://github.com/projectcontour/contour/search?l=Makefile&q=vendor&type=code
https://github.com/projectcontour/contour/search?l=YAML&q=vendor&type=code

Is anyone aware of a reason why we need to keep these, vs. letting `go` automatically download modules as needed?

**Comment by stevesloka** [comment]
+1 on not requiring a local `vendor`. I think it came to be some some tooling was needed from the vendored deps.
