### ISSUE TITLE
come up with a plan for test improvements

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#3312]
We've talked about various ways that Contour's testing could improve. This is a meta-issue to do some R&D and come up with a proposal for a concrete set of improvements to make.

**Comment by youngnick** [comment]
Dropping some notes here from our discussion of this so we don't need to go hunting through them:

----

- Overlap between units/featuretests/integration
  - Originally featuretests were “e2e” validating Envoy config
  - How hard is it to track down a bug?
- Fix places where we’re using prod code to generate test cases etc.
- Action Item: Validate correct/incorrect assumptions about layers of testing
  - Break up layers?
  - Featuretests generate integration tests? (run once to check Envoy config, another to check actual responses to client)
  - How do we validate “wiring” is correct (i.e. cmd package coverage etc.)
- Are we committed to the current integration test framework?
  - The current integration tester works well
  - The fact that you have to learn Rego to add tests is a friction point, particularly for new contributors.
  - Is there a way we can use something like Go as the test driver (lower barrier to contributing integration tests)?
  - Consider use cases:
    - Changing contour config file
    - Have a better story for testing configured values do what we expect
      - Config file
      - On k8s resource
      - Etc.
    - How long does it take to add a test?
    - How long tests run for?
    - Upgrade testing, cooperation with the operator
- Operator sanity check in Contour controller repo?
  - Nightly build to check compatibility?

**Comment by skriss** [comment]
Moving to 1.14 milestone, I'm still working on this.

**Comment by sunjayBhatia** [comment]
was thinking about deploying contour with different params etc. in the integration tests, and was wondering what we thought about why we use the example manifests etc. for testing etc.

it's nice to validate they work but its maybe not the most flexible approach to test a lot of different features

some loose ideas:
- keep what we have, and add new tests that deploy different contours to test specific features not enabled by the base manifest
- maybe we actually unmarshal the yaml in the example manifests files and use those in the go e2e tests?
  - changes in the files would be tested in e2e suite
  - could use those unmarshalled types as a "base" set of objects for tests, copy and modify when we want to deploy something different
- the example manifests could be generated from go struct definitions in code that we use in the e2e tests as test fixtures?
- we could do something where we have a test that verifies some basic set of functionality with the base manifest and then others that deploy different contours to test different things, etc.

**Comment by sunjayBhatia** [comment]
Also, separate thread, would we ever want to encapsulate the deployment of our testing kind cluster in the e2e test suite? too much overhead?

we could still also allow you to supply config to reach out to an existing cluster as well

**Comment by skriss** [comment]
> was thinking about deploying contour with different params etc. in the integration tests, and was wondering what we thought about why we use the example manifests etc. for testing etc.
> 
> it's nice to validate they work but its maybe not the most flexible approach to test a lot of different features

Totally agree, it's easy in the short-term but long-term being able to manipulate the manifests as Go structs will be a lot easier. Whatever we do, we *should* still validate the final example manifests that we put in front of users though.

**Comment by youngnick** [comment]
I like the idea of unmarshalling the example manifests as part of the testing, that seems like a great way both to test them and to use them as the basis for things. We could also extend that to things like fixtures or similar, I think. Ideally there, we end up with a set of standard base things that we can then have test code mutate as required.

**Comment by skriss** [comment]
I think we've covered a lot of the highest priority items in this issue so I'm going to close this out. We can always come back to this in the future as needed.
