### ISSUE TITLE
Upstream Idle Connection Timeout Setting

### ISSUE THREAD

**Issue by sivakrishna-git** [projectcontour/contour#3313]
**Need to understand, is there any configurable upstream idle connection setting at contour:**

As per envoy proxy timeout settings [envoy timeouts](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts#connection-timeouts) , upstream idle connections  use the common_http_protocol_options field in the Cluster’s extension_protocol_options, keyed by envoy.extensions.upstreams.http.v3.HttpProtocolOptions,  didn't find any corresponding option at contour to override via httpproxy or contour configuration 

We have services running on tomcat application server in kubernetes and idle connections being closed by tomcat with  keepalive setting 20 sec but still envoy using those connections to send request resulting upstream_cx_destroy_remote_with_active_rq 503 error and tomcat is closing connections before envoy 

Route level timeoutPolicy idle timeout default 5m only dealing with active stream but not idle connections, we have tried with route level idle timeout to match tomcat keep alive settings but it is not working  and still there are upstream_cx_destroy_remote_with_active_rq 503 errors as  tomcat is closing connections before envoy 

Flow:  Client --> Envoy(Kubernetes)-->Tomact App(Kubernetes)  503 with upstream to envoy 

**We need to have some configurable setting for upstream idle connections via contour configuration or httpproxy, and please provide details on what is the envoy default upstream idle connection timeout value  and how we can override it from contour/httpproxy**

**Comment by skriss** [comment]
@sivakrishna-git you can customize the connection idle timeout via the Contour config file. See https://projectcontour.io/docs/v1.12.0/configuration/#timeout-configuration for more information.

**Comment by sivakrishna-git** [comment]
@skriss : we have tested connection-idle-timeout in Contour config file, it is only working for downstream , but not for upstream

Flow : Client(Down Stream) --> Envoy --> Tomcat(UpStream)

As per envoy documentation "The HTTP protocol idle timeout is defined in a generic message used by both the HTTP connection manager as well as upstream cluster HTTP connections. The idle timeout is the time at which a downstream or upstream connection will be terminated if there are no active streams. The default idle timeout if not otherwise specified is 1 hour. To modify the idle timeout for downstream connections use the common_http_protocol_options field in the HTTP connection manager configuration. To modify the idle timeout for upstream connections use the common_http_protocol_options field in the Cluster’s extension_protocol_options, keyed by envoy.extensions.upstreams.http.v3.HttpProtocolOptions"

Scenarios we have tested:

Client      Contour Idle Timeout   Route Idle Timeout       Tomcat
180 sec      default-60 sec                default- 5m               20 sec  ( Issue with both downstream and upstream idle connections)
180 sec           180 sec                      default- 5m               20 sec  (downstream no issue but upstream 503)
180 sec           180 sec                          20 sec                    20 sec  (downstream no issue but stream termination 408)
180 sec           180 sec                         180 sec                   180 sec (downstream no issue but upstream 503)         
180 sec           180 sec                         180 sec                   190 sec (downstream no issue but upstream 503) 
180 sec           180 sec                     default- 5m                300 sec (downstream no issue but upstream 503 with cx overflow)
180 sec           180 sec                     default- 5m                310 sec (downstream no issue but upstream 503 with cx overflow)

Can you please confirm,  at contour connection-idle-timeout default 60 sec in contour config file  overriding whether 
 downstream connection idle time out or upstream connection  idle timeout  and also as per our  testing upstream idle connections are never closing by envoy until upstream closes , can you please confirm if upstream idle timeout is disabled in contour instead 1 hr mentioned in envoy documentation because upstream_cx_idle_timeout metric always showing zero

**Comment by youngnick** [comment]
Hi @sivakrishna-git, we currently only set the `connect` timeout on upstream connections ( you can see for yourself in `internal/envoy/v3/cluster.go`. We do not pass through any other timeouts to the Cluster (the upstream config). So we do *not* disable the upstream idle timeout or change it in any way away from default (aside from any interaction it has with the downstream timeouts, I didn't check in detail in the Envoy timeout documentation).

I'll just run through what I understand is the problem, and you can confirm I've got it right, before we go on to talking about solutions.

You have a service behind Contour's Envoys.
Sometimes the connections are being closed by the service because they are idle.
When this happens, Envoy increments a metric saying it still had data to send down a connection that was closing.
Is that right?

So this is a problem between Envoy and the upstream, *not* between the client and Envoy. We already have configurability around that in the Route settings (which you've experimented with here).

Your suggestion is that you want to be able to configure the upstream idle timeout, presumably so that it's larger than the service's timeout, so that then you won't get the upstream 503s?

Does this produce user-visible 503s at the client, or is it the metric counter incrementing that you see?

**Comment by sivakrishna-git** [comment]
@youngnick yes you are right, it is the issue b/w envoy and the upstream , upstream_cx_destroy_remote_with_active_rq metric counter increasing as well as 503 being thrown from envoy to client,  it means it is visible at client side

Route level idle timeout only taking care of upstream active streams but not idle connections, In testing we have matched upstream keep alive setting with route level idle timeout  but it didn't work for us , still upstream closing connections and upstream_cx_destroy_remote_with_active_rq metric increasing with 503 thrown back to client

Yes my suggestion is we need ability to configure the upstream idle timeout at contour/envoy side so that envoy can close connections which are idle before upstream does and envoy do not use idle connections to send data,  at the upstream end we have service(tomcat application server) which has  keep alive timeout settings to close idle connections (keepAliveTimeout : The number of milliseconds this Connector will wait for another HTTP request before closing the connection)

Let say if upstream idle timeout we configured as 60 sec at contour/envoy side , and keepalive/idle timeout configured at upstream service as 61 sec , envoy wont use the connections idle from last 60 secs so that we will not get upstream 503

Let me know if you need any other details or if i am wrong

**Comment by youngnick** [comment]
Okay, thanks @sivakrishna-git.

It seems reasonable to me that we have a way to set the upstream connection idle timeout. I'm not sure how we will fit that into the API, but I agree we should look into it.

Anyone else have thoughts? @stevesloka @skriss @sunjayBhatia @danehans ?

**Comment by sivakrishna-git** [comment]
@youngnick : Any update on adding new field to set the upstream connection idle timeout.

**Comment by youngnick** [comment]
As I said previously, we will look into it when we can, but we haven't had a chance to prioritize this issue yet.

Of course, Contour is open-source, you or anyone could pick this work up. Whoever picks this up, I think the next steps are:
- make a plan for where to configure the upstream idle timeout (will probably need to be at the route level of HTTPProxy, but needs proper investigation)
- write either a design as a comment in this issue, or a design document as per the [proposal process](https://github.com/projectcontour/community/blob/main/GOVERNANCE.md#proposal-process)
- build out the support

**Comment by sivakrishna-git** [comment]
@youngnick I feel I am not right person to make changes or provide design for contour new feature as I don’t know  contour end to end architecture and I never did coding in  go language , can someone from contour team prioritize then propose design and make necessary changes please

**Comment by youngnick** [comment]
Thanks for that clarification @sivakrishna-git. We'll do our best to get this one prioritised, but I think there are a few other things ahead of it at the moment. We'll leave the `help-wanted` tag on here so that people can pick it up, I think the direction is pretty clear.

**Comment by Legion2** [comment]
we get 503 errors every day and need a way to configure the idle timeout per upstream service

**Comment by youngnick** [comment]
@Legion2, do you need to have different timeouts per backend service, or would configuring a timeout per route (which holds multiple services that service the same thing) work?

**Comment by Legion2** [comment]
no a timeout per route is enough. I also found [`TimeoutPolicy`](https://projectcontour.io/docs/v1.16.0/config/api/#projectcontour.io/v1.TimeoutPolicy) which can be configured per route. However, it does not allow to configure the idle timeout for upstream connections.

As a workaround I use the `RetryPolicy` with `RetryOn` `reset` to retry when there was an idle timeout by the upstream service. I have to wait and see if this fixes out problems.

**Comment by youngnick** [comment]
Sorry about the delay in replying @Legion2, I think that lines up with the idea about putting this at route-level, along with the test of the TimeoutPolicy. That means that this one is ready to be worked on whenever someone can pick it up.

**Comment by tsaarni** [comment]
I'm wondering about having this as route-level setting.  Like @sivakrishna-git pointed out [here](https://github.com/projectcontour/contour/issues/3313#issuecomment-773735780), upstream setting goes into `Cluster` message instead of `Route`. How should it be sorted out when two `HTTPProxies` have conflicting TimeoutPolicy settings, but point to the same upstream service?

**Comment by sivakrishna-git** [comment]
@tsaarni : Please update documentation https://projectcontour.io/docs/main/config/request-routing/#response-timeouts as well

**Comment by tsaarni** [comment]
Thanks @sivakrishna-git It is documented in the API section https://projectcontour.io/docs/main/config/api/#projectcontour.io/v1.TimeoutPolicy but I missed the guides. I'll update that too.
