### ISSUE TITLE
Removing default node-pool on GKE also removes Contour

### ISSUE THREAD

**Issue by fletcherist** [projectcontour/contour#3315]
**What steps did you take and what happened:**
I'm trying to move my workloads to another node-pool, and the problem is when I remove default node-pool, it also removes contour and envoy, so load balancer and proxy stops working. So my question is how to migrate Contour to another node-pool without downtime?

**What did you expect to happen:**
1. Create cluster on GKE with **default** node-pool
2. Install Contour via `kubectl apply -f https://projectcontour.io/quickstart/contour.yaml`
3. Create another **node-pool-2**
4. Migrate workloads to **node-pool-2**
5. Scale **default** node-pool to 0
6. Load balancer stops working
7. Scale **default** node-pool to 1
8. Everything's fine

**Environment:**

- Contour version: latest
- Kubernetes version: v1.17.15-gke
- Cloud provider or hardware configuration: GKE

**Comment by fletcherist** [comment]
Is there somehow connected with node-affinity or something like in this [config](https://github.com/projectcontour/contour/blob/main/examples/contour/03-contour.yaml)

**Comment by fletcherist** [comment]
actually it seems `deployment.apps/contour` is deployed on both node-pools, but `daemonset.apps/envoy` is only deployed on default one, because it's size is equal to default node-pool size

**Comment by youngnick** [comment]
We don't specify anything in the YAMLs about how the Envoy DaemonSet is placed, so I suspect this is some GKE weirdness. According to the YAML we provide, the DaemonSet should run across **all nodes**

I'd guess that you then may have to do something with the Envoy Service to make the magic LoadBalancer move to the new node group.

**Comment by fletcherist** [comment]
Okay thx for clear explanation, I decided to create new cluster and migrate workloads between new cluster's default pool and old one.

However, I'll try to research the problem with GKE and Envoy's DaemonSet in test environment and will come back with some more information. Close this for now
