### ISSUE TITLE
_integration test 018 (external name) is failing

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#3320]
The external name integration test (018) has started failing:

https://github.com/projectcontour/contour/runs/1834673548?check_suite_focus=true

```
not ok 12 - running Rego check lines ./_integration/testsuite/httpproxy/018-external-name-service.yaml:63-78
  ---
  - Message: |-
      raised predicate "check_for_status_code"
      got status 301, wanted 200
    Severity: Error
    Timestamp: "0001-01-01T00:00:00Z"
  
  ...
```

**Comment by sunjayBhatia** [comment]
Instead of using an actual external service to the local `kind` cluster, could we deploy a service as part of the test and just use an ExternalName service to point to the DNS name?

**Comment by skriss** [comment]
> Instead of using an actual external service to the local `kind` cluster, could we deploy a service as part of the test and just use an ExternalName service to point to the DNS name? Does that work/capture what we're attempting to test?

Yeah that's a good idea, I think that should work just fine and removes the dependency on any external domain; trying it out now.
