### ISSUE TITLE
support envoy listener exact balancer

### ISSUE THREAD

**Issue by iyacontrol** [projectcontour/contour#3331]
A connection balancer implementation that does exact balancing. This means that a lock is held during balancing so that connection counts are nearly exactly balanced between worker threads. This is “nearly” exact in the sense that a connection might close in parallel thus making the counts incorrect, but this should be rectified on the next accept. This balancer sacrifices accept throughput for accuracy and should be used when there are a small number of connections that rarely cycle (e.g., service mesh gRPC egress).

**Comment by youngnick** [comment]
Thanks for logging this issue @iyacontrol.

So, the issue that this fixes for you is that you have long-running, processor-expensive connections running through Envoy, and you want to be able to ensure that they end up evenly spread across Envoy's worker threads?

This seems reasonable, but just want to make sure I haven't misunderstood.

**Comment by iyacontrol** [comment]
> Thanks for logging this issue @iyacontrol.
> 
> So, the issue that this fixes for you is that you have long-running, processor-expensive connections running through Envoy, and you want to be able to ensure that they end up evenly spread across Envoy's worker threads?
> 
> This seems reasonable, but just want to make sure I haven't misunderstood.

@youngnick  Thanks for your reply, your understanding is correct.

**Comment by iyacontrol** [comment]
> > Thanks for logging this issue @iyacontrol.
> > So, the issue that this fixes for you is that you have long-running, processor-expensive connections running through Envoy, and you want to be able to ensure that they end up evenly spread across Envoy's worker threads?
> > This seems reasonable, but just want to make sure I haven't misunderstood.
> 
> @youngnick Thanks for your reply, your understanding is correct.

There should be many users who use grpc like our company，grpc has long-running, processor-expensive connections. 

It is necessary to support envoy listener exact balancer.

**Comment by skriss** [comment]
This was closed by #3314, yes?

**Comment by iyacontrol** [comment]
> This was closed by #3314, yes?

 i think it can be closed.
