### ISSUE TITLE
HTTPRouteForwardTo.Port should be optional 

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3352]
When defining a HTTPRouteForwardTo on an HTTPRoute, the Port should be optional. 

> Port specifies the destination port number to use for the backend referenced by the ServiceName or BackendRef field. If unspecified, the destination port in the request is used when forwarding to a backendRef or serviceName. 

// ref: https://kubernetes-sigs.github.io/service-apis/spec/#networking.x-k8s.io/v1alpha1.HTTPRouteForwardTo

**Comment by abhide** [comment]
The above links seems to be broken; here is the correct link
https://pkg.go.dev/sigs.k8s.io/gateway-api@v0.2.0/apis/v1alpha1#HTTPRouteForwardTo

**Comment by abhide** [comment]
@stevesloka Any objections if I start working on this ticket?

**Comment by stevesloka** [comment]
@abhide we need to come together on a resolution on this (https://github.com/kubernetes-sigs/gateway-api/issues/578) before tackling this issue first to understand the logic needed (i.e. port required with serviceName, but not with backedRef).

**Comment by skriss** [comment]
Looks like in v1alpha2 this has been clarified such that port is required if referencing a service:
https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.BackendObjectReference

> Port specifies the destination port number to use for this resource. Port is required when the referent is a Kubernetes Service. For other resources, destination port might be derived from the referent resource or this field.

So I think we can close this out since we'll be moving to v1alpha2 soon.
