### ISSUE TITLE
Validation for hostnames

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3353]
Need to validate each hostname The first phase of hostname validation can be:

- Ensure the hostname is not an IP address. xref: https://golang.org/pkg/net/#ParseIP
- Ensure the hostname does not contain a port. xref: https://golang.org/pkg/net/#SplitHostPort

As a second phase, the hostname spec states "Hostname is the fully qualified domain name of a network host, as defined by RFC 3986." We should be able to use https://golang.org/pkg/net/?m=all#isDomainName (verify that it supports wildcard prefixes or augment to support wildcards).

> Hostnames defines a set of hostname that should match against the HTTP Host header to select a HTTPRoute to process the request. Hostname is the fully qualified domain name of a network host, as defined by RFC 3986. Note the following deviations from the “host” part of the URI as defined in the RFC:

    IPs are not allowed.
    The : delimiter is not respected because ports are not allowed.

Incoming requests are matched against the hostnames before the HTTPRoute rules. If no hostname is specified, traffic is routed based on the HTTPRouteRules.

Hostname can be “precise” which is a domain name without the terminating dot of a network host (e.g. “foo.example.com”) or “wildcard”, which is a domain name prefixed with a single wildcard label (e.g. “.example.com”). The wildcard character ‘’ must appear by itself as the first DNS label and matches only a single label. You cannot have a wildcard label by itself (e.g. Host == “”). Requests will be matched against the Host field in the following order: 1. If Host is precise, the request matches this rule if the http host header is equal to Host. 2. If Host is a wildcard, then the request matches this rule if the http host header is to equal to the suffix (removing the first label) of the wildcard rule.

// ref: https://kubernetes-sigs.github.io/service-apis/spec/#networking.x-k8s.io/v1alpha1.HTTPRoute
// ref: https://github.com/projectcontour/contour/pull/3278#discussion_r574180711

**Comment by sunjayBhatia** [comment]
Do we have to do this ourselves? Does the `HTTPRoute` CRD already have some admission/validation logic like `Ingress` does for hostnames?

**Comment by danehans** [comment]
> Do we have to do this ourselves? Does the HTTPRoute CRD already have some admission/validation logic like Ingress does for hostnames?

@sunjayBhatia the API validation of this field is pretty basic, xref: https://github.com/kubernetes-sigs/gateway-api/blob/v0.2.0/apis/v1alpha1/shared_types.go#L218-L219. Implementations will need to perform additional validation to meet the spec.
