### ISSUE TITLE
Implement RouteTLSConfig as Secrets

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3355]
Allow an HTTPRoute to specify a `RouteTLSConfig` which is defined by a `certificateRef`. Contour should implement the `secrets` type by having users omit or specifies an empty string for both the group and kind. 

<img width="334" alt="image" src="https://user-images.githubusercontent.com/1048184/107704802-d6818b00-6c8b-11eb-8c25-1d5cd81d8eb9.png">

// ref: https://kubernetes-sigs.github.io/service-apis/spec/#networking.x-k8s.io/v1alpha1.RouteTLSConfig

**Comment by skriss** [comment]
See https://github.com/projectcontour/contour/issues/3439#issuecomment-900594308, closing this one out.
