### ISSUE TITLE
Implement "Exact" HTTPHeaderMatch

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3356]
For an HTTPRoute, need to implement the "Exact" `HTTPHeaderMatch` on a `HTTPRouteRule.HTTPRouteMatch`.

// ref: https://kubernetes-sigs.github.io/gateway-api/spec/#networking.x-k8s.io/v1alpha1.HTTPHeaderMatch

**Comment by youngnick** [comment]
Updated the link in the OP.

This is core support, and so must be part of our initial HTTPRoute implementation.
