### ISSUE TITLE
Gateway API: "RegularExpression" HTTPHeaderMatch [custom]

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3357]
For an HTTPRoute, need to implement the "RegularExpression" `HTTPHeaderMatch` on a `HTTPRouteRule.HTTPRouteMatch`.

**TODO: Determine regex type to implement & document properly**

> Since RegularExpression PathType has custom conformance, implementations can support POSIX, PCRE or any other dialects of regular expressions.

// ref: https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.HTTPHeaderMatch

**Comment by youngnick** [comment]
I updated the link to the docs, since the upstream rename happened already.

Because this is "custom conformance", we don't need to implement this at first (or at all, if we don't want to). So this one should go lower on the priority list.

**Comment by dsvetl** [comment]
Hello,

Any movement on this issue?

**Comment by skriss** [comment]
@dsvetl given that this feature is "custom conformance" this is not currently high on our priority list, but if you're interested in contributing here let us know and we can help out as needed!
