### ISSUE TITLE
POD Cluster IP range is not in RFC1918 and internal http headers are getting sanitized

### ISSUE THREAD

**Issue by ag3man** [projectcontour/contour#3365]
**What steps did you take and what happened:**

- POD cidr range 100.96/16
- Deploy contour with ingress to access internal http service
- routing to service works however remoteIP = 100.96.x.x
- XFF headers are completely missing.
`{"Id":234,"Message":"Hello!","Created":"2021-02-16T18:32:15.5400843-05:00","Request":{"Url":"http://xxxxl/api/public/test","Authority":"http://fxxxx,"IsHttps":false,"RemoteIP":"100.96.15.2","Headers":[]}}`

**What did you expect to happen:**
- I expect to see XFF headers
- have the ability to set an annotation to easily enable use_remote_address

**Anything else you would like to add:**

I found this on the envoy website https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy[…]onfig

```
internal_address_config 
(extensions.filters.network.http_connection_manager.v3.HttpConnectionManager.InternalAddressConfig) Configures what network addresses are considered internal for stats and header sanitation purposes. If unspecified, only RFC1918 IP addresses will be considered internal. See the documentation for x-envoy-internal for more information about internal/external addresses.
```
So I suspect since my POD cidr range is 100.96/16 It is getting sanitized.
I see the XFF in the envoy logs just trying to get them to appear on upstream.

**Environment:**

- Contour version:  v0.11.0
- Kubernetes version: (use `kubectl version`): 1.20+
- Kubernetes installer & version:
- Cloud provider or hardware configuration: AWS with NLB
- OS (e.g. from `/etc/os-release`): amazon linux 2

**Comment by youngnick** [comment]
sorry @ag3man, you have the pod CIDR as 10.96/16, did you mean 100.96/16?

**Comment by youngnick** [comment]
I think that to solve this, we may need a way to let you add ranges into the internal address ranges, we will need to figure out how to do that.

**Comment by ag3man** [comment]
@youngnick  Yes **100.96.0.0/16** is the CIDR. I missed a zero. I have updated it now.

i am looking at a way that I can use --config-yaml to override he default dynamic configuration somehow. Any ideas on how I could do this?

Also looking at this bug. I would not think this is a bug, but more of a feature request. What are your thoughts?

**Comment by youngnick** [comment]
I agree that this is a feature request, with the feature being the ability to add ranges to the "internal" set for Envoy. That seems like a reasonable first pass to me, with an obvious extension being the ability to specify *all* the valid ranges, in case you want to remove some or all of RFC1918. I wouldn't want to do the extension without a pretty good use case though.

But I think just allowing extra CIDRs to be added to the internal list would cover you, right @ag3man ?

**Comment by ag3man** [comment]
@youngnick  Yes. this is correct. Is there any thing I can do at this current time to patch my deployment?

**Comment by youngnick** [comment]
Sorry, I don't think so, it will require a patch to Contour, as the config is sent to Envoy from Contour.
