### ISSUE TITLE
siteproof: External URL checks are flaky, causing us to disable checking some sites

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#3384]
We have had to disable external URL checks for various sites we link to because the siteproof CI job is flaky accessing these resources (see: https://github.com/projectcontour/contour/pull/3382). This may cause documentation to have broken links without us knowing since we skip some important sites (https://www.envoyproxy.io/ being an especially important one).

Let's see if we can improve the siteproof CI check to make it so we don't keep expanding the unchecked external URLs in the Contour site.

Some initial ideas:
- Separate the internal and external link checks into separate runs of `htmlproofer` using `--disable_external` and `external_only ` flags
- Figure out some more advanced configuration to check external links
- Find another tool to check external links

**Comment by skriss** [comment]
Closing this one out too since with the migration to Hugo we dropped the siteproof job.
