### ISSUE TITLE
testing: run integration tests against all supported Kubernetes versions

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#3396]
Per https://projectcontour.io/resources/compatibility-matrix/, each version of Contour is considered compatible with three minor Kubernetes versions. However, our integration tests tend to run only against the latest version (based on whatever image the version of kind that we're using pulls by default).

We should add runs of the tests against the other two versions as well. Personally, I'd be OK with this starting as a nightly job, as I don't know that we *need* to run against all versions for every PR. Open to other inputs on this though.

**Comment by stevesloka** [comment]
Shouldn't be too much effort to enable this and would be good to have the validation running against all the versions. Some of the support policy idea was that our dep on client-go offered that support (i.e. three versions back), so leaning on that pushed the "validation" effort off to that project.

**Comment by youngnick** [comment]
Yes, the original intent was that we lean on client-go's support. But we're doing complicated enough stuff now that it's better than we make sure by testing ourselves.

**Comment by skriss** [comment]
cc @youngnick @xaleeks I'd like to get this done as part of 1.14, moving it into the milestone. Let me know if you disagree.
