### ISSUE TITLE
Add direct responses support

### ISSUE THREAD

**Issue by iyacontrol** [projectcontour/contour#3403]
Envoy supports the sending of “direct” responses. These are preconfigured HTTP responses that do not require proxying to an upstream server.

[the envoy docs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_routing#arch-overview-http-routing-direct-response)

**Comment by skriss** [comment]
dupe of #2515

**Comment by youngnick** [comment]
Thanks for this issue, @iyacontrol, I'll close this one though, since I agree that #2515 is asking for the same feature. Please watch that one for updates.
