### ISSUE TITLE
Distroless Contour

### ISSUE THREAD

**Issue by xaleeks** [projectcontour/contour#3429]
Adjacent to the FIPS compliance requirements that we’re currently exploring is a possible improvement to provide Contour in distroless format at some time in the future.  Please see https://github.com/GoogleContainerTools/distroless

This can help us
Reduce surface attacks (CVEs, security issues, updates)
Reduce image size - speed up download
Lessen support contracts 

This is a request to investigate a path to distroless and figure out if our container images include more than what’s necessary to run our app.  There’s going to be a tradeoff between ease of development and running containers with package managers and extra bits vs size/security.  

Xref https://github.com/envoyproxy/envoy/issues/5325
Xref https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/1729-rebase-images-to-distroless/README.md

**Comment by sunjayBhatia** [comment]
We are already providing only the contour binary on top of `scratch`: https://github.com/projectcontour/contour/blob/3502314c0fc40e62218938c173ab718dad72809c/Dockerfile#L34

**Comment by youngnick** [comment]
Yes, I don't see any point to moving to distroless when we already base from scratch.

**Comment by stevesloka** [comment]
I agree with @youngnick & @sunjayBhatia that our base image is as secure as it can be at the moment. Please reopen @xaleeks if you have a different idea in mind in regards to the distroless image.
