### ISSUE TITLE
Support RouteTLSConfig on HTTPRoute

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3439]
Support TLS on an HTTPRoute by implementing the `RouteTLSConfig`.

>TLS defines the TLS certificate to use for Hostnames defined in this Route. This configuration only takes effect if the AllowRouteOverride field is set to true in the associated Gateway resource.

>Collisions can happen if multiple HTTPRoutes define a TLS certificate for the same hostname. In such a case, conflict resolution guiding principles apply, specifically, if hostnames are same and two different certificates are specified then the certificate in the oldest resource wins.

>Please note that HTTP Route-selection takes place after the TLS Handshake (ClientHello). Due to this, TLS certificate defined here will take precedence even if the request has the potential to match multiple routes (in case multiple HTTPRoutes share the same hostname).

//ref: https://gateway-api.sigs.k8s.io/spec/#networking.x-k8s.io/v1alpha1.RouteTLSConfig

**Comment by skriss** [comment]
Per https://github.com/projectcontour/contour/issues/3404#issuecomment-899982896, configuring TLS on HTTPRoutes is being dropped in `v1alpha2` so there's no point in implementing this now. Closing out.
