### ISSUE TITLE
Set Status on TCPRoute

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3441]
It's been stated that `projectcontour/contour` won't support `TCPRoute` in gateway-api. Currently, Contour doesn't watch for those types of resources, but thinking maybe we should and set an invalid (or `Rejected`) status on those objects in the event someone does setup a TCPRoute with a Contour Gateway and expects something to happen, but nothing ever does. 

//ref: https://gateway-api.sigs.k8s.io/spec/#networking.x-k8s.io/v1alpha1.TCPRoute

**Comment by sunjayBhatia** [comment]
I think that is a good idea and what the status seems to be intended for (and should probably be the same for UDPRoute)

https://gateway-api.sigs.k8s.io/spec/#networking.x-k8s.io/v1alpha1.RouteGatewayStatus

```
Conditions describes the status of the route with respect to the Gateway.The “Admitted” condition must always
be specified by controllers to indicate whether the route has been admitted or rejected by the Gateway, and
why. Note that the route’s availability is also subject to the Gateway’s own status conditions and listener
status.
```

**Comment by stevesloka** [comment]
Good call on the UDP Route, I'll add another issue for that. =)

**Comment by youngnick** [comment]
Yes, I agree, we should definitely be adding a status saying that Contour does not support Routes when they are referenced.
