### ISSUE TITLE
Add the possibility to delete or set headers only on the mirrored request

### ISSUE THREAD

**Issue by andream16** [projectcontour/contour#3444]
Hi everyone.

I was looking at [Traffic Mirroring](https://projectcontour.io/docs/main/config/request-routing/#traffic-mirroring) and I was trying to see if it's possible to remove headers only for the mirrored request leveraging [Header Rewriting](https://projectcontour.io/docs/main/config/request-rewriting/#header-rewriting).

The use case is the following:

- I want to mirror all requests on a certain `fqdn` and on routes with a prefix `/` for analytics purposes
- I want to remove the `X-Authorization` header (for example) only to the requests that get mirrored and not from the ones that go to the target downstream service

I tried to look around but haven't found any way of achieving this. When using `remove` the targeted header is removed from both downstream and mirrored request.

I think this would make sense to not leak particular headers in the mirrored request ingestors.

**Comment by xaleeks** [comment]
Can you sanitize the request after it arrives in the mirror’ed upstream service itself.  I assume you tried stuffing the `requestHeadersPolicy` stanza under the mirror service and it didn’t work? Did it end up removing the header from requests to both services even though you specified it under the mirror one only?  

If that's the case, it seems like a reasonable request, and we should call out it’s not available to mirror services in the docs for the time being.

**Comment by xaleeks** [comment]
documentation around extent of interaction of mirroring and other mechanisms in contour docs is a bit lacking overall.

**Comment by andream16** [comment]
> Can you sanitize the request after it arrives in the mirror’ed upstream service itself

Yes, that's what I did at the end. I'd say that removing it before hand would be a nice solution.

> I assume you tried stuffing the requestHeadersPolicy stanza under the mirror service and it didn’t work? Did it end up removing the header from requests to both services even though you specified it under the mirror one only?

Yeah, tried a bunch of things and the header was removed from both requests going upstream & to the mirror service.

> If that's the case, it seems like a reasonable request, and we should call out it’s not available to mirror services in the docs for the time being.

That makes sense. I would be happy to add it myself 😃

**Comment by youngnick** [comment]
I think the request is reasonable, but how we expose it needs a little thought. So it should end up on the roadmap, but as always, input welcomed. :)

Any solution needs to define:
- How do we tell when to remove a header just for a mirrored service?
- What does the YAML and HTTPProxy structure look like?

Once we have a design for how we can expose the config, then the implementation should be relatively straightforward.

A docs PR in the interim would be extremely welcome though @andream16!
