### ISSUE TITLE
https://projectcontour.io/ not available for few days already

### ISSUE THREAD

**Issue by DmitryBrus** [projectcontour/contour#3451]
I know that it is not definitely a bug of contour,
but its site https://projectcontour.io/ (and installation as well) not available, somebody knows what happened, where to track the status?

**Comment by youngnick** [comment]
Thanks for logging this @DmitryBrus.

Looks like this was caused by human error during a migration of the domain ownership. It's been fixed now, we'll discuss what to do about this for the future at the next maintainer meeting and report back here.

**Comment by DmitryBrus** [comment]
@youngnick thank you for response, we were kind of stuck while downtime.

**Comment by youngnick** [comment]
Looks like there's not much action or us to take on this one, aside from making sure that DNS transfers are done carefully in the future.
