### ISSUE TITLE
Continuous stream of "handling v3 xDS resource request" messages in logs

### ISSUE THREAD

**Issue by furdarius** [projectcontour/contour#3483]
Would it be possible to add setting to adjust log level for logrus, as it was suggested in https://github.com/projectcontour/contour/issues/556

Or get rid of `handling v3 xDS resource request` info message in code?

I'm asking because in our setup with x12 Envoy instances and many routes in several HTTPProxy, we have a continuous stream of `handling v3 xDS resource request` messages in logs.

https://github.com/projectcontour/contour/blob/80f1f7483a2b65013021e131327daa79b723f6db/internal/xds/v3/callbacks.go#L57

It's quite costly when using Google's stackdriver to store logs and makes `kubectl logs -f` unusable.

**Comment by youngnick** [comment]
Those log lines should probably be Debug level, I think, which would turn them off unless you ask for them. Thoughts @stevesloka @skriss @sunjayBhatia @danehans ?

**Comment by sunjayBhatia** [comment]
I would be ok with moving it to debug level, when I’ve debugged in the past I don’t usually use this log line much myself

Do we have a method of dynamically changing log level without restarting Contour? That could make this decision easier as well

**Comment by sunjayBhatia** [comment]
Doesn’t seem like we have anything here https://github.com/projectcontour/contour/blob/80f1f7483a2b65013021e131327daa79b723f6db/internal/debug/debug.go#L35

**Comment by sunjayBhatia** [comment]
https://github.com/projectcontour/contour/issues/3491

**Comment by stevesloka** [comment]
Yeah fine to turn off. Would be nice to be able to turn on for an instance of Contour to debug.

**Comment by skriss** [comment]
+1 for both changes
