### ISSUE TITLE
shutdown manager uses hardcoded admin port

### ISSUE THREAD

**Issue by patrickshan** [projectcontour/contour#3490]
**What steps did you take and what happened:**
we use customised admin port for our envoy pod through [--admin-port](https://github.com/projectcontour/contour/blob/64db9081049afb968b24be94541cadf074fd75ad/cmd/contour/bootstrap.go#L30) but it seems shutdown manager uses [ hardcoded port 9001](https://github.com/projectcontour/contour/blob/main/cmd/contour/shutdownmanager.go#L33) which causes problem during graceful shutdown.

**What did you expect to happen:**
shutdown manager should also take the same admin port or at least configurable.

**Environment:**

- Contour version: all version seems to be impacted including latest v1.13.1
- Kubernetes version: v1.19.7
- Cloud provider or hardware configuration: AWS
- OS: Flatcar OS

**Comment by stevesloka** [comment]
Yup you're correct @patrickshan. Might need a flag to shutdown manager to let you customize.

**Comment by alessandroargentieri** [comment]
Hi, how to assign it to myself?

**Comment by skriss** [comment]
@alessandroargentieri assigned!
