### ISSUE TITLE
Missing TLS protocol option for ExtensionServiceSpec

### ISSUE THREAD

**Issue by arthurlm** [projectcontour/contour#3497]
I am trying to create an extension service using TLS protocol option as it is explain in doc:
https://github.com/projectcontour/contour/blob/da72199674433376bda89d5ad48ec53e2c87cb92/apis/projectcontour/v1alpha1/extensionservice.go#L80

However it is not available in spec:
https://github.com/projectcontour/contour/blob/da72199674433376bda89d5ad48ec53e2c87cb92/apis/projectcontour/v1alpha1/extensionservice.go#L83

And it does not work using service annotation: `projectcontour.io/upstream-protocol.tls: 9443`

Is it possible to add missing protocol option ? Or should we remove tls option from doc ?

**Comment by stevesloka** [comment]
Hey @arthurlm, what are you looking to use the ExtensionService for? 

Right now Contour utilizes that for gRPC services for External Authentication as well as RateLimiting, which are all done over `h2` or `h2c`. But the idea was to make it a generic service integration point so I'm curious what you're trying to setup.

**Comment by arthurlm** [comment]
Hi @stevesloka,
I am trying to do an External Authentication service using gRPC.

However, for now it does not work because my HTTP2 server failed on parsing authority header field.
See this issue: https://github.com/hyperium/h2/issues/525
This is why I was trying to use `tls` protocol option.

Please note that gRPC and HTTP2 are still quite new to me.
So probably using HTTP1 for gRPC is not possible and this option in the doc is the source of my misunderstanding.

**Comment by sunjayBhatia** [comment]
CI failure can be ignored, should be fixed by https://github.com/projectcontour/contour/pull/3521
