### ISSUE TITLE
Secret validation duplicated in cache & dag layers

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3503]
We sanitize secrets when they arrive at the cache layer (https://github.com/projectcontour/contour/blob/main/internal/dag/secret.go#L34:6), however, that logic is duplicated in the dag package (https://github.com/projectcontour/contour/blob/main/internal/dag/accessors.go#L225). 

I theory we should be able to rely on the secrets being valid from the cache bit, but in any case should centralize this logic so we don't get differing results on what is valid or not.

**Comment by alessandroargentieri** [comment]
Hi @stevesloka may I try to manage this? Do you suggest keeping the secret validation in the cache layer or moving away from both and externalize it in another file or package?

**Comment by khayyamsaleem** [comment]
Looks like this issue is still here; @alessandroargentieri if you're alright with it, may I take it up? I would suggest extracting this into a `validators.go` in the `dag` package.

**Comment by alessandroargentieri** [comment]
Sure @khayyamsaleem I'll work on it as you suggested
