### ISSUE TITLE
[TLS] ca.crt from `kubernetes.io/tls` secret is not served

### ISSUE THREAD

**Issue by echupriyanov** [projectcontour/contour#3509]
I have a question regarding HTTPS Ingress serving using Contour as Ingress Controller.
I have created proper `kubernetes.io/tls` type secret, containing `tls.key`, `tls.crt` *and* `ca.crt` files.
But when I check for certificates presented by Ingress, I see only server's certificate `tls.crt` presented, but no CA chain certificates from `ca.crt`.

Is this correct behavior? Is it possible to tune Contour/Envoy to also present `ca.crt` certificates to clients?

Currently using v1.11 of Contour, deployed using Helm chart `bitnami/contour`

**Comment by echupriyanov** [comment]
Looks like as a workaround I can concatenate `ca.crt` to `tls.crt` and use resulting chain as `tls.crt`. But I think it would be more idiomatic for Contour to make this concatenation on user's behalf

**Comment by youngnick** [comment]
The way we handle the `ca.crt` value in TLS secrets is a little weird, agreed, and it would be worth fixing up.
However, there are a couple of places where we look for a separate secret, so we may need to check those.
Next steps here:
- Check to see if there's anything special we need to so that we don't break the current setup.
- Implement checking the `ca.crt` field of TLS secrets if it's not empty.

**Comment by tsaarni** [comment]
Doesn't type [kubernetes.io/tls](https://github.com/kubernetes/api/blob/5d0d5b56b51109a75225966be27ca7b6c6ca6dcd/core/v1/types.go#L5899) currently officially only define fields `tls.key` and `tls.crt`?  Creating secret via `kubectl create secret tls` does not give an option to upload more than those, though it is possible by creating the secret by some other means.

I think it is quite common procedure to configure chain certs by appending them to the server cert PEM file and I wouldn't consider that as a workaround - It is a "PEM bundle" file where the first item needs to be the server cert itself, and next items is the chain of intermediate CA certificates up to (but not including) the root CA certificate, listed in the order from end-entity towards the root.  I think this should be the documented procedure?

Envoy also consumes server certificates as `certificate_chain` https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#extensions-transport-sockets-tls-v3-tlscertificate

**Comment by youngnick** [comment]
Those are all good points, thanks @tsaarni! You're right about `kubuernetes.io/tls` secrets, but I think we need to get the documentation updated to recommend certificate chaining for CA certs, just to make it clear for people who haven't done that before.
