### ISSUE TITLE
DOC - Healthz of Envoy Pod

### ISSUE THREAD

**Issue by Berndinox** [projectcontour/contour#3513]
Hy,

i've read: https://projectcontour.io/guides/health-checking/

However, i dont find any examples, so i tried:

- Add Port to Envoy Daemonset
- Add Port to LB SVC

I cant reach LB-IP:8000/healthz

Any examples available?

**Comment by youngnick** [comment]
Thanks for this issueu @Berndinox. From what you're saying, it seems you want to health-check the Envoys?

Internally, we use the port `8002`, with a path of `ready` for health-checking Envoy itself, but exposing this to the world means also exposing your stats, as the two share a port. I'd be careful about using this for health-checking Envoy for this reason.

I'd actually recommend using the HTTP or HTTPS port for health-checking Envoy, as if that port is open, then Envoy is ready to listen and is fully configured.

**Comment by Berndinox** [comment]
Thanks for clarification!

**Comment by youngnick** [comment]
No problem. Does this close out your question?

**Comment by stevesloka** [comment]
@Berndinox just to clarify a bit from what @youngnick said, checking against the open port is fine to know if Envoy is listening, but if you had to roll the Envoy pod that's where you'd want to check against `/ready` which will return a 5XX error in the event that Envoy is shutting down and the listeners are draining. The `shutdown-manager` in the Envoy pod helps out with this to wait for the SIGTERM from k8s, but before allowing the Envoy pod to terminate, it sets Envoy to a draining state to move off your existing connections. 

In this event you'd want that instance of Envoy to fail its health checks with your load balancer and shift traffic away to avoid having dropped connections. 

There's no reason we couldn't add another listener to manage the health check `/ready` endpoint to allow this to be exposed but not your metrics which is probably a good idea to do anyway, we have the same settings for Contour on it's health check endpoint.
