### ISSUE TITLE
Configurable option for TLS version between envoy and contour

### ISSUE THREAD

**Issue by movikbence** [projectcontour/contour#3518]
Hi

I asked a question on slack, if it is possible to set the minimum version of TLS between envoy and contour. I got that answer that in the moment it is not. I think it would be nice to have that.

Thank you for taking into consideration.

Br,
Bence

**Comment by youngnick** [comment]
This seems like a reasonable feature. Out of curiosity @movikbence, what do you want to set the TLS version to?

**Comment by movikbence** [comment]
since that is is 1.2 now, I would like to have 1.3

**Comment by youngnick** [comment]
This is definitely a reasonable feature, so I'll mark it as a "help-wanted" one. Thanks for this request @movikbence!

**Comment by tsaarni** [comment]
Would some users need still TLS 1.2 or would it be possible to go with TLS 1.3 only, without configurability? As long as we are serving only Envoy's, forcing TLS 1.3 as minimum could work as well for any (reasonable) version of Envoy?

Also, xref #3574 #4024 that looks for global TLS settings.

**Comment by youngnick** [comment]
That's a great point, and worth doing, as long as we document the new cipher requirements TLS 1.3 brings.
