### ISSUE TITLE
Refactor: Move Type specific (e.g. Ingress) helpers out of annotation package

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#3532]
https://github.com/projectcontour/contour/pull/3520 adds the `internal/validation/ingress` package that is used to house helpers used for validation of Ingress resources, e.g. if they match an IngressClass name etc.

We could extend this pattern for other resources.

We already have the `internal/annotation` package with helpers for getting annotations from resources and for doing some checks on the values of annotations/validation etc.

This issue is for starting to consolidate the various places we have these sorts of helpers.

Ideas:
- use `internal/annotation` as a helper package for fetching annotation values but leave type or annotation specific bits to a separate package, possibly in `internal/validation`

**Comment by youngnick** [comment]
That's a big +1 from me.
