### ISSUE TITLE
gateway all namespace selector test wrong

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3536]
The test for validating the Gateway.Spec.Listeners.Routes.Namespaces.From: RouteSelectAll is incorrect. Currently the test (https://github.com/projectcontour/contour/blob/main/internal/dag/builder_test.go#L440), expects no listeners to be created, but if the Gateway is selecting routes from All namespaces then this test should return a set of listeners since the selector matches all routes. 

The test is passing as-is because the service used in the forwardTo is in a different namespace than the Route causing the route to be rejected which is correct, but not testing the intent of this test.

**Comment by skriss** [comment]
@stevesloka this was fixed by #3537 right? I think the issue link in the PR was typo'd.

**Comment by stevesloka** [comment]
Yup you are correct @skriss, thanks for following up on this.
