### ISSUE TITLE
Upgrade instructions for upgrades to 1.14.0 miss out a vital step causing downtime

### ISSUE THREAD

**Issue by yoitsro** [projectcontour/contour#3541]
**What steps did you take and what happened:**
I tried to upgrade my deployment to 1.14.0 following the steps mentioned here: https://projectcontour.io/resources/upgrading/#the-less-easy-way

All my endpoints became unresponsive.

**What did you expect to happen:**
I expected all my endpoints to stay up and responsive.

**Anything else you would like to add:**
This is due to a port change as part of this PR: https://github.com/projectcontour/contour/pull/3393

**Environment:**

- Contour version: 1.14.0
- Kubernetes version: (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.15-gke.1102", GitCommit:"2e625a55a420ded12d04226c63c4cf415efc9cdb", GitTreeState:"clean", BuildDate:"2021-02-23T19:24:16Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}` 
- Kubernetes installer & version: GKE
- Cloud provider or hardware configuration: GKE, 2 nodes
- OS (e.g. from `/etc/os-release`): GKE cos_containerd

**Comment by sunjayBhatia** [comment]
Ah apologies for that, looks like the PR in question never got a release note label so was missed in the release cutting process

**Comment by sunjayBhatia** [comment]
Updated release notes: https://github.com/projectcontour/contour/releases/tag/v1.14.0

**Comment by sunjayBhatia** [comment]
See https://github.com/projectcontour/contour/pull/3543
