### ISSUE TITLE
Contour Managed Envoy

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3545]
As part of the GatewayAPI implementation we've been discussing how to integrate Contour<>Envoy when utilizing GatewayAPI.Gateways. I have a small discussion document outlining a bit more background here (https://docs.google.com/document/d/1kOrGqHXULYO6YLxGCOtVyjz_7mfcW7Yi1WXCpQz6_Qo/edit#heading=h.s3afnqyzdsta). 

The goal of this issue is to create a branch in Contour and investigate how this approach might or might not work moving forward with the GatewayAPI work 

Tasks:

- Configuration CRD for GatewayClass
  - networkPublishing: Define how Envoy is exposed from the cluster
  - gatewayClassRef: 
- Controller to manage Envoy instances
- Set Gateway Status

**Comment by xaleeks** [comment]
Thanks for this @stevesloka .  This spike being worked on right now in the  v1.15 right?  Feel free to untag it if not the case.

**Comment by danehans** [comment]
When Contour manages the envoy infra, the operator should be updated to remove envoy infra management.

cc: @Miciah @candita

**Comment by sunjayBhatia** [comment]
Closing as we have the Gateway provisioner which manages Envoy dynamically
