### ISSUE TITLE
contour pods stuck at ContainerCreating with MountVolume.SetUp failed for volume "contourcert" : secret "contourcert" not found

### ISSUE THREAD

**Issue by vinzo99** [projectcontour/contour#3548]
Hello,

trying to deploy new Contour 1.14 along with Envoy 1.17.1, in my namespace vbertell, using template yaml charts from https://raw.githubusercontent.com/projectcontour/contour/release-1.14/examples/render/contour.yaml

After successful generation of certificates, Contour pods remains in ContainerCreating state with the following error : 

```
# kubectl -n vbertell get po
NAME                                      READY   STATUS              RESTARTS   AGE
contour-6ff6ccc699-9sqzf                  0/1     ContainerCreating   0          12m
contour-6ff6ccc699-f9j29                  0/1     ContainerCreating   0          12m
contour-certgen-v1.14.0-gznj9             0/1     Completed           0          12m

(...)
Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    36s                default-scheduler  Successfully assigned vbertell/contour-6ff6ccc699-9sqzf to bcmt-sandbox6-3c2w2e-2012-s6-worker-01
  Warning  FailedMount  32s (x4 over 36s)  kubelet            MountVolume.SetUp failed for volume "contourcert" : secret "contourcert" not found
  Warning  FailedMount  4s (x7 over 36s)   kubelet            MountVolume.SetUp failed for volume "contour-config" : configmap references non-existent config key: contour.yaml
```

The expected secrets are here : 

```
# kubectl -n vbertell get secrets
NAME                                TYPE                                  DATA   AGE
contour-certgen-token-9gbzj         kubernetes.io/service-account-token   3      14m
contour-token-v5rf8                 kubernetes.io/service-account-token   3      14m
contourcert                         kubernetes.io/tls                     3      14m
envoy-token-wpb8c                   kubernetes.io/service-account-token   3      14m
envoycert                           kubernetes.io/tls                     3      14m
```

Can you please advise ?

Thanks !

**Comment by skriss** [comment]
@vinzo99 would it be possible to provide the exact YAML you're using for your Contour deployment (in a [Gist](https://gist.github.com/) would be great)?

Also, I see you're getting a similar error for the configmap. Could you provide the output of `kubectl -n vbertell describe configmap contour`?

**Comment by vinzo99** [comment]
Sure, here is the yaml file : https://gist.github.com/vinzo99/df945e724d33c6266a76d8b668638969

and the configmap : 
```
# kubectl -n vbertell describe configmap contour
Name:         contour
Namespace:    vbertell
Labels:       <none>
Annotations:  <none>

Data
====
Events:  <none>
```

Thanks !

**Comment by skriss** [comment]
Thanks @vinzo99, so off the bat I see an issue with the configmap, let's get that fixed up first. It should have a key of `contour.yaml` but doesn't. Looking at your gist, it looks like you have an indent error: https://gist.github.com/vinzo99/df945e724d33c6266a76d8b668638969#file-gistfile1-txt-L46-L182 need to be indented once more (you can see `contour.yaml` is not indented under `data` like it should be).

**Comment by vinzo99** [comment]
👍 
Thanks for spotting the typo, it's my second one in 2 days ...
Contour pods are now started. I'm having another issue with Envoy pods not starting but seems familiar (use of PSP requires to add a `privileged` section, I will submit another issue if needed).
Sorry about that, I will close the ticket.
Thanks so much !

**Comment by skriss** [comment]
No problem @vinzo99, glad to be able to help.
