### ISSUE TITLE
Release: More automation for cutting release

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour#3552]
Right now, cutting a release is a very manual process. This issue covers work to further automate the release process.

First priority is something to generate release notes (preferably using the `release-note` and `release-note-action-required` labels to put those changes at the top of the release notes.)

There's probably more automation to consider as well though.

**Comment by sunjayBhatia** [comment]
Related issue: https://github.com/projectcontour/contour/issues/3558

**Comment by sunjayBhatia** [comment]
should be closable now we have the release note label pattern for all changes and the release note tooling
