### ISSUE TITLE
Support HTTPRoute requestMirror RouteFilterType [extended]

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3557]
Support HTTPRoute requestMirror RouteFilterType when defined on an HTTPRoute.

//ref:https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.HTTPRouteFilter

(Support: Extended)

**Comment by sepaper** [comment]
@skriss May I try this?
I have experienced implementing a envoy xds server and k8s CRD, so I think I could implement this feature.
I'm not sure how long it takes, but is it okay to finish this by 1.23.0?

**Comment by skriss** [comment]
@sepaper sure thing, I'll assign it to you. Happy to provide some more direction if you'd like, just let me know.

**Comment by sepaper** [comment]
@skriss Awesome, will do. Thanks! :)
