### ISSUE TITLE
Support HTTPRoute requestHeaderModifier RouteFilterType

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3559]
Support HTTPRoute requestHeaderModifier RouteFilterType.

//ref: https://gateway-api.sigs.k8s.io/spec/#networking.x-k8s.io/v1alpha1.HTTPRouteFilter

**Comment by nak3** [comment]
/close
This was implemented by https://github.com/projectcontour/contour/pull/3539.
@stevesloka @youngnick Could you please update https://github.com/projectcontour/contour/issues/2287#issue-570293364 ? I don't have edit permission.

**Comment by stevesloka** [comment]
Done! Thanks @nak3!
