### ISSUE TITLE
My application wants to get x_forwarded_for ip , What should I do

### ISSUE THREAD

**Issue by bibi520** [projectcontour/contour#3563]
contour version: v1.14.0
![image](https://user-images.githubusercontent.com/42456284/114164724-36c83c80-995e-11eb-897b-71ebb9080bad.png)

**Comment by bibi520** [comment]
There's ELB in front of the Contour

**Comment by sunjayBhatia** [comment]
Some answers online seem to suggest when using the ELB as L7 instead of L4 the `X-Forwarded-For` header is not stripped

**Comment by bibi520** [comment]
need to use L4 ？

**Comment by bibi520** [comment]
My ELB is four-tiered

**Comment by sunjayBhatia** [comment]
Can you give some more details about your ELB set up? It may be that is stripping the header in requests before it gets to Envoy

Any information would be great so we can provide guidance or do some research/reproduction to help

**Comment by bibi520** [comment]
ELB:
![image](https://user-images.githubusercontent.com/42456284/114492643-8a32d700-9c4b-11eb-95ce-7cac538fbe76.png)
contour svc and pod:
![image](https://user-images.githubusercontent.com/42456284/114492694-a46cb500-9c4b-11eb-9e34-3b8380339202.png)
envoy log:
![image](https://user-images.githubusercontent.com/42456284/114492816-e695f680-9c4b-11eb-9de6-8fdf34828c4b.png)
 His x_forwarded_for is the ELB's Intranet address segment
 
Thanks for the trouble

**Comment by bibi520** [comment]
I found the problem that my ELB didn't pass the value x_forwarded_for .......

**Comment by sunjayBhatia** [comment]
@bibi520 Sounds like you able to figure out the problem? Is this issue resolved?

**Comment by bibi520** [comment]
yes

**Comment by bibi520** [comment]
It's my ELB that didn't pass X_forwarded_for

**Comment by sunjayBhatia** [comment]
Sounds good, I’ll close this issue then!
