### ISSUE TITLE
unable to start Envoy DaemonSet on 80

### ISSUE THREAD

**Issue by vinzo99** [projectcontour/contour#3567]
Hello,

I am trying to deploy Contour 1.14.0 along with Envoy 1.17.1, in order to act as an ingress controller. To achieve that I used the template yaml files https://raw.githubusercontent.com/projectcontour/contour/release-1.14/examples/render/contour.yaml and applied a few modifications according to these recommendations in order to use host networking : https://projectcontour.io/docs/v1.14.0/deploy-options/#host-networking

I get the following error in the Envoy container : 
`[2021-04-12 16:30:36.927][1][warning][config] [source/common/config/grpc_subscription_impl.cc:107] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) ingress_http: cannot bind '0.0.0.0:80': Permission denied`

When using a non-root port such as `7777` I get Envoy pod to listen on edge node as expected.

When using the same configuration applied to Contour 1.4.0 with Envoy 1.14.1, Envoy pod successfully listens on `:80` : 
```
# netstat -anp|grep envoy
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      16818/envoy         
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      16818/envoy         
tcp        0      0 0.0.0.0:8002            0.0.0.0:*               LISTEN      16818/envoy         
tcp        0      0 127.0.0.1:59326         127.0.0.1:9001          ESTABLISHED 16818/envoy         
tcp        0      0 127.0.0.1:9001          127.0.0.1:59326         ESTABLISHED 16818/envoy         
tcp        0      0 127.0.0.1:59106         127.0.0.1:9001          ESTABLISHED 16818/envoy         
tcp        0      0 10.11.179.167:41516     10.254.127.200:8001     ESTABLISHED 16818/envoy         
tcp        0      0 127.0.0.1:59292         127.0.0.1:9001          ESTABLISHED 16818/envoy         
tcp        0      0 127.0.0.1:9001          127.0.0.1:59072         ESTABLISHED 16818/envoy         
tcp        0      0 127.0.0.1:59232         127.0.0.1:9001          ESTABLISHED 16818/envoy         
tcp        0      0 127.0.0.1:9001          127.0.0.1:59106         ESTABLISHED 16818/envoy         
tcp        0      0 127.0.0.1:9001          127.0.0.1:59134         ESTABLISHED 16818/envoy         
tcp        0      0 127.0.0.1:9001          127.0.0.1:59232         ESTABLISHED 16818/envoy         
tcp        0      0 127.0.0.1:59134         127.0.0.1:9001          ESTABLISHED 16818/envoy         
tcp        0      0 127.0.0.1:9001          127.0.0.1:59292         ESTABLISHED 16818/envoy         
tcp        0      0 127.0.0.1:59072         127.0.0.1:9001          ESTABLISHED 16818/envoy         
unix  2      [ ]         DGRAM                    1617965  16818/envoy          @envoy_domain_socket_parent_0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
unix  2      [ ]         DGRAM                    1617964  16818/envoy          @envoy_domain_socket_child_0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

Here is the sample yaml file used for configuration : https://gist.github.com/vinzo99/e601c2324b53929dd54663cea2bebf8d

Can you please advise ?

Thanks !

**Comment by youngnick** [comment]
Hi @vinzo99, this is because the pod's security context does not have the capability to use ports below 1024, usually this requires running as `root`. That's why it works when you use another port.

If you're running another load balancer upstream from your nodes, then I'd definitely recommend just using a high port and having the upstream load balancer swap the ports for you.

**Comment by vinzo99** [comment]
Hi @youngnick !

First let me clarify that for several operational constraints, we do not run another load balancer, and need to have Envoy container listen on `:80` on edge nodes, hence the choice of running Host Networking as described here : https://projectcontour.io/docs/v1.14.0/deploy-options/#host-networking , which implies several modifications that we already reflected in the yaml files.

Another constraint is that the Envoy containers do NOT run as `root`, they run as a dedicated `envoy` user with UID:GID `4444:4444`.

In this case I understand the need to add a security context to the Envoy container in the DaemonSet, but I need 2 clarifications : 

1°) can you please specify the whole securityContext block and where to add it ? I remember struggling with options in a different issue

2°) why is it working with Envoy v1.14.1/Contour 1.4.0 without needing to add a security context, with a similar yaml configuration, on the same cluster ?

Thanks !

**Comment by youngnick** [comment]
To bind low ports, you need the CAP_NET_BIND_SERVICE capability. You specify that in the `securityContext` block of the _container_, not the Pod. So, in the Envoy container section, you need to put:
```yaml
    securityContext:
      capabilities:
        add:
        - "NET_BIND_SERVICE"
```
(For some reason, Kubernetes capabilities omit the `CAP_` prefix that they have in other places).

I have no idea why it's working at all with those restrictions and Contour 1.4.0/Envoy 1.14.1, that's a lot of versions ago, so a *lot* has changed since then. If you're binding to nonroot user and not supplying that capability, then it shouldn't work.

**Comment by vinzo99** [comment]
Thanks @youngnick 
I did add the `securityContext` block at the Envoy container level in the DaemonSet, but still get the issue.
I will try adding more options and combinations than just `capabilities`, I guess since Envoy container user is not `root` I should consider adding something else, probably related to user/privileges.

**Comment by youngnick** [comment]
You could also try adding `CAP_NET_ADMN`, this seems like overkill, but may help with debugging. If that works, then it's probably that Envoy needs another network capability added, See https://man7.org/linux/man-pages/man7/capabilities.7.html for an overview of the capabilities.

**Comment by vinzo99** [comment]
I finally had it working by tweaking the securityContext like this : 
```
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_BIND_SERVICE
          allowPrivilegeEscalation: true
          runAsUser: 0
```

Thanks !
