### ISSUE TITLE
Upgrades: How do we handle using new Envoy features in Contour

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#3573]
When a Contour feature needs to utilize a net-new Envoy API/feature/flag/etc. how do we manage upgrades?

For example this change uses a new feature in Lua: https://github.com/projectcontour/contour/pull/3381

Currently we simply update the release notes and upgrade instructions to reflect that Envoy needs to be updated before Contour. However this isn't necessarily sustainable, people can miss this, and if we have other changes that require Contour to be upgraded first, we can have very complicated problems that may require us to delay changes etc.

We don't currently have any codified upgrade testing or practices outside the upgrade documentation we provide but should do so. The Operator currently does not yet support upgrades but will eventually.

We could potentially do this transparently for users by limiting usage of new fields/features sent in configs by the Envoy version. The xDS discovery request has the notion of a node identity/version that could be used to identify requests from older Envoys that need to not be sent configs with new fields etc.

Links:
- https://github.com/envoyproxy/envoy/blob/8771f7f83cea1940a51981ac28da7b3f1b173c38/api/envoy/service/discovery/v3/discovery.proto#L21-L37
- https://github.com/envoyproxy/envoy/blob/8771f7f83cea1940a51981ac28da7b3f1b173c38/api/envoy/config/core/v3/base.proto#L134-L210

**Comment by danehans** [comment]
> The Operator currently does not yet support upgrades but will eventually.

xref https://github.com/projectcontour/contour-operator/issues/142

**Comment by skriss** [comment]
Personally I do like the idea of not putting new Envoy features on the critical path, i.e. the user should always be able to upgrade Contour first and have their existing config continue to work. It's OK if a new Envoy feature is used by **new** Contour functionality, since presumably that wouldn't be configured until after everything has been fully upgraded. It seems like this practice would keep upgrades more predictable.

**Comment by xaleeks** [comment]
I like the thing Sunjay linked and agree with this request wholeheartedly.  Got time to work on this in v1.18? @sunjayBhatia
