### ISSUE TITLE
Should globally configurable TLS options should be set on upstream TLS contexts?

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#3574]
Global TLS configuration here currently only applies to Envoy listeners: https://projectcontour.io/docs/v1.14.0/configuration/#tls-configuration

This means that settings like minimum TLS version and TLS ciphers are not applied to Envoy -> Upstream cluster communication or Envoy -> Extension Service cluster communication.

We do not seem to offer any configurability of these TLS connections.

Is there any reason we have not made these options configurable on the aforementioned connections?

Should we make the existing global configuration also apply to upstreams etc.?

**Comment by youngnick** [comment]
I agree that we should allow configurability of this, and also agree that starting with making the existing global config also apply to upstreams is probably okay.

The only risk there is that we need to ensure that the certificates generated by `contour certgen` will work with TLS 1.3, and make sure that existing installations that have certs that don't won't break if we suddenly start enforcing that the Contour <-> Envoy connection must be TLS 1.3.

**Comment by digibank-rons** [comment]
Hi,

So just to get it straight, currently there is no way of setting cipher suite for TLS connection?

Thanks

**Comment by sunjayBhatia** [comment]
> Hi,
> 
> So just to get it straight, currently there is no way of setting cipher suite for TLS connection?
> 
> Thanks

You can for the connections between downstream clients and Envoy, however this does not apply to connections between Envoy and upstream clusters

**Comment by xaleeks** [comment]
And to satisfy FIPS Compliance, I think Min TLS and TLS ciphers should apply to Envoy <> upstream services as well I would think. I’m tagging this v1.16 first, feel free to adjust it based on your priorities @sunjayBhatia

**Comment by sunjayBhatia** [comment]
@xaleeks Envoy -> upstreams with a FIPS build of Envoy will already send FIPS compatible ciphers without configurability

Does this apply to FIPS really? Or does it more apply if you want to override the defaults that Envoy will choose? (to allow non-FIPS etc. while you are transitioning to FIPS or something or for legacy)

**Comment by sunjayBhatia** [comment]
haven't had a chance to work on this yet and 1.16 release is v soon, should probably move this to the next milestone

**Comment by sunjayBhatia** [comment]
cipher suite configurability for Envoy as a client is maybe a lower priority tbh given this clarification in the docs: https://github.com/envoyproxy/envoy/blob/299eadf8b703972229321f296061adb4e5b510a8/api/envoy/extensions/transport_sockets/tls/v3/common.proto#L93-L109

Envoy in FIPS and non-FIPS mode as a client requests a limited set of ciphers anyways, but we can make it fully configurable for users

**Comment by youngnick** [comment]
We didn't get to this one, moving to 1.18.

**Comment by xaleeks** [comment]
> @xaleeks Envoy -> upstreams with a FIPS build of Envoy will already send FIPS compatible ciphers without configurability
> 
> Does this apply to FIPS really? Or does it more apply if you want to override the defaults that Envoy will choose? (to allow non-FIPS etc. while you are transitioning to FIPS or something or for legacy)

Thanks, I think that’s sufficient.  To elaborate on downstream requirements, FIPS means everything in the Kubernetes cluster in the platform service product is FIPS compliant and using the specific set of cipher suites.  Because we own the Kubernetes distro we ship to customers and Contour is a part of that.  Only exception I can think of is if something like AWS load balancer or Azure load balancer requires non-FIPS compliant cipher suites.

**Comment by xaleeks** [comment]
> We didn't get to this one, moving to 1.18.

Thanks for moving this to 1.18.  I was thinking about how do we know if something actually landed in this release, can we ‘ack’ on the ticket somehow?  Or we can sync offline and I’ll make sure the board is up to date.

**Comment by youngnick** [comment]
If an issue lands in a release, there will be a merged PR associated with it, which should (usually) close the issue as well.

**Comment by xaleeks** [comment]
Just checking in to see if this is still on track for 1.19

**Comment by youngnick** [comment]
Noone assigned yet, let's talk about this one in the meeting tomorrow.

**Comment by abhide** [comment]
Here is my understanding:
Setting minTLSVersion on upstream clusters/ services is out of scope for Contour. However, Envoy can be configured via Contour to use a specific minTLSVersion for TLS Origination when Envoy makes connections to upstream clusters. 
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-transport-socket

I think we need to update: https://github.com/projectcontour/contour/blob/main/internal/envoy/v3/cluster.go#L81 and https://github.com/projectcontour/contour/blob/main/internal/envoy/v3/auth.go#L30

@sunjayBhatia  / @youngnick Wanted to check whether my understanding is correct? Looking for some inputs on how to set minTLSVersion from configuration all the way. I think I might need to update HTTPProxy CRD as well? 

I would like to work on adding this support; is it fine if I assign this issue to myself?

**Comment by sunjayBhatia** [comment]
Sounds right to me @abhide 

Nick had a comment above:

> I agree that we should allow configurability of this, and also agree that starting with making the existing global config also apply to upstreams is probably okay.

Might not need to add it to HTTPProxy at first, we can maybe see if applying the global configuration is enough for people to customize the Envoy -> Upstream TLS connections

**Comment by abhide** [comment]
Thanks @sunjayBhatia for the inputs. 
We can use the same TLS configuration as : https://projectcontour.io/docs/v1.14.0/configuration/#tls-configuration

I think we need to feature flag this and let people enable/disable it rather than contour doing it by default, correct?
At least to start with; we can default to enabled but give the option for cluster admins/operators to disable via configuration? @youngnick @skriss @sunjayBhatia what do you think about this? 

To start with; let me check how to make that global TLS configuration available for Envoy for upstream connections.

**Comment by youngnick** [comment]
I think it's probably better to enable via default, and wait and see if people want more configurability. I think that most people who want to configure ciphersuites will want them to match everywhere.

**Comment by sunjayBhatia** [comment]
this is being worked on in https://github.com/projectcontour/contour/pull/5828
