### ISSUE TITLE
Bump Kubernetes compatibility matrix to include k8s 1.21 / Envoy v1.18.2

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#3583]
Once we are testing against k8s 1.21 in CI we should update the compatibility matrix to show we are compatibly to 1.21 down to 1.19

Also need to update the Envoy version to v1.18.2

This should be done as part of the 1.15.0 release cutting process

**Comment by skriss** [comment]
I'll do this as part of the release.
