### ISSUE TITLE
Update CI base images for E2E tests

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3584]
Our current kind based testing infra pulls a bunch of images each time the e2e tests are run. In some cases the images are very large (500mb+). To speed up the time to pull/load into the cluster, we could pre-load these images into a custom kind image that allows to be the base image. Additionally we could pick smaller test images that aren't so large to help reduce build/test time. 

- [ ] Reduce image sizes for tests
- [ ] CI job/script to build base image & push to a registry

**Comment by skriss** [comment]
It could also be worth considering maintaining our own test "echo server" binary that has the functionality we need for testing purposes. Right now we depend on `ingress-conformance-echo` (a custom build of it from `tsaarni`) and `httpbin` for the combo of functionality we need.

**Comment by youngnick** [comment]
I agree that we should either pick one upstream thing to use for all our tests, or make our own instead and do that. But it should be the one thing across everything regardless.

**Comment by tsaarni** [comment]
I think the "official" build of `ingress-conformance-echo` is at https://gcr.io/k8s-staging-ingressconformance/echoserver, latest still being `gcr.io/k8s-staging-ingressconformance/echoserver:v20201006-42d00bd`.  This one includes the TLS stuff, which was the reason for my custom build back then.

In my own personal dev tests I've completely gotten rid of `httpbin` and use `ingress-conformance-echo` exclusively.  It is much lighter and still contains everything I need.

**Comment by skriss** [comment]
> In my own personal dev tests I've completely gotten rid of `httpbin` and use `ingress-conformance-echo` exclusively. It is much lighter and still contains everything I need.

Yep, we use `httpbin` only in one test -- the health checks test -- and only because it has functionality where if you request a path like `/status/418` it will return a `418` response code. It would be really nice to not have to use it anymore since it's so big.

**Comment by tsaarni** [comment]
> Yep, we use `httpbin` only in one test -- the health checks test -- and only because it has functionality where if you request a path like `/status/418` it will return a `418` response code. It would be really nice to not have to use it anymore since it's so big.

I guess the conformance test suite does not go into status codes of upstream services currently but I wonder if it could be justified that `ingress-conformance-echo` would have a `/status/` endpoint for testing controllers, something simple like [this](https://github.com/tsaarni/ingress-controller-conformance/commit/adb4adecf6b6c70fb6cbb30177a6e6db74e04c38).

**Comment by skriss** [comment]
Would definitely be useful, if they'd take the PR we would use it and drop `httpbin` for sure.

**Comment by sunjayBhatia** [comment]
Also found https://github.com/Ealenn/Echo-Server (docker hub https://hub.docker.com/r/ealen/echo-server) which is pretty nice, doesn't have TLS as far as I can see though

**Comment by tsaarni** [comment]
I've wondered if it would make sense to fork ingress-conformance-echo to have full control. When we last talked about this, I sent https://github.com/kubernetes-sigs/ingress-controller-conformance/pull/91 but I guess it makes no sense for Kubernetes maintainers to keep up with this since it is basically just single .go file.

**Comment by youngnick** [comment]
I think that updating ingress-conformance-echo is a good idea, it will be needed for Gateway API as well. I'll ping Bowei about it.

**Comment by tsaarni** [comment]
I checked that ~100MB could be saved by replacing cert-manager https://github.com/projectcontour/contour/pull/4194#issuecomment-976710013, 

```
REPOSITORY                                 TAG      IMAGE ID       CREATED         SIZE
quay.io/jetstack/cert-manager-webhook      v1.5.1   1e55c894d72f   3 months ago    46.4MB
quay.io/jetstack/cert-manager-controller   v1.5.1   9ca5b2857af9   3 months ago    63.3MB
```
I guess this is not that major footprint reduction though, and it would be replaced by few more Go modules being pulled.

**Comment by tsaarni** [comment]
@sunjayBhatia Looking at the cookie rewriting test cases, maybe this very simple endpoint could suffice to replace `docker.io/ealen/echo-server:0.5.1` (~90MB)
https://github.com/kubernetes-sigs/ingress-controller-conformance/compare/master...tsaarni:return-custom-headers?

The API is borrowed from http://httpbin.org/#/Response_inspection/get_response_headers

**Comment by sunjayBhatia** [comment]
> @sunjayBhatia Looking at the cookie rewriting test cases, maybe this very simple endpoint could suffice to replace `docker.io/ealen/echo-server:0.5.1` (~90MB) [kubernetes-sigs/ingress-controller-conformance@master...tsaarni:return-custom-headers](https://github.com/kubernetes-sigs/ingress-controller-conformance/compare/master...tsaarni:return-custom-headers)?
> 
> The API is borrowed from http://httpbin.org/#/Response_inspection/get_response_headers

yep that looks like it would work! would be a worthy change

**Comment by sunjayBhatia** [comment]
Closing as I think over time we've updated our e2e tests/dependencies so this isn't much of an issue any longer
