### ISSUE TITLE
Provide the ability to protect the metrics endpoints with TLS

### ISSUE THREAD

**Issue by tsaarni** [projectcontour/contour#3594]
The metrics endpoints in Envoy and Contour are currently exposed as unauthenticated HTTP.  This could have some security related consequences:

1. An attacker might find some sensitive information that they can use for their advantage. For example, Envoy `/stats` endpoint can be used to enumerate all upstream services in the cluster.
2. In theory an attacker could masquerade the metrics endpoint(s) and inject fake data to monitoring systems, in order to e.g. hide an ongoing attack, confuse the system to autoscale up/down etc...

It would be nice to protect the metrics endpoints with TLS, using mutual authentication (client+server certs).

**Comment by youngnick** [comment]
I think the ask should be "provide the ability to protect the metrics endpoints with TLS", I don't think we should move the default without very careful consideration, since it would break existing monitoring.

**Comment by tsaarni** [comment]
Yes I agree, that was not the intention to suggest.  Bad communication :)

**Comment by youngnick** [comment]
Totally agree we should allow this, yes.
