### ISSUE TITLE
Gateway Port <> envoy-service-http(s)-address serve flags

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3616]
Contour defines the ports which Envoy listens on via a set of `contour serve` flags:

- envoy-service-http-address
- envoy-service-http-port
- envoy-service-https-address
- envoy-service-https-port

These are defined in a Gateway.Listeners now. Need to find a pattern to not use the contour serve flags but allow the Gateway.Listener ports to take precedence in the event someone is utilizing GatewayAPI.

**Comment by stevesloka** [comment]
Another thought would be to move to use Gateway for Contour by default and have them select root HTTPProxies. Then we can deprecate the flags noted above and use the ports from the Gateway exclusively.

**Comment by youngnick** [comment]
So, we would *always* have a Contour Gateway, that could also refer to HTTPProxy resources?

Having a Gateway able to refer to HTTPProxy resources as a type of Route is actually a great idea regardless, but this one does sound interesting.

**Comment by stevesloka** [comment]
Yeah the thought would be to move Contour to use a Gateway to configure the listeners regardless of if you're using HTTPRoute, TLSRoute, etc. We'd have to add support for Ingress/HTTPProxy, but would give you a single place to define the listener parameters and removes gateway-api from being a "special" implementation.

**Comment by youngnick** [comment]
Once we have Contour managing the Envoy Service at least, this would be a nice option, but I think we'll have to keep the old way around for a while (that is do a proper deprecation cycle), since people may not want to install Alpha CRDs in their clusters.

**Comment by sunjayBhatia** [comment]
I think this can be closed now, see https://projectcontour.io/docs/1.27/config/gateway-api/#gateway-listeners
