### ISSUE TITLE
Migrate E2E tests to Go

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#3621]
- [x] get basic framework defined and running in CI
- [x] implement HTTPProxy tests in Go
- [x] implement Gateway API tests in Go
- [x] implement Ingress tests in Go
- [x] turn off `_integration` tests (#3737)
- [ ] remove numbering from tests (leaving in for now for ease of correlating to the `_integration` tests) (#3838)

Future:
- improvements to how test data (`HTTPProxies`, `Gateways`, `HTTPRoutes`, etc) are defined (YAML? Builders? etc)
- overlap with `featuretests` - can we reuse test cases, helper libs, etc?
- have test framework generate unique test name & namespace & pass an abstraction to tests that "knows" to create stuff in the right place (https://github.com/projectcontour/contour/pull/3622#discussion_r623232987, https://github.com/projectcontour/contour/pull/3622#discussion_r623234704)
- make setup faster (create cluster, build Contour image, load images into cluster, deploy Contour to cluster)
- ~~get HTTPProxy test 013-backend-tls migrated & running (requires an alternate Contour config file) (#3729)~~
- ~~look at Ginkgo (in-progress https://github.com/projectcontour/contour/pull/3638)~~
- ~~improvements to how subtests are registered to be run~~ (covered by move to Ginkgo)
- ~~support different Contour configurations for different sets of tests~~ (covered by running Contour out-of-cluster)

**Comment by skriss** [comment]
@stevesloka @sunjayBhatia @youngnick I'm planning to turn the `_integration` tests off around the end of this month/release cycle, let me know if you have any objections.

**Comment by youngnick** [comment]
As far as I can see, we have coverage over the same things, so that sounds great.

**Comment by sunjayBhatia** [comment]
Relevant issue as well, to track the backend-tls test that we dont have a go e2e for yet: https://github.com/projectcontour/contour/issues/3729

**Comment by skriss** [comment]
We're at a point where we can remove the numbering from the test file names and namespace names, I'll get a PR ready for that so we can close this issue out. cc @sunjayBhatia
