### ISSUE TITLE
Discussion: Moving Contour to Quarterly release cadence

### ISSUE THREAD

**Issue by xaleeks** [projectcontour/contour#3634]
Current support stance for Project Contour is that we only support the latest version.  Since we’re on a monthly release cadence, this can create pressure for users and customers to upgrade at a frequency beyond their level of supportability.  This is a request to think about mechanics to create designated long term releases (LTS) that are more resilient and supported for longer periods of time for certain downstream consumers.  Support in this case means performing root cause analysis, providing workarounds, and as a last resort releasing patches for any security vulnerabilities & sev1 and sev2 issues and bugs.

With respect to upgrade, we will likely only provide upgrade path on an LTS version to another LTS version.  LTS is tentatively defined to mean 9 months to 1 year.  

Other considerations
- Align with Envoy release windows
- Align with K8s release windows
- K8s releases supportability on public clouds, ie. A Kubernetes version is fully supported for 14 months after first being available on Amazon EKS. This is true even if upstream Kubernetes is no longer supporting a version available on Amazon EKS.

**Comment by youngnick** [comment]
We can definitely do this, provided that we are prepared to expend the engineering effort to:
- build and maintain a testing matrix for upgrading from LTS to LTS
- have a firm policy about what "LTS" actually means - the more permissive our support policy is, the more pressure we will get to backport things (which can be quite costly in engineering terms). In any case, I think that a baseline must be that there's no feature backports, ever. Security fixes, sure. Bugs and Issues would need to be extremely severe for us to backport fixes, I think.
- This work also requires skip upgrade support (#3654). No point having LTS releases if users can't go straight from one to the other.

Doing this means that we will need to ensure that a certain percentage of engineer-time is set aside for backporting and support work. The more permissive our definition of support, the larger that percentage will be.

**Comment by xaleeks** [comment]
Would like to officially kick off thinking about moving to a quarterly release schedule (4 minors a year), and perhaps align against Envoy or K8s upstream, with preference for Envoy.  We can’t have our minors chase Envoy minors too closely because we need time to test it out and wait for patches if there are any bugs etc.  So best to lag by 1-2 months probably.  Ie. if Envoy releases are in Jan / Apr / Jul / Oct, corresponding Contour releases could be scheduled for Mar / June / Sept / Dec.  

As part of this, we will support at least N-1 releases which means patching for any vulnerabilities (CVSS > 7.0?), bugs, and issues or features that land in our critical path.    

Welcome any feedback from the community on this!

**Comment by xaleeks** [comment]
> We can definitely do this, provided that we are prepared to expend the engineering effort to:
> 
>     * build and maintain a testing matrix for upgrading from LTS to LTS
> 
>     * have a firm policy about what "LTS" actually means - the more permissive our support policy is, the more pressure we will get to backport things (which can be quite costly in engineering terms). In any case, I think that a baseline must be that there's no feature backports, ever. Security fixes, sure. Bugs and Issues would need to be extremely severe for us to backport fixes, I think.
> 
>     * This work also requires skip upgrade support ([Support jump upgrades for better supportability #3654](https://github.com/projectcontour/contour/issues/3654)). No point having LTS releases if users can't go straight from one to the other.
> 
> 
> Doing this means that we will need to ensure that a certain percentage of engineer-time is set aside for backporting and support work. The more permissive our definition of support, the larger that percentage will be.

For skip upgrades in the case of quarterly releases, IMHO I would like for us to be able to skip N-2, ie release of v1.17 would validate upgrades from v1.15 and v1.16

**Comment by stevesloka** [comment]
Does this change the deprecation policy as well? So if we deprecate something, then should that apply to LTS releases? 

Maybe a design doc would be helpful here @xaleeks to put down these ideas and provide a place to comment on?

**Comment by xaleeks** [comment]
Yeah I'll map out what this means for supporting multiple releases at a time on a gdoc and share it here so we can all add comments.  Right now, tentatively I'm thinking we support  N-2 releases concurrently so with the release of v1.17 today, we would still support 1.15 and 1.16 minors with patch releases in accordance to what was laid out above.  Next, when 1.18 GAs, we would no longer be supporting 1.15.  

If we move to a quarterly release cadence, this would give every minor roughly 9 months of support for the community, which would line up with some of the commercial offerings of Contour as well.  Open to ideas on all this.

**Comment by xaleeks** [comment]
So if go to quarterly releases, I don't think we need a notion of LTS release anywhere, every release is supported until the (N+2)th release is GA.  So 1.15 is supported until 1.18 and 1.16 is supported until 1.19 debuts

The reason for this in my view is vmware has certain commercial Kubernetes distros called Tanzu Kubernetes leveraging Contour and they put out a minor every quarter (or they aspire to), so every Tanzu minor should consume the latest and greatest Contour minor.  That would be ideal.  

> So a user would run v1.17, then later upgrade to v1.20 (which was three months later). This allows users to buy into features faster like we do today, but if they want to stay conservative, then they stick to the LTS and get that stability.

Right, but this is assuming a monthly cadence still.  If we move to quarterly, it would be 9 months btw 1.17 and 1.20

**Comment by xaleeks** [comment]
https://github.com/envoyproxy/envoy/blob/main/RELEASES.md
Xref Envoy release schedule which is at end of each calendar quarter.

**Comment by youngnick** [comment]
I think that doing:
- longer release cycles
- changing the support window to n-2

Are definitely doable, but we'll have to handle some issues:
- our overall support is only nine months, and isn't matched to Kubernetes versions. So we'll have to support up to four  Kubernetes versions if the time frames don't line up, not three like today.
- We'll be doing a lot more work for releases - we will need to have some rules about what gets backported and what doesn't. 
- HTTPProxy versioning is independent of Contour versioning, so we may need to backport HTTPProxy field additions back to the supported versions as well. (I only just thought of this one).

In short, I don't think that our monthly release train model is sustainable, we need to do something different. I think that lengthening the release cycle and supporting more cycles is the most likely stance to be achievable with our current maintainer pool.

I also think that doing LTS releases is an unknown and probably too large amount of work. For upstream Kubernetes we did not choose to do this because of the work it entails when you release the LTS version. Admittedly, Kubernetes is much larger, but I don't think it makes sense for a product with as much change as Contour has seen. Maybe in the future when the feature change list has quietened down, we can reevaluate.

**Comment by skriss** [comment]
> In short, I don't think that our monthly release train model is sustainable, we need to do something different. I think that lengthening the release cycle and supporting more cycles is the most likely stance to be achievable with our current maintainer pool.

+1 to this, I think monthly made sense in the earlier days of the project when things were evolving rapidly but now that things are more stable, slowing down a bit makes more sense for both maintainers and users.

**Comment by erwbgy** [comment]
+1 With my end user hat on I find it difficult to keep up with the monthly release cadence and fall behind, resulting in upgrades to multiple releases in quick succession when I find the time to do so. A quarterly cadence would make this much more manageable. 

Personally I don't see much benefit in a Contour LTS version when Envoy doesn't have one. The security related reasons for upgrading I can think of are all Envoy related, with Contour upgrades being for bug fixes and features. 

Assuming that there will still be point releases for bug fixes, like the recent endpoints watch events, then having feature releases every 3 months could work well, giving more time for stabilisation and testing.

**Comment by youngnick** [comment]
That's a good point, thanks @erwbgy. I think currently we're anticipating keeping a reasonably high bar for patch releases (we'll still keep to major.minor.patch semver style) - basically that it would be a security or other urgent fix. Obviously, the bar will be less than what it is currently, since you could conceivably have to wait a lot longer for the regular release. I guess what I'm saying is that I don't anticipate us releasing patch releases very often, that's all.

**Comment by xaleeks** [comment]
Here's a doc outlining the proposal to move to quarterly releases, comments are welcome

https://docs.google.com/document/d/1OUbSXa0IebF8_7zjvPU1l8L4H2RfYW0thwWmTE7eHZw/edit

**Comment by xaleeks** [comment]
also curious about how folks feel about RC builds and how they would be used

**Comment by sunjayBhatia** [comment]
Moved out of the release column into the "Investigating" section of the board as this is a longer term discussion

Seems like we are collecting feedback and refining the doc posted above

Action items:
- Publicize proposal in community meetings etc.
- Finish/polish proposal in https://docs.google.com/document/d/1OUbSXa0IebF8_7zjvPU1l8L4H2RfYW0thwWmTE7eHZw/edit
- Move end product into a markdown/website page
- Publicize decision in community meetings etc.
- Start implementing new release cadence

@xaleeks Going to assign this to you for now so we have someone on the hook for this

**Comment by youngnick** [comment]
I've just opened this PR  (#3958) which has our official proposal for moving Contour to quarterly releases, starting with 1.20, due out late October. Please check it out, and +1 or comment with feedback. I've addressed all the questions I could think of in this initial PR, but if there's anything else you need to know, please ask, and we can make sure it's answered.
This PR will stay open for at least a week, probably two, to give everyone time for feedback. Once we all agree and it's merged, I'll sweep across the repo and make sure the new state is documented in all the right places.

**Comment by xaleeks** [comment]
Moving this into 1.20 since everything will have been finalized and communicated by 1.20.

**Comment by youngnick** [comment]
Closing this one out as 1.20 is our first quarterly release.
