### ISSUE TITLE
Add support for GatewayAPI Admission webhook

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3639]
Now that there's an admission webhook created for gatewayapi, Contour should add support for this in the docs / examples controllers, etc. 

//refs: 
- https://console.cloud.google.com/gcr/images/k8s-staging-gateway-api/GLOBAL/admission-server?gcrImageListsize=30
- https://github.com/kubernetes-sigs/gateway-api/blob/master/deploy/admission_webhook.yaml

**Comment by skriss** [comment]
#3807 now covers this as well, closing this one out.
