### ISSUE TITLE
HTTPRoute status updates are failing in Kubernetes 1.19.7

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#3641]
Seeing this error in the Contour log when it's trying to update `HTTPRoute` status on 1.19.7:
```
time="2021-05-05T17:02:01Z" level=error msg="unable to update status" context=StatusUpdateHandler error="HTTPRoute.networking.x-k8s.io \"http-filter-1\" is invalid: status.gateways.gatewayRef.controller: Invalid value: \"null\": status.gateways.gatewayRef.controller in body must be of type string: \"null\"" name=http-filter-1 namespace=gateway-005-request-header-modifier-rule
```

It's marked as optional, so not sure why this would be erroring, esp. only on 1.19.x, makes me think maybe there's an upstream issue. @stevesloka any ideas here?

_Originally posted by @skriss in https://github.com/projectcontour/contour/pull/3638#issuecomment-832835980_

**Comment by stevesloka** [comment]
I can see these on a 1.20 cluster as well. I'd like to circle back and add status checks for all of these tests now that we can do that easily. My guess is that the status update is behind the tests and when they go to write status back, the object gets deleted since the testing has moved on to something else.

**Comment by skriss** [comment]
ref. https://github.com/kubernetes-sigs/gateway-api/issues/669

**Comment by skriss** [comment]
@stevesloka maybe we should populate the `Controller` field in the `RouteGatewayStatus` struct to avoid this issue for now, reading the original PR/issue that added that field implies it will become required eventually anyway. Not actually sure which value makes sense, though - `projectcontour.io/contour-operator` or `projectcontour.io/ingress-controller`?

**Comment by stevesloka** [comment]
@skriss let me look back again at the tests, we should be processing through the configured gateway to that field. If not then possibly there's some other edge case that we've hit.

**Comment by skriss** [comment]
Putting a value into the Controller field fixes this issue for me

**Comment by stevesloka** [comment]
Ahh ok I see. Yeah we need to push through what's configured in the Gateway class, but Contour hasn't processed gateway classes at this point. We could use something status like you suggested and then update once we have proper gatewayclass processing. 

I think @danehans was using `projectcontour.io/contour` in other places, but can swap that out for anything right now. 

@skriss do you want to take or I can PR?

**Comment by skriss** [comment]
I'll put a PR up with a static value now for and log an issue to update with the GatewayClass value. Thanks for the input!
