### ISSUE TITLE
add support from upgrading http->https in location header

### ISSUE THREAD

**Issue by andrewzah** [projectcontour/contour#3657]
Creating this per our discussion in the last contour community meeting on 5/4.

Right now we're accomplishing this with the following filter + lua code:

```diff
diff --git a/internal/xdscache/v3/listener.go b/internal/xdscache/v3/listener.go
index ac529a28..7e49380e 100644
--- a/internal/xdscache/v3/listener.go
+++ b/internal/xdscache/v3/listener.go
@@ -485,6 +485,8 @@ func (v *listenerVisitor) visit(vertex dag.Vertex) {
                                AddFilter(envoy_v3.FilterMisdirectedRequests(vh.VirtualHost.Name)).
                                DefaultFilters().
                                AddFilter(authFilter).
+                               AddFilter(envoy_v3.RewriteLocationHeader()).
                                RouteConfigName(path.Join("https", vh.VirtualHost.Name)).
                                MetricsPrefix(vh.ListenerName).
                                AccessLoggers(v.ListenerConfig.newSecureAccessLog()).
```

```diff
diff --git a/internal/envoy/v3/listener.go b/internal/envoy/v3/listener.go
index 89921133..3213f491 100644
--- a/internal/envoy/v3/listener.go
+++ b/internal/envoy/v3/listener.go
@@ -688,3 +688,85 @@ func ContainsFallbackFilterChain(filterchains []*envoy_listener_v3.FilterChain)
+
+func RewriteLocationHeader() *http.HttpFilter {
+       code := `
+   function envoy_on_response(response_handle)
+     local headers = response_handle:headers()
+     local locationHeader = headers:get("location")

+     if locationHeader ~= nil then
+       modified = string.gsub(locationHeader, "http://", "https://")
+       response_handle:headers():replace("location", modified)
+     end
+   end
+ `
+       return &http.HttpFilter{
+               Name: "envoy.filters.http.lua",
+               ConfigType: &http.HttpFilter_TypedConfig{
+                       TypedConfig: protobuf.MustMarshalAny(&lua.Lua{
+                               InlineCode: code,
+                       }),
+               },
+       }
+}

```

and the lua code extracted:
```lua
function envoy_on_response(response_handle)
  local headers = response_handle:headers()
  local locationHeader = headers:get("location")

  if locationHeader ~= nil then
    modified = string.gsub(locationHeader, "http://", "https://")
    response_handle:headers():replace("location", modified)
  end
end
```

---

See the first use case mentioned in this issue: https://github.com/projectcontour/contour/issues/3006

**Comment by youngnick** [comment]
So, the requirement here is "Rewrite all Location headers to HTTPS, always"? And you are currently doing this globally for Contour? I can see adding a boolean thing somewhere that could replicate this, which dodges the support and related issues from #3006.

Sounds like a config file option like `rewriteLocationToSecure` or something might cover this. @andrewzah, do you think that would be what you want? Then, Lua is an implementation detail, if Envoy ever adds a way to do this without Lua, then we can switch to that seamlessly.

**Comment by 205g0** [comment]
Just checking out Contour and stumbled over this issue, does this mean that Contour has no simple toggle or something like a built-in middleware to upgrade http reuqests to https? Didn't find anything in the docs but skimmed them briefly only...

**Comment by andrewzah** [comment]
@youngnick that should work well.

@205g0 not yet, no. You can use a lua filter with the above code to handle upgrading http->https for now.

**Comment by stevesloka** [comment]
@205g0 at a high level, Contour does support an automatic 301 redirect from http->https if you're using HTTPProxy for ingress resources. The issue that @andrewzah is referencing is a little different from basic redirects.

**Comment by 205g0** [comment]
@stefanprodan thx for the info. Ok now I am confused now haha, someone who likes standard Ingress with terse annotations and will upgrade to Gateway API inf future, should I really setup a new cluster which will run for some time on HTTPProxy—I know it will be support beyond Gateway's GA—but yeah...

**Comment by 205g0** [comment]
@stevesloka I checked the API spec for HTTPProxy at https://projectcontour.io/docs/main/config/api/ and couldn't find anything about to-https-redirects in that CRD, even if go down the rabbit hole into the sub-API there's even anything about simple redirects. Hope I missed that or the HTTPProxy CRD_isn't capable of doing redirects neither?!

**Comment by youngnick** [comment]
@205g0 HTTPProxy doesn't have a way to ask for redirect to HTTPS, because it's on by default, unless you specifically disable it by creating an insecure proxy that matches the same domain name and route. If you just ask for `foo.com`, and supply TLS details, Contour will configure the HTTP->HTTPS redirect for you.

@andrewzah's case is about changing the `Location` header unconditionally from `http://foo.com` to `https://foo.com`, regardless of what you specified in your browser. Very different thing, kind of an edge case. But Contour will do HTTP->HTTPS redirect by default for HTTPProxy.

Also, HTTPProxy will be supported until two requirements are fulfilled, at least:
- Gateway API supports everything HTTPProxy does
- The community is happy with us deprecating it.

I don't see either of those things happening for a long time.

**Comment by 205g0** [comment]
@youngnick thanks for the quick clarifications.

Having a HTTP->HTTPS redirect turned on by default is a great design decision. I assume, this default redirect also keeps the path?! So if someone typed `http://example.com/app` it redirects (btw with a 301, permanent one?!) to `http://example.com/app/`, right?

Apologies for such these nitty-gritty questions, hope I can just try it out myself soon, have been playing around with the Ingress only.

**Comment by youngnick** [comment]
@205g0, yes that's correct. All paths for `http://example.com/` get 301-ed to the equivalent `https://example.com/` path by default.

**Comment by xaleeks** [comment]
Just wanted to reiterate Nick’s answer on whether it’s worth investing in HTTPProxy before Gateway API is ready.  Yes, absolutely it is.  Some other reasons I can think of would be

- Gateway API is still nascent and prone to changes.  HTTPProxy is battle tested and provides much more compelling capabilities right now.  We're working on bringing HTTPRoute up to parity with HTTPProxy
- Take a look at the ongoing releases and you’ll see a lot of feature work on HTTPProxy on making it even better.
- Even when gateway API matures and is at parity with HTTPPRoxy, we will support both for some period of time and discuss strategy of possibly moving away from HTTPRoxy with the community first.  This requires buy in and a comfortable cushion for people to migrate.  This is a long ways off

**Comment by youngnick** [comment]
I understand the request is to have a way to say "All HTTP requests should be forwarded to the equivalent HTTPS request, always". Rather than doing this with Lua, I think it would be better to have a way to mandate the behavior we already have with HTTPProxy, which does this for you by default. So, we have a boolean in the config file that would make all methods (Ingress, HTTPProxy, Gateway maybe?) work like this:
- You configure a HTTPS endpoint, you get a redirect for HTTP.
- You configure a HTTP endpoint, Contour says no, do this with HTTPS.

The main thing here is to make a way to *mandate* that this is the only acceptable behavior, I think, rather than the specific Lua implementation. Is that correct @andrewzah ?

**Comment by andrewzah** [comment]
@xaleeks @youngnick However, a more robust solution would be to allow regex editing of headers in general. 

Right now there are `set` and `remove`, but a `replace` option that takes a regex would useful outside of this specific scenario.
