### ISSUE TITLE
CI pipeline/job improvements

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#3681]
Related to https://github.com/projectcontour/contour/issues/3679 there are various improvements we may be able to make in order to have more confidence in our CI jobs/pipelines, speed them up, and follow best practices

- [x] Use dependencies between jobs more often to pipeline operations to reduce wasted effort/time to get results
  - e.g. integration job will depend on an image build job, if that fails, don't bother with expensive integration tests
- [ ] Build Contour image for e2e/integration/push to registry etc. *once* so we are testing and shipping the same artifact
  - Also should reduce the time CI takes, each run does not have to rebuild a container image
- [x] Use github actions build caches to speed up compilation
  - See Steve K's WIP here: https://github.com/skriss/contour/commit/cc2bc154a3c0468c718df40f499136de4e256bf7

**Comment by skriss** [comment]
@sunjayBhatia I think this is all done so we can close this out, agree?

**Comment by sunjayBhatia** [comment]
yeah, i think maybe one improvement could still be to block image push on CI/push the tested image but that can be pulled into its own issue

**Comment by skriss** [comment]
> yeah, i think maybe one improvement could still be to block image push on CI/push the tested image but that can be pulled into its own issue

Makes sense, I misread that second bullet the first time. Opened #4317 to specifically cover that.
