### ISSUE TITLE
`go get` no longer populates the `$GOPATH/src` with the project's source code

### ISSUE THREAD

**Issue by pandeykartikey** [projectcontour/contour#3687]
I was setting up contour as instructed in the CONTRIBUTING.md, when I found that the repo was not being fetched in `$GOPATH/src`. Possible mitigation which I found were setting `GO111MODULE=off` or cloning it in the appropriate directory. If the suggestion seems fine, Shall I go ahead to make this change in the docs?

**Comment by skriss** [comment]
Thanks for noticing the issue @pandeykartikey. Yes, we should update that document. Personally, I'd replace the `go get` command with a `git clone` into any directory (no longer needs to be a subdir of `$GOPATH`).

**Comment by sunjayBhatia** [comment]
Yep I don’t work out of the GOPATH at all with contour, just clone it and other module repos into my workspace directory

**Comment by pandeykartikey** [comment]
I think then the entire `Fetch the source` section can be reduced to fork and clone the repo.
