### ISSUE TITLE
Decision: How to handle GatewayClass Deletion

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour#3700]
**Please describe the problem you have**
How should Contur handle deleting a GatewayClass? This can be a destructive operator if Contour should delete gateways of the class. Maybe Contour should simply update gateway status to indicate something?

**Comment by stevesloka** [comment]
A similar behavior that can happen is if the GatewayClass goes invalid, what should happen? Ultimately we'd like to keep the old version running, but that doesn't work on a cold startup.

**Comment by youngnick** [comment]
I think this isn't well defined in the Gateway API, but it doesn't seem like it's very compatible with not breaking things. At some point, you need a way to stop Contour reconciling things of a GatewayClass. If we don't do that when the GatewayClass is deleted or invalid, when do we do it?

Personally, I think that creating or updating GatewayClasses is a privileged enough operation that we should just have the Gateway fall out of scope of Contour, and have attendant Envoy config removed if it becomes invalid or is removed. We can't protect everybody all the time, and messing with a GatewayClass is a BIG DEAL.

**Comment by stevesloka** [comment]
Should you be able to delete a GatewayClass if it's referenced by a Gateway?

**Comment by youngnick** [comment]
Ideally, no. That is a great point.

**Comment by skriss** [comment]
Per the v1alpha2 spec (https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.GatewayClass):

> Whenever one or more Gateways are using a GatewayClass, implementations MUST add the gateway-exists-finalizer.gateway.networking.k8s.io finalizer on the associated GatewayClass. This ensures that a GatewayClass associated with a Gateway is not deleted while in use.

**Comment by skriss** [comment]
I'm going to close this, as I believe the API spec is clear, and the Contour tracking issue is #3866
