### ISSUE TITLE
Use gateways for all external interactions

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3702]
Thinking through the Gateway api integration, we've been discussing managing Envoy directly from Contour. Should we manage the external traffic targeted to Envoy via Gateway's instead of service type=LoadBalancer? 

Potentially, we could create stub Gateways that in the background manage services with type=LoadBalancer until those direct integrations become available. 

For instance, for AWS, we could stub out a Gateway controller which when requested, creates an ELB with the proper annotations on a service. Contour would only care about creating the proper Gateway of type AWS: ELB, but wouldn't need to be concerned with the service type. 

This would allow us to keep those specific integrations out of the main Contour repo. Also, when the surrounding community gets support for GatewayAPI, then can deprecate our integration and utilize the upstream controller.

**Comment by youngnick** [comment]
This would certainly make the main Contour code simpler in the "Contour manages Envoy" case. I don't know if we'll be ready before then though.

**Comment by stevesloka** [comment]
Here's a diagram I drew up of the interaction:

![Contour-GatewayAPI](https://user-images.githubusercontent.com/1048184/119677556-ac477980-bdf3-11eb-9d4c-86c7c458c139.jpg)

https://docs.google.com/drawings/d/1MQKcMkLc_Dhss_aIf84IEjEqOGYJxBIOZgkCRI-5yj0/edit
