### ISSUE TITLE
session affinity: source ip

### ISSUE THREAD

**Issue by sarthak40** [projectcontour/contour#3703]
**Please describe the problem you have**

Contour supports sticky sessions through [session affinity](https://projectcontour.io/docs/main/config/request-routing/#session-affinity), and more specifically through `loadBalancerPolicy strategy: Cookie`.

When implementing workloads where you'd need tls passthrough, it'd be useful to have the source (/ client) ip and route requests to the same upstream.

I am not sure if that is possible today in envoy though.

**Comment by sunjayBhatia** [comment]
Envoy supports load balancing on source IP: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-routeaction-hashpolicy-connectionproperties

We support request header hashing as a load balancing policy and could extend it to support connection propertly/source IP load balancing: https://projectcontour.io/docs/v1.15.1/config/request-routing/

**Comment by sarthak40** [comment]
@sunjayBhatia thanks for your response!

I'm afraid headers won't be readable through a `tcp_proxy` in the case of a TLS passthrough right?

**Comment by sunjayBhatia** [comment]
Correct but the connection property hashing feature isn’t related to the http headers, to clarify they are separate hash policies we can make configurable

**Comment by youngnick** [comment]
Thanks for raising this issue @sarthak40!

This is probably linked to similar issues:
#3099
#3044
#3142 
that are also about new hash policy options. I'll make sure it's put in the "to be investigated" bucket there as well.

**Comment by xaleeks** [comment]
Source IP seems highly useful for session affinity.  And we should consider allow specifying the source IP in combination with headers for generating the hash value, leveraging the terminal:true to advance through the set of conditionals.  All on a per route basis.  Can we investigate this design for v1.17?  I'm going to tag it for visibility.  cc @skriss 

Looking at the issue Nick linked here https://github.com/projectcontour/contour/issues/3044, it seems we can leverage the parameters afforded by Envoy? ie. the TTL can be useful as well.

Do you have a preference for what the stanza should look like within httpproxy? @sarthak40

**Comment by xaleeks** [comment]
@youngnick do we have bandwidth to tackle this in 1.18?

**Comment by youngnick** [comment]
So, we don't have bandwidth to work on this for a little while, moved to the Prioritized Backlog.
