### ISSUE TITLE
Docs: Update the API reference to properly include the reference in previous versions

### ISSUE THREAD

**Issue by jonasrosland** [projectcontour/contour#3708]
The API reference HTML is automatically built for each version, and is being included in the docs as can be seen here:
https://projectcontour.io/docs/v1.15.1/config/api/

The API reference link for previous active versions have the wrong include function being called resulting in a blank page, as can be seen here:
https://projectcontour.io/docs/v1.15.0/config/api/

The correct behavior is already present in main, but should be fixed for previous versions as well.
Correct:
https://github.com/projectcontour/contour/blob/main/site/content/docs/main/config/api.md
Incorrect:
https://github.com/projectcontour/contour/blob/main/site/content/docs/v1.15.0/config/api.md

**Comment by johnnycase** [comment]
@jonasrosland Hey Jonas, I reviewed this and it has been fixed in #3757.

**Comment by skriss** [comment]
@johnnycase thanks for checking that! I'll close this out.

**Comment by jonasrosland** [comment]
Ah perfect, thanks @johnnycase !
