### ISSUE TITLE
Update SITE_CONTRIBUTION.md

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#3733]
This needs a pretty big overhaul now that we've moved to Hugo.

**Comment by jonasrosland** [comment]
I think this is can be a great first issue for the Contour Tech Docs Working Group, so leaving this open for Thursday's kickoff.

**Comment by hilloaLoa** [comment]
I'd like to take this issue. I've had brief encounters with Jekyll and I'd love to learn Hugo.

**Comment by stevesloka** [comment]
Hey @hilloaLoa how's it going with this? When you're ready let us know and we can take a look and provide some reviews. =)

**Comment by OrlinVasilev** [comment]
@hilloaLoa do you have any update, thank you very much!!

**Comment by hilloaLoa** [comment]
> 
> 
> @hilloaLoa do you have any update, thank you very much!!

Hi, I'm sorry for going AWOL. I've been dealing with personal matters and don't believe that I will be able to complete this assignment. I've unassigned myself from the issue.

**Comment by gary-tai** [comment]
I can take this one. Should this be moved to projectcontour.io?

**Comment by youngnick** [comment]
I think it would be worthwhile keeping the file in the root of the repo, and having the content available on the site as well. Maybe a symlink to the site file from the root?

**Comment by youngnick** [comment]
Even without that though, just updating the content is really important, since it references jekyll and we're now on Hugo.

**Comment by OrlinVasilev** [comment]
@gary-tai @youngnick  just a link here https://projectcontour.io/docs/v1.18.0/start-contributing/#contributing like the other contributing guides?

**Comment by gary-tai** [comment]
The doc can be left outside of /site/contents, just wasn't sure if the goal was to get everything moved under /site. 
I've got most of the content ready for Hugo, perhaps add in best practice section to align with the accessibility assessment (issue #3835.)

**Comment by gary-tai** [comment]
Hi everyone,
I've updated the file, removing Jekyll references and made it for Hugo. 

https://github.com/projectcontour/contour/pull/4620

Thanks.
