### ISSUE TITLE
Question: Docs search for v1.16.0 - not working temporarily?

### ISSUE THREAD

**Issue by karuppiah7890** [projectcontour/contour#3742]
**On Page:** [Docs](https://projectcontour.io/docs/v1.16.0/) I'm not able to do a search in the documentation 😢 For some reason the Algolia API seems to send empty response. Looks like this happens only for v1.16.0 which just got released a few hours ago from what I see https://github.com/projectcontour/contour/releases/tag/v1.16.0 . Is this a temporary thing? Will it be available after some time?

**Comment by skriss** [comment]
@jonasrosland do we need to do anything here to get the new docs indexed?

**Comment by stevesloka** [comment]
Sorry for the delay on this @karuppiah7890, we're digging into why this isn't re-indexing properly.

**Comment by jonasrosland** [comment]
Tagging @orlinvasilev for visibility as well

**Comment by karuppiah7890** [comment]
That's okay, I could still navigate and find what I wanted, also the search in v1.15.x version worked! :)

**Comment by jonasrosland** [comment]
We've updated the search config over on our search engine side, changes should come into effect within 24h:
https://github.com/algolia/docsearch-configs/pull/4166

**Comment by jonasrosland** [comment]
Looks like this works now, can someone else verify so we can close this?

**Comment by stevesloka** [comment]
Works for me! 🎉
