### ISSUE TITLE
Improve "Website: Maintenance planning"

### ISSUE THREAD

**Issue by OrlinVasilev** [projectcontour/contour#3760]
Based on https://github.com/cncf/techdocs/blob/main/assessments/0001-contour.md, better Website: Maintenance planning is needed: 

Under Website: Maintenance planning

Monorepos: Having a docs+code monorepo is risky in the long term, as it couples all docs builds with code builds and vice versa. If docs CI fails because Netlify is temporarily down, for example, this means that all your code builds can potentially fail as well. Coupling docs in a repository with code can also make a code repo's size expand expoentially, especially as projects pick up steam, write more blog posts (with images), and add other multimedia.

Let's discuss the process here!

**Comment by youngnick** [comment]
Feels like this one is maybe a duplicate of #3770 or vice versa? In either case, I think that we should concentrate on getting out information architecture right first before moving everything out. I agree that we do need to do it at some point, but I think the other stuff is better to do first.

**Comment by OrlinVasilev** [comment]
good point very much related so will close this one and keep the other one for discussion!
