### ISSUE TITLE
document Contour crypto functions for FIPS Compliance

### ISSUE THREAD

**Issue by xaleeks** [projectcontour/contour#3769]
As part of the requirement to deliver a FIPS 140-2 compliant build, here’s an additional bookkeeping request. 

As a user, I would like to document the crypto functions used in Contour, in order to meet my company security and compliance requirements.  

- What are the cryptographic libraries, versions, and related crypto functions
- What cryptographic key management techniques (e.g., DH, PBE, CKM, etc.) and standards (e.g., NIST, X9, PKCS, KMIP, etc.) does the product support
- How does the project internally manage cryptographic keys? 
- How are privileged users prevented from misusing or compromising cryptographic keys?
- What confidentiality, integrity, authenticity, and availability controls are used for cryptographic keys
- What is key management hierarchy
- What key management options are supported
- What data encryption keys are supported
- Any key management backup and recovery options?

I’m documenting the request here, the answers can go in a gdoc or hackmd or something else, it does not have to live on github.

cc @sunjayBhatia

**Comment by sunjayBhatia** [comment]
un-assigning myself as I am not actively working on this at the moment
