### ISSUE TITLE
Shutdown-manager /ok filepath issue with read only root filesystem

### ISSUE THREAD

**Issue by Zsolt-LazarZsolt** [projectcontour/contour#3771]
**What steps did you take and what happened:**
Consider the following setup
I created a manifest based on the latest example contour yaml.
The difference is running the shutdown-manager container as a non root user, in a container with readOnlyFilesystem is true.

        securityContext:
          runAsUser: 154691
          runAsGroup: 154691
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
              - all

This makes the contour shutdown command not capable of writing the /ok file.
Also shutdown-manager /shutdown endpoint also will stall indefinitely, as the file /ok never appears.
[1.16.txt](https://github.com/projectcontour/contour/files/6592710/1.16.txt)

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

One possible solution would be to make the path of the /ok file parametrized.
This would mean a parameter for contour shutdown command and also contour shutdown-manager command.

This way I could set a path for this file to be a mounted emptydir, which would be writable.

**Environment:**

- Contour version: 1.16
- Kubernetes version: (use `kubectl version`): 1.22
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by youngnick** [comment]
Thanks for this issue @Zsolt-LazarZsolt. Ironically enough, we started using the file method to stop us having to make remote calls to the Envoy admin port for the shutdown/drain process.

I think that allowing config of the `/ok` file is okay, it will require a few updates though, so probably a guide on how to use that. I can't make any calls on when we would get to this, but I'll talk to @xaleeks about prioritization.

**Comment by youngnick** [comment]
The ask here is, for anyone looking to pick this up:
- add a parameter to `contour shutdown` to set the path to the `ok` file.
- Write a guide detailing how to change the Envoy daemonset to have this actually work.

Please ping me if you decide to pick this up, I will make sure you get a shepherd for your PR.

**Comment by Zsolt-LazarZsolt** [comment]
Thank you for looking into this.
One question:
Do I understand it correctly that contour shutdown-manager also needs this parameter as that one is looking for the file while stalling the /shutdown endpoint calls.

Maybe optionally, beside being a parameter, this could also be set in the containers env, so both commands can pick it up?

**Comment by youngnick** [comment]
Yes, the file is used as a coordination point between the containers, so that we don't need to use network calls, as those network calls could too easily be used for a DoS attack.

**Comment by khayyamsaleem** [comment]
@youngnick I know it's been some time, but would I be able to pick up this ticket? Or is it still required?

**Comment by tsaarni** [comment]
There is now parameter `--ready-file` introduced by PR https://github.com/projectcontour/contour/pull/4084.

Sorry for missing to cross reference this issue from the PR!  I will close this now as resolved.
