### ISSUE TITLE
test/e2e: Run contour on test host, not in k8s cluster so we can swap out contour config flags/file more easily

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#3772]
Should help a lot with gateway e2e tests etc.

We can extract actual k8s things to test to another package (e.g. testing RBAC etc.)

To do:
- [x] Extract upgrade test logic to deploy rendered manifest into something more generic: https://github.com/projectcontour/contour/pull/3793
  - Should be able to decode manifest, modify resources, and redeploy
- [x] In e2e tests no longer rely on Contour existing, deploy instead in tests https://github.com/projectcontour/contour/pull/3803 (for this and the below)
- [x] each e2e test restarts a local contour with different arguments if needed
  - use ginkgo/gexec build to build contour
  - don't need to deploy contour service/deployment etc.
  - beforeeach can specify different args or config file values to customize contour with
  - aftereach shuts contour down
  - use a single justbeforeeach to start up contour, wait for envoy to be healthy
- [x] add "incluster" test suite to explicitly cover incluster things like RBAC etc. https://github.com/projectcontour/contour/issues/3854
- [ ] Improvements to NamespacedTest helper https://github.com/projectcontour/contour/issues/3837
- [ ] extract contour binary from image and use that in local test suite
  - *so we are testing exactly what we release*
  - when a path to a contour binary is specified, use that, otherwise compile contour source

**Comment by youngnick** [comment]
Hopefully #3750 should help here a bit too.

**Comment by sunjayBhatia** [comment]
WIP branch here: https://github.com/sunjayBhatia/contour/tree/e2e-tests-local-contour

Gateway tests passing running contour locally, haven't switched them to use different gateways per test, but that should be easy to do

**Comment by skriss** [comment]
@sunjayBhatia should we close this out now since the core of this is done, and can leave the one or two related followup issues open separately?

**Comment by sunjayBhatia** [comment]
yep sounds good to me 👍🏽

**Comment by skriss** [comment]
Opened #4317 to cover the one additional follow-up, closing this one out.
