### ISSUE TITLE
write design doc for tracing support

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#3792]
ref. #399

**Comment by youngnick** [comment]
Given that I've asked @skriss to work on an update to the ExtensionService design before finishing this, I feel confident this should be moved to at least 1.18, if not later.

**Comment by skriss** [comment]
I'm moving this back to Prioritized Backlog until the team has capacity for this; with all the Gateway changes going on right now this needs to take a back burner.

**Comment by youngnick** [comment]
@skriss is there an issue to cover the ExtensionService redesign work? I can't find one.

**Comment by skriss** [comment]
> @skriss is there an issue to cover the ExtensionService redesign work? I can't find one.

Looks like not, I couldn't find one either.

**Comment by rajatvig** [comment]
Is this work still on the radar?

**Comment by skriss** [comment]
> Is this work still on the radar?

@rajatvig yes it is, it's been on hold for a few reasons but we do want to pick it up again. I see you've commented on https://github.com/projectcontour/contour/pull/3802 so you're aware of that draft doc's existence; if you have any feedback on that doc or can provide any information on your use cases, that would be very helpful for us.

Related to this, We're also hoping to see Envoy add native support for OpenTelemetry tracing soon; the issue tracking that is   https://github.com/envoyproxy/envoy/issues/9958#issuecomment-1028465344.

**Comment by youngnick** [comment]
I created #4324 to cover the work to update ExtensionService's design.
