### ISSUE TITLE
Option to disable access logs

### ISSUE THREAD

**Issue by jroper** [projectcontour/contour#3799]
Access logs are not always needed or desirable. As far as I can see, there is no way to turn envoy access logging off (if there is, please show me!). It should be possible to turn it off.

**Comment by sunjayBhatia** [comment]
You can set the access log files to /dev/null with the “envoy-http(s)-access-log” flags to ensure the logs are not output

**Comment by youngnick** [comment]
That's definitely a good workaround @sunjayBhatia, but it does seem reasonable to have a way to disable access logs if you wish.

I guess that will be even more useful once we finishing implementing tracing (#399), since then you can use the traces instead of trying to parse logs.

**Comment by stevesloka** [comment]
Did you get this working @jroper? I'm going to close, but feel free to reopen if you still have questions.

**Comment by bumarcell** [comment]
Hello, why is this closed? :D

**Comment by sunjayBhatia** [comment]
This was closed due to inactivity/lack of response, if you need this functionality and the workaround listed above is not sufficient, let us know

**Comment by bumarcell** [comment]
Would be perfect if one can disable access-log per Proxy object -just like nginx ingress- 😄

**Comment by sunjayBhatia** [comment]
That is a slightly different feature so would be best to open a fresh issue for that so we can prioiritize!

**Comment by tsaarni** [comment]
I do not know how one would implement per HTTPProxy object control in Envoy, since access logging is configured in HttpConnectionManager (which is not per HTTPProxy). It might require some changes in Envoy.

**Comment by tsaarni** [comment]
Oh ok, maybe it can be possible, but it sounds bit inconvenient to have a single global log filter with (potentially) long AND/OR statement inside it. It sounds bit less hacky to me if someone would implement this on Envoy side :)
