### ISSUE TITLE
kuard-dag.png image not loading

### ISSUE THREAD

**Issue by iamrajiv** [projectcontour/contour#3804]
**On Page:** [https://projectcontour.io/docs/v1.16.0/troubleshooting/contour-graph/](https://projectcontour.io/docs/v1.16.0/troubleshooting/contour-graph/)

**Comment by sunjayBhatia** [comment]
Thanks for the issue! Should be fixed shortly in this PR: https://github.com/projectcontour/contour/pull/3809

Preview of the site: https://deploy-preview-3809--projectcontour.netlify.app/
