### ISSUE TITLE
contour: error: expected argument for flag '--kubernetes-debug', try --help

### ISSUE THREAD

**Issue by jaalle** [projectcontour/contour#3810]
**On Page:** [](https://projectcontour.io/docs/v1.16.0/troubleshooting/contour-debug-log/)

States:

> This flag accepts an integer log level argument, where higher number indicates more detailed logging.

but this should really be:

> This flag **requires** an integer log level argument, where higher number indicates more detailed logging.

because without an integer log level argument, the pod goes into CrashLoopBackOff and error:

> # kubectl logs contour-668d444456-7s8rs --namespace projectcontour
> contour: error: expected argument for flag '--kubernetes-debug', try --help

is reported.

**Comment by skriss** [comment]
@jaalle would you be interested in submitting a PR to clarify this?

**Comment by Patil2099** [comment]
I would love to pick this up.
