### ISSUE TITLE
Adds Gateway Controller Integration Tests

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour#3812]
**Please describe the problem you have**
https://github.com/projectcontour/contour/pull/3773 adds support for testing controller-runtime controllers, starting with the gatewayclass controller. https://github.com/projectcontour/contour/pull/3805 adds a controller-runtime controller to reconcile gateway objects. Tests should be added to exercise the gateway controller.

**Comment by youngnick** [comment]
Full e2e testing will need to wait until after the main Gateway code is in, pushing to 1.18.

**Comment by skriss** [comment]
We opted to go for E2E tests to cover the controllers, and these have been implemented in #3960 (merged) and #3992 (in review).
