### ISSUE TITLE
Docs: Create a "happy path" for a basic installation of Contour

### ISSUE THREAD

**Issue by jonasrosland** [projectcontour/contour#3813]
**Please describe the problem you have**
Based on the docs assessment:
> There's lots of great examples for different configuration and deployment options, but there's no clear "happy path" through the content. I'm a new user and I've decided I want to use Contour. What's considered a "basic" Contour setup and how can I get there?

**Comment by Gabe-GPU** [comment]
Hey Jonas, I would like to work on this issue.

**Comment by skriss** [comment]
I think this is pretty-well covered by the latest https://projectcontour.io/getting-started/ page, which walks through basic installations using YAML, Helm, or the Operator on either a KinD or "normal" (i.e. cloud provider) cluster, so I'm going to close this issue out, but feel free to reopen if you think there's more to do here.
