### ISSUE TITLE
Docs: Make note of the Troubleshooting section where applicable

### ISSUE THREAD

**Issue by jonasrosland** [projectcontour/contour#3816]
**Please describe the problem you have**
From the [docs assessment](https://github.com/cncf/techdocs/blob/main/assessments/0001-contour.md):
> The only place troubleshooting is mentioned is (in the getting started guide)[https://projectcontour.io/getting-started/#troubleshooting]. It's worth emphasizing this elsewhere (i.e. a page in the docs or a mention on the docs landing page).

**Comment by johnnycase** [comment]
I will take this one.

**Comment by jonasrosland** [comment]
Closing thanks to the PR #3830 by @johnnycase , thank you!
