### ISSUE TITLE
Docs: Small styling change for h2 headers

### ISSUE THREAD

**Issue by jonasrosland** [projectcontour/contour#3818]
**Please describe the problem you have**
Based on the [docs assessment](https://github.com/cncf/techdocs/blob/main/assessments/0001-contour.md):

> for `<h2>` elements on documentation pages, change the margin from `margin-bottom: 2rem` to `margin-top: 1rem; margin-bottom: 1rem` or (preferred) `margin-top: 1.5rem; margin-bottom: 0.5rem;`. In general it's better to have padding above an h2 rather than below it, as this helps seperate each section of a page.

**Comment by fanatiicx** [comment]
Hello, I'm new and would like to work on some first issues.

I've been trying to locate `margin-bottom: 2rem`. I was looking in the contour/assets/scss/_components.scss file. Is the `margin-bottom: 2rem` for documentation pages somewhere else? Thanks!

**Comment by jonasrosland** [comment]
Thanks for looking into this @fanatiicx !
I now realize where the error is, this was found on an older version of the site which you can see in an older commit here: 
https://github.com/projectcontour/contour/blob/release-1.15/site/_scss/site/common/_type.scss#L28

This was part of the Jekyll variant of the site, and since we moved over to Hugo there were several elements that got updated at the same time.

So I think this specific issue can be closed, but perhaps there are other stylistic changes that you would recommend?
