### ISSUE TITLE
Docs: Revise the Getting Started guide

### ISSUE THREAD

**Issue by jonasrosland** [projectcontour/contour#3820]
**Please describe the problem you have**
Based on the [docs assessment](https://github.com/cncf/techdocs/blob/main/assessments/0001-contour.md):

> Revise the [getting started page](https://projectcontour.io/getting-started/). Ensure that there is a proper prerequisites list and that new users know where to go next.

**Comment by jonasrosland** [comment]
One of the recommendations is to revise or otherwise use the content on [Contour Philosophy](https://projectcontour.io/resources/philosophy/) as a part of a new getting started guide.

**Comment by youngnick** [comment]
I'd definitely like to review this one, the Philosophy doc is my baby. 😄

**Comment by gary-tai** [comment]
Hi @jonasrosland  - I'm interested in taking this one. I don't know anything about setting up kubernetes, but understand the concept of contour.

How is this different from [Update and clarify our Getting Started docs #3817](https://github.com/projectcontour/contour/issues/3817) ?

**Comment by gary-tai** [comment]
I've split this out into 2 guides:
1. Getting Started with Contour (https://docs.google.com/document/d/1t0Xaym2IXZ9x2dqtNIOO4AcqAIi7akDenbmTaVjirXg/edit?usp=sharing)
2. Getting Started - Contributor's Guide (https://docs.google.com/document/d/1WaQ9RNq4M0ow3iWUMNqGPzn3okDNSmK2vcrP4VGKBmM/edit?usp=sharing)

Link to each has been posted to #contour channel for feedback. Have also rec'd some feedback from Celeste.

Will start Markdown for each.

**Comment by gary-tai** [comment]
PRs submitted for both guide updates:
- PR 3907 - update start contributing
- PR 3924 - quickstart guide

**Comment by gary-tai** [comment]
@jonasrosland - both the quickstart guide (PR 3936) and contributing guide (PR 3907) are in prod now. 

https://github.com/projectcontour/contour/pull/3936
https://github.com/projectcontour/contour/pull/3907

This issue can be closed.

**Comment by youngnick** [comment]
Thanks very much @gary-tai, great work! I'll leave this to @jonasrosland to close out though.

**Comment by skriss** [comment]
We've made a couple rounds of revisions here, closing this out and can open new issues for any further action items.
