### ISSUE TITLE
Support Multiple Gateways

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour#3825]
**Please describe the problem you have**
~~Currently, the operator supports multiple gateways that translate to multiple Contour/Envoy deployments. This is required for Knative. In order to deprecate the gatewayclass/gateway controllers in the operator, Contour must remove `gateway.namespace` and `gateway.name` from the config and support multiple gateways. Each gateway should equal a Contour/Envoy deployment or one contour managing multiple envoy fleets.~~

~~xref: https://github.com/projectcontour/contour/pull/3805~~

Contour is/has changed to only take a Gateway Controller Name to choose what GatewayClass/Gateways to reconcile

Currently a Contour instance+Envoy DaemonSet will serve routes attached to a single Gateway.

Contour needs to appropriately handle multiple Gateways:
- [ ] Initially (for correctness), when multiple Gateways that reference the same GatewayClass exist, only the oldest should reconciled
  - Removes possible conflicts, follows API conflict resolution guidelines
  - Can be implemented ASAP, no dependencies on other features
- [ ] A further feature: when multiple Gateways that reference the same GatewayClass exist, they can be "merged" 
  - This needs more discussion
  - "merged" could mean that compatible listeners between Gateways are merged
  - Could mean that we support more dynamic listener configuration
  - Possibly needs to be done *after* Contour starts managing Envoy since you probably will need to change pod spec
  - Need to take into account endpoint publishing policy

  
cc: @nak3 @Miciah

**Comment by sunjayBhatia** [comment]
Added to 1.19 as this is related to https://github.com/projectcontour/contour-operator/issues/389 which is needed for incremental improvements on contour/operator relationship
