### ISSUE TITLE
Site: Add deprecation style

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3826]
In the old site, we had a "deprecation" style that we could use to call out things that were important to users. It looked something like this: https://web.archive.org/web/20201001071853/https://projectcontour.io/resources/upgrading/

It would be super to have once for deprecated, another for warning, etc such that we can call these things out properly to users.

**Comment by jonasrosland** [comment]
Would this be something you could help out with @fanatiicx ?

**Comment by fanatiicx** [comment]
@jonasrosland Thanks for notifying me. I will leave it for someone else to work on as I have found a couple of other projects that are a better fit for my skills set right now. Best wishes!

**Comment by jonasrosland** [comment]
Sounds good, thanks for letting us know and good luck with your other projects @fanatiicx !

**Comment by gary-tai** [comment]
Found a possible solution here: https://github.com/martignoni/hugo-notice
Four notice types are provided: `warning`, `info`, `note` and `tip`.

Create /site/themes/contour/i1on/en.yaml (add other localizations as needed)
Create shortcode site/themes/contour/layouts/shortcodes/notice.html 
Call shortcode in md:
```
{{< notice warning >}}
Watch out!
{{< /notice >}}
```

![image](https://user-images.githubusercontent.com/85881851/129724443-948ff49b-dd55-42c9-8742-1507573b5006.png)

**Comment by gary-tai** [comment]
For specific "deprecation", need to update:
<style> and <svg> tags in shortcode html.

**Comment by jonasrosland** [comment]
Oh that looks interesting @gary-tai . Would you be able to work on this?

**Comment by gary-tai** [comment]
Yes, I can take it. 

I've reached out to the developer as the first notice box has small top padding, but it doesn't show up in the subsequent notice boxes. Could be something specific with the contour theme.

**Comment by gary-tai** [comment]
@jonasrosland  / @stevesloka - the developer came back with a fix (https://github.com/martignoni/hugo-notice/issues/12). All is working correctly.

Are the native `warning`, `info`, `note` and `tip` notice enough or is there a need for specific "deprecation" notice?

**Comment by jonasrosland** [comment]
I think those would be more than enough :)

**Comment by youngnick** [comment]
+1 from me, those levels are great, thanks.
