### ISSUE TITLE
Add retry_back_off into envoy

### ISSUE THREAD

**Issue by DmitroDemchenko** [projectcontour/contour#3839]
Good morning, currently  there are a lot of useful  params that we can pass via annotations like num-retries, per-try-timeout, retry-on an so on.
Is it possible to configure also retry_back_off / base_retry_backoff_ms ? Because default is 25ms and maximum interval is 10 times in Envoy and I'd like to increase it little beat.
Please help with it.

**Comment by cheshir** [comment]
Hi there. Also looking for a solution to tweak base retry delay a bit.

**Comment by vadim-sychov** [comment]
Recently I faced the same problem, anyone knows how can to solve this?

**Comment by youngnick** [comment]
Thanks for logging this issue @DmitroDemchenko. We can certainly look at adding support for configuring the retry back off. Can I ask how you (and everyone else watching this issue) are configuring Contour?

In general, we try not to add more annotations to our Ingress support, but encourage people to use either HTTPProxy or the forthcoming Gateway API support. That's not to say we won't, but we want to confirm we'll actually be adding a thing you need.

**Comment by DmitroDemchenko** [comment]
Hi, @youngnick , I'm adding Contour in my k8s cluster. Deploying it via helm chart. And I need different ingress resources for my applications. When I configure Ingress resource I use this annotations: 
annotations:
    kubernetes.io/ingress.class: contour
    projectcontour.io/num-retries: "10"
    projectcontour.io/response-timeout: "60s"
    projectcontour.io/retry-on: "5xx,gateway-error,reset,connect-failure"

But I'd like increase time between retries, and found opportunely in envoy do it via  retry_back_off. If it possible now do it another way, not in annotations please let me know.

**Comment by cheshir** [comment]
Hi, @youngnick

I'm using contour in front of hundreds of sites (SEO park). Sites are deployed on GKE preemptible nodes. 
I want to configure backoff to cover scenario when user trying to open site and it's nodes rotates in the same time.

**Comment by xaleeks** [comment]
+1 that this is useful
      
Thanks for sharing @DmitroDemchenko & @cheshir.  If you don’t mind, please also share your usage on this ticket https://github.com/projectcontour/contour/issues/1269
