### ISSUE TITLE
Latest Contour relies on networking.k8s.io/v1 ingress

### ISSUE THREAD

**Issue by Zsolt-LazarZsolt** [projectcontour/contour#3840]
**What steps did you take and what happened:**
I used the latest contour image on an old Kubernetes version.
Contour: Latest
Kubernetes:  v1.16.2

Contour wont start up and I see the following error:
time="2021-06-25T12:19:36Z" level=fatal msg="failed to create informer" error="no matches for networking.k8s.io/v1, Resource=ingresses" resource="networking.k8s.io/v1, Resource=ingresses"

**What did you expect to happen:**
It would be great from a backward compatibility standpoint to not rely on the this resource if not available. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.16+
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version: 1.16.2
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
hey @Zsolt-LazarZsolt, sorry this caused an issue for you. We have our compatibility matrix documented here: https://projectcontour.io/resources/compatibility-matrix/. Our policy is based around supporting the Kubernetes versions that upstream Kubernetes itself supports, i.e. the 3 latest minor versions (see https://kubernetes.io/releases/version-skew-policy/#supported-versions). 

If you're still using Kubernetes 1.18, then I'd suggest sticking with Contour 1.15.1 for now.

**Comment by Zsolt-LazarZsolt** [comment]
@skriss  Thank you for the quick answer. I see what you mean there with the 1.18 and below.
As ingress v1 was only available from kubernetes 1.19 and above.

Thank you for the info. Closing the ticket.
