### ISSUE TITLE
improve Contour config file formatting

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#3843]
xref https://github.com/projectcontour/contour/pull/3694#discussion_r656572797

The formatting of https://github.com/projectcontour/contour/blob/main/examples/contour/01-contour-config.yaml is confusing, because both comments and actual YAML are written with a single leading `#` (with a couple exceptions).

It's also documented [here](https://projectcontour.io/docs/v1.16.0/configuration/#configuration-file), which also includes a commented YAML example.

We should de-dupe all of this and improve formatting. One approach could be:
- the website has the detailed documentation for each field
- `01-contour-config.yaml` includes commented-out config file contents, with *no* field-level documentation, just a link to the website at the top
- the website links to `01-contour-config.yaml` instead of duplicating the YAML example.

**Comment by youngnick** [comment]
I think that documenting the config file is a good idea.

However it ends up looking, I feel like we should do it in an autogenerated way, similar to what we do for HTTPProxy reference docs now, and have the comments/explanations live with the structures that support it somehow. The important parts here is that there's only one place to update, and it gets updated automatically when we update the config file code.
