### ISSUE TITLE
Investigate using e2e tests to collect test coverage

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#3850]
Now that we run contour outside of k8s in the e2e test suite, it would be interesting to see if we could get coverage reports from the tests to enhance our automated checks on changes

Just an idea to start, something to investigate to see if it brings value

**Note** this might be at odds with the goal of testing the same binary we ship in the contour container image in the e2e tests

Notes:
- run contour in e2es in-process with the tests so we can collect coverage stats
- would probably need a dummy test main/abstraction of the existing main etc.
- should increase our coverage %, give us more direct ability to see what is tested when config/flags are added

**Comment by youngnick** [comment]
This is an interesting idea, but I agree that it's really important we check the binary we ship in the image too.
