### ISSUE TITLE
cannot limit request payload size

### ISSUE THREAD

**Issue by RamyChaabane** [projectcontour/contour#3857]
As far as I can tell, there is no config parameter or a kubernetes annotation that limit the size of a request payload (like nginx for instance: nginx.ingress.kubernetes.io/proxy-body-size)

Would be nice if we can have this and send 413 http response to client when he exceeds a certain value

**Comment by xaleeks** [comment]
I think this idea is fairly straightforward and useful to have.

**Comment by RamyChaabane** [comment]
Hi steve
Yes, a global option looks good, and it would be great if we can refine according to HTTP version

**Comment by youngnick** [comment]
So, @RamyChaabane, ideally you'd like to have a request payload size limit like:
- one globally
- one just for HTTP1
- one just for HTTP2, presumably per-stream?

Seems like the more-specific ones would need to override the less specific one in that case.

Also, I think we'll need to do some careful testing to come up with suggested values for these, and document how they work, because it seems from looking at the docs above that it's more complicated than just "only allow this much data to be transferred".

**Comment by RamyChaabane** [comment]
@youngnick ideally yes

**Comment by reicheltp** [comment]
It seems that Envoy supports limiting the requests buffer size globally as well as just for a request: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/buffer/v3/buffer.proto.html#extensions-filters-http-buffer-v3-buffer

I am not that firm yet with the contour architecture but willing to support / create a PR. What steps do I need to take?

**Comment by youngnick** [comment]
Limiting globally sounds like the way to start. If you'd like to create a PR, @reicheltp, that's awesome. As always please check CONTRIBUTING.md in the repo root for the process and stuff, but I think in this case, a configugration file item that defines the buffer size globally would be the right place, and then have that value flow down to the insecure HTTPConnectionManager, and all the secure HTTPConnectionManagers.

If you (or someone else) does decide to have a go, please drop us a line in #contour on Kubernetes Slack if you run into any issues.

**Comment by xaleeks** [comment]
Slightly off topic but an observation is that the question of whether the feature is enabled at the global, route lvl etc comes up constantly.  We should probably have some consistent framework in how we cut these features.  Or we can take Nick’s idea that it’s prioritized based on specificity.  The more specific it’s configured with respect to other entities, the higher the precedence.

And what about limiting the response size based on specific response header?

**Comment by youngnick** [comment]
The problem is that it depends on the feature. For some, it makes sense to have it be set globally first, for others it doesn't make sense to set globally. I don't know if we'll be able to get around doing this on a case-by-case basis.

**Comment by Legionivo** [comment]
Greetings. I have the same question as the author of the issue. How can this be implemented now? 
cc @youngnick  @xaleeks
