### ISSUE TITLE
Issues with traffic splitting based on HTTP Headers

### ISSUE THREAD

**Issue by salaboy** [projectcontour/contour#3859]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I've created this issue in the Knative Project which allows traffic splitting based on headers: 

https://github.com/knative/serving/issues/11621

This feature seems to be working with Kourier but not with Contour. 

**What did you expect to happen:**

I expected it to work as with the other networking implementations. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: The one that is installed with Knative 0.23.0
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
@salaboy Contour definitely supports routing based on headers: https://projectcontour.io/docs/v1.16.0/config/request-routing/#conditions

I just double-checked and header names are case-insensitive; either `x-foo` or `X-Foo` in the header condition are equivalent.

It'd be helpful if you could include the `HTTPProxy` YAML that's being produced by knative - maybe we could track down the issue from there.

**Comment by salaboy** [comment]
@skriss I can definitely give that a try and report back. For some reason the traffic was never routed, even when the header was set to the tag.

**Comment by stevesloka** [comment]
Hey @salaboy just wanted to check in and see how this is going. Were you able to retest?

**Comment by salaboy** [comment]
@stevesloka sorry.. I am a bit complicated as I've just started my new job, but I will try to come back to it during the week.

**Comment by skriss** [comment]
Closing this out as inactive, feel free to reach out again as needed!
