### ISSUE TITLE
Update to CNCF Code of Conduct

### ISSUE THREAD

**Issue by geekygirldawn** [projectcontour/contour#3861]
I noticed that Contour is still using the VMware Code of Conduct, instead of the CNCF one. We have a [Code of Conduct template](https://github.com/cncf/project-template/blob/main/CODE_OF_CONDUCT.md) that you can use. 

cc: @jonasrosland

**Comment by mzrithm** [comment]
I'm happy to take on this issue.

**Comment by sunjayBhatia** [comment]
hey @mzrithm assigned you to this issue 👍🏽

**Comment by mzrithm** [comment]
Thanks, Sunjay!

**Comment by stevesloka** [comment]
Fixed in #4032
