### ISSUE TITLE
Gateway/GatewayClass Finalizers

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3866]
Finalizers were added to Gateway / GatewayClass in #3805 but were removed in #3858 since there were e2e failures. This issue is to describe two things:

- [ ] What the finalizers are meant to be used for (i.e. Creating Envoy infra or extra Gateways to manage say AWS ELBs) [#3797]
- [ ] Implement the finalizers into Gateway/Class and add corresponding tests to validate

I don't think these are required until we start managing Envoy infrastructure which is the next bit to get implemented.

**Comment by skriss** [comment]
Removing this from the 1.22 milestone for now unless it becomes a conformance issue.

**Comment by skriss** [comment]
Closing, replaced by #4732.
