### ISSUE TITLE
Validation of Upstream TLS and Client Certificate with kubernetes.io/tls Secret

### ISSUE THREAD

**Issue by alex1989hu** [projectcontour/contour#3889]
**What steps did you take and what happened:**
Updated already existing and valid `HTTPProxy` with `validation` object to try out feature `Validation of Upstream TLS` . 

The referenced Secret (`caSecret: backend-certificate`) was issued by `cert-manager.io` instance running in Kubernetes cluster. 

The Secret Type is `kubernetes.io/tls` and placed into the same Namespace where `HTTPProxy` is also configured .

The Secret exists:
```sh
kubectl -n dashboard get secrets backend-certificate
NAME                  TYPE                DATA   AGE
backend-certificate   kubernetes.io/tls   3      32h
# See content below
Data
====
ca.crt:   2390 bytes
tls.crt:  1976 bytes
tls.key:  1675 bytes
```

The `HTTProxy` is invalid:
```sh
 kubectl -n dashboard get httpproxies.projectcontour.io dashboard-proxy
NAME              FQDN                         TLS SECRET                              STATUS    STATUS DESCRIPTION
dashboard-proxy   dashboard.health.acme   projectcontour/wildcard-health-cert   invalid   At least one error present, see Errors for details
```

`HTTPProxy` become invalid, here is the error message:
> Service [dashboard-backend-svc:8443] TLS upstream validation policy error: invalid CA Secret "dashboard/backend-certificate": Secret not found

**What did you expect to happen:**
Got a valid `HTTPProxy` due to the fact that the referenced Secret contains `ca.crt`, not doing type checking: `kubernetes.io/tls` vs `Opaque`.

It is not clear why the referenced Secret must be of type `Opaque`.

Reference:
- [Upstream Validation](https://projectcontour.io/docs/v1.17.0/config/upstream-tls/)
- [Client Certificate Validation](https://projectcontour.io/docs/v1.17.0/config/tls-termination/#client-certificate-validation)

**Anything else you would like to add:**
I found some old issues, it is still ambiguous for me why we need `Opaque` Secret:  https://github.com/projectcontour/contour/pull/1714

**Environment:**

- Contour version:
> 1.17.0
- Kubernetes version: (use `kubectl version`):
> Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version:
> Talos (v0.10.4)
- Cloud provider or hardware configuration:
> VMware
- OS (e.g. from `/etc/os-release`):
> Talos (v0.10.4)

**Comment by alex1989hu** [comment]
# Update

It turned out from Pod `contour` log that both **the error message** of `HTTProxy` **and documentation** is wrong.

Contour `(v1.17.0)` is able to use `ca.crt` from the referenced Secret which type is `kubernetes.io/tls`.

As far as I see, it is not mentioned in the documentation but `contour` logs that `ca.crt` shall meet a condition:
> invalid CA certificate bundle: certificate has no common name or subject alt name

Indeed, I had to add Common Name (`CN`) field and regenerate our CA. Once replaced `CA` in the cluster, the error message disappeared from `contour` log.

After this, `HTTProxy` became valid.

## Note for Client Certificate Validation
Only one error log remained in `contour` log:
> invalid TLS certificate: certificate has no common name or subject alt name

Indeed, I had to add Common Name (`CN`) field to Certificate Signing Request. Once replaced the freshly issued certificate, the error message disappeared from `contour` log, and as I expected `HTTProxy` became valid.

## Proposal
1. Rephrase documentation in terms of Secret Type - `Opaque` vs `kubernetes.io/tls` - the latter is also accepted.
2. It is worth to mention that certificate shall have either Common Name (`CN`) or Subject Alt Name (`SAN`)

**Comment by youngnick** [comment]
Ah, thanks for the follow-up @alex1989hu, that's great work. I see we also have #2372 open with a similar issue, I'll have a look into if we document the existing behavior or validate the cert in some other way and remove the CN check.

**Comment by syncer** [comment]
is there anyway to disable the certificate check, we have the same issue and removing the certificate in question from the chain makes the TLS fails on some clients.
```
invalid TLS certificate: certificate has no common name or subject alt name
```

**Comment by youngnick** [comment]
Soiry, @syncer, there is not currently any way to disable the certificate check. It shouldn't be too big a change to change or remove this check, I will see if we can prioritise this one a bit higher.

**Comment by youngnick** [comment]
The action here is to solve #2372 and have a way for Contour to allow certificates that don't have a CN or SAN, one way or another.

**Comment by youngnick** [comment]
I believe that the changes in #4165 should fix this issue, so I'll close this out. Please comment if you find it doesn't work once 1.20 is released.
