### ISSUE TITLE
Example of RDP over contour

### ISSUE THREAD

**Issue by mjschmidt** [projectcontour/contour#3890]
**Please describe the problem you have**
[A clear, concise, description of the problem you are facing. What is the _problem_ that feature X would solve for you?]
It would be really great if Contour had a quick example of RDP over contour. This article seems to believe its supported, but I haven't seen anything in the Contour docs.
https://medium.com/flant-com/comparing-ingress-controllers-for-kubernetes-9b397483b46b

**Comment by OrlinVasilev** [comment]
@mjschmidt can you elaborate a bit more? You have some Windows machine and you want to expose the RDP over the ingress controller ? for me sound like not a Contour area of features :)

**Comment by mjschmidt** [comment]
Ubuntu, but yes.

And okay thank you.
