### ISSUE TITLE
Envoy shutdown-manager and shutdown command flags should be documented and discoverable

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#3899]
Related to https://github.com/projectcontour/contour/issues/3897

It appears documentation on the Envoy shutdown-manager and shutdown command flags are not readily accessible, I had to link to source code to share the `drain-delay` flag.

Instead, they should be documented on the "configuration" page alongside the `contour serve` flags: https://projectcontour.io/docs/v1.17.0/configuration/

**Comment by stevesloka** [comment]
Those are now documented here: https://projectcontour.io/docs/v1.18.1/redeploy-envoy/#shutdown-config-options
