### ISSUE TITLE
deleting a Gateway doesn't remove it from the DAG, still allows HTTPRoutes to be programmed against it

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#3905]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Create Gateway, confirm it's admitted
Delete Gateway, confirm it's gone from the API
Create HTTPRoute using the deleted Gateway
Get route programmed/accessible over HTTP

**What did you expect to happen:**
When the Gateway is deleted from the API, it should be removed from the DAG and Routes should no longer be able to bind to it

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

[This code section](https://github.com/projectcontour/contour/blob/main/internal/controller/gateway.go#L120-L124) calls the `OnDelete` event, however I believe since we dropped the finalizers this is no longer valid -- instead, when a Gateway is deleted, it triggers [this code branch](https://github.com/projectcontour/contour/blob/main/internal/controller/gateway.go#L111-L115) since it's immediately removed from the API. So we should move calling the OnDelete event handler in to that branch.

Note that if/when we re-add finalizers, then any finalizer logic would have to go within a conditional that checks for a non-zero deletion timestamp.

The same goes for GatewayClass since the controller code is very similar.

**Comment by youngnick** [comment]
Oof, great catch, thanks @skriss.

**Comment by skriss** [comment]
I'll try to get this done for 1.18, should be an easy fix 🤞

**Comment by skriss** [comment]
xref #3526

**Comment by skriss** [comment]
This was closed by #3923.
