### ISSUE TITLE
HTTPRoute processing should ensure `/` is prefixed onto path matches

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#3906]
**What steps did you take and what happened:**
Create an HTTPRoute with a path match without a `/` prefix, requests to route are 404ed by Envoy

**What did you expect to happen:**
HTTP requests routed correctly *or* the HTTPRoute is marked as invalid with an condition describing what is wrong

**Comment by youngnick** [comment]
I think we need to either do this, or define that all path matches must start with `/`, and mark the match/route invalid if it doesn't. (I thought we were doing that already, tbh).

**Comment by skriss** [comment]
Looks like we error for `HTTPProxy` if path prefixes don't start with a `/`: https://github.com/projectcontour/contour/blob/main/internal/dag/conditions.go#L60-L62

**Comment by xaleeks** [comment]
I'm going to tag this 1.20.

**Comment by skriss** [comment]
Per https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.PathMatchType:

> PathPrefix and Exact paths must be syntactically valid:

> - Must begin with the / character
> - Must not contain consecutive / characters (e.g. /foo///, //).

Unfortunately it does not say what to do if these conditions do not hold.

**Comment by youngnick** [comment]
Seems like we should be setting a Condition, but I agree that should be specified upstream.
