### ISSUE TITLE
Update Helm Chart to new secure Admin listener setup

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#3943]
Once https://github.com/projectcontour/contour/pull/3934 is merged we should update the Contour Helm chart (here https://github.com/bitnami/charts/tree/master/bitnami/contour) to the new secure by default method of setting up Contour/the Envoy DaemonSet with the Admin Listener on a Unix socket etc.

Note: Be sure to update the README in the helm chart repo for any new fields and call out important ones

**Comment by xaleeks** [comment]
Seems they bumped it https://github.com/bitnami/charts/commit/05f83e513bfb79c0efdc69b8403d4643cf792e58 but it still uses contour 1.18 and envoy 1.19.  I’ve pinged Bitnami team to bump it again to 1.18.1 and 1.19.1 to receive the fix

Something I was able to find out about the bitnami release process is that this chart which is released in their Bitnami Community Catalog (BCC) also drives the version in their downstream TAC (Tanzu Application Catalog).  We’re still chatting about how to keep our releases aligned in a reasonable manner.

**Comment by skriss** [comment]
Looks like this was done in https://github.com/bitnami/charts/pull/7353

**Comment by sunjayBhatia** [comment]
yeah i think this can be called done and closed (someone reopen if needed)

**Comment by xaleeks** [comment]
yup, this can be mitigated in the future by https://github.com/projectcontour/contour/issues/4007
