### ISSUE TITLE
Set a condition if a TLSRoute is invalid

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3946]
If there are no valid clusters or all forwardTos have a weight of 0, the route should get rejected. Need to set a condition on the route stating this happened so users can be made aware. 

_Originally posted by @skriss in https://github.com/projectcontour/contour/pull/3938#discussion_r680026979_

**Comment by xaleeks** [comment]
Can we tag this for v1.20?

**Comment by skriss** [comment]
PR opened to include this in 1.19
