### ISSUE TITLE
Unwanted Parallel Requests

### ISSUE THREAD

**Issue by derekperkins** [projectcontour/contour#3949]
**What steps did you take and what happened:**
is there something in contour that would send out simultaneous requests to multiple backends on a single http call? I have a semi-complex reproducible case, but I can’t seem to narrow down what is happening.

1. Envoy logs a single OPTIONS+GET request to `/signup` . Since this is creating a user, it can only succeed once.
`envoy-xrt4l envoy [2021-08-11T23:21:42.805Z] "GET /signin HTTP/2" 201 - 0 28 1185 1185 "1.1.1.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" "9cf49c44-d8c5-49d3-90bd-2bca95126350" "api.company.com" "1.1.1.1:8080"`
2. This is a non-authenticated endpoint, so it bypasses our standard auth extension service
3. When there is an Authorization header (not sure if this is causing it, but is my only lead so far), it there seems to be N*M requests sent out, where N is the number of upstream pods in the service, and M is a seemingly random retry number, probably happening while the parallel requests are racing. Not every pod gets a request, some pods get multiple and some get none
4. I’ve seen 4 retries across 3 pods, where only 1 of 12 succeeded, but the web client / envoy logging only ever shows the successful response

I’m running 1.18.0 on GKE and I don’t have any retries set up in my HTTPProxy. All I have are cors and auth, plus standard includes. I know that there is a pattern where services are set up to request from multiple upstream providers and return the first/best response, but that is definitely not expected or wanted here.

**Anything else you would like to add:**

- My k8s service is a headless service
- I can't replicate this on any other endpoints, authed or not

**Environment:**

- Contour version: 1.18
- Kubernetes version: 1.20.8-gke.900
- Kubernetes installer & version: GKE
- Envoy is running as a daemonset, per the standard example yaml installation
- Custom settings in 01-contour-config.yaml

```
  timeouts:
     request-timeout: infinity
     connection-idle-timeout: 60s
     stream-idle-timeout: 30m
     max-connection-duration: infinity
     connection-shutdown-grace-period: 5s
```

**Comment by derekperkins** [comment]
I've tested it and the same behavior happens in 1.16.0 and 1.17.1 with the exact same config.

**Comment by derekperkins** [comment]
It appears to be sourcing outside of the cluster somehow, hitting a duplicate endpoint. Sorry for the noise.

**Comment by youngnick** [comment]
No problems, glad it was resolved, I was pretty worried about how we could be doing this one!
