### ISSUE TITLE
HTTPPROXY root becomes invalid after deleting a delegated HTTProxy in anothe namespace

### ISSUE THREAD

**Issue by a5a5a9** [projectcontour/contour#3961]
**What steps did you take and what happened:**
I delete one of the httpproxy in another namespace and it invalidates the httpproxy root .

**What did you expect to happen:**

The HTTPProxy Root needs to be in valid state at all times even thought one of its delegated httpproxy in another namespaces is deleted.

**Anything else you would like to add:**
Scheme: 

httpproxy in httpproxy-roots

httpproxy1 in namespace1
httpproxy2 in namespace2
httpproxy3 in namespace 3

**Environment:**

AWS EKS

**Comment by stevesloka** [comment]
#3824 is now merged so I think this can be closed and this will be included in Contour v1.19 @a5a5a9.
