### ISSUE TITLE
move off off docker.io

### ISSUE THREAD

**Issue by jayunit100** [projectcontour/contour#3998]
**What steps did you take and what happened:**

I think the default docker images for contour are still on dockerhub...
```
docker.io/projectcontour/contour:v1.18.1
```

**What did you expect to happen:**
given rate-limiting, maybe we should default the docker images from contour to gcr.io or some other public bucket?

**Comment by youngnick** [comment]
#3366 also covers this work, although reviewing it, I probably should close that out and open an implementation issue.

**Comment by skriss** [comment]
Todo list:
- [X] Start pushing to GHCR in parallel with Docker Hub, for both main and tag builds. Continue to reference the Docker Hub image in examples & CI for now. This will let us confirm everything is working with GHCR.
- [ ] Publicize that we'll be migrating to GHCR and we'll stop pushing to Docker Hub after release v1.2x (maybe v1.21?)
- [ ] Continue pushing to both registries, but switch example YAML & all other refs over to GHCR. Ideally we can do this for the 1.19 release if everything's in order, to start the migration (#4010 and https://github.com/projectcontour/contour-operator/pull/439).
- [ ] After the release we decide on from Step 2 (e.g. v1.21), turn off the Docker Hub push. Existing images will be left there indefinitely for posterity, but no new images will be pushed.
- [ ] Manually push the last ~year's worth of release-tagged images from Docker Hub to GHCR, just so they're all there.

**Comment by skriss** [comment]
Last step can be done after v1.21 is released.

**Comment by skriss** [comment]
Since we're moving to quarterly releases, I'm going to propose that the upcoming 1.20 release be the last one where we push images to docker.io.
