### ISSUE TITLE
support Host header rewrites per-service

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4002]
Currently, Contour supports rewriting the `Host` header at the route level only. It's explicitly disallowed at the per-service level, because Envoy did not historically support it. As of Envoy 1.19.0, however, setting `host_rewrite_literal` for an individual weighted cluster is now supported (see https://www.envoyproxy.io/docs/envoy/v1.19.0/version_history/current#new-features), so Contour should expose this functionality.

**Comment by xaleeks** [comment]
seems nice to have, tagging it v1.21 tentatively

**Comment by adnanhb** [comment]
Hi, I would like to work on this feature if it is still unassigned. Can someone assign it to me?

**Comment by sunjayBhatia** [comment]
assigned @adnanhb, let us know if you have any questions about how to proceed!

**Comment by sunjayBhatia** [comment]
@adnanhb are you still working on this? let us know if you need anything from us or if we should reassign this issue

**Comment by adnanhb** [comment]
> 



> @adnanhb are you still working on this? let us know if you need anything from us or if we should reassign this issue

Sunjay, i have completed the implementation, just need to get around to testing it. I will revert back with a PR soon.

**Comment by skriss** [comment]
- processing HTTPProxy request headers policy for a route: https://github.com/projectcontour/contour/blob/main/internal/dag/httpproxy_processor.go#L701
- processing HTTPProxy request headers policy for a single service within a route: https://github.com/projectcontour/contour/blob/main/internal/dag/httpproxy_processor.go#L877

The latter does not allow the `Host` header to be rewritten (https://github.com/projectcontour/contour/blob/main/internal/dag/policy.go#L124-L126), however now that Envoy supports it on a per-Service/Cluster basis via host_rewrite_literal (see https://www.envoyproxy.io/docs/envoy/v1.19.0/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-weightedcluster-clusterweight-host-rewrite-literal), Contour can allow it.

**Comment by skriss** [comment]
cc @vmw-yingy @fangfpeng
