### ISSUE TITLE
External Authorizer HTTP support?

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour#4031]
### Discussed in https://github.com/projectcontour/contour/discussions/4030

<div type='discussions-op-text'>

<sup>Originally posted by **danthegoodman1** September 14, 2021</sup>
Looking at the docs: https://projectcontour.io/docs/v1.16.0/config/api/#projectcontour.io/v1.AuthorizationServer

> AuthorizationServer configures an external server to authenticate client requests. The external server must implement the v3 Envoy external authorization GRPC protocol (https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/external_auth.proto).

I was wondering if there were any plans to support HTTP based authorizers so that we could us something like Ory Oathkeeper or a custom HTTP based authorizer?</div>

This seems like a reasonable request. It's big enough that it will need a design, and probably should come after we finish looking at tracing (#399) and the associated ExtensionService redesign (ExternsionService is the mechanism we currently use for configurint external authentication, so I would imagine we'll use a similar mechanism for authorization).

**Comment by m-ibrahim-y42** [comment]
Any updates regarding adding this feature?

**Comment by sunjayBhatia** [comment]
@m-ibrahim-y42 currently this is not on the roadmap for changes maintainers are working on currently, we would be looking for community contributions to champion this going forward

If you are able to contribute that would be great! We can help with the steps needed to get you going
