### ISSUE TITLE
ContourConfiguration CRD should allow custom SecurityContexts for Envoy DaemonSet

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#4039]
See original request from the operator: https://github.com/projectcontour/contour-operator/pull/398

**Comment by xaleeks** [comment]
can we tag a release that you think is appropriate? @sunjayBhatia

**Comment by skriss** [comment]
This should be unblocked now and can be added to the `ContourDeployment` CRD spec and implemented in the Gateway provisioner, unfortunately probably won't make 1.21.
