### ISSUE TITLE
ContourDeployment CRD should allow custom SecurityContext for Contour deployment

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#4040]
See original request from the operator: https://github.com/projectcontour/contour-operator/pull/398

**Comment by xaleeks** [comment]
can we tag a release that you think is appropriate? @sunjayBhatia

**Comment by sunjayBhatia** [comment]
tagged as 1.20 but really depends on our progress using the ContourDeployment CRD in the operator etc.

**Comment by skriss** [comment]
This should be unblocked now and can be added to the `ContourDeployment` CRD spec and implemented in the Gateway provisioner, unfortunately probably won't make 1.21.
