### ISSUE TITLE
Support Keycloak for authentication

### ISSUE THREAD

**Issue by xaleeks** [projectcontour/contour#4045]
> This issue is a sub-task of the epic https://github.com/projectcontour/contour/issues/2664

support authentication with Keycloak for http/https requests. Contour in this instance should act as a client to relay the request to an Keycloak server for authentication before letting the request through to upstream services.

opportunistic: consider implementing this at the virtualhost granularity so different routes can use different auth backends (LDAP, OIDC, managed tokens like Vault), although I don’t think this is P0. Most enterprises use one authN identity provider.

**Comment by rob-elschot** [comment]
@xaleeks As a bit of feedback from a user. My question is why're you making all this? There are solutions that solve this issue. Its a lot a integration hassel to add all the Authentications mechanism and keep them up to date. Maybe given the function of contour its better to support for instance https://github.com/oauth2-proxy/oauth2-proxy. Then you can maintain 1 interface and have them do all the integration with the authentication providers. Then you only need to maintain the https://projectcontour.io/docs/v1.18.0/config/client-authorization/

**Comment by youngnick** [comment]
Thanks for the feedback @rob-elschot - I think I tend to agree, I'd rather us settle on some solutions and validate they work for all these use cases than add this support into Contour directly.

I believe that @xaleeks is logging these to remind us to check that whatever we end up doing works with each of these things rather than suggesting that we implement them directly in Contour.

**Comment by xaleeks** [comment]
Thanks for the feedback Rob.  This ticket is really meant to represent a need for a validated solution for supporting Keycloak, and other IDPs as separate tickets as you've mentioned.  I tend to just log the request as they land on my plate from customers and users.
