### ISSUE TITLE
Website architecture update

### ISSUE THREAD

**Issue by gary-tai** [projectcontour/contour#4057]
Outcome from meeting with @youngnick and @OrlinVasilev to review and plan architecture changes to the projectcountour.io website.

PLAN
Top Navigation Menu:
1. Getting Started page remains as is
2. Documentation landing page contains current files plus guides (version specific) and resources
2. Community landing page contains community information and any community resources
3. Blog page remains as is  

Note: remove Guides and Resources from top navigation and add them under Documentation

Action Items:
1. Move /content/resources/ to /docs/resources/, except upgrade.md
2. Upgrade.md needs to be version specific (edit and located in each version)
3. Table of Contents (TOC) in Documentation needs accordion menu (issue 3814)
4. Make /content/guides/ version specific (issue 3829)
5. Have consistent TOC (e.g. https://projectcontour.io/resources/philosophy/)
6. Update top navigation items (Getting Started / Documentation / Community / Blog)
6. Update site-contribution doc to reflect new architecture

**Comment by youngnick** [comment]
I'm +1 on this plan, obviously.

Next steps here, I think:
- See if we can make a mockup or rough outline of what the site will look like (doesn't need to be perfect, just an indication), and have the community take a look.
- Break out the todo items above into individual issues so they can be picked up. I think we'll need to clearly indicate any ordering concerns though (moving things needs to come before fixing TOC, for example).

**Comment by OrlinVasilev** [comment]
![image](https://user-images.githubusercontent.com/7236111/135271748-e49672f4-89b3-4c51-9b37-db5deb048b0f.png)

**Comment by skriss** [comment]
Overall +1 on this, glad to see some thoughtful reorganization here!

> Documentation landing page contains current files plus guides (version specific) and resources

`Resources` currently looks like it's all videos -- talks and tutorials about Contour. Not sure if that makes sense to move under `Documentation` -- maybe we could just rename it to something more specific like `Videos` or `Talks` and leave it at the top level?

Also -- I believe you all are thinking about this, but wanted to call out explicitly that our Docs TOC can use some work as it's grown "organically" and isn't always the easiest to navigate if you don't already know what you're looking for. We should figure out how best to organize that -- perhaps split between high-level conceptual info, reference docs, task-oriented docs, troubleshooting, etc., and then with further subcategories below that. FWIW I've always sort of liked how Istio organizes things -- see https://istio.io/latest/docs/

**Comment by youngnick** [comment]
> `Resources` currently looks like it's all videos -- talks and tutorials about Contour. Not sure if that makes sense to move under `Documentation` -- maybe we could just rename it to something more specific like `Videos` or `Talks` and leave it at the top level?
Ah, I think I missed that in the description - in the meeting we talked about this moving under the `Community` page. Renaming to `Videos` or `Talks` sounds good to me.

**Comment by gary-tai** [comment]
The landing page for projectcontour.io/resources refers to the file /content/resources/_index.html and contains links to YouTube videos.

The files under /content/resources/ to move are faq, how we work, philosophy, etc.

**Comment by skriss** [comment]
I'd love to see the [docs landing page](https://projectcontour.io/docs/v1.19.1/) look more like Istio's, where it essentially summarizes the table of contents and what each section is for: https://istio.io/latest/docs/

**Comment by skriss** [comment]
Another related issue that'd be great to tackle as part of this: Contour supports 3 different APIs (HTTPProxy, Ingress, Gateway API), each of which enable a different subset of Contour's features. However, our website primarily focuses on HTTPProxy; Ingress only gets [a single page](https://projectcontour.io/docs/v1.20.1/config/ingress/) with some occasional content sprinkled elsewhere, and Gateway API only has [a guide](https://projectcontour.io/guides/gateway-api/).

I would love to see some way to bring these all together, so that for each topic, e.g. [request routing](https://projectcontour.io/docs/v1.20.1/config/request-routing/), we can capture how to do this for each of the 3 different APIs, or indicate when a certain API does not enable the feature.
