### ISSUE TITLE
Performance Regression v1.8.1 => v1.18.1

### ISSUE THREAD

**Issue by dprotaso** [projectcontour/contour#4058]
### Problem

A Knative user [recently reported](https://knative.slack.com/archives/C93E33SN8/p1632319040135700) that when their cluster had around 1000 Knative Services (~4k HTTPProxy) deploying new Services would take O(minutes).  They mentioned earlier versions did not see such delays.

### Context

First Knative has a two contour instances - one for external ingress and the other only for cluster local traffic. Readiness is defined by our controllers probing the envoy proxies for all the desired FQDN and waiting to receive a 200 OK.

We create 4 HTTPProxies for every Knative Service - ie. https://gist.github.com/dprotaso/13561f973e44d119d66326d2cdc68173

This is because we add 4 FQDN 
- (external) foo-test.default.example.com
- (internal) foo-test.default
- (internal) foo-test.default.svc
- (internal) foo-test.default.svc.cluster.local

### Test Setup

I wanted to compare the performance of Contour v1.8.1 against v1.18.1 to rule out any regressions there

#### Cluster Setup
```sh
#!/bin/bash -e

function create_cluster() {
  local CLUSTER_NAME=dave-knative
  local CLUSTER_ZONE=us-east1-d
  local CLUSTER_VERSION=${1:-latest}
  local CLUSTER_NODES=10

  shift 2>&1 > /dev/null

  gcloud container clusters create $CLUSTER_NAME \
    --cluster-version $CLUSTER_VERSION \
    --enable-autoscaling \
    --machine-type=e2-standard-4 \
    --addons=NodeLocalDNS \
    --min-nodes=$CLUSTER_NODES \
    --max-nodes=$CLUSTER_NODES \
    --num-nodes=$CLUSTER_NODES \
    --zone=$CLUSTER_ZONE \
    --scopes=cloud-platform \
    "$@"

  kubectl create clusterrolebinding cluster-admin-binding \
    --clusterrole=cluster-admin \
    --user=$(gcloud config get-value core/account)
}

function install_serving() {
  kubectl apply -f https://github.com/knative/serving/releases/download/v0.26.0/serving-crds.yaml
  kubectl apply -f https://github.com/knative/serving/releases/download/v0.26.0/serving-core.yaml
  kubectl apply -f https://github.com/knative-sandbox/net-contour/releases/download/v0.26.0/contour.yaml
  kubectl apply -f https://github.com/knative-sandbox/net-contour/releases/download/v0.26.0/net-contour.yaml
  kubectl patch configmap/config-network \
    --namespace knative-serving \
    --type merge \
    --patch '{"data":{"ingress.class":"contour.ingress.networking.knative.dev"}}'
}

create_cluster
install_serving
```

Note: To test Contour v1.8.1 the above script was altered to install the following contour version

```
kubectl apply -f https://github.com/knative-sandbox/net-contour/releases/download/v0.18.2/contour.yaml
```

Additional note: When testing on GKE bump the resource quota so that you can create about `3000` K8s Services - default quota is 1500 which will stall the tests

#### Running the tests

We just simply create 1000 Knative services serially

```bash
#!/bin/bash -e

for i in $(seq 1 1000); do
  kn service create foo-$i --image=gcr.io/knative-samples/autoscale-go:0.1 || true
done
```

### Gathering the data

Here we capture a CSV output which includes the Service's creation time and the `Ready` Time.

```
kubectl get ksvc -ojsonpath='{range .items[*]}{.metadata.name},{.metadata.creationTimestamp},{.status.conditions[?(@.type=="Ready")].lastTransitionTime}{"\n"}{end}' | pbcopy
```

### Comparing the results

I plotted the 'Time to Ready' to visualize the performance regression

#### Contour v1.8.1

<img width="801" alt="Screen Shot 2021-09-28 at 9 59 19 AM" src="https://user-images.githubusercontent.com/18562/135101955-c0072673-1d15-4c3c-bd3d-034e90ebef03.png">

#### Contour v1.18.1

<img width="741" alt="Screen Shot 2021-09-28 at 9 59 14 AM" src="https://user-images.githubusercontent.com/18562/135101990-8952691e-1990-431f-b11d-e4e0696f6eee.png">

**Environment:**

- Kubernetes version: (use `kubectl version`): v1.20.10-gke.1600
- Cloud provider or hardware configuration: GKE

**Comment by skriss** [comment]
I'm looking into this, collecting more data across some different versions of Contour to try to narrow down the issue.

**Comment by skriss** [comment]
See #4061 for what I'm pretty confident is the issue/fix. This would've been introduced way back in Contour 1.9.0. Still doing some testing on it to verify, but the runtime graph looks great.

**Comment by dprotaso** [comment]
Just an FYI - Contour 1.14

<img width="644" alt="Screen Shot 2021-09-29 at 12 17 58 PM" src="https://user-images.githubusercontent.com/18562/135308674-7b7b6be9-8bc5-4097-9cee-10e2ad373663.png">

**Comment by skriss** [comment]
The 1.14 graph looks very consistent with the 1.18.1 one, so I think that's a decent sign we didn't have further performance regressions there.
