### ISSUE TITLE
Allow set contour to match ingress objects without ingress class

### ISSUE THREAD

**Issue by elmariofredo** [projectcontour/contour#4060]
## What
It would be handy to allow to

1. Set ingress class for contour
2. Allow ingress object without ingress class set to be matched by contour

at the same time.

Currently there is only possibility to have and match ingress class or don't have ingress class at all according to [code](https://github.com/projectcontour/contour/blob/main/internal/ingressclass/ingressclass.go#L50)

```go
	// If Contour's configured ingress class is empty, the object can either
	// not have an ingress class, or can have a "contour" ingress class.
	if contourIngressClass == "" {
		return objIngressClass == "" || objIngressClass == DefaultClassName
	}
```

We could add additional option to allow ingress without ingress class to be matched to mimic [default ingress class](https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class) behaviour.

## Why

It would be great to allow catch all ingress scenario for teams which doesn't care about which ingress controller is used for their ingress traffic. Also most community helm charts are not picking up with ingressClass property 😔.

**Comment by stevesloka** [comment]
You should't be required to set an ingress class and should work the way you described. Contour will process any ingress object that doesn't have a class or the class is "contour" by default if the class is not specified as a flag to Contour.

**Comment by elmariofredo** [comment]
Sure, but ingress class is a must in multi ingress environment. Even if you don't have a multiple ingresses it's a good practice for future infrastructure changes.

**Comment by elmariofredo** [comment]
@skriss @xaleeks yes! I'm closing this. Sorry didn't know that this is handled on k8s side and not the controller.

Thanks!
