### ISSUE TITLE
Exact path match for HTTPProxy

### ISSUE THREAD

**Issue by tapih** [projectcontour/contour#4069]
It'd be nice to have exact patch match for HTTPProxy.
HTTPProxy seems to support only prefix path match, even though exact path match is included in [this design document](https://github.com/projectcontour/contour/blob/main/design/routing-design.md#exact-match).
Now, I need to configure a route for exact '/' and a route for prefix '/' at the same time, and I have no idea how to do it with HTTPProxy.

**Comment by arjunsalyan** [comment]
Hi @xaleeks @stevesloka , I was trying to build this functionality for an internal use case of our organisation, and it did seem to work fine for us. I have created https://github.com/projectcontour/contour/pull/5000 (still a great deal is left to be worked upon along with documentation).

I would really appreciate some help in covering the edge cases I missed and other guidelines that we generally follow as this would by first time trying to contribute to Contour.

Also, if the PR looks satisfactory this could be assigned to me.
