### ISSUE TITLE
TLS termination with upstream TLS

### ISSUE THREAD

**Issue by tluzon-digibank** [projectcontour/contour#4073]
I have an HTTPProxy which uses **authorization**, thus requiring TLS as well as it to be terminated in contour.
My upstream service is running secured http, so I need "upstream TLS".
Unfortunately when **TLS termination** is active, **upstream TLS** cannot be used.

**Comment by tsaarni** [comment]
Hi @tluzon-digibank! [upstream TLS](https://projectcontour.io/docs/v1.18.2/config/upstream-tls/) is intended to be used together with TLS termination in Contour. It will create another TLS connection between Contour/Envoy and the upstream service, splitting the TLS connection into two separate "legs", external and internal. Could you describe bit more what kind of setup you have and what problems you have with it?

**Comment by skriss** [comment]
Closing this out as inactive, feel free to reopen/reach out again as needed.
