### ISSUE TITLE
Envoy xDS config: Use string_match in HeaderMatcher once deprecation/release cycle passes

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#4076]
See release notes for Envoy 1.20.0: https://www.envoyproxy.io/docs/envoy/v1.20.0/version_history/current

```
http: the HeaderMatcher fields exact_match, safe_regex_match, prefix_match, suffix_match and contains_match are deprecated by string_match.
```

The wrinkle here is that `string_match` was added in Envoy 1.20.0 and does not exist in `1.19.x` so we cannot use this field as soon as we bump to 1.20.0, otherwise we will send invalid config to Envoy instances that have not been updated yet in a rolling deploy. Instead we have to start using this in a release after we release a Contour compatible with 1.20.0.

This should look like:
- Contour X, released with Envoy 1.20.0: keep as is, use specific matchers not `string_match`
- Contour Y, released with Envoy >=1.20.0, use `string_match`

**Comment by khayyamsaleem** [comment]
Hello! Would I be able to take up this issue, if it is currently unassigned?

**Comment by sunjayBhatia** [comment]
sure @khayyamsaleem please let us know if you need any help or pointers

also note a PR for this won't be merged until *strictly after* Contour 1.20.0 is cut, as per the notes in the description

**Comment by khayyamsaleem** [comment]
@sunjayBhatia would it be a bad idea to add in code that only uses the appropriate matchers conditionally depending on the Contour version? that way, this code could be merged sooner than the 1.20.0 release. I don't know if there is precedent for this kind of feature-flag-esque implementation in the contour codebase.

**Comment by khayyamsaleem** [comment]
Spoke with @sunjayBhatia on the above comment, seems something like this is already under consideration per #3573 . Going to implement this without the version-based flag for now.

**Comment by sunjayBhatia** [comment]
@khayyamsaleem are you still working on this? we would be able to merge your changes into `main` since we're working on the 1.21.0 release now
