### ISSUE TITLE
Envoy daemonset lifecycle

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#4078]
The examples in Contour use a Kubernetes daemonset to deploy Envoy inside the cluster, however, if the cluster is scaled down (i.e. number of nodes decreased), then connections can be dropped since the `preStop` hooks never fire to allow the shutdown-manager to allow for those connections to be drained from that specific Envoy instance. 

In the event a node is forcibly drained (e.g. kubectl drain <node>) or scaled down, kubernetes doesn't tell the daemonset pod that this event is happening and the pod is simply terminated. For all other updates it works fine (e.g. updating manifest or images).

I have a [WIP PR](https://github.com/projectcontour/contour/pull/4063) which moves away from a daemonset to a deployment using a `podAntiAffinity` which should make sure that no two instances of Envoy reside on the same node mirroring how daemonsets work. The problem now is that you don't get an envoy instance per node (which might be a good thing in the end for some users). It seems silly to run that much infra on your nodes if you needs don't warrant (eg. you have a 50 node cluster, 50 instances of Envoy might be a bit overkill). But also, you'd have to think about external traffic policy as well as any hostPort mappings since you can't guarantee that each node is still running an Envoy instance. 

You've also got to scale the deployment size dynamically to the right size for your cluster and workloads. Contour could manage this once you get managed Envoy, but for now, a user would just need to determine the count and go from there.

Another alternative might be to have the shutdown manager look for node readiness state, then if it sees it allow Envoy to shutdown properly. That would blend the benefits of the daemonset, but still reduce the number of dropped connections. 

We might need to add a deployment example (as in #4063) along side the daemonset deployment. #4063 removed the daemonset just to see how it might work, but there are still use cases for daemonsets that would lend us to keep both examples.

Also related is #4077 to explain the above bits better in our docs.

**Comment by skriss** [comment]
@stevesloka can this be closed now that the Envoy deployment example & docs have merged, or did you have further specific work items in mind?
