### ISSUE TITLE
HttpProxy status/status description is coming empty

### ISSUE THREAD

**Issue by om3171991** [projectcontour/contour#4114]
**What steps did you take and what happened:**
We have deployed contour through helm chart (bitnami-4.1.3) and HTTP-proxy as part of application deployment but no status/status description is updated like below :

**NAMESPACE   NAME                      FQDN                TLS SECRET           STATUS   STATUS DESCRIPTION
test-ns                test-http-proxy       test.abc.com    star**           

Also as part of contour installation, we have passed below extraAgrs but if we pass any dummy/invalid ingress class name as well, then HTTP-proxy doesn't show any status as invalid or something else.

**extraArgs: ["--ingress-class-name=contour-public"]**

**What did you expect to happen:**

Proper status/description should be displayed.

**Environment:**

- Contour version: 1.12
- Kubernetes version: (use `kubectl version`): 1.20.7
- Cloud provider or hardware configuration: Azure

@stevesloka @youngnick

**Comment by skriss** [comment]
Closing this out, feel free to reach out again as needed.
