### ISSUE TITLE
Gateway API: implement ListenerStatus for Gateways

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4124]
ref. https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.GatewayStatus

We need to populate the `gateway.status.listeners` field with supported kinds, # of attached routes, listener-specific conditions, etc.

**Comment by skriss** [comment]
Working on this now.

**Comment by youngnick** [comment]
Will this include changes to the operator to pull the code there out?

**Comment by skriss** [comment]
I'll double-check but I'm pretty sure there's nothing in the operator that sets any gateway status anymore (and I don't think it had ever gotten to setting listener status specifically).

**Comment by youngnick** [comment]
Awesome, thanks. I think it's particularly important that when we are ready to cut 1.20-rc1, we have a working flow for the Operator to do Gateway API.

**Comment by skriss** [comment]
ref. 3529
