### ISSUE TITLE
Contour ingress controller deployment

### ISSUE THREAD

**Issue by micron1390** [projectcontour/contour#4129]
Hello,

I can not connect contour with the ELB balancer, I registered a private address in loadBalancerIP: "192.168.0.10", but the balancer does not listening ports 80, 443 
It is possible to bind ELB to kubespray ?
> helm install contour bitnami/contour --namespace=kube-system -f values.yaml

> NAME: contour
>LAST DEPLOYED: Fri Oct 22 00:33:13 2021
>NAMESPACE: kube-system
>STATUS: deployed
>REVISION: 1
>TEST SUITE: None
>NOTES:
>Get Contours's load balancer IP/hostname:
>NOTE: It may take a few minutes for this to become available.
>You can watch the status by running:
>$ kubectl get svc contour-envoy --namespace kube-system -w
>Once 'EXTERNAL-IP' is no longer '<pending>':
>$ kubectl describe svc contour-envoy --namespace kube-system | grep Ingress | awk '{print $3}'
>Configure DNS records corresponding to Kubernetes ingress resources to point to the load balancer IP/hostname found in step 1

Thank you in advance.

**Comment by skriss** [comment]
Closing this out as inactive, feel free to reach out again as needed!
