### ISSUE TITLE
Contour config disableAllowChunkedLength setting not working as expected.

### ISSUE THREAD

**Issue by ravilr** [projectcontour/contour#4140]
**What steps did you take and what happened:**
Envoy's `allow_chunked_length`  setting is unintentionally negated here https://github.com/projectcontour/contour/blob/v1.19.1/internal/xdscache/v3/listener.go#L268  during the recent configuration crd feature refactor.

the contour config `disableAllowChunkedLength` is double negated in code in two places instead of expectedly in only one place. 

**What did you expect to happen:**
Setting `disableAllowChunkedLength: false` in the contour configmap should set `allow_chunked_length: true` in envoy config httpconnectionmanager listeners.

**Environment:**

- Contour version: v1.19.1
- Kubernetes version: (use `kubectl version`): v1.22.2

**Comment by sunjayBhatia** [comment]
started working on this and refactoring to make sure it was tested and went down a long path of changes to the `ListenerConfig` etc. that got a bit out of hand

going to push a more tactical fix but generally this falls under the purview of improvements/refactors we can do to make the interfaces between components cleaner, theres a lot of duplication between validation done in `cmd/contour` as well as missed test coverage over small things like this

some of it is to do with the fact that we often don't separate the test code out of the package under test, and have shortcuts to test using non-exported funcs/methods
