### ISSUE TITLE
release v1.18.3 with the RetryPolicy fix

### ISSUE THREAD

**Issue by xaleeks** [projectcontour/contour#4168]
We need to backport / cherrypick the RetryPolicy fix (https://github.com/projectcontour/contour/pull/4135) that we implemented in the latest v1.19.1 to the 1.18.x as well.  There are users that are still actively using v1.18 because they are not ready to upgrade their k8s version yet.

**Comment by xaleeks** [comment]
assigning to @youngnick first

**Comment by youngnick** [comment]
Okay, I will sort out a 1.18.3 release, containing just this fix.

**Comment by youngnick** [comment]
Release 1.18.3 is out, for both Contour and the Operator.
