### ISSUE TITLE
Gateway API: Cross namespace TLS certificateRefs does not work

### ISSUE THREAD

**Issue by nak3** [projectcontour/contour#4181]
**What steps did you take and what happened:**

- As per [Cross namespace certificate references](https://gateway-api.sigs.k8s.io/v1alpha2/guides/tls/#cross-namespace-certificate-references), Gateway should support cross namespace certificate.
- But contour always looks for the secret in the Gateway namespace as per the following code `Namespace: p.source.gateway.Namespace`:

https://github.com/projectcontour/contour/blob/941d33738949e231005cc2167547d654e3b98a52/internal/dag/gatewayapi_processor.go#L271

**What did you expect to happen:**

- [Cross namespace certificate references](https://gateway-api.sigs.k8s.io/v1alpha2/guides/tls/#cross-namespace-certificate-references) should work as per Gateway API doc.

**Environment:**

Contour installed via the yaml (2021/Nov/15):

```
CONTOUR_OPERATOR_VERSION="main" # This is for controlling which version of contour-operator we want to use.
YAML_URL="https://raw.githubusercontent.com/projectcontour/contour-operator/${CONTOUR_OPERATOR_VERSION}/examples/operator/operator.yaml"
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-19T11:52:07Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T20:01:24Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by skriss** [comment]
Yep, this hasn't been implemented yet since it wasn't documented as part of "Core" support for ReferencePolicy, but agree we should get to this. Thanks for filing the issue @nak3.
