### ISSUE TITLE
Improve Contour's operability and observability

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour#4188]
Contour's operability and observability is good enough that we don't receive many compaints about them (that I've seen, anyway).

But it's been a long time since we've gone over the metrics available, the dashboards we provide in our Grafana example, and other things that make Contour easy to operate and manage.

This Epic is to cover work to review these things and see if they can be improved. Some things that I've thought of when looking over our provided dashboards:
- Our Grafana dashboards have some great info in them, but we only provide them as part of the included install of Grafana, which makes them difficult to bring into another install. Can we split them out somehow so that they're easier to consume?
- Have Contour or Envoy added any metrics that would be useful to highlight in our provided dashboards?
- Some of the metrics are useful when you know Contour well, but can be hard to understand if you don't. Can we add more explanation to the provided dashboards?

Other areas I think are worth covering:
- We've added some great information in Conditions in HTTPProxy status, and Gateway API objects also have good information in their Conditions. Is it worth us writing up a newer troubleshooting guide that takes this into account?
- What other ways can we make the Contour troubleshooting experience easier?

**Comment by xaleeks** [comment]
I think the docs could be improved somewhat for a first time prometheus users, right now it assumes pretty good understanding of how it works. Maybe it’s obvious to some uses but maybe some kind of basic guide on how to get prometheus running and how to get the desired metrics.

**Comment by xaleeks** [comment]
>Have Contour or Envoy added any metrics that would be useful to highlight in our provided dashboards? 

rate limited requests?
