### ISSUE TITLE
Externalize 'use_remote_address' from Envoy

### ISSUE THREAD

**Issue by digibank-rons** [projectcontour/contour#4193]
Hey,

We wish to set our contour setup as an edge proxy (we are behind an NLB not ALB) as described here - 
https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge
unfortunately "use_remote_address" directive is not externalized to contour,
currently this allows our external untrusted clients to set their own x-request-id, this clearly is a security concern,
a.  Would love to see this externalized to the contour configmap
b. in the meantime can anyone suggest how to enable this in the current state.

Thanks.

**Comment by youngnick** [comment]
Contour sets `use_remote_address` to true, unconditionally (because it's a good idea and because it's listed in the page you mentioned). Do you want to be able to disable it?
