### ISSUE TITLE
Decision: Escaping path matches and better regex detection

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#4196]
**What do you want the project to decide?**
Currently when performing path matching in Ingress, HTTPProxy, and HTTPRoute, Contour does not consider escaping the path a user supplies to match on.

For example, if a user supplies `/foo|bar` to match on as a prefix in an Ingress resources, this path match is passed directly to Envoy without the proper encoding of the `|` character. Envoy will in practice never receive a `|` in a request, as the path must be encoded. This means when a user types in `http://foo.com/foo|bar` in their browser, curl, or other HTTP client that does encoding properly, they will never get a route match and will always get a 404 from Envoy, as Envoy will receive requests with the path `/foo%7Cbar`.

In addition, if a user uses the correct encoding of the path match `/foo%7Cbar` in an Ingress resource `ImplementationSpecific` match, we incorrectly detect that as a regex pattern rather than a prefix match: https://github.com/projectcontour/contour/blob/09d04885a222b833108a0c5610ca4ef5b5adbea8/internal/dag/ingress_processor.go#L252

Aside from the obvious issues with giving feedback to users on Ingress objects, generally we don't tell users anything about these possible error cases, and actually leave them in the dark about how their match is working or not. We may reject a resource if it has an invalid regex but that is about it.

Another issue is we do not strip fragments or query strings from path matches either so `/foo#` will get passed to Envoy without modification. Envoy solely looks at the path when matching and strips out the extra content so you will end up creating a route match in Envoy that can never be fulfilled

To fix this, we need to make a couple changes:
- Strip fragments and query strings from path matches
  - Should be easy to do with golang url package
- Or reject path matches with fragment and query strings
  - We would log/set status accordingly
  - If a user specifies this they will never get a match on the route they programmed
  - IMO this is what I would choose, having a query or fragment identifier doesn't make sense here and we should let users know
- Do we automatically escape paths with characters that need it?
  - e.g. with the example above, Envoy would be programmed to match on `/foo%7Cbar` not `/foo|bar`
  - This choice is better for usability maybe, but has some "magic" behind the scenes
  - Unless we invent a new status condition, not a good way of telling users what the actual match is unless they look at the Envoy config dump
- Or do we reject resources with path matches that need escaping?
  - e.g. with the example above, the resource would be rejected, users would have to use the encoded path when programming an Ingress etc.
  - We would log/set status accordingly
  - This choice is better if we want to be super explicit about what is valid or not
- Regex detection in the Ingress `ImplementationSpecific` match (and possible future HTTPProxy/HTTPRoute match types) needs work
  - matching on the existing set of characters shown above (especially `%`) is a bit of a weak match to find a regex IMO, this set is missing characters like `()|` etc.
  - possible replacement logic could look like:
    - try to escape path (use golang `url.Parse()`), if that fails, invalid path
    - if encoded == original, use a prefix match
    - if encoded != original (contains characters that need escaping), try to compile original as regex, if valid, program as regex
    - depending on decision for auto-escaping or not, program encoded as prefix or reject path match and log

**Anything else you would like to add:**
Related to investigation on: https://github.com/projectcontour/contour/issues/4191

**Comment by sunjayBhatia** [comment]
cc @projectcontour/maintainers

**Comment by youngnick** [comment]
> * Strip fragments and query strings from path matches
> * Or reject path matches with fragment and query strings

I can see an argument for either, but agree that coming down on the side of providing users more info is a good idea. I vote for the latter option.

> * Do we automatically escape paths with characters that need it?
> * Or do we reject resources with path matches that need escaping?

I think the latter is a bit more clear; I think we should err on the side of requiring specificity in config, and erroring if we don't get it. Proxying traffic is full of weird edge cases even when you do that, I don't think we should do automagic fixes without a very good reason.

> * Regex detection in the Ingress `ImplementationSpecific` match (and possible future HTTPProxy/HTTPRoute match types) needs work
>   * possible replacement logic could look like:
> ...

I like this set of replacement logic, feels clean and easy to test at the unit level.
