### ISSUE TITLE
gRpc timeout for Auth

### ISSUE THREAD

**Issue by digibank-rons** [projectcontour/contour#4198]
Hi,

We have an issue with external auth service, we are getting timeouts from time to time, we found that the default gRpc timeout for auth services is 200ms, how can we extand it please?

Thanks

**Comment by digibank-rons** [comment]
We solved it by adding the following -

  authorization:
      extensionRef:
        name: server-authorization
        namespace: staging
      responseTimeout: 1s

**Comment by youngnick** [comment]
Thanks! That's the intended way to set a timeout to an ExtensionService.
