### ISSUE TITLE
Contour Integration with Istio Ingress Gateway

### ISSUE THREAD

**Issue by prary** [projectcontour/contour#4208]
I have a use case where we want to integrate contour with istio ingress gateway for https connection. I am using contour as a edge for kubernetes cluster and also have istio ingress gateway for mesh enabled namespaces. Right now tls termination happens in contour with the help of fallback certificate and the traffic is routed to ingressgateway service then to virtual service and finally to kubernetes service. 

```tls termination at contour -> ingress gateway -> virtual service -> kubernetes service```

Traffic flowing from contour to ingress gateway is http and want to configure the same to be https. Is there a way possible where contour does the tls termination and then start a fresh https connection with ingress gateway. 

I have tried contour passthrough and tried tls termination at ingress gateway but this doesn't work as ingress gateway does not support fallback certificate.

Any possible way by which we can achieve it? Whole idea is to get https connection inside kubernetes cluster.

**Comment by youngnick** [comment]
Hi @prary, sorry about the delay getting back to you here.

Contour absolutely supports termination and re-encryption, we call it "upstream TLS", and the documentation is here: https://projectcontour.io/docs/v1.19.1/config/upstream-tls/

I think the trickiest part here will be making sure that Istio's certificate infrastructure provisions and maintains a certificate that Contour's Envoys can use to connect to the ingress-gateway (that is, the certs that will go in the upstream TLS config).
