### ISSUE TITLE
Update Contour HealthCheck to include gRPC endpoint

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#4210]
**Please describe the problem you have**
The healthcheck (e.g. `/healthz`) today checks that it can access the k8s api. It should also check that the gRPC endpoint that it serves to Envoy is also running properly. 

// ref: https://github.com/projectcontour/contour/blob/df5feec9881ac60c564c2ee071874f52ae54ac17/internal/health/health.go#L28

**Comment by youngnick** [comment]
Totally makes sense, agreed.

**Comment by sunjayBhatia** [comment]
could use the pattern described here:
- https://github.com/grpc/grpc/blob/master/doc/health-checking.md
- https://medium.com/geekculture/implementing-healthchecks-in-grpc-containers-for-kubernetes-d5049989ab12
