### ISSUE TITLE
metrics listener E2E test flake

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4229]
Seen this one a couple times now:

```
Error Trace:	metrics_test.go:39
  	            				suite.go:724
  	            				asm_amd64.s:1581
  	Error:      	Should be true
  	Test:       	Infra requests to default metrics listener are served
  	Messages:   	expected 200 response code, got 404
```

https://github.com/projectcontour/contour/runs/4474806556?check_suite_focus=true#step:7:154

**Comment by skriss** [comment]
Another: https://github.com/projectcontour/contour/runs/4717320353?check_suite_focus=true#step:7:153

**Comment by sunjayBhatia** [comment]
another: https://github.com/projectcontour/contour/runs/4740752136?check_suite_focus=true
