### ISSUE TITLE
Error messages related to ignored Ingresses.

### ISSUE THREAD

**Issue by Zsolt-LazarZsolt** [projectcontour/contour#4239]
**What steps did you take and what happened:**
When contour is runned with a specific ingress class (----ingress-class-name=something) contour shall ignore all ingresses not annotated or marked with the same ingress class.

If any ingress resource has an annotation that is not supported by contour, it will show an error message about the annotation being ignored, for example:
ERRO[0000] ignoring invalid or unsupported annotation    annotation=ingress.kubernetes.io/body-size.

The problem is: this error message is logged for **any** ingress resources, not just the ones that are having the same ingress class.
This means contour does use resources to check these annotations on "throwaway" ingress resources, and also logs these errors needlessly. 
In debug logs it is shown that the resource is ignored but only after the error message:
DEBU[0000] ignoring object with unmatched ingress class.
This happens every time an ingress resource is created, or modified in the whole cluster.

This is true for ingress v1 and ingress v1beta1 resources, although it is curious that in both cases the log says
version=networking.k8s.io/v1

Replication steps:
Install contour with a random ingress class to look for.
Install or change any Ingress resource, that has an annotation that contour does not handle: 
For example: 
ingress.kubernetes.io/ssl-redirect: "true"
ingress.kubernetes.io/ssl-redirect: "true"

Example ingress manifest included.
[ingress.txt](https://github.com/projectcontour/contour/files/7713166/ingress.txt)

**What did you expect to happen:**
I was expecting the ingresses not using the right ingress class not to be processed at all.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.19.1 but seen in 1.15.2 too
- Kubernetes version: (use `kubectl version`): 
- Kubernetes installer & version:  v1.20.4
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
Yep, [this block of code](https://github.com/projectcontour/contour/blob/main/internal/dag/cache.go#L108-L127) runs before the ingress class filtering. We could definitely do some reordering there. One possible way to approach it: if an object is not "interesting" / inserted in the cache, then don't run the annotation check. This would cover non-matching ingress class, plus some other cases as well where we probably don't need to be checking annotations (irrelevant services, etc).
