### ISSUE TITLE
Dynamic clusters clashing between Ingress and HttpProxy

### ISSUE THREAD

**Issue by Zsolt-LazarZsolt** [projectcontour/contour#4242]
**What steps did you take and what happened:**
Install Contour normally.
Have a http1 AND http2c compliant backend. 
Have the following not common but doable config:
Set up an Ingress: for example example.com with / going to a backend 80.
Set up an HTTPPProxy: example2.com with / going to the same backend 80 but with h2c protocol options.

Both example.com and example2.com will be server to the same backend BUT both will be served over http1.1 between envoy and the backend, meaning the backend service options for the service 80 port is dropped from the httpproxy config.

If I remember correctly the order does not matter, regardless of which is applied first Ingress wins.

**What did you expect to happen:**
Both fqdn-s to be served exactly as their respective resource is set up.

**Anything else you would like to add:**
I attach the related service description 
[kahttp-service.txt](https://github.com/projectcontour/contour/files/7717754/kahttp-service.txt)

Ingress HTTPproxy manifests:
[ingress.txt](https://github.com/projectcontour/contour/files/7717770/ingress.txt)

The used backend will include the used http version in its output (response sent out to the client: Proto: HTTP/1.1)

**Environment:**

- Contour version: 1.15.2
- Kubernetes version: (use `kubectl version`): 1.21.4
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by youngnick** [comment]
I agree this seems like a bug - right now we assume that all the uses of a Service are the same, but I guess this proves that's not the case. I haven't looked at the code, but I suspect we'll need to change some stuff in the DAG to keep track of options like h2c options as part of the service reference/cluster name decision.

**Comment by Zsolt-LazarZsolt** [comment]
Would differentiating also based on the referencing http/ingress/(whatever gateway api uses) be a big waste?
That way the referenced cluster is set as the object reflects. 
Although one httpproxy can still reference the same service 2 different ways on the same port, on different routes.

**Comment by youngnick** [comment]
I think that it's probably better to change the cluster naming and tracking to use a hash of all of the params somehow, so that we can dedupe across usages, whether they are from Ingress, HTTPProxy, or Gateway API.

I think that including the "thing that references this cluster" into the config is likely to end up duplicating things, which could be an issue in big installs.
