### ISSUE TITLE
Set max_requests_per_connection for upstream and downstream connections.

### ISSUE THREAD

**Issue by Zsolt-LazarZsolt** [projectcontour/contour#4243]
There is a possible problem regarding Envoy running out of possible stream-id's during long lived busy HTTP2 connections.
Today Envoy does not handle this error in nghttp2:
https://github.com/envoyproxy/envoy/blob/c01793eb32a58f122d9a54cca7a432565e8186c9/source/common/http/http2/codec_impl.cc#L547
This does differ from the RFC, more on that in this Envoy ticket:
https://github.com/envoyproxy/envoy/issues/19219

The problem is two fold: 
1. Envoy as a client toward the backend:
Contour does not set max_requests_per_connection for dynamic clusters
The above mentioned ticket does say that max_requests_per_connection by default is unlimited, in fact
It seems to be limited:
https://github.com/envoyproxy/envoy/blob/main/source/common/http/conn_pool_base.cc#L94
https://github.com/envoyproxy/envoy/blob/main/source/common/http/conn_pool_base.cc#L172-L174

2. Envoy as a server towards downstream:
Envoy in this regard does implement max_requests_per_connection as a new feature in Envoy 1.20
https://github.com/envoyproxy/envoy/pull/14936
Here it seems to be in fact unlimited unless set.

The issue about not handled nghttp2 is being worked on but not merged by Envoy.

To solve the possible issues regarding this it would be great to either make max_requests_per_connection configurable by user for both downstream and upstream in Contour 
OR
set a hard coded limit for upstream and downstream connections.

For backward compatibility reasons it would also be great to set this limit based also on which version of Envoy Contour is talking to. For example If contour is happen to talk to an Envoy under 1.20, do not set this for downstream.
This would solve issues that can lead to traffic loss during downgrade or rollback of Contour.

**Comment by youngnick** [comment]
Thanks for this issue @Zsolt-LazarZsolt, I agree that doing something here seems reasonable. I think that someone will need to have a look and come up with a design that both fixes the issue and doesn't break the backward compatibility, as you say.

**Comment by chaosbox** [comment]
@youngnick @Zsolt-LazarZsolt 

We were thinking it will be useful to expose `max_requests_per_connection` for downstreams since it will be of help to rebalance long running connections during an autoscaling event, to rebalance the existing workload. 

The other fallback option we had been looking at is `max-connection-duration` but max requests will be better since it limits the connection churn only on the busy ones.

**Comment by skriss** [comment]
@chaosbox see #5401 and #5417 for the latest on this!
