### ISSUE TITLE
De-dupe E2E test code for Envoy deployment

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4267]
Followup to #4126 

Right now some of the E2E test code is duplicated for testing an Envoy Deployment (rather than the default DaemonSet). We should de-dupe this, either by externalizing the duplicated code somewhere and reusing it for both the Deployment and DaemonSet tests, or by reconfiguring the Envoy Deployment tests to run the entire E2E test suite against an Envoy Deployment, as part of our daily build.

Personally I'm now leaning towards the latter, as it gives us full E2E coverage against an Envoy Deployment, while not duplicating test code and not adding potential noise to every PR build.

**Comment by stevesloka** [comment]
Initially I had code that would run the same tests with both the Daemonset model and the Deployment model, but switched to simplify it later on which is what got merged.

**Comment by skriss** [comment]
I like running the full set of E2E's against an Envoy deployment, my concern with doing that on every PR is it introduces twice as many chances for test flakes so potentially adds friction to the PR process. IMHO running them once a day is a good compromise, since we get full coverage but avoid the PR issue, and get feedback "soon enough" on the off chance something breaks the Deployment-based Envoy but not the DaemonSet Envoy.

**Comment by stevesloka** [comment]
Yeah for sure. In reality, how Envoy is deployed shouldn't matter much with respect to how Contour sends it updates. 

I figured the PR run would catch errors with how the yaml defined for the deployed is generated or if say a volume or something is changed.

Overall do I agree that running nightly would be fine to catch the few things that happen here or there.
