### ISSUE TITLE
drop # of required PR reviews to 1

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4270]
**What do you want the project to decide?**

I'm proposing dropping the number of required reviews on a PR to 1. When possible or necessary, it's still good to have 2 reviews, but it shouldn't be a blocker / shouldn't require the user of admin privileges to work around. This is in light of the # of maintainers who are actively doing reviews and the time zone disparities.

Input from other maintainers welcome.

**Comment by sunjayBhatia** [comment]
cc @projectcontour/maintainers 

I'm down with this, for big changes we tend to wait for multiple reviewers, maybe we can implement some automation for that eventually but by convention seems ok for now

**Comment by stevesloka** [comment]
I like the idea of having it tied to the size tag on the PR, this was why we moved to 2 reviews was to make sure enough maintainers agreed with the changes getting merged in. But for now is fine to move back to 1.

**Comment by youngnick** [comment]
When we had two people in two separate timezones, we put this in place to ensure that we didn't end up with timezones running ahead of each other.

I think we can try out going back to 1 review, and making sure that we're clear that for bigger or more complex changes we expect more reviews, but I feel like the best solution is to do something using the size of the PR somehow. It just feels less annoying when a bot tells you do something, than if someone comes and says "hey, I wanted to review this".

Maybe we could also agree that if someone assigns themselves as a reviewer, they need to review before merge? That way people can signal they're interested in a PR before it merges.

**Comment by skriss** [comment]
Discussed in the maintainers meeting and agreed to drop required reviewers to 1. For larger PRs, additional maintainers should be given the opportunity to review as well.
