### ISSUE TITLE
TLS-termination at the NLB does not fully work

### ISSUE THREAD

**Issue by gregkoganvmm** [projectcontour/contour#4277]
**What steps did you take and what happened:**
I attempted to setup Contour with an TLS-terminated Network Load Balancer (NLB) using the [Bitnami chart](https://artifacthub.io/packages/helm/bitnami/contour/7.2.0) connecting over a non-encrypted connection to a Java upstream. I set both `envoy.containerPorts.http` and `envoy.containerPorts.https` ports to 8080 , and enabled the Proxy v2 protocol on the load balancer manually. That allowed for both port 80 and port 443 to be handled by Contour/Envoy and receive traffic. Then I setup a force-ssl-redirect using the `ingress.kubernetes.io/force-ssl-redirect: "true"` annotation on the application ingress, which resulted in an infinite loop most likely because both http and https traffic is being handled on the same port without analysis of the protocol the client is using. Also, related to the same problem of not analyzing the protocol used by the client, if the upstream server is relying on the http headers, such as `X-Forwarded-Proto` to determine the protocol, those values are not being passed along to the upstream server and the default is http. This resulted in the response containing http:// urls when the application was accessed on https/443 (this was a test application that serves dynamic html, not a restful endpoint).

P.S. The chart seems to have an issue with defaults - port 80 is the default, but that does not work (possibly due to non-root user being used in the chart) - using a high port, like 8080 works.

**What did you expect to happen:**
1. `ingress.kubernetes.io/force-ssl-redirect: "true"`  should have resulted in a successful redirect to https/443
2. LoadBalancer proxy information/headers (e.g. `X-Forwarded-Proto`, `X-Forwarded-For`, `X-Forwarded-Port`) should be passed along to the upstream to allow for producing an appropriate response. 

**Environment:**
- Contour version: 1.19.1
- Kubernetes version: (use `kubectl version`):`Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/arm64"}`
- Kubernetes installer & version: kops 1.22.2, bitnami chart version 7.2.0
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): 1.19.1-debian-10-r60 (sorry, don't have the containers running anymore and it's not super-relevant)

**NLB annotations**
```
 annotations: {
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:xxx:certificate/xxxx",
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true",
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "tcp",
      service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS13-1-2-2021-06",
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443",
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp",
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*',
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    }
```

**Comment by youngnick** [comment]
Thanks for this issue @gregkoganvmm, I feel like I kind of get what you mean, but any chance you could add a diagram? I have a couple of ideas, but want to make sure I have a clear picture before going too deep.

Sorry for the delay in getting back to you.

**Comment by jbonjean** [comment]
Hi, is there still no way to use `ingress.kubernetes.io/force-ssl-redirect` with TLS termination at the ELB (NLB or ALB) level?
