### ISSUE TITLE
Can't use Gateway API with Contour

### ISSUE THREAD

**Issue by aryan9600** [projectcontour/contour#4296]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
* Installed Contour via: `kubectl apply -f https://projectcontour.io/quickstart/contour.yaml`
* Installed Gateway related CRDs via: `kubectl apply -f examples/gateway/00-crds.yaml`

* Installed GatewayClass via: `kubectl apply -f examples/gateway/01-gatewayclass.yaml`, which did not succeed.
```
❯ k describe gatewayclass
Name:         example
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1alpha2
Kind:         GatewayClass
Metadata:
  Creation Timestamp:  2022-01-26T06:41:47Z
  Generation:          1
  Managed Fields:
    API Version:  gateway.networking.k8s.io/v1alpha2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:controllerName:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2022-01-26T06:41:47Z
  Resource Version:  873
  UID:               2a524669-5986-4d2e-a137-319bab545b5d
Spec:
  Controller Name:  projectcontour.io/projectcontour/contour
Status:
  Conditions:
    Last Transition Time:  1970-01-01T00:00:00Z
    Message:               Waiting for controller
    Reason:                Waiting
    Status:                Unknown
    Type:                  Accepted
Events:                    <none>
```

**What did you expect to happen:**
An admitted GatewayClass managed by the Contour controller.
Please let me know if I'm missing something here.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.19
- Kubernetes version: (use `kubectl version`): Client=1.23, Server=1.23
- Kubernetes installer & version: N/A
- Cloud provider or hardware configuration: kind amd64
- OS (e.g. from `/etc/os-release`): Ubuntu 18.0.4

**Comment by sunjayBhatia** [comment]
The default contour example manifest actually does not set up Contour to look for GatewayClass/Gateway resources, you do need to set the gateway controller name to ensure contour knows what gatewayclass/gateway to look for: https://projectcontour.io/docs/v1.19.1/configuration/#gateway-configuration

The Gateway API specific example YAML does this for you: https://projectcontour.io/quickstart/contour-gateway.yaml

**Comment by skriss** [comment]
Looks like this has been answered so I'm going to close this out, feel free to reach out again as needed! Also note that Contour v1.20 just came out, with Gateway API v1alpha2 support: https://github.com/projectcontour/contour/releases/tag/v1.20.0 and here's one more helpful link to a guide that walks through getting going with Contour and Gateway API: https://projectcontour.io/guides/gateway-api/

**Comment by paulwitt** [comment]
Pretty sure this is still not working.  Status is still "Unknown" which means that gitops tools like ArgoCD won't complete the sync.
