### ISSUE TITLE
Add query parameter hash policy

### ISSUE THREAD

**Issue by pkit** [projectcontour/contour#4319]
**Please describe the problem you have**

Right now `projectcontour` implements routing/lb policies based on:
- cookie
- header
- sourceIP

Envoy supports hash policy on query parameters, [here](https://www.envoyproxy.io/docs/envoy/v1.17.0/api-v3/config/route/v3/route_components.proto#config-route-v3-routeaction-hashpolicy-queryparameter)
It would be nice to have it, as some services out in the wild use all types of identity mappings, not only header-based.

**Comment by youngnick** [comment]
This seems like a reasonable ask - @sunjayBhatia, do you remember any reason why we wouldn't be able to add this to the methods we already support?

**Comment by sunjayBhatia** [comment]
Nope no reason not to add this, we started out just with header hashing since that was what was initially requested but query param hashing should be easy to add

@pkit if you are able to contribute we would gladly take a PR!

**Comment by sunjayBhatia** [comment]
see https://github.com/projectcontour/contour/pull/4141 for the related PR that added source ip hashing, let us know if you need any assistance 👍🏽
