### ISSUE TITLE
update "Introduction to Contour" link on projectcontour.io

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4320]
The "Introduction to Contour" link on the projectcontour.io landing page points to a blog from 2019 that references Contour v0.10, this link should be updated to point to something newer, or perhaps we could drop that entire section as it seems somewhat redundant with other ways to navigate the site.

**Comment by yankay** [comment]
HI @skriss , Is the [projectcontour document introduction](https://projectcontour.io/docs/v1.20.0/) page suitable. The beginner can know the  main introduction from the page

**Comment by skriss** [comment]
@yankay thanks for looking at this - I'm actually thinking we should remove that whole grey section, as both links in it are out of date (on looking at the second one, it references a blog post that uses IngressRoute which no longer exists), and I can't think of anything to link to there that we don't already link to elsewhere on the main page.

**Comment by gary-tai** [comment]
@skriss 
Looks like the file to change is:
site>themes>contour>layouts>index.html
remove `<div class="bg-grey introduction">.... /div>`

will look like the attached screenshot:
![Contour landing page - no grey section](https://user-images.githubusercontent.com/85881851/179870039-e98441cd-172a-4701-8258-dea7c7564b55.png)

Let me know if that's what you had in mind.
