### ISSUE TITLE
Less verbose access logging.

### ISSUE THREAD

**Issue by Zsolt-LazarZsolt** [projectcontour/contour#4321]
Currently Contour sets up envoy to log every request to /dev/stdout or alternatively if
--envoy-http-access-log=/dev/null
--envoy-https-access-log=/dev/null
parameters are used the access logs can be turned off completely.
The logs can help us debugging, although on a busy system the amount of generated logs can be a big task to log collecting subsystems

It would be great to have a solution between fully on and fully off. For example an error level logging of access: only logging the requests that are not successful. This could be a good middle ground.
This can be achieved with envoys own access_log_filters 

I was able to have some filtering with 
              filter:
                status_code_filter:
                  comparison:
                    op: GE
                    value:
                      default_value : 300
                      runtime_key: 'something'
in envoys access_log configuration.
Alternatively the response_flag_filter could be useful also, although I was unable to create a filter that trigger to everything only leaving 200 - lines out.

It would be great to have this feature be parameterized in configmap for exmaple:
by default: no filtering
<operand: EQ LE GE>:<response code>

**Comment by youngnick** [comment]
Thanks for the suggestion @Zsolt-LazarZsolt.

I'm not sure that full configurability is required here though. Maybe we could have something like this:

```yaml
  onlyLogAbove: 300
```
I can't really see any reason that people would need to use anything other than GE as the operator? What do you think?

**Comment by Zsolt-LazarZsolt** [comment]
Sounds good, maybe one caveat can be when the client disconnects.
that looks as follows:
[2022-02-07T12:20:22.560Z] "GET / HTTP/1.1" 0 DC 0 0 3114 - "-" "Wget/1.19.4 (linux-gnu)" "9d2d9292-0f8a-47b7-a4d6-9eac3ed5f093" "localhost:5000" "127.0.0.1:4000" /

that of course is very tricky as this info is can be crucial but hard to cover with only one filter together with the normal http error codes >300

**Comment by Zsolt-LazarZsolt** [comment]
the best would be everything that is not 200, but I could not find not_filter yet

**Comment by youngnick** [comment]
If that solution works @Zsolt-LazarZsolt, maybe we could add this as `onlyLogErrors: true` or similar?

**Comment by tsaarni** [comment]
I've chatted with Zsolt and can try to take a stab at this.
