### ISSUE TITLE
design: Update ExtensionService to split out each type of extension

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour#4324]
After working on #399 for a while, @skriss suggested (in https://github.com/projectcontour/contour/pull/3802#discussion_r660084154) that we look at updating ExtensionService to have a separate CRD for each type of extension service.

This issue is to cover that work.

From https://github.com/projectcontour/contour/pull/3802#discussion_r660084154:
> I think if we moved to a CRD per service type (ExtAuthService, RateLimitService, TracingService), we could make this work since each type could be significantly different - and tracing would need to be significantly different than the others given that it's not an xDS gRPC service, and, depending on the provider, does not make use of an Envoy cluster at all (which is effectively what an ExtensionService is right now). However, I think it's going to be difficult to move from the generic ExtensionService to a CRD per service type since it'll require what I believe is a breaking API change for ExtAuth (HTTPProxy currently has an implicitly-typed reference to an ExtensionService), and disruptive/breaking config file changes for rate limiting. If we wanted to do that, it might need to wait for a v2 API/v2 Contour.
>Another option would be to add type-specific subfields to ExtensionService; however, because tracing is so different from the existing ExtensionService types, many of the existing fields in ExtensionService don't apply to tracing, so we end up with a messy API where many fields just don't apply in certain circumstances. I'm not a huge fan of this option given where we're starting from -- even though ExtensionService is "alpha", we don't want to break users if we can avoid it, which makes it harder to make in-place changes.
>We could introduce just a TracingService CRD in the v1alpha1 group which would give us a chance to experiment with having a CRD per service type, and then look to migrate the other existing service types to specific CRDs down the road. I like this approach in theory, though there are some challenges specifically around OpenCensus since it can't be configured more than once per Envoy lifetime (that would apply even if we used the config file).

**Comment by pavelnikolov** [comment]
This PR was sent last week and I am looking forward to having this merged and implemented in contour as well.
https://github.com/envoyproxy/envoy/pull/20281

**Comment by sunjayBhatia** [comment]
at least in the context of OpenTelemetry and enabling tracic, this may not be necessary as a prerequisite for that work as the OpenTelemetry filter just takes a gRPC service so an ExtensionService based approach will still likely work

**Comment by skriss** [comment]
> at least in the context of OpenTelemetry and enabling tracic, this may not be necessary as a prerequisite for that work as the OpenTelemetry filter just takes a gRPC service so an ExtensionService based approach will still likely work

Agreed, no longer a blocker. This may still be a good idea in general, but it can be evaluated independently of tracing support.
