### ISSUE TITLE
support disabling Envoy's merge_slashes option

### ISSUE THREAD

**Issue by mszabo-wikia** [projectcontour/contour#4339]
**What steps did you take and what happened:**
An upstream resource with URL path `/wiki/Mitou_Shoukan://Blood-Sign_-_Tập_1_Ending_1` becomes inaccessible when exposed via Contour - the path is normalized to `/wiki/Mitou_Shoukan:/Blood-Sign_-_Tập_1_Ending_1` in the upstream request.

**What did you expect to happen:**
The URL should be accessible.

**Anything else you would like to add:**
~~It seems this is due to https://github.com/projectcontour/contour/pull/988 enabling `normalize_path` for connection managers as a mitigation for https://github.com/envoyproxy/envoy/security/advisories/GHSA-xcx5-93pw-jw2w. Currently, this value is not configurable.~~

Edit: The cause is [`merge_slashes`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-merge-slashes) rather than `normalize_path`.

**Environment:**

- Contour version: 1.20.0
- Kubernetes version: (use `kubectl version`): N/A
- Kubernetes installer & version: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from `/etc/os-release`): N/A

**Comment by mszabo-wikia** [comment]
I think the easiest way to go about this would be to expose `normalize_path` via the global contour config, but have it default to true—this way, new installs have a secure default out of the box, and compatibility with existing installs that do not define a value for it in global config will be maintained, while allowing to selectively disable the normalization in cases such as this issue where it may be warranted.

What do you think?

**Comment by youngnick** [comment]
Yes, I don't see any other way than a boolean like that, but I think it will need a strong callout in the docs that it does make our behavior less standards-compliant, which is why it's defaulted to true.

We have both the config file and the ContourConfig CRD as config options at the moment, so it would need to go there.

**Comment by mszabo-wikia** [comment]
Per the office hours meeting today: this behavior appears to be caused by Envoy's `merge_slashes` option rather than `normalize_path`, which seems to not play a role here. (https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-normalize-path)

It seems it should be fine to make this configurable (defaulting to true) and it'd be less controversial than toggling the RFC normalization that `normalize_path` provides.

**Comment by skriss** [comment]
FYI for background, couple links to the past issue and PR that added this static configuration:
- https://github.com/projectcontour/contour/issues/2344
- https://github.com/projectcontour/contour/pull/2406
