### ISSUE TITLE
envoy healthcheck

### ISSUE THREAD

**Issue by tirelibirefe** [projectcontour/contour#4342]
Hello,
Here is my topology:
![image](https://user-images.githubusercontent.com/45227339/153761910-20b54e5f-746d-434b-9ebb-14c33ac2cdf7.png)

...and here is my ALB health status:
![image](https://user-images.githubusercontent.com/45227339/153761937-aaaa9a41-765e-4c94-9b90-dad3c86bb780.png)

![image](https://user-images.githubusercontent.com/45227339/153765650-51caf724-d029-494b-ae97-0fb5f88143b4.png)

I tried several combinations like;
```
port:8002 path:/healthz 

port: http path: /

port: https path:/healthz 

port: http path:/healthz 
```

...but no luck. 

`"GET /healthz HTTP/1.1" 404 NR 0 0 0 - "192.168.X.X" "ELB-HealthChecker/2.0" "382a-0c564fa906d6" "192.168.X.X" "-"`

Could you please advise what must the correct healthcheck configuration for ALB? 

Thanks & Regards

**Comment by sunjayBhatia** [comment]
you should be able to use port `8002` and the `/ready` endpoint: https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--ready (also configured in the k8s readiness check here: https://github.com/projectcontour/contour/blob/3498b966d4ed9ef1edb139b8ec8f8b6bddba6c8b/examples/contour/03-envoy.yaml#L82-L87)

**Comment by tirelibirefe** [comment]
Hello,
thanks for explanation @sunjayBhatia 
...but the port 8002 is not exposed:

```
$ k get svc -n projectcontour
NAME      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
contour   ClusterIP   10.100.199.147   <none>        8001/TCP                     5d12h
envoy     NodePort    10.100.36.111    <none>        80:31602/TCP,443:30276/TCP   5d12h
```

is that normal? Which endpoint must the httpproxy be associated?

Thanks & Regards

**Comment by Johannes1509** [comment]
Hi @tirelibirefe did you find any solution? Im facing the same issue :)

**Comment by skriss** [comment]
If you need port 8002 exposed on the envoy Service you'll need to add that manually, it's not done by default in our example YAML.
