### ISSUE TITLE
prometheus node exporter port 9100 problem

### ISSUE THREAD

**Issue by tirelibirefe** [projectcontour/contour#4343]
Hello,
I installed Contour via Contour Operator on EKS - Kubernetes and also installed monitoring stuff via yaml files under examples folder.

Here is the result:

`prometheus-node-exporter-vpc7z             0/1     CrashLoopBackOff `

...

 `level=fatal msg="listen tcp :9100: bind: address already in use" source="node_exporter.go:79"`

Because I have another prometheus in another namespace which is used by other services in Kubernetes and it's listening port 9100 of the ndoes . 

Conflict!

If I change the port number as 9101 in 03-prometheus-node-exporter.yaml configuration , would it be correct, or enough?

How do you guys figure out this conflict? Is there a workaround for that problem?

Thanks & Regards

**Comment by sunjayBhatia** [comment]
You should not need more than one instance of the prometheus node exporter daemonset, if you already have one that should be sufficient to get node metrics (so you can probably skip installing the one in this repo's example and possibly other pieces of that example, as it is intended to be sort of a complete example in case you don't already have any monitorig set up)

**Comment by tirelibirefe** [comment]
Thank you @sunjayBhatia , that answer what I was looking for.

**Comment by sunjayBhatia** [comment]
Sounds good, closing for now
