### ISSUE TITLE
The go.mod file is go version 1.15，but the go version has been upgraded to 1.17.5

### ISSUE THREAD

**Issue by yankay** [projectcontour/contour#4349]
According the PR: https://github.com/projectcontour/contour/pull/4232 , the golang version has been upgrade to 1.17.5.

But there are still 1.15 in go.mod file: https://github.com/projectcontour/contour/blob/main/go.mod#L3.

Should we upgrade it to make the upgrade completely

**Comment by sunjayBhatia** [comment]
The version in the go.mod file represents the minimum version of Go needed to compile the contour module. It’s a bit older than the latest to ensure we don’t cause compatibility issues as I believe we don’t use any language features only in later versions that would force people to upgrade their Go technically

**Comment by yankay** [comment]
Thanks.
