### ISSUE TITLE
Support for gRPC-JSON transcoder

### ISSUE THREAD

**Issue by juanpmarin** [projectcontour/contour#4353]
Envoy supports exposing gRPC services as rest services using trascoding. This is supported by envoy with [this plugin](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter) and based on the definitions from [Google Cloud Endpoints](https://cloud.google.com/endpoints/docs/grpc/transcoding)

Supporting this would enable to develop services with a nice and structured way of defining them, as gRPC is, but enabling multiple consumers that support rest services, web clients for example.

For more information you can refer to:
https://cloud.google.com/endpoints/docs/grpc/transcoding
https://github.com/grpc-ecosystem/grpc-gateway
https://cloud.google.com/apis/design

**Comment by youngnick** [comment]
Thanks for this @juanpmarin, it looks like this is a duplicate of #4291?

**Comment by juanpmarin** [comment]
@youngnick you're right, thanks.
Closing this now
