### ISSUE TITLE
 external authorization sample

### ISSUE THREAD

**Issue by tirelibirefe** [projectcontour/contour#4354]
Hello,
I need to an authorization system integration for custom developed apis and some other applications like Prometheus which needs to be protected.

I've seen  external authorization configuration for contour-authserver. I looked for another external authorization configuration sample but couldn't have found. 

What is the correct walk-through for that? Is there any sample configuration which is used Keycloak, Microsoft/Azure LDAP or anything else as external auth server?

Thanks & Regards

**Comment by youngnick** [comment]
So sorry to take a long time to get back to you here @tirelibirefe. We don't currently have a good example of using contour-authserver for Oauth flows, although we did merge support for it earlier. Sorry.

I'm also working on a way to do Oauth using Envoy's inbuilt filter in #2664, which would mean that you can do some oauth flows without needing the external auth service.
