### ISSUE TITLE
Configure Ingress Controller on my first kubernetes cluster

### ISSUE THREAD

**Issue by cmonty14** [projectcontour/contour#4355]
This is certainly no bug report, but I'm kindly asking for your help.

I have successfully deployed my (first) kubernetes cluster; it is running with 3 control plane nodes in HA + 2 compute nodes.
```
# k get nodes
NAME        STATUS   ROLES                       AGE     VERSION
k3s-node1   Ready    control-plane,etcd,master   3h35m   v1.22.6+k3s1
k3s-node2   Ready    control-plane,etcd,master   126m    v1.22.6+k3s1
k3s-node3   Ready    control-plane,etcd,master   122m    v1.22.6+k3s1
k3s-node4   Ready    <none>                      120m    v1.22.6+k3s1
k3s-node5   Ready    <none>                      120m    v1.22.6+k3s1

```

I have used k3sup for deploying the cluster with kube-vip.

The problem I'm facing is related to the network restrictions of my lab, means noVLAN, limited IPs.
Therefore I configured a network bridge on the server that is hosting the VMs.
- each node is running as a VM in Proxmox VE
- Proxmox VE node is providing bridged network 10.97.206.11 and 192.168.100.11
- any VM is  running in isolated subnet 192.168.100.0/24 using gateway 192.168.100.11
- cluster API is accessible from this Proxmox VE node only

Overall I have deployed these pods:
```
# k get pods -A -o wide
NAMESPACE                   NAME                                       READY   STATUS              RESTARTS   AGE     IP                NODE        NOMINATED NODE   READINESS GATES
cert-manager                cert-manager-6d6bb4f487-4ktgq              1/1     Running             0          21h     10.72.4.4         k3s-node5   <none>           <none>
cert-manager                cert-manager-cainjector-7d55bf8f78-k2rfq   1/1     Running             0          21h     10.72.4.3         k3s-node5   <none>           <none>
cert-manager                cert-manager-webhook-577f77586f-8x777      1/1     Running             0          21h     10.72.3.4         k3s-node4   <none>           <none>
default                     httpbin-85777b684b-bjkr6                   0/1     ContainerCreating   0          22s     <none>            k3s-node4   <none>           <none>
default                     httpbin-85777b684b-dzdrt                   1/1     Running             0          22s     10.72.4.11        k3s-node5   <none>           <none>
default                     httpbin-85777b684b-htt6r                   0/1     ContainerCreating   0          22s     <none>            k3s-node4   <none>           <none>
kube-system                 coredns-96cc4f57d-skd5f                    1/1     Running             0          23h     10.72.0.3         k3s-node1   <none>           <none>
kube-system                 helm-install-cert-manager--1-92ntj         0/1     Completed           0          21h     10.72.3.2         k3s-node4   <none>           <none>
kube-system                 kube-vip-cloud-provider-0                  1/1     Running             0          22h     10.72.4.2         k3s-node5   <none>           <none>
kube-system                 kube-vip-ds-jl8qp                          1/1     Running             0          22h     192.168.100.153   k3s-node3   <none>           <none>
kube-system                 kube-vip-ds-mswl6                          1/1     Running             0          23h     192.168.100.151   k3s-node1   <none>           <none>
kube-system                 kube-vip-ds-zbkbh                          1/1     Running             0          22h     192.168.100.152   k3s-node2   <none>           <none>
kube-system                 local-path-provisioner-84bb864455-sb84x    1/1     Running             0          23h     10.72.0.2         k3s-node1   <none>           <none>
kube-system                 metrics-server-ff9dbcb6c-vwwbq             1/1     Running             0          23h     10.72.0.4         k3s-node1   <none>           <none>
projectcontour              contour-684dc4978d-gpdwh                   1/1     Running             0          6m30s   10.72.4.9         k3s-node5   <none>           <none>
projectcontour              contour-684dc4978d-tlvrw                   1/1     Running             0          6m30s   10.72.3.19        k3s-node4   <none>           <none>
projectcontour              contour-certgen-v1.20.0--1-vhhfx           0/1     Completed           0          6m33s   10.72.3.18        k3s-node4   <none>           <none>
projectcontour              envoy-4l79k                                2/2     Running             0          6m30s   10.72.4.10        k3s-node5   <none>           <none>
projectcontour              envoy-cgw2k                                2/2     Running             0          6m30s   10.72.3.20        k3s-node4   <none>           <none>
```
My understand is that an Ingress Controller is required to access services running in my cluster.
Therefore I deployed contour and httbin (for testing)
```
# kubectl get po,svc,ing -l app=httpbin
NAME                           READY   STATUS    RESTARTS   AGE
pod/httpbin-85777b684b-bjkr6   1/1     Running   0          38s
pod/httpbin-85777b684b-dzdrt   1/1     Running   0          38s
pod/httpbin-85777b684b-htt6r   1/1     Running   0          38s

NAME              TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
service/httpbin   ClusterIP   10.82.52.75   <none>        80/TCP    38s

NAME                                CLASS    HOSTS   ADDRESS        PORTS   AGE
ingress.networking.k8s.io/httpbin   <none>   *       172.20.10.58   80      38s
```

Currently I don't know how configure the cluster access for service users.

Could you please assist here?

**Environment:**
- Contour version: latest
- Kubernetes version: (use `kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", 
GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: k3s version v1.22.6+k3s1 (3228d9cb)
- Cloud provider or hardware configuration: VM based on KVM
- OS (e.g. from `/etc/os-release`): Debian 11

**Comment by youngnick** [comment]
I'm sorry we've taken so long to come back to you on this one @cmonty14.

I'm not very familiar with your Proxmox setup, sorry, but maybe some background may help.

Contour's Envoys need to have traffic able to get to them somehow. In our example deployment, we rely on Service of type LoadBalancer, which is provided in a lot of public clouds or managed Kubernetes offerings, that will allow you to create a Service, and have underlying load balancing infrastructure created for you automatically.

Obviously, that doesn't work for you.

For local deployments like yours, there are a few options:
- use a project like [metalLB](https://metallb.universe.tf/) to add some Service of type LoadBalancer to your cluster. It seems like you may be able to use the Layer 2 mode here to get it to work. The advantage here is that you don't _need_ to use Ingress resources to expose services, you _can_ just use Services directly. That's better for non-HTTP services in particular.
- use HostPorts on your Envoy Daemonset - you can specify hostPorts alongside the containerPort in the Pod definition inside the Daemonset. (see https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#ports) for details. This will allow your Envoy Daemonset to receive traffic on each node's IP address, and you can configure a round-robin DNS to get the traffic to Envoy.

**Comment by cmonty14** [comment]
Hello,

thanks for your reply.

In the meantime I started from scratch, means I deployed the kubernetes cluster using a different network that is **not bridged**. The external subnet is `10.97.206.0/24`.

The load balancer service is provided by _kube-vip_, and to my best knowledge this works as expected.

The latest deployments are:

- Contour
- httpbin

And I think this is running as expected:
```
# kubectl get po -l app=httpbin
NAME                       READY   STATUS    RESTARTS   AGE
httpbin-85777b684b-2tp5j   1/1     Running   0          44s
httpbin-85777b684b-c4fhp   1/1     Running   0          44s
httpbin-85777b684b-kslcd   1/1     Running   0          44s
root@ld3976:~# kubectl get -n projectcontour service envoy -o wide
NAME    TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                      AGE   SELECTOR
envoy   LoadBalancer   10.93.136.134   10.97.206.210   80:32265/TCP,443:31769/TCP   12m   app=envoy

# kubectl get po,svc,ing -l app=httpbin
NAME                           READY   STATUS    RESTARTS   AGE
pod/httpbin-85777b684b-2tp5j   1/1     Running   0          2m8s
pod/httpbin-85777b684b-c4fhp   1/1     Running   0          2m8s
pod/httpbin-85777b684b-kslcd   1/1     Running   0          2m8s

NAME              TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
service/httpbin   ClusterIP   10.93.48.36   <none>        80/TCP    2m8s

NAME                                CLASS    HOSTS   ADDRESS         PORTS   AGE
ingress.networking.k8s.io/httpbin   <none>   *       10.97.206.210   80      2m7s

# kubectl get services
NAME         TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
httpbin      ClusterIP   10.93.48.36   <none>        80/TCP    89s
kubernetes   ClusterIP   10.93.0.1     <none>        443/TCP   21m
```

Now I have this questions:

1. Why is the output of `kubectl get services` not showing an external-IP for service `httpbin`?
2. How can I access a _rancher_ deployment that was completed before the deployment of _Contour_?

**Comment by cmonty14** [comment]
Update:
I cannot open httpbin using external IP 10.97.206.215.
The root cause I identified is that ports 80 and 443 are filtered:
```
# nmap -p 80,443 10.97.206.215
Starting Nmap 7.70 ( https://nmap.org ) at 2022-03-18 11:20 CET
Nmap scan report for 10.97.206.210 (10.97.206.215)
Host is up (0.00012s latency).

PORT    STATE    SERVICE
80/tcp  filtered http
443/tcp filtered https
MAC Address: C2:6C:D5:60:81:AE (Unknown)

```

However there's no firewall in the network.
If I deploy Nginx with `kubectl create deploy nginx --image=nginx:stable-alpine` and then expose it to port 80 with `kubectl expose deploy nginx --port=80 --type=LoadBalancer` I can access the Nginx webpage w/o problems.
The output of `kubectl `confirms the external IP:
```
# kubectl get po,svc,ing -l app=nginx
NAME                         READY   STATUS    RESTARTS   AGE
pod/nginx-6bd999f769-cnhv8   1/1     Running   0          15m

NAME            TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)        AGE
service/nginx   LoadBalancer   10.93.48.187   10.97.206.210   80:32008/TCP   14s

```

So, what is causing the problem with _httpbin_?

**Comment by youngnick** [comment]
The way Contour works is that it takes Ingress objects, and makes the domain and path you specify in there available using the Envoy service. So, you'll need to access that domain name by curling the _Envoy_ service IP address, which is looks like is `10.97.206.210` from your config above.

It looks like you've got only a wildcard in the hostname in the Ingress, which I don't think will work with Contour. You'll need to set the hostname in the Ingress to some domain, and then ensure that the Host header in the HTTP request matches the hostname in the Ingress.

So, if you set the hostname to `httpbin.example.com`, you would need to do:
```bash
curl -H "Host: httpbin.example.com" http://10.97.206.210/
```
For Contour's Envoys to serve traffic.

To put this another way, all Ingress controllers (which both Contour and ingress-nginx are) basically _multiplex_ multiple HTTP services onto a single Service of Type Loadbalancer.

**Comment by cmonty14** [comment]
Thanks for your reply. This is my understanding of it.
Envoy is listening on `10.97.206.210`, and this is based on output
```
# kubectl get -n projectcontour service envoy -o wide
NAME    TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                      AGE   SELECTOR
envoy   LoadBalancer   10.93.136.134   10.97.206.210   80:32265/TCP,443:31769/TCP   12m   app=envoy
```
Now I must define a hostname in my DNS controller for this IP `10.97.206.210`.
After this I can verify it with `curl -H "Host: httpbin.example.com" http://10.97.206.210/`.

But what about IP `10.97.206.215` based on this output?
```
# kubectl get po,svc,ing -l app=httpbin
NAME                           READY   STATUS    RESTARTS   AGE
pod/httpbin-85777b684b-2tp5j   1/1     Running   0          2m8s
pod/httpbin-85777b684b-c4fhp   1/1     Running   0          2m8s
pod/httpbin-85777b684b-kslcd   1/1     Running   0          2m8s

NAME              TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
service/httpbin   ClusterIP   10.93.48.36   <none>        80/TCP    2m8s

NAME                                CLASS    HOSTS   ADDRESS         PORTS   AGE
ingress.networking.k8s.io/httpbin   <none>   *       10.97.206.215   80      2m7s
```
Is this not the IP the webservice is listening?

**Comment by youngnick** [comment]
That IP listed under `ADDRESS` will have been updated by one controller or another at some point, either Contour or ingress-nginx. Neither controller will remove that entry when the Ingress falls out of its scope, so the details may be stale. In either case, it will most likely have been set to the address of the LoadBalancer Service fronting the ingress controller.

Do you still have both Contour and ingress-nginx installed? If so, you may need to look at setting an ingress-class, either via annotation or the Ingress v1 field. By default, Contour will process Ingress objects with no ingress-class or the value `contour`. I believe that ingress-nginx will also process Ingress objects with no ingress-class by default.

**Comment by cmonty14** [comment]
Hello,
I have deployed nginx as load balancer only to proove that there are not firewall rules or whatever that filter communication with the cluster, means this service is deleted and not running in parallel to Contour.
Actually I deployed nginx-service after I identified Contour was not working.

**Comment by youngnick** [comment]
Okay, if only Contour is running in this cluster, and the Envoy service's External IP is `10.97.206.210`, the fact that your Ingress is showing an External IP of `10.97.206.215` means that Contour is not reconciling the resource properly. I'd set Contour's logs to debug level, restart it and see what the logs say about the resource.

**Comment by skriss** [comment]
Closing this out as inactive, feel free to reopen/reach out again if needed.
