### ISSUE TITLE
Ability to disable Envoy adding server headers to responses

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour#4359]
From #3692, @LiddersUK:
> My security team and the external pen testers continue to raise this as an (admittedly low impact) issue as if an attacker knows the technology that we employ then it gives them an attack vector.
> Their recommendation is for us to remove any server banners from response headers.

According to envoyproxy/envoy#14421, it seems like we will need to set the `server_header_transformation` param on the HTTPConnectionManager top `PASS_THROUGH`.

This will require a new global config boolean that defaults to `true` that will allow disabling of Envoy's server header responses.

**Comment by chris93111** [comment]
Hi any update of this ?

**Comment by Vishal-Chdhry** [comment]
Hi @sunjayBhatia! I would love to implement this, can you please guide me on where to start?

**Comment by Vishal-Chdhry** [comment]
@sunjayBhatia, Sorry for the delay on this issue, i was busy in college exams.
 
why cant we directly use an enum, i am having trouble with figuring out where it should be an enum and where should i convert it to the boolean type.

I have to add it as an enum here
https://github.com/projectcontour/contour/blob/057bac9a7180ab87a80c6436cc8d22f8de43f0ba/internal/envoy/v3/listener.go#L150

and convert it to an enum as well probably by doing something like this
https://github.com/projectcontour/contour/blob/057bac9a7180ab87a80c6436cc8d22f8de43f0ba/internal/envoy/v3/listener.go#L239

I have opened a PR on this as well
