### ISSUE TITLE
Add possibility to set multiple LoadBalancer services

### ISSUE THREAD

**Issue by Zsolt-LazarZsolt** [projectcontour/contour#4362]
In our systems we install Contour and Envoy on DualStack environments, it is supporting both IPV6 and IPV4 addresses

Because of other issues we do not create a LoadBalancer kubernetes service with:
ipFamilyPolicy: RequireDualStack or ipFamilyPolicy: PreferDualStack
We instead create two single stack services:
envoy-v4 and envoy-v6 with their respective ipFamilies set.

It would be great if we could list both services for Contour to watch as parameter
--envoy-service-name=envoy-v4,envoy-v6

So in the statuses of httpproxies and ingresses both LoadBalancerIP-s are present 
status:
  loadBalancer:
    ingress:
    - ip: envoy-v4 LoadBalancerIP
    - ip: envoy-v6 LoadBalancerIP

**Comment by youngnick** [comment]
This seems like a reasonable ask, just need to check that the usage is allowed in the upstream struct (which it seems like it should be?)

**Comment by xaleeks** [comment]
Can you state the other issues you mentioned that prevents you from leveraging the ipFamilyPolicy on Services now that dualstack graduates to GA in k8s 1.23.  I don't think we've yet explicitly tested ipv6 dual stack with sepc.ipFamilyPolicy:PreferDualStack yet but that's definitely higher priority for validation.  That will give you both ipv4 and ipv6 addresses for the Service which is the right way to run on true dual stack environments.

**Comment by Zsolt-LazarZsolt** [comment]
Hello Everyone 

Sorry for the late answer. In many cases we are deploying on bare metal clusters and using metal-lb to attract traffic.
The support for services with both IP Families in metal-lb was initiated but not finished
https://github.com/metallb/metallb/pull/727
I see now they might have moved forward with the implementation, For us moving toward both IPFamilies in the same service is a step in the far future.
