### ISSUE TITLE
Move non versioned Guide docs to versioned docs

### ISSUE THREAD

**Issue by kcoriordan** [projectcontour/contour#4396]
**What steps did you take and what happened:**
Some of the Guides in the doc sit outside the versioned docs, also some are maybe not applicable to the latest version/s of Contour.
Remove older guides
Move guides under versioned docs

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version:
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
Probably can be removed entirely since they only apply to very old unsupported versions:
- https://projectcontour.io/guides/ingressroute-to-httpproxy/
- https://projectcontour.io/guides/xds-migration/

**Comment by skriss** [comment]
This one also seems very old/redundant with other info, can probably be dropped:
- https://projectcontour.io/guides/tls/

**Comment by skriss** [comment]
I am going to try to get this done for 1.24, this would be really nice to have. cc @sunjayBhatia @pnbrown
