### ISSUE TITLE
Support self signed client certificates

### ISSUE THREAD

**Issue by jroper** [projectcontour/contour#4399]
Amazon API Gateway allows enabling mTLS communication between it and the upstream services, as per the [documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started-client-side-ssl-authentication.html). If the upstream services are running in k8s behind a Contour ingress, then Contour needs to be configured to trust the certificates that Amazon creates. The problem is, Amazon API Gateway only creates the certificates for you, you can't provide a certificate to Amazon API Gateway, and these certificates are self signed certificates. There is no CA.

I've done some testing, and it seems that Contour only supports using a CA certificate bundle to validate incoming mTLS connections. I tried giving Contour a self signed certificate, expecting that Contour would trust requests made with that certs private key, and it didn't, it failed with an error of "unknown ca".

To support Amazon API Gateway, and other mTLS scenarios where self signed certificates must be used, it would be ideal if Contour can support self signed certificates in the configured ca bundle. Ideally, it should support multiple self signed certificates in the bundle, since rotating self signed certificates requires the server to support multiple certs at once (as per the Amazon API Gateway documentation linked to above).

**Comment by youngnick** [comment]
This seems like a reasonable ask.

However, as always the question is: where would we put the configuration that would allow you to do this. Should we have a global "allow self-signed certs/disable CA checks" setting? If we pass self-signed certs to Envoy, do we need to tell it to trust them? Or should this be a per-vhost setting (which is more flexible but will require you to set it for _every_ vhost).

@jroper, do you have any thoughts here? Would a global setting be okay for you?

**Comment by jroper** [comment]
All good questions, I'm still learning a bit here about how things are "supposed to be done".

I'm not sure what the value of having such configuration to enable it or disable it is (and that's not me asserting an opinion that there's no value, I don't know). Right now, if you configure a secret with a self signed, non CA cert in the `caSecret` field, it doesn't work, you've got a configuration that will never accept any requests no matter what certificate is supplied (at least, my own testing shows this). So, one possibility is to detect, in envoy, when such a certificate is provided, and if so, instead of using it as a CA certificate, use it to validate that it is the same certificate as the key used with the certificate of the incoming request. Doing this won't break any existing already working functionality, it will only make something that didn't work before, now work.

So, essentially, the fact that you've configured a self signed cert rather than a CA cert indicates that you want self signed checks rather than CA checks. But I don't know if there are any downsides to that. Or if all of my assumptions are incorrect, like for example, maybe if you do configure a non CA cert currently, Contour will treat it as a CA cert (doesn't seem right, generally if the CA flag is not there in the cert, most crypto libraries will refuse to validate other certs with it, but this is my assumption, I don't know that for sure).

**Comment by tsaarni** [comment]
I doubt there is anything in Contour that would prevent self-signed certificates to be used like that. When you receive "unknown ca" TLS alert from Envoy, I think it is because BoringSSL (OpenSSL fork that Envoy uses) did not accept certificate as trusted unless it has `Certificate Sign` listed in its X509v3 Key Usage extension field.  I was experimenting a bit and got "unknown ca" with following debug printout in Envoy logs in that case:

```
[2022-03-15 08:07:48.281][14][debug][conn_handler] [source/server/active_tcp_listener.cc:140] [C1295] new connection from 172.18.0.1:43586
[2022-03-15 08:07:48.282][14][debug][connection] [source/extensions/transport_sockets/tls/cert_validator/default_validator.cc:202] X509_verify_cert: certificate verification error at depth 0: unable to get local issuer certificate
[2022-03-15 08:07:48.283][14][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:225] [C1295] TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[2022-03-15 08:07:48.283][14][debug][connection] [source/common/network/connection_impl.cc:249] [C1295] closing socket: 0
[2022-03-15 08:07:48.283][14][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:225] [C1295] TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
```

After adding `Certificate Sign` key usage (in addition to normal Digital Signature and Key Encipherment key usages) it worked.

I don't know if this helps much since I assume there is no controls in AWS API Gateway for the key usages in the generated client cert?

**Comment by tsaarni** [comment]
I also checked  Envoy docs for [CertificateValidationContext](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#envoy-v3-api-msg-extensions-transport-sockets-tls-v3-certificatevalidationcontext). It is bit unclear what would happen if leaving CA certificate unset but setting `verify_certificate_spki` or `verify_certificate_hash` with the values matching the client cert.

**Comment by jroper** [comment]
Correct, there doesn't seem to be any controls in the AWS API Gateway, they just give you the cert, and you have to use that. Ironically, for their downstream client certificate support, they too also only support providing a user supplied CA certificate. But they expect everything upstream to support their individually issued self signed certs.

I was wondering about the `verify_certificate_spki/hash` too. Now, I'm no C++ expert, and this is an unfamiliar codebase, but I think, reading through [the code](https://github.com/envoyproxy/envoy/blob/0fae6970ddaf93f024908ba304bbd2b34e997a51/source/extensions/transport_sockets/tls/cert_validator/default_validator.cc), you can leave the CA certificate unset while setting either or both of those lists.

**Comment by jroper** [comment]
Also, something dumb about the AWS API Gateway, they know that their backend mTLS support doesn't work with common services/servers:

![aws-api-gateway](https://user-images.githubusercontent.com/105833/158346280-cbdf679c-8e4a-4ee9-b3e9-05d8ef180b68.png)

They couldn't even connect to themselves, because their own frontend configuration does not support this. Other API Gateways, such as Google Apigee, don't have this problem. AWS does need to get their act together here.

**Comment by tsaarni** [comment]
:( I wonder if most would be fixed if they just would add `Certificate Sign` key usage.  It would fix Contour+Envoy compatibility.

**Comment by jroper** [comment]
This is what it could look like if we supported self signed certificates in Contour. I still have to test this manually (don't readily have a test environment at the moment), and of course write tests etc:

https://github.com/jroper/contour/commit/3a231c8101ceaef94294675660e9d1f19ef48078

**Comment by tsaarni** [comment]
@jroper So it worked with AWS API Gateway certs with this change? Cool! 

Something I wonder and would like to hear what people think: 

Would it be safer to just expose [SPKI validation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#envoy-v3-api-field-extensions-transport-sockets-tls-v3-certificatevalidationcontext-verify-certificate-spki) explicitly, instead of recognizing non-CA certs from the cert bundle in `caSecret` and turning them into SPKI hashes? Strictly speaking, it is not validation by CA certificate anymore so adding field for verifying SPKI hashes could express it more directly. It was an option when the original request for client cert based authentication was being proposed https://github.com/projectcontour/contour/issues/1090 but it was dropped back then for having minimal viable design to begin with.

**Comment by jroper** [comment]
@tsaarni Haven't tested yet, just putting the code up there to demonstrate the approach, as I said I don't have the environment handy (and right now am doing this work on borrowed time). But of course, I will make sure I test it thoroughly before I submit a PR.

I think exposing the SPKI validation explicitly is a good approach. Of course, both approaches have their merits, but exposing it directly is probably a better one, and I think means a simpler, more explicit and easy to understand approach for users.

I think I should be able to find some time to do this, submit a PR etc. So, I'll modify the CRD to allow this:

```yaml
    tls:
      secretName: server-secret
      clientValidation:
        spkiHashes:
          - j1fFFSBuF7S/Hzk5xsIq7N7wvVm8xdMpMnt0OUsz5rs=
```

The behaviour will be the same as what envoy offers, either or both validation methods can be present, and both will be applied if they are both there. I'll test manually with AWS, and assuming tests already exist for the client validation that I can use as a starting point, I'll write an additional test for SPKI validation. Does that sound ok?

**Comment by jroper** [comment]
Ok, I've now had a chance to test the code, and it works, the SPKI validation works. However, I've also found that Amazon API Gateway works without the change (I had been testing with my own self signed certificates because that was easier). Here's an example certificate that Amazon issues:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            a6:ad:0c:88:1e:71:70:31
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, L = Seattle, CN = ApiGateway
        Validity
            Not Before: Mar 18 02:24:59 2022 GMT
            Not After : Mar 18 02:24:59 2023 GMT
        Subject: C = US, L = Seattle, CN = ApiGateway
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:ca:f0:ad:e2:f0:d4:39:f6:01:f1:f1:73:e0:f5:
                    e8:e2:18:d3:7c:ab:3d:98:97:a9:92:fb:9b:ab:79:
                    30:7b:c7:ae:09:21:54:0f:e7:f1:33:d1:dc:5a:92:
                    4d:e4:12:7d:1f:a4:fa:ba:93:13:ec:71:68:a0:29:
                    df:41:f8:fb:22:8a:c1:b3:b2:e0:c6:c6:0d:7d:bf:
                    d1:e5:67:2b:79:3b:98:41:36:4d:b5:db:20:e1:46:
                    32:fe:1b:dd:19:bf:4a:f6:4d:92:97:84:82:5a:49:
                    c3:fd:51:2d:f7:2e:04:91:77:3b:4a:d5:6c:21:f4:
                    bf:16:49:c0:da:ae:96:e3:cb:2f:b7:eb:dc:f9:90:
                    5b:3e:d8:fa:b3:78:7a:3e:cb:44:9a:0d:4e:9a:56:
                    ef:90:fe:26:c3:8f:c1:02:3f:f5:90:3c:6a:dd:64:
                    a0:75:ae:3b:a7:1b:12:b6:0a:d0:f2:ba:32:26:fa:
                    28:66:37:7f:33:b8:62:3c:16:0e:3b:7a:eb:9a:f2:
                    b4:22:2c:b8:bc:73:33:02:7a:85:55:25:50:d8:b6:
                    45:7f:cd:09:58:4c:74:0d:c5:59:92:71:fd:92:f0:
                    96:eb:83:eb:eb:a0:c8:35:76:0a:54:c3:9a:24:69:
                    16:4f:62:26:e8:76:20:e9:fa:c8:ff:a6:48:97:52:
                    88:4d
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha256WithRSAEncryption
         7e:a8:4c:1f:5d:b0:29:9f:d3:90:2e:f4:23:f0:b7:07:8c:21:
         d0:fd:02:0e:8e:ba:43:e7:72:96:dc:ad:04:ce:b0:af:83:f2:
         aa:41:f2:f8:62:4a:df:dd:bb:8d:3c:65:c5:b1:8d:81:be:dc:
         3d:1c:b8:3e:47:d4:fd:7b:8d:2f:b5:be:ea:c9:6f:b4:74:96:
         74:b1:b4:50:6d:5a:67:a8:6a:e0:59:3c:62:ea:46:d7:f8:9e:
         a8:82:af:dd:0b:c6:b9:c9:98:08:ad:b1:8f:f1:cd:bc:35:2f:
         99:68:9f:b0:5a:ff:c1:df:85:4d:85:04:c4:97:ad:82:5a:54:
         ea:d6:6c:f2:c3:31:9a:dc:9f:2e:eb:76:56:b8:3d:7e:3f:d9:
         c6:5f:d6:48:99:a4:17:df:0e:1a:e9:94:3a:7c:48:8d:93:9e:
         ed:e9:a6:b8:5a:8a:1d:d0:ad:5c:63:6e:1e:95:ec:c8:5c:f5:
         ec:41:ff:4a:bc:86:90:48:01:ce:8b:c0:a8:f7:12:c5:26:e6:
         f3:5a:10:dd:e7:96:18:93:74:e0:84:26:48:f7:dc:a8:c4:81:
         9c:cb:f5:80:97:41:8f:ef:28:7a:33:89:83:ba:28:5d:ff:31:
         c4:70:8b:98:45:a8:86:eb:3e:29:f2:77:0e:04:75:82:7e:39:
         82:58:ae:0d
```

As you can see, there's no `CA:TRUE`, and no key usage requirements. And, somehow, it works? I guess, the absence of the key usage parameter means it's allowed to be used for anything maybe? I don't know. It also appears that multiple certificates can be passed, and only one has to pass validation.

At this point, I'm just confused.

**Comment by tsaarni** [comment]
> I guess, the absence of the key usage parameter means it's allowed to be used for anything maybe? 

Could be, I'm not familiar with this detail.  It would be interesting to know this.

Do you mean that in your previous tests where Contour did not work, you had Server Auth and Client Auth key usages, but not Certificate Sign?  I ask because coincidentally there has been also recent changes in Envoy in this area  https://github.com/envoyproxy/envoy/security/advisories/GHSA-837m-wjrv-vm5g so theoretically that could have impact as well

**Comment by tsaarni** [comment]
Looking at the change related to the CVE, it does not directly look like it would have any impact https://github.com/envoyproxy/envoy/compare/v1.20.1...v1.20.2.

**Comment by tsaarni** [comment]
> I guess, the absence of the key usage parameter means it's allowed to be used for anything maybe?

Googling this a bit and looking at the [code here](https://github.com/google/boringssl/blob/c7a3c46574e7fc32357b2cc68f961c56c72b0ca4/crypto/x509v3/v3_purp.c#L794-L795) it seems like this might be the case.
