### ISSUE TITLE
Contour Resource Limits data is very out of date

### ISSUE THREAD

**Issue by lou-lan** [projectcontour/contour#4400]
**What do you want the project to decide?**

https://projectcontour.io/guides/resource-limits/

I see on this page that contour's memory footprint is `244MB` at `5k` ingress and `5k` Service, and `2600MB` at `10k`.

In my own testing, 5k is nearly `500MB` and `10k` is `1.024GiB`.

The data does not look accurate.

| Test Criteria |          |      |     |     Contour |             |       Envoy |             |
|--------------:|---------:|-----:|----:|------------:|------------:|------------:|------------:|
|      #Service | #Ingress |  RPS |  CC | Memory (MB) | CPU% / Core | Memory (MB) | CPU% / Core |
|             0 |        0 |    0 |   0 |          10 |           0 |          15 |           0 |
|            5k |        0 |    0 |   0 |          46 |          2% |          15 |          0% |
|           10k |        0 |    0 |   0 |          77 |          3% |         205 |          2% |
|             0 |       5k |    0 |   0 |          36 |          1% |         230 |          2% |
|             0 |      10k |    0 |   0 |          63 |          1% |          10 |          1% |
|            5k |       5k |    0 |   0 |         244 |          1% |         221 |          1% |
|           10k |      10k |    0 |   0 |        2600 |          6% |         430 |          4% |
|             0 |        0 |  30k | 600 |           8 |          1% |          17 |          3% |
|             0 |        0 | 100k | 10k |          10 |          1% |         118 |         14% |
|             0 |        0 | 200k | 20k |           9 |          1% |         191 |         31% |
|             0 |        0 | 300k | 30k |          10 |          1% |         225 |         40% |

**Anything else you would like to add:**

```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-03-15T08:35:22Z"
  labels:
    test: ""
  name: svc-999
  namespace: default
  resourceVersion: "1332819"
  uid: 8ce4c815-128c-42fd-b7b4-1f52f20e0df8
spec:
  clusterIP: 10.98.41.45
  clusterIPs:
  - 10.98.41.45
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: "2022-03-15T08:35:22Z"
  generation: 1
  labels:
    test: ""
  name: svc-999
  namespace: default
  resourceVersion: "1332858"
  uid: 0609d069-8b8c-48cc-970b-110a0ab8a696
spec:
  defaultBackend:
    service:
      name: svc-999
      port:
        number: 80
  ingressClassName: contour
  rules:
  - host: svc-999
    http:
      paths:
      - backend:
          service:
            name: svc-999
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - ip: 10.0.2.150
```

**Comment by skriss** [comment]
Yeah, this data is quite old - I'm not sure exactly what version of Contour it was run with, but given it ran on Kubernetes 1.12, it's definitely due for a refresh.
