### ISSUE TITLE
Move setting of image pull policies to `IfNotPresent` into the release branch automation scripts

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4404]
Currently, when `make generate-deployment` is run and the files in https://github.com/projectcontour/contour/tree/main/examples/render are generated, all image pull policies are switched from `Always` to `IfNotPresent`. This make task is required to have been run for all PR's to main. The implication of this is that the rendered manifests on the `main` branch have an image pull policy of `IfNotPresent`, which doesn't really make sense on the `main` branch because the manifests use a Contour image tag of `main` which is constantly updating as `main` branch builds are happening.

We should move the logic that sets these image pull policies to `IfNotPresent` into https://github.com/projectcontour/contour/blob/main/hack/release/make-release-tag.sh, so that it only happens on release branches at the same time as we update the image tags to be immutable, version-specific tags, where `IfNotPresent` actually makes sense.

**Comment by rajatvig** [comment]
Have fixed the code in the new PR
