### ISSUE TITLE
consider changing "contour envoy shutdown" --check-delay default to 0s

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4422]
Currently, the `contour envoy shutdown` command has a default `--check-delay` value of `60s`. This means that, after triggering a deletion of Envoy, nothing happens for 60 seconds, at which point the command starts polling for remaining open connections.

I don't see any reason not to start checking for open connections right away. In the case where are no open connections, this means the Envoy pod can shut down immediately, rather than having to wait 60 seconds. The polling continues indefinitely, until there are few enough connections (default: none) to shutdown, so not sure what the delayed start is buying us.

**Comment by youngnick** [comment]
Agreed, feels like this should be at most 5 seconds or something.

**Comment by sunjayBhatia** [comment]
ha, yeah set that to 0s in the e2e tests just for that reason
