### ISSUE TITLE
run Gateway API conformance tests as part of CI

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4429]
At some point we should start running the Gateway API conformance tests as part of our CI, either for all builds or on a nightly basis. Right now, with the use of the provisioner and https://github.com/kubernetes-sigs/gateway-api/pull/1080, we're passing everything. We'd probably want to make it non-blocking if we run it for PRs, since as more tests get added to the suite we're bound to find existing gaps/bugs in our implementation.

**Comment by xaleeks** [comment]
can we add this to 1.21? @skriss

**Comment by skriss** [comment]
Yeah we should be able to, just waiting for one upstream PR to merge first.
