### ISSUE TITLE
make use of Envoy's path-based prefix matching

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4442]
Now that https://github.com/envoyproxy/envoy/issues/18148 has been implemented in https://github.com/envoyproxy/envoy/pull/20145, we should look to move our Ingress and HTTPRoute implementations to use this new prefix matching mode rather than our custom regex. We can implement this once Envoy 1.22 comes out.

**Comment by mmalecki** [comment]
(Feel free to assign me to this, I'm working on this in order to get #4300 going.)
