### ISSUE TITLE
Envoy in PROXY mode uses untrusted x-forwarded-for header information 

### ISSUE THREAD

**Issue by watzo** [projectcontour/contour#4449]
**What steps did you take and what happened:**
* followed guide https://projectcontour.io/guides/proxy-proto/ to enable PROXY protocol on AWS ELB
* x-forwarded-for was correctly filled in to remote IP address
* when x-forwarded-for was added as a client header, it got added to the chain

**What did you expect to happen:**
* I had expected the x-forwarded-for header sent by the client to be ignored
 
**Anything else you would like to add:**
Runtime envoy config:

use_remote_address: true
xff_num_trusted_hops: 0

**Environment:**

- Contour version: Bitnami helm chart contour-4.3.11 / 1.17.0-debian-10-r0
- Kubernetes version: (use `kubectl version`): v1.20.11-eks-f17b81
- Kubernetes installer & version: AWS EKS
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from `/etc/os-release`):

**Comment by sunjayBhatia** [comment]
contour supports configuring the number of trusted hops for the x-forwarded-for header here: https://projectcontour.io/docs/v1.20.1/configuration/#network-configuration

Does using that get you the behavior you expect?

**Comment by sunjayBhatia** [comment]
That setting won’t show up in the bootstrap file for envoy, the bootstrap is static configuration to get envoy running and connected to contour, the trusted hops setting will show up in the xDS config dump you can find following: https://projectcontour.io/docs/v1.20.1/troubleshooting/envoy-admin-interface/ (the /config_dump endpoint)

**Comment by watzo** [comment]
Thanks @sunjayBhatia. Indeed in the runtime config I can see the num-trusted-hops applied as xff_num_trusted_hops. So I guess I can isolate the issue to inconsistency in the envoy config or an issue with envoy itself?

**Comment by sunjayBhatia** [comment]
hm it may be that we have a bug tbh, since we do set `use_remote_address` on the `HTTPConnectionManager` but attempt to use the `original_ip_detection_extensions` filter (https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/http/original_ip_detection/xff/v3/xff.proto#extension-envoy-http-original-ip-detection-xff) to set the number of trusted hops 

I don't remember that disclaimer about not using `use_remote_address` being present being there before when I made the change, will try it out

**Comment by sunjayBhatia** [comment]
ok here is the envoy issue: https://github.com/envoyproxy/envoy/issues/17554 and https://github.com/envoyproxy/envoy/pull/17558

**Comment by sunjayBhatia** [comment]
looks like something we may have missed out on in between Contour 1.19 and 1.20 since we skipped from Envoy 1.19.1 to 1.21.0

**Comment by sunjayBhatia** [comment]
do you see `Original IP detection extensions and use_remote_address may not be mixed` in any Envoy logs?

**Comment by sunjayBhatia** [comment]
hm, you're on contour 1.17 though so this issue may not even apply, which would explain why you don't have any issues with the HTTPConnectionManager being rejected

**Comment by sunjayBhatia** [comment]
I think generally the point with the "trusted hops" setting is not that it restricts what goes in the header as passed to downstreams, but rather controls how Envoy calculates what the remote address the client is using

**Comment by watzo** [comment]
> I think generally the point with the "trusted hops" setting is not that it restricts what goes in the header as passed to downstreams, but rather controls how Envoy calculates what the remote address the client is using
> 
> and if you are using proxy protocol, the proxy protocol filter in Envoy uses the proxy header in the TCP connection rather than the HTTP headers

ok, so I think then we are closer to assessing this as a bug. Indeed, when --use-proxy-protocol is in use, the PROXY protocol dictates the remote address, and should ignore any downstream X-Forwarded-For header.

**Comment by watzo** [comment]
> hm, you're on contour 1.17 though so this issue may not even apply, which would explain why you don't have any issues with the HTTPConnectionManager being rejected

 I was in the process of upgrading Contour, on 1.18 the same behavior manifests.

**Comment by watzo** [comment]
> hm it may be that we have a bug tbh, since we do set `use_remote_address` on the `HTTPConnectionManager` but attempt to use the `original_ip_detection_extensions` filter (https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/http/original_ip_detection/xff/v3/xff.proto#extension-envoy-http-original-ip-detection-xff) to set the number of trusted hops

In the context of the PROXY protocol listener, this extension should not be used it seems, however, the config of the extension suggests that the default setting of xff_num_trusted_hops=0 should effectively disable it.

**Comment by sunjayBhatia** [comment]
there shouldn't be any bug in contour versions up until 1.19, this should become available in Contoyr 1.21: https://github.com/projectcontour/contour/pull/4470

**Comment by watzo** [comment]
> I think generally the point with the "trusted hops" setting is not that it restricts what goes in the header as passed to downstreams, but rather controls how Envoy calculates what the remote address the client is using
> 
> and if you are using proxy protocol, the proxy protocol filter in Envoy uses the proxy header in the TCP connection rather than the HTTP headers

Which component in Envoy should do the sanitizing of the headers? Because I would expect that untrusted headers would be stripped. X-Forwarded-Host and X-Forwarded-For should not have contained client provided input:

X-Envoy-Expected-Rq-Timeout-Ms: 15000
X-Envoy-External-Address: 10.205.70.134
X-Forwarded-For: 2.2.2.2,1.1.1.1,10.205.70.134
X-Forwarded-Host: illegal
X-Forwarded-Proto: https
X-Request-Id: 4250b829-a868-4835-8e77-46ef64ba8bda
X-Request-Start: t=1650482714.645

I'm currently trying to reproduce this in a local envoy setup (both on 1.17 and 1.21), not yet succeeding.

**Comment by sunjayBhatia** [comment]
I don't think it is intended that any proxy sanitizes that header, it is intended as untrusted information from a client that can possibly inform calculation as to what the actual client ip may be, based on how you have set up your proxy hops etc. (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#selecting_an_ip_address). It is definitely possible to spoof things, which is why it is not intended to be used w/o considerations.

Envoy does not strip content from that header but uses it and the "num trusted hops" setting to determine what the actual client ip may be for internal connection state data to pass along to filters etc. and to set in `x-envoy-external-address` for example: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-envoy-external-address

**Comment by sunjayBhatia** [comment]
Since you are using PROXY protocol, you can possibly also just remove the header: https://projectcontour.io/docs/v1.20.1/config/api/#projectcontour.io/v1.HeadersPolicy

**Comment by watzo** [comment]
> Since you are using PROXY protocol, you can possibly also just remove the header: https://projectcontour.io/docs/v1.20.1/config/api/#projectcontour.io/v1.HeadersPolicy

X-Forwarded-For and X-Forwarded-Host are used in an upstream system that I can't reconfigure easily (so I cannot use x-envoy-external-address)

I found a workaround using requestHeaderPolicy, but would rather fix this on a global configuration level.

  - name: X-Forwarded-For
     value: "%DOWNSTREAM_REMOTE_ADDRESS%"

**Comment by youngnick** [comment]
Adding this gotcha to the guide seems very reasonable to me. With the other PR @sunjayBhatia has proposed, do you think that would be enough to close this one out, @watzo?

**Comment by sunjayBhatia** [comment]
you can set that configuration globally using the option the request header policy option in the Contour config file: https://projectcontour.io/docs/v1.20.1/configuration/#policy-configuration (be sure when you update the contour ConfigMap to restart your Contour instances to pick up the changed config)
