### ISSUE TITLE
content length not allowed in 1xx or 204 ingress

### ISSUE THREAD

**Issue by chris93111** [projectcontour/contour#4458]
Hi 

we recently migrated ingress traefik to contour, I have an api that returns a 204 and the envoy crash with 502 

the error is content length not allowed in 1xx or 204 ingress

they are a solution to pass this parameter to envoy ?
envoy.reloadable_features.send_strict_1xx_and_204_response_headers: false

contour:1.20.1

**Comment by youngnick** [comment]
Thanks for this issue @chris93111.

It does seem like providing a content-length in either the 1xx or 204 cases is pretty strongly against the HTTP spec, which is unfortunate.

I think that @sunjayBhatia could probably verify, but it looks like the reloadable feature you mention has been or will soon be removed from Envoy: envoyproxy/envoy#19510 and envoyproxy/envoy#19524, so I don't think we can implement something using that for you.

Any thoughts here @sunjayBhatia ?

**Comment by sunjayBhatia** [comment]
Yeah, I think you are correct @youngnick, Envoy 1.22 removed that runtime guard so there is no chance of overriding this behavior going forward.

From https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2 (similar for `Transfer-Encoding` in section 3.3.1)
```
   A server MUST NOT send a Content-Length header field in any response
   with a status code of 1xx (Informational) or 204 (No Content).  A
   server MUST NOT send a Content-Length header field in any 2xx
   (Successful) response to a CONNECT request ([Section 4.3.6 of
   [RFC7231]](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.6)).
```

HTTP codec handling happens on responses before any header manipulation, so dropping those headers yourself on that route is not going to help either

unfortunately looks like the application will need to change to be compliant with the RFC

**Comment by chris93111** [comment]
Ok thanks finaly is logic
