### ISSUE TITLE
Use Envoy Stateful Session HTTP filter

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#4480]
**Please describe the problem you have**
There have been some requests for certain capabilities that cannot really be provided when implementing session affinity solely with a load balancing policy. The stateful session HTTP filter in Envoy may provide some more functionality: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/stateful_session_filter

e.g.
- ability to still route requests to backends that are draining or unhealthy, to ensure the session affinity continues
- using a load balancing strategy to balance requests evenly across backends, but still maintain persistent sessions

**Comment by joshsleeper** [comment]
sorry for the closed issue necro, but my company is evaluating contour and needs precisely this kind of functionality for a few applications that are... rather picky about session affinity unfortunately.

what can we do to get this issue reopened and get a discussion going?
