### ISSUE TITLE
Are service annotations for envoy cluster supposed to affect envoy high_priority as well as default_priority?

### ISSUE THREAD

**Issue by jordo** [projectcontour/contour#4497]
**What question do you have?:**

Are service annotations supposed to affect envoy `high_priority` as well as `default_priority` in envoy clusters?  When I add annotation to my service, ex: `projectcontour.io/max-connections: 40960` I see envoy cluster configuration is only updated for the `default_priority` and NOT the `high_priority`.  What implications does this have, and should contour be updating high_priority as well?

```
$ curl http://localhost:9001/clusters
default/tankkings-production-nakama-service/7351/da39a3ee5e::observability_name::default_tankkings-production-nakama-service_7351
default/tankkings-production-nakama-service/7351/da39a3ee5e::default_priority::max_connections::40960
default/tankkings-production-nakama-service/7351/da39a3ee5e::default_priority::max_pending_requests::40960
default/tankkings-production-nakama-service/7351/da39a3ee5e::default_priority::max_requests::40960
default/tankkings-production-nakama-service/7351/da39a3ee5e::default_priority::max_retries::40960
default/tankkings-production-nakama-service/7351/da39a3ee5e::high_priority::max_connections::1024
default/tankkings-production-nakama-service/7351/da39a3ee5e::high_priority::max_pending_requests::1024
default/tankkings-production-nakama-service/7351/da39a3ee5e::high_priority::max_requests::1024
```

**Environment:**

- Contour version: bitnami contour helm chart 7.4.2
- Kubernetes version: -
- Kubernetes installer & version: -
- Cloud provider or hardware configuration: -
- OS (e.g. from `/etc/os-release`): -

**Comment by sunjayBhatia** [comment]
apologies for not answering earlier, but contour does not set up any difference in endpoint priority at the moment so the difference there should not matter
