### ISSUE TITLE
Missing Annotation:  kubernetes.io/rewrite-target

### ISSUE THREAD

**Issue by HelloPb** [projectcontour/contour#4506]
Provide support for rewrite-target annotation for Kind: Ingress

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    contour.kubernetes.io/rewrite-target: /

**Environment:**

- Contour version: v1.20.1

**Comment by sunjayBhatia** [comment]
At this time I don't believe Contour maintainers have bandwidth to add *new* features for Ingress, we're mainly focused on HTTPProxy and Gateway API improvements, however contributions are always welcome and we can help move those forward!
