### ISSUE TITLE
adjust Gateway API conformance test runs

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4513]
Right now we're always running the latest and greatest Gateway API conformance tests. As @sunjayBhatia [rightly pointed out](https://github.com/projectcontour/contour/pull/4452#discussion_r844291931), this could be problematic since it's a moving target. I propose we do the following:

- change the PR build run to run against the conformance tests in the version of Gateway API that we use (via go.mod)*
- add a daily build that runs the latest/greatest conformance tests, so we can stay up-to-date and fix any issues as they arise

*the caveat is that there aren't any conformance tests in the [release-0.4](https://github.com/kubernetes-sigs/gateway-api/tree/release-0.4) branch, so we'll have to wait until 0.5 to move to this.

**Comment by sunjayBhatia** [comment]
sounds like a nice compromise 👍🏽
