### ISSUE TITLE
Add a switch option for httpproxy

### ISSUE THREAD

**Issue by yangyy93** [projectcontour/contour#4527]
**Please describe the problem you have**
[A clear, concise, description of the problem you are facing. What is the _problem_ that feature X would solve for you?]
I want to prevent the configuration of httpproxy from being sent to envoy without changing httpproxy. Now I can only do it by deleting httpproxy. Is it a better way to add an online/offline switch to httpproxy？

**Comment by sunjayBhatia** [comment]
you could use the `ingressClassName` field (https://projectcontour.io/docs/v1.21.0/config/api/#projectcontour.io/v1.HTTPProxySpec) to filter out proxies you want to "switch off"

**Comment by yangyy93** [comment]
> 您可以使用该`ingressClassName`字段（https://projectcontour.io/docs/v1.21.0/config/api/#projectcontour.io/v1.HTTPProxySpec）过滤掉您想要“关闭”的代理

Thanks for your answer, this does solve the problem
