### ISSUE TITLE
deploy contour and envoy by apply yaml file but envoy not listening https port 8443 

### ISSUE THREAD

**Issue by wuzhuoquan** [projectcontour/contour#4538]
**What question do you have?:**
I deploy contour and envoy by apply the yaml file: https://github.com/projectcontour/contour/blob/main/examples/render/contour-deployment.yaml

And I create a httpproxy resource,It works well on http port 8080

but i found that envoy pod not listening the https port 8443

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The pods running
```
[root@master01 render]# kubectl get pod -n projectcontour
NAME                       READY   STATUS    RESTARTS   AGE
contour-6cb9f6c4bb-54z4t   1/1     Running   0          14h
contour-6cb9f6c4bb-d7f9j   1/1     Running   0          14h
envoy-5c4ff6546-cb8j5      2/2     Running   0          37m
envoy-5c4ff6546-ck26c      2/2     Running   0          36m
```

But in the envoy container, not listening the https port 8443
```
[root@node02 ~]# docker ps |grep envoy
ae002fe06572        registry.cn-hangzhou.aliyuncs.com/wuzhuoquan/envoyproxy               "envoy -c /config/en…"   38 minutes ago      Up 38 minutes                           k8s_envoy_envoy-5c4ff6546-cb8j5_projectcontour_3cee8e1b-f731-41ed-9c28-3bcb28056824_0
f11e5da3662d        registry.cn-hangzhou.aliyuncs.com/wuzhuoquan/contour                  "/bin/contour envoy …"   38 minutes ago      Up 38 minutes                           k8s_shutdown-manager_envoy-5c4ff6546-cb8j5_projectcontour_3cee8e1b-f731-41ed-9c28-3bcb28056824_0
899d929f4425        registry.cn-hangzhou.aliyuncs.com/google-containers/pause-amd64:3.0   "/pause"                 38 minutes ago      Up 38 minutes                           k8s_POD_envoy-5c4ff6546-cb8j5_projectcontour_3cee8e1b-f731-41ed-9c28-3bcb28056824_0
[root@node02 ~]# docker inspect ae002fe06572 |grep Pid
            "Pid": 1036575,
            "PidMode": "",
            "PidsLimit": null,
[root@node02 ~]# nsenter -n -t 1036575
[root@node02 ~]# netstat -anltp|grep -i listen
tcp        0      0 0.0.0.0:8002            0.0.0.0:*               LISTEN      1036575/envoy
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      1036575/envoy
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1036575/envoy
tcp6       0      0 :::8090                 :::*                    LISTEN      1036529/contour
```

**Environment:**

- Contour version: envoy 1.22.0
- Kubernetes version: (use `kubectl version`): 1.20.4
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): centos8

**Comment by tsaarni** [comment]
Envoy should start listening `:8443` when there is valid TLS configuration. How does the `HTTPProxy` resource look like, have you set `HTTPProxy.spec.virtualhost.tls.secretName`?

**Comment by wuzhuoquan** [comment]
> Envoy should start listening `:8443` when there is valid TLS configuration. How does the `HTTPProxy` resource look like, have you set `HTTPProxy.spec.virtualhost.tls.secretName`?

It‘s that mean I must create a ```HTTPProxy``` resource with ```valid TLS configuration```, or envoy will not start listening ```:8443```?
I didn't create tls HTTPProxy  with ```HTTPProxy.spec.virtualhost.tls.secretName```, but I create with ```HTTPProxy.spec.virtualhost.tls.passthrough```  like this：
```
spec:
  routes:
  - services:
    - name: demoapi-v1
      port: 8080
  virtualhost:
    fqdn: demoapi.com
    tls:
      passthrough: true
```
but still, not listening ```:8443```

**Comment by tsaarni** [comment]
Ok in case of `passthrough` the `secretName` is not given, sorry for the confusion. 

In `passthrough` case TLS is to be passed through the proxy to the upstream service without decrypting and Envoy cannot handle HTTP level `routes` since it does not process HTTP inside the TLS connection. Its unfortunate there wasn't error message telling this.  Try this instead

```yaml
spec:
  tcpproxy:
    services:
    - name: demoapi-v1
      port: 8080
  virtualhost:
    fqdn: demoapi.com
    tls:
      passthrough: true
```

Port `8080` in `demoapi-v1` should accept TLS connections, since `passthrough` means that the upstream service receives the external TLS connection.

**Comment by wuzhuoquan** [comment]
Ok,thank you.
I will try again.
