### ISSUE TITLE
Move upgrade path/recommendation to the top of release note

### ISSUE THREAD

**Issue by victorcq** [projectcontour/contour#4541]
As a Contour user, I'd prefer to have the upgrade path/recommendation at the top of each release note, so that it's more obvious. 

For example, `v1.21.0` has the following requirements, but it's put under "Minor Changes" in the [release note](https://github.com/projectcontour/contour/releases/tag/v1.21.0)

> Upgrading to this version of Contour will explicitly require you to upgrade to Contour v1.20.0 first to ensure proper migration of leader election coordination resources.

**Comment by youngnick** [comment]
I agree that anything that has hard requirements on this should actually be a major change so that it's at the top of the file. Thanks for calling it out @victorcq!
