### ISSUE TITLE
Gateway API: ReferencePolicy -> ReferenceGrant rename

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4555]
Gateway API is renaming the `ReferencePolicy` resource to `ReferenceGrant`. We'll need to update Contour for this.

ref. https://github.com/kubernetes-sigs/gateway-api/pull/1179

**Comment by youngnick** [comment]
As of today, ReferencePolicy will be still included in v0.5.0, so it's not super urgent, but we should move before v0.6.0, when it will be removed (and most likely, moved to beta tbh).

**Comment by skriss** [comment]
Still to do: drop ReferencePolicy when we upgrade to v0.6.0.

**Comment by skriss** [comment]
Moving to 1.24 since it's unlikely we'll get Gateway API v0.6 into 1.23.

**Comment by skriss** [comment]
- [ ] drop ReferencePolicy support (#4830)
- [ ] update ReferenceGrant to v1beta1
