### ISSUE TITLE
Gateway API: support multiple RequestMirror filters per rule in HTTPRoute [extended]

### ISSUE THREAD

**Issue by sejongk** [projectcontour/contour#4566]
Currently, Contour only supports a single RequestMirror filter per rule in HTTPRoute (#4557). 
As mentioned in https://github.com/projectcontour/contour/pull/4557#discussion_r892903763, we can improve this by supporting multiple RequestMirror filters per rule in HTTPRoute as follows:
If there is more than one RequestMirror filter, then each filter defines a backend to mirror traffic to.
Finally, Contour gets the whole backends, converts these to a slice of MirrorPolicies, and set the slice to `dag.Route.MirrorPolicy`
ref. https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.HTTPRouteFilter
(Support: Extended)

**Comment by sepaper** [comment]
Hi, @skriss. I'm tackling this improvement and having an issue with this. 

Currently, multiple HTTPRouteFilters with the same type are not supported on the Core/Extended filters(ref. https://github.com/kubernetes-sigs/gateway-api/issues/598).
Therefore, it seems better to change the current `HTTPRequestMirrorFilter.backendRef` which type is `BackendObjectReference` into `HTTPRequestMirrorFilter.backendRefs` which type is `[]BackendObjectReference` in Gateway API.

I'm planning to open a new issue in the gateway-api repository to discuss the above improvement.
Would you mind sharing your idea before I open a new issue for this?

**Comment by skriss** [comment]
Closing since per https://github.com/kubernetes-sigs/gateway-api/issues/598, the admission webhook does not allow multiple core filters of a given type per rule.

**Comment by sepaper** [comment]
@skriss Thanks for the comment!

**Comment by skriss** [comment]
Reopening this issue, as https://github.com/kubernetes-sigs/gateway-api/pull/2199 has added support for multiple mirror filters per rule. Help wanted!

**Comment by LiorLieberman** [comment]
you can assign it to me,  already came up with some draft

**Comment by LiorLieberman** [comment]
To clarify, does it mean we want to add support for HTTPProxy as well?

**Comment by sunjayBhatia** [comment]
> To clarify, does it mean we want to add support for HTTPProxy as well?

Looks like it was originally only supported on a single backend due to Envoy only supporting a single mirror policy on a RouteAction

I'm not sure we've actually seen any requests to mirror to multiple services with HTTPProxy so I'm ok with leaving HTTPProxy changes out of this and keeping this focused on keeping up with Gateway API conformance

**Comment by LiorLieberman** [comment]
> I'm not sure we've actually seen any requests to mirror to multiple services with HTTPProxy so I'm ok with leaving HTTPProxy changes out of this and keeping this focused on keeping up with Gateway API conformance

Anyway we have to change bits of HTTPProxy, (since it also uses dag). We can do minimal changes in HTTPProxy to use MirrorPolicy list, so we keep multiple mirrors unsupported and then follow up with it. 

I will upload a draft PR and ask for feedback there

**Comment by LiorLieberman** [comment]
draft pr is here: https://github.com/projectcontour/contour/pull/5652

**Comment by maczikasz** [comment]
Hi, is this feature released yet or do you have a plan s to which release (and when) this will be available?

**Comment by skriss** [comment]
@maczikasz Looks like this landed in Contour 1.26.0: https://github.com/projectcontour/contour/blob/main/changelogs/CHANGELOG-v1.26.0.md#adding-support-for-multiple-gateway-api-requestmirror-filters-within-the-same-http-or-grpc-rule

**Comment by maczikasz** [comment]
@skriss awesome, sorry to have missed it, thanks
