### ISSUE TITLE
remove Contour E2E's that overlap with Gateway API conformance

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4579]
As upstream Gateway API conformance tests are built out, we can probably get rid of overlapping Contour E2E's that validate the same functionality. This will save some CI time and reduce maintenance burden. As a starting point, once we upgrade to Gateway API v0.5.0 and pin to the conformance tests included there, we should do an audit of Contour's E2E's and drop any redundant ones.

**Comment by sunjayBhatia** [comment]
unstaling, this seems worthwhile to do

**Comment by sunjayBhatia** [comment]
some removals going in here: https://github.com/projectcontour/contour/pull/4765

**Comment by skriss** [comment]
Adding this to the current milestone for tracking, we'll likely carry it forward.

**Comment by skriss** [comment]
Bumping to 1.24.0 for continued work.

**Comment by skriss** [comment]
@sunjayBhatia anything else here for 1.24, or shall we move this over to 1.25 for continued work?

**Comment by sunjayBhatia** [comment]
looks like none of the gateway tests are removable due to overlap with v0.7.1 or v0.8.0-rc1 tags as far as I can tell, can call this done for v1.26.0 IMO

**Comment by skriss** [comment]
I'm going to close this out as we've done most/all of this work by now. Can file specific issues as anything else comes up.
