### ISSUE TITLE
kubernetes dashboard access issue with tls certificate

### ISSUE THREAD

**Issue by rshiva777** [projectcontour/contour#4606]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Deployed kubernetes dashboard on cluster and able to access UI using httpproxy  with tls as passthrough: true.

$curl https://dashboard.test.internal.com -k
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

i am able to curl with -k option and access dashboard UI

But when i try to use the tls certificate on contor httpproxy, i am getting the below error  

$curl https://dashboard.test.internal.com 
"Client sent an HTTP request to an HTTPS server."

**What did you expect to happen:**

it should work with tls certificate. should be able to get UI access and curl
Also i see the below error on logs on envoy container

Chrome/91.0.4472.124 Safari/537.36" "7a549c-ea40-4c14-8cd-a10dd970" "dashboard.test.internal.com " "100.96.5.15:8443"
[2022-07-01T15:16:56.035Z] "GET / HTTP/2" 400 - 0 48 1 1 "100.96.1.1" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: v1.12.0
- Kubernetes version: (use `kubectl version`): 1.21
- Kubernetes installer & version: 1.21
- Cloud provider or hardware configuration:  vmware 
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by tsaarni** [comment]
You mentioned that TLS passthrough works, so the upstream service (the dashboard) was terminating TLS. Could it be that error _"Client sent an HTTP request to an HTTPS server"_ is coming from the dashboard, which still expects to terminate TLS, but now receives cleartext HTTP since the termination happens at the proxy.

Do you still want to use TLS between the proxy and the dashboard? If yes, check https://projectcontour.io/docs/v1.21.1/config/upstream-tls/.

**Comment by rshiva777** [comment]
@tsaarni 

Thanks for the inputs. After enabling the upstream annotation in the service file of dashboard i am able to access it on browser and shell

Solution:
I added the below annotation to the dashboard service file which solved the issue

    projectcontour.io/upstream-protocol.tls: "80"

**Comment by tsaarni** [comment]
@rshiva777 Thanks for the update, great news it now works! 

Closing the issue.
