### ISSUE TITLE
upgrade test flakes after releasing v1.22.0

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4647]
I've seen several (but not all) of the upgrade test runs fail after releasing v1.22.0. The failures can be seen at the top of https://github.com/projectcontour/contour/actions/workflows/prbuild.yaml. They all point to the code that waits for the Envoy DaemonSet to be out-of-date, and then updated. I'm wondering if the upgrade is a no-op so it never becomes out-of-date, though that doesn't explain why it still succeeds sometimes. Needs a little more digging into.

**Comment by skriss** [comment]
I'm taking a look at this, from my initial testing it looks like the DaemonSet fully updates during the time that the test is waiting for the Deployment to update, so by the time it gets to the "wait for DaemonSet to be out of date" check, it's too late since it's already updated. I'll see what changes we can make, perhaps we can just get rid of the "wait for DaemonSet to be out of date" check since there's no longer a 60-second drain delay.

**Comment by sunjayBhatia** [comment]
> I'm taking a look at this, from my initial testing it looks like the DaemonSet fully updates during the time that the test is waiting for the Deployment to update, so by the time it gets to the "wait for DaemonSet to be out of date" check, it's too late since it's already updated. I'll see what changes we can make, perhaps we can just get rid of the "wait for DaemonSet to be out of date" check since there's no longer a 60-second drain delay.

ah yeah the drain delay changed by default! was wondering why we didnt run into this earlier with these tests
