### ISSUE TITLE
E2E test flake: Gateway API request mirror test

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4650]
We've seen the Gateway API request mirror test flaking recently. Here's one example:

https://github.com/projectcontour/contour/runs/7566077014?check_suite_focus=true#step:7:222

Ideally we can find and address the flake, but if not, we should add retries into the test definition to avoid having to re-run manually.

**Comment by sunjayBhatia** [comment]
unstaling since a CI flake that we need to keep track of
