### ISSUE TITLE
Fluxcd CRD apply : var substitution failed for 'tlscertificatedelegations.projectcontour.io'  YAMLToJSON: yaml: line 79: found unknown escape character

### ISSUE THREAD

**Issue by alokhom** [projectcontour/contour#4672]
facing issues with CRD tlscertificatedelegations.projectcontour.io
 YAMLToJSON: yaml: line 79: found unknown escape character
 
 file: https://github.com/projectcontour/contour/blob/main/examples/contour/01-crds.yaml

**Comment by sunjayBhatia** [comment]
can you provide exactly which version of contour is being installed here? line 79 of `main` is currently: https://github.com/projectcontour/contour/blob/87fc2ffba5b636e836f3c2cd04d57a767c244c32/examples/contour/01-crds.yaml#L79

we also have end to end tests ensuring at least `main` and the previous release YAMLs apply correctly

**Comment by skriss** [comment]
Closing this out as inactive, feel free to reach out again if needed.
