### ISSUE TITLE
Support gateway.networking.k8s.io

### ISSUE THREAD

**Issue by hobyte** [projectcontour/contour#4678]
As the `ingress` API in kubernetes is limited to only **http** and **https** traffic, **UDP** and **TCP** routing could only be routed with `CRDs` provided by the proxy. To make routing of **UDP** and **TCP** easier, kubernetes introduced the [`Gateway API`](https://kubernetes.io/blog/2021/04/22/evolving-kubernetes-networking-with-the-gateway-api/).

It would be nice, if contour supports this API, as it makes routing much more flexible.

Example usage: [mailu](https://mailu.io) mail server uses ingress to publish the web interfaces, but NodePort to publish the IMAP, ... Connections. With Contour supporting Gateway API, mailu could use the Gateway API for all Protocols

**Comment by sunjayBhatia** [comment]
Contour does support v1beta1 of the Gateway API, see: https://projectcontour.io/guides/gateway-api/

Also note that Contour does not plan to support UDPRoute or TCPRoute at this time since we are focused on L7 capabilities

**Comment by skriss** [comment]
Closing this one out, feel free to reach out again if you have further questions.
