### ISSUE TITLE
Optional CRD-s

### ISSUE THREAD

**Issue by Zsolt-LazarZsolt** [projectcontour/contour#4684]
Rationale: We are using Contour in a multi tenant environment, usually more than one Contour is installed on the same cluster, also different versions are in play.
To solve helm ownership issues on resources, we are handling the required CRD-s in it's own lifecycle as a separate helm package. For that reason we are trying to minimize the amount of CRD-s to take care of, only introduce them to the lifecycle when absolutely required.
As an example: so far have not needed extensionservices, contourconfiguration or contourdeloyment resources.

Currently Contour has a hard dependency on CRD-s, without all of them the Contour process fails to start.
I would propose to optionally create the informers on all CRD resources, only warn on the resources missing instead of a full stop.
That way if some of the CRD-s are missing, Contour can start up, only the related functionalities are left out of use.

**Comment by skriss** [comment]
Hey @Zsolt-LazarZsolt, that's an interesting idea. I think it's a fair point that some (many?) folks may not be using `ExtensionService`, `ContourConfiguration`, and `ContourDeployment`, and also that they aren't required for Contour's core functionality to work. The main downside I see is that users wouldn't get immediate/obvious feedback if something is wrong with their installation and some of the CRDs did not get created. One option would be to make this opt-in behavior, so adding a flag like `--allow-missing-crds` that would allow Contour to start up and function if some CRDs were absent, but by default it would still behave as it does today.

**Comment by Zsolt-LazarZsolt** [comment]
That would be perfect. Best of both worlds. :)

**Comment by tsaarni** [comment]
I think part of the CRDs are already optional:

* `ContourDeployement` CRD needs to be installed only if executing `contour gateway-provisioner`. Executing it without the CRD does not make much sense either, so maybe it is already optional enough.
* The Gateway API CRDs need to be installed only if Gateway API is configured, so optionality exists there via the config. 
 
It seems to me that `ExtensionService` and `ContourConfiguration` are the only mandatory CRDs that could be optional? What could further motivate it, is that they are still labeled as `v1alpha1`. But I have some doubts just ignoring errors, if `--allow-missing-crds` would do that. 

@skriss Would it make sense to add feature flags like `--disable-extensionservice` and `--disable-contourconfiguration` which would make Contour not register informers for those objects at all? That way the CRDs could be optional without having to ignore errors.

I chatted with Zsolt, and it could work for him.

**Comment by nsimons** [comment]
I could have a stab at this, looks simple enough to be a good first PR and get my feet wet!

kingpin does not yet support the setting several arguments with a comma separator, looks like it's coming in a [future version](https://github.com/alecthomas/kingpin/commit/b88248d8da3f8a9eb99fc83b47a53b295e9fc8ee). We could parse it ourselves from a `StringVar`, but I believe it makes more sense to use a `EnumsVar`; then we get the validation for free as well (we can restrict the possible arguments of the flag).
