### ISSUE TITLE
Add a page to the website documenting Contour's integrations with other tools

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4704]
It'd be great to have a page on the website documenting/linking to docs on Contour's integrations with various other tools. Some I know of off the top of my head:
- [Open Service Mesh](https://release-v1-2.docs.openservicemesh.io/docs/demos/ingress_contour/)
- [Linkerd](https://linkerd.io/2.12/tasks/using-ingress/#contour)
- [knative serving](https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#install-a-networking-layer)
- [ArgoCD](https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#contour)
- ...

ref. #2204
ref. #2920
ref. #2089
ref. #2506

**Comment by MaryAyobami** [comment]
Hello @skriss I'd love to work on this, can I proceed?

**Comment by skriss** [comment]
@MaryAyobami This is already being worked on in #5537, but if there's more to do once the initial page merges, we would definitely take your help.
