### ISSUE TITLE
E2E test flake: gRPC

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4707]
e.g. https://github.com/projectcontour/contour/runs/8254026285?check_suite_focus=true#step:7:251

TODO: try to de-flake, possibly add `FlakeAttempts(3)`

**Comment by sunjayBhatia** [comment]
Haven't been able to repro this one locally so added flake attempts

**Comment by sunjayBhatia** [comment]
nooooooooo :(

**Comment by sunjayBhatia** [comment]
submitted https://github.com/projectcontour/contour/pull/4743

**Comment by sunjayBhatia** [comment]
haven't seen this in a while, going to remove the flake attempts

**Comment by skriss** [comment]
This appears to be resolved, closing this out!
