### ISSUE TITLE
rewrite-target $1 - contour configuration

### ISSUE THREAD

**Issue by giladk1221** [projectcontour/contour#4714]
Hi,
I'm using the Builtin NSX-T ingress controller for a long time.
I decided to implement contour Ingress instead.
in the Ingress Manifest, I added relevant annotation for rewrite-target - ingress.kubernetes.io/rewrite-target: /$1(like was configured in NSX-T manifest too).
It looks like this configuration didn't do anything with contour.

Is there any other method to implement rewrite-target to /$1 with HTTP proxy or something like that?
in the documentation, I can see only mentions of a specific path and didn't see anything for  $1 or something similar to this configuration.

waiting for your response, 

Gilad

**Comment by sunjayBhatia** [comment]
If you would like to use path rewriting in Contour, take a look at the HTTPProxy resource: https://projectcontour.io/docs/v1.22.1/config/request-rewriting/#path-rewriting
