### ISSUE TITLE
Does Contour Ingress work with k3s/k3d?

### ISSUE THREAD

**Issue by HummingMind** [projectcontour/contour#4718]
Hello,
I can't seem to get Contour installed on a K3D cluster (1 master 3 workers).
I was able to get Emissary working, but I would prefer to use Contour if I can get it to work. Obviously, I skipped the Traefik deployment during k3d cluster creation.

No errors show up, but it seems to be stuck on this:

![image](https://user-images.githubusercontent.com/87399963/189731619-b50cb45c-33da-4e59-8f25-31c511b9d6fd.png)

Looks like the control plane pod is running, but not the envoy pods.

I know you need a loadbalancer, but I thought k3d provided it's proxy pod for this purpose.
Any help is appreciated.

**Environment:**

- Contour version: 1.22.1
- Kubernetes version: (use `kubectl version`): 1.24.4
- Kubernetes installer & version: k3d 5.4.6
- Cloud provider or hardware configuration: local via k3s/k3d
- OS (e.g. from `/etc/os-release`): Windows 11 with Docker Desktop running on WSL2 (Ubuntu).

**Comment by sunjayBhatia** [comment]
Does inspecting the status of the Envoy daemonset offer any hints, e.g. output from `kubectl -n projectcontour describe daemonset/envoy`

**Comment by HummingMind** [comment]
> Does inspecting the status of the Envoy daemonset offer any hints, e.g. output from `kubectl -n projectcontour describe daemonset/envoy`

Is there something specific there to look at?
In the events, I see three SuccessfulCreate events for the pods.

**Comment by HummingMind** [comment]
It actually seems to break the k3d cluster. :o
Restarting docker, you can see all of the k3d containers exited with code 255. And after starting them up again kubectl can't connect to the cluster anymore.

Has anyone from the team ever tested Contour with k3d clusters? I know KIND is supported, but k3d has quite a few more features that are advantageous.

**Comment by sunjayBhatia** [comment]
> Is there something specific there to look at?

the pods are in the `Pending` state so they are either waiting to be scheduled or one for of their containers to initialize, do you see any more detail there? from your screenshot it looks like the envoy pods have not been assigned a node? also from a quick look, it seems traefik is automatically installed w/ k3d as an ingress controller, you may want to be sure there are no hostport or other conflicts, depending on how they are both deployed

I have not personally used k3d with Contour, myself

**Comment by sunjayBhatia** [comment]
a quick try with a vanilla seeming k3d cluster and I get the following:

```
Warning  FailedScheduling  7s    default-scheduler  0/3 nodes are available: 1 node(s) didn't have free ports for the requested pod ports. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod.
```

**Comment by sunjayBhatia** [comment]
yeah looks like a conflict with the existing `traefik` daemonset

**Comment by HummingMind** [comment]
Did you make sure to skip the traefik deployment? If you are creating the cluster via the command line, you can do this:
k3d cluster create --server-arg "--no-deploy=traefik"

**Comment by sunjayBhatia** [comment]
> Did you make sure to skip the traefik deployment? If you are creating the cluster via the command line, you can do this: k3d cluster create --k3s-arg="--disable=traefik@server:*"

ah, its not just disabling traefik but also the `svclb-envoy-*` daemonset that needs to be disabled to stop the port conflict

**Comment by HummingMind** [comment]
I think that is their virtual load balancer. It's part of the reason I picked k3d, so I don't have to mess with things like MetalLB. I can just map a port to their load balancer and I can access it on my machine via localhost using that load balancer. At least that's the idea.

Any idea why Contour has a conflict with it? It seems to work with Emissary, which is also Envoy based?

**Comment by sunjayBhatia** [comment]
nothing fundamental about Envoy, its how the daemonsets are configured, both have hostports configured for port 80 and 443, you can just remove the hostport configuration from Contours Envoy daemonset and everything should work, just tried it out

**Comment by HummingMind** [comment]
Awesome! I just have to figure out how to do that now. 😁 
Do I have to do that through a HELM chart then?

Sorry, I am still rather new to Kubernetes. 😢 

Thank you!

**Comment by HummingMind** [comment]
It would be nice if you guys could add a mention of k3d compatibility to your documentation for newbies like myself.
You can go ahead and close this issue.

Once again, thank you for figuring this out!
Have a great day!

**Comment by HummingMind** [comment]
Just a final update:
for some reason removing the hostPorts via the envoy.useHostPort=false parameter would still have some of the pods in pending state. Setting the envoy.hostPorts.http and envoy.hostPorts.https parameters to something other than 80 and 443 seems to have worked. At least all the pods came up.
