### ISSUE TITLE
How can I convert unit millisecond to  seconds in access log

### ISSUE THREAD

**Issue by vnline** [projectcontour/contour#4726]
I want to customize access log , convert %DURATION% and %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% millisecond unit to seconds unit. Is there anyway to do it ? 

json-fields:
 - "request_time=%DURATION%"
 - "upstream_response_time=%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"

Use seconds unit in access log

**Comment by sunjayBhatia** [comment]
There are some guidelines on this page for converting an operator like `%DURATION%` to a different unit: https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#command-operators (see the section about customizing `%START_TIME%`)

I'm not entirely sure you can do the same with a value grabbed from a request/response header, but worth a try

**Comment by vnline** [comment]
> There are some guidelines on this page for converting an operator like `%DURATION%` to a different unit: https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#command-operators (see the section about customizing `%START_TIME%`)
> 
> I'm not entirely sure you can do the same with a value grabbed from a request/response header, but worth a try

I had try set like below,but report not support.
  - "request_time=%DURATION(%s.%6f)%"
  - 
time="2022-09-17T02:11:16Z" level=error msg="Error adding/updating listener(s) ingress_http: Not supported field in StreamInfo: DURATION(%s.%6f)\n" code=13 connection=134 context=xds node_id=envoy-sc62c node_version=v1.19.1 response_nonce=1 version_info=2
