### ISSUE TITLE
Please support Rate Limit in Gateway API

### ISSUE THREAD

**Issue by kahirokunn** [projectcontour/contour#4730]
https://github.com/projectcontour/contour/blob/08d87aefcdeba93665b04e8b6a893efc8d9d5671/design/gateway-apis-implementation.md

> This design is intended to cover the initial alpha releases of the Gateway API. We will aim to implement the core featureset of the APIs at that point.
We will then work with the upstream community on features that Contour and HTTPProxy currently support, but the Gateway API do not, and how best to represent those features in the APIs.
There are some features that are currently gaps for Contour (wildcard domain names, and exact path matching, for example), and some that Contour supports that the Gateway API do not (websockets, configurable timeouts, header replacement, external auth, rate limiting, and so on).

There was a note like this one year ago, but a year has already passed.
What is the current plan to support Rate Limit in the Gateway API?

It seems that the necessary components to implement Rate Limit, such as [Policy Attachment](https://gateway-api.sigs.k8s.io/references/policy-attachment/), are already in place.
https://github.com/kubernetes-sigs/gateway-api/issues/326#issuecomment-1192014068

**Comment by sunjayBhatia** [comment]
Now that Gateway API has extension points as you mention, the next steps for features like this are to come up with a design for "*Policy" CRDs and/or HTTPRoute filter extension CRDs to provide the the relevant configuration options

Some design writeups are in the works and we would appreciate feedback and comments on them

**Comment by kahirokunn** [comment]
That's something to look forward to!
