### ISSUE TITLE
Add GatewayClass finalizer

### ISSUE THREAD

**Issue by izturn** [projectcontour/contour#4732]
**Please describe the problem you have**
When a controller starts managing a Gateway, it is supposed to update its GatewayClass with a finalizer so that the GatewayClass cannot be deleted while there are still Gateways referring to it.

https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.GatewayClass

  > Whenever one or more Gateways are using a GatewayClass, implementations MUST add
  >  the gateway-exists-finalizer.gateway.networking.k8s.io finalizer on the associated GatewayClass. 
  > This ensures that a GatewayClass associated with a Gateway is not deleted while in use.

**Comment by skriss** [comment]
Thanks @izturn, looks like this is a dupe of #3866 but we can close the old one out and track here.

**Comment by izturn** [comment]
@skriss thx, I saw your comments for https://github.com/envoyproxy/gateway/pull/373, pls show me how to implement it for `contour`,  I like to implement it

**Comment by skriss** [comment]
There is currently some upstream discussion on whether this should be part of the Gateway API spec or not (https://github.com/kubernetes-sigs/gateway-api/issues/1411), let's hold off on doing anything until that is resolved.

**Comment by izturn** [comment]
got it
