### ISSUE TITLE
Support  scrape Contour/Envoy metrics by Prometheus Operator

### ISSUE THREAD

**Issue by izturn** [projectcontour/contour#4746]
**Please describe the problem you have**
```
// TODO [danehans]: Remove the prometheus annotations when Contour is updated to
// show how the Prometheus Operator is used to scrape Contour/Envoy metrics.
PodAnnotations: map[string]string{
	"prometheus.io/scrape": "true",
	"prometheus.io/port":   "8002",
	"prometheus.io/path":   "/stats/prometheus",
},
```

```
// TODO [danehans]: Remove the prometheus annotations when Contour is updated to
// show how the Prometheus Operator is used to scrape Contour/Envoy metrics.
Annotations: map[string]string{
	"prometheus.io/scrape": "true",
	"prometheus.io/port":   fmt.Sprintf("%d", metricsPort),
},
```

I'd like to implement this as follows:
1. add a flag to ContourDeployment:

>
> type ContourDeploymentSpec struct {
>	// +optional
>	EnableMetrics bool  `json:"enableMetrics,omitempty"`
> }
2. if `EnableMetrics` equals to `false`, do nothing
3. otherwise, expose ports for services: contour/8000 & envoy/8002
4. `kubectl apply` `CR\ServiceMontior` by themself (optional)
5. that's all

@skriss @sunjayBhatia  any advise?

**Comment by sunjayBhatia** [comment]
Are you using the prometheus operator @izturn? I don't think we've had any explicit comments about using it except for that comment from the original contour operator codebase

**Comment by sunjayBhatia** [comment]
I think with the naming here we would want to be explicit that we're setting it up for use by the prometheus operator
- maybe an explicit "PrometheusSettings" type with an option to use the traditional annotations method or the operator method

*or* give users the ability to do what they want to the various Service objects to ensure they get what they want without us having to worry about that external component (and possibly provide some documentation on how to integrate with it)
- I think this sort of lines up with this PR: https://github.com/projectcontour/contour/pull/4705

**Comment by izturn** [comment]
yes, i like the `option 2`
