### ISSUE TITLE
test/e2e/upgrade: Failing upgrade tests

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#4771]
Recent failures of the e2e upgrade tests

Failures are in the uptime, less than 90% uptime during the upgrade

See examples:
- https://github.com/projectcontour/contour/actions/runs/3176941431/jobs/5176897679
- https://github.com/projectcontour/contour/actions/runs/3161373907/jobs/5146962389

**Comment by sunjayBhatia** [comment]
added to 1.23.0 milestone so we track this

**Comment by sunjayBhatia** [comment]
haven't been able to repro locally, but it is a little interesting that its only happened so far on the 1.25 k8s runs

**Comment by sunjayBhatia** [comment]
haven't yet been able to repro in workflow runs in my fork either unfortunately

**Comment by sunjayBhatia** [comment]
tentatatively want to close this since we haven't seen it again, but will keep it around maybe until the next release

**Comment by skriss** [comment]
I think we're good to close this out for now, have not seen any failures on CI in quite awhile.
