### ISSUE TITLE
add support for "ALL" DNS lookup family

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4778]
Envoy's [DNS lookup family setting](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-enum-config-cluster-v3-cluster-dnslookupfamily) now supports an "ALL" option. When selected, both IPv4 and IPv6 addresses are returned by the DNS resolver (if they exist), and [Happy Eyeballs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/connection_pooling#arch-overview-happy-eyeballs) is enabled for upstream connections, which allows Envoy to efficiently detect whether to use ipv6 or ipv4 connections. This is a nice option for a dual-stack environment where a combination of IPv4 and IPv6 may be needed, and may make a good default setting for Contour users. At a minimum, we should enable it as an option for DNS lookup family.

**Comment by Vishal-Chdhry** [comment]
\assign

**Comment by sunjayBhatia** [comment]
@Vishal-Chdhry hey there I can assign you if you would like to work on this, let us know if you have any questions about what to do here!

**Comment by Vishal-Chdhry** [comment]
Thank you so much @sunjayBhatia! Yes, it would be really helpful if you could give me some guidance on the changes i need to make
