### ISSUE TITLE
update actions/checkout and actions/cache to v3

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4785]
In our latest daily CI run we got warnings for some of our GitHub actions: https://github.com/projectcontour/contour/actions/runs/3226663519 (see Annotations below the diagram)

The linked blog indicates we need to upgrade our actions to the latest versions. Specifically, it looks like we need to update `actions/checkout` and `actions/cache` to `v3`, across _all_ of our workflows in the `.github/workflows` directory.

**Comment by fMurugi** [comment]
Hi I would like to work on this please assign me .Thank you.

**Comment by skriss** [comment]
@fMurugi just checking in to see if you are still working on this.

**Comment by fMurugi** [comment]
@skriss  yes i will be making a PR soon

**Comment by skriss** [comment]
Started a new issue with additional Actions that need to be upgraded: https://github.com/projectcontour/contour/issues/4814
