### ISSUE TITLE
add Gateway provisioner documentation

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4786]
We should add documentation that covers the Gateway provisioner and its functionality (i.e. what's exposed in the ContourDeployment CRD), in a style similar to https://projectcontour.io/docs/v1.22.1/config/fundamentals/ and the rest of the HTTPProxy documentation. Right now there's a guide that covers it but it's not versioned, not exhaustive, and not all that discoverable.

**Comment by skriss** [comment]
I'm working on this + other Gateway API documentation.

**Comment by davinkevin** [comment]
👏 and thank you, very good doc!
