### ISSUE TITLE
Update the Community Page on the Website

### ISSUE THREAD

**Issue by pnbrown** [projectcontour/contour#4787]
The [community page](https://projectcontour.io/community/) on the Contour site does not link to the [Google Group](https://groups.google.com/g/project-contour) that we are now using for the mailing list and still has the times for our Community Meetings which are currently paused. We need to update the links and copy.

**Comment by Anuran12** [comment]
Hi @pnbrown  i would like to work on this.. please assign this to me

**Comment by pnbrown** [comment]
Sure. Please let me know if you need any help with this one. It'd be great to get this changed over soon.

**Comment by pnbrown** [comment]
In the column on the far right, there's a part that talks about joining the mailing list that currently links to a sunsetting group. We want to replace that link with the Google Groups one.

Further below in that column, we want to remove the meeting information and say that Contour Community Meetings and Office Hours are currently paused.

**Comment by pnbrown** [comment]
Of course! Thanks for picking this up and helping out.

The relevant file is here:
https://github.com/projectcontour/contour/blob/main/site/content/community/_index.html

**Comment by Anuran12** [comment]
hey @pnbrown  
![image](https://user-images.githubusercontent.com/104062485/195491470-95e85c9e-74bf-499f-b384-d629b75aec83.png)

I have to change the both right ? for Australia time zones and Americas time zones

and replace of Every "Every first and third Tuesday at....." . I will write "Contour Community Meetings and Office Hours are currently paused."

**Comment by pnbrown** [comment]
That would be great. There's another reference in the leftmost column as well.

**Comment by Anuran12** [comment]
![image](https://user-images.githubusercontent.com/104062485/195492216-b58d84fc-0813-4700-bd26-964204308768.png)

this one ?

**Comment by pnbrown** [comment]
Yes. It may or may not be helpful to put some language there and remove the link at the top that goes to an old Office Hours document. I'll have to take another look.

**Comment by Anuran12** [comment]
![image](https://user-images.githubusercontent.com/104062485/195493776-10423e26-e26f-4303-ac49-e7bcd4132270.png)

looking good ?

**Comment by pnbrown** [comment]
I think that's a great start. Can we remove the link in the left column to the Contour Office Hours doc?

**Comment by Anuran12** [comment]
> I think that's a great start. Can we remove the link in the left column to the Contour Office Hours doc?

which one ?

**Comment by pnbrown** [comment]
The link in Join the Contour Office Hours

**Comment by Anuran12** [comment]
it's redirecting into the github's wiki section..

**Comment by Anuran12** [comment]
I will remove the link only right ?

**Comment by pnbrown** [comment]
Yes.

**Comment by Anuran12** [comment]
Ok done.. can I send the PR now ?

**Comment by Anuran12** [comment]
Hii... @pnbrown 

Thank you for helping me. 🥰

I want to contribute more in this repository. But i don't know much about backend. But i have very good proficiency in frontend.  So if your website needs and frontend work please let me know or please create the issue i will check. 

The current UI of the website is basic. So it will be great if you change something.... 

Thank you again 🥰
