### ISSUE TITLE
updates/deletes to unrelated Services trigger DAG rebuilds

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4793]
Spun out from https://github.com/projectcontour/contour/issues/4386, it looks like the same thing happens for Services since we are not calling `serviceTriggersRebuild` on removals (which happen for both updates and deletes).

**Comment by skriss** [comment]
Adding to 1.24 to be tackled along with the Secrets work.

**Comment by Vishal-Chdhry** [comment]
Hi! @skriss I would love to contribute but I can't understand what I have to do can you please guide me a little

**Comment by skriss** [comment]
Hey @Vishal-Chdhry! Here's some more detail, let me know if you have further questions.

https://github.com/projectcontour/contour/pull/4792 did something similar, but for Secrets -- it's a good template to follow.

When we insert a Service into the DAG cache, we call `kc.serviceTriggersRebuild` to see if the DAG needs to be rebuilt (https://github.com/projectcontour/contour/blob/main/internal/dag/cache.go#L112). However, when we update/delete a Service, we are not performing that same check (https://github.com/projectcontour/contour/blob/main/internal/dag/cache.go#L263-L267). We need to add that check to the remove logic.

We should also ensure that https://github.com/projectcontour/contour/blob/main/internal/dag/cache_test.go#L953 has test cases for both (a) deleting a Service that _is_ referenced by an HTTPProxy, which should trigger a rebuild; and (b) deleting a Service that is not referenced, which should not trigger a rebuild.

**Comment by Vishal-Chdhry** [comment]
\assign
