### ISSUE TITLE
[Doc] The "goboring-version" in "FIPS 140-2 in Contour" doc is outdated.

### ISSUE THREAD

**Issue by moeyui1** [projectcontour/contour#4794]
**On Page:** [FIPS 140-2 in Contour](https://projectcontour.io/guides/fips/)

The specific paragraphs are as follows: 

```
We can use the Google-provided Go implementation that has patches on top of standard Go to enable integrating BoringCrypto. This is available to us in the [goboring/golang](https://hub.docker.com/r/goboring/golang/) container image we can use as a build base. In addition, to ensure we can statically compile the contour binary when it is linked with the BoringCrypto C library, we must pass some additional arguments to the make container target.
To perform the Contour image build with BoringCrypto, change directories to where you have the Contour source code checked out and run the following (replacing <goboring-version-tag> with the appropriate version of Go and BoringCrypto, see [here](https://go.googlesource.com/go/+/dev.boringcrypto/misc/boring/README.md#version-strings) for version specifics):
```

However, when I checked [the version list of goboring/golang on Docker hub](https://hub.docker.com/r/goboring/golang/tags), the latest version is [1.16.7b7](https://hub.docker.com/layers/goboring/golang/1.16.7b7/images/sha256-ad86974b2b260afa11293748b6c1e0fe0edbeb5874f8850d108cdcdf0a5795c1?context=explore). The Go 1.17+ versions are not there according to [the image overview](https://go.googlesource.com/go/+/dev.boringcrypto/README.boringcrypto.md).

```
This branch is no more. GOEXPERIMENT=boringcrypto on the standard branch does the job now.
```

So there is no need to use `goboring/golang` for BoringCrypto enable, instead, we can use the standard `golang` image with `GOEXPERIMENT=boringcrypto`. I've tested the output container image in this way and it seems to work well. Test according to:

```
To be fully sure the produced contour binary has been compiled with BoringCrypto you must remove the -s flag from the base Contour Makefile to stop stripping symbols and run through the build process above. Then you will be able to inspect the contour binary with go tool nm to check for symbols containing the string _Cfunc__goboringcrypto_.
```

So maybe the doc needs some updates, I will be glad to submit a PR if it is convenient.

**Comment by sunjayBhatia** [comment]
thanks for the research and work @moeyui1 a PR would be very welcome!

**Comment by sunjayBhatia** [comment]
if you are able to work on this I can assign this issue to you for tracking 👍🏽

**Comment by moeyui1** [comment]
> if you are able to work on this I can assign this issue to you for tracking 👍🏽

Sure. I will create a PR later.
