### ISSUE TITLE
Handle Envoy 1.24.0 deprecations

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#4802]
See: https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.24/v1.24.0#deprecated

Assuming 1.24.0 will be picked up in Contour 1.23.0, we should make these changes in Contour 1.24.0 (to ensure a smooth upgrade), since they seem to include deprecations paired with additions to the now-preferred fields

**Comment by skriss** [comment]
Should update the go-control-plane module dep as part of this.
