### ISSUE TITLE
Why Envoy container doesn't have a liveliness probe by default? 

### ISSUE THREAD

**Issue by YuxinZhou** [projectcontour/contour#4812]
**What question do you have?:**

I notice that the Envoy container doesn't have a liveliness probe by default:  https://projectcontour.io/quickstart/contour.yaml. I am curious if this is by intention.  Any concerns if I add that to our environment? 

Asking because there is an occurrence when the envoy container is stuck and cannot recover by itself.  I need to manually kill the pod so that it can recover.  

```
pod/envoy-bx8sn               2/2     Running        0              16h
pod/envoy-gprq2               2/2     Running        0              15h
pod/envoy-jlsm5               2/2     Running        0              15h
pod/envoy-vd4nh               2/2     Running        0              17h
pod/envoy-xzthg               1/2     Running        1              18h

Type     Reason     Age                     From     Message
----     ------     ----                    ----     -------
Warning  Unhealthy  2m28s (x8149 over 27h)  kubelet  readiness probe failed for container envoy: Service Unavailable
```

**Comment by skriss** [comment]
@xuanqu we're looking into some related issues in #4851, for which adding a liveness probe to Envoy is likely part of a solution. I'd track that issue for further updates.

**Comment by skriss** [comment]
I'm going to close this question out, and use #4851 to track the work to resolve the issues around this.
