### ISSUE TITLE
Gateway API: support ResponseHeaderModifier filter (extended/experimental)

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4819]
https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteFilter

Should be fairly straight-forward since we already have support for this via HTTPProxy, and it's very similar to the RequestHeaderModifier logic.

**Comment by sunjayBhatia** [comment]
proposal to move this to 1.24.0 or another upcoming release, so Gateway API can get feedback on it + the conformance tests

**Comment by skriss** [comment]
👍 from me, adding to the milestone.

**Comment by sunjayBhatia** [comment]
heres a spike I did just now with most implementation done (but no testing): https://github.com/sunjayBhatia/contour/tree/gwapi-latest-with-resp-header-modification

can be used as a basis for whoever picks this up

was done as part of fixing up the conformance tests in https://github.com/kubernetes-sigs/gateway-api/issues/1473

**Comment by sunjayBhatia** [comment]
chatted on slack and I will go ahead and finish this one out, since its mostly done
