### ISSUE TITLE
HttpProxy status is NotReconciled but Routes are active and working

### ISSUE THREAD

**Issue by sunnyverma88** [projectcontour/contour#4825]
Log :  level=info msg="performing delayed update" context=contourEventHandler last_update=20.397055089s outstanding=1. Based on previous closed issue , I tried updating the ingress class to kubernetes.io/ingress.class but that didnt help.

**Comment by sunnyverma88** [comment]
I followed the examples to deploy contour and envoy(as deployment) but I am running multiple contours in the same cluster and namespace to handle different routing use cases.  Last 12 hour logs only have these debug msg

`time="2022-10-27T13:42:03Z" level=debug msg="*v1.Service skipping update, only status has changed" context=contourEventHandler op=update
time="2022-10-27T12:59:41Z" level=debug msg="*v1.HTTPProxy skipping update, only status has changed" context=contourEventHandler op=update
`

I went ahead and delete the HtppProxy and create a new one. Below logs has the details around that.
[contour-logs.txt](https://github.com/projectcontour/contour/files/9880832/contour-logs.txt)

**Comment by skriss** [comment]
Ah, ok. There are a number of changes that need to be made to the example manifests to support running multiple instances, particularly within a single namespace, which unfortunately we don't have documented yet (ref. #855).

It sounds like, at a minimum, you may be running into an issue where both instances are using the same leader election lease. You need to provide the `--leader-election-resource-name` flag to the `contour serve` command (https://github.com/projectcontour/contour/blob/main/examples/contour/03-contour.yaml#L38-L46), and use a different name for each instance.

There are a number of other things that need to be altered as well to avoid conflicts between the instances - pod labels/selectors for the Deployments, the `--xds-address` flag to the `bootstrap` command on the Envoy deployment specifying the appropriate Contour service name, and a number of other things that I'd have to go dig up. Our [Gateway provisioner](https://projectcontour.io/getting-started/#option-3-contour-gateway-provisioner-alpha) does support this use case, if that's an option for provisioning for you (you can still use HTTPProxies with Contours provisioned that way).

**Comment by sunnyverma88** [comment]
I am not using different names of the deployment but added a scope variable- app: contour ;scope: {{ $ingress.type }}. and specified the same in the service selector. Envoy is pointing to different ingresses. --xds-address=contour-{{ $ingress.type }}.  Does providing the scope name to the --leader-election-resource-name flag works ?? or I need to change my approach and change the name of the deployment.

**Comment by sunnyverma88** [comment]
It works !! I now see a LeaderElection event.
