### ISSUE TITLE
TLSRoute service references not considered in serviceTriggersRebuild

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4831]
in internal/dag/cache.go, the serviceTriggersRebuild function determines if a Service add/update/delete should trigger a DAG rebuild based on whether that Service is referenced by any relevant resource (Ingress, HTTPProxy, HTTPRoute). However, this function does not currently look at TLSRoutes for references, which it should in addition to the other resource types it is currently looking at.

Positive and negative test cases should be added to https://github.com/projectcontour/contour/blob/main/internal/dag/cache_test.go (TestKubernetesCacheInsert and TestKubernetesCacheRemove).

**Comment by sanjeev98kumar** [comment]
Hii @skriss 
Could you please assign this issue to me? I am looking for my first PR.
Also wanted to know how much time will it require for me to set up contour on my local?
