### ISSUE TITLE
ExtensionServices are updated continuously by contour

### ISSUE THREAD

**Issue by LeoHexspoor** [projectcontour/contour#4838]
**What steps did you take and what happened:**
We deployed a couple of ExtensionServices for ratelimiting and authentication. After that we noticed the extension services were in an update loop where only the following fields are constantly being updated:
- metadata.resourceVersion
- status.conditions[0].lastTransitionTime

In a cluster with just 3 extensionservices we have 22ops on extension services while we are not actively modifying them. The kubernetes api-server is reporting millions of PUT requests with the following labels:
component="apiserver",group="[projectcontour.io](http://projectcontour.io/)",resource="extensionservices",scope="resource",subresource="status",verb="PUT",version="v1alpha1"

**What did you expect to happen:**
No updates to the extension service objects once they are healthy.

**Anything else you would like to add:**
Initial feedback on Slack was that this is a gap in the extensionservice logic where the transition time is not ignored when checking the update status.

**Environment:**

- Contour version: 1.22
- Kubernetes version: 1.23
- Cloud provider or hardware configuration: GKE

**Comment by sunjayBhatia** [comment]
See: https://github.com/projectcontour/contour/blob/2ba1559ee5746c8616f6ec37f0905411f4bb03e4/internal/k8s/helpers.go#L28

There is no case for ignoring transition time for ExtensionService

**Comment by sunjayBhatia** [comment]
Also see: https://github.com/projectcontour/contour/blob/2ba1559ee5746c8616f6ec37f0905411f4bb03e4/internal/contour/handler.go#L190-L198

updates do not ignore status changes on ExtensionService

**Comment by Vishal-Chdhry** [comment]
@sunjayBhatia Hi! may I pick this up!

**Comment by skriss** [comment]
@Vishal-Chdhry assigned!
