### ISSUE TITLE
Envoy shutdown: Investigate using /drain_listeners admin endpoint

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#4852]
**Please describe the problem you have**
Currently when shutting down Envoy, we use the `/healthcheck/fail` endpoint to cause healthchecks to fail and Envoy to drain connections.

We can investigate using the `/drain_listeners` admin endpoint to drain connections: https://www.envoyproxy.io/docs/envoy/latest/operations/admin#post--drain_listeners.
This is configurable via CLI options: https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-drain-time-s

**Comment by skriss** [comment]
Dupe of https://github.com/projectcontour/contour/issues/2705, but can close the old one out.

**Comment by sunjayBhatia** [comment]
So this endpoint works in conjunction with the `--drain-time-s` flag explicitly, after the specified drain time (defaulted to 600s), the admin listener we use to expose the `/ready` will no longer be listening:

The Envoy pod will no longer be ready due to:
```
Readiness probe failed: Get "http://10.244.2.250:8002/ready": dial tcp 10.244.2.250:8002: connect: connection refused
```

And this is not recoverable with `/healthcheck/ok`, unlike `/healthcheck/fail`

If you use the admin socket listener, that actually still reports state `LIVE` in `/ready/ and `/server_info` (at least in the Envoy version I am using atm, 1.23.1)

**Comment by sunjayBhatia** [comment]
Using `/drain_listeners` doesn't seem like it will get us what we want on its own, the drain time delays the removal of the pod endpoint from the Envoy Service and new connections are still accepted in the "drain" period. We would still need to do the same connection counting to know when it is safe to fully shut down.

See also: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/draining#arch-overview-draining

**Comment by sunjayBhatia** [comment]
Probably not worth making any changes in this space, *maybe* could use `/drain_listeners` at the same time as `/healthcheck/fail`, but that seems redundant since the HTTP Connection Manager should be telling existing connections to close already (and would need to coordinate the correct drain time configuration)

**Comment by sunjayBhatia** [comment]
closing with `wontfix` to signify we likely won't make any changes at the moment
