### ISSUE TITLE
welcome new contributors workflow is failing on PRs

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4895]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Had a new contributor submit a PR.
Did not get the new contributor message.
Saw an error in the workflow (https://github.com/projectcontour/contour/actions/runs/3601857784/jobs/6069993984#step:2:43)

**What did you expect to happen:**
The PR should get the new contributor comment added.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
cc @pnbrown 

**Environment:**

- Contour version:
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by pnbrown** [comment]
Thanks for filing this. I need to bring in the updates discussed in https://github.com/projectcontour/contour/pull/4855 and it should resolve. Will work on it today.
