### ISSUE TITLE
Question: Returning custom gRPC header or status in rate limiting

### ISSUE THREAD

**Issue by josephschorr** [projectcontour/contour#4901]
**What question do you have?:**

I'm curious to know if there is a way to set a custom gRPC status code and/or header to be returned if a rate limit is exceeded via the contour rate limiting system, rather than simply returning 429. The 429 error gets mapped by gRPC into an `UNAVAILABLE` error without much user-visible context, and we'd like to provide a nicer error message.

**Comment by sunjayBhatia** [comment]
Have you tried having your RLS return specialized response headers using this field in the RLS response? https://github.com/envoyproxy/data-plane-api/blob/c65cd6eeca57c6e56f0ee044ca33b8b275e480ec/envoy/service/ratelimit/v3/rls.proto#L196

**Comment by sunjayBhatia** [comment]
there is also this field: envoy-v3-api-field-extensions-filters-http-ratelimit-v3-ratelimit-rate-limited-as-resource-exhausted

which might be good for us to turn on generally

**Comment by sunjayBhatia** [comment]
updated the link above ^

**Comment by vroldanbet** [comment]
@sunjayBhatia yeah that's the flag we were looking into, but Contour does not expose it. We are totally fine if you guys decide to turn it on by default, but that may be an unexpected breaking change to clients already expecting `UNAVAILABLE`.

**Comment by vroldanbet** [comment]
I've opened https://github.com/projectcontour/contour/pull/4971 to implement this
