### ISSUE TITLE
Root proxy is invalid with DuplicateMatchConditions error when there are multiple inclusions with header match conditions

### ISSUE THREAD

**Issue by ajayslele** [projectcontour/contour#4907]
**What steps did you take and what happened:**
Root proxy gets into invalid state with DuplicateMatchConditions error when there are multiple inclusions with header match conditions. The header matches have multiple conditions, and few of these conditions are same across includes. But as all match conditions in include are ANDed, all the match conditions under include should be considered for detecting duplicate match conditions, and not just individual ones. Refer below for an example.

**What did you expect to happen:**
Since match conditions under include are ANDed, code should check for uniqueness of the ANDed condition and across all includes not just the consecutive one. The logic used here to detect duplicates seems incorrect: https://github.com/projectcontour/contour/blob/main/internal/dag/httpproxy_processor.go#L1383

**Anything else you would like to add:**
NOK
====
Root HTTPProxy with below spec goes to invalid state with DuplicateMatchConditions error.

spec:
  includes:
  - conditions:
    - prefix: /offer1
    name: child1
    namespace: offer1
  - conditions:
    - header:
        exact: xxx
        name: x-header
    - header:
        exact: yyy
        name: y-header
    name: child1
    namespace: offer1
  - conditions:
    - header:
        exact: xxx
        name: x-header
    - header:
        exact: zzz
        name: z-header
    name: child1
    namespace: offer1

Status:
  Conditions:
    Errors:
      Message:             duplicate conditions defined on an include
      Reason:              DuplicateMatchConditions
      Status:              True
      Type:                IncludeError
    Last Transition Time:  2022-12-07T19:14:58Z
    Message:               At least one error present, see Errors for details
    Observed Generation:   1
    Reason:                ErrorPresent
    Status:                False
    Type:                  Valid
  Current Status:          invalid
  Description:             At least one error present, see Errors for details

OK
====
Root HTTPProxy with similar spec with rearranged includes (so those with header matches are not next to each other) is in valid state.

spec:
  includes:
  - conditions:
    - header:
        exact: xxx
        name: x-header
    - header:
        exact: yyy
        name: y-header
    name: child1
    namespace: offer1
  - conditions:
    - prefix: /offer1
    name: child1
    namespace: offer1
  - conditions:
    - header:
        exact: xxx
        name: x-header
    - header:
        exact: zzz
        name: z-header
    name: child1
    namespace: offer1

Status:
  Conditions:
    Last Transition Time:  2022-12-07T19:25:10Z
    Message:               Valid HTTPProxy
    Observed Generation:   1
    Reason:                Valid
    Status:                True
    Type:                  Valid
  Current Status:          valid
  Description:             Valid HTTPProxy

**Environment:**

- Contour version: 1.23
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by sunjayBhatia** [comment]
thanks for the repot @ajayslele I was able to reproduce this 👍🏽

**Comment by sunjayBhatia** [comment]
this looks wrong: https://github.com/projectcontour/contour/blob/5d7fb0710f0a32fa15e2d348d0dbdd74dad1b86b/internal/dag/httpproxy_processor.go#L1383-L1397
