### ISSUE TITLE
Unable to specify an ip for contour

### ISSUE THREAD

**Issue by thatvmwareguy** [projectcontour/contour#4916]
When installing contour, there is no way to specify an IP address. This causes issues when having to reinstall contour and the same IP is not guaranteed. As this means having to update dns with the new ip address that was assigned.

**Comment by thatvmwareguy** [comment]
Envoy data plane

**Comment by sunjayBhatia** [comment]
If your cloud provider supports it, you should be able to set the `spec.loadBalancerIP` field on the Envoy Service

See: https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer

```
Some cloud providers allow you to specify the loadBalancerIP. In those cases, the load-balancer is created with the user-specified loadBalancerIP. If the loadBalancerIP field is not specified, the loadBalancer is set up with an ephemeral IP address. If you specify a loadBalancerIP but your cloud provider does not support the feature, the loadbalancerIP field that you set is ignored.
```

**Comment by thatvmwareguy** [comment]
this doesnt seem to work in tkgs using contour/envoy, as it will still grab a dynamic ip, but this setting does work if you use nginx ingress controller.
