### ISSUE TITLE
Access Logs: Equivalent to NGINX $remote_user

### ISSUE THREAD

**Issue by BerGer23** [projectcontour/contour#4934]
We are in the process of switching over from ingress-nginx.
Configuring the access logs the Envoys emit, I am trying to find a replacement for NGINX's `$remote_user`  - detailed [here](https://nginx.org/en/docs/http/ngx_http_core_module.html):
_$remote_user
user name supplied with the Basic authentication_

The only way to doing this with Contour I found so far is to include deployment of an authz-service that parses the header, extracts the username and returns a response that includes adding this custom header & value.

Is there an easier way to enable this behaviour for Contour?

Thanks in advance folks!

**Comment by sunjayBhatia** [comment]
Unfortunately, this isn't directly available from Envoy's access log operators

if you know the length of the username you could possibly use something like `%REQ(Authorization):Z%` where `Z` is the length, though that will still be base 64 encoded

**Comment by BerGer23** [comment]
Alright, thank you for the input @sunjayBhatia
