### ISSUE TITLE
Access logs: How to create field for query string?

### ISSUE THREAD

**Issue by BerGer23** [projectcontour/contour#4935]
We are in the process of switching over from ingress-nginx.
Configuring the access logs the Envoys emit, I am trying to find a way to make the query string of a requests have its own separate field in the created JSON access log entry.
I know how to configure logging the path without the query string from the documentation's last paragraph - [REQ_WITHOUT_QUERY](https://projectcontour.io/docs/v1.22.1/config/access-logging/). 

Now I just need to know how to log _just_ the query string.

I read the [Envoy documentation on access logging](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage), but could not find enlightenment yet.

Thanks in advance folks!

**Comment by tsaarni** [comment]
Hi @BerGer23, unfortunately it is not possible to split out query string into separate field.

**Comment by sunjayBhatia** [comment]
I was going to say you might be able to do some string formatting magic, but the `%REQ(X?Y):Z%` operator only allows truncation (with the `Z` parameter), so seems unlikely that will help to isolate the query string

**Comment by BerGer23** [comment]
Thank you both for the input!
