### ISSUE TITLE
support getting LoadBalancerStatus from an Ingress (e.g. AWS ALB) or Gateway

### ISSUE THREAD

**Issue by kahirokunn** [projectcontour/contour#4952]
I am using Ingress + NodePortS without LoadBalancerService.
Therefore, it is useful to have envoy-ingress-name and envoy-ingress-namespace.
Similarly, it may be useful to have envoy-gateway-name and envoy-gateway-namespace as well, since the Gateway API is expected to become more active in the future.

related Issues: https://github.com/projectcontour/contour/issues/4951

**Comment by sunjayBhatia** [comment]
the `envoy-service-name/namespace` flags are used for identifying which LoadBalancer Service External IP to watch in order to populate the  LoadBalancer IP on Ingress/HTTPProxy resources. I'm not sure how that fits in with the proposed flags you mention here?

**Comment by kahirokunn** [comment]
> LoadBalancer Service External IP to watch in order to populate the LoadBalancer IP on Ingress/HTTPProxy resources.

@sunjayBhatia I also think that flags will be needed to identify which external IP of the Ingress (eg. aws-load-balancer-controller) to monitor.

**Comment by sunjayBhatia** [comment]
I'm not sure what you mean by that, can you clarify a bit? How is your ALB set up to interact with Contour and what information on which resources are you missing?

**Comment by kahirokunn** [comment]
@sunjayBhatia Sorry for the lack of explanation.

1. LoadBalancer Service -> envoy is the default configuration
2. Ingress (ingressClass alb) -> NodePort Service -> envoy is the configuration I use

The reason I use ALB (Ingress + NodePort Service) instead of NLB (LoadBalancer Service) is to use AWS WAF.
https://aws.amazon.com/waf/?nc1=h_ls

Many companies have places where they would like to use AWS WAF.
However, in that case, contour cannot configure the HTTPProxy status.loadbalancer.
If status.loadbalancer is not set, External DNS, etc. will not work, and it will be difficult to find out to which ingress (ALB) it is connected.

**Comment by sunjayBhatia** [comment]
Thanks for spelling that out, makes sense

We have not put too much work into Contour's UX when using an ALB setup so we'll have to think a little about how we want to have this work

**Comment by kahirokunn** [comment]
I see.
Contour is the best product out there, so I'd be very happy if you'd consider the ALB experience as well!
Thx!!!

**Comment by kahirokunn** [comment]
@sunjayBhatia @skriss 
I want to make contour easy to use in ALB as well.
If I write golang code to add envoy-ingress-name and envoy-ingress-namespace and create a PR, can you merge it?
The intent of my question is to make sure that if I create this feature and it does not get merged, it will be a wasted effort.

**Comment by kahirokunn** [comment]
keep

**Comment by skriss** [comment]
xref https://github.com/projectcontour/contour/issues/2539, has some additional use cases around sourcing the LoadBalancerStatus

**Comment by kahirokunn** [comment]
keep

**Comment by kahirokunn** [comment]
Keep

**Comment by kahirokunn** [comment]
Keep

**Comment by kahirokunn** [comment]
keep

**Comment by skriss** [comment]
@hligit is working on this

**Comment by kahirokunn** [comment]
keep
