### ISSUE TITLE
how to launch the subcommand "contour serve"

### ISSUE THREAD

**Issue by mrfranc** [projectcontour/contour#4965]
**On Page:** [](https://projectcontour.io/docs/v1.23.2/troubleshooting/contour-debug-log/)

I installed ingress from contour two hours ago. something went wrong and I want to debug. So I spent 2 hours with the google and contour website to clarify how to launch the command contour serve.
and I was unsuccessful. 
Sorry

**Comment by tsaarni** [comment]
Did you already add `--debug`? [This page](https://projectcontour.io/docs/main/configuration/#serve-flags) has the full list of command line flags and a generic example deployment manifest [here](https://github.com/projectcontour/contour/blob/cde4525f4e24508a002f4e7c9476f3b4d4077c0d/examples/contour/03-contour.yaml#L38-L47) shows how `contour serve` is often launched.

**Comment by mrfranc** [comment]
> Did you already add `--debug`? [This page](https://projectcontour.io/docs/main/configuration/#serve-flags) has the full list of command line flags and a generic example deployment manifest [here](https://github.com/projectcontour/contour/blob/cde4525f4e24508a002f4e7c9476f3b4d4077c0d/examples/contour/03-contour.yaml#L38-L47) shows how `contour serve` is often launched.

Thank you for your answer. I'm sorry. Maybe I'm novice in k8s but I saw all these pages and I still can't understand how to launch contour serve.
When I'm doing it from command prompt in Windows I see "command not found". When I try to do it with "kubectl contour serv" I also see "unknown command". I've read page with options. It is nice that how I can use the option if I don't know how to launch program :)

**Comment by mrfranc** [comment]
could you please give me one simple example how to launch 
contour server --debug
which environment should I use for that and how I have to prepare it?
Thanks

**Comment by tsaarni** [comment]
Contour serve is the ingress controller application itself, executing inside the cluster. It is not a separate command for troubleshoot the installation. You would not run it on your own machine typically. To troubleshoot the installation, you can either edit the deployment manifest by adding the `--debug` flag and then reinstall Contour again with the debug enabled. Assuming you used the example manifests to install Contour, you could alternatively use `kubectl -n projectcontour edit deployment/contour` to edit the existing `Deployment` resource, without reinstalling. See [Kubernetes docs](https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/#kubectl-edit) for more information.  After that, you can read the logs by running `kubectl -n projectcontour logs deployment/contour`.
