### ISSUE TITLE
Gateway provisioner: better error handling when ensuring resources

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4975]
Right now, if the gateway provisioner gets any errors ensuring resources, the error is just logged in the provisioner logs: https://github.com/projectcontour/contour/blob/main/internal/provisioner/controller/gateway.go#L355-L357

This is not very user-visible. We should likely be setting a condition on the Gateway, surfacing the error.

This came up while reviewing #4973, where if the port numbers specified on the Gateway aren't in the allowed NodePort range, the error is logged but not surfaced on the Gateway itself.

**Comment by sunjayBhatia** [comment]
I guess this would apply to the `Programmed` condition on the Gateway itself but would be super useful to be able to figure out which Listener specifically is invalid so we could set the condition on that as well/instead

we could parse the errors we get back from the api server to do so, etc. (have to think about that more)

**Comment by sunjayBhatia** [comment]
the full log line/error string that comes back:

```
time="2023-01-12T22:55:30Z" level=error msg="Reconciler error" caller="logr.go:279" context=kubernetes controller=gateway-controller error="failed to ensure resources for gateway: failed to ensure envoy service for gateway projectcontour/contour: failed to update resource projectcontour/envoy-contour: failed to update service projectcontour/envoy-contour: Service \"envoy-contour\" is invalid: spec.ports[0].nodePort: Invalid value: 81: provided port is not in the valid range. The range of valid ports is 30000-32767" logger=contour-gateway-provisioner name=contour namespace=projectcontour object="{\"name\":\"contour\",\"namespace\":\"projectcontour\"}" reconcileID="\"59da7e44-1edb-4a7f-b664-1c62bcb0986b\""
```

**Comment by sunjayBhatia** [comment]
at the moment the contour controller and not the provisioner sets the `Programmed` condition on the Gateway and Listeners, but the actual "act of programming" the Gateway is a split responsibility

**Comment by sunjayBhatia** [comment]
we could possible change to a model where the provisioner sets the top-level `Programmed` condition to True/False based on whether the infrastructure is properly created, and then the controller actually programming routes etc. sets Listener status only?
