### ISSUE TITLE
upgrade tests: Investigate flakiness (NC Upstream cluster not found response flag)

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#4991]
Our upgrade tests have been flaky recently, reporting a success rate for requests during an upgrade < 90%

After adding a little more logging to see the source of the failures, we see:
- a couple client timeouts
- 503s with the NC (Upstream cluster not found) Envoy response flag

I haven't been able to reproduce this locally or on my fork github actions as of yet which is a bit odd

Given the NC response flag that is set on responses during the Contour deployment update, it seems we may have a new Contour instance that sent over Routes to Envoy but possible removed/not sent over the correct Clusters yet which isn't great, possibly related to: https://github.com/projectcontour/contour/issues/1280

Examples:
- https://github.com/projectcontour/contour/actions/runs/3951882181/jobs/6766362516
- https://github.com/projectcontour/contour/actions/runs/3900527771/jobs/6661393129
- https://github.com/projectcontour/contour/actions/runs/3857581048/jobs/6575211629

**Comment by skriss** [comment]
Thanks for looking into this @sunjayBhatia. I wonder how hard it would be to eagerly fill the DAG cache with all the resources before starting processing/serving. It doesn't seem too difficult on the surface but I'm sure there are some complications. That way, the first time the DAG build ran, an initial snapshot of all the resources would already be there.

**Comment by sunjayBhatia** [comment]
yeah i've gotta dust off what i was trying around ordered startup of our various components, right now the only guard to prevent the xDS server from starting up early is here: https://github.com/projectcontour/contour/blob/ae025b7081cb6b55df503f8a75a5010973b6c651/cmd/contour/serve.go#L652

**Comment by skriss** [comment]
This continues to crop up, adding to the 1.26 milestone to see if we can figure out what's going on here

**Comment by sunjayBhatia** [comment]
among other things related to https://github.com/projectcontour/contour/issues/2134, looking into opting into using ADS to see if it helps here, I would expect it does, however making ADS the default will be a major/breaking change since it requires a bootstrap change coupled with switching to the go-control-plane xDS server with ADS enabled and generating ADS snapshots

**Comment by sunjayBhatia** [comment]
So far just local testing with ADS has been pretty successful

Currently working on making ADS an opt-in configuration, it is a pretty ugly change to do passing config from the serve cli flags straight-up as it changes every resource that references another via a ConfigSource (and all the internal Listener/ClusterCache structs etc.), so trying to consolidate/refactor first

**Comment by skriss** [comment]
@sunjayBhatia I think the tests themselves have stabilized since https://github.com/projectcontour/contour/commit/0b4a8b829d018519f55029c5318371358edb0914, so I'm inclined to close this flake issue and track any other ADS/go-control-plane work in a different issue. Feel free to reopen if you disagree!
