### ISSUE TITLE
add metrics for DAG cache contents

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5005]
It'd be nice to have ~~counter~~ gauge metrics indicating how many items are in the DAG cache (by kind at least). This would be helpful for ensuring we aren't holding onto resources we shouldn't be.

Suggested structure would be a single GaugeVec metric, named `contour_dag_cache_object_count`, with at least one label, `kind`, and potentially another for `namespace`. This metric should be set each time an object is added to or removed from the DAG cache, based on the current length of the relevant map.

**Comment by theVJagrawal** [comment]
hey @skriss I want to work on this issue so can you please elaborate it more

**Comment by skriss** [comment]
Contour's metrics are defined here: https://github.com/projectcontour/contour/blob/main/internal/metrics/metrics.go
DAG cache:
- instantiation (https://github.com/projectcontour/contour/blob/main/cmd/contour/serve.go#L952) -- would need to take in a `*metrics.Metrics`
- object addition (https://github.com/projectcontour/contour/blob/main/internal/dag/cache.go#L99) -- need to set the appropriate metrics by measuring the size of the relevant map
- object removal (https://github.com/projectcontour/contour/blob/main/internal/dag/cache.go#L242) -- need to set the appropriate metrics by measuring the size of the relevant map

**Comment by izturn** [comment]
@skriss  i'd like to implement it
