### ISSUE TITLE
Kubernetes manifest is invalid (under Kubernetes 1.26.1)

### ISSUE THREAD

**Issue by sanmai-NL** [projectcontour/contour#5030]
**What steps did you take and what happened:**
```console
$ kubectl apply -f https://projectcontour.io/quickstart/contour.yaml

...
The Deployment "contour" is invalid: 
* spec.template.spec.volumes[1].configMap.defaultMode: Invalid value: 644: must be a number between 0 and 0777 (octal), both inclusive
* spec.template.spec.containers[0].volumeMounts[1].name: Not found: "contour-config"
```

**What did you expect to happen:**

Succesful deployment.

**Anything else you would like to add:**

 I'm not using Kind but I find it hard to relate this fault to that.

**Environment:**

- Contour version: latest as of today, https://projectcontour.io/getting-started/. No version listed.
- Kubernetes version: (use `kubectl version`):
  ```
  WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
  Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:24Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/amd64"}
  Kustomize Version: v4.5.7
  Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1+k3s1", GitCommit:"f10af367c3c96863c081ada4018e94e085c9404d", GitTreeState:"clean", BuildDate:"2023-01-26T00:59:34Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Kubernetes installer & version: Rancher Desktop 1.7.0
- Cloud provider or hardware configuration: Local MacOS Rancher Desktop
- OS (e.g. from `/etc/os-release`): MacOS 13.2

**Comment by skriss** [comment]
Hey @sanmai-NL, I just tried this on a 1.26.0 kind cluster with the same kubectl version as you and it worked fine. I'll see if I can repro with Rancher Desktop / k3s 1.26.1.

From the error it looks like the leading `0` in https://github.com/projectcontour/contour/blob/v1.23.2/examples/render/contour.yaml#L6967 is being dropped, not sure off the top of my head what would be causing that.

**Comment by sanmai-NL** [comment]
This could be my fault due to pretty printing the YAML. Seems like a strange error indeed (to malform the octal).

**Comment by sanmai-NL** [comment]
Please save your time and I'll check for my own error. I undid the formatting to reproduce but apparently not completely.

**Comment by sanmai-NL** [comment]
After redownloading `contour.yaml`, it works without error.

Interestingly, the Kubernetes API docs claim that 644 should have worked as well: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#configmapvolumesource-v1-core.
