### ISSUE TITLE
local.projectcontour.io misses an AAAA DNS Resource Record

### ISSUE THREAD

**Issue by sanmai-NL** [projectcontour/contour#5039]
local.projectcontour.io has an A RR for IPv4, with value `127.0.0.1`. For IPv6, however, it misses an AAAA RR with value `::1`.

**Comment by sanmai-NL** [comment]
Fresh.

**Comment by skriss** [comment]
I'm looking into this

**Comment by sanmai-NL** [comment]
Fresh

**Comment by skriss** [comment]
Assigning @pnbrown who was tracking this down

**Comment by pnbrown** [comment]
This may be resolved now thanks to @jonasrosland and the CNCF Service for the help over the last couple months. Please let us know and we can close this.

**Comment by sanmai-NL** [comment]
You can check using `dig` or `drill` at your leisure.

**Comment by skriss** [comment]
Closing out, thanks all!

**Comment by developer-guy** [comment]
Hello @skriss! I'm still cannot see the records that cause a problem while accessing the services:

```bash
dig local.projectcontour.io AAAA local.projectcontour.io A +short # returns empty result
```

**Comment by developer-guy** [comment]
It worked for me too as well thank you 🙏
