### ISSUE TITLE
remove labels from routes in internal/dag/status_test.go

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5075]
Many of the HTTPRoutes/TLSRoutes used in internal/dag/status_test.go have labels applied to them, e.g. https://github.com/projectcontour/contour/blob/main/internal/dag/status_test.go#L4224-L4226.

These used to be required with an old version of Gateway API, where attachment to Gateways was driven by labels. However, they're no longer necessary and are just noise in the test data.

We should remove all of these labels from the HTTPRoutes/TLSRoutes in this test file.

**Comment by Hussain0520** [comment]
Hey I want to work on this issue

**Comment by sunjayBhatia** [comment]
thanks for your interest @Hussain0520 let us know if you need any pointers 👍🏽

**Comment by Hussain0520** [comment]
@sunjayBhatia Thanks!

**Comment by Hussain0520** [comment]
Hey @sunjayBhatia, The lines mentioned for the issue are just brackets so can you just point me to line where mentioned labels are present. Thanks!

**Comment by sunjayBhatia** [comment]
looks like line numbers changed, heres a permalink example: https://github.com/projectcontour/contour/blob/3cefa518d6f4b0e3840e59b2084e7eb83cc13ce6/internal/dag/status_test.go#L4766-L4768

**Comment by Hussain0520** [comment]
Thanks! I'll remove all labels anything else you need to do?

**Comment by sunjayBhatia** [comment]
no that should be it for this issue

**Comment by Hussain0520** [comment]
Hey @sunjayBhatia I have made the changes and raised the PR. If you have any similar issues which I can contribute to, I'll be open to contribution.
