### ISSUE TITLE
Test TestConditions_ContainsQueryParameter_HTTProxy fails occasionally

### ISSUE THREAD

**Issue by tsaarni** [projectcontour/contour#5079]
Following unit test seems to fail occasionally: [TestConditions_ContainsQueryParameter_HTTProxy](
https://github.com/projectcontour/contour/blob/2287c8e4dbea7ded3086e0fb300714cc482f0287/internal/featuretests/v3/queryparametercondition_test.go#L30). The test was introduced in #5036.

It fails rarely but if running in loop, it will eventually fail

```console
$ go test -count 100 -tags "oidc gcp osusergo netgo" -mod=readonly github.com/projectcontour/contour/internal/featuretests/...
```

<details><summary>See the error message here.</summary>

<pre>
    queryparametercondition_test.go:453:   []*anypb.Any{
                Inverse(protocmp.Transform, protocmp.Message{
                        "@type":    s"google.protobuf.Any",
                        "type_url": string("type.googleapis.com/envoy.config.route.v3.RouteConfiguration"),
                        "value": protocmp.Message{
                                "@type":                  s"envoy.config.route.v3.RouteConfiguration",
                                "name":                   string("ingress_http"),
                                "request_headers_to_add": []protocmp.Message{{"@type": s"envoy.config.core.v3.HeaderValueOption", "header": protocmp.Message{"@type": s"envoy.config.core.v3.HeaderValue", "key": string("x-request-start"), "value": string("t=%START_TIME(%s.%3f)%")}}},
                                "virtual_hosts": []protocmp.Message{
                                        {
                                                "@type":   s"envoy.config.route.v3.VirtualHost",
                                                "domains": []string{"hello.world"},
                                                "name":    string("hello.world"),
                                                "routes": []protocmp.Message{
                                                        {
                                                                "@type": s"envoy.config.route.v3.Route",
                                                                "match": protocmp.Message{
                                                                        "@type":  s"envoy.config.route.v3.RouteMatch",
                                                                        "prefix": string("/"),
                                                                        "query_parameters": []protocmp.Message{
                                                                                {
                                                                                        "@type": s"envoy.config.route.v3.QueryParameterMatcher",
                                                                                        "name":  string("query-param"),
                                                                                        "string_match": protocmp.Message{
                                                                                                "@type":    s"envoy.type.matcher.v3.StringMatcher",
        -                                                                                       "contains": string("abc"),
        +                                                                                       "contains": string("def"),
                                                                                        },
                                                                                },
                                                                        },
                                                                },
                                                                "route": protocmp.Message{
                                                                        "@type":   s"envoy.config.route.v3.RouteAction",
        -                                                               "cluster": string("default/svc1/80/da39a3ee5e"),
        +                                                               "cluster": string("default/svc2/80/da39a3ee5e"),
                                                                },
                                                        },
                                                        {
                                                                "@type": s"envoy.config.route.v3.Route",
                                                                "match": protocmp.Message{
                                                                        "@type":  s"envoy.config.route.v3.RouteMatch",
                                                                        "prefix": string("/"),
                                                                        "query_parameters": []protocmp.Message{
                                                                                {
                                                                                        "@type": s"envoy.config.route.v3.QueryParameterMatcher",
                                                                                        "name":  string("query-param"),
                                                                                        "string_match": protocmp.Message{
                                                                                                "@type":    s"envoy.type.matcher.v3.StringMatcher",
        -                                                                                       "contains": string("def"),
        +                                                                                       "contains": string("abc"),
                                                                                        },
                                                                                },
                                                                        },
                                                                },
                                                                "route": protocmp.Message{
                                                                        "@type":   s"envoy.config.route.v3.RouteAction",
        -                                                               "cluster": string("default/svc2/80/da39a3ee5e"),
        +                                                               "cluster": string("default/svc1/80/da39a3ee5e"),
                                                                },
                                                        },
                                                },
                                        },
                                },
                        },
                }),
          }
</pre>        
</details>

While working on https://github.com/projectcontour/contour/pull/5064 I have noticed that the failure happen much more likely, maybe because that PR changes the timings and could possibly have impact on race conditions.

**Comment by tsaarni** [comment]
@relu I wonder, did you ever see this error?

**Comment by relu** [comment]
@tsaarni I'm afraid I don't recall seeing it, but I'm glad to hear it was found and sorted out. :raised_hands:

**Comment by tsaarni** [comment]
Oh, sorry I missed that. Thank you @skriss and @relu!
