### ISSUE TITLE
Heap memory clean up and limits

### ISSUE THREAD

**Issue by Daxcor69** [projectcontour/contour#5097]
User Case:
I have an application that uses long standing websocket connections. Sometimes between 6-8 hours.  I am seeing total heap memory creep over time.  

Issue:
My customers encounter a significant delay of service sporadically, usually during peak times.

Env:
I am running haproxy as a front end TCP LB round robin to host networked envoy deamonset on baremetal.

Question: 
If you don't set --overload-max-heap=  does envoy do clean up as mentioned here ```Shrink heap action is executed when 95% of the maximum heap size is reached```?  How does garbage collection happen?  Is this more of a question for Envoy than for Contour?

**Comment by tsaarni** [comment]
Hi @Daxcor69!  

If it is increasing during extended period continuously without upper bound, then to me it sounds like it might be a memory leak. Details are certainly more of a question for Envoy. Generally, I do not expect memory to be reclaimed from a process while it is running, but not continuously increase either!

As an exception to that general rule, Envoy overload manager does have the possibility to reclaim memory back to the system. Here is I found and noted down back when adding support for overload manager to Contour:

* [Overload manager](https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/overload_manager/overload_manager)  is enabled only if `--overload-max-heap` is set. I do not believe there will be an attempt to return allocated memory back to the operating system if overload manager is NOT enabled.
* Envoy uses [tmalloc](https://github.com/google/tcmalloc) as its `malloc()` implementation to manage heap memory.
* When overload manager and "shrink heap" action is enabled, it will be executed once every 10 seconds ([link](https://github.com/envoyproxy/envoy/blob/3cd4408783b86abaea94080f92944d7f714249e4/source/common/memory/heap_shrinker.cc#L24-L26))
* In practice it calls `tcmalloc::MallocExtension::ReleaseMemoryToSystem()` [here]( https://github.com/envoyproxy/envoy/blob/ff5b0a0325818463965ac1fc5abacf8d592a8dcd/source/common/memory/utils.cc#L22-L27). The function is described in this [tmalloc doc](https://google.github.io/tcmalloc/tuning.html#memory-releasing).
* The heap usage metrics can be monitored by port forwarding Envoy port 9001 and making request `curl http://localhost:9001/memory`. See troubleshooting instructions [here](https://projectcontour.io/docs/v1.24.1/troubleshooting/envoy-admin-interface/). To get an idea how these metrics map into tmalloc metrics, see code [here](https://github.com/envoyproxy/envoy/blob/ff5b0a0325818463965ac1fc5abacf8d592a8dcd/source/common/memory/stats.cc#L14-L43). Tmalloc metrics are documented [here](https://github.com/google/tcmalloc/blob/e091b551403f42417cb374110467a2f0ad661dc2/tcmalloc/malloc_extension.h#L225-L267) and [here](https://github.com/google/tcmalloc/blob/ac7a54fc916587a680b99ec7ceef1fd0e5b0953e/tcmalloc/malloc_extension.h#L427-L444).
* Envoy calculates pressure as follows ([code](https://github.com/envoyproxy/envoy/blob/4b5eee6b8ec3fc84fd1f7e6ee684947724843e47/source/extensions/resource_monitors/fixed_heap/fixed_heap_monitor.cc#L24-L34)):

```
physical = generic.heap_size
unmapped = tcmalloc.pageheap_unmapped_bytes

used = physical - unmapped
pressure = used / configured_max_heap_size_bytes
```

**Comment by Daxcor69** [comment]
Thank you for the explanation.   I will reach out to envoy and ask the same to see their thoughts.  It is tough sometimes separating  contour and envoy, but I am getting a clearer picture.  Again thank you.
