### ISSUE TITLE
Access logging: Add option to log originating Ingress/HTTPProxy with custom operator

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#5098]
**Please describe the problem you have**
Knowing the namespace/name of the Ingress/HTTPProxy that apply to a route can be useful when analyzing access logs to debug an issue or useful when sending logs to an aggregation service in a multi-tenant cluster.

We can add an access log operator specific to contour that users can add to the "text" or JSON access log types that will enable logging the name and namespace of the "originating" resource.
Here we mean "originating" resource to be the Ingress/HTTPProxy/etc. which has the route configuration that the request causing the access log is matched to.
For example if we have an Ingress in the `default` namespace named `foo` that specifies a hostname and prefix path match `example.com/api`,  any request to `example.com/api/*` will come with `default` and `foo` in the access log.

This is similar to the nginx feature `$namespace` and `$ingress_name` logging variables: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/log-format/

Possible implementations:
- Add metadata to each route and use the access log operators to fetch that and log it
  - https://github.com/envoyproxy/go-control-plane/blob/5903a350ed1cc44813f0a239ef3195278ac9a55d/envoy/config/route/v3/route_components.pb.go#L790-L795
  - https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#config-access-log-format-dynamic-metadata
- Add an access log with a different filter for each vhost/route etc.
  - filter on hostname, path etc?
  - https://github.com/envoyproxy/go-control-plane/blob/5903a350ed1cc44813f0a239ef3195278ac9a55d/envoy/config/accesslog/v3/accesslog.pb.go#L182onnection_manager.pb.go#L490
  - https://github.com/envoyproxy/go-control-plane/blob/5903a350ed1cc44813f0a239ef3195278ac9a55d/envoy/config/accesslog/v3/accesslog.pb.go#L262-L281
  - could cause a large number of access logs/processing decisions figuring out which match writes the log

Some considerations/testing notes:
- Need to make sure includes work properly, logging for included routes should work
- should work for Ingress
- an equivalent to the nginx `$service_name` might be useful as well, if not already available via existing Envoy access log operators
- naming?
- etc.

**Comment by tailrecur** [comment]
We currently have an Nginx ingress controller where we use the access logs to generate metrics for the different services behind it and use the `$ingress_name` and `$service_name` to distinguish the traffic. 
I'm trying to migrate to contour as the ingress controller and ran into this issue so +1 on implementing this feature 🙏🏽

**Comment by tailrecur** [comment]
Contour already has a `%CONTOUR_SERVICE_NAME%` dynamic value while expanding header policies so it would be good to align the names when implementing this fix.

**Comment by skriss** [comment]
@sunjayBhatia I can start looking into this if that works for you

**Comment by sunjayBhatia** [comment]
> @sunjayBhatia I can start looking into this if that works for you

go for it!

**Comment by skriss** [comment]
Got a basic spike working using the first approach in https://github.com/projectcontour/contour/compare/main...skriss:contour:accesslog-proxy-ns-name?expand=1

Example text access log output:

```
[2023-06-27T22:11:23.609Z] "(Ingress) default/basic" "GET /ing HTTP/1.1" 200 - 0 424 5 4 "172.18.0.1" "curl/7.88.1" "bec6899c-17a8-4ad1-b677-b516fca44541" "local.stevekriss.com" "10.244.1.18:8080"
[2023-06-27T22:11:31.437Z] "(HTTPProxy) default/proxy-1" "GET /s3 HTTP/1.1" 200 - 0 425 3 2 "172.18.0.1" "curl/7.88.1" "2b74845f-6feb-4d11-8019-90cb9793894e" "local.stevekriss.com" "10.244.1.20:8080"
[2023-06-27T22:11:34.873Z] "(HTTPProxy) default/proxy-1" "GET /s2 HTTP/1.1" 200 - 0 425 1 0 "172.18.0.1" "curl/7.88.1" "5d3434ca-8c5f-45d4-b5e5-20d4cf8f7533" "local.stevekriss.com" "10.244.1.19:8080"
[2023-06-27T22:11:35.970Z] "(HTTPProxy) default/proxy-1" "GET /s1 HTTP/1.1" 200 - 0 423 2 2 "172.18.0.1" "curl/7.88.1" "1da6d8a8-59e4-443e-8868-b503a0363967" "local.stevekriss.com" "10.244.1.18:8080"
```

Probably need to support some syntactic sugar for these, `%METADATA(ROUTE:envoy.access_loggers.file:namespace)%` etc. are not the most user-friendly.
