### ISSUE TITLE
ingressroute: update status of a parent IR when it is pointing to an invalid IR or a non-existent IR

### ISSUE THREAD

**Issue by alexbrand** [projectcontour/contour#510]
In a delegation path, we might want to let the owner of an IngressRoute that is delegating a path to another IngressRoute about an invalid or non-existent children.

Related: #490

**Comment by rosskukulinski** [comment]
This should also include the situation when the delegated namespace does not exist.

**Comment by rosskukulinski** [comment]
I think we should let this idea soak a bit more and gather feedback from users. Shifting to 0.7.0

**Comment by davecheney** [comment]
Closing, won't fix
