### ISSUE TITLE
set condition of Accepted: false with reason UnsupportedValue for unknown HTTPRoute path match types

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5103]
**What steps did you take and what happened:**
Currently, when an HTTPRoute has an unknown path match type (not `PathPrefix` or `Exact`), Contour sets a condition of "NotImplemented: true" with reason "PathMatchType". See:
- https://github.com/projectcontour/contour/blob/main/internal/dag/gatewayapi_processor.go#L1432

**What did you expect to happen:**
Per [the Gateway API spec](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.PathMatchType):

> Unknown values here must result in the implementation setting the Accepted Condition for the Route to status: False, with a Reason of UnsupportedValue.

Thanks to @fangfpeng for finding this!

**Anything else you would like to add:**
It would be good to audit other uses of the custom `NotImplemented` condition and see if there are other places where we should make a similar switch, it looks like there probably are.

**Environment:**
- Contour version: main

**Comment by nerdynikhil** [comment]
Hey @skriss, I would like to work on this.

**Comment by skriss** [comment]
Thanks @nerdynikhil; would you also be willing to investigate the other uses of the custom `NotImplemented` condition and change them if appropriate?

**Comment by nerdynikhil** [comment]
I can give it a try, @skriss. i'm on it

**Comment by nerdynikhil** [comment]
For https://github.com/projectcontour/contour/blob/b00a3f24641d4358ca40fb625c5f668b36c0b2db/internal/dag/gatewayapi_processor.go#L1047 we could have something like  `ConditionInvalidMatch` or `ConditionUnsupportedMatch` 

For https://github.com/projectcontour/contour/blob/b00a3f24641d4358ca40fb625c5f668b36c0b2db/internal/dag/gatewayapi_processor.go#L1063 simply `ConditionInvalidQueryParamMatch`

For https://github.com/projectcontour/contour/blob/b00a3f24641d4358ca40fb625c5f668b36c0b2db/internal/dag/gatewayapi_processor.go#L1184 let's say `RouteConditionNotImplemented`

For https://github.com/projectcontour/contour/blob/b00a3f24641d4358ca40fb625c5f668b36c0b2db/internal/dag/gatewayapi_processor.go#L1534 looking at other cases in the block, for the default case `UnsupportedFilterType`?

As I'm not very familiar with the codebase, I was only able to make rough suggestions based on my limited understanding and might sound totally ridiculous to you. The rest of the work is for you and the team to decide.
