### ISSUE TITLE
Envoy Thrift Proxy

### ISSUE THREAD

**Issue by shadialtarsha** [projectcontour/contour#5137]
**What question do you have?:**
I was wondering if there are any plans to add support for [Envoy Thrift Proxy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/thrift_proxy/v3/thrift_proxy.proto) to Contour.
Thank you!

**Comment by sunjayBhatia** [comment]
We do not have plans to do so at this time, but would accept community contributions to start experimenting and designing such a feature!

**Comment by shadialtarsha** [comment]
Hey @sunjayBhatia 
Thanks for replying! 
We are evaluating Contour as a potential ingress controller and having a Thrift proxy is an essential feature for us and we are happy to contribute! 
Let me open a design proposal for this!
