### ISSUE TITLE
DNS queries when locking down allowed DNS lookups

### ISSUE THREAD

**Issue by pfrydids** [projectcontour/contour#5153]
**What question do you have?:**

 I am implementing DNS Exfiltration protection and have seen periodic DNS queries for a domain `contour` and have tracked it down to the envoy daemonset .

Everything seems to be working but I see that a dns resolution for contour fails and then it moves on and it succeeds.
```
[2023-03-08 14:23:55.810][1][debug][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:324] dns resolution for contour started
[2023-03-08 14:23:55.813][1][debug][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:133] dns resolution for contour failed with c-ares status 1
[2023-03-08 14:23:55.813][1][debug][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:245] dns resolution for contour completed with status 0
```

which kinda confirm that nothing untoward is happening. But I'd prefer not to have to tolerate this attempt to lookup contour in our virtual private cloud DNS provider. It seems like it is ultimately getting resolved and presumably that is via coredns (the k8s DNS provider) .

Is this configurable in anyway?

**Anything else you would like to add:**

**Environment:**

- Contour version: 1.21.1
- Kubernetes version: (use `kubectl version`): 1.24
- Kubernetes installer & version: ?
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Amazon Linux 2

**Comment by tsaarni** [comment]
I guess in theory during deployment of Contour there could be a race condition where Envoy pods start and make a DNS lookup before the `Service` resource for `contour` has been created. In that case CoreDNS would be still unaware of the DNS record. But I would have assumed the query to be resolved by CoreDNS internally within the cluster, without forwarding to external DNS server :thinking: 

If I make a lookup on my cluster, CoreDNS refuses to forward DNS lookups with unqualified names. It just seems to respond with "no such name".
