### ISSUE TITLE
Avoiding HTTP 504 errors for long-running upstream requests, with Gateway API

### ISSUE THREAD

**Issue by jdoylei** [projectcontour/contour#5159]
How can we configure timeouts in Contour - based on Gateway API objects - to avoid HTTP 504 "upstream request timeout" responses from Envoy when our upstream service is slow (response in > 15 seconds)?

**Background:**

We have Contour's [Gateway provisioner](https://projectcontour.io/guides/gateway-api/) installed, currently [v1.23.0](https://raw.githubusercontent.com/projectcontour/contour/v1.23.0/examples/render/contour-gateway-provisioner.yaml), so our apps can use Gateway API with dynamic provisioning.

We hit a road-block with a slow upstream service that exceeds 15 seconds and causes Envoy to respond with HTTP 504 "upstream request timeout".  I think this means that the upstream service is exceeding Envoy's default 15-second [route-level timeout](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts#route-timeouts).

I gleaned from the Gateway API guide that I could use ```ContourDeployment``` to set some configuration, including the ```runtimeSettings.envoy.timeouts``` block with e.g. ```timeouts.requestTimeout```.  And I verified using ```/config_dump``` that Envoy's config reflects these timeouts settings, e.g. ```request_timeout```.  But this requestTimeout/request_timeout is different from the route-level timeout in Envoy's config, and changing it doesn't seem to affect this 15-second limit.  It doesn't seem that any of ```ContourDeployment``` impacts the route-level timeout.

Outside of Gateway API, it looks like there are different ways of setting the route-level timeout:
* [HTTPProxy timeoutPolicy.response](https://projectcontour.io/docs/v1.23.0/config/api/#projectcontour.io/v1.TimeoutPolicy)
* [Ingress annotation projectcontour.io/response-timeout](https://projectcontour.io/docs/v1.23.0/config/annotations/#contour-specific-ingress-annotations)

But I don't see a way using Gateway API and associated objects (GatewayClass, ContourDeployment, Gateway, HTTPRoute, Service) to set this.

How can we use Gateway API and still support a slow upstream service that takes > 15 seconds?

If there's not an immediate solution in the current Contour version, here are some thoughts:
* Can ```ContourDeployment``` ```runtimeSettings.envoy.timeouts``` get a new field that gives a global value to apply as the route-level timeout for *all* Envoy routes?
* Can Contour process the annotation ```projectcontour.io/response-timeout``` on Gateway, similar to what it does on Ingress?  Or even on Service (since there are already Service Contour annotations that seem like they map to Envoy route config)?
* Can Contour implement a policy CRD for settings like the route-level timeout along the lines of the [Gateway policy attachment spec](https://gateway-api.sigs.k8s.io/references/policy-attachment/#hierarchy)?  E.g. we would create a ```ContourTimeoutPolicy``` with a setting ```response: '30s'``` and ```targetRef``` pointing to an HTTPRoute?

Thanks for your time!

**Environment:**

- Contour version: v1.23.0
- Kubernetes version: (use `kubectl version`): v1.23.8

**Comment by liangyuanpeng** [comment]
> based on Gateway API objects - to avoid HTTP 504 "upstream request timeout"

Some ref for doc and seems like the gateway API have not deine for timeout today. It's in progress.

- https://github.com/kubernetes-sigs/gateway-api/issues/1742

**Comment by dlip** [comment]
This is a blocker for my team, I've tried setting the following in the ContourDeployment, but it doesn't seem to help.

```yaml
kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
  namespace: projectcontour
  name: contour-with-envoy-deployment-params
spec:
  runtimeSettings:
    policy:
      requestHeaders:
        set:
          x-envoy-upstream-rq-timeout-ms: "60000"
    envoy:
      timeouts:
        requestTimeout: 60s
```

Is there any possible workaround?

**Comment by dlip** [comment]
This is still an issue for me

**Comment by skriss** [comment]
The Gateway API GEP (https://github.com/kubernetes-sigs/gateway-api/pull/1997) has merged, so when this is available in the API we will look to implement.

**Comment by skriss** [comment]
https://github.com/projectcontour/contour/pull/5997 merged initial Gateway API timeout support which will be in the upcoming 1.28 release. I believe that closes out this request.
