### ISSUE TITLE
Http upgrade to https support custom port

### ISSUE THREAD

**Issue by yangyy93** [projectcontour/contour#5161]
**Please describe the problem you have**
[A clear, concise, description of the problem you are facing. What is the _problem_ that feature X would solve for you?]
When I enable tls in the domain name, the http request will be redirected to https by default. Now there is no custom port to configure. Is it possible to add a custom port to redirect to the non-443 port of https?
https://www.envoyproxy.io/docs/envoy/v1.25.2/api-v3/config/route/v3/route_components.proto.html#envoy-v3-api-msg-config-route-v3-redirectaction

**Comment by skriss** [comment]
@yangyy93 I noticed this same thing while working on https://github.com/projectcontour/contour/pull/5044 (see https://github.com/projectcontour/contour/blob/768782acc0f6e3be71ee04028d72bc84844e96a5/design/multiple-listeners-design.md#insecure---secure-redirect) -- currently, there's no way to control the port used for the insecure -> secure redirects.

For Gateway API, I think the user could define this themselves via HTTPRoutes with redirect policies, but for Ingress/HTTPProxy, we'd need to add a config knob for this.
