### ISSUE TITLE
Connection response header appears to be removed

### ISSUE THREAD

**Issue by boatmisser** [projectcontour/contour#5165]
**What question do you have?:**
We have an EKS cluster with Contour as the Ingress.
We have an app that returns `Connection: keep-alive` in the response.
The expectation is that the client will see this response header; however it seems that Contour is removing it.
In k8s, if I `port-forward` directly to the app I can see the `Connection` header in the response.
However if I `port-forward` to envoy then the `Connection` header is missing.

Is this intended behaviour?
Is there documentation on exactly what headers Contour adds, removes or passes on?

Thanks

**Anything else you would like to add:**
No

**Environment:**

- Contour version: v1.23.0
- Kubernetes version: (use `kubectl version`): 1.24
- Cloud provider or hardware configuration: AWS

**Comment by sunjayBhatia** [comment]
The `Connection` header is a "hop-by-hop" header and should not be propagated by proxies, see https://www.rfc-editor.org/rfc/rfc9110.html#name-connection

If you want to ensure returns `Connection` on downstream responses yourself, you can use https://deploy-preview-5163--projectcontour.netlify.app/docs/1.24/config/api/#projectcontour.io/v1.HeadersPolicy
