### ISSUE TITLE
Ability to provide custom HTML response for 5xx errors

### ISSUE THREAD

**Issue by oliverkane** [projectcontour/contour#5196]
**What question do you have?:**
Ability to provide custom HTML response for 5xx errors

**Anything else you would like to add:**
We are currently using Project Contour as our Kubernetes ingress controller and have encountered a scenario where we would like to provide a custom HTML response for 5xx errors. We understand that 5xx errors occur when there is a failure for the ingress controller to get information from the upstream, and this is a common scenario that we want to prepare for.

However, we have found that there doesn't appear to be a simple mechanism to provide a custom HTML response for these errors in Project Contour. If we were using an external Load Balancer, we could specify such a static response.

We would greatly appreciate it if the Project Contour team could provide clarity on whether this desirable use case is possible within the existing architecture of the project, and if not, if there are any plans to add such a feature in the future.

Thank you for your time and efforts in maintaining this project.

**Environment:**
-latest and greatest everything (recently from scratch, multiple environments, eg, kind, minikube, EKS, microk8s), new ubuntu 22.04 vms.

**Comment by skriss** [comment]
Hey @oliverkane, this looks like a duplicate of #320, would you agree? If so, we can continue the conversation there.

**Comment by oliverkane** [comment]
Looks like that's a dupe. I'll circle over there.
