### ISSUE TITLE
Wildcard certificate with HTTP/2 causes 421 Misdirected Request on cross-host connection reuse

### ISSUE THREAD

**Issue by sybereal** [projectcontour/contour#5240]
**What steps did you take and what happened:**

I deployed a Gateway with a wildcard hostname `*.cluster.example.com` and matching certificate, as well as two HTTPRoutes with specific hostnames matching that wildcard name. When navigating from one to another in a browser that implements HTTP/2 connection reuse, e.g. Firefox, there will be a 421 Misdirected Request error. Since the spec does not _require_ retrying, some clients (our reports came from macOS Safari users) will then be stuck on the error page.

I was able to forcibly trigger the 421 by passing one URL (for SNI) and then overriding the `Host` header to try and direct the request to another backend.

**What did you expect to happen:**

If there is one gateway with one certificate matching all possible hostnames, I would expect HTTP/2 connection reuse to work.

**Anything else you would like to add:**

I originally experienced the issue with separate Ingress resources using the same wildcard certificate and switched to Gateway API, hoping the split between the Gateway and HTTPRoute resources would avoid this issue.
In both cases, as soon as TLS is enabled, one filter chain is generated for each hostname, preventing connection reuse across hostnames.

Currently, the workaround I deployed disables HTTP/2, thus avoiding cross-host connection reuse entirely.

**Environment:**

- Contour version: 1.24.2 (Helm chart version 11.1.1)
- Kubernetes version: (use `kubectl version`): Kubernetes API server 1.25.5 (AKS) or 1.25.3 (KinD)
- Kubernetes installer & version: AKS/KinD
- Cloud provider or hardware configuration: Azure (AKS), bare metal / WSL (KinD)
- OS (e.g. from `/etc/os-release`): KinD running on openSUSE Tumbleweed in WSL, AKS running on Ubuntu

**Comment by sunjayBhatia** [comment]
This behavior is by design (and will not differ between Ingress, HTTPProxy, or Gateway API) because requests can be routed to the wrong backend/be processed incorrectly (generally be run through the wrong filter chain) if we do not check that the SNI and request authority match.

See original issue: https://github.com/projectcontour/contour/issues/1493

**Comment by sybereal** [comment]
My bad, I guess I should've phrased it as a question instead of a bug report.

So, am I correct in assuming that connection coalescing and thus HTTP/2 with wildcard certificates is inherently unsupported by Contour?

> requests can be routed to the wrong backend/be processed incorrectly (generally be run through the wrong filter chain) if we do not check that the SNI and request authority match

That's another question I had: I noticed that when TLS is disabled, there is only one filter chain and hosts are disambiguated through virtual hosts on the route config. But once TLS is enabled, each host gets its own filter chain.
