### ISSUE TITLE
allow alpha Gateway API resource informers to be disabled

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5247]
Currently, Contour packages the experimental channel of Gateway API, which includes both alpha and beta resources. However, some users may like to only have standard channel (beta) resources in their cluster. Contour should allow disabling the informers for alpha resources in that case.

We should be able to make use of the `--disable-feature` flag to `contour serve` which already allows disabling Contour's alpha ExtensionService resource informer.

**Comment by nsimons** [comment]
Yeah I was actually thinking the exact same thing last week when I was testing Gateway. I initially only installed the beta channel and Contour wouldn't start.

I can take this issue.

**Comment by sunjayBhatia** [comment]
Thanks @nsimons assigned to you 👍🏽
