### ISSUE TITLE
queryParameter condition not working in contour 1.24.0

### ISSUE THREAD

**Issue by saurabhguptaDoingCS** [projectcontour/contour#5248]
**What question do you have?:**
Hi Team, 
I am trying to use the below proxy configuration on the contour version 1.24.0 to route all requests with query parameter m=8 to my "new-service" and rest of the traffic distributed between other 3 services A, B and C.

**but not able to work "queryParameter" condition and getting following error on apply the httpproxy:** 
`strict decoding error: unknown field "spec.routes[0].conditions[0].queryParameter"`

Please look into it. 

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: pproxy
  namespace: p-prod
  labels:
    app.kubernetes.io/instance: myserver-azure
    app.kubernetes.io/name: myserver-azure
spec:
  virtualhost:
    fqdn: pproxy.w.myorg.com
    tls:
      secretName: myserver-prod-star-tls
  routes:
    - conditions:
      - queryParameter:
          name: m
          exact: 8
          ignoreCase: true
      services:
        - name: new-service
          port: 80
    - services:
        - name: a-service
          port: 80
          weight: 20
        - name: b-service
          port: 80
          weight: 30
        - name: c-service
          port: 80
          weight: 950
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- Contour version: 1.24.0
- AKS Version: Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", BuildDate:"2022-06-15T14:14:10Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", BuildDate:"2022-12-11T00:15:47Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by skriss** [comment]
@saurabhguptaDoingCS query parameter routing has not yet been released - the code been merged to `main` and will be in the upcoming v1.25.0 release around the end of the month.

If you're looking to try it out early, you can use the `main` branch's [example manifest](https://github.com/projectcontour/contour/blob/main/examples/render/contour.yaml) as a starting point. Please keep in mind this is a dev build and may not be stable. We will also have a 1.25 beta/release candidate available in the next week or two.
