### ISSUE TITLE
Support for configuring TLS_FALLBACK_SCSV on envoy using contour solution

### ISSUE THREAD

**Issue by Srinu88** [projectcontour/contour#5249]
Hi Team,

We are using Projectcontour to manage ingress traffic to app which are running on kubernetes cluster. As part of pentest we have observed that underlying envoy webserver is not configured to support TLS_FALLBACK_SCSV. Can you let us know how can we achieve this by update contour configuration. Incase if existing contour doesn't support this then is there any plan to provide support for this feature in near term.

Thanks.

**Comment by tsaarni** [comment]
Hi @Srinu88! 

Since we support only TLSv1.2 and TLSv1.3 and do not enable the obsoleted TLS versions, the use of TLS_FALLBACK_SCSV [rfc7507](https://www.rfc-editor.org/rfc/rfc7507.html) seems to be deprecated by [rfc8996](https://www.rfc-editor.org/rfc/rfc8996) with following rationale:

> The version-fallback Signaling Cipher Suite Value specified in RFC7507 was defined to detect when a given client and server negotiate a lower version of (D)TLS than their highest shared version. TLS 1.3 (RFC8446) incorporates a different mechanism that achieves this purpose, via sentinel values in the ServerHello.Random field. With (D)TLS versions prior to 1.2 fully deprecated, the only way for (D)TLS implementations to negotiate a lower version than their highest shared version would be to negotiate (D)TLS 1.2 while supporting (D)TLS 1.3; supporting (D)TLS 1.3 implies support for the ServerHello.Random mechanism. Accordingly, the functionality from RFC7507 has been superseded, and this document marks it as Obsolete.

**Comment by Srinu88** [comment]
Hi @tsaarni !

Thank your for the explanation, however our security team would like to understand exactly whether contour solution really has support to enable or disable TLS_FALLBACK_SCSV mechanism. 

Best Regards,
Srinivas.

> Hi @Srinu88!
> 
> Since we support only TLSv1.2 and TLSv1.3 and do not enable the obsoleted TLS versions, the use of TLS_FALLBACK_SCSV [rfc7507](https://www.rfc-editor.org/rfc/rfc7507.html) seems to be deprecated by [rfc8996](https://www.rfc-editor.org/rfc/rfc8996) with following rationale:
> 
> > The version-fallback Signaling Cipher Suite Value specified in RFC7507 was defined to detect when a given client and server negotiate a lower version of (D)TLS than their highest shared version. TLS 1.3 (RFC8446) incorporates a different mechanism that achieves this purpose, via sentinel values in the ServerHello.Random field. With (D)TLS versions prior to 1.2 fully deprecated, the only way for (D)TLS implementations to negotiate a lower version than their highest shared version would be to negotiate (D)TLS 1.2 while supporting (D)TLS 1.3; supporting (D)TLS 1.3 implies support for the ServerHello.Random mechanism. Accordingly, the functionality from RFC7507 has been superseded, and this document marks it as Obsolete.

Hi @tsaarni !

Thank your for the explanation, however our security team would like to understand exactly whether contour solution really has support to enable or disable TLS_FALLBACK_SCSV mechanism. 

Best Regards,
Srinivas.

**Comment by tsaarni** [comment]
Hi @Srinu88. As far as I understand, the underlying TLS implementation (BoringSSL) does have support for `FALLBACK_SCSV` and it would work if we would offer TLSv1.1. There does not seem to be any specific configuration needed to enable this. 

However, since we do not offer TLSv1.1 there does not seem to be a way to trigger the server to act on a client that sends `TLS_FALLBACK_SCSV`. That is, Envoy will never respond with alert `inappropriate_fallback` alert because the conditions described by [rfc7507](https://www.rfc-editor.org/rfc/rfc7507.html) cannot happen with TLSv1.2 and TLSv1.3 being the only enabled protocol versions.

Can you describe the exact protocol sequence what you observed and what you expected to observe when you said:
> As part of pentest we have observed that underlying envoy webserver is not configured to support TLS_FALLBACK_SCSV.
