### ISSUE TITLE
Support namespace-scoped Contour instances via Gateway provisioner

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5256]
As a follow-up to #5214, Contour's Gateway provisioner should support deploying Contour scoped to watching a subset of namespaces or one namespace. This requires adding an option to ContourDeployment for specifying the namespaces to watch, and then setting the `--watch-namespaces` flag on `contour serve` and adjusting the RBAC resources to be 1+ Roles and RoleBindings instead of a ClusterRole and ClusterRoleBinding.

_Originally posted by @skriss in https://github.com/projectcontour/contour/pull/5214#discussion_r1157821393_

**Comment by padlar** [comment]
working on this one

**Comment by sunjayBhatia** [comment]
assigned to @lubronzhan ! (havent heard from you for a while @padlar)

**Comment by sunjayBhatia** [comment]
should be some prior art in https://github.com/projectcontour/contour/pull/5302 that can be spruced up @lubronzhan, if you end up using it would be nice to ensure @padlar gets some co-author credit 👍🏽

**Comment by lubronzhan** [comment]
Yeah sure. I noticed @skriss mentioned there are some concerns about directly changing values of contourDeployment will cause mass rolling out of changes. 
The example Steve refer to is between gatewayclass and gateway. Adding an infrastructure field to gateway so to override the settings in `gatewayclass.spec.parameterRef`. In contour's case, it's `ContourDeployment`

Does @skriss suggest we have some mechanism that could for example add a field to ContourDeployment to tell whether the gatewayProvisioner should generate a copy of `ContourDeployment` on whenever a gateway is generated, and referencing that gateway to the new ContourDeployment
`type ContourDeployment struct{
	autoGenerateConfig bool
}
`
This way user can just modify the ContourDeployment associated with the current Gateway if they need to modify contour, without impacting other Gateway referencing the same gatewayClass.

**Comment by lubronzhan** [comment]
Or just keep current ContourDeployment structure, we don't automatically create ContourDeployment for Gateway, but change the way gatewayController reconcile, if there is `infrastructure` field in Gateway, let's say `ContourDeployment2`, which is different from `ContourDeployment1` referenced in GatewayClass parameterRef, Gateway provisioner should respect `ContourDeployment2` first, if there are fields in `ContourDeployment1` not in `ContourDeployment2`, then we can decide either to inherit those or just ignore them. 
We can discuss in the other issue later
I just created this one https://github.com/projectcontour/contour/issues/6071

**Comment by skriss** [comment]
@lubronzhan thanks for looking into this, and for filing #6071  - I agree that implementing the per-Gateway Infrastructure field is the best way going forward to solve the issue I was concerned about. It'll likely require revisiting some of our current reconciliation code, in addition to implementing the new field.

In the mean time, I think it's fair to move ahead with #5302 more or less as-is. We already violate the guidance of "GatewayClass should be used as a creation template only" in a few places, so it's not making things much worse.
