### ISSUE TITLE
Kustomization usage

### ISSUE THREAD

**Issue by nsimons** [projectcontour/contour#5258]
In #5257 I found it useful again to create a kustomization file to be able to deploy the disable-features use case quickly. Is `kustomize` something we generally would like to keep using in the future as well, or should we try to go for something else?

There is one problem, `kustomize` has a requirement that every _base_ configuration has a corresponding `kustomization.yaml` file, and our `/render` folder structure goes against this. Currently we have:

examples/render/
├── contour-deployment.yaml
├── contour-gateway-provisioner.yaml
├── contour-gateway.yaml
├── contour.yaml
└── kustomization.yaml

where it is only possible to refer to one of the base files (currently the above `kustomization.yaml` refers to `contour.yaml`). The other `contour-*.yaml` files cannot be used for kustomization (*).

If we would like to use the other `contour-*.yaml` files, then we need something like this:

examples/render/
├── contour
│   ├── contour.yaml
│   └── kustomization.yaml
├── contour-deployment
│   ├── contour-deployment.yaml
│   └── kustomization.yaml
├── contour-gateway
│   ├── contour-gateway.yaml
│   └── kustomization.yaml
├── contour-gateway-provisioner
│   ├── contour-gateway-provisioner.yaml
│   └── kustomization.yaml
...

It's not a big deal to change to this, but what do you think? It requires few modification in the `/hack` directory and in a handful of other places (e.g. `netlify.toml`).

(*) There is one workaround, you can execute the `kustomize` command with flag `--load-restrictor=LoadRestrictionsNone` (described [here](https://kubectl.docs.kubernetes.io/faq/kustomize/#security-file-foo-is-not-in-or-below-bar)) which means the above requirement/check is skipped, so you can refer to files in arbitrary directories without the need of kustomization.yaml, but this is not so clean.

**Comment by sunjayBhatia** [comment]
I'm open to moving towards using something like kustomize more consistently so we have less repetition, makes it easier to provide sample configs, etc., as long as we can keep the quickstart links and all working as they do today

We may also think about publishing example rendered YAML as artifacts in our github releases (cc @skriss you had this thought earlier)
