### ISSUE TITLE
Controller-gen randomly fails for filenames from mktemp

### ISSUE THREAD

**Issue by tsaarni** [projectcontour/contour#5271]
**What steps did you take and what happened:**

Compiling Contour sometimes fails when running `make generate`. The error can look something like this

```
Error: unable to parse option "object:headerFile=/var/folders/3f/08k867j16n1c0wvrxzp19b_m0000gn/T/tmp.gbjZOJRW": [invalid digit '8' in octal literal (at <input>:1:28)] 
```

This error was from MacOS and `/var/folders/zz/xyz` base path is coming from _CS_DARWIN_USER_TEMP_DIR ([link](https://magnusviri.com/what-is-var-folders.html)).  Depending on users (bad) luck, it might be interpreted as invalid digit like `08` ([link](https://go.dev/ref/spec#Integer_literals)) in this example and the generation will fail. When this happens, it is 100% reproducible since user's temp base dir does not change between executions.

Another example is from Linux. `mktemp` will sometimes generate filename that is interpreted as hexadecimal floating point numbers ([link](https://go.dev/ref/spec#Floating-point_literals)). It will happen very rarely, and the chances are that next run it will not fail. Error might look like following:

```
Error: unable to parse option "object:headerFile=/tmp/tmp.4pQcvCfLNX": ['p' exponent requires hexadecimal mantissa (at <input>:1:20) exponent has no digits (at <input>:1:20)]
```

**What did you expect to happen:**

Compiling should not fail.

**Anything else you would like to add:**

There is a limitation in [controller-tools](https://github.com/kubernetes-sigs/controller-tools) that causes the filename to be interpreted as digit https://github.com/kubernetes-sigs/controller-tools/issues/734

During Contour build we are running `controller-gen` for a filename that is created by `mktemp` - which can generate files that look like invalid digits

https://github.com/projectcontour/contour/blob/4e82e78a5a3ec8ed4d0cb7a31aa6b4a4b5b12444/hack/generate-crd-deepcopy.sh#L37-L44

There was previous attempt #5119 fixing similar problem.

It would be great if build did not depend on `mktemp` for filenames that are sent to controller-tools. The same issue applies both `hack/generate-crd-deepcopy.sh` and `hack/generate-crd-yaml.sh`

**Comment by christianang** [comment]
Took a look at this issue. Looks like controller-gen has fixed it in: https://github.com/kubernetes-sigs/controller-tools/pull/802.

I validated this by doing the following:

```bash
echo "// foo" > /tmp/tmp.4pQcvCfLNX

# Doesn't work because this release doesn't contain the commit
go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.11.4 object:headerFile=/tmp/tmp.4pQcvCfLNX paths=./apis/...

# Works because it contains the fix
go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.12.0 object:headerFile=/tmp/tmp.4pQcvCfLNX paths=./apis/...
```

Since contour is using the latest controller-gen when you run `make generate`, I think this issue can be closed.

**Comment by sunjayBhatia** [comment]
Nice! thanks for validating that, closing accordingly
