### ISSUE TITLE
document the argo-rollouts plugin for httpproxy

### ISSUE THREAD

**Issue by izturn** [projectcontour/contour#5280]
Hey @skriss @sunjayBhatia our team just release [a plugin](https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-contour) for  `contour/httpproxy` to let it can work with `argo-rollouts`, so whether we need to make a note at here?  If the answer is yes, where is the right place to do that?  Thanks.

**Comment by izturn** [comment]
Ok, I will add to it, maybe I/We post a blog later.

**Comment by skriss** [comment]
xref #4704

**Comment by izturn** [comment]
@skriss @sunjayBhatia WDYT about @wilsonwu 's suggestion?

**Comment by sunjayBhatia** [comment]
im a fan, aligns with https://github.com/projectcontour/contour/issues/4704 as well
