### ISSUE TITLE
HTTPProxy: HTTP healthcheck expected status code should be configurable

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#5289]
**Please describe the problem you have**
In some cases, the [HTTPHealthCheckPolicy API](https://projectcontour.io/docs/1.24/config/api/#projectcontour.io/v1.HTTPHealthCheckPolicy) provided by HTTPProxy is not sufficient, users may want the healthcheck to pass with a status code other than 200.

An open question here is whether this should be a single status code or a list

Notes:
- Envoy API field `ExpectedStatuses`: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/health_check.proto#envoy-v3-api-field-config-core-v3-healthcheck-httphealthcheck-expected-statuses

**Comment by skriss** [comment]
> An open question here is whether this should be a single status code or a list

Looks like Envoy supports configuring a contiguous range of expected statuses (e.g. 200-299); I'd say if we're going to add this as an option to healthCheckPolicy then probably makes sense to support a range there as well.
