### ISSUE TITLE
tracing: add feature test for custom tags

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5291]
Tracing has a [feature test](https://github.com/projectcontour/contour/blob/main/internal/featuretests/v3/tracing_test.go), however it is missing test coverage for [custom tags](https://github.com/projectcontour/contour/blob/main/internal/xdscache/v3/listener.go#L150). Coverage should be added in the feature test that ensures custom tags specified in the config are properly set on the tracing filter.

This could be done by adding some custom tags in [the existing TracingConfig](https://github.com/projectcontour/contour/blob/main/internal/featuretests/v3/tracing_test.go#L34-L40), and then verifying that the [emitted tracing filter config](https://github.com/projectcontour/contour/blob/main/internal/featuretests/v3/tracing_test.go#L105-L111) has the appropriate tags set.

**Comment by tsaarni** [comment]
Tip: To check the coverage results, run `make check-coverage` and open file `coverage.html`
