### ISSUE TITLE
internal/envoy/v3: add test coverage for SlowStartConfig with Least Request LB policy

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5292]
[Slow start config has test coverage for when used with a round robin LB policy](https://github.com/projectcontour/contour/blob/main/internal/envoy/v3/cluster_test.go#L577-L610), however coverage is missing for when used with [least request LB policy](https://github.com/projectcontour/contour/blob/main/internal/envoy/v3/cluster.go#L119-L124). Add a test case similar to the existing one, for a cluster with a "least request" LB policy.

**Comment by tsaarni** [comment]
Tip: To check the coverage results, run `make check-coverage` and open file `coverage.html`

**Comment by owayss** [comment]
working on this
