### ISSUE TITLE
upgrade metallb to latest (v0.13.9)

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5293]
Contour uses [metallb](https://metallb.universe.tf/) in its default kind cluster setup for development and testing.

Currently, [v0.13.7 is being used](https://github.com/projectcontour/contour/blob/main/test/scripts/make-kind-cluster.sh#L75). This should be upgraded to [v0.13.9](https://metallb.universe.tf/release-notes/#version-0-13-9) to pick up bug fixes.

**Comment by IdanAtias** [comment]
Hi, I'll take that.
