### ISSUE TITLE
cmd/contour/serve.go: de-dupe ExtensionService resolution code

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5295]
In cmd/contour/serve.go, we have three different ExtensionServices that are being resolved:
- Tracing
- Global rate limiting
- Global ExtAuth

There is some code duplication between these that would be good to extract a helper function for. Specifically, the following blocks of code all do the same thing:
- https://github.com/projectcontour/contour/blob/main/cmd/contour/serve.go#L675-L702
- https://github.com/projectcontour/contour/blob/main/cmd/contour/serve.go#L720-L748
- https://github.com/projectcontour/contour/blob/main/cmd/contour/serve.go#L606-L631

Extract a helper for this logic that can be reused across the three `setupXXX` methods.

**Comment by shayyxi** [comment]
I want to work on this.
