### ISSUE TITLE
remove double import in internal/envoy/v3/listener.go

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5300]
In internal/envoy/v3/listener.go, the package `github.com/envoyproxy/go-control-plane/envoy/extensions/filters/http/router/v3` is imported twice under two different aliases (`envoy_extensions_filters_http_router_v3` and `envoy_router_v3`). 

The import using `envoy_extensions_filters_http_router_v3` should be removed, and the references to it should be updated to use `envoy_router_v3`.

**Comment by padlar** [comment]
PR submitted
