### ISSUE TITLE
[provisioner] add a way to generate dualstack envoy service

### ISSUE THREAD

**Issue by Jean-Daniel** [projectcontour/contour#5308]
**Please describe the problem you have**

Our setup actually requires to deploy envoy behind a Dual Stack LoadBalancer service.
While it is possible to create a `LoadBalancer` service by providing the Envoy Networking Type, Kubernetes defaults to create such `Service` with `ipFamilyPolicy` set to `SingleStack`.

To create a Dual Stack service, `ipFamilyPolicy` [must be explicitly](https://kubernetes.io/docs/concepts/services-networking/dual-stack/#service-type-loadbalancer) set to `PreferDualStack` or `RequireDualStack `, which is currently not possible.

Would it make sense to add such setting in `ContourDeployment.spec.envoy.networkPublishing` ?

**Comment by skriss** [comment]
That makes sense to me @Jean-Daniel
