### ISSUE TITLE
Even if http2 connection is active and data are getting streams, stream_idle_timeout gets triggered after 5m

### ISSUE THREAD

**Issue by kumar-subashp** [projectcontour/contour#5309]
Even if the http2 connection is active/alive and data are getting streams, stream_idle_timeout gets triggered after 5m, which leads to connection timeout. how to handle this scenario?

Application Details:
 we have exposed a reactive API endpoint over http2, and calling that endpoint using webclient to streams the data. 

**Environment:**

- Contour version: 1.18.0
- Kubernetes version: (use `kubectl version`): v1.23.10
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
Per Slack:
