### ISSUE TITLE
how to configure initial_stream_window_size and initial_connection_window_size http/2 envoy options through contour ?

### ISSUE THREAD

**Issue by kumar-subashp** [projectcontour/contour#5315]
how to configure initial_stream_window_size and initial_connection_window_size http/2 envoy options through contour ?

**Environment:**

- Contour version:
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
@kumar-subashp this is not currently configurable via Contour, the Envoy defaults apply.

https://github.com/projectcontour/contour/issues/1795 tracks changing the defaults for these fields to match the recommended settings in https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge#best-practices-edge. We could potentially look at making these user-configurable as well, if it's needed.

**Comment by skriss** [comment]
I'm going to close this issue out; please continue any further discussion on #1795, thanks!
