### ISSUE TITLE
[Feature] Outlier Detection

### ISSUE THREAD

**Issue by wilsonwu** [projectcontour/contour#5317]
Hi team, about outlier detection feature, do you think it is right time to have?

@yangyy93 and I would like to contribute it.

**Comment by wilsonwu** [comment]
@skriss Do you have any suggestion?

**Comment by sunjayBhatia** [comment]
@wilsonwu I think that would be an improvement that would augment existing health-checking behavior 👍🏽 

A full design doc with motivations and use cases would be great to see to make sure we consider/design an API that meets the stated goals!

(also we can use this issue as a tracking issue for the design and implementation, though the description could use a tiny summary on what the intent is for posterity)

**Comment by wilsonwu** [comment]
Thanks @sunjayBhatia, we will start for the design work soon, any update will post here for review.
