### ISSUE TITLE
Add owner ref to resources created by gateway provisioner

### ISSUE THREAD

**Issue by RmStorm** [projectcontour/contour#5338]
We're using ArgoCD to deploy our applications. The gateway provisioner creates a contour deployment and an envoy deployment. These should be owned by the gateway that caused their creation. Without the owner ref ArgoCD becomes confused and marks the resources for deletion. So the application always looks out of sync.

Maybe it's somewhat of an ArgoCD problem but I think having the owner refs make sense? The [k8s documentation](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/) seems to imply to me that this is a typical case where an ownerref is the thing to do.

And the change seems fairly straightforward, I think the OwnerRef should be added [here](https://github.com/projectcontour/contour/blob/main/internal/provisioner/objects/deployment/deployment.go#L197-L201) when applicable.

**Comment by sunjayBhatia** [comment]
That sounds like a reasonable change, the Gateway being the in-namespace "owner" of the provisioned infrastructure resources makes sense

There is also this GEP which (I thought already did, but I must be mistaken) may formalize this sort of structure as a feature of the API in the future: https://github.com/kubernetes-sigs/gateway-api/pull/1868, so something to keep an eye on (I'll add a comment with this query as well)

**Comment by sunjayBhatia** [comment]
see here: https://github.com/kubernetes-sigs/gateway-api/pull/1757/files#diff-d493b9be8a91ac6e0c07106e8a63a34486a029bb2a7e39bb5ec6989d0cab11e3R183

looks like this notion is already capture in a GEP, so reasonable to go forward with this IMO

**Comment by RmStorm** [comment]
That's great! I can make a PR for this but my knowledge of Contour is extremely limited. I have a hunch that more than just the Envoy daemonset/deployment and the Contour deployment should have this annotation?

A single contour instance seems to be created by the [6 'Ensure' calls here](https://github.com/projectcontour/contour/blob/main/internal/provisioner/controller/gateway.go#L428-L437). Should all of them have the api owner annotation?

And how would I go about implementing it? The Contour object has a [GatewayControllerName](https://github.com/projectcontour/contour/blob/main/internal/provisioner/model/model.go#L148) but not a concrete owning gateway? Is the actual gateway easy to get hold of? Or should I add a field to that model with it? I need the UID and the name of the owning gateway.

If you can answer these two question I would happily make a PR :smile:. But it could very well be that it's faster for you to do it.
