### ISSUE TITLE
[Enhancement] The request/limit resources for some containers

### ISSUE THREAD

**Issue by wilsonwu** [projectcontour/contour#5349]
During our usage, we found these job: `envoy-initconfig`, and this container: `shutdown-manager` with some resources limitation problem in some cluster with quota setting. By default these resouces setting is: `{}`, and there is no way to set it when we setup new contour and envoy.

So do you think we can have a customized setting for the reousces for these two container? If OK, we can contribute it.

**Comment by skriss** [comment]
ref. https://projectcontour.io/docs/1.25/deploy-options/#setting-resource-requests-and-limits
ref. https://projectcontour.io/docs/1.25/troubleshooting/envoy-container-draining/

@wilsonwu, is this in the context of the Gateway provisioner?

**Comment by wilsonwu** [comment]
Thanks for your reply @skriss and I checked with @yangyy93, seems for `envoy-initconfig` and `shutdown-manager` there is no way to change the resources (CPU and memory), any docs I missed please let me know.

**Comment by wilsonwu** [comment]
@skriss can't agree more with you, I will talk about this with @izturn and enhance it if need.

**Comment by izturn** [comment]
thx u all, i will work on this
