### ISSUE TITLE
Where can i define load balancing algorithm? 

### ISSUE THREAD

**Issue by Sinamcp** [projectcontour/contour#5354]
Hi, I deployed contour, but my question is how can define which load balancing algorithm to use? is there any arg, env or something else?
I know i can define it in HTTPProxy object, but i just want to know what happen if user does not set loadBalancerPolicy, and what is the default loadBalancerPolicy?

**Comment by sunjayBhatia** [comment]
See this documentation for examples and descriptions of the defaults etc.: https://projectcontour.io/docs/1.25/config/request-routing/#load-balancing-strategy

**Comment by Sinamcp** [comment]
Thanks, @sunjayBhatia, i though there is configuration in contour itself, it seems we need to configure it at HTTPProxy abject

**Comment by Sinamcp** [comment]
Thanks for your help
