### ISSUE TITLE
How can I change port for shutdown manager(8090)

### ISSUE THREAD

**Issue by Sinamcp** [projectcontour/contour#5356]
**What question do you have?:**
I deployed 3 envoy on the same edge node, with different ingressclass and hostnetwork: true. I just wanted to know how can I change the shutdown port for each envoy, I mean what the port name is?
For example for liveness porbe is metrics.

**Environment:**

- Contour version: 1.25
- Kubernetes version: 1.23

**Comment by skriss** [comment]
See https://projectcontour.io/docs/1.25/redeploy-envoy/#shutdown-manager-config-options. You can provide the `--serve-port` flag to the `contour envoy shutdown-manager` command (https://github.com/projectcontour/contour/blob/main/examples/contour/03-envoy.yaml#L27-L31), and then change the corresponding port in the `preStop` hook (ref. https://github.com/projectcontour/contour/blob/main/examples/contour/03-envoy.yaml#L95).

**Comment by Sinamcp** [comment]
Thanks @skriss 
      containers:
        - args:
            - envoy
            - shutdown-manager
          command:
            - contour
          image: 'ghcr.io/projectcontour/contour:v1.25.0'
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - contour
                  - envoy
                  - shutdown
                args:
                  - --serve-port=8091 
          name: shutdown-manager
          volumeMounts:
            - mountPath: /admin
              name: envoy-admin

is thta ok?

**Comment by skriss** [comment]
Put `--serve-port=8091` on a new line within `args`

**Comment by Sinamcp** [comment]
Thanks a lot @skriss, It works
