### ISSUE TITLE
Set http to https redirect for all ingresses

### ISSUE THREAD

**Issue by ZrytyADHD** [projectcontour/contour#5395]
I have a question about some settings.
We use Contour with Envoy for Kubernetes cluster

I want to set globally redirect from http to https when it's created.

Now when do that i have to add annotation to each ingress:
ingress.kubernetes.io/ssl-redirect: "true"

There is an option to set in globally for all current and future ingress which will be created.

**Comment by skriss** [comment]
@ZrytyADHD there is not currently a way to set this behavior by default for all Ingresses, you would need to add the annotation to each one. If you use HTTPProxy, however, it is enabled by default.
