### ISSUE TITLE
Update EventHandler to use new client-go cache.ResourceEventHandler interface

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#5402]
Let's try to take advantage of the new addition to the client-go `ResourceEventHandler` loop to make our processing of the initial resource list/startup better.

See the `OnAdd` method: https://github.com/kubernetes/client-go/blob/151a5919dbfe858f011422d6fcee2b998bb209d8/tools/cache/controller.go#L218

It adds a boolean parameter to signify whether the event comes as part of the initial List of resources on startup.

We can use this to improve our startup flow and ensure not just Informers are synced before we start the xDS server but that handlers actually receive the events.

**Comment by tsaarni** [comment]
xref https://github.com/projectcontour/contour/pull/5672
