### ISSUE TITLE
Envoy FIPS build doesn't produce tarball

### ISSUE THREAD

**Issue by kyle-ntx** [projectcontour/contour#5411]
**What question do you have?:**
I've been attempting to follow the instructions on the [FIPS 140-2 in Contour](https://projectcontour.io/guides/fips/) documentation page, however, I am struggling to create the envoy_binary.tar.gz file mentioned in the section about building Envoy.  

When I run the command `BAZEL_BUILD_EXTRA_OPTIONS="--define boringssl=fips" ENVOY_DOCKER_BUILD_DIR=~/envoyBuild ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release.server_only'` from within the envoy directory (created by git cloning the envoy repo), the build appears to run without error, however, it does not produce the expected tar file. 

When I look in the specified ENVOY_DOCKER_BUILD_DIR directory, I find 3 folders: bazel_root, envoy, repository_cache.  Digging down into the 'envoy' folder I eventually find an executable called 'envoy' and another called envoy.dwp.  They are found at this path: `/envoyBuild/envoy/x64/source/exe/envoy`

Does anyone have any idea what I am doing wrong here?  My gut feeling on this is that either I've missed something obvious or the Envoy build process has changed and the command supplied in the documentation no longer works the way it used to. 

**Environment:**

- Contour version: latest. 
- Kubernetes version: (use `kubectl version`): N/A
- Kubernetes installer & version: N/A
- Cloud provider or hardware configuration: Azure  F32s_v2
- OS (e.g. from `/etc/os-release`):
Build Environment:
Ubuntu Server 22.04.2 LTS
Docker Engine 24.0.1

**Comment by sunjayBhatia** [comment]
Yep the build process in Envoy has changed so our doc needs a bit of an update, we can use this issue to track making the updates

**Comment by sunjayBhatia** [comment]
Take a look at the update in https://github.com/projectcontour/contour/pull/5415 to see if it works! Would appreciate any comments in case you run into any issues

**Comment by kyle-ntx** [comment]
Thanks for the super fast response! I've taken a look at the PR and left a comment.
