### ISSUE TITLE
Issue with GOMAXPROCS when running contour from quickstart

### ISSUE THREAD

**Issue by stumueller** [projectcontour/contour#5426]
**What steps did you take and what happened:**
I am running Ubuntu in WSL. In my minikube instance I am running kubectl apply -f https://projectcontour.io/quickstart/contour.yaml
The certgen pods are erroring with the following in the log file:

level=fatal msg="failed to set GOMAXPROCS" error="path \"/docker/4bfd8940271e25298fc1c1e94e7a739a1f9247b7b6888a75186017484ee8f55f\" is not a descendant of mount point root \"/docker/4bfd8940271e25298fc1c1e94e7a739a1f9247b7b6888a75186017484ee8f55f/kubelet\" and cannot be exposed from \"/sys/fs/cgroup/misc/kubelet\""

**What did you expect to happen:**
This was working about a month ago, when I last ran this.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.25
- Kubernetes version: (use `kubectl version`): 1.26.3
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): Ubuntu

**Comment by sunjayBhatia** [comment]
Looks like another instance of https://github.com/projectcontour/contour/issues/5378

**Comment by stumueller** [comment]
So I've downgraded docker-ce to 23.0.5-1 and containerd.io to 1.6.4-1 and its working again now - but obviously I'd like to be able to upgrade to the latest.

**Comment by sunjayBhatia** [comment]
We've made a change here https://github.com/projectcontour/contour/pull/5427 and a 1.25 backport as well, so once we cut 1.25.x this should be fixed

Closing for now since you've got a workaround and the next releases should contain the fix
