### ISSUE TITLE
Gateway API conformance: Request mirror test is flaky

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#5445]
We've recently merged support for Gateway API v0.7.1 and associated conformance tests, which include a request mirroring test: https://github.com/kubernetes-sigs/gateway-api/blob/v0.7.1/conformance/tests/httproute-request-mirror.go

So far this test has been flaky, see:
- https://github.com/projectcontour/contour/actions/runs/5189870905/jobs/9356194610
- https://github.com/projectcontour/contour/actions/runs/5213468387/jobs/9409525070

**Comment by sunjayBhatia** [comment]
submitted https://github.com/kubernetes-sigs/gateway-api/pull/2098

**Comment by sunjayBhatia** [comment]
debugging in https://github.com/projectcontour/contour/pull/5446 but now of course it never fails

**Comment by sunjayBhatia** [comment]
tbh beginning to think returning errors early might be what is helping that debug branch not fail so often, so enabled verbose logging to inspect the passed results

**Comment by skriss** [comment]
Hopefully fixed by https://github.com/kubernetes-sigs/gateway-api/pull/2438

**Comment by skriss** [comment]
Will keep an eye on this for a bit but hopefully we'll be able to close it out.

**Comment by skriss** [comment]
Haven't seen any recent instances of this flaking so I'll close this out for now, can always reopen if needed.
