### ISSUE TITLE
Global Contour configurations should be applied in all processors

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#5458]
This isn't exclusive to this PR #5417, but we have various cluster-level settings that are supposed to be global that do not get applied to Ingress or Gateway API generated clusters. Similarly, global extauth or other features do not get applied to routes/clusters/etc. generated from Gateway API/etc. resources (see https://github.com/projectcontour/contour/discussions/5435)

We should make sure the story here is consistent and document what is not supported and/or implement these features across the board.

Notes:
- It may be more ideal to abstract some of these global configs to be applied regardless of the processors in place, so duplication of code doesn't have to happen

**Comment by skriss** [comment]
xref https://github.com/projectcontour/contour/pull/5493#discussion_r1237383250

**Comment by skriss** [comment]
> It may be more ideal to abstract some of these global configs to be applied regardless of the processors in place, so duplication of code doesn't have to happen

I like this idea, otherwise we get duplication of code _and_ it's easy to miss certain places that need updates.
