### ISSUE TITLE
services referenced by a GRPCRoute don't trigger a DAG rebuild

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5476]
The [serviceTriggersRebuild](https://github.com/projectcontour/contour/blob/main/internal/dag/cache.go#L387) method determines whether a Service change should trigger a DAG rebuild, based on whether the Service is referenced by any routing config. It looks like we forgot to add code to check GRPCRoutes for Service references here. That should be added and look similar to the existing checks for HTTPRoutes and TLSRoutes.

**Comment by yanggangtony** [comment]
I will have a try to that.
