### ISSUE TITLE
Request for Fractional Mirroring

### ISSUE THREAD

**Issue by hshamji** [projectcontour/contour#5495]
Hello,

Envoy allows for fractional request mirroring: [Envoy Docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-routeaction-requestmirrorpolicy) & [Envoy proto](https://github.com/envoyproxy/envoy/blob/908af8a94fac533e693c396bad6bbbb00cc10b6f/api/envoy/config/route/v3/route_components.proto#L809).

Currently in Contour without the ability to set this attribute it defaults to mirroring 100% of traffic.

Mirroring is particularly useful when developing new applications, but being forced to mirror 100% of (usually prod) traffic is too burdensome / expensive in high RPS contexts. Being able to control the mirroring percentage would allow us to use the mirroring functionality in **many** more places.

Could a workaround be to create a mirror (to a dummy service) and use fractional splitting on that mirror to get the desired % to the target service? Would that work? Are there other options to get the same effect?

If this needs to be implemented, am happy to work on this and submit a PR.

Love to chat more about reactions to this request. Thank you,

**Comment by tsaarni** [comment]
Hi @hshamji! If you didn't see https://github.com/projectcontour/contour/issues/1889 yet, could you check it and see https://github.com/projectcontour/contour/issues/1889#issuecomment-1538862413. Would option 1 work for you?

**Comment by hshamji** [comment]
Awesome. Happy to.

Implementation seems fairly light, IIUC. Just use the `weight` attribute that is already present on the Route object and use it to set fractional_percent when present with a mirror policy. No changes to CRD, no additional indirection, etc.?

**Comment by skriss** [comment]
:+1: I'm on-board with that approach, thanks @hshamji!
