### ISSUE TITLE
send envoy logs to syslog server

### ISSUE THREAD

**Issue by Sinamcp** [projectcontour/contour#5525]
**What question do you have?:**

Hi, I just wanted to know that, is that possible to send envoy logs to syslog? like telegraf
- Contour version: 1.25

**Comment by tsaarni** [comment]
Envoy itself does not support syslog protocol, but one could use some external log forwarder, such as fluent-bit, to bridge the gap.

Here are the access loggers that Envoy supports currently natively: [link](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/accesslog/v3/accesslog.proto#extension-category-envoy-access-loggers). From those, Contour currently configures Envoy with File access log (`envoy.access_loggers.file`).

**Comment by Sinamcp** [comment]
Thanks, I don't know why this  envoy metric(envoy_cluster_upstream_rq) does NOT have label for route_name or vhost, because in our case we want to monitor rps per route, not per service

**Comment by sunjayBhatia** [comment]
@Sinamcp see this issue https://github.com/projectcontour/contour/issues/4637

we haven't yet enabled per-route stats but this issue should enable that, if that is relevant to your needs

**Comment by Sinamcp** [comment]
Thanks @sunjayBhatia, I hope you enable these feature soon, because we need it.
