### ISSUE TITLE
Httpproxy not supporting queryParameter match condition

### ISSUE THREAD

**Issue by nageshs28** [projectcontour/contour#5549]
**What steps did you take and what happened:**
Upgraded contour to 1.25
Update httpproxy routes to add querycondition

    - conditions:
      - queryParameter:
          name: x
          exact: 18

Error -  strict decoding error: unknown field "spec.routes[0].conditions[0].queryParameter

**What did you expect to happen:**
Httpproxy should be applied and show valid, envoy should honour during routing

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.25
- Kubernetes version: (use `kubectl version`): 1.26
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: Azure - AKS
- OS (e.g. from `/etc/os-release`): ubuntu 22 lts

**Comment by nageshs28** [comment]
@relu  Can you please help here

**Comment by relu** [comment]
@nageshs28 are you sure you updated the CRDs? Make sure the `httpproxies.projectcontour.io` is up to date.

**Comment by nageshs28** [comment]
Thanks folks, it was issue with outdated crd only.
