### ISSUE TITLE
Cache sync latency

### ISSUE THREAD

**Issue by therealak12** [projectcontour/contour#5550]
**What steps did you take and what happened:**
1. We have a cluster with around 3000 httpproxy objects. Also, the connection between the etcd and the disk utilized as its storage is slow.
2. When the latency escalates, the controller manager process terminates with a `leader election lost` error message.
3. After being restarted, the new process marks nearly all httpproxy objects as invalid with an error message like `secret for fallback certificate not found` or `target service not found`.

**What did you expect to happen:**
The controller should wait for the cache sync and then start validating httpproxy objects.

**Anything else you would like to add:**
I'm not sure if the cache sync latency is the issue. Another possibility is the latency in reconciling the `TLSCertificateDelegation` resource.

**Environment:**

- Contour version: v1.25.0
- Kubernetes version: (use `kubectl version`): v1.23.3
- Kubernetes installer & version: okd4 ([installation process](https://docs.okd.io/latest/installing/index.html))
- Cloud provider or hardware configuration:
CPU: 24 (Skylake, IBRS)
Arch: x86_64
Memory: 62Gi
- OS (e.g. from `/etc/os-release`): CentOS 7

**Comment by therealak12** [comment]
Some more details on this issue:
Contour fills an additional cache (separate from the controller runtime's cache). As far as I've understood, the cache is filled gradually as the `OnAdd`, `OnUpdate`, and `OnDelete` events of controller-runtime (or better to say client-go) are fired. Here are some important points in the code:

- [The OnAdd handler function](https://github.com/projectcontour/contour/blob/main/internal/contour/handler.go#L86)
- [The actual insert function call](https://github.com/projectcontour/contour/blob/main/internal/contour/handler.go#L185)
- [The insertion of a secret into the cache](https://github.com/projectcontour/contour/blob/main/internal/dag/cache.go#L125)
- [The way a secret is looked up in the cache](https://github.com/projectcontour/contour/blob/main/internal/dag/cache.go#L693)

A challenge arises in that the [eventHandler added to the manager](https://github.com/projectcontour/contour/blob/main/cmd/contour/serve.go#L590) solely implements the [LeaderElectionRunnable](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/manager/manager.go#L312) interface. However, IMHO, it should implement the [hasCache](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/manager/internal.go#L171) interface so that the manager could detect when the cache is synced!

In our cluster, which utilizes a slow-disk etcd, the sequence of events is as follows:

1. The `WaitForCacheSync` function is called to ensure the controller runtime cache is synced.
2. The operator tries to find a delegated secret [here](https://github.com/projectcontour/contour/blob/main/internal/dag/httpproxy_processor.go#L233) from the **dag's internal cache** which may not be necessarily in sync with the most recent etcd state.
3. Consequently, The httpproxy objects will be marked as invalid one by one with a `SecretNotValid` condition and a `secret not found` error message.

---

A trivial solution is to implement a `WaitForCacheSync` method for the internal cache so that the controller runtime could ensure cache sync. I'm not 100% sure how to implement this method but I'm trying to figure it out. I'd really appreciate any help on this or any other idea on how to solve this issue.

**Comment by therealak12** [comment]
The client-go informers [list their specific resources initially](https://github.com/kubernetes/client-go/blob/master/tools/cache/reflector.go#L673). Later the [`HasSynced` function](https://github.com/kubernetes/client-go/blob/master/tools/cache/delta_fifo.go#L298) checks if items of the initial have been popped completely.

The same implementation for the contour dag's internal cache is possible though not trivial. We have to list [the resources we are interested in](https://github.com/projectcontour/contour/blob/main/internal/dag/cache.go#L121) and pass them to the [contourHandler](https://github.com/projectcontour/contour/blob/main/cmd/contour/serve.go#L530). Then the handler itself should pop each object from the list after it's handled. A new `HasSynced` method can be introduced which checks if all of the list items are popped.

As a workaround, we can make [`HoldoffDelay` and `HoldoffDelayMax`](https://github.com/projectcontour/contour/blob/main/cmd/contour/serve.go#L532-L533) configurable so that clusters with slow etcd can set these to higher values to ensure Dag is built after the full cache sync.
Increasing these values might result in high latency in the reconciliation of ingress objects but is preferable to downtimes caused by invalidated ingress objects.

These stuff are just my interpretation of the contour's logic. If any of the maintainers could approve these suggestions, I'm okay with implementing them. Thanks in advance.

**Comment by tsaarni** [comment]
I'm not familiar with this, so take following with a grain of salt, but some time ago I saw client-go and controller-runtime added a new parameter `isInInitialList bool`  to `OnAdd()`. If adding debug print for it [here](https://github.com/projectcontour/contour/blob/dfe042ec18d081d36576f366bd492c21b73db582/internal/contour/handler.go#L85-L87), it _seemed_ like it was `true` for objects added during initial synchronization and `false` for the ones added later.  

I did not attempt to find out more about it, to prove this is the case, or to see if there are other ways. Anyhow, it seemed bit backward to me, since from that boolean you still do not know if that was the last `OnAdd(isInInitialList=true)` call there will be, other than maybe by having a timeout that gets extended by short period at every `OnAdd(isInInitialList=true)` call?

**Comment by therealak12** [comment]
Many thanks!
This `isInInitialList` perfectly aligns with the requirement!
I'll investigate the existing implementations using this boolean, and try to implement the same for DAG's internal cache (if you agree).

**Comment by tsaarni** [comment]
> I'll investigate the existing implementations using this boolean, and try to implement the same for DAG's internal cache (if you agree).

It would be absolutely fantastic if you do! :smile: :tada:

**Comment by therealak12** [comment]
For an object of the initial list, the client-go [waits for the handler's handle method](https://github.com/kubernetes/client-go/blob/b8a03ab933ab332affa308e107cac58ccc6f40f4/tools/cache/shared_informer.go#L974) (e.g. `OnAdd`) to be done and then assumes the object is synced into the cache.

The way contour implements `OnAdd` somehow neutralizes this logic of client-go. The code [pushes the event to a channel](https://github.com/projectcontour/contour/blob/4c00ba934792a271fb60846bd9cd01daef37ba8e/internal/contour/handler.go#L86) and [processes the event asynchronously](https://github.com/projectcontour/contour/blob/4c00ba934792a271fb60846bd9cd01daef37ba8e/internal/contour/handler.go#L146).

A simple way to work around this is to track objects with a [SingleFileTracker](https://github.com/kubernetes/client-go/blob/b8a03ab933ab332affa308e107cac58ccc6f40f4/tools/cache/synctrack/synctrack.go#L80) and ensure all of them are handled by the handler in the `HasSynced` method. This is the same way client-go handles events.

Another solution could be changing the logic to handle events synchronously. I doubt if this is a good way of handling the issue.
