### ISSUE TITLE
virtualhost wildcard fqdn (*) support

### ISSUE THREAD

**Issue by puneri78** [projectcontour/contour#5554]
**What question do you have?:**
How to support wildcard virtualhost fqdn i.e. any fqdn support which is deployed in cloud behind ALB ?
e.g. two ALBs with following DNS mapping - to use same envoy.
example.com
example.org

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
As of now I'm able to achieve this and setting fqdn virtualhost to "*" - by disabling following in FilterMisdirectedRequests
	//	if host ~= target then
	//		request_handle:respond(
	//			{[":status"] = "421"},
	//			string.format("misdirected request to %%q", host)
	//		)
	//	end

though this works just fine for usecase I have, like to know if this is valid feature request and we can add some kind of flag/header similar to authority header to support this usecase.
**Environment:**

- Contour version: 1.25

**Comment by therealak12** [comment]
Could we please reopen this issue? It's still valid.
