### ISSUE TITLE
Affinity passthrough for Envoy pods in ContourDeployment

### ISSUE THREAD

**Issue by cehoffman** [projectcontour/contour#5558]
**Please describe the problem you have**
[A clear, concise, description of the problem you are facing. What is the _problem_ that feature X would solve for you?]

The envoy pods provisioned for a Gateway setup when choosing Deployment type through the ContourDeployment parameters to the GatewayClass lack any sort of anti affinity. Since the contour pods themselves get anti affinity it would make sense the envoy pods do as well. Short of automatically setting this anti affinity, having a pass through of affinity setup from the ContourDeployment is the next best option I think.

**Comment by lubronzhan** [comment]
As discussed, there is no need to make change to the ContourDeployment API, a default anti affinity rule inside default manifest would be enough.

**Comment by davinci26** [comment]
fwiw (not that it matters) +1 on this, we also do that in production
