### ISSUE TITLE
Gateway API Conformance: Early integration of v0.8.0

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#5561]
Let's run the latest available Gateway Conformance tests against Contour to ensure we support the v0.8.0 release and can give feedback if there are any issues.

We can run against `main` or any RC tags that come up before the release for v0.8.0.

We should also enable conformance test/profile reporting.

Initially tagged with milestone 1.26.0 but may slip to 1.27.0 depending on timelines.

See milestone: https://github.com/kubernetes-sigs/gateway-api/milestone/13

**Comment by skriss** [comment]
Tried running Gateway API `main` tests against Contour `main`, ran into https://github.com/kubernetes-sigs/gateway-api/pull/2195

Otherwise looks good to me; the one failing redirect test remains.

**Comment by sunjayBhatia** [comment]
Going to pull the conformance reporting part into its own issue since it may include a longer tail of contribution/CI setup not strictly related to just bumping Gateway API version
