### ISSUE TITLE
Cleanup: Use Envoy `contains` for header routing

### ISSUE THREAD

**Issue by davinci26** [projectcontour/contour#5572]
**Please describe the problem you have**
[A clear, concise, description of the problem you are facing. What is the _problem_ that feature X would solve for you?]

In `func containsMatch(s string, ignoreCase bool) *envoy_route_v3.HeaderMatcher_StringMatch`  https://github.com/projectcontour/contour/blob/cca06915b4c3a603d87ee7857cafaba19e4bac74/internal/envoy/v3/route.go#L826

we implement it with `safe_regex` matching but we can switch to use `contains` which is the native way of envoy to do this 

See https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/matcher/v3/string.proto

**Comment by davinci26** [comment]
Any objection if I add `good first issue` label?

**Comment by sunjayBhatia** [comment]
@davinci26 sounds good to me 👍🏽, added those labels

**Comment by sunjayBhatia** [comment]
from my reading of the API the contains match should mirror what we have, this e2e should confirm: https://github.com/projectcontour/contour/blob/main/test/e2e/httpproxy/header_condition_match_test.go

**Comment by skriss** [comment]
Worth double-checking behavior for both when the header is not present on the request, xref another issue @davinci26 raised
