### ISSUE TITLE
How to set custom header for a HttpProxy for all routes

### ISSUE THREAD

**Issue by deveshk0** [projectcontour/contour#5576]
**What question do you have?:**
How to set custom header for a HttpProxy for all routes

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1,25
- Kubernetes version: (use `kubectl version`): 1.26
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by sunjayBhatia** [comment]
Looks like this was asked/answered on slack as well: https://kubernetes.slack.com/archives/C8XRH2R4J/p1690201051662899

**Comment by deveshk0** [comment]
@sunjayBhatia  yes

 As currently headers are supported either on global policy level or on each route level.
is there any plan to add support custom headers on proxy level?

**Comment by deveshk0** [comment]
Since Envoy support header based on virtual host, can we support this also? https://pkg.go.dev/github.com/envoyproxy/go-control-plane@v0.11.1/envoy/config/route/v3#VirtualHost

I happy to put a PR with little bit of guidence

**Comment by deveshk0** [comment]
@skriss PR is already open for this, can someone review this ?

**Comment by skriss** [comment]
Ack, I'll add to my review queue.

**Comment by sunjayBhatia** [comment]
Apologies, we got a bit behind reviewing the PR for this issue, bumping to 1.29.0

**Comment by rishinair11** [comment]
Is there any update on this. 
This feature would help us cleanup our HTTPProxy configuration a lot. @deveshk0 thanks for the work you have done so far.
