### ISSUE TITLE
How to reach contour ingress using tcp ports (eg-29049,29048)

### ISSUE THREAD

**Issue by san4ever** [projectcontour/contour#5583]
Hi Team,
Our apps have a requirement to reach the contour ingress using TCP ports pass through (eg29049, 29048). By default it is reaching with 443 ports. So what configuration changes needs to be done to reach the traffic to contour for TCP Ports

Thanks
Sandeep

**Comment by skriss** [comment]
@san4ever Contour's HTTPProxy API does not support generic TCP proxying on arbitrary ports. It has limited support for [TLS session proxying via TCPProxy](https://projectcontour.io/docs/1.25/config/tls-termination/#tls-session-proxying).

However, the upcoming Contour 1.26 release will support [Gateway API's TCPRoute](https://gateway-api.sigs.k8s.io/guides/tcp/), including support for adding listeners on arbitrary ports. That will probably be your best bet based on what you're describing. See https://github.com/projectcontour/contour/pull/5471 for some more information on that.
