### ISSUE TITLE
让contour支持删除cookie内的字段

### ISSUE THREAD

**Issue by carlo-zhang** [projectcontour/contour#5587]
**Please describe the problem you have**
[A clear, concise, description of the problem you are facing. What is the _problem_ that feature X would solve for you?]

I am using the Contour gateway, but I would like to delete a field in the cookie. Is there a function that can meet this requirement

**Comment by sunjayBhatia** [comment]
Take a look at the cookie rewriting feature: https://projectcontour.io/docs/1.25/config/cookie-rewriting/
