### ISSUE TITLE
Header Rewriting per service level failing with Exception RequestHeadersPolicyInvalid 

### ISSUE THREAD

**Issue by djonnadula** [projectcontour/contour#5632]
**What steps did you take and what happened:**
While applying Header Rewriting at service level specifically Host header causing HTTPProxy in invalid state. This is specifically happening in use case multiple services are routing traffic to different backend Services. 
Status:
  Conditions:
    Errors:
      Message:             rewriting "Host" header is not supported on request headers
      Reason:              RequestHeadersPolicyInvalid
      Status:              True
      Type:                ServiceError
    Last Transition Time:  
    Message:               At least one error present, see Errors for details
    Observed Generation:   1
    Reason:                ErrorPresent
    Status:                False
    Type:                  Valid
  Current Status:          invalid
  Description:             At least one error present, see Errors for details
  Load Balancer:

**What did you expect to happen:**
Host Header should be supported for Header Rewriting by service level

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: proxy
  annotations:
    kubernetes.io/ingress.class: "contour"
spec:
  virtualhost:
    fqdn: api.test.com
    tls:
      enableFallbackCertificate: true			#
     - conditions:
        - prefix: /abc
      jwtVerificationPolicy:
        disabled: true

      services:
        - name: service-v1
          port: 443
          requestHeadersPolicy:
            set:
              - name: Host
                value: api.test1.com
        - name: service-v2              
          port: 443
          requestHeadersPolicy:
            set:
              - name: Host
                value: api.test2.com

**Environment:**

- Contour version: 1.23.2
- Kubernetes version: (use `kubectl version`): 1.25.7
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: VMs
- OS (e.g. from `/etc/os-release`): Redhat8

**Comment by skriss** [comment]
@djonnadula this issue (https://github.com/projectcontour/contour/issues/4002) was fixed in Contour 1.25.0, please upgrade and try on the new version.

**Comment by skriss** [comment]
Closing this out but feel free to reach out again if you are still having issues after upgrading.
