### ISSUE TITLE
Gateway API: set Listener ResolvedRefs=true if not set to false

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5648]
ref. https://github.com/kubernetes-sigs/gateway-api/pull/2247

We need to set the Listener's ResolvedRefs=true if we haven't otherwise set it to false.

Should be similar to what we do for Accepted/Programmed -- see https://github.com/projectcontour/contour/blob/d60959ec98d46df61de6127464677fa571fd2dae/internal/dag/gatewayapi_processor.go#L435

**Comment by HeavenTonight** [comment]
mabey i can try fix this issue,thanks! /assign
