### ISSUE TITLE
One httpproxy supports multiple fqdn

### ISSUE THREAD

**Issue by yangyy93** [projectcontour/contour#5649]
Now a root http proxy supports one fqdn field, but now we have a requirement that multiple different domain names can access the same service. Now I have to create multiple root httpproxy and multiple child httpproxy to realize this function. If a root httpproxy can support multiple domain names, it can simplify a lot of configuration. [Envoy's domain itself supports multiple domain names](https://www.envoyproxy.io/docs/envoy/v1.27.0/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-virtualhost).Is it possible to consider updating fqdn as an array?

**Comment by tsaarni** [comment]
Linking (somewhat) related discussion about pluralization of `subjectName` field in `HTTPProxy` : #5520 and the API conventions doc link https://github.com/projectcontour/contour/issues/5520#issuecomment-1603414729.

**Comment by yangyy93** [comment]
Yes, implementations for singular and plural compatibility are a concern. Will you consider increasing the plural form of fqdn on this basis?
