### ISSUE TITLE
Add overload-max-heap field in contourconfig

### ISSUE THREAD

**Issue by yangyy93** [projectcontour/contour#5662]
**Please describe the problem you have**
[A clear, concise, description of the problem you are facing. What is the _problem_ that feature X would solve for you?]
I want to use [Overload Manager](https://projectcontour.io/docs/main/config/overload-manager/), but contourconfig doesn’t have this field. Is it possible to add a field `overload-max-heap`? If this field exists when configuring the envoy-initconfig container, add the startup args `--overload-max-heap`

**Comment by sunjayBhatia** [comment]
This seems reasonable to add, will add the `help wanted` label on this
