### ISSUE TITLE
Issue with enabling websockets

### ISSUE THREAD

**Issue by jacobpoly73** [projectcontour/contour#5675]
I am using Contour with Envoy on Tanzu. I have an application that needs websockets enabled. For this I created an HTTPProxy as follows:

apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: my-httpproxy
  namespace: my-ns
spec:
  routes:
  - conditions:
    - prefix: /
    **enableWebsockets: true**
    services:
    - name: sa-nginx
      port: 80
  virtualhost:
    fqdn: mysite.domain.com
    tls:
      secretName: secret-tls

However when the connection asks for an upgrade to using websockets, it receives a 403 error. 

The client shows: 
2023-08-14T19:37:40.976 ERROR! Can't handle status: ({"status-code":**403**,"status-text":" Forbidden","vary":"Accept-Encoding","date":"Mon, 14 Aug 2023 19:37:40 GMT","server":"envoy","connection":"close","content-length":"0"},"")

Envoy logs show:
[2023-08-14T19:37:26.841Z] "GET /ws/tools/join HTTP/1.1" **403** - 0 0 0 - "100.96.8.1" "-" "6b72f2d6-e8ed-4b8d-94b7-5dd13daff8b5" "mysite.domain.com" "-"

Do I need to do anything additionally to make this work? I have 3 envoy pods that are part of a daemonset. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version:
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version: v1.23.10
- Cloud provider or hardware configuration: Tanzu
- OS (e.g. from `/etc/os-release`): CentOS Linux 7 (Core)

**Comment by sunjayBhatia** [comment]
from the access log line you provided it looks like that response is coming from your application (not Envoy, shown by the lack of response flags in the access log), so a first check seems like to validate why that is occurring

**Comment by jacobpoly73** [comment]
Hi @sunjayBhatia - thanks for the response. I took a look and some other posts also seemed to show that the Response code will be empty in the case of a 403 error related to websocket upgrade (see example here https://github.com/envoyproxy/envoy/issues/27056). 

Also two questions 
- should the enablewebsockets flag work automatically? Or do I need to do anything to enable this feature beforehand?
- will the "prefix: /" cover all recursive paths or will it only work if the root url without anything trailing is used?
