### ISSUE TITLE
feat(manifests): publish manifests into github release or in website using a version number in path

### ISSUE THREAD

**Issue by davinkevin** [projectcontour/contour#5679]
Hello contour team 👋,

I would like to request for a (minor) improvement, not to project-contour itself, but to the `yaml` manifests I use to install contour. 

Currently, files are published to the website, available using the following url:

```
https://projectcontour.io/quickstart/contour.yaml
https://projectcontour.io/quickstart/contour-gateway-provisioner.yaml
```

As a consumer of them, I would like to: 
* consume past version of project contour manifests
* be able to get version targeted by a link just by reading the path

This is something already available in projects like [cert-manager](https://cert-manager.io/docs/installation/).

I don't have any preference for the technical solution, until I can download them using a simple `url` and `curl` for it, like already done for a lot of projects in my [`gitops` project](https://gitlab.com/davinkevin.fr/home-server).

**Comment by skriss** [comment]
hey @davinkevin -- check out:
- https://projectcontour.io/quickstart/v1.25.2/contour.yaml
- https://projectcontour.io/quickstart/v1.25.2/contour-gateway-provisioner.yaml

**Comment by davinkevin** [comment]
@skriss 👏, fastest resolution possible. 

Did I miss them on the website? I'll add them to my `gitops` repository right now. Feel free to close it if they are meant to stay 😇

**Comment by skriss** [comment]
I think we do reference the versioned links in a few places, but they may not be super-well documented. Regardless, they are permanent and we will have them for each new release.
