### ISSUE TITLE
list Gateway API release version in compat matrix, versions.yaml

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5728]
I was thinking maybe we should start listing GWAPI release versions instead of just the API versions, might be a little more meaningful, but can consider doing that update separately.

_Originally posted by @skriss in https://github.com/projectcontour/contour/pull/5727#discussion_r1309221817_

**Comment by skriss** [comment]
I'd like to go ahead with this, @sunjayBhatia do you see any issue with changing the format, particularly in versions.yaml? Frankly I don't really know if anyone uses versions.yaml; there's some context in https://github.com/projectcontour/contour/issues/4007 about Bitnami potentially using it for Helm chart verification but that's from two years ago so not sure if that's accurate or not. I'll dig around a little.

**Comment by sunjayBhatia** [comment]
no real issues from me, but yeah we added that for Bitnami IIRC, not sure if they are actually using that in practice
