### ISSUE TITLE
Nagle Algorithm (TCP_NODELAY) causing performance issues

### ISSUE THREAD

**Issue by harshita-meena** [projectcontour/contour#5770]
**What question do you have?:**
I have been seeing issues with performance of some services at low RPS and feel it might be related t[o Nagle algorithm ](https://github.com/projectcontour/contour/blob/5b564bc97cd37b57710225e3d3cdbefeba16293a/site/content/docs/1.26/guides/cert-manager.md?plain=1#L640)being enabled. Is there a way in contour we can control this particular parameter ? Or if you know it is enabled right now. 

When i run curl on the lb proxy ip, it does not show me TCP_NODELAY set. 
![Screen Shot 2023-09-20 at 12 34 47 PM](https://github.com/projectcontour/contour/assets/70981082/0d1430e1-467b-43a1-b30c-edfa90f85f37)

**Environment:**

- Contour version: 1.27
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5-gke.200", GitCommit:"f9aad8e51abb509136cb82b4a00cc3d77d3d70d9", GitTreeState:"clean", BuildDate:"2023-08-26T23:26:22Z", GoVersion:"go1.20.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.27) exceeds the supported minor version skew of +/-1
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`): NAME="CentOS Linux"

**Comment by sunjayBhatia** [comment]
The output you link to is coming from `curl`, you can control the TCP_NODELAY setting on the socket curl uses with the flag `--tcp-nodelay` (see https://curl.se/docs/manpage.html)

Contour does not set the TCP_NODELAY option Envoy's outbound sockets

**Comment by harshita-meena** [comment]
Thankyou @sunjayBhatia , that make sense. I realized that later while looking for other parameters to tune in contour. Is there any other way to set TCP_NODELAY  for  envoy's outbound sockets ? or is it not possible ?

**Comment by sunjayBhatia** [comment]
Off the top of my head I don't think there is anywhere in Envoy's APIs where you can set arbitrary socket options on upstream sockets via cluster config or transport socket config:
- https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto
- https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/transport_socket/transport_socket

**Comment by harshita-meena** [comment]
Thankyou for confirming!
