### ISSUE TITLE
Readiness probe failed

### ISSUE THREAD

**Issue by yannrenarddav** [projectcontour/contour#5771]
Hello,

We regularly have pods which are in error and which do not restart correctly. The only solution remains to delete the pod.

  Warning  Unhealthy  37m (x29 over 39h)     kubelet  Readiness probe failed: Get "http://10.200.6.5:8002/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  32m (x12 over 39h)     kubelet  Liveness probe failed: Get "http://10.200.6.5:8090/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  2m1s (x1396 over 94m)  kubelet  Readiness probe failed: HTTP probe failed with statuscode: 503

The issue happen more and more, recreating the pod can't be a solution. How can I fix the issue ? Is there any logs I can check to have more information about what happen ?

Kubernetes version is 1.24.14
Contour version is 1.23.6 

The same issue was already present with previous version of kubernetes and contour. 

Regards.

**Comment by skriss** [comment]
https://projectcontour.io/docs/1.26/troubleshooting/envoy-container-draining/ has some suggestions that may help

**Comment by PSanetra** [comment]
I experience this issue on the envoy pods, too. Usually the envoy `/ready` endpoint returns a valid response within `< 100ms`, but sometimes its response time takes over `5 seconds`. I am not sure why.

**Comment by skriss** [comment]
https://github.com/projectcontour/contour/issues/4540 may be at play here
