### ISSUE TITLE
How to use TCPRoute by Contour

### ISSUE THREAD

**Issue by walleliu1016** [projectcontour/contour#5777]
**What question do you have?:**
I want to use TCPRoute, to forward the traffic to zookeeper pods, but failed after create the Gateway and TCPRoute, cannot create Gateway without any error message.
After read the docs: [https://projectcontour.io/docs/1.26/config/gateway-api/](https://projectcontour.io/docs/1.26/config/gateway-api/), i found something below:
![捕获](https://github.com/projectcontour/contour/assets/8541378/f9d35238-57c7-4624-87e6-62e7a5ba0b69)

So, if i want to use Contour TCPRoute, i must to deploy Contour with **_Dynamic provisioning_**, not **_Static provisioning_**.

Thanks a lot.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: v1.26.0
- Kubernetes version: (use `kubectl version`): v1.28
- Kubernetes installer & version: 
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
@walleliu1016 it will definitely be easier to use TCPRoute if you use dynamic provisioning, since the provisioner will take care of setting up Service ports to expose your routes. However, it should be possible with static provisioning too -- you will just need to manually edit the Envoy service to add the port. Note that there is a mapping scheme between the Listener/Service port, and the container port that Envoy will listen on -- see https://projectcontour.io/docs/1.26/config/gateway-api/#gateway-listeners. So, for example, if want to expose your TCPRoute on port 10000, then the service port should be 10000, and the container port should be 18000.

**Comment by walleliu1016** [comment]
> @walleliu1016 it will definitely be easier to use TCPRoute if you use dynamic provisioning, since the provisioner will take care of setting up Service ports to expose your routes. However, it should be possible with static provisioning too -- you will just need to manually edit the Envoy service to add the port. Note that there is a mapping scheme between the Listener/Service port, and the container port that Envoy will listen on -- see https://projectcontour.io/docs/1.26/config/gateway-api/#gateway-listeners. So, for example, if want to expose your TCPRoute on port 10000, then the service port should be 10000, and the container port should be 18000.

thanks for your reploy.

**Comment by walleliu1016** [comment]
> @walleliu1016 it will definitely be easier to use TCPRoute if you use dynamic provisioning, since the provisioner will take care of setting up Service ports to expose your routes. However, it should be possible with static provisioning too -- you will just need to manually edit the Envoy service to add the port. Note that there is a mapping scheme between the Listener/Service port, and the container port that Envoy will listen on -- see https://projectcontour.io/docs/1.26/config/gateway-api/#gateway-listeners. So, for example, if want to expose your TCPRoute on port 10000, then the service port should be 10000, and the container port should be 18000.

hi, i have read the provisioning code in :https://github.com/projectcontour/contour/blob/main/internal/provisioner/objects/dataplane/dataplane.go#L276
Contour crd will create contourcontrolplane container and dataplane container, but i does not find any example about Contour crd in the example. 
So it's missing?

**Comment by walleliu1016** [comment]
I want to deploy multiple contour + envoy, and each envoy has different cpu and memory resource, for instance, some envoy will handle large flow, need more cpu and memory.
