### ISSUE TITLE
Enable statistics for remaining_ in Envoy

### ISSUE THREAD

**Issue by nageshs28** [projectcontour/contour#5794]
**What question do you have?:**
I want to see how circuit breakers are performing to tune it.
So need to enable track_remaining in Envoy via Contour proxy or annotations

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
<img width="955" alt="image" src="https://github.com/projectcontour/contour/assets/46618911/e536e1b5-0a6c-4b2b-8fbb-5c2914740495">

**Environment:**

- Contour version: 1.25.0
- Kubernetes version: (use `kubectl version`): 1.26.0
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`):

**Comment by sunjayBhatia** [comment]
Seems like a reasonable request, changing tags to a feature request.

Here is a link to the field that enables this: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/circuit_breaker.proto#envoy-v3-api-field-config-cluster-v3-circuitbreakers-thresholds-track-remaining

**Comment by Akhil-2001** [comment]
Hey @sunjayBhatia I'd like to tackle this. Could you give me some background as to where the changes need to be made?

**Comment by sunjayBhatia** [comment]
There are a couple places where we configure circuit breaker thresholds:
- https://github.com/projectcontour/contour/blob/b865f33cb5f10e082e3cfbc9a0a54bb6c3a3ff18/internal/envoy/v3/cluster.go#L82-L89
- https://github.com/projectcontour/contour/blob/b865f33cb5f10e082e3cfbc9a0a54bb6c3a3ff18/internal/envoy/v3/bootstrap.go#L220-L234

As far as I know, it should be as simple as setting the linked field above to true and fixing up the required tests

**Comment by sunjayBhatia** [comment]
Let me know if you would like to be assigned @Akhil-2001, thanks!

**Comment by Akhil-2001** [comment]
@sunjayBhatia Thanks a lot for the context! I would like to work on this, please assign it to me.
