### ISSUE TITLE
site: Netlify "Mixed Content" action not running

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#5796]
**What steps did you take and what happened:**

See this PR: https://github.com/projectcontour/contour/pull/5790

The "Mixed Content" Netlify action is not running and is stuck in "Expected" status

<img width="874" alt="Screenshot 2023-10-02 at 10 36 59 AM" src="https://github.com/projectcontour/contour/assets/5337253/c8d2aef1-1c09-4a2d-a93d-160b86d043c4">

This is blocking PRs from being merged by the auto-merge feature since all the required checks do not run/succeed.

**What did you expect to happen:**

The action runs successfully or is removed if needed.

**Anything else you would like to add:**

I can't log in to the Netlify to look at the settings for the projectcontour site. Bumped Hugo here but that is not the issue: https://github.com/projectcontour/contour/pull/5795

Github Actions and netlify deploy logs don't seem to hold any clues:
- https://github.com/projectcontour/contour/pull/5790/checks?check_run_id=17315740343
- https://app.netlify.com/sites/projectcontour/deploys/651ac5052091c200074aa1f0

**Environment:**

N/A

**Comment by skriss** [comment]
I dropped it as a required check from branch protection rules for now, so it's not blocking PRs. Unfortunately I don't have access to Netlify either.

**Comment by sunjayBhatia** [comment]
> I dropped it as a required check from branch protection rules for now, so it's not blocking PRs. Unfortunately I don't have access to Netlify either.

Ah nice, I think we can close this then, that looks like it fixed the stalled actions on https://github.com/projectcontour/contour/pull/5797 and others

Didn't realize the actions settings were in the Branches section 👀
