### ISSUE TITLE
clarify logic in endpointstranslator.go 

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5800]
ref. https://github.com/projectcontour/contour/pull/5745#discussion_r1334684738
ref. https://github.com/projectcontour/contour/blob/7feb49e86b3598e78421f6afe249ff6740cd6d9b/internal/xdscache/v3/endpointstranslator.go#L57
ref. https://github.com/projectcontour/contour/pull/5745#discussion_r1344514952

This line, and the (soon-to-be-merged) same line in endpointslicetranslator.go, could be rewritten for clarity. I'd suggest possibly breaking it into multiple independent short-circuits.

**Comment by xiangpingjiang** [comment]
@skriss 
hello, Kriss, I would like to work on this issue. Can you please assign me?

**Comment by skriss** [comment]
Sure, I would suggest waiting until #5745 is merged though, so it can be addressed in both places at the same time.
