### ISSUE TITLE
use EndpointSlices by default

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5891]
#5745 added opt-in support for EndpointSlices. This issue is to switch to using EndpointSlices by default, once #5745 has been sufficiently validated.

Adding this to 1.28 milestone but can always be pushed out if needed.

**Comment by izturn** [comment]
i'd like to work on it

**Comment by skriss** [comment]
@davinci26 @clayton-gonsalves it'd be great to get an update from you all on using EndpointSlices - have you had any issues we need to know about before flipping it to be the default?

**Comment by davinci26** [comment]
We have been using it in production for a while with no issues.

We also noticed significant cpu reduction before and after we deployed the change in the controller when parsing large deployments

**Comment by skriss** [comment]
We're going to move this to 1.29, so we've got a full release cycle to run CI etc. with the new default.
