### ISSUE TITLE
upload file with status code 0 downstream_remote_disconnect

### ISSUE THREAD

**Issue by yziane** [projectcontour/contour#5895]
We have a mobile app that uploads video files to an API on our vSphere Tanzu Kubernetes cluster. When users are on a 4G connection, we encountered some issues with file uploads. The logs indicate a status code of 0 and 'downstream_remote_disconnect.'

The mobile app development team conducted a test using Nginx Ingress and resolved the issue by setting 'proxy_request_buffering: off.'

I've been searching for the equivalent option in Contour, and it appears that 'per_connection_buffer_limit_bytes' might be the equivalent setting. Is it possible to disable this option? If so, can we achieve this by adding an annotation like the following?"

**Environment:**

- Contour version: 1.22.1
- Kubernetes version: (use `kubectl version`): 1.23
- Kubernetes installer & version: v1.23.8+vmware.3
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
@yziane Contour added the ability to configure this setting in 1.26, for both Listeners and Clusters (https://github.com/projectcontour/contour/pull/5513 and https://github.com/projectcontour/contour/pull/5493) -- see the docs at https://projectcontour.io/docs/1.26/configuration/#listener-configuration and https://projectcontour.io/docs/1.26/configuration/#cluster-configuration

**Comment by yziane** [comment]
Thank you @skriss
