### ISSUE TITLE
Add RetryPolicy in ExtensionServiceSpec

### ISSUE THREAD

**Issue by jerome-quere** [projectcontour/contour#5910]
Hello,

I'm using Contour with an ExtensionService to manage authentication. I have an average load of 500 req/s. I'm experiencing an issue where, on some occasions, the connection to the authentication service is reset/closed by Envoy, resulting in the original request failing with a PERMISSION_DENIED error. This is not ideal for downstream services. 

This issue almost always coincides with an Envoy cx destroy event. 

<img width="2934" alt="Screenshot 2023-10-30 at 14 23 25" src="https://github.com/projectcontour/contour/assets/526046/24ec66d1-a2ee-4a1f-b40a-f3335f8c1e66">

Since network connections are never 100% stable what should we do to handle such errors and avoid returning a PERMISSION_DENIED error.

I'm wondering if it would be possible to add a `RetryPolicy` in the `ExtensionServiceSpec` to handle this type of situation.

**Comment by skriss** [comment]
@jerome-quere that sounds reasonable, would you be interested in contributing a change here?

**Comment by sunjayBhatia** [comment]
Unrelated to the topic at hand but great to see users diagnosing issues using Envoy's stats output, if youre interested in contributing in this area too please let us know! Here's another issue that would be great to get some user input on: https://github.com/projectcontour/contour/issues/5655

**Comment by davinci26** [comment]
Is this supported by envoy? iiuc envoy doesnt support retries for ext-auth services https://github.com/envoyproxy/envoy/issues/17918

**Comment by jerome-quere** [comment]
I think it should be possible via:

[extension-envoy-filters-http-ext-authz](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#extension-envoy-filters-http-ext-authz).grpc_service.envoy_grpc.retry_policy setting

**Comment by davinci26** [comment]
Ty for the pointer. The docs document this field as:

>  Indicates the retry policy for re-establishing the gRPC stream

I read this as a `tcp` level retry which only retries on stream establishment whereas Contour `Retry` policy is a more generic retry policy.

I think it might be confusing for the user to expose the entire `RetryPolicy` object knowing that it is supported with many asterisks.
