### ISSUE TITLE
Gateway API: update docs and examples for v1 API version

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5919]
GatewayClass, Gateway and HTTPRoute will move to `v1` as of Gateway API 1.0. This issue is to update relevant documentation and examples to use that API version, where applicable.

- e.g. https://projectcontour.io/docs/main/config/gateway-api/
- e.g. https://projectcontour.io/docs/main/guides/gateway-api/

**Comment by izturn** [comment]
i'd like to work on this
