### ISSUE TITLE
Gateway API: fix for failing GatewayWithAttachedRoutes conformance test

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5920]
As of Gateway API v1.0.0-rc2, the GatewayWithAttachedRoutes conformance test has started failing. This is related to how attached routes are counted when a Gateway is invalid. ref. https://github.com/kubernetes-sigs/gateway-api/pull/2477

**Comment by izturn** [comment]
i'd like to work on it

**Comment by sunjayBhatia** [comment]
looks like there is some work upstream going on for this test: https://github.com/kubernetes-sigs/gateway-api/pull/2548

**Comment by sunjayBhatia** [comment]
Recent history on this test follows these PRs:
- https://github.com/kubernetes-sigs/gateway-api/pull/2477
- https://github.com/kubernetes-sigs/gateway-api/pull/2535
- https://github.com/kubernetes-sigs/gateway-api/pull/2548
