### ISSUE TITLE
ExtensionService should support client certificates

### ISSUE THREAD

**Issue by jroper** [projectcontour/contour#5924]
ExtensionServices may not want to accept calls from anything, they may want to authorize the calls. One way to do this would be to allow the configuration of a client certificate when configuring an extension service.

**Comment by tsaarni** [comment]
Hi @jroper!  Did you check [Envoy Client Certificate](https://projectcontour.io/docs/v1.17.1/config/upstream-tls/#envoy-client-certificate). I believe it should work for extension service too.
