### ISSUE TITLE
update endpoint slice E2E to use require.Eventually(...) instead of fixed sleeps

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5974]
I've seen the endpoint slice E2E flake a few times recently. Upon review, https://github.com/projectcontour/contour/blob/main/test/e2e/infra/endpointslice_test.go#L63-L99 is using fixed 10-second sleeps to wait for convergence, which can be fragile. Typically we use `require.Eventually` or similar constructs to handle these situations. This should make the test less likely to flake.

**Comment by sunjayBhatia** [comment]
ah yeah missed this in the review of the e2e tests, makes sense +1
