### ISSUE TITLE
Support standard Forwarded header

### ISSUE THREAD

**Issue by PSanetra** [projectcontour/contour#5991]
As far as I can see the ingess controller currently just supports the "non-standard" X-Forwarded-* headers. It would be nice to support also the standard [Forwarded header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded).

Use case
Keycloak has added support for the Forwarded header with version [21.0.0](https://www.keycloak.org/2023/02/keycloak-2100-released.html#_support_for_the_standard_forwarded_header_when_running_behind_a_reverse_proxy) and advices reverse-proxies to override this header.

Support in the nginx ingress controller is currently added, too: https://github.com/kubernetes/ingress-nginx/pull/10322

**Comment by tsaarni** [comment]
I think this would rather be a request for Envoy as also the existing `X-forwarded-*` logic is implemented there. 

With a quick glance at the proposed NGINX approach, it seems to use configuration approach, with some limitations mentioned in the warning of the [wiki article](https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/).

I think proper parsing would rather be done in C++ in Envoy.

As pointer for those who are looking for the workaround: overriding the header can be done using [request rewriting](https://projectcontour.io/docs/1.27/config/request-rewriting/): (1) use `httpproxy.spec.routes.requestHeadersPolicy.remove` to remove `Forwarded` header, or alternatively, maybe attempt to trivially (2) use `requestHeadersPolicy.set` to set the header to `for=%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%` ([link](https://projectcontour.io/docs/1.27/config/request-rewriting/#dynamic-header-values))

Coincidentally , I've written an issue for Keycloak https://github.com/keycloak/keycloak/issues/23431 😅

**Comment by PSanetra** [comment]
Thank you @tsaarni for that suggestion!

I think I will set that header in the bitnami Helm chart globally like this:
```yaml
configInline:
  policy:
    request-headers:
      set:
        Forwarded: "for=%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%;host=%REQ(Host);proto=%PROTOCOL%"
```
