### ISSUE TITLE
Support override the defaults for `circuit breakers`

### ISSUE THREAD

**Issue by davinci26** [projectcontour/contour#6001]
The way https://projectcontour.io/docs/1.27/config/annotations/ work right now is that if they are not set in the service annotations as expected then they are not set letting Envoy default them.

```
	if envoy.AnyPositive(service.MaxConnections, service.MaxPendingRequests, service.MaxRequests, service.MaxRetries) {
		cluster.CircuitBreakers = &envoy_cluster_v3.CircuitBreakers{
			Thresholds: []*envoy_cluster_v3.CircuitBreakers_Thresholds{{
				MaxConnections:     protobuf.UInt32OrNil(service.MaxConnections),
				MaxPendingRequests: protobuf.UInt32OrNil(service.MaxPendingRequests),
				MaxRequests:        protobuf.UInt32OrNil(service.MaxRequests),
				MaxRetries:         protobuf.UInt32OrNil(service.MaxRetries),
			}},
		}
	}
```

This works great but in bigger clusters the Envoy default might not be good enough. Then it is becomes the responsibility of every service owner to set the annotations in their service correctly which can be error prone.

We would like to add a `global` default such that we can perform logic in the form of `service.MaxConnections` or `GlobalDefault`

**Comment by davinci26** [comment]
This is a bit more long term but related we should bring those into the `HTTPProxy` CRD, it feels like they are annotations due to legacy reasons

**Comment by therealak12** [comment]
Also, solves https://github.com/projectcontour/contour/issues/1192. Doesn't it?
