### ISSUE TITLE
multiple fqdn on virtualhost how?

### ISSUE THREAD

**Issue by balagitid** [projectcontour/contour#6064]
**What question do you have?:**
multiple fqdn on virtualhost how?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
How to achieve multiple fqdn? looking something like ..as like istio service mesh virtual service.

apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kubeapp-proxy
  namespace: dev
spec:
  virtualhost:
    fqdn:
       "kubeapp.dev.kubelancer.net"
       "localhost"
  routes:
    - conditions:
      - prefix: /
      services:
        - name: kubeapp
          port: 80 

**Environment:**

- Contour version:
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
@balagitid see https://projectcontour.io/docs/1.27/config/virtual-hosts/, in particular the "Virtualhost Aliases" section, for how to accomplish this in Contour.

**Comment by balagitid** [comment]
Hi @skriss ,

Thanks, instead of creating multiple roots for each HTTPProxy, Do we make as array list out all allowed hosts in single HTTPProxy. 

`apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: name-example-foo
  namespace: default
spec:
  virtualhost:
    fqdn:
     - example.com
     - stable.example.com
     - latest.example.com
  routes:
    - services:
      - name: s1
        port: 80`

**Comment by skriss** [comment]
No, that is not supported in HTTPProxy. You need to use the multiple roots approach.
