### ISSUE TITLE
Consider aligning how SNI is set for upstream TLS 

### ISSUE THREAD

**Issue by tsaarni** [projectcontour/contour#6098]
Currently Contour uses SNI for upstream TLS connection in following ways:

* `httpproxy`: SNI is not set by default. It is set if (1) user defines `requestHeadersPolicy` with key [`Host`](https://projectcontour.io/docs/1.27/config/api/#projectcontour.io/v1.HeadersPolicy) or if (2) the referred `Service` is of type `ExternalName` and external name services are enabled
(see [logic here](https://github.com/projectcontour/contour/blob/61b6fae59b3262058b666337cc1fb8d12b0fa1a6/internal/dag/httpproxy_processor.go#L1601-L1620)).
* `tcpproxy`: SNI is not set (see issue #4373).
* `extensionservice`: SNI is set if validation is enabled. Value is set from [`extensionservice.spec.validation.subjectName`](https://github.com/projectcontour/contour/blob/main/internal/dag/extension_processor.go#L170-L177), or `subjectNames[0]` in the next release.
* `ingress`: SNI or upstream validation is not supported ([see code](https://github.com/projectcontour/contour/blob/1987eaccdf4ada19cb63a428a17e0fc7feb03b97/internal/dag/ingress_processor.go#L297-L307)).
* Gateway API: (1) [`HTTPRoute`](https://github.com/projectcontour/contour/blob/1987eaccdf4ada19cb63a428a17e0fc7feb03b97/internal/dag/gatewayapi_processor.go#L2034-L2043) supports upstream TLS (it sets `Cluster.Protocol`) but does not support SNI or validation (it does not set `Cluster.[SNI|UpstreamValidation]`), (2) [`TLSRoute`](https://github.com/projectcontour/contour/blob/1987eaccdf4ada19cb63a428a17e0fc7feb03b97/internal/dag/gatewayapi_processor.go#L1018-L1025) does not seem to support upstream TLS,  but still sets `Cluster.SNI` which has no effect without upstream TLS, (3) [`GRPCRoute`](https://github.com/projectcontour/contour/blob/1987eaccdf4ada19cb63a428a17e0fc7feb03b97/internal/dag/gatewayapi_processor.go#L2121-L2130) supports upstream TLS but does not support SNI or validation, (4) [`TCPRoute`](https://github.com/projectcontour/contour/blob/1987eaccdf4ada19cb63a428a17e0fc7feb03b97/internal/dag/gatewayapi_processor.go#L1705-L1712) does not seem to support upstream TLS but still sets `SNI` field. 

It would be nice if SNI was set by default, and if the default behaviour was aligned between all above cases (this does not imply removing current behaviour).

One alternative could be to use the subjectAltName from `validation` in all cases, that is, align the defaults with current `extensionservice` behaviour.  Sometimes the validation context is omitted and SNI would not get set. 

Usually SNI is set to the hostname that the client is connecting to, that is, if service name is 'foo', then SNI is set to `foo`. This is the behaviour that all TLS client applications usually implement, and is expected by [RFC6066](https://datatracker.ietf.org/doc/html/rfc6066#page-6)

> "HostName" contains the fully qualified DNS hostname of the server, as understood by the client.

This also aligns with current `ExternalName` behaviour.

One option could be to use subject alternative name from `validation.subjectName` when present, but fall back to service hostname when it is not configured and for resource types that do not support it.

**Comment by skriss** [comment]
xref https://github.com/projectcontour/contour/issues/2893
