### ISSUE TITLE
test/e2e: Test Upstream TLS settings with Gateway API Routes

### ISSUE THREAD

**Issue by christianang** [projectcontour/contour#6140]
From #6119, We would like to test upstream TLS i.e BackendTLSPolicy with Gateway API Routes in an e2e test to ensure that Contour has wired up everything correctly. E.g to cover the Gateway processor being wired up properly in serve.go.

**Comment by christianang** [comment]
@sunjayBhatia revisiting this issue. Did we already accomplish this task via https://github.com/projectcontour/contour/pull/6119#discussion_r1468123241. Looking at the test I see that it does check the upstream tls version here:

https://github.com/projectcontour/contour/blob/bc8994801c57fe8c5e611c2a5b3fe2435c292b27/test/e2e/gateway/backend_tls_policy_test.go#L184-L187

Or was there more to this issue.

**Comment by sunjayBhatia** [comment]
We could also add a check similar to https://github.com/projectcontour/contour/blob/main/test/e2e/httpproxy/backend_tls_test.go where we check the right client cert is sent when contour/envoy are configured with a client cert for upstream TLS

Can do this via an e2e test but I think a featuretests "integration" test should also work fine if one doesn't exist for BackendTLSPolicy in this context
