### ISSUE TITLE
Validate Cluster Name generation won't run into duplicate cluster names with BackendTLSPolicy

### ISSUE THREAD

**Issue by christianang** [projectcontour/contour#6141]
From #6119, there is some concern with: https://github.com/projectcontour/contour/blob/31a5bb24de6b98549b405749aeffe9d32d8e9c6f/internal/envoy/cluster.go#L50-L55

Quote from @sunjayBhatia in https://github.com/projectcontour/contour/pull/6119#discussion_r1468124988:
> hm i wonder if we could run into some issues here with duplicate cluster names for when the same cluster is referenced in different places that have different backend tls settings, adding as a follow up

We'd like to validate there aren't issue with what is occurring here or if there are open a PR to fix it.

**Comment by christianang** [comment]
> hm i wonder if we could run into some issues here with duplicate cluster names for when the same cluster is referenced in different places that have different backend tls settings, adding as a follow up

Thinking about this again. I think because a BackendTLSPolicy targets a service, which is what is translated into an envoy cluster, then it shouldn't be possible to have the same cluster with different backend tls settings, but if I'm missing something let me know.

**Comment by sunjayBhatia** [comment]
> > hm i wonder if we could run into some issues here with duplicate cluster names for when the same cluster is referenced in different places that have different backend tls settings, adding as a follow up
> 
> Thinking about this again. I think because a BackendTLSPolicy targets a service, which is what is translated into an envoy cluster, then it shouldn't be possible to have the same cluster with different backend tls settings, but if I'm missing something let me know.

Yeah this makes a lot of sense in the context of only using Gateway API

where we might run into trouble is if we're using a combination of GW API and HTTPProxy but targeting the same service with an HTTPRoute/BackendTLSPolicy and HTTPProxy

currently we don't have a lot of testing/logic around migrating from one type of config to another, but this could become an issue in the future

**Comment by christianang** [comment]
> Yeah this makes a lot of sense in the context of only using Gateway API
>
> where we might run into trouble is if we're using a combination of GW API and HTTPProxy but targeting the same service with an HTTPRoute/BackendTLSPolicy and HTTPProxy
>
> currently we don't have a lot of testing/logic around migrating from one type of config to another, but this could become an issue in the future

Right, didn't think about the interaction between HTTPProxy and HTTPRoute, makes sense to test this behavior.
