### ISSUE TITLE
Minor improvement: Replacing existing ref package with k8s.io/utils/ptr

### ISSUE THREAD

**Issue by lubronzhan** [projectcontour/contour#6163]
Upstream already has a helper function to get pointer of an object.
We can just use the upstream one and get rid of our existing ref package https://github.com/projectcontour/contour/tree/main/internal/ref

**Comment by tsaarni** [comment]
I think it was previously used via `k8s.io/utils/pointers` but it was replaced with internal package https://github.com/projectcontour/contour/pull/4930.  Since then, direct dependency to `k8s.io/utils` is back though.

**Comment by lubronzhan** [comment]
IC, their implementation was improved after to use generic type
Now just `ptr.To()`

**Comment by sunjayBhatia** [comment]
we originally got rid of it so we could use our own generic form but now the generic one exists idk if its worth carrying our own? the utils package looks like it will be indirectly imported anyway even if we don't use it so might as well reduce duplication
