### ISSUE TITLE
How to tune max_request_bytes

### ISSUE THREAD

**Issue by rgarrigue** [projectcontour/contour#6178]
**What question do you have?:**

I'ld like to increase the allowed request size for a given endpoint. How can I do that ? 

Reason is a company profile creation endpoint where a couple of logos can be around 20Mb, which is above the default of Envoy's max_request_bytes I believe.

**Anything else you would like to add:**

Although I'ld like to specify this at the httpproxy level, I can settle down for a global setting until a better solution.

**Environment:**

- Contour version:  docker.io/bitnami/contour:1.26.0-debian-11-r0'
- Kubernetes version: (use `kubectl version`): v1.27.9-eks-5e0fdde
- Kubernetes installer & version: EKS
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): ?

**Comment by rgarrigue** [comment]
To be even clearer, I'ld like an equivalent of Nginx Ingress Controller's

>     nginx.ingress.kubernetes.io/proxy-body-size: 128m

**Comment by tsaarni** [comment]
xref #6315
