### ISSUE TITLE
Spawn Upstream Span when Tracing is enabled

### ISSUE THREAD

**Issue by SamMHD** [projectcontour/contour#6270]
As described in [Envoy documentations](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-tracing), when tracing is enabled and envoy is working as an independent proxy, It's better to set ```spawn_upstream_span``` to true and that seems reasonable because mostly when we are using envoy with Contour we would like to see it's tracing spans as an independent hop in tracing records.

Right now it is something like this:
<img width="332" alt="Screenshot 1402-12-25 at 00 30 58" src="https://github.com/projectcontour/contour/assets/46444723/54864458-22f7-4f45-aa02-8ea52ed6f48b">

So contour managed envoy spans will be at same level as the upstream spans are because both upstream and envoy are using same parent span. So I think it's more convenient to spawn a new span for upstream to show this service hop in request traces.

**Comment by SamMHD** [comment]
I'll be happy to hear your opinions on it.

**Comment by sunjayBhatia** [comment]
Yep that sounds totally reasonable to me +1 to adding that

**Comment by sunjayBhatia** [comment]
Looks like you've started a PR @SamMHD, thanks! I'll assign this issue to you as well

**Comment by SamMHD** [comment]
Thank you @sunjayBhatia for your review. I'll fix the issues with the PR.
