### ISSUE TITLE
Contour does not get ready when routing config is not present

### ISSUE THREAD

**Issue by Zsolt-LazarZsolt** [projectcontour/contour#6291]
**What steps did you take and what happened:**
Non leader contour process never gets ready when there is no configuration.

If Contour is installed in a near empty cluster, for example a new kind cluster, without the following:
secrets of the right kind (tls or opaque with CA-s)
any ingress or HTTPProxy

Two contour pods start up. The one which does not become the leader does not get ready ever.
This only changes if a secret of the right kind or ingress/HTTPProxy is added to the cluster.

Easiest way to reproduce: take the original rendered yaml:

https://raw.githubusercontent.com/projectcontour/contour/main/examples/render/contour.yaml

kubectl create ns new

use the watch namespace functionality by adding the line to the contour parameters - "--watch-namespaces=new"
Apply the modified yaml.

Output will be the following:

`kubectl get pods -n projectcontour 

NAME                       READY   STATUS    RESTARTS   AGE
contour-777f8d6f76-htws8   0/1     Running   0          3m59s
contour-777f8d6f76-k7fck   1/1     Running   0          3m59s
envoy-wkvsh                2/2     Running   0          3m59s
`
 
Apply any HTTPProxy to the new namespace and soon the non leader Contour becomes ready.

**What did you expect to happen:**
Both Contour instances to become ready.

**Anything else you would like to add:**
Alternatively it is possible it is possible to start a fresh kind cluster,
 modify the rendered yaml to run contour insecure and remove the job creating secrets
 and reach the same result without using the watch-namespace functionality.
 
 example kind cluster config:
 `
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: simulator
nodes:
- role: control-plane
- role: worker
`

Dropping an install yaml for convenience:
- removed certgen (created certs hide the issue)
- removed envoy
- set contour to run as insecure
[insecure_mini_config.txt](https://github.com/projectcontour/contour/files/14650137/insecure_mini_config.txt)

Tested 1.26.0 It does not have the same issue 

**Environment:**

- Contour version: 1.27.0 - main
- Kubernetes version: (use `kubectl version`): v1.25.4
- Kubernetes installer & version: v1.25.3

**Comment by tsaarni** [comment]
I was confused in initial analysis above: lease object does not need to be in watched namespaces. I think adding the namespace to watched namespaces helped only because `projectcontour` namespace happened to have some secrets that then triggered the startup logic (and therefore worked around the bug).
