### ISSUE TITLE
support httproute to set annotation with "projectcontour.io/response-timeout"

### ISSUE THREAD

**Issue by Bryce-huang** [projectcontour/contour#6310]
**Please describe the problem you have**
[A clear, concise, description of the problem you are facing. What is the _problem_ that feature X would solve for you?]

The annotation is **"projectcontour.io/response-timeout"** only support ingress

```go
var annotationsByKind = map[string]map[string]struct{}{
	"Ingress": {
		"ingress.kubernetes.io/force-ssl-redirect":       {},
		"kubernetes.io/ingress.allow-http":               {},
		"kubernetes.io/ingress.class":                    {},
		"projectcontour.io/ingress.class":                {},
		"projectcontour.io/num-retries":                  {},
		"projectcontour.io/response-timeout":             {},
		"projectcontour.io/retry-on":                     {},
		"projectcontour.io/tls-minimum-protocol-version": {},
		"projectcontour.io/tls-maximum-protocol-version": {},
		"projectcontour.io/tls-cert-namespace":           {},
		"projectcontour.io/websocket-routes":             {},
	},
	"Service": {
		"projectcontour.io/max-connections":       {},
		"projectcontour.io/max-pending-requests":  {},
		"projectcontour.io/max-requests":          {},
		"projectcontour.io/max-retries":           {},
		"projectcontour.io/upstream-protocol.h2":  {},
		"projectcontour.io/upstream-protocol.h2c": {},
		"projectcontour.io/upstream-protocol.tls": {},
	},
	"HTTPProxy": {
		"kubernetes.io/ingress.class":     {},
		"projectcontour.io/ingress.class": {},
	},
	"Secret": {
		"projectcontour.io/generated-by-version": {},
	},
}
```

**Comment by tsaarni** [comment]
Hi @Bryce-huang! 

The Gateway API uses [different mechanism](https://gateway-api.sigs.k8s.io/geps/gep-1742/) for setting timeouts. 

Did you check this feature https://github.com/projectcontour/contour/releases/tag/v1.28.0 

> Gateway API: support HTTPRoute request timeouts
>
> Contour now enables end-users to specify request timeouts by setting the [HTTPRouteRule.Timeouts.Request] (https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPRouteTimeouts) parameter. Note that BackendRequest is not yet implemented because without Gateway API support for retries, it's functionally equivalent to Request.

**Comment by Bryce-huang** [comment]
Thanks,I use v1beta1,maybe need migrate to v1
