### ISSUE TITLE
Migrate HTTPProxy to HTTPRoute

### ISSUE THREAD

**Issue by musklor** [projectcontour/contour#6354]
Thanks a lot for your work.

I'd like to migrate from httpproxy to httproute.

Do you know how i can do that?

I need hsts (Content-Security-Policy), rewrite caldav for nextcloud and Permissions-Policy.

apiVersion: projectcontour.io/vi
kind: HTTPProxy
metadata:
  name: example
spec:
  virtualhost:
    fqdn: example.com
  routes:
  - services:
    - name: app
      port: 80
      responseHeadersPolicy:
        set:
        - name: Content-Security-Policy
          value: "default-src 'self'"
        - name: Strict-Transport-Security
          value: max-age=31536000; includeSubDomains

**Comment by musklor** [comment]
For HSTS, maybe

filters:
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        add:
        - name: X-Header-Add-1
          value: header-add-1
        - name: X-Header-Add-2
          value: header-add-2
        - name: X-Header-Add-3
          value: header-add-3

**Comment by musklor** [comment]
Maybe I can use ingress2gateway

**Comment by sunjayBhatia** [comment]
we do intend to support converting Ingresses and HTTPProxies to Gateway API resources in the ingress2gateway project, however have not had a chance to contribute that work yet, take a look at the tracking issue: https://github.com/kubernetes-sigs/ingress2gateway/issues/143
