### ISSUE TITLE
Gateway API: 0s timeout should disable the timeout

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#6373]
ref. https://github.com/kubernetes-sigs/gateway-api/blob/v1.0.0/apis/v1/httproute_types.go#L277

ref. https://github.com/kubernetes-sigs/gateway-api/pull/2823

**Comment by dprotaso** [comment]
Is it possible to cherry pick this to v1.28.x (if it's convenient)?

**Comment by skriss** [comment]
> Is it possible to cherry pick this to v1.28.x (if it's convenient)?

Yeah that should be possible, we'll likely do a 1.28 patch release around the time we release 1.29 (beginning of May)
