### ISSUE TITLE
RFI: Improved handling of HTTPProxy conflicts

### ISSUE THREAD

**Issue by rosskukulinski** [projectcontour/contour#640]
**Describe the solution you'd like**

Inspired by [an issue in Gimbal](https://github.com/heptio/gimbal/issues/209), I'd like to (open the discussion on how we might improve the user experience when one or more IngressRoutes conflict.

Contour's default behavior if two or more IngressRoutes attempt to define the same FQDN is to mark them all as invalid.  This can result in an entire domain being removed from the live routing configuration until the change is reverted.

While the `--root-ingress-namespaces` feature can be used to limit the number of users authorized to create root IngressRoutes, there still is the very real possibility that an administrator could accidentally cause a major outage.

What solutions are there to this problem and what's the impact of the necessary changes?

**Comment by rosskukulinski** [comment]
@davecheney @stevesloka @alexbrand for feedback

**Comment by stevesloka** [comment]
I think this issue needs some design or discussion about how to address. Contour does currently mark any IngressRoute / Proxy as invalid if the names duplicate. 

Could we maybe look at the resource verison and see which one is older and use that one?

**Comment by davecheney** [comment]
@stevesloka do you think we need to resolve this before 1.0 ships or can we tackle it afterwards?

**Comment by jmdelrosario-ti** [comment]
Hi, is there a plan to address this in the future? Or any recommended workaround / solution. Thanks
