### ISSUE TITLE
Per IP rate limit?

### ISSUE THREAD

**Issue by sabershahhoseini** [projectcontour/contour#6411]
Is there any way to apply per IP rate limit? Seems like local rate limits do not care about IP and only thing is they care is how many requests are given to upstream service.

I mean, if someone just bulk requests to my service, anyone else gets 429? It's not good!

**Comment by sunjayBhatia** [comment]
> Is there any way to apply per IP rate limit? Seems like local rate limits do not care about IP and only thing is they care is how many requests are given to upstream service.

Envoy's local rate limit filter does not offer more advanced mechanisms for filtering requests or applying different requests based on source IP

this can be achieved using global rate limiting and using the request source IP in a descriptor that the rate limit server applies a specialized rate limit for, see: https://projectcontour.io/docs/1.28/config/rate-limiting/#global-rate-limiting
