### ISSUE TITLE
Ability to query for Services referenced by an IngressRoute

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#647]
**Describe the solution you'd like**
Have an easy way to know what Services are referenced in an IngressRoute. 

One way to implement might be to automatically label the IngressRoute with services that they consume. By having label's on the IngressRoute we could do label queries across all IngressRoutes that are referencing a specific service. 

A downside is having Contour update existing services that it does not own.

**Comment by davecheney** [comment]
I’m going to push this to the unplanned milestone because I don’t see us looking at this before Contour 1.0.
