### ISSUE TITLE
Add a separate label for envoy or contour

### ISSUE THREAD

**Issue by yangyy93** [projectcontour/contour#6488]
**What question do you have?:**
The field PodAnnotations is now defined in the Spec of ContourDeployment, through which Annotations can be added to contour or envoy pods separately, but for Labels, there is no similar definition. I found that there was a PR (#5543) that implemented this function, but Closed due to merge of #5968.
Because of the merger of #5968, now we can either add annotations to envoy or contour separately, or add (same) annotations to both contour and envoy through gateway.infrastructure.annotation; I think it is a good idea to provide the ability to configure separate labels for envoy or contour for more flexible use.

**Comment by yangyy93** [comment]
@skriss @sunjayBhatia 
have any opinions on this issue?

**Comment by wilsonwu** [comment]
@skriss @sunjayBhatia any comments for this? We'd like to contribute it.
