### ISSUE TITLE
Add support for HTTP based external auth server

### ISSUE THREAD

**Issue by rajivmordani** [projectcontour/contour#6509]
Currently Contour supports only the gRPC mechanism for external auth. However a lot of open source IAM solutions support HTTP based external auth for envoy which is useful to integrate with. Need to add support for HTTP based external auth in contour in order to integrate with IAM providers like authelia, authentik etc.

**Comment by skriss** [comment]
A few initial references in the existing codebase:
- ExtensionService CRD definition: https://github.com/projectcontour/contour/blob/main/apis/projectcontour/v1alpha1/extensionservice.go
- conversion of ExtensionService CRD to "DAG" (internal model) representation: https://github.com/projectcontour/contour/blob/00a976a0431b162e8896958af14ef359979c23eb/internal/dag/extension_processor.go#L108-L149
- Generation of Envoy ExtAuthz filter config: https://github.com/projectcontour/contour/blob/00a976a0431b162e8896958af14ef359979c23eb/internal/envoy/v3/listener.go#L791-L827

**Comment by skriss** [comment]
We'll also need to look through https://www.envoyproxy.io/docs/envoy/v1.30.2/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#envoy-v3-api-msg-extensions-filters-http-ext-authz-v3-httpservice in detail and decide which fields need to be exposed via Contour config.

**Comment by sunjayBhatia** [comment]
Thanks for the issue!

Broad strokes first impression this should be a relatively simple addition, some thoughts on TODOs below:

*How users let Contour know their External Auth Service is HTTP and not gRPC*
- Add to `ExtensionService`
- Can possibly use the `Protocol` field/Service annotations: https://github.com/projectcontour/contour/blob/00a976a0431b162e8896958af14ef359979c23eb/apis/projectcontour/v1alpha1/extensionservice.go#L80-L85
- `ExtensionService` processing code: https://github.com/projectcontour/contour/blob/main/internal/dag/extension_processor.go

*Resulting Envoy Config needs a URI/hostname*
- See the `server_uri` field here: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#extensions-filters-http-ext-authz-v3-httpservice and the contained fields: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/http_uri.proto#envoy-v3-api-msg-config-core-v3-httpuri
- Should this be a new field added to `ExtensionService`? Reuse the SNI field from `UpstreamValidation`? https://github.com/projectcontour/contour/blob/00a976a0431b162e8896958af14ef359979c23eb/apis/projectcontour/v1alpha1/extensionservice.go#L78

*Integration testing*
- See: https://github.com/projectcontour/contour/blob/main/internal/featuretests/v3/authorization_test.go

*E2E Testing*
- Would be good to have some e2e tests added that validated some base functionality
- Similar to: https://github.com/projectcontour/contour/blob/main/test/e2e/httpproxy/external_auth_test.go

**Comment by rajivmordani** [comment]
Thanks Steve and Sunjay for the pointers. Let me look and circle back.
