### ISSUE TITLE
do we have cookie based routing for httpproxy?

### ISSUE THREAD

**Issue by chatwithruben** [projectcontour/contour#6510]
**What question do you have?:**
i have a use case where httpproxy should validate the cookie contents and route to particular service accordinly.

cookie name is "cookie"
inside cookie we have something like X-Service-version-v12 also in some cookies it might be X-Service-version-v13

so what we wanted is our httpproxy should be capable of reading for the cookie and route to particular service accordingly.

**Comment by sunjayBhatia** [comment]
Contour does not have cookie based request matching at this time, but we do support cookie based load balancing/session affinity to enable you to maintain a stateful session to an individual app instance, see the `RequestHash` or `Cookie` load balancing strategies documented here: https://projectcontour.io/docs/1.29/config/request-routing/#load-balancing-strategy

**Comment by chatwithruben** [comment]
@sunjayBhatia Can we consider this as a a good use case?
