### ISSUE TITLE
Support ingress.kubernetes.io/limit-whitelist

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#66]
Add support for `ingress.kubernetes.io/limit-whitelist`

**Comment by jpeach** [comment]
This annotation is specific to ingress-nginx, do we still want to support it?

**Comment by sunjayBhatia** [comment]
@projectcontour/maintainers superceded by https://github.com/projectcontour/contour/issues/3693 ?

**Comment by youngnick** [comment]
Definitely.
