### ISSUE TITLE
Improvement of OpenSSF Scorecard Score

### ISSUE THREAD

**Issue by harshitasao** [projectcontour/contour#6615]
Hi, I'm Harshita. I’m working with [CNCF and the Google Open Source Security Team for the GSoC 2024 term](https://github.com/cncf/mentoring/issues/1196). We are collaborating to enhance security practices across various CNCF projects. The goal is to improve security for all CNCF projects by both using OpenSSF Scorecards and implementing its security improvements.

As this project already has scorecard action, I'm here to increase the final score by going over each check. I've listed all of the checks where work needs to be done, in order of its criticality. I plan to submit each PR for each fix. Please let me know what you think and for which ones a PR is welcome that I will submit it ASAP.

**Current Score:** 9.0

**Scorecard report:** https://scorecard.dev/viewer/?uri=github.com/projectcontour/contour

Here's a few checks we can work on to improve the project's security posture:

- [ ] [Fuzzing](https://github.com/ossf/scorecard/blob/main/docs/checks.md#fuzzing): Score = 0
    - Integrating the project with OSS-Fuzz by following the instructions [here](https://google.github.io/oss-fuzz/). The most difficult one on the list, maintainers help, is highly appreciated. For example, helping in identifying the components where fuzz testing will be added.

/cc @joycebrum @diogoteles08 @pnacht @nate-double-u

**Comment by tsaarni** [comment]
Do you already have an idea what interfaces to fuzz? Contour itself interacts with the outside world via Kubernetes CRDs ([link](https://projectcontour.io/docs/main/config/api/), [link](https://kubernetes.io/docs/concepts/services-networking/ingress/), [link](https://gateway-api.sigs.k8s.io/)), and it has endpoints exposed over network: gRPC for [Envoy xDS](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol), REST for [metrics](https://projectcontour.io/docs/main/guides/prometheus/#contour-metrics).
