### ISSUE TITLE
Support envoy "safe retry on reset" policy value

### ISSUE THREAD

**Issue by geomacy** [projectcontour/contour#6770]
Envoy [v1.31.0](https://www.envoyproxy.io/docs/envoy/v1.31.0/version_history/v1.31/v1.31.0) introduced a new [safe retry on reset](https://github.com/envoyproxy/envoy/issues/10007) setting [reset-before-request](https://www.envoyproxy.io/docs/envoy/v1.31.0/configuration/http/http_filters/router_filter#config-http-filters-router-x-envoy-retry-on) . This release was included in Contour [v1.30.1](https://github.com/projectcontour/contour/releases#hd-a43394e4). 

We want to use retries but want to avoid where possible the risk of retrying API operations that it would be unsafe to retry.

This issue proposes an update to the Contour validation enum for retryPolicy [RetryOn](https://github.com/projectcontour/contour/blob/fbf2d589beb8eefde47b340073d813bd734fb127/apis/projectcontour/v1/httpproxy.go#L1149) to include the new policy value so that HTTPProxies can take advantage of this new, safer, behaviour.

From:
```go
// RetryOn is a string type alias with validation to ensure that the value is valid.
// +kubebuilder:validation:Enum="5xx";gateway-error;reset;connect-failure;retriable-4xx;refused-stream;retriable-status-codes;retriable-headers;cancelled;deadline-exceeded;internal;resource-exhausted;unavailable
type RetryOn string
```

to 
```go
// RetryOn is a string type alias with validation to ensure that the value is valid.
// +kubebuilder:validation:Enum="5xx";gateway-error;reset;reset-before-request;connect-failure;retriable-4xx;refused-stream;retriable-status-codes;retriable-headers;cancelled;deadline-exceeded;internal;resource-exhausted;unavailable
type RetryOn string
```

**Comment by tsaarni** [comment]
Thanks for spotting this @geomacy!  I opened a PR #6772.

**Comment by geomacy** [comment]
Many thanks @tsaarni!
