### ISSUE TITLE
Support ingress.kubernetes.io/auth-{type,secret,realm}

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#68]
Add support for 

- `ingress.kubernetes.io/auth-type`
- `ingress.kubernetes.io/auth-secret`
- `ingress.kubernetes.io/auth-realm`

Annotations.

**Comment by domhauton** [comment]
Without this there is no way to protect ingress endpoints with oauth2.

https://eng.fromatob.com/post/2017/02/lets-encrypt-oauth-2-and-kubernetes-ingress/

**Comment by swade1987** [comment]
Would be great to have the equivalent of 

```
nginx.ingress.kubernetes.io/auth-signin: "https://auth.oidc.example.co.uk/oauth2/start?rd=https://$host$request_uri$is_args$args"
nginx.ingress.kubernetes.io/auth-url: "https://auth.oidc.example.co.uk/oauth2/auth"
```

**Comment by sunjayBhatia** [comment]
@projectcontour/maintainers superceded by https://github.com/projectcontour/contour/issues/2664 ?

**Comment by travisghansen** [comment]
For anyone landing here my project now supports contour (so oauth, oidc, jwt, etc, etc). https://github.com/travisghansen/external-auth-server

**Comment by youngnick** [comment]
Yes, I think this one is superseded by #2664, thanks for finding this issue.

And that's great to hear @travisghansen, thanks! Being able to look at another implementation will be very helpful for the inline filter version.

**Comment by travisghansen** [comment]
Yeah, happy to work with you on design if it’s helpful.
