### ISSUE TITLE
Configuration to inject failures or delays

### ISSUE THREAD

**Issue by rosskukulinski** [projectcontour/contour#719]
**Describe the solution you'd like**

I would like to be able to configure artificial request failures and delays as part of my chaos engineering practice in production.  I want to make sure that sub-component availability/latency does not cause cascading issues.

**Anything else you would like to add:**

Envoy supports this behavior through the [Fault Injection filter](https://www.envoyproxy.io/docs/envoy/v1.7.0/configuration/http_filters/fault_filter)

**Comment by sunjayBhatia** [comment]
@projectcontour/maintainers do we anticipate doing this? seems like there are other tools that can be used to achieve similar outcomes without expanding contour's focus

**Comment by youngnick** [comment]
It does seem a bit out of scope for Contour, and we've never been asked for anything like it. I don't think it's likely we'll do this.

**Comment by sunjayBhatia** [comment]
Closing in that case ^
