### ISSUE TITLE
Support tls cert/key via file mount

### ISSUE THREAD

**Issue by ungureanuvladvictor** [projectcontour/contour#845]
**Describe the solution you'd like**

We would like to have the ability to specify a tls cert/key for a `SecureVirtualHost` via a file present in the filesystem of the contour container rather than using k8s secrets. From my investigation it looks like the `SecureVirtualHost` struct embeds the `Secret` struct which has a `v1.Secret` as a member.

**Comment by davecheney** [comment]
Thanks for raising this issue. There are a few design points to work through here.

1. If the filesystem is mounted onto the contour container, that would probably mean all users had the permission to edit the contour deployment descriptor to mount a filesystem. 

2. If there are multiple contour containers running, does the filesystem have to be mounted into all of them.

2a. Technically Envoy needs the certificates, not Contour, so the points above apply to the Envoy container.

Can you please explain a bit about your deployment scenario so I can better understand your requirements.

**Comment by ungureanuvladvictor** [comment]
Currently we do not have a deployment. We are researching to use contour+envoy instead of nginx ingress but the use of k8s secrets blocks us.

Currently we have a custom mechanism that based on certain annotations on the pod a mutating webhook attaches a volume + an init container grabbing secrets from a backend. Now we custom configured the nginx template and hardcoded the path to the cert and key for the vhost we have.

**Comment by davecheney** [comment]
We're going to do this another way, see #898
