### ISSUE TITLE
Can't get Contour to evenly schedule across nodes (not reliably)

### ISSUE THREAD

**Issue by lostllama** [projectcontour/contour#922]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I can't get Contour to reliably schedule onto multiple nodes, despite there being ample resources available with regards to resource requests (for Contour I modified the config to request 5m, and for Envoy 50m). This has caused issues with draining a node where my podDisruptionBudget doesn't seem to have been honoured at times.

**What did you expect to happen:**

I expect that, given the available resources, the two Contour instances should be evenly spread across both nodes.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Contour config:

    # This file is generated from the individual yaml files by deployment/render.sh.
    # Do not edit this file directly but instead edit the source files and
    # re-render.
    apiVersion: v1
    kind: Namespace
    metadata:
      name: heptio-contour
    ---
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: contour
      namespace: heptio-contour
    ---
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: ingressroutes.contour.heptio.com
      labels:
        component: ingressroute
    spec:
      group: contour.heptio.com
      version: v1beta1
      scope: Namespaced
      names:
        plural: ingressroutes
        kind: IngressRoute
      additionalPrinterColumns:
        - name: FQDN
          type: string
          description: Fully qualified domain name
          JSONPath: .spec.virtualhost.fqdn
        - name: TLS Secret
          type: string
          description: Secret with TLS credentials
          JSONPath: .spec.virtualhost.tls.secretName
        - name: First route
          type: string
          description: First routes defined
          JSONPath: .spec.routes[0].match
        - name: Status
          type: string
          description: The current status of the IngressRoute
          JSONPath: .status.currentStatus
        - name: Status Description
          type: string
          description: Description of the current status
          JSONPath: .status.description
      validation:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                virtualhost:
                  properties:
                    fqdn:
                      type: string
                      pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-z0-9]{2,}$
                    tls:
                      properties:
                        secretName:
                          type: string
                          pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ # DNS-1123 subdomain
                        minimumProtocolVersion:
                          type: string
                          enum:
                            - "1.3"
                            - "1.2"
                            - "1.1"
                strategy:
                  type: string
                  enum:
                    - RoundRobin
                    - WeightedLeastRequest
                    - Random
                    - RingHash
                    - Maglev
                healthCheck:
                  type: object
                  required:
                    - path
                  properties:
                    path:
                      type: string
                      pattern: ^\/.*$
                    intervalSeconds:
                      type: integer
                    timeoutSeconds:
                      type: integer
                    unhealthyThresholdCount:
                      type: integer
                    healthyThresholdCount:
                      type: integer
                routes:
                  type: array
                  items:
                    required:
                      - match
                    properties:
                      match:
                        type: string
                        pattern: ^\/.*$
                      delegate:
                        type: object
                        required:
                          - name
                        properties:
                          name:
                            type: string
                            pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ # DNS-1123 subdomain
                          namespace:
                            type: string
                            pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$ # DNS-1123 label
                      services:
                        type: array
                        items:
                          type: object
                          required:
                            - name
                            - port
                          properties:
                            name:
                              type: string
                              pattern: ^[a-z]([-a-z0-9]*[a-z0-9])?$ # DNS-1035 label
                            port:
                              type: integer
                            weight:
                              type: integer
                            strategy:
                              type: string
                              enum:
                                - RoundRobin
                                - WeightedLeastRequest
                                - Random
                                - RingHash
                                - Maglev
                            healthCheck:
                              type: object
                              required:
                                - path
                              properties:
                                path:
                                  type: string
                                  pattern: ^\/.*$
                                intervalSeconds:
                                  type: integer
                                timeoutSeconds:
                                  type: integer
                                unhealthyThresholdCount:
                                  type: integer
                                healthyThresholdCount:
                                  type: integer
    ---
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        app: contour
      name: contour
      namespace: heptio-contour
    spec:
      selector:
        matchLabels:
          app: contour
      replicas: 2
      template:
        metadata:
          labels:
            app: contour
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "8002"
            prometheus.io/path: "/stats"
            prometheus.io/format: "prometheus"
        spec:
          containers:
          - image: gcr.io/heptio-images/contour:master
            imagePullPolicy: Always
            name: contour
            command: ["contour"]
            args: ["serve", "--incluster"]
            resources:
              requests:
                cpu: "5m"
                
          - image: docker.io/envoyproxy/envoy-alpine:v1.8.0
            name: envoy
            ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
            command: ["envoy"]
            args:
            - --config-path /config/contour.yaml
            - --service-cluster cluster0
            - --service-node node0
            - --log-level info
            - --v2-config-only
            readinessProbe:
              httpGet:
                path: /healthz
                port: 8002
              initialDelaySeconds: 3
              periodSeconds: 3
            resources:
              requests:
                cpu: "50m"
            volumeMounts:
            - name: contour-config
              mountPath: /config
            lifecycle:
              preStop:
                exec:
                  command: ["wget", "-qO-", "http://localhost:9001/healthcheck/fail"] 
          initContainers:
          - image: gcr.io/heptio-images/contour:master
            imagePullPolicy: Always
            name: envoy-initconfig
            command: ["contour"]
            args:
            - bootstrap
            # Uncomment the statsd-enable to enable statsd metrics
            #- --statsd-enable
            # Uncomment to set a custom stats emission address and port
            #- --stats-address=0.0.0.0
            #- --stats-port=8002
            - /config/contour.yaml
            volumeMounts:
            - name: contour-config
              mountPath: /config
          volumes:
          - name: contour-config
            emptyDir: {}
          dnsPolicy: ClusterFirst
          serviceAccountName: contour
          terminationGracePeriodSeconds: 30
          # The affinity stanza below tells Kubernetes to try hard not to place 2 of
          # these pods on the same node.
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: contour
                  topologyKey: kubernetes.io/hostname
    ---
    apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    metadata:
      name: contour
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: contour
    subjects:
    - kind: ServiceAccount
      name: contour
      namespace: heptio-contour
    ---
    apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
    metadata:
      name: contour
    rules:
    - apiGroups:
      - ""
      resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
      verbs:
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - nodes
      verbs:
      - get
    - apiGroups:
      - ""
      resources:
      - services
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - extensions
      resources:
      - ingresses
      verbs:
      - get
      - list
      - watch
    - apiGroups: ["contour.heptio.com"]
      resources: ["ingressroutes"]
      verbs:
      - get
      - list
      - watch
      - put
      - post
      - patch
    ---
    apiVersion: v1
    kind: Service
    metadata:
     name: contour
     namespace: heptio-contour
     annotations:
      # This annotation puts the AWS ELB into "TCP" mode so that it does not
      # do HTTP negotiation for HTTPS connections at the ELB edge.
      # The downside of this is the remote IP address of all connections will
      # appear to be the internal address of the ELB. See docs/proxy-proto.md
      # for information about enabling the PROXY protocol on the ELB to recover
      # the original remote IP address.
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    spec:
     ports:
     - port: 80
       name: http
       protocol: TCP
       targetPort: 8080
     - port: 443
       name: https
       protocol: TCP
       targetPort: 8443
     selector:
       app: contour
     type: LoadBalancer
    ---

PodDisruptionBudget:

    apiVersion: policy/v1beta1
    kind: PodDisruptionBudget
    metadata:
      name: "contour-disruption-budget"
      namespace: heptio-contour
      labels:
        app: "contour"
    spec:
      maxUnavailable: 1
      selector:
        matchLabels:
          app: "contour"

Autoscaler:

    apiVersion: autoscaling/v1
    kind: HorizontalPodAutoscaler
    metadata:
      name: contour
      namespace: heptio-contour
    spec:
      maxReplicas: 10
      minReplicas: 2
      scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: contour
      targetCPUUtilizationPercentage: 70

Nodes (`kubectl get nodes -o wide --show-labels --all-namespaces`):

	gke-clustername-clu-default-pool-cb97b8f2-7qxr   Ready     <none>    7d        v1.11.6-gke.2                 Container-Optimized OS from Google   4.14.65+         docker://17.3.2     beta.kubernetes.io/arch=amd64,beta.kubernetes.io/fluentd-ds-ready=true,beta.kubernetes.io/instance-type=custom-4-10240,beta.kubernetes.io/os=linux,cloud.google.com/gke-nodepool=default-pool,cloud.google.com/gke-os-distribution=cos,failure-domain.beta.kubernetes.io/region=asia-northeast1,failure-domain.beta.kubernetes.io/zone=asia-northeast1-a,kubernetes.io/hostname=gke-clustername-clu-default-pool-cb97b8f2-7qxr
	gke-clustername-clu-default-pool-cb97b8f2-zfnt   Ready     <none>    7d        v1.11.6-gke.2                 Container-Optimized OS from Google   4.14.65+         docker://17.3.2     beta.kubernetes.io/arch=amd64,beta.kubernetes.io/fluentd-ds-ready=true,beta.kubernetes.io/instance-type=custom-4-10240,beta.kubernetes.io/os=linux,cloud.google.com/gke-nodepool=default-pool,cloud.google.com/gke-os-distribution=cos,failure-domain.beta.kubernetes.io/region=asia-northeast1,failure-domain.beta.kubernetes.io/zone=asia-northeast1-a,kubernetes.io/hostname=gke-clustername-clu-default-pool-cb97b8f2-zfnt

Pods (`kubectl get pods -o wide --show-labels --all-namespaces`):

	heptio-contour    contour-686c5557c4-7fw28                                         2/2       Running     0          5d        10.8.2.45    gke-clustername-clu-default-pool-cb97b8f2-zfnt   app=contour,pod-template-hash=2427111370
	heptio-contour    contour-686c5557c4-pcrct                                         2/2       Running     0          5d        10.8.2.46    gke-clustername-clu-default-pool-cb97b8f2-zfnt   app=contour,pod-template-hash=2427111370

Information from `kubectl describe nodes`:

	gke-clustername-clu-default-pool-cb97b8f2-7qxr:
	
		Allocatable:
		 cpu:                3920m
		 ephemeral-storage:  18858075679
		 hugepages-2Mi:      0
		 memory:             8063308Ki
		 pods:               110
		 
	    Namespace                  Name                                                              CPU Requests  CPU Limits  Memory Requests  Memory Limits
	    ---------                  ----                                                              ------------  ----------  ---------------  -------------
	    cert-manager               cert-manager-85f8c98f85-pwsq2                                     0 (0%)        0 (0%)      0 (0%)           0 (0%)
	    kube-system                event-exporter-v0.2.3-85644fcdf-rdf7b                             0 (0%)        0 (0%)      0 (0%)           0 (0%)
	    kube-system                fluentd-gcp-scaler-8b674f786-6rf75                                0 (0%)        0 (0%)      0 (0%)           0 (0%)
	    kube-system                fluentd-gcp-v3.2.0-mwsdc                                          100m (2%)     1 (25%)     200Mi (2%)       500Mi (6%)
	    kube-system                kube-dns-548976df6c-dnkmf                                         260m (6%)     0 (0%)      110Mi (1%)       170Mi (2%)
	    kube-system                kube-dns-548976df6c-f48lq                                         260m (6%)     0 (0%)      110Mi (1%)       170Mi (2%)
	    kube-system                kube-dns-autoscaler-67c97c87fb-87pzc                              20m (0%)      0 (0%)      10Mi (0%)        0 (0%)
	    kube-system                kube-proxy-gke-clustername-clu-default-pool-cb97b8f2-7qxr         100m (2%)     0 (0%)      0 (0%)           0 (0%)
	    kube-system                l7-default-backend-7ff48cffd7-pmwpz                               10m (0%)      10m (0%)    20Mi (0%)        20Mi (0%)
	    kube-system                metrics-server-v0.2.1-fd596d746-pjfh4                             53m (1%)      148m (3%)   154Mi (1%)       404Mi (5%)
	    kube-system                tiller-deploy-597c48f967-kfj2n                                    0 (0%)        0 (0%)      0 (0%)           0 (0%)
	    production                 production-api1-blue-64bc979557-5f2pm                             300m (7%)     0 (0%)      700Mi (8%)       0 (0%)
	    production                 production-api1-green-6f9988c7df-h6rx2                            300m (7%)     0 (0%)      700Mi (8%)       0 (0%)
	    production                 production-api2-blue-58d7645959-fkhv5                             800m (20%)    0 (0%)      2000Mi (25%)     0 (0%)
	    production                 production-background-worker-blue-56c5cc4bb-5s7gx                 300m (7%)     0 (0%)      500Mi (6%)       0 (0%)
		
    gke-clustername-clu-default-pool-cb97b8f2-zfnt:
	
		Allocatable:
		 cpu:                3920m
		 ephemeral-storage:  18858075679
		 hugepages-2Mi:      0
		 memory:             8063308Ki
		 pods:               110
		 
	    Namespace                  Name                                                              CPU Requests  CPU Limits  Memory Requests  Memory Limits
	    ---------                  ----                                                              ------------  ----------  ---------------  -------------
	    heptio-contour             contour-686c5557c4-7fw28                                          55m (1%)      0 (0%)      0 (0%)           0 (0%)
	    heptio-contour             contour-686c5557c4-pcrct                                          55m (1%)      0 (0%)      0 (0%)           0 (0%)
	    kube-system                fluentd-gcp-v3.2.0-szthk                                          100m (2%)     1 (25%)     200Mi (2%)       500Mi (6%)
	    kube-system                heapster-v1.6.0-beta.1-ff654688-vvz76                             138m (3%)     138m (3%)   301656Ki (3%)    301656Ki (3%)
	    kube-system                kube-proxy-gke-clustername-clu-default-pool-cb97b8f2-zfnt         100m (2%)     0 (0%)      0 (0%)           0 (0%)
	    production                 production-api1-green-6f9988c7df-cd4gx                            300m (7%)     0 (0%)      700Mi (8%)       0 (0%)
	    production                 production-api2-blue-58d7645959-zd2wc                             800m (20%)    0 (0%)      2000Mi (25%)     0 (0%)
	    production                 production-api2-green-7b8749f4fd-2jhgk                            800m (20%)    0 (0%)      2000Mi (25%)     0 (0%)
	    production                 production-background-worker-blue-56c5cc4bb-f9zx9                 300m (7%)     0 (0%)      500Mi (6%)       0 (0%)

**Environment:**

- Contour version: v0.10.0-rc.1
- Kubernetes version: (use `kubectl version`): 1.11.6-gke.2
- Kubernetes installer & version: ?
- Cloud provider or hardware configuration: GKE
- OS (e.g. from `/etc/os-release`): Not sure

**Comment by lostllama** [comment]
@stevesloka Let me know if you need any more information. Thanks!

**Comment by lostllama** [comment]
Today I tried to scale contour to 4 replicas (instead of 2) and ended up with this:

	gke-clustername-clu-default-pool-cb97b8f2-zfnt   contour-686c5557c4-7fw28
	gke-clustername-clu-default-pool-cb97b8f2-zfnt   contour-686c5557c4-92shw
	gke-clustername-clu-default-pool-cb97b8f2-zfnt   contour-686c5557c4-pcrct
	gke-clustername-clu-default-pool-cb97b8f2-7qxr   contour-686c5557c4-rs8hb

It seems that 1 of the new replicas also scheduled on the same node as the existing 2, instead of aiming for the other node.

**Comment by rochacon** [comment]
@lostllama you're using the `pod.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution` rule, which will make Kubernetes scheduler _try_ to spread the pods evenly in the clusters but won't *require* the even spread. This allows you to grow your Contour replica count independently to your node count.

To guarantee the spread and never place 2 Contour pods in the same node, you may switch to `pod.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution` or to a `DaemonSet` setup (which will always place a Contour instance on each node). Check `kubectl explain pod.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution` for more info on the specific rule.

**Comment by lostllama** [comment]
@rochacon I appreciate that it isn't guaranteed, but the Contour config does say that it will try hard. When you have two nodes with ample resources, and it puts 3 on the same node before putting any on another node, it doesn't seem to be trying at all.

**Comment by SDBrett** [comment]
PR: #1428 added anti affinity rules for the contour pods to the `examples/contour/03-contour.yaml` manifest.

This solves the issue of contour pods being scheduled on the same node.

Can this issue be closed?

**Comment by lostllama** [comment]
@SDBrett I believe so.
