### ISSUE TITLE
Update Ingress Resources apiVersion before K8s v1.18 

### ISSUE THREAD

**Issue by VMmore** [projectcontour/contour#973]
Ingress resources are available via networking.k8s.io/v1beta1 as of v1.14. Ingress resources in extensions/v1beta1 are deprecated and will no longer be served in v1.18. Existing persisted data can be retrieved/updated via the networking.k8s.io/v1beta1 API.

Even though those timelines are 6-12 months away, it's never to early to sweep manifests and client API calls that need to be migrated.

- Kubernetes version: (use `kubectl version`): v1.14 (need solution by v1.18)

**Comment by davecheney** [comment]
Moving to the unplanned milestone, we'll tackle this post Contour 1.0 and do a backport in the current stable release if necessary.

**Comment by stevesloka** [comment]
We need to prioritize this work sooner. The `extensions/v1beta1` api group is deprecated in v1.16 which will ship soon: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by davecheney** [comment]
Duplicate of #1633
