### ISSUE TITLE
Enable SSO capabilities

### ISSUE THREAD

**Issue by swade1987** [projectcontour/contour#986]
**What functionality I would like:**
Currently I have a Single Sign On (SSO) implementation in AWS (using a classic ELB) using:
- Nginx Ingress Controller
- OAuth2 Proxy
- Dex

However, I would like to move to an Envoy based ingress controller leveraging a more modern load-balancer (ideally an NLB).  However, it does not look like an equivalent to the following annotations are supported at present:

```
nginx.ingress.kubernetes.io/auth-signin:
nginx.ingress.kubernetes.io/auth-url:
```
**Environment:**
N/A

**Comment by davecheney** [comment]
Thank you for raising this issue. Sadly I don't see anyone being able to work on this before our 1.0 release in Oct/Nov. I am going to assign this to the unschedule milestone so we don't loose it, but to be honest that we're not planning on implementing this feature at the moment.

**Comment by travisghansen** [comment]
For those interested and when the time comes that `contour` supports external/forward auth: https://github.com/heptio/contour/issues/432#issuecomment-503142288

**Comment by michmike** [comment]
we will do the work in the ticket #432 . that's the extent of the external auth work we will undertake in contour

**Comment by jpeach** [comment]
Duplicate of #432
